/*
 * Tamil course content — data only.
 *
 * The app GENERATES exercises from these lists, so to add material you just
 * add words or sentences here; every practice mode picks them up automatically.
 *
 *   TOPICS   — the categories shown on the home screen.
 *   VOCAB    — { ta, tr, en, topic } single words / short phrases.
 *   SENTENCES— { ta, tr, en, topic, words:[{ta,tr}] } for translation & building.
 *   ALPHABET — the letters, exposed to the engine as vocab-like items.
 *
 * tr = transliteration (light scholarly scheme: ā ī ū ḷ ṇ ṟ ṭ ḻ ṅ ñ …).
 */

/* ------------------------------- Topics -------------------------------- */
const TOPICS = [
  { id: "alphabet",   title: "Alphabet",        icon: "🔤", color: "#58cc02", kind: "alpha" },
  { id: "greetings",  title: "Greetings",       icon: "👋", color: "#1cb0f6", kind: "vocab" },
  { id: "numbers",    title: "Numbers",         icon: "🔢", color: "#ff9600", kind: "vocab" },
  { id: "family",     title: "Family & People", icon: "👪", color: "#ce82ff", kind: "vocab" },
  { id: "pronouns",   title: "Pronouns",        icon: "🧑", color: "#ff4b4b", kind: "vocab" },
  { id: "food",       title: "Food & Drink",    icon: "🍚", color: "#e6b800", kind: "vocab" },
  { id: "animals",    title: "Animals",         icon: "🐘", color: "#2b70c9", kind: "vocab" },
  { id: "colors",     title: "Colours",         icon: "🎨", color: "#ff86d0", kind: "vocab" },
  { id: "body",       title: "The Body",        icon: "✋", color: "#00cd9c", kind: "vocab" },
  { id: "home",       title: "Home & Objects",  icon: "🏠", color: "#a560ff", kind: "vocab" },
  { id: "nature",     title: "Nature",          icon: "🌳", color: "#78c800", kind: "vocab" },
  { id: "time",       title: "Time & Days",     icon: "📅", color: "#f0a020", kind: "vocab" },
  { id: "verbs",      title: "Verbs",           icon: "🏃", color: "#e64b4b", kind: "vocab" },
  { id: "adjectives", title: "Adjectives",      icon: "⭐", color: "#1fb0d6", kind: "vocab" },
  { id: "places",     title: "Places",          icon: "📍", color: "#9b59b6", kind: "vocab" },
  { id: "questions",  title: "Question Words",  icon: "❓", color: "#e67e22", kind: "vocab" },
  { id: "common",     title: "Common Words",    icon: "📚", color: "#5b6bff", kind: "vocab" },
  { id: "sentences",  title: "Sentences",       icon: "📝", color: "#2b70c9", kind: "sentence" },
];

/* ------------------------------ Alphabet ------------------------------- */
// Exposed as items { ta, tr, en } where en is the romanised sound.
const VOWELS = [
  ["அ","a"],["ஆ","aa"],["இ","i"],["ஈ","ii"],["உ","u"],["ஊ","uu"],
  ["எ","e"],["ஏ","ee"],["ஐ","ai"],["ஒ","o"],["ஓ","oo"],["ஔ","au"],
];
const CONSONANTS = [
  ["க்","k"],["ங்","ṅ"],["ச்","c"],["ஞ்","ñ"],["ட்","ṭ"],["ண்","ṇ"],
  ["த்","t"],["ந்","n"],["ப்","p"],["ம்","m"],["ய்","y"],["ர்","r"],
  ["ல்","l"],["வ்","v"],["ழ்","ḻ"],["ள்","ḷ"],["ற்","ṟ"],["ன்","ṉ"],
];
const ALPHABET = {
  vowels: VOWELS.map(([ta, tr]) => ({ ta, tr, en: tr, topic: "alphabet" })),
  consonants: CONSONANTS.map(([ta, tr]) => ({ ta, tr, en: tr, topic: "alphabet" })),
};

/* ------------------------------ Vocabulary ----------------------------- */
const V = (topic, rows) => rows.map(([ta, tr, en]) => ({ ta, tr, en, topic }));

const VOCAB = [].concat(
  V("greetings", [
    ["வணக்கம்", "vaṇakkam", "hello / goodbye"],
    ["நன்றி", "naṉṟi", "thank you"],
    ["ஆம்", "aam", "yes"],
    ["இல்லை", "illai", "no"],
    ["சரி", "sari", "okay"],
    ["தயவு செய்து", "tayavu ceytu", "please"],
    ["மன்னிக்கவும்", "maṉṉikkavum", "sorry / excuse me"],
    ["நலம்", "nalam", "fine / well"],
    ["வரவேற்பு", "varavēṟpu", "welcome"],
    ["பெயர்", "peyar", "name"],
    ["காலை வணக்கம்", "kālai vaṇakkam", "good morning"],
    ["மாலை வணக்கம்", "mālai vaṇakkam", "good evening"],
    ["இனிய இரவு", "iṉiya iravu", "good night"],
    ["போய் வருகிறேன்", "pōy varukiṟēṉ", "goodbye (I'll go and come)"],
    ["மீண்டும் சந்திப்போம்", "mīṇṭum cantippōm", "see you again"],
    ["எப்படி இருக்கிறீர்கள்", "eppaṭi irukkiṟīrkaḷ", "how are you"],
    ["நலமா", "nalamā", "are you well?"],
    ["பரவாயில்லை", "paravāyillai", "no problem / it's okay"],
    ["வாழ்த்துக்கள்", "vāḻttukkaḷ", "congratulations / greetings"],
    ["வாருங்கள்", "vāruṅkaḷ", "please come"],
    ["உட்காருங்கள்", "uṭkāruṅkaḷ", "please sit"],
    ["மகிழ்ச்சி", "makiḻcci", "happiness / pleasure"],
  ]),
  V("numbers", [
    ["பூஜ்யம்", "pūjyam", "zero"],
    ["ஒன்று", "oṉṟu", "one"],
    ["இரண்டு", "iraṇṭu", "two"],
    ["மூன்று", "mūṉṟu", "three"],
    ["நான்கு", "nāṉku", "four"],
    ["ஐந்து", "aindu", "five"],
    ["ஆறு", "āṟu", "six"],
    ["ஏழு", "ēḻu", "seven"],
    ["எட்டு", "eṭṭu", "eight"],
    ["ஒன்பது", "oṉpatu", "nine"],
    ["பத்து", "pattu", "ten"],
    ["இருபது", "irupatu", "twenty"],
    ["முப்பது", "muppatu", "thirty"],
    ["பதினொன்று", "patiṉoṉṟu", "eleven"],
    ["பன்னிரண்டு", "paṉṉiraṇṭu", "twelve"],
    ["பதிமூன்று", "patimūṉṟu", "thirteen"],
    ["பதினான்கு", "patiṉāṉku", "fourteen"],
    ["பதினைந்து", "patiṉaintu", "fifteen"],
    ["பதினாறு", "patiṉāṟu", "sixteen"],
    ["பதினேழு", "patiṉēḻu", "seventeen"],
    ["பதினெட்டு", "patiṉeṭṭu", "eighteen"],
    ["பத்தொன்பது", "pattoṉpatu", "nineteen"],
    ["நாற்பது", "nāṟpatu", "forty"],
    ["அறுபது", "aṟupatu", "sixty"],
    ["எழுபது", "eḻupatu", "seventy"],
    ["எண்பது", "eṇpatu", "eighty"],
    ["தொண்ணூறு", "toṇṇūṟu", "ninety"],
    ["ஆயிரம்", "āyiram", "thousand"],
    ["இலட்சம்", "ilaṭcam", "hundred thousand (lakh)"],
    ["ஐம்பது", "aimpatu", "fifty"],
    ["நூறு", "nūṟu", "hundred"],
    ["முதல்", "mutal", "first"],
    ["இரண்டாவது", "iraṇṭāvatu", "second"],
    ["மூன்றாவது", "mūṉṟāvatu", "third"],
    ["பாதி", "pāti", "half"],
  ]),
  V("family", [
    ["அம்மா", "ammā", "mother"],
    ["அப்பா", "appā", "father"],
    ["அண்ணா", "aṇṇā", "elder brother"],
    ["தம்பி", "tampi", "younger brother"],
    ["அக்கா", "akkā", "elder sister"],
    ["தங்கை", "taṅkai", "younger sister"],
    ["தாத்தா", "tāttā", "grandfather"],
    ["பாட்டி", "pāṭṭi", "grandmother"],
    ["மகன்", "makaṉ", "son"],
    ["மகள்", "makaḷ", "daughter"],
    ["நண்பன்", "naṇpaṉ", "friend (m)"],
    ["நண்பி", "naṇpi", "friend (f)"],
    ["குழந்தை", "kuḻantai", "child / baby"],
    ["பெண்", "peṇ", "woman / girl"],
    ["ஆண்", "āṇ", "man / male"],
    ["கணவன்", "kaṇavaṉ", "husband"],
    ["மனைவி", "maṉaivi", "wife"],
    ["மாமா", "māmā", "uncle (maternal)"],
    ["அத்தை", "attai", "aunt (paternal)"],
    ["சித்தப்பா", "cittappā", "uncle (younger paternal)"],
    ["பெரியப்பா", "periyappā", "uncle (elder paternal)"],
    ["மாமியார்", "māmiyār", "mother-in-law"],
    ["மாமனார்", "māmaṉār", "father-in-law"],
    ["பேரன்", "pēraṉ", "grandson"],
    ["பேத்தி", "pētti", "granddaughter"],
    ["உறவினர்", "uṟaviṉar", "relative"],
    ["மக்கள்", "makkaḷ", "people"],
    ["குடும்பம்", "kuṭumpam", "family"],
  ]),
  V("pronouns", [
    ["நான்", "nāṉ", "I"],
    ["நீ", "nī", "you (informal)"],
    ["நீங்கள்", "nīṅkaḷ", "you (polite)"],
    ["அவன்", "avaṉ", "he"],
    ["அவள்", "avaḷ", "she"],
    ["அவர்", "avar", "he / she (respect)"],
    ["அது", "atu", "it"],
    ["நாங்கள்", "nāṅkaḷ", "we"],
    ["அவர்கள்", "avarkaḷ", "they"],
    ["இது", "itu", "this"],
    ["அந்த", "anta", "that"],
  ]),
  V("food", [
    ["சாப்பாடு", "sāppāṭu", "food / meal"],
    ["தண்ணீர்", "taṇṇīr", "water"],
    ["பால்", "pāl", "milk"],
    ["சாதம்", "sātam", "rice (cooked)"],
    ["ரொட்டி", "roṭṭi", "bread"],
    ["பழம்", "paḻam", "fruit"],
    ["வாழைப்பழம்", "vāḻaippaḻam", "banana"],
    ["காய்கறி", "kāykaṟi", "vegetable"],
    ["முட்டை", "muṭṭai", "egg"],
    ["மீன்", "mīṉ", "fish"],
    ["தேநீர்", "tēnīr", "tea"],
    ["காபி", "kāpi", "coffee"],
    ["சர்க்கரை", "carkkarai", "sugar"],
    ["உப்பு", "uppu", "salt"],
    ["இனிப்பு", "iṉippu", "sweet"],
    ["காரம்", "kāram", "spicy"],
  ]),
  V("animals", [
    ["நாய்", "nāy", "dog"],
    ["பூனை", "pūṉai", "cat"],
    ["மாடு", "māṭu", "cow"],
    ["குதிரை", "kutirai", "horse"],
    ["யானை", "yāṉai", "elephant"],
    ["புலி", "puli", "tiger"],
    ["சிங்கம்", "ciṅkam", "lion"],
    ["பறவை", "paṟavai", "bird"],
    ["எலி", "eli", "mouse / rat"],
    ["குரங்கு", "kuraṅku", "monkey"],
    ["ஆடு", "āṭu", "goat"],
    ["கோழி", "kōḻi", "chicken"],
    ["பாம்பு", "pāmpu", "snake"],
  ]),
  V("colors", [
    ["சிவப்பு", "civappu", "red"],
    ["நீலம்", "nīlam", "blue"],
    ["பச்சை", "paccai", "green"],
    ["மஞ்சள்", "mañcaḷ", "yellow"],
    ["கருப்பு", "karuppu", "black"],
    ["வெள்ளை", "veḷḷai", "white"],
    ["ஆரஞ்சு", "ārañcu", "orange"],
    ["இளஞ்சிவப்பு", "iḷañcivappu", "pink"],
    ["பழுப்பு", "paḻuppu", "brown"],
    ["ஊதா", "ūtā", "purple"],
  ]),
  V("body", [
    ["தலை", "talai", "head"],
    ["கண்", "kaṇ", "eye"],
    ["காது", "kātu", "ear"],
    ["மூக்கு", "mūkku", "nose"],
    ["வாய்", "vāy", "mouth"],
    ["கை", "kai", "hand / arm"],
    ["கால்", "kāl", "leg / foot"],
    ["விரல்", "viral", "finger"],
    ["முடி", "muṭi", "hair"],
    ["பல்", "pal", "tooth"],
    ["வயிறு", "vayiṟu", "stomach"],
    ["இதயம்", "itayam", "heart"],
  ]),
  V("home", [
    ["வீடு", "vīṭu", "house"],
    ["கதவு", "katavu", "door"],
    ["ஜன்னல்", "jaṉṉal", "window"],
    ["மேசை", "mēcai", "table"],
    ["நாற்காலி", "nāṟkāli", "chair"],
    ["கட்டில்", "kaṭṭil", "bed"],
    ["விளக்கு", "viḷakku", "lamp"],
    ["புத்தகம்", "puttakam", "book"],
    ["பேனா", "pēṉā", "pen"],
    ["கடிகாரம்", "kaṭikāram", "clock"],
    ["சாவி", "cāvi", "key"],
    ["உடை", "uṭai", "clothes"],
    ["காலணி", "kālaṇi", "shoe"],
  ]),
  V("nature", [
    ["சூரியன்", "cūriyaṉ", "sun"],
    ["சந்திரன்", "cantiraṉ", "moon"],
    ["நட்சத்திரம்", "naṭcattiram", "star"],
    ["வானம்", "vāṉam", "sky"],
    ["மழை", "maḻai", "rain"],
    ["காற்று", "kāṟṟu", "wind / air"],
    ["மரம்", "maram", "tree"],
    ["பூ", "pū", "flower"],
    ["இலை", "ilai", "leaf"],
    ["நதி", "nati", "river"],
    ["கடல்", "kaṭal", "sea"],
    ["மலை", "malai", "mountain"],
    ["நெருப்பு", "neruppu", "fire"],
    ["பூமி", "pūmi", "earth"],
  ]),
  V("time", [
    ["நாள்", "nāḷ", "day"],
    ["வாரம்", "vāram", "week"],
    ["மாதம்", "mātam", "month"],
    ["வருடம்", "varuṭam", "year"],
    ["இன்று", "iṉṟu", "today"],
    ["நேற்று", "nēṟṟu", "yesterday"],
    ["நாளை", "nāḷai", "tomorrow"],
    ["காலை", "kālai", "morning"],
    ["மதியம்", "matiyam", "noon"],
    ["மாலை", "mālai", "evening"],
    ["இரவு", "iravu", "night"],
    ["மணி", "maṇi", "hour / o'clock"],
    ["திங்கள்", "tiṅkaḷ", "Monday"],
    ["செவ்வாய்", "cevvāy", "Tuesday"],
    ["புதன்", "putaṉ", "Wednesday"],
    ["வியாழன்", "viyāḻaṉ", "Thursday"],
    ["வெள்ளி", "veḷḷi", "Friday"],
    ["சனி", "caṉi", "Saturday"],
    ["ஞாயிறு", "ñāyiṟu", "Sunday"],
  ]),
  V("verbs", [
    ["சாப்பிடு", "sāppiṭu", "eat"],
    ["குடி", "kuṭi", "drink"],
    ["போ", "pō", "go"],
    ["வா", "vā", "come"],
    ["படி", "paṭi", "read / study"],
    ["எழுது", "eḻutu", "write"],
    ["பார்", "pār", "see / look"],
    ["கேள்", "kēḷ", "hear / ask"],
    ["பேசு", "pēcu", "speak"],
    ["சொல்", "col", "say / tell"],
    ["செய்", "cey", "do / make"],
    ["கொடு", "koṭu", "give"],
    ["எடு", "eṭu", "take"],
    ["வாங்கு", "vāṅku", "buy"],
    ["தூங்கு", "tūṅku", "sleep"],
    ["நட", "naṭa", "walk"],
    ["ஓடு", "ōṭu", "run"],
    ["உட்கார்", "uṭkār", "sit"],
    ["விளையாடு", "viḷaiyāṭu", "play"],
    ["நேசி", "nēci", "love"],
    ["விரும்பு", "virumpu", "like / want"],
    ["தெரி", "teri", "know"],
    ["புரி", "puri", "understand"],
    ["கற்று", "kaṟṟu", "learn"],
  ]),
  V("adjectives", [
    ["பெரிய", "periya", "big"],
    ["சிறிய", "ciṟiya", "small"],
    ["நல்ல", "nalla", "good"],
    ["கெட்ட", "keṭṭa", "bad"],
    ["புதிய", "putiya", "new"],
    ["பழைய", "paḻaiya", "old"],
    ["நீளமான", "nīḷamāṉa", "long"],
    ["உயரமான", "uyaramāṉa", "tall"],
    ["வேகமான", "vēkamāṉa", "fast"],
    ["மெதுவான", "metuvāṉa", "slow"],
    ["சூடான", "cūṭāṉa", "hot"],
    ["குளிரான", "kuḷirāṉa", "cold"],
    ["அழகான", "aḻakāṉa", "beautiful"],
    ["கடினமான", "kaṭiṉamāṉa", "difficult"],
    ["எளிதான", "eḷitāṉa", "easy"],
  ]),
  V("places", [
    ["பள்ளி", "paḷḷi", "school"],
    ["மருத்துவமனை", "maruttuvamaṉai", "hospital"],
    ["கடை", "kaṭai", "shop"],
    ["சந்தை", "cantai", "market"],
    ["கோயில்", "kōyil", "temple"],
    ["வங்கி", "vaṅki", "bank"],
    ["நூலகம்", "nūlakam", "library"],
    ["உணவகம்", "uṇavakam", "restaurant"],
    ["பூங்கா", "pūṅkā", "park"],
    ["நகரம்", "nakaram", "city"],
    ["கிராமம்", "kirāmam", "village"],
    ["நாடு", "nāṭu", "country"],
    ["சாலை", "cālai", "road / street"],
  ]),
  V("questions", [
    ["என்ன", "eṉṉa", "what"],
    ["யார்", "yār", "who"],
    ["எங்கே", "eṅkē", "where"],
    ["எப்போது", "eppōtu", "when"],
    ["ஏன்", "ēṉ", "why"],
    ["எப்படி", "eppaṭi", "how"],
    ["எத்தனை", "ettaṉai", "how many"],
    ["எவ்வளவு", "evvaḷavu", "how much"],
    ["எது", "etu", "which"],
  ]),
  V("common", [
    ["இல்லை", "illai", "not/no"],
    ["தான்", "tāṉ", "just/indeed (emphatic)"],
    ["என்று", "eṉṟu", "that (quotative)"],
    ["மற்றும்", "maṟṟum", "and"],
    ["ஆனால்", "āṉāl", "but"],
    ["அல்லது", "allatu", "or"],
    ["கூட", "kūṭa", "also/even"],
    ["மட்டும்", "maṭṭum", "only"],
    ["மிகவும்", "mikavum", "very"],
    ["ரொம்ப", "rompa", "very/a lot"],
    ["என்றால்", "eṉṟāl", "if"],
    ["ஏனென்றால்", "ēṉeṉṟāl", "because"],
    ["பிறகு", "piṟaku", "then/after"],
    ["அப்புறம்", "appuṟam", "then/afterwards"],
    ["இல்", "il", "in/at"],
    ["க்கு", "kku", "to/for"],
    ["இருந்து", "iruntu", "from"],
    ["உடன்", "uṭaṉ", "with"],
    ["பற்றி", "paṟṟi", "about"],
    ["இல்லாமல்", "illāmal", "without"],
    ["மேல்", "mēl", "on/above"],
    ["கீழ்", "kīḻ", "under/below"],
    ["வரை", "varai", "until/up to"],
    ["போல்", "pōl", "like/as"],
    ["உள்ளே", "uḷḷē", "inside"],
    ["வெளியே", "veḷiyē", "outside"],
    ["முன்", "muṉ", "before/in front"],
    ["பின்", "piṉ", "after/behind"],
    ["அருகில்", "arukil", "near"],
    ["பக்கம்", "pakkam", "toward/side"],
    ["இடையே", "iṭaiyē", "between"],
    ["நடுவில்", "naṭuvil", "in the middle"],
    ["ஆகவே", "ākavē", "so/therefore"],
    ["எனவே", "eṉavē", "therefore"],
    ["அதனால்", "ataṉāl", "so/because of that"],
    ["ஆனாலும்", "āṉālum", "however/even so"],
    ["இருந்தாலும்", "iruntālum", "even though"],
    ["மேலும்", "mēlum", "moreover/also"],
    ["அதாவது", "atāvatu", "that is/meaning"],
    ["போன்ற", "pōṉṟa", "such as/like"],
    ["தவிர", "tavira", "except/besides"],
    ["மூலம்", "mūlam", "through/via"],
    ["வழியாக", "vaḻiyāka", "via/through"],
    ["நோக்கி", "nōkki", "toward"],
    ["ஆம்", "ām", "yes"],
    ["சரி", "cari", "okay/right"],
    ["ஏன்", "ēṉ", "why"],
    ["இன்னும்", "iṉṉum", "still/yet/more"],
    ["ஏற்கனவே", "ēṟkaṉavē", "already"],
    ["ஒருவேளை", "oruvēḷai", "maybe/perhaps"],
    ["போது", "pōtu", "when/during"],
    ["வேண்டும்", "vēṇṭum", "need/must"],
    ["ஆக", "āka", "as/to be"],
    ["என", "eṉa", "as/that"],
    ["அன்றி", "aṉṟi", "apart from"],
    ["நான்", "nāṉ", "I"],
    ["நீ", "nī", "you (informal)"],
    ["அது", "atu", "it/that"],
    ["இது", "itu", "this"],
    ["அவர்", "avar", "he/she (respectful)"],
    ["நீங்கள்", "nīṅkaḷ", "you (plural/formal)"],
    ["அவன்", "avaṉ", "he (informal)"],
    ["அவள்", "avaḷ", "she"],
    ["நாங்கள்", "nāṅkaḷ", "we (exclusive)"],
    ["அவர்கள்", "avarkaḷ", "they"],
    ["என்", "eṉ", "my"],
    ["உன்", "uṉ", "your"],
    ["எனக்கு", "eṉakku", "to me"],
    ["என்னை", "eṉṉai", "me"],
    ["உனக்கு", "uṉakku", "to you"],
    ["உன்னை", "uṉṉai", "you (object)"],
    ["நாம்", "nām", "we (inclusive)"],
    ["இங்கே", "iṅkē", "here"],
    ["அங்கே", "aṅkē", "there"],
    ["இந்த", "inta", "this (adj)"],
    ["அந்த", "anta", "that (adj)"],
    ["தன்", "taṉ", "one's own"],
    ["அவனை", "avaṉai", "him"],
    ["அவளை", "avaḷai", "her"],
    ["அவனுக்கு", "avaṉukku", "to him"],
    ["அவளுக்கு", "avaḷukku", "to her"],
    ["உங்கள்", "uṅkaḷ", "your (formal)"],
    ["உங்களுக்கு", "uṅkaḷukku", "to you (formal)"],
    ["என்னுடைய", "eṉṉuṭaiya", "my/mine"],
    ["நம்", "nam", "our (inclusive)"],
    ["எங்கள்", "eṅkaḷ", "our (exclusive)"],
    ["நமக்கு", "namakku", "to us"],
    ["நம்மை", "nammai", "us"],
    ["அவர்களை", "avarkaḷai", "them"],
    ["அவர்களுக்கு", "avarkaḷukku", "to them"],
    ["இவை", "ivai", "these"],
    ["அவை", "avai", "those"],
    ["இவர்", "ivar", "he/she (this one, respectful)"],
    ["இவன்", "ivaṉ", "he (this one)"],
    ["இவள்", "ivaḷ", "she (this one)"],
    ["அவரை", "avarai", "him/her (respectful)"],
    ["அவருக்கு", "avarukku", "to him/her (respectful)"],
    ["தன்னை", "taṉṉai", "oneself"],
    ["எங்களுக்கு", "eṅkaḷukku", "to us (exclusive)"],
    ["என்ன", "eṉṉa", "what"],
    ["யார்", "yār", "who"],
    ["எங்கே", "eṅkē", "where"],
    ["எப்போது", "eppōtu", "when"],
    ["எப்படி", "eppaṭi", "how"],
    ["எது", "etu", "which one"],
    ["எந்த", "enta", "which (adj.)"],
    ["எத்தனை", "ettaṉai", "how many"],
    ["எவ்வளவு", "evvaḷavu", "how much"],
    ["யாருடைய", "yāruṭaiya", "whose"],
    ["யாரு", "yāru", "who (spoken)"],
    ["எங்க", "eṅka", "where (spoken)"],
    ["எப்ப", "eppa", "when (spoken)"],
    ["யாரை", "yārai", "whom"],
    ["யாருக்கு", "yārukku", "to/for whom"],
    ["எதற்கு", "etaṟku", "for what/why"],
    ["எவன்", "evaṉ", "who (m.)"],
    ["எவள்", "evaḷ", "who (f.)"],
    ["எங்கிருந்து", "eṅkiruntu", "from where"],
    ["போ", "pō", "go"],
    ["வா", "vā", "come"],
    ["சொல்", "col", "say/tell"],
    ["பார்", "pār", "see/look"],
    ["செய்", "cey", "do"],
    ["கொடு", "koṭu", "give"],
    ["எடு", "eṭu", "take"],
    ["சாப்பிடு", "cāppiṭu", "eat"],
    ["குடி", "kuṭi", "drink"],
    ["கேள்", "kēḷ", "ask/hear"],
    ["பேசு", "pēcu", "speak/talk"],
    ["தெரி", "teri", "know"],
    ["நினை", "niṉai", "think"],
    ["வேண்டு", "vēṇṭu", "want"],
    ["விரும்பு", "virumpu", "like/desire"],
    ["போடு", "pōṭu", "put/drop"],
    ["வை", "vai", "keep/put"],
    ["இரு", "iru", "be/stay"],
    ["பண்ணு", "paṇṇu", "do/make"],
    ["படி", "paṭi", "read/study"],
    ["எழுது", "eḻutu", "write"],
    ["புரிந்துகொள்", "purintukoḷ", "understand"],
    ["நட", "naṭa", "walk/happen"],
    ["ஓடு", "ōṭu", "run"],
    ["உட்கார்", "uṭkār", "sit"],
    ["நில்", "nil", "stand/stop"],
    ["தூங்கு", "tūṅku", "sleep"],
    ["எழுந்திரு", "eḻuntiru", "wake/get up"],
    ["வாங்கு", "vāṅku", "buy/receive"],
    ["விற்று", "viṟṟu", "sell"],
    ["காத்திரு", "kāttiru", "wait"],
    ["உதவு", "utavu", "help"],
    ["கூப்பிடு", "kūppiṭu", "call"],
    ["பதில்சொல்", "patilcol", "answer"],
    ["வாழ்", "vāḻ", "live"],
    ["இறந்துபோ", "iṟantupō", "die"],
    ["கழுவு", "kaḻuvu", "wash"],
    ["சுத்தம்செய்", "cuttamcey", "clean"],
    ["தூக்கு", "tūkku", "carry/lift"],
    ["கண்டுபிடி", "kaṇṭupiṭi", "find"],
    ["தொலை", "tolai", "lose"],
    ["வெல்", "vel", "win"],
    ["ஆரம்பி", "ārampi", "start"],
    ["நிறுத்து", "niṟuttu", "stop"],
    ["பயன்படுத்து", "payaṉpaṭuttu", "use"],
    ["சந்தி", "canti", "meet"],
    ["சிரி", "ciri", "laugh/smile"],
    ["அழு", "aḻu", "cry"],
    ["பாடு", "pāṭu", "sing"],
    ["ஆடு", "āṭu", "dance/play"],
    ["குதி", "kuti", "jump"],
    ["விழு", "viḻu", "fall"],
    ["பிடி", "piṭi", "catch/hold"],
    ["எறி", "eṟi", "throw"],
    ["உடை", "uṭai", "break"],
    ["கட்டு", "kaṭṭu", "build/tie"],
    ["எண்ணு", "eṇṇu", "count"],
    ["திற", "tiṟa", "open"],
    ["மூடு", "mūṭu", "close"],
    ["சமை", "camai", "cook"],
    ["வெட்டு", "veṭṭu", "cut"],
    ["விளையாடு", "viḷaiyāṭu", "play"],
    ["வேலைசெய்", "vēlaicey", "work"],
    ["கத்துக்கொடு", "kattukkoṭu", "teach"],
    ["நேசி", "nēci", "love"],
    ["நம்பு", "nampu", "believe/trust"],
    ["பார்த்துக்கொள்", "pārttukkoḷ", "take care"],
    ["தொடு", "toṭu", "touch"],
    ["விடு", "viṭu", "leave/let"],
    ["திரும்பு", "tirumpu", "return/turn"],
    ["பறந்துபோ", "paṟantupō", "fly"],
    ["நீந்து", "nīntu", "swim"],
    ["இழு", "iḻu", "pull"],
    ["தள்ளு", "taḷḷu", "push"],
    ["காட்டு", "kāṭṭu", "show"],
    ["மற", "maṟa", "forget"],
    ["நினைவில்வை", "niṉaivilvai", "remember"],
    ["கொல்", "kol", "kill"],
    ["அடி", "aṭi", "hit/beat"],
    ["ஊற்று", "ūṟṟu", "pour"],
    ["நிரப்பு", "nirappu", "fill"],
    ["காலிசெய்", "kālicey", "empty"],
    ["அனுப்பு", "aṉuppu", "send"],
    ["கொண்டுவா", "koṇṭuvā", "bring"],
    ["தேடு", "tēṭu", "search"],
    ["முடி", "muṭi", "finish"],
    ["தொடங்கு", "toṭaṅku", "begin"],
    ["மாற்று", "māṟṟu", "change"],
    ["கற்றுக்கொள்", "kaṟṟukkoḷ", "learn"],
    ["ஏறு", "ēṟu", "climb"],
    ["இறங்கு", "iṟaṅku", "get down"],
    ["இருக்கு", "irukku", "is/there is"],
    ["இருக்கிறது", "irukkiṟatu", "is/exists"],
    ["இருக்கிறேன்", "irukkiṟēṉ", "I am"],
    ["வேணும்", "vēṇum", "want (spoken)"],
    ["முடியும்", "muṭiyum", "can/possible"],
    ["முடியாது", "muṭiyātu", "cannot"],
    ["தெரியும்", "teriyum", "I know"],
    ["தெரியாது", "teriyātu", "don't know"],
    ["வேண்டாம்", "vēṇṭām", "don't want"],
    ["போகிறேன்", "pōkiṟēṉ", "I am going"],
    ["வருகிறேன்", "varukiṟēṉ", "I am coming"],
    ["சாப்பிடுகிறேன்", "cāppiṭukiṟēṉ", "I am eating"],
    ["போனேன்", "pōṉēṉ", "I went"],
    ["வந்தேன்", "vantēṉ", "I came"],
    ["போவேன்", "pōvēṉ", "I will go"],
    ["வருவேன்", "varuvēṉ", "I will come"],
    ["போகலாம்", "pōkalām", "let's go"],
    ["ஆச்சு", "āccu", "it happened/done"],
    ["ஆகும்", "ākum", "will be/ok"],
    ["சொன்னேன்", "coṉṉēṉ", "I said"],
    ["பார்த்தேன்", "pārttēṉ", "I saw"],
    ["கொடுத்தேன்", "koṭuttēṉ", "I gave"],
    ["வாங்கினேன்", "vāṅkiṉēṉ", "I bought/took"],
    ["பண்ணுவேன்", "paṇṇuvēṉ", "I will do"],
    ["பண்ணினேன்", "paṇṇiṉēṉ", "I did"],
    ["தெரிஞ்சு", "teriñcu", "known (spoken)"],
    ["புரியுது", "puriyutu", "I understand"],
    ["புரியலை", "puriyalai", "don't understand"],
    ["நடந்தது", "naṭantatu", "it happened"],
    ["ஆகிவிட்டது", "ākiviṭṭatu", "it's done"],
    ["வரலாம்", "varalām", "may come/let's"],
    ["சாப்பிடலாம்", "cāppiṭalām", "let's eat"],
    ["இருக்கலாம்", "irukkalām", "may be"],
    ["செய்யலாம்", "ceyyalām", "can do/let's do"],
    ["கூடாது", "kūṭātu", "should not"],
    ["வேண்டியது", "vēṇṭiyatu", "needed"],
    ["தேவை", "tēvai", "need/necessary"],
    ["பிடிக்கும்", "piṭikkum", "I like"],
    ["பிடிக்கல", "piṭikkala", "don't like"],
    ["நினைக்கிறேன்", "niṉaikkiṟēṉ", "I think"],
    ["நினைச்சேன்", "niṉaiccēṉ", "I thought"],
    ["கேட்டேன்", "kēṭṭēṉ", "I asked/heard"],
    ["இருந்தது", "iruntatu", "it was"],
    ["இருந்தேன்", "iruntēṉ", "I was"],
    ["வந்துடு", "vantuṭu", "come (please)"],
    ["போயிடு", "pōyiṭu", "just go"],
    ["முடிஞ்சது", "muṭiñcatu", "it's finished"],
    ["தெரிஞ்சிக்கோ", "teriñcikkō", "get to know"],
    ["பேர்", "pēr", "name"],
    ["பெயர்", "peyar", "name (formal)"],
    ["ஆள்", "āḷ", "person"],
    ["மனிதன்", "maṉitaṉ", "man/human"],
    ["பெண்", "peṇ", "woman/girl"],
    ["ஆண்", "āṇ", "man/male"],
    ["பையன்", "paiyaṉ", "boy"],
    ["பெண்ணு", "peṇṇu", "girl (colloquial)"],
    ["பொண்ணு", "poṇṇu", "girl (colloquial)"],
    ["பிள்ளை", "piḷḷai", "child"],
    ["குழந்தை", "kuḻantai", "child/baby"],
    ["அம்மா", "ammā", "mother"],
    ["அப்பா", "appā", "father"],
    ["தாய்", "tāy", "mother"],
    ["தந்தை", "tantai", "father"],
    ["அண்ணா", "aṇṇā", "elder brother"],
    ["அண்ணன்", "aṇṇaṉ", "elder brother"],
    ["தம்பி", "tampi", "younger brother"],
    ["அக்கா", "akkā", "elder sister"],
    ["தங்கை", "taṅkai", "younger sister"],
    ["சகோதரன்", "cakōtaraṉ", "brother"],
    ["சகோதரி", "cakōtari", "sister"],
    ["மகன்", "makaṉ", "son"],
    ["மகள்", "makaḷ", "daughter"],
    ["கணவன்", "kaṇavaṉ", "husband"],
    ["மனைவி", "maṉaivi", "wife"],
    ["பாட்டி", "pāṭṭi", "grandmother"],
    ["தாத்தா", "tāttā", "grandfather"],
    ["மாமா", "māmā", "uncle"],
    ["அத்தை", "attai", "aunt"],
    ["சித்தப்பா", "cittappā", "father's younger brother"],
    ["சித்தி", "citti", "mother's younger sister/aunt"],
    ["மாமி", "māmi", "aunt/mother-in-law"],
    ["உறவினர்", "uṟaviṉar", "relative"],
    ["நண்பன்", "naṇpaṉ", "friend (male)"],
    ["நண்பர்", "naṇpar", "friend"],
    ["தோழி", "tōḻi", "friend (female)"],
    ["ஆசிரியர்", "āciriyar", "teacher"],
    ["மாணவன்", "māṇavaṉ", "student (male)"],
    ["மாணவி", "māṇavi", "student (female)"],
    ["மாணவர்", "māṇavar", "student"],
    ["மருத்துவர்", "maruttuvar", "doctor"],
    ["டாக்டர்", "ṭākṭar", "doctor"],
    ["தொழிலாளி", "toḻilāḷi", "worker"],
    ["வேலைக்காரன்", "vēlaikkāraṉ", "servant/worker"],
    ["விவசாயி", "vivacāyi", "farmer"],
    ["அண்டை வீட்டுக்காரர்", "aṇṭai vīṭṭukkārar", "neighbour"],
    ["விருந்தாளி", "viruntāḷi", "guest"],
    ["விருந்தினர்", "viruntiṉar", "guest"],
    ["ராஜா", "rājā", "king"],
    ["அரசன்", "aracaṉ", "king"],
    ["ராணி", "rāṇi", "queen"],
    ["கடவுள்", "kaṭavuḷ", "god"],
    ["தெய்வம்", "teyvam", "god/deity"],
    ["மக்கள்", "makkaḷ", "people"],
    ["ஜனங்கள்", "jaṉaṅkaḷ", "people/public"],
    ["பெரியவர்", "periyavar", "elder/older person"],
    ["தலைவர்", "talaivar", "leader"],
    ["தலை", "talai", "head"],
    ["கண்", "kaṇ", "eye"],
    ["கை", "kai", "hand/arm"],
    ["கால்", "kāl", "leg/foot"],
    ["முகம்", "mukam", "face"],
    ["வாய்", "vāy", "mouth"],
    ["காது", "kātu", "ear"],
    ["மூக்கு", "mūkku", "nose"],
    ["பல்", "pal", "tooth"],
    ["நாக்கு", "nākku", "tongue"],
    ["கழுத்து", "kaḻuttu", "neck"],
    ["வயிறு", "vayiṟu", "stomach"],
    ["முதுகு", "mutuku", "back"],
    ["விரல்", "viral", "finger"],
    ["தோள்", "tōḷ", "shoulder"],
    ["மார்பு", "mārpu", "chest"],
    ["முழங்கால்", "muḻaṅkāl", "knee"],
    ["பாதம்", "pātam", "foot"],
    ["தோல்", "tōl", "skin"],
    ["எலும்பு", "elumpu", "bone"],
    ["இரத்தம்", "irattam", "blood"],
    ["இதயம்", "itayam", "heart"],
    ["மூளை", "mūḷai", "brain"],
    ["உடல்", "uṭal", "body"],
    ["உடம்பு", "uṭampu", "body/health"],
    ["நோய்", "nōy", "sickness/disease"],
    ["வலி", "vali", "pain"],
    ["காய்ச்சல்", "kāyccal", "fever"],
    ["மருந்து", "maruntu", "medicine"],
    ["மருத்துவமனை", "maruttuvamaṉai", "hospital"],
    ["ஆஸ்பத்திரி", "āspattiri", "hospital"],
    ["தலைவலி", "talaivali", "headache"],
    ["வயிற்றுவலி", "vayiṟṟuvali", "stomach ache"],
    ["ஜுரம்", "juram", "fever"],
    ["இருமல்", "irumal", "cough"],
    ["சளி", "caḷi", "cold/phlegm"],
    ["காயம்", "kāyam", "wound/injury"],
    ["உதடு", "utaṭu", "lip"],
    ["கன்னம்", "kaṉṉam", "cheek"],
    ["நகம்", "nakam", "nail"],
    ["ஆரோக்கியம்", "ārōkkiyam", "health"],
    ["மூச்சு", "mūccu", "breath"],
    ["தண்ணீர்", "taṇṇīr", "water"],
    ["உணவு", "uṇavu", "food"],
    ["சாப்பாடு", "cāppāṭu", "meal/food"],
    ["சோறு", "cōṟu", "cooked rice"],
    ["அரிசி", "arici", "rice (grain)"],
    ["பால்", "pāl", "milk"],
    ["காபி", "kāpi", "coffee"],
    ["தேநீர்", "tēnīr", "tea"],
    ["பசி", "paci", "hunger"],
    ["சுவை", "cuvai", "taste"],
    ["உப்பு", "uppu", "salt"],
    ["சர்க்கரை", "carkkarai", "sugar"],
    ["எண்ணெய்", "eṇṇey", "oil"],
    ["முட்டை", "muṭṭai", "egg"],
    ["மீன்", "mīṉ", "fish"],
    ["கோழி", "kōḻi", "chicken"],
    ["இறைச்சி", "iṟaicci", "meat"],
    ["காய்கறி", "kāykaṟi", "vegetable"],
    ["பழம்", "paḻam", "fruit"],
    ["பருப்பு", "paruppu", "lentil/dal"],
    ["கறி", "kaṟi", "curry"],
    ["மிளகாய்", "miḷakāy", "chilli"],
    ["வெங்காயம்", "veṅkāyam", "onion"],
    ["தக்காளி", "takkāḷi", "tomato"],
    ["தேங்காய்", "tēṅkāy", "coconut"],
    ["உருளைக்கிழங்கு", "uruḷaikkiḻaṅku", "potato"],
    ["வாழைப்பழம்", "vāḻaippaḻam", "banana"],
    ["மாம்பழம்", "māmpaḻam", "mango"],
    ["ரொட்டி", "roṭṭi", "bread"],
    ["இனிப்பு", "iṉippu", "sweet"],
    ["தயிர்", "tayir", "curd/yogurt"],
    ["மோர்", "mōr", "buttermilk"],
    ["நெய்", "ney", "ghee"],
    ["வெண்ணெய்", "veṇṇey", "butter"],
    ["தேன்", "tēṉ", "honey"],
    ["தாகம்", "tākam", "thirst"],
    ["காலை உணவு", "kālai uṇavu", "breakfast"],
    ["மதிய உணவு", "matiya uṇavu", "lunch"],
    ["இரவு உணவு", "iravu uṇavu", "dinner"],
    ["தின்பண்டம்", "tiṉpaṇṭam", "snack"],
    ["மசாலா", "macālā", "spice/masala"],
    ["மிளகு", "miḷaku", "pepper"],
    ["மஞ்சள்", "mañcaḷ", "turmeric"],
    ["இஞ்சி", "iñci", "ginger"],
    ["பூண்டு", "pūṇṭu", "garlic"],
    ["புளி", "puḷi", "tamarind"],
    ["கடுகு", "kaṭuku", "mustard"],
    ["சீரகம்", "cīrakam", "cumin"],
    ["மல்லி", "malli", "coriander"],
    ["கீரை", "kīrai", "greens/spinach"],
    ["கத்திரிக்காய்", "kattirikkāy", "brinjal/eggplant"],
    ["வெண்டைக்காய்", "veṇṭaikkāy", "okra"],
    ["கடலை", "kaṭalai", "gram/chickpea"],
    ["நிலக்கடலை", "nilakkaṭalai", "peanut"],
    ["வெல்லம்", "vellam", "jaggery"],
    ["இளநீர்", "iḷanīr", "tender coconut water"],
    ["கோதுமை", "kōtumai", "wheat"],
    ["மாவு", "māvu", "flour"],
    ["இட்லி", "iṭli", "idli"],
    ["தோசை", "tōcai", "dosa"],
    ["சாம்பார்", "cāmpār", "sambar"],
    ["ரசம்", "racam", "rasam"],
    ["ஊறுகாய்", "ūṟukāy", "pickle"],
    ["எலுமிச்சை", "elumiccai", "lemon"],
    ["வடை", "vaṭai", "vada"],
    ["வீடு", "vīṭu", "house"],
    ["கதவு", "katavu", "door"],
    ["அறை", "aṟai", "room"],
    ["ஜன்னல்", "jaṉṉal", "window"],
    ["விளக்கு", "viḷakku", "lamp/light"],
    ["மேசை", "mēcai", "table"],
    ["நாற்காலி", "nāṟkāli", "chair"],
    ["கட்டில்", "kaṭṭil", "bed/cot"],
    ["புத்தகம்", "puttakam", "book"],
    ["பேனா", "pēṉā", "pen"],
    ["காகிதம்", "kākitam", "paper"],
    ["சாவி", "cāvi", "key"],
    ["பெட்டி", "peṭṭi", "box"],
    ["பை", "pai", "bag"],
    ["தட்டு", "taṭṭu", "plate"],
    ["கரண்டி", "karaṇṭi", "spoon"],
    ["கத்தி", "katti", "knife"],
    ["வாளி", "vāḷi", "bucket"],
    ["சோப்பு", "cōppu", "soap"],
    ["துண்டு", "tuṇṭu", "towel"],
    ["கண்ணாடி", "kaṇṇāṭi", "mirror/glass"],
    ["கடிகாரம்", "kaṭikāram", "clock"],
    ["பணம்", "paṇam", "money"],
    ["மோதிரம்", "mōtiram", "ring"],
    ["கூடை", "kūṭai", "basket"],
    ["சுவர்", "cuvar", "wall"],
    ["தரை", "tarai", "floor"],
    ["கூரை", "kūrai", "roof"],
    ["விசிறி", "viciṟi", "fan"],
    ["தலையணை", "talaiyaṇai", "pillow"],
    ["போர்வை", "pōrvai", "blanket"],
    ["பாய்", "pāy", "mat"],
    ["துடைப்பம்", "tuṭaippam", "broom"],
    ["போன்", "pōṉ", "phone"],
    ["பாட்டில்", "pāṭṭil", "bottle"],
    ["குவளை", "kuvaḷai", "tumbler/cup"],
    ["கோப்பை", "kōppai", "cup/mug"],
    ["கிண்ணம்", "kiṇṇam", "bowl"],
    ["மெத்தை", "mettai", "mattress"],
    ["அலமாரி", "alamāri", "cupboard/shelf"],
    ["படம்", "paṭam", "picture/photo"],
    ["கடிதம்", "kaṭitam", "letter"],
    ["குடை", "kuṭai", "umbrella"],
    ["செருப்பு", "ceruppu", "slippers/footwear"],
    ["ஆடை", "āṭai", "clothes/dress"],
    ["துணி", "tuṇi", "cloth"],
    ["வாசல்", "vācal", "entrance/doorway"],
    ["சட்டி", "caṭṭi", "pot/pan"],
    ["பானை", "pāṉai", "pot"],
    ["அடுப்பு", "aṭuppu", "stove"],
    ["மூடி", "mūṭi", "lid"],
    ["கயிறு", "kayiṟu", "rope"],
    ["ஊசி", "ūci", "needle"],
    ["நூல்", "nūl", "thread"],
    ["கத்தரிக்கோல்", "kattarikkōl", "scissors"],
    ["சீப்பு", "cīppu", "comb"],
    ["மெழுகுவர்த்தி", "meḻukuvartti", "candle"],
    ["மணி", "maṇi", "bell"],
    ["சாக்கு", "cākku", "sack"],
    ["டப்பா", "ṭappā", "tin/container"],
    ["கிணறு", "kiṇaṟu", "well"],
    ["படுக்கை", "paṭukkai", "bed/bedding"],
    ["கம்பளம்", "kampaḷam", "carpet/rug"],
    ["பணப்பை", "paṇappai", "wallet/purse"],
    ["தீப்பெட்டி", "tīppeṭṭi", "matchbox"],
    ["சட்டை", "caṭṭai", "shirt"],
    ["புடவை", "puṭavai", "saree"],
    ["காலணி", "kālaṇi", "shoe/footwear"],
    ["வேட்டி", "vēṭṭi", "dhoti"],
    ["பாவாடை", "pāvāṭai", "skirt/petticoat"],
    ["தொப்பி", "toppi", "hat/cap"],
    ["வளையல்", "vaḷaiyal", "bangle"],
    ["சங்கிலி", "caṅkili", "chain"],
    ["பொத்தான்", "pottāṉ", "button"],
    ["பட்டு", "paṭṭu", "silk"],
    ["மேலாடை", "mēlāṭai", "upper garment/top"],
    ["பெல்ட்", "pelṭ", "belt"],
    ["காற்சட்டை", "kāṟcaṭṭai", "pants/trousers"],
    ["சேலை", "cēlai", "saree"],
    ["முக்காடு", "mukkāṭu", "veil/head cover"],
    ["நகை", "nakai", "jewellery"],
    ["காதணி", "kātaṇi", "earring"],
    ["கைக்குட்டை", "kaikkuṭṭai", "handkerchief"],
    ["காற்று", "kāṟṟu", "wind/air"],
    ["நெருப்பு", "neruppu", "fire"],
    ["மழை", "maḻai", "rain"],
    ["மரம்", "maram", "tree"],
    ["பூ", "pū", "flower"],
    ["சூரியன்", "cūriyaṉ", "sun"],
    ["நிலா", "nilā", "moon"],
    ["வானம்", "vāṉam", "sky"],
    ["மேகம்", "mēkam", "cloud"],
    ["நட்சத்திரம்", "naṭcattiram", "star"],
    ["கடல்", "kaṭal", "sea"],
    ["மலை", "malai", "mountain"],
    ["கல்", "kal", "stone"],
    ["மண்", "maṇ", "soil/earth"],
    ["இலை", "ilai", "leaf"],
    ["வெயில்", "veyil", "sunshine/heat"],
    ["குளிர்", "kuḷir", "cold/chill"],
    ["வெளிச்சம்", "veḷiccam", "light"],
    ["நிழல்", "niḻal", "shadow"],
    ["ஆறு", "āṟu", "river"],
    ["காடு", "kāṭu", "forest"],
    ["புல்", "pul", "grass"],
    ["மணல்", "maṇal", "sand"],
    ["தங்கம்", "taṅkam", "gold"],
    ["இரும்பு", "irumpu", "iron"],
    ["புயல்", "puyal", "storm"],
    ["இடி", "iṭi", "thunder"],
    ["மின்னல்", "miṉṉal", "lightning"],
    ["விதை", "vitai", "seed"],
    ["வேர்", "vēr", "root"],
    ["செடி", "ceṭi", "plant"],
    ["ஏரி", "ēri", "lake"],
    ["வெப்பம்", "veppam", "heat"],
    ["பூமி", "pūmi", "earth/planet"],
    ["நிலம்", "nilam", "land/ground"],
    ["பனி", "paṉi", "snow/dew/fog"],
    ["அலை", "alai", "wave"],
    ["வெள்ளம்", "veḷḷam", "flood"],
    ["மலர்", "malar", "blossom/flower"],
    ["குன்று", "kuṉṟu", "hill"],
    ["குளம்", "kuḷam", "pond"],
    ["ஒளி", "oḷi", "light/ray"],
    ["வானவில்", "vāṉavil", "rainbow"],
    ["புகை", "pukai", "smoke"],
    ["கிளை", "kiḷai", "branch"],
    ["வெள்ளி", "veḷḷi", "silver"],
    ["ஆகாயம்", "ākāyam", "sky"],
    ["தூசி", "tūci", "dust"],
    ["சூடு", "cūṭu", "heat/hot"],
    ["கடற்கரை", "kaṭaṟkarai", "beach/seashore"],
    ["தோட்டம்", "tōṭṭam", "garden"],
    ["மேடு", "mēṭu", "mound/hillock"],
    ["சேறு", "cēṟu", "mud"],
    ["நாய்", "nāy", "dog"],
    ["பூனை", "pūṉai", "cat"],
    ["மாடு", "māṭu", "cow/cattle"],
    ["பசு", "pacu", "cow"],
    ["குதிரை", "kutirai", "horse"],
    ["யானை", "yāṉai", "elephant"],
    ["புலி", "puli", "tiger"],
    ["சிங்கம்", "ciṅkam", "lion"],
    ["கரடி", "karaṭi", "bear"],
    ["குரங்கு", "kuraṅku", "monkey"],
    ["மான்", "māṉ", "deer"],
    ["முயல்", "muyal", "rabbit"],
    ["எலி", "eli", "rat/mouse"],
    ["பாம்பு", "pāmpu", "snake"],
    ["தவளை", "tavaḷai", "frog"],
    ["பறவை", "paṟavai", "bird"],
    ["காக்கை", "kākkai", "crow"],
    ["கிளி", "kiḷi", "parrot"],
    ["வாத்து", "vāttu", "duck"],
    ["மயில்", "mayil", "peacock"],
    ["கழுகு", "kaḻuku", "eagle"],
    ["எறும்பு", "eṟumpu", "ant"],
    ["தேனீ", "tēṉī", "bee"],
    ["ஈ", "ī", "fly"],
    ["கொசு", "kocu", "mosquito"],
    ["சிலந்தி", "cilanti", "spider"],
    ["பட்டாம்பூச்சி", "paṭṭāmpūcci", "butterfly"],
    ["பூச்சி", "pūcci", "insect/bug"],
    ["எருமை", "erumai", "buffalo"],
    ["கழுதை", "kaḻutai", "donkey"],
    ["செம்மறி ஆடு", "cemmaṟi āṭu", "sheep"],
    ["பன்றி", "paṉṟi", "pig"],
    ["நரி", "nari", "fox/jackal"],
    ["அணில்", "aṇil", "squirrel"],
    ["ஆமை", "āmai", "turtle/tortoise"],
    ["பல்லி", "palli", "lizard/gecko"],
    ["நண்டு", "naṇṭu", "crab"],
    ["இறால்", "iṟāl", "shrimp/prawn"],
    ["புறா", "puṟā", "pigeon/dove"],
    ["குருவி", "kuruvi", "sparrow"],
    ["கூண்டு", "kūṇṭu", "cage"],
    ["தென்னை", "teṉṉai", "coconut tree"],
    ["மாமரம்", "māmaram", "mango tree"],
    ["வேம்பு", "vēmpu", "neem tree"],
    ["ஊர்", "ūr", "town/village"],
    ["கடை", "kaṭai", "shop/store"],
    ["நகரம்", "nakaram", "city"],
    ["பள்ளி", "paḷḷi", "school"],
    ["சாலை", "cālai", "road"],
    ["தெரு", "teru", "street"],
    ["கோயில்", "kōyil", "temple"],
    ["நாடு", "nāṭu", "country"],
    ["உலகம்", "ulakam", "world"],
    ["அலுவலகம்", "aluvalakam", "office"],
    ["வங்கி", "vaṅki", "bank"],
    ["சந்தை", "cantai", "market"],
    ["கல்லூரி", "kallūri", "college"],
    ["இடம்", "iṭam", "place"],
    ["கட்டிடம்", "kaṭṭiṭam", "building"],
    ["நிலையம்", "nilaiyam", "station"],
    ["விடுதி", "viṭuti", "hotel/lodge"],
    ["உணவகம்", "uṇavakam", "restaurant"],
    ["பூங்கா", "pūṅkā", "park"],
    ["வயல்", "vayal", "field/paddy"],
    ["பண்ணை", "paṇṇai", "farm"],
    ["கிராமம்", "kirāmam", "village"],
    ["பாலம்", "pālam", "bridge"],
    ["நூலகம்", "nūlakam", "library"],
    ["காவல் நிலையம்", "kāval nilaiyam", "police station"],
    ["தபால் நிலையம்", "tapāl nilaiyam", "post office"],
    ["விமான நிலையம்", "vimāṉa nilaiyam", "airport"],
    ["தொழிற்சாலை", "toḻiṟcālai", "factory"],
    ["சிறை", "ciṟai", "prison/jail"],
    ["பள்ளிவாசல்", "paḷḷivācal", "mosque"],
    ["தேவாலயம்", "tēvālayam", "church"],
    ["பட்டணம்", "paṭṭaṇam", "town"],
    ["வீதி", "vīti", "street/avenue"],
    ["சமையலறை", "camaiyalaṟai", "kitchen"],
    ["மைதானம்", "maitāṉam", "ground/field"],
    ["கோட்டை", "kōṭṭai", "fort"],
    ["அரண்மனை", "araṇmaṉai", "palace"],
    ["மண்டபம்", "maṇṭapam", "hall"],
    ["திரையரங்கம்", "tiraiyaraṅkam", "cinema/theatre"],
    ["பேருந்து நிலையம்", "pēruntu nilaiyam", "bus station"],
    ["ரயில் நிலையம்", "rayil nilaiyam", "railway station"],
    ["வண்டி", "vaṇṭi", "vehicle/cart"],
    ["கார்", "kār", "car"],
    ["பேருந்து", "pēruntu", "bus"],
    ["ரயில்", "rayil", "train"],
    ["விமானம்", "vimāṉam", "airplane"],
    ["வழி", "vaḻi", "way/path"],
    ["பயணம்", "payaṇam", "journey/trip"],
    ["வலது", "valatu", "right"],
    ["இடது", "iṭatu", "left"],
    ["தூரம்", "tūram", "distance/far"],
    ["வேகம்", "vēkam", "speed"],
    ["ஓட்டுநர்", "ōṭṭunar", "driver"],
    ["திசை", "ticai", "direction"],
    ["படகு", "paṭaku", "boat"],
    ["கப்பல்", "kappal", "ship"],
    ["மிதிவண்டி", "mitivaṇṭi", "bicycle"],
    ["சக்கரம்", "cakkaram", "wheel"],
    ["பாதை", "pātai", "path/track"],
    ["டிக்கெட்", "ṭikkeṭ", "ticket"],
    ["கட்டணம்", "kaṭṭaṇam", "fare/fee"],
    ["வரைபடம்", "varaipaṭam", "map"],
    ["பெட்ரோல்", "peṭrōl", "petrol"],
    ["எரிபொருள்", "eriporuḷ", "fuel"],
    ["போக்குவரத்து", "pōkkuvarattu", "traffic/transport"],
    ["நேராக", "nērāka", "straight/directly"],
    ["முன்னால்", "muṉṉāl", "front/ahead"],
    ["பின்னால்", "piṉṉāl", "behind"],
    ["ஓட்டு", "ōṭṭu", "to drive"],
    ["வேகமாக", "vēkamāka", "fast/quickly"],
    ["மெதுவாக", "metuvāka", "slowly"],
    ["சிக்னல்", "cikṉal", "signal"],
    ["பயணி", "payaṇi", "passenger/traveler"],
    ["விபத்து", "vipattu", "accident"],
    ["இருக்கை", "irukkai", "seat"],
    ["நடைபாதை", "naṭaipātai", "footpath/pavement"],
    ["வேலை", "vēlai", "work/job"],
    ["விலை", "vilai", "price"],
    ["விற்பனை", "viṟpaṉai", "sale/selling"],
    ["காசு", "kācu", "money/cash"],
    ["பணக்காரன்", "paṇakkāraṉ", "rich person"],
    ["ஏழை", "ēḻai", "poor person"],
    ["சம்பளம்", "campaḷam", "salary"],
    ["கூலி", "kūli", "wages"],
    ["லாபம்", "lāpam", "profit"],
    ["நஷ்டம்", "naṣṭam", "loss"],
    ["கடன்", "kaṭaṉ", "debt/loan"],
    ["வரி", "vari", "tax"],
    ["நாணயம்", "nāṇayam", "coin"],
    ["கணக்கு", "kaṇakku", "account"],
    ["கூட்டம்", "kūṭṭam", "meeting"],
    ["திட்டம்", "tiṭṭam", "plan"],
    ["வியாபாரம்", "viyāpāram", "business"],
    ["வாடிக்கையாளர்", "vāṭikkaiyāḷar", "customer"],
    ["முதலாளி", "mutalāḷi", "boss/owner"],
    ["மலிவு", "malivu", "cheap"],
    ["விலை உயர்ந்த", "vilai uyarnta", "expensive"],
    ["செலவு", "celavu", "cost/expense"],
    ["தொழில்", "toḻil", "trade/occupation"],
    ["பணக்கார", "paṇakkāra", "rich (adj)"],
    ["நோட்டு", "nōṭṭu", "currency note"],
    ["பொருள்", "poruḷ", "goods/item"],
    ["கடைக்காரர்", "kaṭaikkārar", "shopkeeper"],
    ["வருமானம்", "varumāṉam", "income"],
    ["விற்பனையாளர்", "viṟpaṉaiyāḷar", "seller/salesman"],
    ["செலவழி", "celavaḻi", "spend"],
    ["சேமிப்பு", "cēmippu", "savings"],
    ["மொத்தம்", "mottam", "total"],
    ["ரூபாய்", "rūpāy", "rupee"],
    ["கம்பெனி", "kampeṉi", "company"],
    ["பங்கு", "paṅku", "share/part"],
    ["ஊதியம்", "ūtiyam", "wage/pay"],
    ["வேலைவாய்ப்பு", "vēlaivāyppu", "employment"],
    ["பேரம்", "pēram", "bargain"],
    ["முதலீடு", "mutalīṭu", "investment"],
    ["கல்வி", "kalvi", "education"],
    ["படிப்பு", "paṭippu", "studies/learning"],
    ["வகுப்பு", "vakuppu", "class"],
    ["பாடம்", "pāṭam", "lesson"],
    ["கேள்வி", "kēḷvi", "question"],
    ["பதில்", "patil", "answer"],
    ["பென்சில்", "peṉcil", "pencil"],
    ["எழுத்து", "eḻuttu", "letter/alphabet"],
    ["வார்த்தை", "vārttai", "word"],
    ["மொழி", "moḻi", "language"],
    ["தமிழ்", "tamiḻ", "Tamil"],
    ["ஆங்கிலம்", "āṅkilam", "English"],
    ["தேர்வு", "tērvu", "exam"],
    ["மதிப்பெண்", "matippeṇ", "mark/score"],
    ["அறிவு", "aṟivu", "knowledge"],
    ["வாக்கியம்", "vākkiyam", "sentence"],
    ["பல்கலைக்கழகம்", "palkalaikkaḻakam", "university"],
    ["வீட்டுப்பாடம்", "vīṭṭuppāṭam", "homework"],
    ["வாசி", "vāci", "read"],
    ["வகுப்பறை", "vakuppaṟai", "classroom"],
    ["விடை", "viṭai", "answer/solution"],
    ["விடுமுறை", "viṭumuṟai", "holiday/vacation"],
    ["குறிப்பு", "kuṟippu", "note"],
    ["எண்", "eṇ", "number"],
    ["தலைமையாசிரியர்", "talaimaiyāciriyar", "headmaster"],
    ["தேர்ச்சி", "tērcci", "pass/proficiency"],
    ["மொபைல்", "mopail", "mobile"],
    ["செய்தி", "ceyti", "news"],
    ["தொலைக்காட்சி", "tolaikkāṭci", "television"],
    ["கணினி", "kaṇiṉi", "computer"],
    ["இணையம்", "iṇaiyam", "internet"],
    ["மின்சாரம்", "miṉcāram", "electricity"],
    ["தொலைபேசி", "tolaipēci", "telephone"],
    ["கைபேசி", "kaipēci", "mobile phone"],
    ["கேமரா", "kēmarā", "camera"],
    ["வீடியோ", "vīṭiyō", "video"],
    ["அழைப்பு", "aḻaippu", "call"],
    ["புகைப்படம்", "pukaippaṭam", "photograph"],
    ["மின்னஞ்சல்", "miṉṉañcal", "email"],
    ["திரை", "tirai", "screen"],
    ["செய்தித்தாள்", "ceytittāḷ", "newspaper"],
    ["வானொலி", "vāṉoli", "radio"],
    ["இயந்திரம்", "iyantiram", "machine"],
    ["மின்கலம்", "miṉkalam", "battery"],
    ["மின்னோட்டம்", "miṉṉōṭṭam", "electric current"],
    ["குறுஞ்செய்தி", "kuṟuñceyti", "text message/SMS"],
    ["மின்விளக்கு", "miṉviḷakku", "light bulb"],
    ["மின்விசிறி", "miṉviciṟi", "electric fan"],
    ["வலைத்தளம்", "valaittaḷam", "website"],
    ["விசைப்பலகை", "vicaippalakai", "keyboard"],
    ["அஞ்சல்", "añcal", "mail/post"],
    ["மின்னணு", "miṉṉaṇu", "electronic"],
    ["நேரம்", "nēram", "time"],
    ["நாள்", "nāḷ", "day"],
    ["இன்று", "iṉṟu", "today"],
    ["நாளை", "nāḷai", "tomorrow"],
    ["நேற்று", "nēṟṟu", "yesterday"],
    ["இப்போது", "ippōtu", "now"],
    ["காலை", "kālai", "morning"],
    ["இரவு", "iravu", "night"],
    ["மாலை", "mālai", "evening"],
    ["மதியம்", "matiyam", "noon / midday"],
    ["வாரம்", "vāram", "week"],
    ["மாதம்", "mātam", "month"],
    ["வருடம்", "varuṭam", "year"],
    ["ஆண்டு", "āṇṭu", "year"],
    ["நிமிடம்", "nimiṭam", "minute"],
    ["வினாடி", "viṉāṭi", "second"],
    ["அப்போது", "appōtu", "then"],
    ["எப்போதும்", "eppōtum", "always"],
    ["தினமும்", "tiṉamum", "daily"],
    ["சில நேரம்", "cila nēram", "sometimes"],
    ["முன்பு", "muṉpu", "before / earlier"],
    ["சீக்கிரம்", "cīkkiram", "early / soon"],
    ["தாமதம்", "tāmatam", "late / delay"],
    ["ஒருபோதும்", "orupōtum", "never"],
    ["கணம்", "kaṇam", "moment"],
    ["காலம்", "kālam", "season / period"],
    ["கோடை", "kōṭai", "summer"],
    ["குளிர்காலம்", "kuḷirkālam", "winter"],
    ["மழைக்காலம்", "maḻaikkālam", "rainy season"],
    ["பகல்", "pakal", "daytime"],
    ["நண்பகல்", "naṇpakal", "noon"],
    ["பிற்பகல்", "piṟpakal", "afternoon"],
    ["அதிகாலை", "atikālai", "early morning"],
    ["விடியல்", "viṭiyal", "dawn"],
    ["நள்ளிரவு", "naḷḷiravu", "midnight"],
    ["சமயம்", "camayam", "occasion / time"],
    ["பொழுது", "poḻutu", "time / while"],
    ["கிழமை", "kiḻamai", "weekday"],
    ["திங்கட்கிழமை", "tiṅkaṭkiḻamai", "Monday"],
    ["செவ்வாய்க்கிழமை", "cevvāykkiḻamai", "Tuesday"],
    ["புதன்கிழமை", "putaṉkiḻamai", "Wednesday"],
    ["வியாழக்கிழமை", "viyāḻakkiḻamai", "Thursday"],
    ["வெள்ளிக்கிழமை", "veḷḷikkiḻamai", "Friday"],
    ["சனிக்கிழமை", "caṉikkiḻamai", "Saturday"],
    ["ஞாயிற்றுக்கிழமை", "ñāyiṟṟukkiḻamai", "Sunday"],
    ["கடந்த", "kaṭanta", "past / last"],
    ["அடுத்த", "aṭutta", "next"],
    ["மணிநேரம்", "maṇinēram", "hour (duration)"],
    ["வாரயிறுதி", "vārayiṟuti", "weekend"],
    ["தை", "tai", "Thai (month)"],
    ["சித்திரை", "cittirai", "Chithirai (month)"],
    ["ஆடி", "āṭi", "Aadi (month)"],
    ["மார்கழி", "mārkaḻi", "Margazhi (month)"],
    ["கார்த்திகை", "kārttikai", "Karthigai (month)"],
    ["மாசி", "māci", "Maasi (month)"],
    ["பங்குனி", "paṅkuṉi", "Panguni (month)"],
    ["புரட்டாசி", "puraṭṭāci", "Purattasi (month)"],
    ["வைகாசி", "vaikāci", "Vaikasi (month)"],
    ["ஒன்று", "oṉṟu", "one"],
    ["இரண்டு", "iraṇṭu", "two"],
    ["மூன்று", "mūṉṟu", "three"],
    ["நான்கு", "nāṉku", "four"],
    ["ஐந்து", "aintu", "five"],
    ["ஏழு", "ēḻu", "seven"],
    ["எட்டு", "eṭṭu", "eight"],
    ["ஒன்பது", "oṉpatu", "nine"],
    ["பத்து", "pattu", "ten"],
    ["நூறு", "nūṟu", "hundred"],
    ["ஆயிரம்", "āyiram", "thousand"],
    ["பதினொன்று", "patiṉoṉṟu", "eleven"],
    ["பன்னிரண்டு", "paṉṉiraṇṭu", "twelve"],
    ["இருபது", "irupatu", "twenty"],
    ["முப்பது", "muppatu", "thirty"],
    ["நாற்பது", "nāṟpatu", "forty"],
    ["ஐம்பது", "aimpatu", "fifty"],
    ["பூஜ்யம்", "pūjyam", "zero"],
    ["லட்சம்", "laṭcam", "lakh"],
    ["எல்லாம்", "ellām", "all"],
    ["கொஞ்சம்", "koñcam", "a little/few"],
    ["நிறைய", "niṟaiya", "a lot/many"],
    ["அதிகம்", "atikam", "more/much"],
    ["குறைவு", "kuṟaivu", "less"],
    ["பாதி", "pāti", "half"],
    ["முழு", "muḻu", "whole"],
    ["பகுதி", "pakuti", "part"],
    ["ஒவ்வொரு", "ovvoru", "each/every"],
    ["சில", "cila", "some/a few"],
    ["பல", "pala", "many"],
    ["முதல்", "mutal", "first"],
    ["இரண்டாவது", "iraṇṭāvatu", "second"],
    ["மூன்றாவது", "mūṉṟāvatu", "third"],
    ["இரட்டை", "iraṭṭai", "double/pair"],
    ["ஜோடி", "jōṭi", "pair"],
    ["டஜன்", "ṭajaṉ", "dozen"],
    ["பதின்மூன்று", "patiṉmūṉṟu", "thirteen"],
    ["பதினான்கு", "patiṉāṉku", "fourteen"],
    ["பதினைந்து", "patiṉaintu", "fifteen"],
    ["பதினாறு", "patiṉāṟu", "sixteen"],
    ["பதினேழு", "patiṉēḻu", "seventeen"],
    ["பதினெட்டு", "patiṉeṭṭu", "eighteen"],
    ["பத்தொன்பது", "pattoṉpatu", "nineteen"],
    ["அறுபது", "aṟupatu", "sixty"],
    ["எழுபது", "eḻupatu", "seventy"],
    ["எண்பது", "eṇpatu", "eighty"],
    ["தொண்ணூறு", "toṇṇūṟu", "ninety"],
    ["நிறம்", "niṟam", "colour"],
    ["சிவப்பு", "civappu", "red"],
    ["கருப்பு", "karuppu", "black"],
    ["வெள்ளை", "veḷḷai", "white"],
    ["பச்சை", "paccai", "green"],
    ["நீலம்", "nīlam", "blue"],
    ["அளவு", "aḷavu", "size/measure"],
    ["கிலோ", "kilō", "kilo"],
    ["நீளம்", "nīḷam", "length"],
    ["எடை", "eṭai", "weight"],
    ["உயரம்", "uyaram", "height"],
    ["வட்டம்", "vaṭṭam", "circle/round"],
    ["கோடு", "kōṭu", "line"],
    ["மீட்டர்", "mīṭṭar", "metre"],
    ["லிட்டர்", "liṭṭar", "litre"],
    ["கிராம்", "kirām", "gram"],
    ["ஆரஞ்சு", "ārañcu", "orange"],
    ["இளஞ்சிவப்பு", "iḷañcivappu", "pink"],
    ["சாம்பல்", "cāmpal", "grey"],
    ["பழுப்பு", "paḻuppu", "brown"],
    ["ஊதா", "ūtā", "purple/violet"],
    ["சதுரம்", "caturam", "square"],
    ["புள்ளி", "puḷḷi", "point/dot"],
    ["கிலோமீட்டர்", "kilōmīṭṭar", "kilometre"],
    ["அங்குலம்", "aṅkulam", "inch"],
    ["வடிவம்", "vaṭivam", "shape"],
    ["கனம்", "kaṉam", "weight/heaviness"],
    ["பெரிய", "periya", "big"],
    ["சிறிய", "ciṟiya", "small"],
    ["நல்ல", "nalla", "good"],
    ["கெட்ட", "keṭṭa", "bad"],
    ["புதிய", "putiya", "new"],
    ["பழைய", "paḻaiya", "old"],
    ["சரியான", "cariyāṉa", "right/correct"],
    ["தவறான", "tavaṟāṉa", "wrong"],
    ["கடைசி", "kaṭaici", "last"],
    ["முக்கியமான", "mukkiyamāṉa", "important"],
    ["நீளமான", "nīḷamāṉa", "long"],
    ["குட்டையான", "kuṭṭaiyāṉa", "short"],
    ["உயரமான", "uyaramāṉa", "tall"],
    ["உயர்ந்த", "uyarnta", "high"],
    ["தாழ்வான", "tāḻvāṉa", "low"],
    ["சூடான", "cūṭāṉa", "hot"],
    ["குளிரான", "kuḷirāṉa", "cold"],
    ["நிறைந்த", "niṟainta", "full"],
    ["காலியான", "kāliyāṉa", "empty"],
    ["திறந்த", "tiṟanta", "open"],
    ["மூடிய", "mūṭiya", "closed"],
    ["அழகான", "aḻakāṉa", "beautiful"],
    ["வேகமான", "vēkamāṉa", "fast"],
    ["மெதுவான", "metuvāṉa", "slow"],
    ["எளிதான", "eḷitāṉa", "easy"],
    ["கடினமான", "kaṭiṉamāṉa", "difficult"],
    ["பலமான", "palamāṉa", "strong"],
    ["பலவீனமான", "palavīṉamāṉa", "weak"],
    ["கனமான", "kaṉamāṉa", "heavy"],
    ["இலகுவான", "ilakuvāṉa", "light (weight)"],
    ["உண்மையான", "uṇmaiyāṉa", "true"],
    ["பொய்யான", "poyyāṉa", "false"],
    ["நிஜமான", "nijamāṉa", "real"],
    ["முக்கிய", "mukkiya", "main"],
    ["ஒரே", "orē", "same"],
    ["வித்தியாசமான", "vittiyācamāṉa", "different"],
    ["இளம்", "iḷam", "young"],
    ["சுத்தமான", "cuttamāṉa", "clean"],
    ["அழுக்கான", "aḻukkāṉa", "dirty"],
    ["ஈரமான", "īramāṉa", "wet"],
    ["உலர்ந்த", "ularnta", "dry"],
    ["வெதுவெதுப்பான", "vetuvetuppāṉa", "warm"],
    ["அகலமான", "akalamāṉa", "wide"],
    ["குறுகலான", "kuṟukalāṉa", "narrow"],
    ["தடிமனான", "taṭimaṉāṉa", "thick"],
    ["மெல்லிய", "melliya", "thin"],
    ["கொழுத்த", "koḻutta", "fat"],
    ["கெட்டியான", "keṭṭiyāṉa", "hard/firm"],
    ["மென்மையான", "meṉmaiyāṉa", "soft"],
    ["தூரமான", "tūramāṉa", "far"],
    ["அருகிலுள்ள", "arukiluḷḷa", "near"],
    ["ஆழமான", "āḻamāṉa", "deep"],
    ["ஆழமற்ற", "āḻamaṟṟa", "shallow"],
    ["கூர்மையான", "kūrmaiyāṉa", "sharp"],
    ["மழுங்கிய", "maḻuṅkiya", "dull/blunt"],
    ["பிரகாசமான", "pirakācamāṉa", "bright"],
    ["இருண்ட", "iruṇṭa", "dark"],
    ["சத்தமான", "cattamāṉa", "loud"],
    ["அமைதியான", "amaitiyāṉa", "quiet"],
    ["இனிப்பான", "iṉippāṉa", "sweet"],
    ["புளிப்பான", "puḷippāṉa", "sour"],
    ["கசப்பான", "kacappāṉa", "bitter"],
    ["உப்பான", "uppāṉa", "salty"],
    ["காரமான", "kāramāṉa", "spicy"],
    ["ருசியான", "ruciyāṉa", "tasty"],
    ["மகிழ்ச்சியான", "makiḻcciyāṉa", "happy"],
    ["சோகமான", "cōkamāṉa", "sad"],
    ["கோபமான", "kōpamāṉa", "angry"],
    ["களைப்பான", "kaḷaippāṉa", "tired"],
    ["பசியான", "paciyāṉa", "hungry"],
    ["தாகமான", "tākamāṉa", "thirsty"],
    ["நோய்வாய்ப்பட்ட", "nōyvāyppaṭṭa", "sick"],
    ["ஆரோக்கியமான", "ārōkkiyamāṉa", "healthy"],
    ["தயார்", "tayār", "ready"],
    ["விலையுயர்ந்த", "vilaiyuyarnta", "expensive"],
    ["மலிவான", "malivāṉa", "cheap"],
    ["அசிங்கமான", "aciṅkamāṉa", "ugly"],
    ["மீண்டும்", "mīṇṭum", "again"],
    ["அடிக்கடி", "aṭikkaṭi", "often"],
    ["சில நேரங்களில்", "cila nēraṅkaḷil", "sometimes"],
    ["வழக்கமாக", "vaḻakkamāka", "usually"],
    ["உடனே", "uṭaṉē", "immediately/soon"],
    ["நன்றாக", "naṉṟāka", "well/nicely"],
    ["மோசமாக", "mōcamāka", "badly"],
    ["கவனமாக", "kavaṉamāka", "carefully"],
    ["திடீரென்று", "tiṭīreṉṟu", "suddenly"],
    ["ஒன்றாக", "oṉṟāka", "together"],
    ["தனியாக", "taṉiyāka", "alone"],
    ["அதிகமாக", "atikamāka", "greatly/excessively"],
    ["ஏறக்குறைய", "ēṟakkuṟaiya", "almost"],
    ["உண்மையில்", "uṇmaiyil", "really"],
    ["கண்டிப்பாக", "kaṇṭippāka", "certainly/surely"],
    ["நிச்சயமாக", "niccayamāka", "definitely/of course"],
    ["மேலே", "mēlē", "up/above"],
    ["கீழே", "kīḻē", "down/below"],
    ["எங்கும்", "eṅkum", "everywhere"],
    ["மறுபடியும்", "maṟupaṭiyum", "again"],
    ["போதும்", "pōtum", "enough"],
    ["முன்னே", "muṉṉē", "front/ahead"],
  ]),
  V("common", [
    ["உயிர் எழுத்துகள்", "uyir eḻuttukaḷ", "vowels"],
    ["மெய் எழுத்துகள்", "mey eḻuttukaḷ", "consonants"],
    ["உயிர்மெய் எழுத்துகள்", "uyirmey eḻuttukaḷ", "consonant-vowel letters"],
    ["குறில்", "kuṟil", "short vowel"],
    ["நெடில்", "neṭil", "long vowel"],
    ["வல்லினம்", "valliṉam", "hard consonants"],
    ["மெல்லினம்", "melliṉam", "soft (nasal) consonants"],
    ["இடையினம்", "iṭaiyiṉam", "medium consonants"],
    ["இனம்", "iṉam", "class, family"],
    ["ஆயுத எழுத்து", "āyuta eḻuttu", "aytham (special letter)"],
    ["செந்தமிழ்", "centamiḻ", "refined/classical Tamil"],
    ["கொடுந்தமிழ்", "koṭuntamiḻ", "colloquial Tamil"],
    ["தா", "tā", "give"],
    ["தீ", "tī", "fire"],
    ["ஊது", "ūtu", "blow"],
    ["படு", "paṭu", "Lie down"],
    ["ஓது", "ōtu", "Recite"],
    ["வால்", "vāl", "Tail"],
    ["வாள்", "vāḷ", "Sword"],
    ["கிழவி", "kiḻavi", "Old lady"],
    ["குழவி", "kuḻavi", "Infant"],
    ["பூஜியம்", "pūjiyam", "Zero"],
    ["இரண்டாயிரம்", "iraṇṭāyiram", "Two thousand"],
    ["முதலாவது", "mutalāvatu", "First"],
    ["நான்காவது", "nāṉkāvatu", "Fourth"],
    ["இருக்கிறீர்கள்", "irukkiṟīrkaḷ", "You are"],
    ["திரு", "tiru", "Mr."],
    ["திருமதி", "tirumati", "Mrs."],
    ["செல்வி", "celvi", "Miss"],
    ["செல்வன்", "celvaṉ", "Master"],
    ["மாண்புமிகு", "māṇpumiku", "Honorable"],
    ["ஐயா", "aiyā", "Sir"],
    ["அம்மணி", "ammaṇi", "Young lady"],
    ["குட்டி", "kuṭṭi", "Little one"],
    ["எப்பொழுது", "eppoḻutu", "When"],
    ["உண்", "uṇ", "Eat (formal)"],
    ["ஆமாம்", "āmām", "Yes"],
    ["போய்விட்டு வருகிறேன்", "pōyviṭṭu varukiṟēṉ", "Goodbye"],
    ["பிறகு பார்க்கலாம்", "piṟaku pārkkalām", "See you later"],
    ["வீட்டு முகவரி", "vīṭṭu mukavari", "Home address"],
    ["படிக்கிறீர்கள்", "paṭikkiṟīrkaḷ", "You are studying"],
    ["அப்படியா?", "appaṭiyā?", "Is that so?"],
    ["கணினி அறிவியல்", "kaṇiṉi aṟiviyal", "Computer science"],
    ["கிழக்கு", "kiḻakku", "East"],
    ["பந்து", "pantu", "Ball"],
    ["முள்", "muḷ", "Thorn"],
    ["கடி", "kaṭi", "To bite"],
    ["நடனம்", "naṭaṉam", "Dance"],
    ["அருவாள்", "aruvāḷ", "Sickle"],
    ["பொம்மை", "pommai", "Toy"],
    ["உயரமாக", "uyaramāka", "Tall"],
    ["கிடை", "kiṭai", "To be available"],
    ["ஒருமை", "orumai", "Singular"],
    ["பன்மை", "paṉmai", "Plural"],
    ["திணை", "tiṇai", "Class / division"],
    ["கதை", "katai", "story"],
    ["தேள்", "tēḷ", "scorpion"],
    ["மாங்காய்", "māṅkāy", "mango"],
    ["நியாபகம்", "niyāpakam", "memory"],
    ["சத்தமாக", "cattamāka", "loudly"],
    ["திரும்ப", "tirumpa", "again"],
    ["தவறு", "tavaṟu", "wrong, mistake"],
    ["எனக்குப் புரியவில்லை", "eṉakkup puriyavillai", "I don't understand"],
    ["எனக்குத் தெரியாது", "eṉakkut teriyātu", "I don't know"],
    ["இது என்ன?", "itu eṉṉa?", "what is this?"],
    ["வினைச்சொற்கள்", "viṉaiccoṟkaḷ", "verbs"],
    ["நிகழ்காலம்", "nikaḻkālam", "present tense"],
    ["கடந்தகாலம்", "kaṭantakālam", "past tense"],
    ["எதிர்காலம்", "etirkālam", "future tense"],
    ["மன்னி", "maṉṉi", "forgive"],
    ["கொண்டாடு", "koṇṭāṭu", "celebrate"],
    ["உறவு", "uṟavu", "relationship"],
    ["தமக்கை", "tamakkai", "older sister"],
    ["கொள்ளுத் தாத்தா", "koḷḷut tāttā", "great grandfather"],
    ["கொள்ளுப் பாட்டி", "koḷḷup pāṭṭi", "great grandmother"],
    ["மாப்பிள்ளை", "māppiḷḷai", "son-in-law"],
    ["மருமகன்", "marumakaṉ", "son-in-law"],
    ["மருமகள்", "marumakaḷ", "daughter-in-law"],
    ["அண்ணி", "aṇṇi", "elder brother's wife"],
    ["மைத்துனன்", "maittuṉaṉ", "brother-in-law"],
    ["நாத்தனார்", "nāttaṉār", "husband's sister"],
    ["மைத்துனி", "maittuṉi", "wife's sister"],
    ["சம்பந்தி", "campanti", "co-parent-in-law"],
    ["பெரியம்மா", "periyammā", "elder aunt"],
    ["சின்னம்மா", "ciṉṉammā", "younger aunt"],
    ["மாற்றாந்தாய்", "māṟṟāntāy", "stepmother"],
    ["மாற்றாந்தகப்பன்", "māṟṟāntakappaṉ", "stepfather"],
    ["தத்துப்பிள்ளை", "tattuppiḷḷai", "adopted child"],
    ["வளர்ப்பு மகள்", "vaḷarppu makaḷ", "adopted daughter"],
    ["வளர்ப்பு மகன்", "vaḷarppu makaṉ", "adopted son"],
    ["வளர்ப்பு சகோதரி", "vaḷarppu cakōtari", "adopted sister"],
    ["வளர்ப்பு சகோதரன்", "vaḷarppu cakōtaraṉ", "adopted brother"],
    ["பிடிக்காது", "piṭikkātu", "dislike"],
    ["குளி", "kuḷi", "bathe"],
    ["வானிலை", "vāṉilai", "weather"],
    ["ஆனி", "āṉi", "Aani (month)"],
    ["ஆவணி", "āvaṇi", "Aavani (month)"],
    ["ஐப்பசி", "aippaci", "Aippasi (month)"],
    ["நண்பர்கள்", "naṇparkaḷ", "friends"],
    ["பேராசிரியர்", "pērāciriyar", "professor"],
    ["நேர்நிகர்", "nērnikar", "virtual"],
    ["பதிவேற்று", "pativēṟṟu", "upload"],
    ["சந்திப்பு", "cantippu", "meeting"],
    ["ஆராய்ச்சி செய்", "ārāycci cey", "do research"],
    ["குறிப்பு எழுது", "kuṟippu eḻutu", "take notes"],
    ["உடற்பயிற்சி", "uṭaṟpayiṟci", "exercise"],
    ["தலை வாரு", "talai vāru", "comb hair"],
    ["பல் தேய்", "pal tēy", "brush teeth"],
    ["ஓய்வு", "ōyvu", "rest"],
    ["நடனம் ஆடு", "naṭaṉam āṭu", "dance"],
    ["சமையல் செய்", "camaiyal cey", "cook"],
    ["பாத்திரம் கழுவு", "pāttiram kaḻuvu", "wash dishes"],
    ["சுத்தம் செய்", "cuttam cey", "clean"],
    ["துணி துவை", "tuṇi tuvai", "wash clothes"],
    ["தயார் ஆகு", "tayār āku", "get ready"],
    ["தாமரை", "tāmarai", "lotus"],
    ["கடல் நீர்", "kaṭal nīr", "seawater"],
    ["அழகு", "aḻaku", "beauty"],
    ["நிறங்கள்", "niṟaṅkaḷ", "colors"],
    ["செம்மஞ்சள்", "cemmañcaḷ", "orange"],
    ["சிகப்பு", "cikappu", "red"],
    ["பரிமாணங்கள்", "parimāṇaṅkaḷ", "dimensions, sizes"],
    ["ஒல்லியான", "olliyāṉa", "thin"],
    ["வடிவங்கள்", "vaṭivaṅkaḷ", "shapes"],
    ["வட்டமான", "vaṭṭamāṉa", "circular"],
    ["நேரான", "nērāṉa", "straight"],
    ["சதுரமான", "caturamāṉa", "square"],
    ["முக்கோணமான", "mukkōṇamāṉa", "triangular"],
    ["சுவைகள்", "cuvaikaḷ", "tastes"],
    ["மோசமான", "mōcamāṉa", "bad"],
    ["காய்ந்த", "kāynta", "dry"],
    ["இலேசான", "ilēcāṉa", "light"],
    ["மிருதுவான", "mirutuvāṉa", "soft"],
    ["இளமையான", "iḷamaiyāṉa", "young"],
    ["அளவுகள்", "aḷavukaḷ", "quantities"],
    ["குறைவான", "kuṟaivāṉa", "few"],
    ["ஏராளமான", "ērāḷamāṉa", "many"],
    ["மிகுந்த", "mikunta", "much"],
    ["முழுமையான", "muḻumaiyāṉa", "whole"],
    ["இப்பொழுது", "ippoḻutu", "now"],
    ["அப்பொழுது", "appoḻutu", "then"],
    ["இன்றிரவு", "iṉṟiravu", "tonight"],
    ["நேற்றிரவு", "nēṟṟiravu", "last night"],
    ["அடுத்த வாரம்", "aṭutta vāram", "next week"],
    ["ஏற்கெனவே", "ēṟkeṉavē", "already"],
    ["அண்மையில்", "aṇmaiyil", "recently"],
    ["விரைவில்", "viraivil", "soon"],
    ["உடனடியாய்", "uṭaṉaṭiyāy", "immediately"],
    ["முன்னர்", "muṉṉar", "ago, before"],
    ["தொலைவில்", "tolaivil", "away, far"],
    ["முற்றிலும்", "muṟṟilum", "completely"],
    ["உண்மையாக", "uṇmaiyāka", "really"],
    ["நன்கு", "naṉku", "well"],
    ["பெரும்பாலும்", "perumpālum", "mostly"],
    ["ஒன்றாய்", "oṉṟāy", "together"],
    ["தன்னந்தனியாக", "taṉṉantaṉiyāka", "alone"],
    ["எப்பொழுதும்", "eppoḻutum", "always"],
    ["சில சமயம்", "cila camayam", "sometimes"],
    ["அரிதாய்", "aritāy", "rarely"],
    ["வலது பக்கம்", "valatu pakkam", "right side"],
    ["இடது பக்கம்", "iṭatu pakkam", "left side"],
    ["பின்பு", "piṉpu", "after"],
    ["ஏறத்தாழ", "ēṟattāḻa", "about / approximately"],
    ["அடுத்து", "aṭuttu", "next to"],
    ["தடியான", "taṭiyāṉa", "thick"],
    ["குழந்தைகள்", "kuḻantaikaḷ", "children"],
    ["மரவீடு", "maravīṭu", "tree house"],
    ["ஐஸ் கிரீம்", "ais kirīm", "ice cream"],
    ["ஓவியம்", "ōviyam", "art / painting"],
    ["விளையாட்டு", "viḷaiyāṭṭu", "play / game"],
    ["இளம் சிவப்பு", "iḷam civappu", "pink"],
    ["பலூன்", "palūṉ", "balloon"],
    ["திசைகள்", "ticaikaḷ", "directions"],
    ["இடங்கள்", "iṭaṅkaḷ", "places"],
    ["வடக்கு", "vaṭakku", "north"],
    ["தெற்கு", "teṟku", "south"],
    ["மேற்கு", "mēṟku", "west"],
    ["வடகிழக்கு", "vaṭakiḻakku", "northeast"],
    ["வடமேற்கு", "vaṭamēṟku", "northwest"],
    ["தென்கிழக்கு", "teṉkiḻakku", "southeast"],
    ["தென்மேற்கு", "teṉmēṟku", "southwest"],
    ["வங்காள விரிகுடா", "vaṅkāḷa virikuṭā", "Bay of Bengal"],
    ["மாநிலம்", "mānilam", "state"],
    ["இலங்கை", "ilaṅkai", "Sri Lanka"],
    ["கர்நாடகா", "karnāṭakā", "Karnataka"],
    ["ஆந்திரப் பிரதேசம்", "āntirap piratēcam", "Andhra Pradesh"],
    ["ஜலசந்தி", "jalacanti", "strait"],
    ["தமிழ்நாடு", "tamiḻnāṭu", "Tamil Nadu"],
    ["இந்தியா", "intiyā", "India"],
    ["இந்தியப் பெருங்கடல்", "intiyap peruṅkaṭal", "Indian Ocean"],
    ["கேரளம்", "kēraḷam", "Kerala"],
    ["ஊர்கள்", "ūrkaḷ", "towns"],
    ["நாய்கள்", "nāykaḷ", "dogs"],
    ["தூக்கம்", "tūkkam", "sleep"],
    ["பஞ்சு", "pañcu", "cotton"],
    ["நஞ்சு", "nañcu", "poison"],
    ["அஞ்சு", "añcu", "fear"],
    ["ஆசை", "ācai", "desire"],
    ["எச்சில்", "eccil", "saliva"],
    ["ஓடம்", "ōṭam", "boat"],
    ["டமாரம்", "ṭamāram", "a drum"],
    ["டீ", "ṭī", "tea"],
    ["பூட்டு", "pūṭṭu", "lock"],
    ["மோது", "mōtu", "collide / strike"],
    ["கத்து", "kattu", "shout / scream"],
    ["கோபம்", "kōpam", "anger"],
    ["அபாயம்", "apāyam", "danger"],
    ["சாபம்", "cāpam", "curse"],
    ["தப்பு", "tappu", "mistake"],
    ["துப்பு", "tuppu", "spit"],
    ["மரத்தை", "marattai", "tree (accusative)"],
    ["நடு", "naṭu", "plant / middle"],
    ["உரி", "uri", "peel"],
    ["மாட்டு", "māṭṭu", "hang"],
    ["தேர்", "tēr", "chariot"],
    ["பாட்டு", "pāṭṭu", "song; poem"],
    ["பிசை", "picai", "knead; mix"],
    ["மிதி", "miti", "step on"],
    ["கூடு", "kūṭu", "nest"],
    ["கல", "kala", "mix"],
    ["நகர்த்து", "nakarttu", "move; shift"],
    ["காப்பாற்று", "kāppāṟṟu", "save; protect"],
    ["தேய்", "tēy", "brush; rub"],
    ["கள்", "kaḷ", "toddy; liquor"],
    ["அரண்", "araṇ", "fort"],
    ["மடி", "maṭi", "fold; die"],
    ["உரல்", "ural", "mortar"],
    ["காய்", "kāy", "vegetable; unripe fruit"],
    ["தின்", "tiṉ", "eat"],
    ["மடக்கு", "maṭakku", "bend; fold"],
    ["பேச்சு", "pēccu", "talk; speech"],
    ["குடிக்காதே", "kuṭikkātē", "do not drink"],
    ["ஆல்", "āl", "by; with (instrumental)"],
    ["குறடு", "kuṟaṭu", "pliers; tongs"],
    ["ஆணி", "āṇi", "nail (metal)"],
    ["நறுக்கு", "naṟukku", "cut; chop"],
    ["வெட்டி", "veṭṭi", "useless; idle"],
    ["கிள்ளு", "kiḷḷu", "pinch"],
    ["பகை", "pakai", "enmity; hostility"],
    ["கலக்கு", "kalakku", "mix; stir"],
    ["பிடுங்கு", "piṭuṅku", "pull; pluck"],
    ["செங்கல்", "ceṅkal", "brick"],
    ["நீர்", "nīr", "water"],
    ["கூர்மை", "kūrmai", "sharpness"],
    ["பூசு", "pūcu", "apply; smear (paint)"],
    ["சட்டம்", "caṭṭam", "frame; law"],
    ["கைதட்டல்", "kaitaṭṭal", "applause"],
    ["பஞ்சம்", "pañcam", "scarcity; famine"],
    ["குறை", "kuṟai", "shortcoming; defect"],
    ["உறை", "uṟai", "cover; sheath"],
    ["தோடு", "tōṭu", "earring"],
    ["உண்டு", "uṇṭu", "there is; it has"],
    ["பெரியவன்", "periyavaṉ", "elder; older one"],
    ["கிடைக்கும்", "kiṭaikkum", "is available; will be obtained"],
    ["அவிழ்", "aviḻ", "untie"],
    ["பருக்கை", "parukkai", "morsel of rice"],
    ["இறை", "iṟai", "scoop and pour; lord"],
    ["கண்ணீர்", "kaṇṇīr", "tears"],
    ["வெண்மை", "veṇmai", "whiteness"],
    ["ஆழம்", "āḻam", "depth"],
    ["சண்டை", "caṇṭai", "fight"],
    ["வண்டு", "vaṇṭu", "bee; beetle"],
    ["மொய்", "moy", "swarm; throng"],
    ["அச்சு", "accu", "axle"],
    ["உழவன்", "uḻavaṉ", "farmer"],
    ["வினைச்சொல்", "viṉaiccol", "verb"],
  ])
);

/* ------------------------------ Sentences ------------------------------ */
// words: tokens for the "build" mode, in order, each with its transliteration.
const S = (topic, rows) =>
  rows.map(([ta, tr, en, words]) => ({
    ta, tr, en, topic,
    words: words.map(([wta, wtr]) => ({ ta: wta, tr: wtr })),
  }));

const SENTENCES = [].concat(
  S("greetings", [
    ["வணக்கம், எப்படி இருக்கிறீர்கள்?", "vaṇakkam, eppaṭi irukkiṟīrkaḷ?", "Hello, how are you?",
      [["வணக்கம்","vaṇakkam"],["எப்படி","eppaṭi"],["இருக்கிறீர்கள்","irukkiṟīrkaḷ"]]],
    ["நான் நலமாக இருக்கிறேன்", "nāṉ nalamāka irukkiṟēṉ", "I am fine",
      [["நான்","nāṉ"],["நலமாக","nalamāka"],["இருக்கிறேன்","irukkiṟēṉ"]]],
    ["உங்கள் பெயர் என்ன?", "uṅkaḷ peyar eṉṉa?", "What is your name?",
      [["உங்கள்","uṅkaḷ"],["பெயர்","peyar"],["என்ன","eṉṉa"]]],
    ["என் பெயர் ராஜா", "eṉ peyar rājā", "My name is Raja",
      [["என்","eṉ"],["பெயர்","peyar"],["ராஜா","rājā"]]],
    ["எனக்கு புரியவில்லை", "eṉakku puriyavillai", "I don't understand",
      [["எனக்கு","eṉakku"],["புரியவில்லை","puriyavillai"]]],
    ["மீண்டும் சொல்லுங்கள்", "mīṇṭum colluṅkaḷ", "Please say it again",
      [["மீண்டும்","mīṇṭum"],["சொல்லுங்கள்","colluṅkaḷ"]]],
  ]),
  S("food", [
    ["எனக்கு தண்ணீர் வேண்டும்", "eṉakku taṇṇīr vēṇṭum", "I want water",
      [["எனக்கு","eṉakku"],["தண்ணீர்","taṇṇīr"],["வேண்டும்","vēṇṭum"]]],
    ["நான் சாதம் சாப்பிடுகிறேன்", "nāṉ sātam sāppiṭukiṟēṉ", "I am eating rice",
      [["நான்","nāṉ"],["சாதம்","sātam"],["சாப்பிடுகிறேன்","sāppiṭukiṟēṉ"]]],
    ["அவள் பால் குடிக்கிறாள்", "avaḷ pāl kuṭikkiṟāḷ", "She is drinking milk",
      [["அவள்","avaḷ"],["பால்","pāl"],["குடிக்கிறாள்","kuṭikkiṟāḷ"]]],
    ["இந்த சாப்பாடு சுவையாக இருக்கிறது", "inta sāppāṭu cuvaiyāka irukkiṟatu", "This food is tasty",
      [["இந்த","inta"],["சாப்பாடு","sāppāṭu"],["சுவையாக","cuvaiyāka"],["இருக்கிறது","irukkiṟatu"]]],
    ["எனக்கு காபி பிடிக்கும்", "eṉakku kāpi piṭikkum", "I like coffee",
      [["எனக்கு","eṉakku"],["காபி","kāpi"],["பிடிக்கும்","piṭikkum"]]],
  ]),
  S("verbs", [
    ["நான் பள்ளிக்கு போகிறேன்", "nāṉ paḷḷikku pōkiṟēṉ", "I am going to school",
      [["நான்","nāṉ"],["பள்ளிக்கு","paḷḷikku"],["போகிறேன்","pōkiṟēṉ"]]],
    ["அவன் புத்தகம் படிக்கிறான்", "avaṉ puttakam paṭikkiṟāṉ", "He is reading a book",
      [["அவன்","avaṉ"],["புத்தகம்","puttakam"],["படிக்கிறான்","paṭikkiṟāṉ"]]],
    ["நாங்கள் விளையாடுகிறோம்", "nāṅkaḷ viḷaiyāṭukiṟōm", "We are playing",
      [["நாங்கள்","nāṅkaḷ"],["விளையாடுகிறோம்","viḷaiyāṭukiṟōm"]]],
    ["நீ எங்கே போகிறாய்?", "nī eṅkē pōkiṟāy?", "Where are you going?",
      [["நீ","nī"],["எங்கே","eṅkē"],["போகிறாய்","pōkiṟāy"]]],
    ["அவர்கள் வேலை செய்கிறார்கள்", "avarkaḷ vēlai ceykiṟārkaḷ", "They are working",
      [["அவர்கள்","avarkaḷ"],["வேலை","vēlai"],["செய்கிறார்கள்","ceykiṟārkaḷ"]]],
    ["நான் தமிழ் கற்கிறேன்", "nāṉ tamiḻ kaṟkiṟēṉ", "I am learning Tamil",
      [["நான்","nāṉ"],["தமிழ்","tamiḻ"],["கற்கிறேன்","kaṟkiṟēṉ"]]],
    ["நீங்கள் என்ன செய்கிறீர்கள்?", "nīṅkaḷ eṉṉa ceykiṟīrkaḷ?", "What are you doing?",
      [["நீங்கள்","nīṅkaḷ"],["என்ன","eṉṉa"],["செய்கிறீர்கள்","ceykiṟīrkaḷ"]]],
  ]),
  S("family", [
    ["இது என் அம்மா", "itu eṉ ammā", "This is my mother",
      [["இது","itu"],["என்","eṉ"],["அம்மா","ammā"]]],
    ["என் அப்பா வேலைக்கு போகிறார்", "eṉ appā vēlaikku pōkiṟār", "My father goes to work",
      [["என்","eṉ"],["அப்பா","appā"],["வேலைக்கு","vēlaikku"],["போகிறார்","pōkiṟār"]]],
    ["எனக்கு ஒரு தம்பி இருக்கிறான்", "eṉakku oru tampi irukkiṟāṉ", "I have a younger brother",
      [["எனக்கு","eṉakku"],["ஒரு","oru"],["தம்பி","tampi"],["இருக்கிறான்","irukkiṟāṉ"]]],
  ]),
  S("time", [
    ["இன்று திங்கள்", "iṉṟu tiṅkaḷ", "Today is Monday",
      [["இன்று","iṉṟu"],["திங்கள்","tiṅkaḷ"]]],
    ["இப்போது மணி என்ன?", "ippōtu maṇi eṉṉa?", "What time is it now?",
      [["இப்போது","ippōtu"],["மணி","maṇi"],["என்ன","eṉṉa"]]],
  ]),
  S("nature", [
    ["வானம் நீலமாக இருக்கிறது", "vāṉam nīlamāka irukkiṟatu", "The sky is blue",
      [["வானம்","vāṉam"],["நீலமாக","nīlamāka"],["இருக்கிறது","irukkiṟatu"]]],
    ["இன்று மழை பெய்கிறது", "iṉṟu maḻai peykiṟatu", "It is raining today",
      [["இன்று","iṉṟu"],["மழை","maḻai"],["பெய்கிறது","peykiṟatu"]]],
    ["இந்த பூ அழகாக இருக்கிறது", "inta pū aḻakāka irukkiṟatu", "This flower is beautiful",
      [["இந்த","inta"],["பூ","pū"],["அழகாக","aḻakāka"],["இருக்கிறது","irukkiṟatu"]]],
  ]),
  S("places", [
    ["கடை எங்கே இருக்கிறது?", "kaṭai eṅkē irukkiṟatu?", "Where is the shop?",
      [["கடை","kaṭai"],["எங்கே","eṅkē"],["இருக்கிறது","irukkiṟatu"]]],
    ["நான் சந்தைக்கு போகிறேன்", "nāṉ cantaikku pōkiṟēṉ", "I am going to the market",
      [["நான்","nāṉ"],["சந்தைக்கு","cantaikku"],["போகிறேன்","pōkiṟēṉ"]]],
    ["நான் வீட்டில் இருக்கிறேன்", "nāṉ vīṭṭil irukkiṟēṉ", "I am at home",
      [["நான்","nāṉ"],["வீட்டில்","vīṭṭil"],["இருக்கிறேன்","irukkiṟēṉ"]]],
  ]),
  S("sentences", [
    ["நான் நேற்று வந்தேன்", "nāṉ nēṟṟu vantēṉ", "I came yesterday (past)",
      [["நான்","nāṉ"],["நேற்று","nēṟṟu"],["வந்தேன்","vantēṉ"]]],
    ["நான் இன்று வருகிறேன்", "nāṉ iṉṟu varukiṟēṉ", "I am coming today (present)",
      [["நான்","nāṉ"],["இன்று","iṉṟu"],["வருகிறேன்","varukiṟēṉ"]]],
    ["நான் நாளை வருவேன்", "nāṉ nāḷai varuvēṉ", "I will come tomorrow (future)",
      [["நான்","nāṉ"],["நாளை","nāḷai"],["வருவேன்","varuvēṉ"]]],
    ["எனக்கு தமிழ் தெரியும்", "eṉakku tamiḻ teriyum", "I know Tamil",
      [["எனக்கு","eṉakku"],["தமிழ்","tamiḻ"],["தெரியும்","teriyum"]]],
    ["இது மிகவும் நல்லது", "itu mikavum nallatu", "This is very good",
      [["இது","itu"],["மிகவும்","mikavum"],["நல்லது","nallatu"]]],
  ]),
  S("greetings", [
    ["நீங்கள் எப்படி இருக்கிறீர்கள்?", "nīṅkaḷ eppaṭi irukkiṟīrkaḷ?", "How are you?",
      [["நீங்கள்", "nīṅkaḷ"], ["எப்படி", "eppaṭi"], ["இருக்கிறீர்கள்", "irukkiṟīrkaḷ"]]],
    ["நான் நன்றாக இருக்கிறேன்", "nāṉ naṉṟāka irukkiṟēṉ", "I am well",
      [["நான்", "nāṉ"], ["நன்றாக", "naṉṟāka"], ["இருக்கிறேன்", "irukkiṟēṉ"]]],
    ["உங்களை சந்தித்ததில் மகிழ்ச்சி", "uṅkaḷai cantittatil makiḻcci", "Nice to meet you",
      [["உங்களை", "uṅkaḷai"], ["சந்தித்ததில்", "cantittatil"], ["மகிழ்ச்சி", "makiḻcci"]]],
    ["என் பெயர் குமார்", "eṉ peyar kumār", "My name is Kumar",
      [["என்", "eṉ"], ["பெயர்", "peyar"], ["குமார்", "kumār"]]],
    ["நீங்கள் எங்கிருந்து வருகிறீர்கள்?", "nīṅkaḷ eṅkiruntu varukiṟīrkaḷ?", "Where are you from?",
      [["நீங்கள்", "nīṅkaḷ"], ["எங்கிருந்து", "eṅkiruntu"], ["வருகிறீர்கள்", "varukiṟīrkaḷ"]]],
    ["நான் இந்தியாவைச் சேர்ந்தவன்", "nāṉ intiyāvaic cērntavaṉ", "I am from India",
      [["நான்", "nāṉ"], ["இந்தியாவைச்", "intiyāvaic"], ["சேர்ந்தவன்", "cērntavaṉ"]]],
    ["உங்களைச் சந்தித்ததில் மகிழ்ச்சி", "uṅkaḷaic cantittatil makiḻcci", "Nice to meet you",
      [["உங்களைச்", "uṅkaḷaic"], ["சந்தித்ததில்", "cantittatil"], ["மகிழ்ச்சி", "makiḻcci"]]],
    ["எனக்கு சோர்வாக இருக்கிறது", "eṉakku cōrvāka irukkiṟatu", "I am tired",
      [["எனக்கு", "eṉakku"], ["சோர்வாக", "cōrvāka"], ["இருக்கிறது", "irukkiṟatu"]]],
    ["நான் மகிழ்ச்சியாக இருக்கிறேன்", "nāṉ makiḻcciyāka irukkiṟēṉ", "I am happy",
      [["நான்", "nāṉ"], ["மகிழ்ச்சியாக", "makiḻcciyāka"], ["இருக்கிறேன்", "irukkiṟēṉ"]]],
    ["எனக்கு உடல்நிலை சரியில்லை", "eṉakku uṭalnilai cariyillai", "I am not well",
      [["எனக்கு", "eṉakku"], ["உடல்நிலை", "uṭalnilai"], ["சரியில்லை", "cariyillai"]]],
    ["எனக்கு தாகமாக இருக்கிறது", "eṉakku tākamāka irukkiṟatu", "I am thirsty",
      [["எனக்கு", "eṉakku"], ["தாகமாக", "tākamāka"], ["இருக்கிறது", "irukkiṟatu"]]],
    ["தயவுசெய்து மீண்டும் சொல்லுங்கள்", "tayavuceytu mīṇṭum colluṅkaḷ", "Please say it again",
      [["தயவுசெய்து", "tayavuceytu"], ["மீண்டும்", "mīṇṭum"], ["சொல்லுங்கள்", "colluṅkaḷ"]]],
    ["தயவுசெய்து எனக்கு உதவுங்கள்", "tayavuceytu eṉakku utavuṅkaḷ", "Please help me",
      [["தயவுசெய்து", "tayavuceytu"], ["எனக்கு", "eṉakku"], ["உதவுங்கள்", "utavuṅkaḷ"]]],
    ["நான் உள்ளே வரலாமா?", "nāṉ uḷḷē varalāmā?", "May I come in?",
      [["நான்", "nāṉ"], ["உள்ளே", "uḷḷē"], ["வரலாமா", "varalāmā"]]],
    ["மெதுவாக பேசுங்கள்", "metuvāka pēcuṅkaḷ", "Please speak slowly",
      [["மெதுவாக", "metuvāka"], ["பேசுங்கள்", "pēcuṅkaḷ"]]],
  ]),
  S("family", [
    ["என் அப்பா ஒரு ஆசிரியர்", "eṉ appā oru āciriyar", "My father is a teacher",
      [["என்", "eṉ"], ["அப்பா", "appā"], ["ஒரு", "oru"], ["ஆசிரியர்", "āciriyar"]]],
    ["எனக்கு இரண்டு சகோதரிகள் இருக்கிறார்கள்", "eṉakku iraṇṭu cakōtarikaḷ irukkiṟārkaḷ", "I have two sisters",
      [["எனக்கு", "eṉakku"], ["இரண்டு", "iraṇṭu"], ["சகோதரிகள்", "cakōtarikaḷ"], ["இருக்கிறார்கள்", "irukkiṟārkaḷ"]]],
    ["இது என் குடும்பம்", "itu eṉ kuṭumpam", "This is my family",
      [["இது", "itu"], ["என்", "eṉ"], ["குடும்பம்", "kuṭumpam"]]],
    ["என் அக்கா ஒரு மருத்துவர்", "eṉ akkā oru maruttuvar", "My elder sister is a doctor",
      [["என்", "eṉ"], ["அக்கா", "akkā"], ["ஒரு", "oru"], ["மருத்துவர்", "maruttuvar"]]],
    ["உங்கள் குடும்பம் எப்படி இருக்கிறது?", "uṅkaḷ kuṭumpam eppaṭi irukkiṟatu?", "How is your family?",
      [["உங்கள்", "uṅkaḷ"], ["குடும்பம்", "kuṭumpam"], ["எப்படி", "eppaṭi"], ["இருக்கிறது", "irukkiṟatu"]]],
  ]),
  S("food", [
    ["எனக்கு தேநீர் பிடிக்கும்", "eṉakku tēnīr piṭikkum", "I like tea",
      [["எனக்கு", "eṉakku"], ["தேநீர்", "tēnīr"], ["பிடிக்கும்", "piṭikkum"]]],
    ["இந்த உணவு சுவையாக இருக்கிறது", "inta uṇavu cuvaiyāka irukkiṟatu", "This food is tasty",
      [["இந்த", "inta"], ["உணவு", "uṇavu"], ["சுவையாக", "cuvaiyāka"], ["இருக்கிறது", "irukkiṟatu"]]],
    ["எனக்கு பசிக்கிறது", "eṉakku pacikkiṟatu", "I am hungry",
      [["எனக்கு", "eṉakku"], ["பசிக்கிறது", "pacikkiṟatu"]]],
    ["நான் சாப்பிட விரும்புகிறேன்", "nāṉ cāppiṭa virumpukiṟēṉ", "I want to eat",
      [["நான்", "nāṉ"], ["சாப்பிட", "cāppiṭa"], ["விரும்புகிறேன்", "virumpukiṟēṉ"]]],
    ["உங்களுக்கு பால் வேண்டுமா?", "uṅkaḷukku pāl vēṇṭumā?", "Do you want milk?",
      [["உங்களுக்கு", "uṅkaḷukku"], ["பால்", "pāl"], ["வேண்டுமா", "vēṇṭumā"]]],
  ]),
  S("places", [
    ["இந்த பொருள் எவ்வளவு?", "inta poruḷ evvaḷavu?", "How much is this item?",
      [["இந்த", "inta"], ["பொருள்", "poruḷ"], ["எவ்வளவு", "evvaḷavu"]]],
    ["நான் இதை வாங்க வேண்டும்", "nāṉ itai vāṅka vēṇṭum", "I want to buy this",
      [["நான்", "nāṉ"], ["இதை", "itai"], ["வாங்க", "vāṅka"], ["வேண்டும்", "vēṇṭum"]]],
    ["இது மிகவும் விலை உயர்ந்தது", "itu mikavum vilai uyarntatu", "This is very expensive",
      [["இது", "itu"], ["மிகவும்", "mikavum"], ["விலை", "vilai"], ["உயர்ந்தது", "uyarntatu"]]],
    ["சந்தையில் விலை குறைவாக உள்ளது", "cantaiyil vilai kuṟaivāka uḷḷatu", "At the market the price is low",
      [["சந்தையில்", "cantaiyil"], ["விலை", "vilai"], ["குறைவாக", "kuṟaivāka"], ["உள்ளது", "uḷḷatu"]]],
    ["நான் சந்தைக்குச் செல்கிறேன்", "nāṉ cantaikkuc celkiṟēṉ", "I am going to the market",
      [["நான்", "nāṉ"], ["சந்தைக்குச்", "cantaikkuc"], ["செல்கிறேன்", "celkiṟēṉ"]]],
    ["நீங்கள் நேராக செல்லுங்கள்", "nīṅkaḷ nērāka celluṅkaḷ", "You go straight",
      [["நீங்கள்", "nīṅkaḷ"], ["நேராக", "nērāka"], ["செல்லுங்கள்", "celluṅkaḷ"]]],
    ["மருத்துவமனை அருகில் இருக்கிறது", "maruttuvamaṉai arukil irukkiṟatu", "The hospital is near",
      [["மருத்துவமனை", "maruttuvamaṉai"], ["அருகில்", "arukil"], ["இருக்கிறது", "irukkiṟatu"]]],
    ["அங்கே இடதுபுறம் திரும்புங்கள்", "aṅkē iṭatupuṟam tirumpuṅkaḷ", "Turn left there",
      [["அங்கே", "aṅkē"], ["இடதுபுறம்", "iṭatupuṟam"], ["திரும்புங்கள்", "tirumpuṅkaḷ"]]],
    ["பேருந்து நிலையம் எங்கே இருக்கிறது?", "pēruntu nilaiyam eṅkē irukkiṟatu?", "Where is the bus station?",
      [["பேருந்து", "pēruntu"], ["நிலையம்", "nilaiyam"], ["எங்கே", "eṅkē"], ["இருக்கிறது", "irukkiṟatu"]]],
  ]),
  S("time", [
    ["இன்று திங்கட்கிழமை", "iṉṟu tiṅkaṭkiḻamai", "Today is Monday",
      [["இன்று", "iṉṟu"], ["திங்கட்கிழமை", "tiṅkaṭkiḻamai"]]],
    ["நான் காலையில் எழுகிறேன்", "nāṉ kālaiyil eḻukiṟēṉ", "I wake up in the morning",
      [["நான்", "nāṉ"], ["காலையில்", "kālaiyil"], ["எழுகிறேன்", "eḻukiṟēṉ"]]],
    ["இப்போது எட்டு மணி", "ippōtu eṭṭu maṇi", "It is eight o'clock now",
      [["இப்போது", "ippōtu"], ["எட்டு", "eṭṭu"], ["மணி", "maṇi"]]],
    ["நான் இரவில் தூங்குகிறேன்", "nāṉ iravil tūṅkukiṟēṉ", "I sleep at night",
      [["நான்", "nāṉ"], ["இரவில்", "iravil"], ["தூங்குகிறேன்", "tūṅkukiṟēṉ"]]],
  ]),
  S("adjectives", [
    ["இந்த வீடு பெரியது", "inta vīṭu periyatu", "This house is big",
      [["இந்த", "inta"], ["வீடு", "vīṭu"], ["பெரியது", "periyatu"]]],
    ["அவள் உயரமாக இருக்கிறாள்", "avaḷ uyaramāka irukkiṟāḷ", "She is tall",
      [["அவள்", "avaḷ"], ["உயரமாக", "uyaramāka"], ["இருக்கிறாள்", "irukkiṟāḷ"]]],
    ["அந்த மலர் அழகாக இருக்கிறது", "anta malar aḻakāka irukkiṟatu", "That flower is beautiful",
      [["அந்த", "anta"], ["மலர்", "malar"], ["அழகாக", "aḻakāka"], ["இருக்கிறது", "irukkiṟatu"]]],
    ["என் அறை சிறியது", "eṉ aṟai ciṟiyatu", "My room is small",
      [["என்", "eṉ"], ["அறை", "aṟai"], ["சிறியது", "ciṟiyatu"]]],
  ]),
  S("verbs", [
    ["நான் பள்ளிக்குப் போகிறேன்", "nāṉ paḷḷikkup pōkiṟēṉ", "I am going to school",
      [["நான்", "nāṉ"], ["பள்ளிக்குப்", "paḷḷikkup"], ["போகிறேன்", "pōkiṟēṉ"]]],
    ["அவன் ஒரு புத்தகம் படித்தான்", "avaṉ oru puttakam paṭittāṉ", "He read a book",
      [["அவன்", "avaṉ"], ["ஒரு", "oru"], ["புத்தகம்", "puttakam"], ["படித்தான்", "paṭittāṉ"]]],
    ["நாங்கள் நாளை வருவோம்", "nāṅkaḷ nāḷai varuvōm", "We will come tomorrow",
      [["நாங்கள்", "nāṅkaḷ"], ["நாளை", "nāḷai"], ["வருவோம்", "varuvōm"]]],
    ["அவள் உணவு சாப்பிடுகிறாள்", "avaḷ uṇavu cāppiṭukiṟāḷ", "She is eating food",
      [["அவள்", "avaḷ"], ["உணவு", "uṇavu"], ["சாப்பிடுகிறாள்", "cāppiṭukiṟāḷ"]]],
    ["நான் நேற்று வீட்டில் இருந்தேன்", "nāṉ nēṟṟu vīṭṭil iruntēṉ", "I was at home yesterday",
      [["நான்", "nāṉ"], ["நேற்று", "nēṟṟu"], ["வீட்டில்", "vīṭṭil"], ["இருந்தேன்", "iruntēṉ"]]],
  ]),
  S("numbers", [
    ["என்னிடம் மூன்று புத்தகங்கள் உள்ளன", "eṉṉiṭam mūṉṟu puttakaṅkaḷ uḷḷaṉa", "I have three books",
      [["என்னிடம்", "eṉṉiṭam"], ["மூன்று", "mūṉṟu"], ["புத்தகங்கள்", "puttakaṅkaḷ"], ["உள்ளன", "uḷḷaṉa"]]],
    ["எனக்கு இரண்டு கொடுங்கள்", "eṉakku iraṇṭu koṭuṅkaḷ", "Give me two",
      [["எனக்கு", "eṉakku"], ["இரண்டு", "iraṇṭu"], ["கொடுங்கள்", "koṭuṅkaḷ"]]],
    ["அங்கே ஐந்து பேர் இருக்கிறார்கள்", "aṅkē aintu pēr irukkiṟārkaḷ", "There are five people there",
      [["அங்கே", "aṅkē"], ["ஐந்து", "aintu"], ["பேர்", "pēr"], ["இருக்கிறார்கள்", "irukkiṟārkaḷ"]]],
    ["எனக்கு ஒரு கப் தேநீர் வேண்டும்", "eṉakku oru kap tēnīr vēṇṭum", "I want one cup of tea",
      [["எனக்கு", "eṉakku"], ["ஒரு", "oru"], ["கப்", "kap"], ["தேநீர்", "tēnīr"], ["வேண்டும்", "vēṇṭum"]]],
    ["இந்த வகுப்பில் பத்து மாணவர்கள் உள்ளனர்", "inta vakuppil pattu māṇavarkaḷ uḷḷaṉar", "There are ten students in this class",
      [["இந்த", "inta"], ["வகுப்பில்", "vakuppil"], ["பத்து", "pattu"], ["மாணவர்கள்", "māṇavarkaḷ"], ["உள்ளனர்", "uḷḷaṉar"]]],
  ])
);

if (typeof window !== "undefined") {
  window.TOPICS = TOPICS;
  window.VOCAB = VOCAB;
  window.SENTENCES = SENTENCES;
  window.ALPHABET = ALPHABET;
}
