/* ============================================================================
 * Arabic course (Modern Standard Arabic) — data only.
 *
 * `ta` is the Arabic, written with the short vowels where they help a learner,
 * `tr` its transliteration (ḥ ṣ ḍ ṭ ẓ ʿ ʾ ā ī ū …), `en` the meaning. Nouns
 * are given with the definite article only where that's the usual citation
 * form. Arabic is written right to left; the app handles that for you.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------- Abjad --------------------------------- */
  const LETTERS = A([
    ["ا", "alif", "a / ā"], ["ب", "bāʾ", "b"], ["ت", "tāʾ", "t"], ["ث", "thāʾ", "th"],
    ["ج", "jīm", "j"], ["ح", "ḥāʾ", "ḥ — a breathy h"], ["خ", "khāʾ", "kh"],
    ["د", "dāl", "d"], ["ذ", "dhāl", "dh"], ["ر", "rāʾ", "r"], ["ز", "zāy", "z"],
    ["س", "sīn", "s"], ["ش", "shīn", "sh"], ["ص", "ṣād", "ṣ — emphatic s"],
    ["ض", "ḍād", "ḍ — emphatic d"], ["ط", "ṭāʾ", "ṭ — emphatic t"],
    ["ظ", "ẓāʾ", "ẓ — emphatic dh"], ["ع", "ʿayn", "ʿ — from the throat"],
    ["غ", "ghayn", "gh — like a French r"], ["ف", "fāʾ", "f"], ["ق", "qāf", "q — deep k"],
    ["ك", "kāf", "k"], ["ل", "lām", "l"], ["م", "mīm", "m"], ["ن", "nūn", "n"],
    ["ه", "hāʾ", "h"], ["و", "wāw", "w / ū"], ["ي", "yāʾ", "y / ī"],
  ]);
  const SOUNDS = A([
    ["ـَ", "fatḥa", "short a"], ["ـِ", "kasra", "short i"], ["ـُ", "ḍamma", "short u"],
    ["ـْ", "sukūn", "no vowel"], ["ـّ", "shadda", "doubles the letter"],
    ["ال", "al-", "the definite article 'the'"],
    ["ة", "tāʾ marbūṭa", "final -a, marks feminine"],
    ["ـً", "tanwīn", "the -an ending"],
    ["ء", "hamza", "a glottal stop"],
    ["sun letters", "ash-shams", "al- assimilates: al-shams → ash-shams"],
  ]);
  const ALPHABET = { vowels: LETTERS, consonants: SOUNDS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["مَرْحَبًا", "marḥaban", "hello"],
      ["السَّلامُ عَلَيْكُم", "as-salāmu ʿalaykum", "peace be upon you (hello)"],
      ["وَعَلَيْكُمُ السَّلام", "wa-ʿalaykumu s-salām", "and upon you peace (reply)"],
      ["صَباحُ الخَيْر", "ṣabāḥu l-khayr", "good morning"],
      ["مَساءُ الخَيْر", "masāʾu l-khayr", "good evening"],
      ["تُصْبِحُ عَلى خَيْر", "tuṣbiḥu ʿalā khayr", "good night"],
      ["مَعَ السَّلامة", "maʿa s-salāma", "goodbye"],
      ["إلى اللِّقاء", "ilā l-liqāʾ", "see you again"],
      ["شُكْرًا", "shukran", "thank you"],
      ["شُكْرًا جَزيلًا", "shukran jazīlan", "thank you very much"],
      ["عَفْوًا", "ʿafwan", "you're welcome / excuse me"],
      ["مِنْ فَضْلِك", "min faḍlik", "please"],
      ["نَعَم", "naʿam", "yes"], ["لا", "lā", "no"],
      ["آسِف", "āsif", "sorry"],
      ["كَيْفَ حالُك؟", "kayfa ḥāluk", "how are you?"],
      ["أَنا بِخَيْر", "anā bi-khayr", "I am well"],
      ["الحَمْدُ لله", "al-ḥamdu li-llāh", "praise be to God (I'm fine)"],
      ["تَشَرَّفْنا", "tasharrafnā", "pleased to meet you"],
      ["أَهْلًا وَسَهْلًا", "ahlan wa-sahlan", "welcome"],
      ["مَبْروك", "mabrūk", "congratulations"],
      ["بِالتَّوْفيق", "bi-t-tawfīq", "good luck"],
      ["حَسَنًا", "ḥasanan", "okay"],
      ["إِنْ شاءَ الله", "in shāʾa llāh", "God willing"],
      ["ما اسْمُك؟", "mā ismuk", "what is your name?"],
      ["اسْمي", "ismī", "my name is"],
    ]),
    V("numbers", [
      ["صِفْر", "ṣifr", "zero"], ["واحِد", "wāḥid", "one"], ["اِثْنان", "ithnān", "two"],
      ["ثَلاثة", "thalātha", "three"], ["أَرْبَعة", "arbaʿa", "four"],
      ["خَمْسة", "khamsa", "five"], ["سِتّة", "sitta", "six"], ["سَبْعة", "sabʿa", "seven"],
      ["ثَمانِية", "thamāniya", "eight"], ["تِسْعة", "tisʿa", "nine"],
      ["عَشَرة", "ʿashara", "ten"], ["أَحَدَ عَشَر", "aḥada ʿashar", "eleven"],
      ["اِثْنا عَشَر", "ithnā ʿashar", "twelve"], ["عِشْرون", "ʿishrūn", "twenty"],
      ["ثَلاثون", "thalāthūn", "thirty"], ["أَرْبَعون", "arbaʿūn", "forty"],
      ["خَمْسون", "khamsūn", "fifty"], ["مِئة", "miʾa", "one hundred"],
      ["أَلْف", "alf", "one thousand"], ["مِلْيون", "milyūn", "million"],
      ["الأَوَّل", "al-awwal", "the first"], ["الثّاني", "ath-thānī", "the second"],
      ["الأَخير", "al-akhīr", "the last"], ["نِصْف", "niṣf", "half"],
      ["رُبْع", "rubʿ", "quarter"], ["رَقَم", "raqam", "number"],
      ["كَثير", "kathīr", "many"], ["قَليل", "qalīl", "few"],
    ]),
    V("colors", [
      ["أَحْمَر", "aḥmar", "red"], ["أَزْرَق", "azraq", "blue"],
      ["أَخْضَر", "akhḍar", "green"], ["أَصْفَر", "aṣfar", "yellow"],
      ["أَسْوَد", "aswad", "black"], ["أَبْيَض", "abyaḍ", "white"],
      ["رَمادي", "ramādī", "grey"], ["بُنّي", "bunnī", "brown"],
      ["بُرْتُقالي", "burtuqālī", "orange"], ["وَرْدي", "wardī", "pink"],
      ["بَنَفْسَجي", "banafsajī", "purple"], ["ذَهَبي", "dhahabī", "golden"],
      ["فِضّي", "fiḍḍī", "silver"], ["فاتِح", "fātiḥ", "light (colour)"],
      ["داكِن", "dākin", "dark"], ["لَوْن", "lawn", "colour"],
      ["مُلَوَّن", "mulawwan", "colourful"], ["شاحِب", "shāḥib", "pale"],
      ["لامِع", "lāmiʿ", "shiny"], ["سَماوي", "samāwī", "sky blue"],
    ]),
    V("family", [
      ["عائِلة", "ʿāʾila", "family"], ["أُسْرة", "usra", "household / family"],
      ["أُمّ", "umm", "mother"], ["أَب", "ab", "father"],
      ["والِدَيْن", "wālidayn", "parents"], ["اِبْن", "ibn", "son"],
      ["بِنْت", "bint", "daughter / girl"], ["أَخ", "akh", "brother"],
      ["أُخْت", "ukht", "sister"], ["جَدّ", "jadd", "grandfather"],
      ["جَدّة", "jadda", "grandmother"], ["حَفيد", "ḥafīd", "grandson"],
      ["عَمّ", "ʿamm", "paternal uncle"], ["عَمّة", "ʿamma", "paternal aunt"],
      ["خال", "khāl", "maternal uncle"], ["خالة", "khāla", "maternal aunt"],
      ["اِبْنُ العَمّ", "ibnu l-ʿamm", "cousin (m)"], ["زَوْج", "zawj", "husband"],
      ["زَوْجة", "zawja", "wife"], ["طِفْل", "ṭifl", "child"],
      ["رَضيع", "raḍīʿ", "baby"], ["قَريب", "qarīb", "relative / near"],
      ["زَواج", "zawāj", "marriage"], ["عُرْس", "ʿurs", "wedding"],
    ]),
    V("people", [
      ["إِنْسان", "insān", "human being"], ["شَخْص", "shakhṣ", "person"],
      ["ناس", "nās", "people"], ["رَجُل", "rajul", "man"],
      ["اِمْرَأة", "imraʾa", "woman"], ["وَلَد", "walad", "boy"],
      ["صَديق", "ṣadīq", "friend (m)"], ["صَديقة", "ṣadīqa", "friend (f)"],
      ["جار", "jār", "neighbour"], ["ضَيْف", "ḍayf", "guest"],
      ["شابّ", "shābb", "young man"], ["شَيْخ", "shaykh", "elder"],
      ["أَجْنَبي", "ajnabī", "foreigner"], ["زَميل", "zamīl", "colleague"],
      ["فَريق", "farīq", "team"], ["مَجْموعة", "majmūʿa", "group"],
      ["اِسْم", "ism", "name"], ["سَيِّد", "sayyid", "Mr / sir"],
      ["سَيِّدة", "sayyida", "Mrs / madam"], ["شَعْب", "shaʿb", "a people"],
      ["مُواطِن", "muwāṭin", "citizen"], ["جُمْهور", "jumhūr", "crowd / public"],
    ]),
    V("pronouns", [
      ["أَنا", "anā", "I"], ["أَنْتَ", "anta", "you (m)"], ["أَنْتِ", "anti", "you (f)"],
      ["هُوَ", "huwa", "he"], ["هِيَ", "hiya", "she"], ["نَحْنُ", "naḥnu", "we"],
      ["أَنْتُم", "antum", "you (plural)"], ["هُم", "hum", "they (m)"],
      ["هُنَّ", "hunna", "they (f)"], ["ـي", "-ī", "my"], ["ـكَ", "-ka", "your (m)"],
      ["ـكِ", "-ki", "your (f)"], ["ـهُ", "-hu", "his"], ["ـها", "-hā", "her"],
      ["ـنا", "-nā", "our"], ["ـهُم", "-hum", "their"],
      ["هٰذا", "hādhā", "this (m)"], ["هٰذِهِ", "hādhihi", "this (f)"],
      ["ذٰلِكَ", "dhālika", "that (m)"], ["تِلْكَ", "tilka", "that (f)"],
      ["أَحَد", "aḥad", "someone"], ["لا أَحَد", "lā aḥad", "nobody"],
      ["كُلّ", "kull", "all / every"], ["نَفْس", "nafs", "self"],
      ["بَعْض", "baʿḍ", "some"],
    ]),
    V("questions", [
      ["ما", "mā", "what (before a noun)"], ["ماذا", "mādhā", "what (before a verb)"],
      ["مَنْ", "man", "who"], ["أَيْنَ", "ayna", "where"], ["مَتى", "matā", "when"],
      ["لِماذا", "limādhā", "why"], ["كَيْفَ", "kayfa", "how"],
      ["كَم", "kam", "how much / how many"], ["أَيّ", "ayy", "which"],
      ["مِنْ أَيْنَ", "min ayna", "where from"], ["لِمَنْ", "li-man", "whose"],
      ["هَلْ", "hal", "makes a yes/no question"], ["سُؤال", "suʾāl", "question"],
      ["جَواب", "jawāb", "answer"], ["سَأَلَ", "saʾala", "to ask"],
      ["أَجابَ", "ajāba", "to answer"], ["بِكَم؟", "bi-kam", "how much does it cost?"],
      ["كَمِ السّاعة؟", "kami s-sāʿa", "what time is it?"],
      ["ماذا يَحْدُث؟", "mādhā yaḥduth", "what is happening?"],
      ["أَلَيْسَ كَذٰلِك؟", "a-laysa ka-dhālik", "isn't that so?"],
    ]),
    V("grammar", [
      ["وَ", "wa", "and"], ["أَوْ", "aw", "or"], ["لٰكِنْ", "lākin", "but"],
      ["لِأَنَّ", "li-anna", "because"], ["إِذا", "idhā", "if"], ["أَنَّ", "anna", "that"],
      ["مِنْ", "min", "from"], ["إِلى", "ilā", "to"], ["في", "fī", "in"],
      ["عَلى", "ʿalā", "on"], ["تَحْتَ", "taḥta", "under"], ["مَعَ", "maʿa", "with"],
      ["بِدون", "bidūn", "without"], ["لِ", "li-", "for"], ["بِ", "bi-", "by / with"],
      ["عَنْ", "ʿan", "about"], ["بَيْنَ", "bayna", "between"],
      ["بَعْدَ", "baʿda", "after"], ["قَبْلَ", "qabla", "before"],
      ["حَتّى", "ḥattā", "until / even"], ["الـ", "al-", "the"],
      ["أَيْضًا", "ayḍan", "also"], ["لَيْسَ", "laysa", "is not"],
      ["لَمْ", "lam", "did not"], ["لَنْ", "lan", "will not"],
      ["إِذَنْ", "idhan", "so / therefore"], ["عِنْدَما", "ʿindamā", "when"],
    ]),
    V("adjectives", [
      ["كَبير", "kabīr", "big"], ["صَغير", "ṣaghīr", "small"],
      ["جَيِّد", "jayyid", "good"], ["سَيِّئ", "sayyiʾ", "bad"],
      ["جَديد", "jadīd", "new"], ["قَديم", "qadīm", "old (things)"],
      ["شابّ", "shābb", "young"], ["طَويل", "ṭawīl", "long / tall"],
      ["قَصير", "qaṣīr", "short"], ["عالٍ", "ʿālin", "high"],
      ["حارّ", "ḥārr", "hot"], ["بارِد", "bārid", "cold"],
      ["سَهْل", "sahl", "easy"], ["صَعْب", "ṣaʿb", "difficult"],
      ["جَميل", "jamīl", "beautiful"], ["قَبيح", "qabīḥ", "ugly"],
      ["قَوي", "qawī", "strong"], ["ضَعيف", "ḍaʿīf", "weak"],
      ["سَريع", "sarīʿ", "fast"], ["بَطيء", "baṭīʾ", "slow"],
      ["غَني", "ghanī", "rich"], ["فَقير", "faqīr", "poor"],
      ["سَعيد", "saʿīd", "happy"], ["حَزين", "ḥazīn", "sad"],
      ["تَعْبان", "taʿbān", "tired"], ["نَظيف", "naẓīf", "clean"],
      ["وَسِخ", "wasikh", "dirty"], ["مُمْتَلِئ", "mumtaliʾ", "full"],
      ["فارِغ", "fārigh", "empty"], ["غالٍ", "ghālin", "expensive"],
      ["رَخيص", "rakhīṣ", "cheap"], ["مُهِمّ", "muhimm", "important"],
    ]),
    V("adverbs", [
      ["جِدًّا", "jiddan", "very"], ["كَثيرًا", "kathīran", "a lot"],
      ["قَليلًا", "qalīlan", "a little"], ["جَيِّدًا", "jayyidan", "well"],
      ["دائِمًا", "dāʾiman", "always"], ["أَبَدًا", "abadan", "never"],
      ["أَحْيانًا", "aḥyānan", "sometimes"], ["غالِبًا", "ghāliban", "often"],
      ["الآن", "al-ān", "now"], ["اليَوْم", "al-yawm", "today"],
      ["أَمْس", "ams", "yesterday"], ["غَدًا", "ghadan", "tomorrow"],
      ["مُبَكِّرًا", "mubakkiran", "early"], ["مُتَأَخِّرًا", "mutaʾakhkhiran", "late"],
      ["هُنا", "hunā", "here"], ["هُناك", "hunāk", "there"],
      ["قَريب", "qarīb", "near"], ["بَعيد", "baʿīd", "far"],
      ["مَعًا", "maʿan", "together"], ["فَقَطْ", "faqaṭ", "only"],
      ["رُبَّما", "rubbamā", "maybe"], ["بِالفِعْل", "bi-l-fiʿl", "already"],
      ["ما زالَ", "mā zāla", "still"], ["مَرّة أُخْرى", "marra ukhrā", "again"],
      ["بِبُطْء", "bi-buṭʾ", "slowly"], ["بِسُرْعة", "bi-surʿa", "quickly"],
      ["تَقْريبًا", "taqrīban", "almost"], ["حَقًّا", "ḥaqqan", "really"],
    ]),
    V("verbs", [
      ["كانَ", "kāna", "to be (was)"], ["صارَ", "ṣāra", "to become"],
      ["فَعَلَ", "faʿala", "to do"], ["ذَهَبَ", "dhahaba", "to go"],
      ["جاءَ", "jāʾa", "to come"], ["اِسْتَطاعَ", "istaṭāʿa", "to be able to"],
      ["أَرادَ", "arāda", "to want"], ["عَرَفَ", "ʿarafa", "to know"],
      ["قالَ", "qāla", "to say"], ["تَكَلَّمَ", "takallama", "to speak"],
      ["أَكَلَ", "akala", "to eat"], ["شَرِبَ", "shariba", "to drink"],
      ["سَكَنَ", "sakana", "to live (reside)"], ["رَأى", "raʾā", "to see"],
      ["شاهَدَ", "shāhada", "to watch"], ["سَمِعَ", "samiʿa", "to hear"],
      ["قَرَأَ", "qaraʾa", "to read"], ["كَتَبَ", "kataba", "to write"],
      ["عَمِلَ", "ʿamila", "to work"], ["دَرَسَ", "darasa", "to study"],
      ["نامَ", "nāma", "to sleep"], ["اِشْتَرى", "ishtarā", "to buy"],
      ["باعَ", "bāʿa", "to sell"], ["فَتَحَ", "fataḥa", "to open"],
      ["أَغْلَقَ", "aghlaqa", "to close"], ["بَدَأَ", "badaʾa", "to begin"],
      ["اِنْتَهى", "intahā", "to finish"], ["ساعَدَ", "sāʿada", "to help"],
      ["اِحْتاجَ", "iḥtāja", "to need"], ["فَكَّرَ", "fakkara", "to think"],
      ["مَشى", "mashā", "to walk"], ["رَكَضَ", "rakaḍa", "to run"],
      ["اِنْتَظَرَ", "intaẓara", "to wait"], ["أَعْطى", "aʿṭā", "to give"],
      ["أَخَذَ", "akhadha", "to take"], ["وَصَلَ", "waṣala", "to arrive"],
      ["خَرَجَ", "kharaja", "to go out"], ["أَحَبَّ", "aḥabba", "to love"],
    ]),
    V("food", [
      ["طَعام", "ṭaʿām", "food"], ["أَكْل", "akl", "food / eating"],
      ["ماء", "māʾ", "water"], ["خُبْز", "khubz", "bread"],
      ["أَرُزّ", "aruzz", "rice"], ["لَحْم", "laḥm", "meat"],
      ["دَجاج", "dajāj", "chicken"], ["سَمَك", "samak", "fish"],
      ["بَيْض", "bayḍ", "eggs"], ["حَليب", "ḥalīb", "milk"],
      ["جُبْن", "jubn", "cheese"], ["زُبْدة", "zubda", "butter"],
      ["فاكِهة", "fākiha", "fruit"], ["تُفّاح", "tuffāḥ", "apples"],
      ["مَوْز", "mawz", "bananas"], ["بُرْتُقال", "burtuqāl", "oranges"],
      ["خُضار", "khuḍār", "vegetables"], ["بَطاطا", "baṭāṭā", "potatoes"],
      ["طَماطِم", "ṭamāṭim", "tomatoes"], ["بَصَل", "baṣal", "onions"],
      ["ثوم", "thūm", "garlic"], ["مِلْح", "milḥ", "salt"],
      ["فِلْفِل", "filfil", "pepper"], ["سُكَّر", "sukkar", "sugar"],
      ["زَيْت", "zayt", "oil"], ["قَهْوة", "qahwa", "coffee"],
      ["شاي", "shāy", "tea"], ["عَصير", "ʿaṣīr", "juice"],
      ["حَساء", "ḥasāʾ", "soup"], ["سَلَطة", "salaṭa", "salad"],
      ["حَلْوى", "ḥalwā", "sweets"], ["فَطور", "faṭūr", "breakfast"],
      ["غَداء", "ghadāʾ", "lunch"], ["عَشاء", "ʿashāʾ", "dinner"],
      ["مَطْعَم", "maṭʿam", "restaurant"], ["الحِساب", "al-ḥisāb", "the bill"],
      ["جائِع", "jāʾiʿ", "hungry"], ["عَطْشان", "ʿaṭshān", "thirsty"],
    ]),
    V("body", [
      ["جِسْم", "jism", "body"], ["رَأْس", "raʾs", "head"], ["شَعْر", "shaʿr", "hair"],
      ["وَجْه", "wajh", "face"], ["عَيْن", "ʿayn", "eye"], ["أُذُن", "udhun", "ear"],
      ["أَنْف", "anf", "nose"], ["فَم", "fam", "mouth"], ["سِنّ", "sinn", "tooth"],
      ["لِسان", "lisān", "tongue"], ["رَقَبة", "raqaba", "neck"],
      ["كَتِف", "katif", "shoulder"], ["ذِراع", "dhirāʿ", "arm"],
      ["يَد", "yad", "hand"], ["إِصْبَع", "iṣbaʿ", "finger"],
      ["رِجْل", "rijl", "leg / foot"], ["قَدَم", "qadam", "foot"],
      ["رُكْبة", "rukba", "knee"], ["ظَهْر", "ẓahr", "back"],
      ["صَدْر", "ṣadr", "chest"], ["قَلْب", "qalb", "heart"],
      ["مَعِدة", "maʿida", "stomach"], ["دَم", "dam", "blood"],
      ["عَظْم", "ʿaẓm", "bone"], ["جِلْد", "jild", "skin"],
      ["دِماغ", "dimāgh", "brain"],
    ]),
    V("health", [
      ["صِحّة", "ṣiḥḥa", "health"], ["طَبيب", "ṭabīb", "doctor"],
      ["مُسْتَشْفى", "mustashfā", "hospital"], ["صَيْدَلِيّة", "ṣaydaliyya", "pharmacy"],
      ["دَواء", "dawāʾ", "medicine"], ["مَريض", "marīḍ", "ill / patient"],
      ["سَليم", "salīm", "healthy / sound"], ["أَلَم", "alam", "pain"],
      ["حُمّى", "ḥummā", "fever"], ["سُعال", "suʿāl", "cough"],
      ["زُكام", "zukām", "a cold"], ["جُرْح", "jurḥ", "wound"],
      ["مُمَرِّضة", "mumarriḍa", "nurse"], ["مَوْعِد", "mawʿid", "appointment"],
      ["يُؤْلِمُني", "yuʾlimunī", "it hurts me"],
      ["إِسْعاف", "isʿāf", "ambulance"], ["طَوارِئ", "ṭawāriʾ", "emergency"],
      ["راحة", "rāḥa", "rest"], ["رِياضة", "riyāḍa", "exercise / sport"],
      ["حِمْية", "ḥimya", "diet"], ["وَصْفة", "waṣfa", "prescription"],
      ["شِفاء", "shifāʾ", "healing / recovery"],
    ]),
    V("clothing", [
      ["مَلابِس", "malābis", "clothes"], ["قَميص", "qamīṣ", "shirt"],
      ["بَنْطَلون", "banṭalūn", "trousers"], ["فُسْتان", "fustān", "dress"],
      ["تَنّورة", "tannūra", "skirt"], ["مِعْطَف", "miʿṭaf", "coat"],
      ["جاكيت", "jākīt", "jacket"], ["كَنْزة", "kanza", "sweater"],
      ["حِذاء", "ḥidhāʾ", "shoe"], ["جَوارِب", "jawārib", "socks"],
      ["قُبَّعة", "qubbaʿa", "hat"], ["وِشاح", "wishāḥ", "scarf"],
      ["قُفّازات", "quffāzāt", "gloves"], ["حِزام", "ḥizām", "belt"],
      ["نَظّارات", "naẓẓārāt", "glasses"], ["حَقيبة", "ḥaqība", "bag"],
      ["بَدْلة", "badla", "suit"], ["حِجاب", "ḥijāb", "headscarf"],
      ["ثَوْب", "thawb", "robe / garment"], ["مَقاس", "maqās", "size"],
      ["لَبِسَ", "labisa", "to wear"], ["خَلَعَ", "khalaʿa", "to take off"],
    ]),
    V("home", [
      ["بَيْت", "bayt", "house / home"], ["مَنْزِل", "manzil", "residence"],
      ["شَقّة", "shaqqa", "apartment"], ["غُرْفة", "ghurfa", "room"],
      ["مَطْبَخ", "maṭbakh", "kitchen"], ["حَمّام", "ḥammām", "bathroom"],
      ["غُرْفةُ النَّوْم", "ghurfatu n-nawm", "bedroom"],
      ["صالة", "ṣāla", "living room / hall"], ["باب", "bāb", "door"],
      ["نافِذة", "nāfidha", "window"], ["طاوِلة", "ṭāwila", "table"],
      ["كُرْسي", "kursī", "chair"], ["سَرير", "sarīr", "bed"],
      ["أَريكة", "arīka", "sofa"], ["مِصْباح", "miṣbāḥ", "lamp"],
      ["مِرْآة", "mirʾāt", "mirror"], ["مِفْتاح", "miftāḥ", "key"],
      ["صَحْن", "ṣaḥn", "plate"], ["كوب", "kūb", "cup / glass"],
      ["سِكّين", "sikkīn", "knife"], ["مِلْعَقة", "milʿaqa", "spoon"],
      ["شَوْكة", "shawka", "fork"], ["حَديقة", "ḥadīqa", "garden"],
      ["دَرَج", "daraj", "stairs"], ["سَقْف", "saqf", "roof / ceiling"],
      ["جِدار", "jidār", "wall"], ["أَرْض", "arḍ", "floor / ground"],
      ["ثَلّاجة", "thallāja", "fridge"],
    ]),
    V("animals", [
      ["حَيَوان", "ḥayawān", "animal"], ["كَلْب", "kalb", "dog"],
      ["قِطّ", "qiṭṭ", "cat"], ["حِصان", "ḥiṣān", "horse"],
      ["بَقَرة", "baqara", "cow"], ["خَروف", "kharūf", "sheep"],
      ["ماعِز", "māʿiz", "goat"], ["جَمَل", "jamal", "camel"],
      ["دَجاجة", "dajāja", "hen"], ["طائِر", "ṭāʾir", "bird"],
      ["سَمَكة", "samaka", "fish"], ["فَأْر", "faʾr", "mouse"],
      ["أَرْنَب", "arnab", "rabbit"], ["أَسَد", "asad", "lion"],
      ["نَمِر", "namir", "tiger / leopard"], ["فيل", "fīl", "elephant"],
      ["قِرْد", "qird", "monkey"], ["دُبّ", "dubb", "bear"],
      ["ذِئْب", "dhiʾb", "wolf"], ["ثُعْبان", "thuʿbān", "snake"],
      ["عَنْكَبوت", "ʿankabūt", "spider"], ["فَراشة", "farāsha", "butterfly"],
      ["نَحْلة", "naḥla", "bee"], ["نَمْلة", "namla", "ant"],
      ["ذُبابة", "dhubāba", "fly"],
    ]),
    V("nature", [
      ["طَبيعة", "ṭabīʿa", "nature"], ["شَمْس", "shams", "sun"],
      ["قَمَر", "qamar", "moon"], ["نَجْم", "najm", "star"],
      ["سَماء", "samāʾ", "sky"], ["سَحابة", "saḥāba", "cloud"],
      ["مَطَر", "maṭar", "rain"], ["ثَلْج", "thalj", "snow"],
      ["ريح", "rīḥ", "wind"], ["نار", "nār", "fire"],
      ["أَرْض", "arḍ", "earth"], ["بَحْر", "baḥr", "sea"],
      ["نَهْر", "nahr", "river"], ["بُحَيْرة", "buḥayra", "lake"],
      ["جَبَل", "jabal", "mountain"], ["غابة", "ghāba", "forest"],
      ["شَجَرة", "shajara", "tree"], ["زَهْرة", "zahra", "flower"],
      ["وَرَقة", "waraqa", "leaf / sheet of paper"],
      ["عُشْب", "ʿushb", "grass"], ["شاطِئ", "shāṭiʾ", "beach / shore"],
      ["جَزيرة", "jazīra", "island"], ["صَحْراء", "ṣaḥrāʾ", "desert"],
      ["حَجَر", "ḥajar", "stone"], ["طَقْس", "ṭaqs", "weather"],
      ["عاصِفة", "ʿāṣifa", "storm"],
    ]),
    V("places", [
      ["مَكان", "makān", "place"], ["مَدينة", "madīna", "city"],
      ["قَرْية", "qarya", "village"], ["بَلَد", "balad", "country"],
      ["شارِع", "shāriʿ", "street"], ["ساحة", "sāḥa", "square"],
      ["سوق", "sūq", "market"], ["مَتْجَر", "matjar", "shop"],
      ["بَنْك", "bank", "bank"], ["مَدْرَسة", "madrasa", "school"],
      ["مَسْجِد", "masjid", "mosque"], ["كَنيسة", "kanīsa", "church"],
      ["مَتْحَف", "matḥaf", "museum"], ["حَديقة عامّة", "ḥadīqa ʿāmma", "public park"],
      ["فُنْدُق", "funduq", "hotel"], ["مَطار", "maṭār", "airport"],
      ["مَحَطّة", "maḥaṭṭa", "station"], ["مَكْتَبة", "maktaba", "library / bookshop"],
      ["مَكْتَب", "maktab", "office / desk"], ["سينَما", "sīnamā", "cinema"],
      ["حَيّ", "ḥayy", "neighbourhood"], ["مَرْكَز", "markaz", "centre"],
      ["ريف", "rīf", "countryside"], ["حُدود", "ḥudūd", "border"],
      ["مَخْبَز", "makhbaz", "bakery"],
    ]),
    V("travel", [
      ["سَفَر", "safar", "travel"], ["رِحْلة", "riḥla", "trip"],
      ["سَيّارة", "sayyāra", "car"], ["حافِلة", "ḥāfila", "bus"],
      ["قِطار", "qiṭār", "train"], ["طائِرة", "ṭāʾira", "aeroplane"],
      ["دَرّاجة", "darrāja", "bicycle"], ["قارِب", "qārib", "boat"],
      ["تاكْسي", "tāksī", "taxi"], ["تَذْكِرة", "tadhkira", "ticket"],
      ["جَواز سَفَر", "jawāz safar", "passport"], ["حَقيبة سَفَر", "ḥaqībat safar", "suitcase"],
      ["أَمْتِعة", "amtiʿa", "luggage"], ["خَريطة", "kharīṭa", "map"],
      ["طَريق", "ṭarīq", "road / way"], ["مُغادَرة", "mughādara", "departure"],
      ["وُصول", "wuṣūl", "arrival"], ["تَأْخير", "taʾkhīr", "delay"],
      ["يَسار", "yasār", "left"], ["يَمين", "yamīn", "right"],
      ["مُباشَرةً", "mubāsharatan", "straight ahead"],
      ["تاهَ", "tāha", "to get lost"], ["جُمْرُك", "jumruk", "customs"],
      ["حَقيبة ظَهْر", "ḥaqībat ẓahr", "backpack"],
    ]),
    V("time", [
      ["وَقْت", "waqt", "time"], ["ساعة", "sāʿa", "hour / clock"],
      ["دَقيقة", "daqīqa", "minute"], ["ثانِية", "thāniya", "second"],
      ["يَوْم", "yawm", "day"], ["أُسْبوع", "usbūʿ", "week"],
      ["شَهْر", "shahr", "month"], ["سَنة", "sana", "year"],
      ["صَباح", "ṣabāḥ", "morning"], ["ظُهْر", "ẓuhr", "noon"],
      ["مَساء", "masāʾ", "evening"], ["لَيْل", "layl", "night"],
      ["الاِثْنَيْن", "al-ithnayn", "Monday"], ["الثُّلاثاء", "ath-thulāthāʾ", "Tuesday"],
      ["الأَرْبِعاء", "al-arbiʿāʾ", "Wednesday"], ["الخَميس", "al-khamīs", "Thursday"],
      ["الجُمْعة", "al-jumʿa", "Friday"], ["السَّبْت", "as-sabt", "Saturday"],
      ["الأَحَد", "al-aḥad", "Sunday"], ["يَناير", "yanāyir", "January"],
      ["فِبْراير", "fibrāyir", "February"], ["مارِس", "māris", "March"],
      ["أَبْريل", "abrīl", "April"], ["صَيْف", "ṣayf", "summer"],
      ["شِتاء", "shitāʾ", "winter"], ["رَبيع", "rabīʿ", "spring"],
      ["خَريف", "kharīf", "autumn"], ["تاريخ", "tārīkh", "date / history"],
    ]),
    V("work", [
      ["عَمَل", "ʿamal", "work"], ["وَظيفة", "waẓīfa", "job"],
      ["شَرِكة", "sharika", "company"], ["مُدير", "mudīr", "manager"],
      ["مُوَظَّف", "muwaẓẓaf", "employee"], ["راتِب", "rātib", "salary"],
      ["مال", "māl", "money"], ["نُقود", "nuqūd", "cash"],
      ["سِعْر", "siʿr", "price"], ["دَفَعَ", "dafaʿa", "to pay"],
      ["اِجْتِماع", "ijtimāʿ", "meeting"], ["مَشْروع", "mashrūʿ", "project"],
      ["زَبون", "zabūn", "customer"], ["فاتورة", "fātūra", "invoice"],
      ["عَقْد", "ʿaqd", "contract"], ["بِطاقة", "biṭāqa", "card"],
      ["مِهْنة", "mihna", "profession"], ["مُهَنْدِس", "muhandis", "engineer"],
      ["مُعَلِّم", "muʿallim", "teacher"], ["مُحامٍ", "muḥāmin", "lawyer"],
      ["تاجِر", "tājir", "merchant"], ["كَسَبَ", "kasaba", "to earn"],
      ["خَصْم", "khaṣm", "discount"], ["ضَريبة", "ḍarība", "tax"],
    ]),
    V("school", [
      ["مَدْرَسة", "madrasa", "school"], ["جامِعة", "jāmiʿa", "university"],
      ["صَفّ", "ṣaff", "class"], ["تِلْميذ", "tilmīdh", "pupil"],
      ["طالِب", "ṭālib", "student"], ["أُسْتاذ", "ustādh", "professor / teacher"],
      ["كِتاب", "kitāb", "book"], ["دَفْتَر", "daftar", "notebook"],
      ["قَلَم", "qalam", "pen"], ["قَلَم رَصاص", "qalam raṣāṣ", "pencil"],
      ["وَرَق", "waraq", "paper"], ["كَلِمة", "kalima", "word"],
      ["جُمْلة", "jumla", "sentence"], ["دَرْس", "dars", "lesson"],
      ["اِمْتِحان", "imtiḥān", "exam"], ["واجِب", "wājib", "homework / duty"],
      ["دَرَجة", "daraja", "grade / degree"], ["تَعَلَّمَ", "taʿallama", "to learn"],
      ["عَلَّمَ", "ʿallama", "to teach"], ["فَهِمَ", "fahima", "to understand"],
      ["شَرَحَ", "sharaḥa", "to explain"], ["لُغة", "lugha", "language"],
      ["تاريخ", "tārīkh", "history"], ["رِياضِيّات", "riyāḍiyyāt", "mathematics"],
      ["عُلوم", "ʿulūm", "science"], ["مَعْرِفة", "maʿrifa", "knowledge"],
    ]),
    V("tech", [
      ["حاسوب", "ḥāsūb", "computer"], ["كُمْبيوتَر", "kumbyūtar", "computer (loan)"],
      ["هاتِف", "hātif", "telephone"], ["جَوّال", "jawwāl", "mobile phone"],
      ["شاشة", "shāsha", "screen"], ["لَوْحةُ المَفاتيح", "lawḥatu l-mafātīḥ", "keyboard"],
      ["فَأْرة", "faʾra", "mouse"], ["إِنْتَرْنِت", "intarnit", "internet"],
      ["شَبَكة", "shabaka", "network"], ["بَريد إِلِكْتْروني", "barīd iliktrūnī", "email"],
      ["كَلِمةُ السِّرّ", "kalimatu s-sirr", "password"], ["مِلَفّ", "milaff", "file"],
      ["مُجَلَّد", "mujallad", "folder"], ["تَطْبيق", "taṭbīq", "app"],
      ["بَرْنامَج", "barnāmaj", "program"], ["حَمَّلَ", "ḥammala", "to download"],
      ["رَفَعَ", "rafaʿa", "to upload"], ["حَفِظَ", "ḥafiẓa", "to save"],
      ["حَذَفَ", "ḥadhafa", "to delete"], ["بَحَثَ", "baḥatha", "to search"],
      ["شَغَّلَ", "shaghghala", "to switch on"], ["أَطْفَأَ", "aṭfaʾa", "to switch off"],
      ["كاميرا", "kāmīrā", "camera"], ["بَطّارِيّة", "baṭṭāriyya", "battery"],
      ["رابِط", "rābiṭ", "link"], ["بَيانات", "bayānāt", "data"],
    ]),
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["مَرْحَبًا، كَيْفَ حالُك؟", "marḥaban, kayfa ḥāluk", "Hello, how are you?",
        [["مَرْحَبًا", "marḥaban"], ["كَيْفَ", "kayfa"], ["حالُك", "ḥāluk"]]],
      ["أَنا بِخَيْر، شُكْرًا", "anā bi-khayr, shukran", "I am well, thank you",
        [["أَنا", "anā"], ["بِخَيْر", "bi-khayr"], ["شُكْرًا", "shukran"]]],
      ["ما اسْمُك؟", "mā ismuk", "What is your name?",
        [["ما", "mā"], ["اسْمُك", "ismuk"]]],
      ["اسْمي أَحْمَد", "ismī aḥmad", "My name is Ahmed",
        [["اسْمي", "ismī"], ["أَحْمَد", "aḥmad"]]],
      ["لا أَفْهَم", "lā afham", "I don't understand",
        [["لا", "lā"], ["أَفْهَم", "afham"]]],
      ["مِنْ فَضْلِك، أَعِدْ", "min faḍlik, aʿid", "Please repeat",
        [["مِنْ", "min"], ["فَضْلِك", "faḍlik"], ["أَعِدْ", "aʿid"]]],
      ["هَلْ تَتَكَلَّمُ الإِنْجْليزِيّة؟", "hal tatakallamu l-injlīziyya",
        "Do you speak English?",
        [["هَلْ", "hal"], ["تَتَكَلَّمُ", "tatakallamu"], ["الإِنْجْليزِيّة", "al-injlīziyya"]]],
      ["تَشَرَّفْنا بِمَعْرِفَتِك", "tasharrafnā bi-maʿrifatik", "Pleased to meet you",
        [["تَشَرَّفْنا", "tasharrafnā"], ["بِمَعْرِفَتِك", "bi-maʿrifatik"]]],
    ]),
    S("food", [
      ["أُريدُ ماءً، مِنْ فَضْلِك", "urīdu māʾan, min faḍlik", "I want water, please",
        [["أُريدُ", "urīdu"], ["ماءً", "māʾan"], ["مِنْ", "min"], ["فَضْلِك", "faḍlik"]]],
      ["أَنا جائِع", "anā jāʾiʿ", "I am hungry",
        [["أَنا", "anā"], ["جائِع", "jāʾiʿ"]]],
      ["أَنا عَطْشان", "anā ʿaṭshān", "I am thirsty",
        [["أَنا", "anā"], ["عَطْشان", "ʿaṭshān"]]],
      ["الطَّعامُ لَذيذ", "aṭ-ṭaʿāmu ladhīdh", "The food is delicious",
        [["الطَّعامُ", "aṭ-ṭaʿāmu"], ["لَذيذ", "ladhīdh"]]],
      ["الحِساب، مِنْ فَضْلِك", "al-ḥisāb, min faḍlik", "The bill, please",
        [["الحِساب", "al-ḥisāb"], ["مِنْ", "min"], ["فَضْلِك", "faḍlik"]]],
      ["لا آكُلُ اللَّحْم", "lā ākulu l-laḥm", "I don't eat meat",
        [["لا", "lā"], ["آكُلُ", "ākulu"], ["اللَّحْم", "al-laḥm"]]],
    ]),
    S("travel", [
      ["أَيْنَ المَحَطّة؟", "ayna l-maḥaṭṭa", "Where is the station?",
        [["أَيْنَ", "ayna"], ["المَحَطّة", "al-maḥaṭṭa"]]],
      ["أُريدُ تَذْكِرة إِلى القاهِرة", "urīdu tadhkira ilā l-qāhira",
        "I want a ticket to Cairo",
        [["أُريدُ", "urīdu"], ["تَذْكِرة", "tadhkira"], ["إِلى", "ilā"], ["القاهِرة", "al-qāhira"]]],
      ["القِطارُ يَصِلُ السّاعةَ الثّامِنة", "al-qiṭāru yaṣilu s-sāʿata th-thāmina",
        "The train arrives at eight",
        [["القِطارُ", "al-qiṭāru"], ["يَصِلُ", "yaṣilu"], ["السّاعةَ", "as-sāʿata"], ["الثّامِنة", "ath-thāmina"]]],
      ["أَنا تائِه", "anā tāʾih", "I am lost",
        [["أَنا", "anā"], ["تائِه", "tāʾih"]]],
      ["اِتَّجِهْ يَمينًا", "ittajih yamīnan", "Turn right",
        [["اِتَّجِهْ", "ittajih"], ["يَمينًا", "yamīnan"]]],
    ]),
    S("home", [
      ["أَسْكُنُ في بَيْتٍ صَغير", "askunu fī baytin ṣaghīr", "I live in a small house",
        [["أَسْكُنُ", "askunu"], ["في", "fī"], ["بَيْتٍ", "baytin"], ["صَغير", "ṣaghīr"]]],
      ["البابُ مَفْتوح", "al-bābu maftūḥ", "The door is open",
        [["البابُ", "al-bābu"], ["مَفْتوح", "maftūḥ"]]],
      ["عائِلَتي كَبيرة", "ʿāʾilatī kabīra", "My family is big",
        [["عائِلَتي", "ʿāʾilatī"], ["كَبيرة", "kabīra"]]],
    ]),
    S("time", [
      ["كَمِ السّاعة؟", "kami s-sāʿa", "What time is it?",
        [["كَمِ", "kami"], ["السّاعة", "as-sāʿa"]]],
      ["اليَوْمُ الاِثْنَيْن", "al-yawmu l-ithnayn", "Today is Monday",
        [["اليَوْمُ", "al-yawmu"], ["الاِثْنَيْن", "al-ithnayn"]]],
      ["غَدًا أَذْهَبُ إِلى السّوق", "ghadan adhhabu ilā s-sūq",
        "Tomorrow I go to the market",
        [["غَدًا", "ghadan"], ["أَذْهَبُ", "adhhabu"], ["إِلى", "ilā"], ["السّوق", "as-sūq"]]],
      ["أَعْمَلُ دائِمًا في الصَّباح", "aʿmalu dāʾiman fī ṣ-ṣabāḥ",
        "I always work in the morning",
        [["أَعْمَلُ", "aʿmalu"], ["دائِمًا", "dāʾiman"], ["في", "fī"], ["الصَّباح", "aṣ-ṣabāḥ"]]],
    ]),
    S("school", [
      ["أَدْرُسُ العَرَبِيّةَ كُلَّ يَوْم", "adrusu l-ʿarabiyyata kulla yawm",
        "I study Arabic every day",
        [["أَدْرُسُ", "adrusu"], ["العَرَبِيّةَ", "al-ʿarabiyyata"], ["كُلَّ", "kulla"], ["يَوْم", "yawm"]]],
      ["الكِتابُ مُفيدٌ جِدًّا", "al-kitābu mufīdun jiddan", "The book is very useful",
        [["الكِتابُ", "al-kitābu"], ["مُفيدٌ", "mufīdun"], ["جِدًّا", "jiddan"]]],
      ["هَلْ يُمْكِنُكَ مُساعَدَتي؟", "hal yumkinuka musāʿadatī", "Can you help me?",
        [["هَلْ", "hal"], ["يُمْكِنُكَ", "yumkinuka"], ["مُساعَدَتي", "musāʿadatī"]]],
    ]),
    S("health", [
      ["رَأْسي يُؤْلِمُني", "raʾsī yuʾlimunī", "My head hurts",
        [["رَأْسي", "raʾsī"], ["يُؤْلِمُني", "yuʾlimunī"]]],
      ["أَحْتاجُ إِلى طَبيب", "aḥtāju ilā ṭabīb", "I need a doctor",
        [["أَحْتاجُ", "aḥtāju"], ["إِلى", "ilā"], ["طَبيب", "ṭabīb"]]],
      ["لَسْتُ بِخَيْر", "lastu bi-khayr", "I am not well",
        [["لَسْتُ", "lastu"], ["بِخَيْر", "bi-khayr"]]],
    ]),
    S("work", [
      ["بِكَمْ هٰذا؟", "bi-kam hādhā", "How much is this?",
        [["بِكَمْ", "bi-kam"], ["هٰذا", "hādhā"]]],
      ["هٰذا غالٍ جِدًّا", "hādhā ghālin jiddan", "This is very expensive",
        [["هٰذا", "hādhā"], ["غالٍ", "ghālin"], ["جِدًّا", "jiddan"]]],
      ["أَعْمَلُ في مَكْتَب", "aʿmalu fī maktab", "I work in an office",
        [["أَعْمَلُ", "aʿmalu"], ["في", "fī"], ["مَكْتَب", "maktab"]]],
    ]),
  );

  /* ----------------------------- Conjugation ------------------------------
   * The two Arabic tenses — al-māḍī (past) and al-muḍāriʿ (present) — plus the
   * future formed with sa-. Singular persons, with the masculine "you". */
  const CONJUGATION = [
    C("كَتَبَ", "kataba", "write", [
      ["كَتَبْتُ", "katabtu", "I wrote", "I", "past"],
      ["كَتَبْتَ", "katabta", "you wrote", "you", "past"],
      ["كَتَبَ", "kataba", "he wrote", "he", "past"],
      ["كَتَبَتْ", "katabat", "she wrote", "she", "past"],
      ["كَتَبْنا", "katabnā", "we wrote", "we", "past"],
      ["كَتَبوا", "katabū", "they wrote", "they", "past"],
      ["أَكْتُبُ", "aktubu", "I write", "I", "present"],
      ["تَكْتُبُ", "taktubu", "you write", "you", "present"],
      ["يَكْتُبُ", "yaktubu", "he writes", "he", "present"],
      ["تَكْتُبُ (هِيَ)", "taktubu (hiya)", "she writes", "she", "present"],
      ["نَكْتُبُ", "naktubu", "we write", "we", "present"],
      ["يَكْتُبونَ", "yaktubūna", "they write", "they", "present"],
      ["سَأَكْتُبُ", "sa-aktubu", "I will write", "I", "future"],
      ["سَتَكْتُبُ", "sa-taktubu", "you will write", "you", "future"],
      ["سَيَكْتُبُ", "sa-yaktubu", "he will write", "he", "future"],
      ["سَنَكْتُبُ", "sa-naktubu", "we will write", "we", "future"],
      ["سَيَكْتُبونَ", "sa-yaktubūna", "they will write", "they", "future"],
    ]),
    C("ذَهَبَ", "dhahaba", "go", [
      ["ذَهَبْتُ", "dhahabtu", "I went", "I", "past"],
      ["ذَهَبْتَ", "dhahabta", "you went", "you", "past"],
      ["ذَهَبَ", "dhahaba", "he went", "he", "past"],
      ["ذَهَبَتْ", "dhahabat", "she went", "she", "past"],
      ["ذَهَبْنا", "dhahabnā", "we went", "we", "past"],
      ["ذَهَبوا", "dhahabū", "they went", "they", "past"],
      ["أَذْهَبُ", "adhhabu", "I go", "I", "present"],
      ["تَذْهَبُ", "tadhhabu", "you go", "you", "present"],
      ["يَذْهَبُ", "yadhhabu", "he goes", "he", "present"],
      ["نَذْهَبُ", "nadhhabu", "we go", "we", "present"],
      ["يَذْهَبونَ", "yadhhabūna", "they go", "they", "present"],
      ["سَأَذْهَبُ", "sa-adhhabu", "I will go", "I", "future"],
      ["سَتَذْهَبُ", "sa-tadhhabu", "you will go", "you", "future"],
      ["سَيَذْهَبُ", "sa-yadhhabu", "he will go", "he", "future"],
      ["سَنَذْهَبُ", "sa-nadhhabu", "we will go", "we", "future"],
      ["سَيَذْهَبونَ", "sa-yadhhabūna", "they will go", "they", "future"],
    ]),
    C("أَكَلَ", "akala", "eat", [
      ["أَكَلْتُ", "akaltu", "I ate", "I", "past"],
      ["أَكَلْتَ", "akalta", "you ate", "you", "past"],
      ["أَكَلَ", "akala", "he ate", "he", "past"],
      ["أَكَلَتْ", "akalat", "she ate", "she", "past"],
      ["أَكَلْنا", "akalnā", "we ate", "we", "past"],
      ["أَكَلوا", "akalū", "they ate", "they", "past"],
      ["آكُلُ", "ākulu", "I eat", "I", "present"],
      ["تَأْكُلُ", "taʾkulu", "you eat", "you", "present"],
      ["يَأْكُلُ", "yaʾkulu", "he eats", "he", "present"],
      ["نَأْكُلُ", "naʾkulu", "we eat", "we", "present"],
      ["يَأْكُلونَ", "yaʾkulūna", "they eat", "they", "present"],
      ["سَآكُلُ", "sa-ākulu", "I will eat", "I", "future"],
      ["سَتَأْكُلُ", "sa-taʾkulu", "you will eat", "you", "future"],
      ["سَيَأْكُلُ", "sa-yaʾkulu", "he will eat", "he", "future"],
      ["سَنَأْكُلُ", "sa-naʾkulu", "we will eat", "we", "future"],
      ["سَيَأْكُلونَ", "sa-yaʾkulūna", "they will eat", "they", "future"],
    ]),
    C("شَرِبَ", "shariba", "drink", [
      ["شَرِبْتُ", "sharibtu", "I drank", "I", "past"],
      ["شَرِبْتَ", "sharibta", "you drank", "you", "past"],
      ["شَرِبَ", "shariba", "he drank", "he", "past"],
      ["شَرِبْنا", "sharibnā", "we drank", "we", "past"],
      ["شَرِبوا", "sharibū", "they drank", "they", "past"],
      ["أَشْرَبُ", "ashrabu", "I drink", "I", "present"],
      ["تَشْرَبُ", "tashrabu", "you drink", "you", "present"],
      ["يَشْرَبُ", "yashrabu", "he drinks", "he", "present"],
      ["نَشْرَبُ", "nashrabu", "we drink", "we", "present"],
      ["يَشْرَبونَ", "yashrabūna", "they drink", "they", "present"],
      ["سَأَشْرَبُ", "sa-ashrabu", "I will drink", "I", "future"],
      ["سَتَشْرَبُ", "sa-tashrabu", "you will drink", "you", "future"],
      ["سَيَشْرَبُ", "sa-yashrabu", "he will drink", "he", "future"],
      ["سَنَشْرَبُ", "sa-nashrabu", "we will drink", "we", "future"],
      ["سَيَشْرَبونَ", "sa-yashrabūna", "they will drink", "they", "future"],
    ]),
    C("قَرَأَ", "qaraʾa", "read", [
      ["قَرَأْتُ", "qaraʾtu", "I read", "I", "past"],
      ["قَرَأْتَ", "qaraʾta", "you read", "you", "past"],
      ["قَرَأَ", "qaraʾa", "he read", "he", "past"],
      ["قَرَأْنا", "qaraʾnā", "we read", "we", "past"],
      ["قَرَأوا", "qaraʾū", "they read", "they", "past"],
      ["أَقْرَأُ", "aqraʾu", "I read", "I", "present"],
      ["تَقْرَأُ", "taqraʾu", "you read", "you", "present"],
      ["يَقْرَأُ", "yaqraʾu", "he reads", "he", "present"],
      ["نَقْرَأُ", "naqraʾu", "we read", "we", "present"],
      ["يَقْرَأونَ", "yaqraʾūna", "they read", "they", "present"],
      ["سَأَقْرَأُ", "sa-aqraʾu", "I will read", "I", "future"],
      ["سَتَقْرَأُ", "sa-taqraʾu", "you will read", "you", "future"],
      ["سَيَقْرَأُ", "sa-yaqraʾu", "he will read", "he", "future"],
      ["سَنَقْرَأُ", "sa-naqraʾu", "we will read", "we", "future"],
      ["سَيَقْرَأونَ", "sa-yaqraʾūna", "they will read", "they", "future"],
    ]),
    C("تَكَلَّمَ", "takallama", "speak", [
      ["تَكَلَّمْتُ", "takallamtu", "I spoke", "I", "past"],
      ["تَكَلَّمْتَ", "takallamta", "you spoke", "you", "past"],
      ["تَكَلَّمَ", "takallama", "he spoke", "he", "past"],
      ["تَكَلَّمْنا", "takallamnā", "we spoke", "we", "past"],
      ["تَكَلَّموا", "takallamū", "they spoke", "they", "past"],
      ["أَتَكَلَّمُ", "atakallamu", "I speak", "I", "present"],
      ["تَتَكَلَّمُ", "tatakallamu", "you speak", "you", "present"],
      ["يَتَكَلَّمُ", "yatakallamu", "he speaks", "he", "present"],
      ["نَتَكَلَّمُ", "natakallamu", "we speak", "we", "present"],
      ["يَتَكَلَّمونَ", "yatakallamūna", "they speak", "they", "present"],
      ["سَأَتَكَلَّمُ", "sa-atakallamu", "I will speak", "I", "future"],
      ["سَتَتَكَلَّمُ", "sa-tatakallamu", "you will speak", "you", "future"],
      ["سَيَتَكَلَّمُ", "sa-yatakallamu", "he will speak", "he", "future"],
      ["سَنَتَكَلَّمُ", "sa-natakallamu", "we will speak", "we", "future"],
      ["سَيَتَكَلَّمونَ", "sa-yatakallamūna", "they will speak", "they", "future"],
    ]),
    C("عَمِلَ", "ʿamila", "work", [
      ["عَمِلْتُ", "ʿamiltu", "I worked", "I", "past"],
      ["عَمِلْتَ", "ʿamilta", "you worked", "you", "past"],
      ["عَمِلَ", "ʿamila", "he worked", "he", "past"],
      ["عَمِلْنا", "ʿamilnā", "we worked", "we", "past"],
      ["عَمِلوا", "ʿamilū", "they worked", "they", "past"],
      ["أَعْمَلُ", "aʿmalu", "I work", "I", "present"],
      ["تَعْمَلُ", "taʿmalu", "you work", "you", "present"],
      ["يَعْمَلُ", "yaʿmalu", "he works", "he", "present"],
      ["نَعْمَلُ", "naʿmalu", "we work", "we", "present"],
      ["يَعْمَلونَ", "yaʿmalūna", "they work", "they", "present"],
      ["سَأَعْمَلُ", "sa-aʿmalu", "I will work", "I", "future"],
      ["سَتَعْمَلُ", "sa-taʿmalu", "you will work", "you", "future"],
      ["سَيَعْمَلُ", "sa-yaʿmalu", "he will work", "he", "future"],
      ["سَنَعْمَلُ", "sa-naʿmalu", "we will work", "we", "future"],
      ["سَيَعْمَلونَ", "sa-yaʿmalūna", "they will work", "they", "future"],
    ]),
    C("سَكَنَ", "sakana", "live", [
      ["سَكَنْتُ", "sakantu", "I lived", "I", "past"],
      ["سَكَنْتَ", "sakanta", "you lived", "you", "past"],
      ["سَكَنَ", "sakana", "he lived", "he", "past"],
      ["سَكَنّا", "sakannā", "we lived", "we", "past"],
      ["سَكَنوا", "sakanū", "they lived", "they", "past"],
      ["أَسْكُنُ", "askunu", "I live", "I", "present"],
      ["تَسْكُنُ", "taskunu", "you live", "you", "present"],
      ["يَسْكُنُ", "yaskunu", "he lives", "he", "present"],
      ["نَسْكُنُ", "naskunu", "we live", "we", "present"],
      ["يَسْكُنونَ", "yaskunūna", "they live", "they", "present"],
      ["سَأَسْكُنُ", "sa-askunu", "I will live", "I", "future"],
      ["سَتَسْكُنُ", "sa-taskunu", "you will live", "you", "future"],
      ["سَيَسْكُنُ", "sa-yaskunu", "he will live", "he", "future"],
      ["سَنَسْكُنُ", "sa-naskunu", "we will live", "we", "future"],
      ["سَيَسْكُنونَ", "sa-yaskunūna", "they will live", "they", "future"],
    ]),
    C("رَأى", "raʾā", "see", [
      ["رَأَيْتُ", "raʾaytu", "I saw", "I", "past"],
      ["رَأَيْتَ", "raʾayta", "you saw", "you", "past"],
      ["رَأى", "raʾā", "he saw", "he", "past"],
      ["رَأَيْنا", "raʾaynā", "we saw", "we", "past"],
      ["رَأَوْا", "raʾaw", "they saw", "they", "past"],
      ["أَرى", "arā", "I see", "I", "present"],
      ["تَرى", "tarā", "you see", "you", "present"],
      ["يَرى", "yarā", "he sees", "he", "present"],
      ["نَرى", "narā", "we see", "we", "present"],
      ["يَرَوْنَ", "yarawna", "they see", "they", "present"],
      ["سَأَرى", "sa-arā", "I will see", "I", "future"],
      ["سَتَرى", "sa-tarā", "you will see", "you", "future"],
      ["سَيَرى", "sa-yarā", "he will see", "he", "future"],
      ["سَنَرى", "sa-narā", "we will see", "we", "future"],
      ["سَيَرَوْنَ", "sa-yarawna", "they will see", "they", "future"],
    ]),
    C("دَرَسَ", "darasa", "study", [
      ["دَرَسْتُ", "darastu", "I studied", "I", "past"],
      ["دَرَسْتَ", "darasta", "you studied", "you", "past"],
      ["دَرَسَ", "darasa", "he studied", "he", "past"],
      ["دَرَسْنا", "darasnā", "we studied", "we", "past"],
      ["دَرَسوا", "darasū", "they studied", "they", "past"],
      ["أَدْرُسُ", "adrusu", "I study", "I", "present"],
      ["تَدْرُسُ", "tadrusu", "you study", "you", "present"],
      ["يَدْرُسُ", "yadrusu", "he studies", "he", "present"],
      ["نَدْرُسُ", "nadrusu", "we study", "we", "present"],
      ["يَدْرُسونَ", "yadrusūna", "they study", "they", "present"],
      ["سَأَدْرُسُ", "sa-adrusu", "I will study", "I", "future"],
      ["سَتَدْرُسُ", "sa-tadrusu", "you will study", "you", "future"],
      ["سَيَدْرُسُ", "sa-yadrusu", "he will study", "he", "future"],
      ["سَنَدْرُسُ", "sa-nadrusu", "we will study", "we", "future"],
      ["سَيَدْرُسونَ", "sa-yadrusūna", "they will study", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Patience",
      l1: "الصَّبْرُ", l2: "مِفْتاحُ الفَرَج.",
      tr1: "aṣ-ṣabru", tr2: "miftāḥu l-faraj",
      en: "Patience is the key to relief." },
    { n: 2, chapterEn: "Work",
      l1: "مَنْ جَدَّ", l2: "وَجَد.",
      tr1: "man jadda", tr2: "wajad",
      en: "Whoever strives, finds." },
    { n: 3, chapterEn: "Time",
      l1: "الوَقْتُ", l2: "كَالسَّيْف.",
      tr1: "al-waqtu", tr2: "ka-s-sayf",
      en: "Time is like a sword — if you don't cut it, it cuts you." },
    { n: 4, chapterEn: "Speech",
      l1: "خَيْرُ الكَلامِ", l2: "ما قَلَّ وَدَلّ.",
      tr1: "khayru l-kalāmi", tr2: "mā qalla wa-dall",
      en: "The best speech is that which is brief and to the point." },
    { n: 5, chapterEn: "Friendship",
      l1: "الصَّديقُ", l2: "وَقْتَ الضّيق.",
      tr1: "aṣ-ṣadīqu", tr2: "waqta ḍ-ḍīq",
      en: "A friend is known in a time of hardship." },
    { n: 6, chapterEn: "Effort",
      l1: "اِعْقِلْها", l2: "وَتَوَكَّل.",
      tr1: "iʿqilhā", tr2: "wa-tawakkal",
      en: "Tie your camel, then trust in God." },
    { n: 7, chapterEn: "Company",
      l1: "الطُّيورُ عَلى أَشْكالِها", l2: "تَقَع.",
      tr1: "aṭ-ṭuyūru ʿalā ashkālihā", tr2: "taqaʿ",
      en: "Birds of a kind land together." },
    { n: 8, chapterEn: "Knowledge",
      l1: "اُطْلُبِ العِلْمَ", l2: "مِنَ المَهْدِ إِلى اللَّحْد.",
      tr1: "uṭlubi l-ʿilma", tr2: "mina l-mahdi ilā l-laḥd",
      en: "Seek knowledge from the cradle to the grave." },
    { n: 9, chapterEn: "Prudence",
      l1: "لَيْسَ كُلُّ ما يَلْمَعُ", l2: "ذَهَبًا.",
      tr1: "laysa kullu mā yalmaʿu", tr2: "dhahaban",
      en: "Not all that glitters is gold." },
    { n: 10, chapterEn: "Home",
      l1: "بَيْتُكَ", l2: "قَلْعَتُك.",
      tr1: "baytuka", tr2: "qalʿatuk",
      en: "Your home is your fortress." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("arabic", {
    icons: {
      alphabet: "الأَبْجَدِيّة", greetings: "تَحِيّات", numbers: "أَرْقام", colors: "أَلْوان",
      family: "عائِلة", people: "ناس", pronouns: "ضَمائِر", questions: "أَسْئِلة",
      grammar: "أَدَوات", adjectives: "صِفات", adverbs: "ظُروف", verbs: "أَفْعال",
      food: "طَعام", body: "جِسْم", health: "صِحّة", clothing: "مَلابِس", home: "بَيْت",
      animals: "حَيَوانات", nature: "طَبيعة", places: "أَماكِن", travel: "سَفَر",
      time: "وَقْت", work: "عَمَل", school: "مَدْرَسة", tech: "تِقْنِيّة", sentences: "جُمَل",
    },
    ui: { account: "حِساب", progress: "تَقَدُّم", search: "بَحْث" },
    alphabet: ALPHABET,
    alphabetTitle: "The abjad",
    alphabetLabels: ["Letters", "Marks & rules"],
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "مُراجَعة", vocab: "كَلِمات", sentence: "جُمَل", conjugation: "أَفْعال",
      listening: "اِسْتِماع", mixed: "مُنَوَّع", reading: "أَمْثال",
    },
    reading: {
      id: "amthal", title: "Proverbs", native: "أَمْثال",
      desc: "Classic Arabic sayings, line by line",
      blurb: "أمثال — proverbs quoted across the Arabic-speaking world.",
      unit: "sayings", numLabel: "مَثَل",
      lineQuestion: "Which line completes this saying?",
      items: PROVERBS,
    },
  });
})();
