/* ============================================================================
 * Chinese course (Mandarin, simplified characters) — data only.
 *
 * `ta` is the characters, `tr` the pinyin with tone marks, `en` the meaning.
 * Measure words are given with the nouns that most need them.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* --------------------------- Pinyin & tones ----------------------------
   * Mandarin has no alphabet, but it has a sound system, and pinyin spells it
   * out exactly: every syllable is one of 21 initials plus one of ~36 finals,
   * carrying one of five tones. Learn those three lists and you can pronounce
   * any character you are given the reading for — which is why this is the
   * writing-system section for Chinese.
   *
   * `ta` is written as pinyin would write it (finals with the hyphen that
   * marks where the initial goes), `tr` is how to say it, `en` the note.
   * -------------------------------------------------------------------- */
  const TONES = A([
    ["mā 妈", "mā (high, flat)", "1st tone — hold it high and level: mother"],
    ["má 麻", "má (rising)", "2nd tone — rise, as if asking: hemp"],
    ["mǎ 马", "mǎ (dip, rise)", "3rd tone — dip low then rise: horse"],
    ["mà 骂", "mà (falling)", "4th tone — drop sharply: to scold"],
    ["ma 吗", "ma (light)", "neutral tone — short and toneless: makes a question"],
    ["ā á ǎ à", "a", "the four tones written on a"],
    ["ī í ǐ ì", "i", "the four tones written on i"],
    ["ū ú ǔ ù", "u", "the four tones written on u"],
    ["nǐ hǎo", "ní hǎo", "two 3rd tones: the first becomes a 2nd"],
    ["bù → bú", "bú", "bù turns 2nd before another 4th tone"],
  ]);
  /* The 21 initials — the consonant a syllable can start with. */
  const INITIALS = A([
    ["b-", "b (as in 'spy')", "initial b"], ["p-", "p (puff of air)", "initial p"],
    ["m-", "m", "initial m"], ["f-", "f", "initial f"],
    ["d-", "d (as in 'sty')", "initial d"], ["t-", "t (puff of air)", "initial t"],
    ["n-", "n", "initial n"], ["l-", "l", "initial l"],
    ["g-", "g (as in 'sky')", "initial g"], ["k-", "k (puff of air)", "initial k"],
    ["h-", "h (from the throat)", "initial h"],
    ["j-", "j (smiling)", "initial j — tongue forward"],
    ["q-", "ch (smiling)", "initial q — like 'cheese'"],
    ["x-", "sh (smiling)", "initial x — like 'she'"],
    ["zh-", "j (curled)", "initial zh — tongue curled back"],
    ["ch-", "ch (curled)", "initial ch — tongue curled back"],
    ["sh-", "sh (curled)", "initial sh — tongue curled back"],
    ["r-", "r (curled)", "initial r — between r and zh"],
    ["z-", "dz", "initial z — flat tongue"],
    ["c-", "ts", "initial c — flat tongue, with a puff"],
    ["s-", "s", "initial s — flat tongue"],
  ]);
  /* The finals — everything after the initial. */
  const FINALS = A([
    ["-a", "ah", "final a"], ["-o", "aw", "final o"], ["-e", "uh", "final e"],
    ["-i", "ee", "final i"], ["-u", "oo", "final u"], ["-ü", "ew (rounded lips)", "final ü"],
    ["-ai", "eye", "final ai"], ["-ei", "ay", "final ei"],
    ["-ao", "ow", "final ao"], ["-ou", "oh", "final ou"],
    ["-an", "ahn", "final an"], ["-en", "un", "final en"],
    ["-ang", "ahng", "final ang"], ["-eng", "ung", "final eng"],
    ["-ong", "oong", "final ong"], ["-er", "arr", "final er"],
    ["-ia", "yah", "final ia"], ["-ie", "yeh", "final ie"],
    ["-iao", "yow", "final iao"], ["-iu", "yoh", "final iu — said 'iou'"],
    ["-ian", "yen", "final ian — said 'yen'"], ["-in", "een", "final in"],
    ["-iang", "yahng", "final iang"], ["-ing", "ing", "final ing"],
    ["-iong", "yoong", "final iong"],
    ["-ua", "wah", "final ua"], ["-uo", "waw", "final uo"],
    ["-uai", "why", "final uai"], ["-ui", "way", "final ui — said 'uei'"],
    ["-uan", "wahn", "final uan"], ["-un", "wun", "final un"],
    ["-uang", "wahng", "final uang"], ["-ueng", "wung", "final ueng"],
    ["-üe", "yweh", "final üe"], ["-üan", "ywen", "final üan"], ["-ün", "ywin", "final ün"],
  ]);
  const ALPHABET = { vowels: INITIALS.concat(FINALS), consonants: TONES };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["你好", "nǐ hǎo", "hello"], ["您好", "nín hǎo", "hello (polite)"],
      ["早上好", "zǎoshang hǎo", "good morning"],
      ["晚上好", "wǎnshang hǎo", "good evening"],
      ["晚安", "wǎn'ān", "good night"], ["再见", "zàijiàn", "goodbye"],
      ["拜拜", "bàibai", "bye-bye"], ["谢谢", "xièxie", "thank you"],
      ["不客气", "bú kèqi", "you're welcome"], ["请", "qǐng", "please"],
      ["是", "shì", "yes / to be"], ["对", "duì", "correct / yes"],
      ["不是", "bú shì", "no / is not"], ["不", "bù", "not"],
      ["对不起", "duìbuqǐ", "sorry"], ["没关系", "méi guānxi", "it's all right"],
      ["请问", "qǐngwèn", "excuse me (may I ask)"],
      ["你好吗？", "nǐ hǎo ma", "how are you?"],
      ["我很好", "wǒ hěn hǎo", "I am fine"],
      ["很高兴认识你", "hěn gāoxìng rènshi nǐ", "pleased to meet you"],
      ["欢迎", "huānyíng", "welcome"], ["回头见", "huítóu jiàn", "see you later"],
      ["明天见", "míngtiān jiàn", "see you tomorrow"],
      ["恭喜", "gōngxǐ", "congratulations"], ["祝你好运", "zhù nǐ hǎoyùn", "good luck"],
      ["干杯", "gānbēi", "cheers"], ["好的", "hǎo de", "okay"],
      ["没问题", "méi wèntí", "no problem"],
    ]),
    V("numbers", [
      ["零", "líng", "zero"], ["一", "yī", "one"], ["二", "èr", "two"],
      ["三", "sān", "three"], ["四", "sì", "four"], ["五", "wǔ", "five"],
      ["六", "liù", "six"], ["七", "qī", "seven"], ["八", "bā", "eight"],
      ["九", "jiǔ", "nine"], ["十", "shí", "ten"], ["十一", "shíyī", "eleven"],
      ["十二", "shí'èr", "twelve"], ["二十", "èrshí", "twenty"],
      ["三十", "sānshí", "thirty"], ["五十", "wǔshí", "fifty"],
      ["一百", "yìbǎi", "one hundred"], ["一千", "yìqiān", "one thousand"],
      ["一万", "yíwàn", "ten thousand"], ["第一", "dì yī", "first"],
      ["第二", "dì èr", "second"], ["最后", "zuìhòu", "last"],
      ["一半", "yíbàn", "half"], ["两", "liǎng", "two (before a measure word)"],
      ["个", "gè", "the general measure word"], ["号", "hào", "number / date"],
      ["多少", "duōshao", "how many / how much"], ["几", "jǐ", "how many (small numbers)"],
    ]),
    V("colors", [
      ["红色", "hóngsè", "red"], ["蓝色", "lánsè", "blue"], ["绿色", "lǜsè", "green"],
      ["黄色", "huángsè", "yellow"], ["黑色", "hēisè", "black"],
      ["白色", "báisè", "white"], ["灰色", "huīsè", "grey"],
      ["棕色", "zōngsè", "brown"], ["橙色", "chéngsè", "orange"],
      ["粉色", "fěnsè", "pink"], ["紫色", "zǐsè", "purple"],
      ["金色", "jīnsè", "golden"], ["银色", "yínsè", "silver"],
      ["颜色", "yánsè", "colour"], ["浅", "qiǎn", "light (colour)"],
      ["深", "shēn", "dark / deep"], ["彩色", "cǎisè", "colourful"],
      ["亮", "liàng", "bright"], ["暗", "àn", "dim / dark"],
      ["天蓝色", "tiānlánsè", "sky blue"], ["透明", "tòumíng", "transparent"],
    ]),
    V("family", [
      ["家", "jiā", "home / family"], ["家人", "jiārén", "family members"],
      ["妈妈", "māma", "mum"], ["爸爸", "bàba", "dad"],
      ["母亲", "mǔqīn", "mother (formal)"], ["父亲", "fùqīn", "father (formal)"],
      ["父母", "fùmǔ", "parents"], ["儿子", "érzi", "son"],
      ["女儿", "nǚ'ér", "daughter"], ["哥哥", "gēge", "older brother"],
      ["弟弟", "dìdi", "younger brother"], ["姐姐", "jiějie", "older sister"],
      ["妹妹", "mèimei", "younger sister"], ["爷爷", "yéye", "paternal grandfather"],
      ["奶奶", "nǎinai", "paternal grandmother"], ["外公", "wàigōng", "maternal grandfather"],
      ["外婆", "wàipó", "maternal grandmother"], ["孙子", "sūnzi", "grandson"],
      ["叔叔", "shūshu", "uncle"], ["阿姨", "āyí", "aunt"],
      ["丈夫", "zhàngfu", "husband"], ["妻子", "qīzi", "wife"],
      ["孩子", "háizi", "child"], ["宝宝", "bǎobao", "baby"],
      ["亲戚", "qīnqi", "relative"], ["婚礼", "hūnlǐ", "wedding"],
    ]),
    V("people", [
      ["人", "rén", "person"], ["人们", "rénmen", "people"],
      ["男人", "nánrén", "man"], ["女人", "nǚrén", "woman"],
      ["男孩", "nánhái", "boy"], ["女孩", "nǚhái", "girl"],
      ["朋友", "péngyou", "friend"], ["邻居", "línjū", "neighbour"],
      ["客人", "kèrén", "guest"], ["先生", "xiānsheng", "Mr / sir"],
      ["女士", "nǚshì", "Ms / madam"], ["年轻人", "niánqīngrén", "young person"],
      ["老人", "lǎorén", "elderly person"], ["大人", "dàrén", "adult"],
      ["外国人", "wàiguórén", "foreigner"], ["同事", "tóngshì", "colleague"],
      ["同学", "tóngxué", "classmate"], ["队", "duì", "team"],
      ["小组", "xiǎozǔ", "group"], ["名字", "míngzi", "name"],
      ["姓", "xìng", "surname"], ["大家", "dàjiā", "everyone"],
      ["自己", "zìjǐ", "oneself"],
    ]),
    V("pronouns", [
      ["我", "wǒ", "I / me"], ["你", "nǐ", "you"], ["您", "nín", "you (polite)"],
      ["他", "tā", "he / him"], ["她", "tā", "she / her"], ["它", "tā", "it"],
      ["我们", "wǒmen", "we / us"], ["你们", "nǐmen", "you (plural)"],
      ["他们", "tāmen", "they (m or mixed)"], ["她们", "tāmen", "they (f)"],
      ["我的", "wǒ de", "my"], ["你的", "nǐ de", "your"],
      ["他的", "tā de", "his"], ["我们的", "wǒmen de", "our"],
      ["这", "zhè", "this"], ["那", "nà", "that"],
      ["这个", "zhège", "this one"], ["那个", "nàge", "that one"],
      ["这里", "zhèlǐ", "here"], ["那里", "nàlǐ", "there"],
      ["有人", "yǒu rén", "someone"], ["没有人", "méiyǒu rén", "nobody"],
      ["每个人", "měi ge rén", "everyone"], ["别人", "biérén", "other people"],
    ]),
    V("questions", [
      ["什么", "shénme", "what"], ["谁", "shéi", "who"], ["哪里", "nǎlǐ", "where"],
      ["什么时候", "shénme shíhou", "when"], ["为什么", "wèishénme", "why"],
      ["怎么", "zěnme", "how"], ["怎么样", "zěnmeyàng", "how about it?"],
      ["哪个", "nǎge", "which"], ["多少钱", "duōshao qián", "how much money"],
      ["多久", "duō jiǔ", "how long"], ["谁的", "shéi de", "whose"],
      ["吗", "ma", "turns a statement into a question"],
      ["呢", "ne", "and what about…?"], ["问题", "wèntí", "question / problem"],
      ["答案", "dá'àn", "answer"], ["问", "wèn", "to ask"],
      ["回答", "huídá", "to answer"], ["几点", "jǐ diǎn", "what time"],
      ["怎么了", "zěnme le", "what's wrong?"],
      ["是不是", "shì bu shì", "is it or isn't it?"],
    ]),
    V("grammar", [
      ["和", "hé", "and"], ["或者", "huòzhě", "or"], ["但是", "dànshì", "but"],
      ["因为", "yīnwèi", "because"], ["所以", "suǒyǐ", "so / therefore"],
      ["如果", "rúguǒ", "if"], ["的", "de", "possessive / descriptive particle"],
      ["了", "le", "marks a completed action"], ["在", "zài", "at / in / -ing"],
      ["从", "cóng", "from"], ["到", "dào", "to / until"],
      ["给", "gěi", "to give / for"], ["跟", "gēn", "with"],
      ["为了", "wèile", "in order to"], ["把", "bǎ", "moves the object forward"],
      ["被", "bèi", "marks the passive"], ["上", "shàng", "on / up"],
      ["下", "xià", "under / down"], ["里", "lǐ", "inside"],
      ["外", "wài", "outside"], ["中间", "zhōngjiān", "between"],
      ["也", "yě", "also"], ["都", "dōu", "all / both"],
      ["还", "hái", "still / also"], ["就", "jiù", "then / just"],
      ["很", "hěn", "very (links adjectives)"], ["不", "bù", "not"],
      ["没", "méi", "not (with 有 and the past)"],
    ]),
    V("adjectives", [
      ["大", "dà", "big"], ["小", "xiǎo", "small"], ["好", "hǎo", "good"],
      ["坏", "huài", "bad / broken"], ["新", "xīn", "new"], ["旧", "jiù", "old (things)"],
      ["老", "lǎo", "old (people)"], ["年轻", "niánqīng", "young"],
      ["长", "cháng", "long"], ["短", "duǎn", "short"], ["高", "gāo", "tall / high"],
      ["矮", "ǎi", "short (in height)"], ["热", "rè", "hot"], ["冷", "lěng", "cold"],
      ["容易", "róngyì", "easy"], ["难", "nán", "difficult"],
      ["漂亮", "piàoliang", "pretty"], ["丑", "chǒu", "ugly"],
      ["强", "qiáng", "strong"], ["弱", "ruò", "weak"], ["快", "kuài", "fast"],
      ["慢", "màn", "slow"], ["有钱", "yǒuqián", "rich"], ["穷", "qióng", "poor"],
      ["高兴", "gāoxìng", "happy"], ["伤心", "shāngxīn", "sad"],
      ["累", "lèi", "tired"], ["干净", "gānjìng", "clean"], ["脏", "zāng", "dirty"],
      ["满", "mǎn", "full"], ["空", "kōng", "empty"], ["贵", "guì", "expensive"],
      ["便宜", "piányi", "cheap"], ["重要", "zhòngyào", "important"],
    ]),
    V("adverbs", [
      ["很", "hěn", "very"], ["非常", "fēicháng", "extremely"],
      ["有点儿", "yǒudiǎnr", "a bit"], ["太", "tài", "too (much)"],
      ["一直", "yìzhí", "always / straight"], ["总是", "zǒngshì", "always"],
      ["从不", "cóng bù", "never"], ["有时候", "yǒu shíhou", "sometimes"],
      ["经常", "jīngcháng", "often"], ["现在", "xiànzài", "now"],
      ["今天", "jīntiān", "today"], ["昨天", "zuótiān", "yesterday"],
      ["明天", "míngtiān", "tomorrow"], ["早", "zǎo", "early"],
      ["晚", "wǎn", "late"], ["一起", "yìqǐ", "together"],
      ["只", "zhǐ", "only"], ["也许", "yěxǔ", "maybe"],
      ["已经", "yǐjīng", "already"], ["还没", "hái méi", "not yet"],
      ["再", "zài", "again"], ["慢慢地", "mànmàn de", "slowly"],
      ["快点", "kuài diǎn", "quickly / hurry up"], ["差不多", "chàbuduō", "almost"],
      ["真的", "zhēn de", "really"], ["一定", "yídìng", "certainly"],
      ["马上", "mǎshàng", "immediately"],
    ]),
    V("verbs", [
      ["是", "shì", "to be"], ["有", "yǒu", "to have"], ["做", "zuò", "to do / make"],
      ["去", "qù", "to go"], ["来", "lái", "to come"], ["会", "huì", "to know how to / will"],
      ["能", "néng", "to be able to"], ["可以", "kěyǐ", "may / can"],
      ["想", "xiǎng", "to want / to think"], ["要", "yào", "to want / will"],
      ["知道", "zhīdào", "to know (a fact)"], ["认识", "rènshi", "to know (a person)"],
      ["说", "shuō", "to speak / say"], ["讲", "jiǎng", "to talk / explain"],
      ["吃", "chī", "to eat"], ["喝", "hē", "to drink"], ["住", "zhù", "to live / stay"],
      ["看", "kàn", "to look / watch / read"], ["听", "tīng", "to listen"],
      ["读", "dú", "to read aloud"], ["写", "xiě", "to write"],
      ["工作", "gōngzuò", "to work"], ["学习", "xuéxí", "to study"],
      ["睡觉", "shuìjiào", "to sleep"], ["买", "mǎi", "to buy"],
      ["卖", "mài", "to sell"], ["开", "kāi", "to open / drive"],
      ["关", "guān", "to close / switch off"], ["开始", "kāishǐ", "to begin"],
      ["结束", "jiéshù", "to end"], ["帮助", "bāngzhù", "to help"],
      ["需要", "xūyào", "to need"], ["走", "zǒu", "to walk / leave"],
      ["跑", "pǎo", "to run"], ["等", "děng", "to wait"], ["给", "gěi", "to give"],
      ["拿", "ná", "to take / hold"], ["到", "dào", "to arrive"],
      ["喜欢", "xǐhuan", "to like"], ["爱", "ài", "to love"],
    ]),
    V("food", [
      ["食物", "shíwù", "food"], ["水", "shuǐ", "water"], ["米饭", "mǐfàn", "cooked rice"],
      ["面条", "miàntiáo", "noodles"], ["面包", "miànbāo", "bread"],
      ["包子", "bāozi", "steamed bun"], ["饺子", "jiǎozi", "dumplings"],
      ["肉", "ròu", "meat"], ["鸡肉", "jīròu", "chicken (meat)"],
      ["牛肉", "niúròu", "beef"], ["猪肉", "zhūròu", "pork"],
      ["鱼", "yú", "fish"], ["鸡蛋", "jīdàn", "egg"], ["牛奶", "niúnǎi", "milk"],
      ["奶酪", "nǎilào", "cheese"], ["水果", "shuǐguǒ", "fruit"],
      ["苹果", "píngguǒ", "apple"], ["香蕉", "xiāngjiāo", "banana"],
      ["橙子", "chéngzi", "orange"], ["蔬菜", "shūcài", "vegetables"],
      ["土豆", "tǔdòu", "potato"], ["西红柿", "xīhóngshì", "tomato"],
      ["洋葱", "yángcōng", "onion"], ["大蒜", "dàsuàn", "garlic"],
      ["盐", "yán", "salt"], ["糖", "táng", "sugar"], ["油", "yóu", "oil"],
      ["茶", "chá", "tea"], ["咖啡", "kāfēi", "coffee"], ["果汁", "guǒzhī", "juice"],
      ["啤酒", "píjiǔ", "beer"], ["汤", "tāng", "soup"],
      ["早饭", "zǎofàn", "breakfast"], ["午饭", "wǔfàn", "lunch"],
      ["晚饭", "wǎnfàn", "dinner"], ["餐厅", "cāntīng", "restaurant"],
      ["买单", "mǎidān", "the bill"], ["好吃", "hǎochī", "tasty"],
      ["饿", "è", "hungry"], ["渴", "kě", "thirsty"],
    ]),
    V("body", [
      ["身体", "shēntǐ", "body"], ["头", "tóu", "head"], ["头发", "tóufa", "hair"],
      ["脸", "liǎn", "face"], ["眼睛", "yǎnjing", "eye"], ["耳朵", "ěrduo", "ear"],
      ["鼻子", "bízi", "nose"], ["嘴", "zuǐ", "mouth"], ["牙齿", "yáchǐ", "tooth"],
      ["舌头", "shétou", "tongue"], ["脖子", "bózi", "neck"],
      ["肩膀", "jiānbǎng", "shoulder"], ["手臂", "shǒubì", "arm"],
      ["手", "shǒu", "hand"], ["手指", "shǒuzhǐ", "finger"],
      ["腿", "tuǐ", "leg"], ["脚", "jiǎo", "foot"], ["膝盖", "xīgài", "knee"],
      ["背", "bèi", "back"], ["胸", "xiōng", "chest"], ["心", "xīn", "heart"],
      ["肚子", "dùzi", "stomach / belly"], ["血", "xuè", "blood"],
      ["骨头", "gǔtou", "bone"], ["皮肤", "pífū", "skin"], ["脑子", "nǎozi", "brain"],
    ]),
    V("health", [
      ["健康", "jiànkāng", "health / healthy"], ["医生", "yīshēng", "doctor"],
      ["医院", "yīyuàn", "hospital"], ["药店", "yàodiàn", "pharmacy"],
      ["药", "yào", "medicine"], ["生病", "shēngbìng", "to fall ill"],
      ["疼", "téng", "to hurt / ache"], ["发烧", "fāshāo", "to have a fever"],
      ["咳嗽", "késou", "to cough"], ["感冒", "gǎnmào", "a cold"],
      ["伤口", "shāngkǒu", "wound"], ["护士", "hùshi", "nurse"],
      ["预约", "yùyuē", "appointment"], ["救护车", "jiùhùchē", "ambulance"],
      ["急诊", "jízhěn", "emergency treatment"], ["休息", "xiūxi", "to rest"],
      ["运动", "yùndòng", "exercise / sport"], ["检查", "jiǎnchá", "to examine"],
      ["处方", "chǔfāng", "prescription"], ["好起来", "hǎo qǐlái", "to get better"],
      ["头疼", "tóuténg", "headache"], ["肚子疼", "dùzi téng", "stomach ache"],
    ]),
    V("clothing", [
      ["衣服", "yīfu", "clothes"], ["衬衫", "chènshān", "shirt"],
      ["T恤", "T-xù", "t-shirt"], ["裤子", "kùzi", "trousers"],
      ["牛仔裤", "niúzǎikù", "jeans"], ["裙子", "qúnzi", "skirt"],
      ["连衣裙", "liányīqún", "dress"], ["外套", "wàitào", "coat"],
      ["夹克", "jiákè", "jacket"], ["毛衣", "máoyī", "sweater"],
      ["鞋", "xié", "shoes"], ["靴子", "xuēzi", "boots"], ["袜子", "wàzi", "socks"],
      ["帽子", "màozi", "hat"], ["围巾", "wéijīn", "scarf"],
      ["手套", "shǒutào", "gloves"], ["腰带", "yāodài", "belt"],
      ["眼镜", "yǎnjìng", "glasses"], ["包", "bāo", "bag"],
      ["西装", "xīzhuāng", "suit"], ["尺码", "chǐmǎ", "size"],
      ["穿", "chuān", "to wear (clothes)"], ["戴", "dài", "to wear (hat, glasses)"],
      ["试", "shì", "to try"],
    ]),
    V("home", [
      ["房子", "fángzi", "house"], ["公寓", "gōngyù", "apartment"],
      ["房间", "fángjiān", "room"], ["厨房", "chúfáng", "kitchen"],
      ["卫生间", "wèishēngjiān", "bathroom"], ["卧室", "wòshì", "bedroom"],
      ["客厅", "kètīng", "living room"], ["门", "mén", "door"],
      ["窗户", "chuānghu", "window"], ["桌子", "zhuōzi", "table"],
      ["椅子", "yǐzi", "chair"], ["床", "chuáng", "bed"],
      ["沙发", "shāfā", "sofa"], ["灯", "dēng", "lamp / light"],
      ["镜子", "jìngzi", "mirror"], ["钥匙", "yàoshi", "key"],
      ["盘子", "pánzi", "plate"], ["杯子", "bēizi", "cup / glass"],
      ["筷子", "kuàizi", "chopsticks"], ["刀", "dāo", "knife"],
      ["勺子", "sháozi", "spoon"], ["花园", "huāyuán", "garden"],
      ["楼梯", "lóutī", "stairs"], ["屋顶", "wūdǐng", "roof"],
      ["墙", "qiáng", "wall"], ["地板", "dìbǎn", "floor"],
      ["冰箱", "bīngxiāng", "fridge"], ["电视", "diànshì", "television"],
    ]),
    V("animals", [
      ["动物", "dòngwù", "animal"], ["狗", "gǒu", "dog"], ["猫", "māo", "cat"],
      ["马", "mǎ", "horse"], ["牛", "niú", "cow / ox"], ["猪", "zhū", "pig"],
      ["羊", "yáng", "sheep / goat"], ["鸡", "jī", "chicken"],
      ["鸟", "niǎo", "bird"], ["鱼", "yú", "fish"], ["老鼠", "lǎoshǔ", "mouse / rat"],
      ["兔子", "tùzi", "rabbit"], ["狮子", "shīzi", "lion"],
      ["老虎", "lǎohǔ", "tiger"], ["大象", "dàxiàng", "elephant"],
      ["猴子", "hóuzi", "monkey"], ["熊", "xióng", "bear"],
      ["熊猫", "xióngmāo", "panda"], ["狼", "láng", "wolf"],
      ["蛇", "shé", "snake"], ["蜘蛛", "zhīzhū", "spider"],
      ["蝴蝶", "húdié", "butterfly"], ["蜜蜂", "mìfēng", "bee"],
      ["蚂蚁", "mǎyǐ", "ant"], ["龙", "lóng", "dragon"],
    ]),
    V("nature", [
      ["自然", "zìrán", "nature"], ["太阳", "tàiyáng", "sun"],
      ["月亮", "yuèliang", "moon"], ["星星", "xīngxing", "star"],
      ["天空", "tiānkōng", "sky"], ["云", "yún", "cloud"],
      ["雨", "yǔ", "rain"], ["雪", "xuě", "snow"], ["风", "fēng", "wind"],
      ["火", "huǒ", "fire"], ["土地", "tǔdì", "land / soil"],
      ["海", "hǎi", "sea"], ["河", "hé", "river"], ["湖", "hú", "lake"],
      ["山", "shān", "mountain"], ["森林", "sēnlín", "forest"],
      ["树", "shù", "tree"], ["花", "huā", "flower"], ["叶子", "yèzi", "leaf"],
      ["草", "cǎo", "grass"], ["海滩", "hǎitān", "beach"],
      ["岛", "dǎo", "island"], ["沙漠", "shāmò", "desert"],
      ["石头", "shítou", "stone"], ["天气", "tiānqì", "weather"],
      ["暴风雨", "bàofēngyǔ", "storm"],
    ]),
    V("places", [
      ["地方", "dìfang", "place"], ["城市", "chéngshì", "city"],
      ["村子", "cūnzi", "village"], ["国家", "guójiā", "country"],
      ["街", "jiē", "street"], ["广场", "guǎngchǎng", "square"],
      ["市场", "shìchǎng", "market"], ["商店", "shāngdiàn", "shop"],
      ["银行", "yínháng", "bank"], ["学校", "xuéxiào", "school"],
      ["寺庙", "sìmiào", "temple"], ["教堂", "jiàotáng", "church"],
      ["博物馆", "bówùguǎn", "museum"], ["公园", "gōngyuán", "park"],
      ["酒店", "jiǔdiàn", "hotel"], ["机场", "jīchǎng", "airport"],
      ["车站", "chēzhàn", "station"], ["图书馆", "túshūguǎn", "library"],
      ["办公室", "bàngōngshì", "office"], ["电影院", "diànyǐngyuàn", "cinema"],
      ["附近", "fùjìn", "the area nearby"], ["市中心", "shì zhōngxīn", "city centre"],
      ["农村", "nóngcūn", "countryside"], ["边境", "biānjìng", "border"],
    ]),
    V("travel", [
      ["旅行", "lǚxíng", "to travel / journey"], ["车", "chē", "vehicle"],
      ["汽车", "qìchē", "car"], ["公共汽车", "gōnggòng qìchē", "bus"],
      ["火车", "huǒchē", "train"], ["飞机", "fēijī", "aeroplane"],
      ["自行车", "zìxíngchē", "bicycle"], ["船", "chuán", "boat"],
      ["出租车", "chūzūchē", "taxi"], ["地铁", "dìtiě", "underground"],
      ["票", "piào", "ticket"], ["护照", "hùzhào", "passport"],
      ["行李", "xíngli", "luggage"], ["箱子", "xiāngzi", "suitcase"],
      ["地图", "dìtú", "map"], ["路", "lù", "road"], ["方向", "fāngxiàng", "direction"],
      ["出发", "chūfā", "to set off"], ["到达", "dàodá", "to arrive"],
      ["晚点", "wǎndiǎn", "delayed"], ["左", "zuǒ", "left"], ["右", "yòu", "right"],
      ["一直走", "yìzhí zǒu", "go straight on"], ["迷路", "mílù", "to get lost"],
      ["海关", "hǎiguān", "customs"],
    ]),
    V("time", [
      ["时间", "shíjiān", "time"], ["小时", "xiǎoshí", "hour"],
      ["分钟", "fēnzhōng", "minute"], ["秒", "miǎo", "second"],
      ["天", "tiān", "day"], ["星期", "xīngqī", "week"],
      ["月", "yuè", "month / moon"], ["年", "nián", "year"],
      ["早上", "zǎoshang", "morning"], ["中午", "zhōngwǔ", "noon"],
      ["下午", "xiàwǔ", "afternoon"], ["晚上", "wǎnshang", "evening"],
      ["星期一", "xīngqīyī", "Monday"], ["星期二", "xīngqī'èr", "Tuesday"],
      ["星期三", "xīngqīsān", "Wednesday"], ["星期四", "xīngqīsì", "Thursday"],
      ["星期五", "xīngqīwǔ", "Friday"], ["星期六", "xīngqīliù", "Saturday"],
      ["星期天", "xīngqītiān", "Sunday"], ["一月", "yīyuè", "January"],
      ["二月", "èryuè", "February"], ["三月", "sānyuè", "March"],
      ["周末", "zhōumò", "weekend"], ["钟", "zhōng", "clock"],
      ["点", "diǎn", "o'clock"], ["春天", "chūntiān", "spring"],
      ["夏天", "xiàtiān", "summer"], ["秋天", "qiūtiān", "autumn"],
      ["冬天", "dōngtiān", "winter"],
    ]),
    V("work", [
      ["工作", "gōngzuò", "work / job"], ["公司", "gōngsī", "company"],
      ["老板", "lǎobǎn", "boss"], ["员工", "yuángōng", "employee"],
      ["工资", "gōngzī", "salary"], ["钱", "qián", "money"],
      ["元", "yuán", "yuan (currency)"], ["价格", "jiàgé", "price"],
      ["付钱", "fù qián", "to pay"], ["会议", "huìyì", "meeting"],
      ["项目", "xiàngmù", "project"], ["客户", "kèhù", "client"],
      ["发票", "fāpiào", "invoice / receipt"], ["合同", "hétong", "contract"],
      ["卡", "kǎ", "card"], ["现金", "xiànjīn", "cash"],
      ["职业", "zhíyè", "profession"], ["工程师", "gōngchéngshī", "engineer"],
      ["律师", "lǜshī", "lawyer"], ["老师", "lǎoshī", "teacher"],
      ["生意", "shēngyi", "business"], ["赚钱", "zhuàn qián", "to earn money"],
      ["打折", "dǎzhé", "to give a discount"], ["税", "shuì", "tax"],
    ]),
    V("school", [
      ["学校", "xuéxiào", "school"], ["大学", "dàxué", "university"],
      ["班", "bān", "class"], ["学生", "xuésheng", "student"],
      ["老师", "lǎoshī", "teacher"], ["书", "shū", "book"],
      ["笔记本", "bǐjìběn", "notebook"], ["铅笔", "qiānbǐ", "pencil"],
      ["笔", "bǐ", "pen"], ["纸", "zhǐ", "paper"], ["字", "zì", "character"],
      ["词", "cí", "word"], ["句子", "jùzi", "sentence"],
      ["课", "kè", "lesson / class"], ["考试", "kǎoshì", "exam"],
      ["作业", "zuòyè", "homework"], ["成绩", "chéngjì", "grade / result"],
      ["学", "xué", "to learn"], ["教", "jiāo", "to teach"],
      ["懂", "dǒng", "to understand"], ["解释", "jiěshì", "to explain"],
      ["语言", "yǔyán", "language"], ["中文", "Zhōngwén", "Chinese language"],
      ["历史", "lìshǐ", "history"], ["数学", "shùxué", "mathematics"],
      ["科学", "kēxué", "science"],
    ]),
    V("tech", [
      ["电脑", "diànnǎo", "computer"], ["手机", "shǒujī", "mobile phone"],
      ["电话", "diànhuà", "telephone"], ["屏幕", "píngmù", "screen"],
      ["键盘", "jiànpán", "keyboard"], ["鼠标", "shǔbiāo", "mouse"],
      ["网络", "wǎngluò", "network / internet"], ["上网", "shàngwǎng", "to go online"],
      ["电子邮件", "diànzǐ yóujiàn", "email"], ["密码", "mìmǎ", "password"],
      ["文件", "wénjiàn", "file / document"], ["文件夹", "wénjiànjiā", "folder"],
      ["应用", "yìngyòng", "app"], ["软件", "ruǎnjiàn", "software"],
      ["下载", "xiàzài", "to download"], ["上传", "shàngchuán", "to upload"],
      ["保存", "bǎocún", "to save"], ["删除", "shānchú", "to delete"],
      ["搜索", "sōusuǒ", "to search"], ["打开", "dǎkāi", "to switch on / open"],
      ["关掉", "guāndiào", "to switch off"], ["相机", "xiàngjī", "camera"],
      ["电池", "diànchí", "battery"], ["链接", "liànjiē", "link"],
      ["数据", "shùjù", "data"], ["微信", "Wēixìn", "WeChat"],
    ]),
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["你好，你好吗？", "nǐ hǎo, nǐ hǎo ma", "Hello, how are you?",
        [["你好", "nǐ hǎo"], ["你", "nǐ"], ["好", "hǎo"], ["吗", "ma"]]],
      ["我很好，谢谢", "wǒ hěn hǎo, xièxie", "I am very well, thank you",
        [["我", "wǒ"], ["很", "hěn"], ["好", "hǎo"], ["谢谢", "xièxie"]]],
      ["你叫什么名字？", "nǐ jiào shénme míngzi", "What is your name?",
        [["你", "nǐ"], ["叫", "jiào"], ["什么", "shénme"], ["名字", "míngzi"]]],
      ["我叫李明", "wǒ jiào Lǐ Míng", "My name is Li Ming",
        [["我", "wǒ"], ["叫", "jiào"], ["李明", "Lǐ Míng"]]],
      ["我不明白", "wǒ bù míngbai", "I don't understand",
        [["我", "wǒ"], ["不", "bù"], ["明白", "míngbai"]]],
      ["请再说一遍", "qǐng zài shuō yí biàn", "Please say it again",
        [["请", "qǐng"], ["再", "zài"], ["说", "shuō"], ["一遍", "yí biàn"]]],
      ["很高兴认识你", "hěn gāoxìng rènshi nǐ", "Very pleased to meet you",
        [["很", "hěn"], ["高兴", "gāoxìng"], ["认识", "rènshi"], ["你", "nǐ"]]],
      ["你会说英语吗？", "nǐ huì shuō Yīngyǔ ma", "Can you speak English?",
        [["你", "nǐ"], ["会", "huì"], ["说", "shuō"], ["英语", "Yīngyǔ"], ["吗", "ma"]]],
    ]),
    S("food", [
      ["我要一杯咖啡", "wǒ yào yì bēi kāfēi", "I want a cup of coffee",
        [["我", "wǒ"], ["要", "yào"], ["一杯", "yì bēi"], ["咖啡", "kāfēi"]]],
      ["我饿了", "wǒ è le", "I am hungry",
        [["我", "wǒ"], ["饿", "è"], ["了", "le"]]],
      ["我渴了", "wǒ kě le", "I am thirsty",
        [["我", "wǒ"], ["渴", "kě"], ["了", "le"]]],
      ["这个菜很好吃", "zhège cài hěn hǎochī", "This dish is delicious",
        [["这个", "zhège"], ["菜", "cài"], ["很", "hěn"], ["好吃", "hǎochī"]]],
      ["买单，谢谢", "mǎidān, xièxie", "The bill, please",
        [["买单", "mǎidān"], ["谢谢", "xièxie"]]],
      ["我不吃肉", "wǒ bù chī ròu", "I don't eat meat",
        [["我", "wǒ"], ["不", "bù"], ["吃", "chī"], ["肉", "ròu"]]],
    ]),
    S("travel", [
      ["车站在哪里？", "chēzhàn zài nǎlǐ", "Where is the station?",
        [["车站", "chēzhàn"], ["在", "zài"], ["哪里", "nǎlǐ"]]],
      ["我要一张去北京的票", "wǒ yào yì zhāng qù Běijīng de piào",
        "I want a ticket to Beijing",
        [["我", "wǒ"], ["要", "yào"], ["一张", "yì zhāng"], ["去", "qù"], ["北京", "Běijīng"], ["的", "de"], ["票", "piào"]]],
      ["火车八点到", "huǒchē bā diǎn dào", "The train arrives at eight",
        [["火车", "huǒchē"], ["八点", "bā diǎn"], ["到", "dào"]]],
      ["我迷路了", "wǒ mílù le", "I am lost",
        [["我", "wǒ"], ["迷路", "mílù"], ["了", "le"]]],
      ["请往右转", "qǐng wǎng yòu zhuǎn", "Please turn right",
        [["请", "qǐng"], ["往", "wǎng"], ["右", "yòu"], ["转", "zhuǎn"]]],
    ]),
    S("home", [
      ["我住在一个小房子里", "wǒ zhù zài yí ge xiǎo fángzi lǐ",
        "I live in a small house",
        [["我", "wǒ"], ["住", "zhù"], ["在", "zài"], ["一个", "yí ge"], ["小", "xiǎo"], ["房子", "fángzi"], ["里", "lǐ"]]],
      ["门开着", "mén kāi zhe", "The door is open",
        [["门", "mén"], ["开", "kāi"], ["着", "zhe"]]],
      ["我家很大", "wǒ jiā hěn dà", "My family / home is big",
        [["我", "wǒ"], ["家", "jiā"], ["很", "hěn"], ["大", "dà"]]],
    ]),
    S("time", [
      ["现在几点？", "xiànzài jǐ diǎn", "What time is it now?",
        [["现在", "xiànzài"], ["几点", "jǐ diǎn"]]],
      ["今天是星期一", "jīntiān shì xīngqīyī", "Today is Monday",
        [["今天", "jīntiān"], ["是", "shì"], ["星期一", "xīngqīyī"]]],
      ["明天我去市场", "míngtiān wǒ qù shìchǎng", "Tomorrow I go to the market",
        [["明天", "míngtiān"], ["我", "wǒ"], ["去", "qù"], ["市场", "shìchǎng"]]],
      ["我总是早上工作", "wǒ zǒngshì zǎoshang gōngzuò", "I always work in the morning",
        [["我", "wǒ"], ["总是", "zǒngshì"], ["早上", "zǎoshang"], ["工作", "gōngzuò"]]],
    ]),
    S("school", [
      ["我每天学中文", "wǒ měitiān xué Zhōngwén", "I study Chinese every day",
        [["我", "wǒ"], ["每天", "měitiān"], ["学", "xué"], ["中文", "Zhōngwén"]]],
      ["这本书很有意思", "zhè běn shū hěn yǒu yìsi", "This book is very interesting",
        [["这本", "zhè běn"], ["书", "shū"], ["很", "hěn"], ["有意思", "yǒu yìsi"]]],
      ["你能帮我吗？", "nǐ néng bāng wǒ ma", "Can you help me?",
        [["你", "nǐ"], ["能", "néng"], ["帮", "bāng"], ["我", "wǒ"], ["吗", "ma"]]],
    ]),
    S("health", [
      ["我头疼", "wǒ tóuténg", "I have a headache",
        [["我", "wǒ"], ["头疼", "tóuténg"]]],
      ["我需要医生", "wǒ xūyào yīshēng", "I need a doctor",
        [["我", "wǒ"], ["需要", "xūyào"], ["医生", "yīshēng"]]],
      ["我不舒服", "wǒ bù shūfu", "I don't feel well",
        [["我", "wǒ"], ["不", "bù"], ["舒服", "shūfu"]]],
    ]),
    S("work", [
      ["这个多少钱？", "zhège duōshao qián", "How much is this?",
        [["这个", "zhège"], ["多少", "duōshao"], ["钱", "qián"]]],
      ["太贵了", "tài guì le", "It's too expensive",
        [["太", "tài"], ["贵", "guì"], ["了", "le"]]],
      ["我在办公室工作", "wǒ zài bàngōngshì gōngzuò", "I work in an office",
        [["我", "wǒ"], ["在", "zài"], ["办公室", "bàngōngshì"], ["工作", "gōngzuò"]]],
    ]),
  );

  /* ----------------------------- Conjugation ------------------------------
   * Chinese verbs never change form. What changes is the marker around them:
   * 了 for a completed action, 在 for something in progress, 会/要 for the
   * future. These tables drill that pattern with the pronouns. */
  const CONJUGATION = [
    C("吃", "chī", "eat", [
      ["我吃了", "wǒ chī le", "I ate", "I", "past"],
      ["你吃了", "nǐ chī le", "you ate", "you", "past"],
      ["他吃了", "tā chī le", "he ate", "he", "past"],
      ["她吃了", "tā chī le", "she ate", "she", "past"],
      ["我们吃了", "wǒmen chī le", "we ate", "we", "past"],
      ["他们吃了", "tāmen chī le", "they ate", "they", "past"],
      ["我吃", "wǒ chī", "I eat", "I", "present"],
      ["你吃", "nǐ chī", "you eat", "you", "present"],
      ["他吃", "tā chī", "he eats", "he", "present"],
      ["我们吃", "wǒmen chī", "we eat", "we", "present"],
      ["他们吃", "tāmen chī", "they eat", "they", "present"],
      ["我会吃", "wǒ huì chī", "I will eat", "I", "future"],
      ["你会吃", "nǐ huì chī", "you will eat", "you", "future"],
      ["他会吃", "tā huì chī", "he will eat", "he", "future"],
      ["我们会吃", "wǒmen huì chī", "we will eat", "we", "future"],
      ["他们会吃", "tāmen huì chī", "they will eat", "they", "future"],
    ]),
    C("喝", "hē", "drink", [
      ["我喝了", "wǒ hē le", "I drank", "I", "past"],
      ["你喝了", "nǐ hē le", "you drank", "you", "past"],
      ["他喝了", "tā hē le", "he drank", "he", "past"],
      ["我们喝了", "wǒmen hē le", "we drank", "we", "past"],
      ["他们喝了", "tāmen hē le", "they drank", "they", "past"],
      ["我喝", "wǒ hē", "I drink", "I", "present"],
      ["你喝", "nǐ hē", "you drink", "you", "present"],
      ["他喝", "tā hē", "he drinks", "he", "present"],
      ["我们喝", "wǒmen hē", "we drink", "we", "present"],
      ["他们喝", "tāmen hē", "they drink", "they", "present"],
      ["我会喝", "wǒ huì hē", "I will drink", "I", "future"],
      ["你会喝", "nǐ huì hē", "you will drink", "you", "future"],
      ["他会喝", "tā huì hē", "he will drink", "he", "future"],
      ["我们会喝", "wǒmen huì hē", "we will drink", "we", "future"],
      ["他们会喝", "tāmen huì hē", "they will drink", "they", "future"],
    ]),
    C("去", "qù", "go", [
      ["我去了", "wǒ qù le", "I went", "I", "past"],
      ["你去了", "nǐ qù le", "you went", "you", "past"],
      ["他去了", "tā qù le", "he went", "he", "past"],
      ["我们去了", "wǒmen qù le", "we went", "we", "past"],
      ["他们去了", "tāmen qù le", "they went", "they", "past"],
      ["我去", "wǒ qù", "I go", "I", "present"],
      ["你去", "nǐ qù", "you go", "you", "present"],
      ["他去", "tā qù", "he goes", "he", "present"],
      ["我们去", "wǒmen qù", "we go", "we", "present"],
      ["他们去", "tāmen qù", "they go", "they", "present"],
      ["我要去", "wǒ yào qù", "I will go", "I", "future"],
      ["你要去", "nǐ yào qù", "you will go", "you", "future"],
      ["他要去", "tā yào qù", "he will go", "he", "future"],
      ["我们要去", "wǒmen yào qù", "we will go", "we", "future"],
      ["他们要去", "tāmen yào qù", "they will go", "they", "future"],
    ]),
    C("说", "shuō", "speak", [
      ["我说了", "wǒ shuō le", "I spoke", "I", "past"],
      ["你说了", "nǐ shuō le", "you spoke", "you", "past"],
      ["他说了", "tā shuō le", "he spoke", "he", "past"],
      ["我们说了", "wǒmen shuō le", "we spoke", "we", "past"],
      ["他们说了", "tāmen shuō le", "they spoke", "they", "past"],
      ["我说", "wǒ shuō", "I speak", "I", "present"],
      ["你说", "nǐ shuō", "you speak", "you", "present"],
      ["他说", "tā shuō", "he speaks", "he", "present"],
      ["我们说", "wǒmen shuō", "we speak", "we", "present"],
      ["他们说", "tāmen shuō", "they speak", "they", "present"],
      ["我会说", "wǒ huì shuō", "I will speak", "I", "future"],
      ["你会说", "nǐ huì shuō", "you will speak", "you", "future"],
      ["他会说", "tā huì shuō", "he will speak", "he", "future"],
      ["我们会说", "wǒmen huì shuō", "we will speak", "we", "future"],
      ["他们会说", "tāmen huì shuō", "they will speak", "they", "future"],
    ]),
    C("看", "kàn", "look / read", [
      ["我看了", "wǒ kàn le", "I looked", "I", "past"],
      ["你看了", "nǐ kàn le", "you looked", "you", "past"],
      ["他看了", "tā kàn le", "he looked", "he", "past"],
      ["我们看了", "wǒmen kàn le", "we looked", "we", "past"],
      ["他们看了", "tāmen kàn le", "they looked", "they", "past"],
      ["我看", "wǒ kàn", "I look", "I", "present"],
      ["你看", "nǐ kàn", "you look", "you", "present"],
      ["他看", "tā kàn", "he looks", "he", "present"],
      ["我们看", "wǒmen kàn", "we look", "we", "present"],
      ["他们看", "tāmen kàn", "they look", "they", "present"],
      ["我会看", "wǒ huì kàn", "I will look", "I", "future"],
      ["你会看", "nǐ huì kàn", "you will look", "you", "future"],
      ["他会看", "tā huì kàn", "he will look", "he", "future"],
      ["我们会看", "wǒmen huì kàn", "we will look", "we", "future"],
      ["他们会看", "tāmen huì kàn", "they will look", "they", "future"],
    ]),
    C("写", "xiě", "write", [
      ["我写了", "wǒ xiě le", "I wrote", "I", "past"],
      ["你写了", "nǐ xiě le", "you wrote", "you", "past"],
      ["他写了", "tā xiě le", "he wrote", "he", "past"],
      ["我们写了", "wǒmen xiě le", "we wrote", "we", "past"],
      ["他们写了", "tāmen xiě le", "they wrote", "they", "past"],
      ["我写", "wǒ xiě", "I write", "I", "present"],
      ["你写", "nǐ xiě", "you write", "you", "present"],
      ["他写", "tā xiě", "he writes", "he", "present"],
      ["我们写", "wǒmen xiě", "we write", "we", "present"],
      ["他们写", "tāmen xiě", "they write", "they", "present"],
      ["我会写", "wǒ huì xiě", "I will write", "I", "future"],
      ["你会写", "nǐ huì xiě", "you will write", "you", "future"],
      ["他会写", "tā huì xiě", "he will write", "he", "future"],
      ["我们会写", "wǒmen huì xiě", "we will write", "we", "future"],
      ["他们会写", "tāmen huì xiě", "they will write", "they", "future"],
    ]),
    C("买", "mǎi", "buy", [
      ["我买了", "wǒ mǎi le", "I bought", "I", "past"],
      ["你买了", "nǐ mǎi le", "you bought", "you", "past"],
      ["他买了", "tā mǎi le", "he bought", "he", "past"],
      ["我们买了", "wǒmen mǎi le", "we bought", "we", "past"],
      ["他们买了", "tāmen mǎi le", "they bought", "they", "past"],
      ["我买", "wǒ mǎi", "I buy", "I", "present"],
      ["你买", "nǐ mǎi", "you buy", "you", "present"],
      ["他买", "tā mǎi", "he buys", "he", "present"],
      ["我们买", "wǒmen mǎi", "we buy", "we", "present"],
      ["他们买", "tāmen mǎi", "they buy", "they", "present"],
      ["我要买", "wǒ yào mǎi", "I will buy", "I", "future"],
      ["你要买", "nǐ yào mǎi", "you will buy", "you", "future"],
      ["他要买", "tā yào mǎi", "he will buy", "he", "future"],
      ["我们要买", "wǒmen yào mǎi", "we will buy", "we", "future"],
      ["他们要买", "tāmen yào mǎi", "they will buy", "they", "future"],
    ]),
    C("学习", "xuéxí", "study", [
      ["我学习了", "wǒ xuéxí le", "I studied", "I", "past"],
      ["你学习了", "nǐ xuéxí le", "you studied", "you", "past"],
      ["他学习了", "tā xuéxí le", "he studied", "he", "past"],
      ["我们学习了", "wǒmen xuéxí le", "we studied", "we", "past"],
      ["他们学习了", "tāmen xuéxí le", "they studied", "they", "past"],
      ["我学习", "wǒ xuéxí", "I study", "I", "present"],
      ["你学习", "nǐ xuéxí", "you study", "you", "present"],
      ["他学习", "tā xuéxí", "he studies", "he", "present"],
      ["我们学习", "wǒmen xuéxí", "we study", "we", "present"],
      ["他们学习", "tāmen xuéxí", "they study", "they", "present"],
      ["我会学习", "wǒ huì xuéxí", "I will study", "I", "future"],
      ["你会学习", "nǐ huì xuéxí", "you will study", "you", "future"],
      ["他会学习", "tā huì xuéxí", "he will study", "he", "future"],
      ["我们会学习", "wǒmen huì xuéxí", "we will study", "we", "future"],
      ["他们会学习", "tāmen huì xuéxí", "they will study", "they", "future"],
    ]),
    C("工作", "gōngzuò", "work", [
      ["我工作了", "wǒ gōngzuò le", "I worked", "I", "past"],
      ["你工作了", "nǐ gōngzuò le", "you worked", "you", "past"],
      ["他工作了", "tā gōngzuò le", "he worked", "he", "past"],
      ["我们工作了", "wǒmen gōngzuò le", "we worked", "we", "past"],
      ["他们工作了", "tāmen gōngzuò le", "they worked", "they", "past"],
      ["我工作", "wǒ gōngzuò", "I work", "I", "present"],
      ["你工作", "nǐ gōngzuò", "you work", "you", "present"],
      ["他工作", "tā gōngzuò", "he works", "he", "present"],
      ["我们工作", "wǒmen gōngzuò", "we work", "we", "present"],
      ["他们工作", "tāmen gōngzuò", "they work", "they", "present"],
      ["我会工作", "wǒ huì gōngzuò", "I will work", "I", "future"],
      ["你会工作", "nǐ huì gōngzuò", "you will work", "you", "future"],
      ["他会工作", "tā huì gōngzuò", "he will work", "he", "future"],
      ["我们会工作", "wǒmen huì gōngzuò", "we will work", "we", "future"],
      ["他们会工作", "tāmen huì gōngzuò", "they will work", "they", "future"],
    ]),
    C("来", "lái", "come", [
      ["我来了", "wǒ lái le", "I came", "I", "past"],
      ["你来了", "nǐ lái le", "you came", "you", "past"],
      ["他来了", "tā lái le", "he came", "he", "past"],
      ["我们来了", "wǒmen lái le", "we came", "we", "past"],
      ["他们来了", "tāmen lái le", "they came", "they", "past"],
      ["我来", "wǒ lái", "I come", "I", "present"],
      ["你来", "nǐ lái", "you come", "you", "present"],
      ["他来", "tā lái", "he comes", "he", "present"],
      ["我们来", "wǒmen lái", "we come", "we", "present"],
      ["他们来", "tāmen lái", "they come", "they", "present"],
      ["我会来", "wǒ huì lái", "I will come", "I", "future"],
      ["你会来", "nǐ huì lái", "you will come", "you", "future"],
      ["他会来", "tā huì lái", "he will come", "he", "future"],
      ["我们会来", "wǒmen huì lái", "we will come", "we", "future"],
      ["他们会来", "tāmen huì lái", "they will come", "they", "future"],
    ]),
  ];

  /* ------------------------------ Proverbs -------------------------------
   * 成语 (chéngyǔ) and common sayings — four-character idioms carry a whole
   * story in four syllables, which is half the pleasure of learning them. */
  const PROVERBS = [
    { n: 1, chapterEn: "Persistence",
      l1: "有志者", l2: "事竟成。",
      tr1: "yǒu zhì zhě", tr2: "shì jìng chéng",
      en: "Where there is a will, the thing will be accomplished." },
    { n: 2, chapterEn: "Beginnings",
      l1: "千里之行，", l2: "始于足下。",
      tr1: "qiān lǐ zhī xíng", tr2: "shǐ yú zú xià",
      en: "A journey of a thousand miles begins beneath one's feet." },
    { n: 3, chapterEn: "Learning",
      l1: "学而不思则罔，", l2: "思而不学则殆。",
      tr1: "xué ér bù sī zé wǎng", tr2: "sī ér bù xué zé dài",
      en: "Learning without thought is labour lost; thought without learning is perilous." },
    { n: 4, chapterEn: "Practice",
      l1: "熟能", l2: "生巧。",
      tr1: "shú néng", tr2: "shēng qiǎo",
      en: "Familiarity breeds skill — practice makes perfect." },
    { n: 5, chapterEn: "Patience",
      l1: "水滴", l2: "石穿。",
      tr1: "shuǐ dī", tr2: "shí chuān",
      en: "Dripping water bores through stone." },
    { n: 6, chapterEn: "Prudence",
      l1: "入乡", l2: "随俗。",
      tr1: "rù xiāng", tr2: "suí sú",
      en: "Enter a village, follow its customs." },
    { n: 7, chapterEn: "Fortune",
      l1: "塞翁失马，", l2: "焉知非福。",
      tr1: "sài wēng shī mǎ", tr2: "yān zhī fēi fú",
      en: "The old man lost his horse — how do you know it isn't good luck?" },
    { n: 8, chapterEn: "Effort",
      l1: "一分耕耘，", l2: "一分收获。",
      tr1: "yì fēn gēngyún", tr2: "yì fēn shōuhuò",
      en: "One measure of ploughing, one measure of harvest." },
    { n: 9, chapterEn: "Friendship",
      l1: "在家靠父母，", l2: "出外靠朋友。",
      tr1: "zài jiā kào fùmǔ", tr2: "chū wài kào péngyou",
      en: "At home rely on your parents; away from home, on your friends." },
    { n: 10, chapterEn: "Time",
      l1: "一寸光阴", l2: "一寸金。",
      tr1: "yí cùn guāngyīn", tr2: "yí cùn jīn",
      en: "An inch of time is an inch of gold." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("chinese", {
    icons: {
      alphabet: "拼音", greetings: "问候", numbers: "数字", colors: "颜色",
      family: "家庭", people: "人们", pronouns: "代词", questions: "疑问",
      grammar: "虚词", adjectives: "形容词", adverbs: "副词", verbs: "动词",
      food: "食物", body: "身体", health: "健康", clothing: "衣服", home: "家",
      animals: "动物", nature: "自然", places: "地方", travel: "旅行",
      time: "时间", work: "工作", school: "学校", tech: "科技", sentences: "句子",
    },
    ui: { account: "账户", progress: "进度", search: "搜索" },
    alphabet: ALPHABET,
    alphabetTitle: "Pinyin & tones",
    alphabetLabels: ["Initials & finals", "Tones"],
    alphabetUnit: "sounds",
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "复习", vocab: "生词", sentence: "句子", conjugation: "动词",
      listening: "听力", mixed: "综合", reading: "成语",
    },
    reading: {
      id: "chengyu", title: "Sayings", native: "成语",
      desc: "Classic Chinese idioms and proverbs",
      blurb: "成语 — four-character idioms and old sayings, each carrying a whole story.",
      unit: "sayings", numLabel: "第",
      lineQuestion: "Which line completes this saying?",
      items: PROVERBS,
    },
  });
})();
