/* ============================================================================
 * English course — data only.
 *
 * This course teaches English vocabulary rather than translating into it, so
 * the three lines are: `ta` the word, `tr` a plain respelling of how it sounds
 * (stressed syllable in CAPS), `en` a short definition in simple English.
 * Choice questions therefore read "which definition fits this word?", which is
 * how a vocabulary builder should work.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------ Alphabet ------------------------------- */
  const LETTERS = A([
    ["A a", "ay"], ["B b", "bee"], ["C c", "see"], ["D d", "dee"], ["E e", "ee"],
    ["F f", "ef"], ["G g", "jee"], ["H h", "aitch"], ["I i", "eye"], ["J j", "jay"],
    ["K k", "kay"], ["L l", "el"], ["M m", "em"], ["N n", "en"], ["O o", "oh"],
    ["P p", "pee"], ["Q q", "cue"], ["R r", "ar"], ["S s", "ess"], ["T t", "tee"],
    ["U u", "you"], ["V v", "vee"], ["W w", "DUB-el-you"], ["X x", "eks"],
    ["Y y", "why"], ["Z z", "zed / zee"],
  ]);
  const SOUNDS = A([
    ["th (voiced)", "th", "as in 'this'"], ["th (voiceless)", "th", "as in 'think'"],
    ["sh", "sh", "as in 'ship'"], ["ch", "ch", "as in 'church'"],
    ["ng", "ng", "as in 'sing'"], ["ph", "f", "as in 'phone'"],
    ["silent e", "—", "makes the vowel long: 'hat' → 'hate'"],
    ["oo (long)", "oo", "as in 'food'"], ["oo (short)", "uu", "as in 'book'"],
    ["ee", "ee", "as in 'see'"], ["ea", "ee / e", "'sea' but 'bread'"],
    ["ai / ay", "ay", "as in 'rain', 'day'"], ["ow / ou", "ow", "as in 'now', 'house'"],
    ["oi / oy", "oy", "as in 'coin', 'boy'"],
    ["schwa", "uh", "the weak vowel in 'about'"],
    ["silent k", "—", "as in 'knee', 'know'"],
    ["silent gh", "—", "as in 'night', 'through'"],
  ]);
  const ALPHABET = { vowels: LETTERS, consonants: SOUNDS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["hello", "huh-LOH", "a greeting when you meet someone"],
      ["hi", "HY", "an informal hello"],
      ["good morning", "guud MOR-ning", "a greeting used before noon"],
      ["good afternoon", "guud af-ter-NOON", "a greeting used after noon"],
      ["good evening", "guud EEV-ning", "a greeting used at night"],
      ["goodbye", "guud-BY", "what you say when leaving"],
      ["bye", "BY", "an informal goodbye"],
      ["see you later", "see yoo LAY-ter", "goodbye until the next meeting"],
      ["thank you", "THANK yoo", "words that show gratitude"],
      ["thanks", "THANKS", "an informal thank you"],
      ["you're welcome", "yor WEL-kum", "the polite reply to thank you"],
      ["please", "PLEEZ", "a polite word added to a request"],
      ["yes", "YES", "a word of agreement"],
      ["no", "NOH", "a word of refusal"],
      ["sorry", "SOR-ee", "a word said when apologising"],
      ["excuse me", "ik-SKYOOZ mee", "a polite way to get attention"],
      ["how are you?", "how ar YOO", "a question asking about someone's wellbeing"],
      ["I'm fine", "ym FYN", "a reply meaning you are well"],
      ["nice to meet you", "nys tuh MEET yoo", "a greeting at a first meeting"],
      ["welcome", "WEL-kum", "a warm greeting to an arriving guest"],
      ["congratulations", "kun-grach-uu-LAY-shunz", "words of praise for an achievement"],
      ["good luck", "guud LUK", "a wish for success"],
      ["cheers", "CHEERZ", "a toast, or an informal thanks"],
      ["take care", "tayk KAIR", "a friendly goodbye"],
      ["okay", "oh-KAY", "a word meaning fine or agreed"],
      ["of course", "uv KORS", "certainly; without question"],
    ]),
    V("numbers", [
      ["zero", "ZEER-oh", "the number 0"], ["one", "WUN", "the number 1"],
      ["two", "TOO", "the number 2"], ["three", "THREE", "the number 3"],
      ["four", "FOR", "the number 4"], ["five", "FYV", "the number 5"],
      ["six", "SIKS", "the number 6"], ["seven", "SEV-en", "the number 7"],
      ["eight", "AYT", "the number 8"], ["nine", "NYN", "the number 9"],
      ["ten", "TEN", "the number 10"], ["eleven", "i-LEV-en", "the number 11"],
      ["twelve", "TWELV", "the number 12"], ["thirteen", "thur-TEEN", "the number 13"],
      ["twenty", "TWEN-tee", "the number 20"], ["thirty", "THUR-tee", "the number 30"],
      ["fifty", "FIF-tee", "the number 50"], ["hundred", "HUN-dred", "the number 100"],
      ["thousand", "THOW-zand", "the number 1,000"],
      ["million", "MIL-yun", "a thousand thousand"],
      ["first", "FURST", "coming before all others"],
      ["second", "SEK-und", "coming after the first"],
      ["last", "LAST", "coming after all others"],
      ["half", "HAF", "one of two equal parts"],
      ["quarter", "KWOR-ter", "one of four equal parts"],
      ["double", "DUB-el", "twice as much"],
      ["several", "SEV-rul", "more than two but not many"],
      ["dozen", "DUZ-en", "a group of twelve"],
    ]),
    V("colors", [
      ["red", "RED", "the colour of blood"],
      ["blue", "BLOO", "the colour of a clear sky"],
      ["green", "GREEN", "the colour of grass"],
      ["yellow", "YEL-oh", "the colour of a lemon"],
      ["black", "BLAK", "the darkest colour"],
      ["white", "WYT", "the lightest colour, like snow"],
      ["grey", "GRAY", "a colour between black and white"],
      ["brown", "BROWN", "the colour of soil or wood"],
      ["orange", "OR-inj", "a colour between red and yellow"],
      ["pink", "PINK", "a pale red"],
      ["purple", "PUR-pel", "a colour between red and blue"],
      ["golden", "GOHL-den", "having the colour of gold"],
      ["silver", "SIL-ver", "a shiny pale grey"],
      ["light", "LYT", "pale in colour"],
      ["dark", "DARK", "deep in colour, with little light"],
      ["colour", "KUL-er", "the quality that makes something red, blue, etc."],
      ["colourful", "KUL-er-ful", "having many bright colours"],
      ["pale", "PAYL", "light and weak in colour"],
      ["bright", "BRYT", "strong and shining"],
      ["shade", "SHAYD", "a particular version of a colour"],
      ["stripe", "STRYP", "a long band of colour"],
      ["plain", "PLAYN", "of one colour, with no pattern"],
    ]),
    V("family", [
      ["family", "FAM-uh-lee", "a group of people related to each other"],
      ["mother", "MUTH-er", "a female parent"], ["father", "FAH-ther", "a male parent"],
      ["mum", "MUM", "an informal word for mother"],
      ["dad", "DAD", "an informal word for father"],
      ["parents", "PAIR-ents", "a mother and father"],
      ["son", "SUN", "a male child"], ["daughter", "DAW-ter", "a female child"],
      ["brother", "BRUTH-er", "a male sibling"], ["sister", "SIS-ter", "a female sibling"],
      ["grandfather", "GRAND-fah-ther", "the father of your parent"],
      ["grandmother", "GRAND-muth-er", "the mother of your parent"],
      ["grandchild", "GRAND-chyld", "the child of your child"],
      ["uncle", "UN-kel", "the brother of your parent"],
      ["aunt", "ANT", "the sister of your parent"],
      ["cousin", "KUZ-en", "the child of your aunt or uncle"],
      ["nephew", "NEF-yoo", "the son of your sibling"],
      ["niece", "NEES", "the daughter of your sibling"],
      ["husband", "HUZ-band", "a married man"],
      ["wife", "WYF", "a married woman"],
      ["baby", "BAY-bee", "a very young child"],
      ["child", "CHYLD", "a young person"],
      ["relative", "REL-uh-tiv", "any member of your family"],
      ["wedding", "WED-ing", "the ceremony of getting married"],
      ["twin", "TWIN", "one of two children born together"],
    ]),
    V("people", [
      ["person", "PUR-sun", "a single human being"],
      ["people", "PEE-pel", "more than one person"],
      ["man", "MAN", "an adult male"], ["woman", "WUUM-an", "an adult female"],
      ["boy", "BOY", "a young male"], ["girl", "GURL", "a young female"],
      ["friend", "FREND", "a person you like and trust"],
      ["neighbour", "NAY-ber", "a person who lives near you"],
      ["stranger", "STRAYN-jer", "a person you don't know"],
      ["guest", "GEST", "a person you invite"],
      ["adult", "AD-ult", "a fully grown person"],
      ["teenager", "TEEN-ay-jer", "a person aged 13 to 19"],
      ["colleague", "KOL-eeg", "a person you work with"],
      ["team", "TEEM", "a group working together"],
      ["group", "GROOP", "a number of people or things together"],
      ["crowd", "KROWD", "a large number of people in one place"],
      ["name", "NAYM", "the word a person is called by"],
      ["surname", "SUR-naym", "a family name"],
      ["partner", "PART-ner", "the person you share your life with"],
      ["foreigner", "FOR-in-er", "a person from another country"],
      ["citizen", "SIT-i-zen", "a legal member of a country"],
      ["neighbourhood", "NAY-ber-huud", "the area where you live"],
      ["stranger's face", "STRAYN-jerz FAYS", "a face you do not recognise"],
    ]),
    V("pronouns", [
      ["I", "EYE", "the word you use for yourself"],
      ["you", "YOO", "the person being spoken to"],
      ["he", "HEE", "a male already mentioned"],
      ["she", "SHEE", "a female already mentioned"],
      ["it", "IT", "a thing already mentioned"],
      ["we", "WEE", "you and I together"],
      ["they", "THAY", "more than one person already mentioned"],
      ["me", "MEE", "the object form of I"],
      ["him", "HIM", "the object form of he"],
      ["her", "HUR", "the object form of she"],
      ["us", "US", "the object form of we"],
      ["them", "THEM", "the object form of they"],
      ["my", "MY", "belonging to me"],
      ["your", "YOR", "belonging to you"],
      ["his", "HIZ", "belonging to him"],
      ["our", "OWR", "belonging to us"],
      ["their", "THAIR", "belonging to them"],
      ["this", "THIS", "the thing near me"],
      ["that", "THAT", "the thing further away"],
      ["these", "THEEZ", "the things near me"],
      ["someone", "SUM-wun", "an unnamed person"],
      ["nobody", "NOH-bod-ee", "not a single person"],
      ["everyone", "EV-ree-wun", "all the people"],
      ["myself", "my-SELF", "me, and no one else"],
    ]),
    V("questions", [
      ["what", "WOT", "asks about a thing"],
      ["who", "HOO", "asks about a person"],
      ["where", "WAIR", "asks about a place"],
      ["when", "WEN", "asks about a time"],
      ["why", "WY", "asks about a reason"],
      ["how", "HOW", "asks about a method"],
      ["which", "WICH", "asks you to choose between options"],
      ["how much", "how MUCH", "asks about an amount or price"],
      ["how many", "how MEN-ee", "asks about a number of things"],
      ["how long", "how LONG", "asks about a length of time"],
      ["whose", "HOOZ", "asks who something belongs to"],
      ["question", "KWES-chun", "a sentence that asks something"],
      ["answer", "AN-ser", "a reply to a question"],
      ["ask", "ASK", "to put a question to someone"],
      ["reply", "ri-PLY", "to answer"],
      ["wonder", "WUN-der", "to want to know something"],
      ["doubt", "DOWT", "to be unsure that something is true"],
      ["explain", "ik-SPLAYN", "to make something clear"],
      ["mean", "MEEN", "to have a particular sense"],
      ["really?", "REE-uh-lee", "a short question showing surprise"],
    ]),
    V("grammar", [
      ["and", "AND", "joins two things together"],
      ["or", "OR", "shows a choice between things"],
      ["but", "BUT", "introduces a contrast"],
      ["because", "bi-KOZ", "gives a reason"],
      ["if", "IF", "introduces a condition"],
      ["so", "SOH", "shows a result"],
      ["of", "UV", "shows belonging"],
      ["to", "TOO", "shows direction or purpose"],
      ["in", "IN", "inside something"],
      ["on", "ON", "resting on a surface"],
      ["at", "AT", "at a point or place"],
      ["with", "WITH", "together with something"],
      ["without", "with-OWT", "not having something"],
      ["for", "FOR", "showing purpose or benefit"],
      ["from", "FROM", "showing the starting point"],
      ["between", "bi-TWEEN", "in the space separating two things"],
      ["under", "UN-der", "below something"],
      ["over", "OH-ver", "above, or more than"],
      ["through", "THROO", "from one side to the other"],
      ["until", "un-TIL", "up to a point in time"],
      ["the", "THUH", "points to a specific thing"],
      ["a", "UH", "points to any one thing"],
      ["also", "AWL-soh", "in addition"],
      ["although", "awl-THOH", "despite the fact that"],
      ["however", "how-EV-er", "introduces a contrast"],
      ["not", "NOT", "makes a sentence negative"],
      ["while", "WYL", "during the time that"],
    ]),
    V("adjectives", [
      ["big", "BIG", "large in size"], ["small", "SMAWL", "little in size"],
      ["good", "GUUD", "of high quality"], ["bad", "BAD", "of poor quality"],
      ["new", "NYOO", "made or bought recently"],
      ["old", "OHLD", "having existed a long time"],
      ["young", "YUNG", "not old; early in life"],
      ["long", "LONG", "measuring a lot from end to end"],
      ["short", "SHORT", "not long; not tall"],
      ["high", "HY", "far above the ground"],
      ["hot", "HOT", "at a high temperature"],
      ["cold", "KOHLD", "at a low temperature"],
      ["easy", "EE-zee", "not difficult"],
      ["difficult", "DIF-i-kult", "needing effort or skill"],
      ["beautiful", "BYOO-ti-ful", "very pleasing to look at"],
      ["ugly", "UG-lee", "unpleasant to look at"],
      ["strong", "STRONG", "having great power"],
      ["weak", "WEEK", "lacking strength"],
      ["fast", "FAST", "moving quickly"],
      ["slow", "SLOH", "moving without speed"],
      ["rich", "RICH", "having a lot of money"],
      ["poor", "POR", "having very little money"],
      ["happy", "HAP-ee", "feeling pleasure"],
      ["sad", "SAD", "feeling unhappy"],
      ["tired", "TY-erd", "needing rest"],
      ["clean", "KLEEN", "free from dirt"],
      ["dirty", "DUR-tee", "covered in dirt"],
      ["full", "FUUL", "holding as much as possible"],
      ["empty", "EMP-tee", "containing nothing"],
      ["expensive", "ik-SPEN-siv", "costing a lot"],
      ["cheap", "CHEEP", "costing little"],
      ["important", "im-POR-tant", "having great value or effect"],
      ["safe", "SAYF", "free from danger"],
      ["quiet", "KWY-et", "making little noise"],
    ]),
    V("adverbs", [
      ["very", "VER-ee", "to a great degree"],
      ["quite", "KWYT", "to some degree"],
      ["too", "TOO", "more than is wanted"],
      ["well", "WEL", "in a good way"],
      ["badly", "BAD-lee", "in a poor way"],
      ["always", "AWL-wayz", "at every time"],
      ["never", "NEV-er", "at no time"],
      ["sometimes", "SUM-tymz", "on some occasions"],
      ["often", "OF-en", "many times"],
      ["now", "NOW", "at this moment"],
      ["today", "tuh-DAY", "on this day"],
      ["yesterday", "YES-ter-day", "on the day before today"],
      ["tomorrow", "tuh-MOR-oh", "on the day after today"],
      ["early", "UR-lee", "before the usual time"],
      ["late", "LAYT", "after the usual time"],
      ["here", "HEER", "in this place"],
      ["there", "THAIR", "in that place"],
      ["together", "tuh-GETH-er", "with each other"],
      ["only", "OHN-lee", "and nothing more"],
      ["maybe", "MAY-bee", "possibly"],
      ["already", "awl-RED-ee", "before now"],
      ["still", "STIL", "continuing up to now"],
      ["again", "uh-GEN", "one more time"],
      ["almost", "AWL-mohst", "very nearly"],
      ["slowly", "SLOH-lee", "at a low speed"],
      ["quickly", "KWIK-lee", "at high speed"],
      ["carefully", "KAIR-ful-ee", "with attention"],
      ["suddenly", "SUD-en-lee", "without warning"],
    ]),
    V("verbs", [
      ["be", "BEE", "to exist, or to have a quality"],
      ["have", "HAV", "to own or hold"],
      ["do", "DOO", "to perform an action"],
      ["go", "GOH", "to move to another place"],
      ["come", "KUM", "to move towards the speaker"],
      ["can", "KAN", "to be able to"],
      ["want", "WONT", "to wish for something"],
      ["need", "NEED", "to require something"],
      ["know", "NOH", "to have information about"],
      ["think", "THINK", "to use your mind"],
      ["say", "SAY", "to speak words"],
      ["speak", "SPEEK", "to use your voice to talk"],
      ["eat", "EET", "to put food in your mouth"],
      ["drink", "DRINK", "to swallow liquid"],
      ["live", "LIV", "to be alive, or to have a home"],
      ["see", "SEE", "to notice with your eyes"],
      ["watch", "WOCH", "to look at for a while"],
      ["listen", "LIS-en", "to pay attention to sound"],
      ["read", "REED", "to look at and understand words"],
      ["write", "RYT", "to put words on paper"],
      ["work", "WURK", "to do a job"],
      ["learn", "LURN", "to gain knowledge"],
      ["sleep", "SLEEP", "to rest with your eyes closed"],
      ["buy", "BY", "to get something for money"],
      ["sell", "SEL", "to give something for money"],
      ["open", "OH-pen", "to make something not closed"],
      ["close", "KLOHZ", "to shut something"],
      ["begin", "bi-GIN", "to start"],
      ["finish", "FIN-ish", "to bring to an end"],
      ["help", "HELP", "to make things easier for someone"],
      ["walk", "WAWK", "to move on foot"],
      ["run", "RUN", "to move quickly on foot"],
      ["wait", "WAYT", "to stay until something happens"],
      ["give", "GIV", "to hand something to someone"],
      ["take", "TAYK", "to get hold of something"],
      ["bring", "BRING", "to carry something here"],
      ["find", "FYND", "to discover something"],
      ["lose", "LOOZ", "to no longer have something"],
      ["change", "CHAYNJ", "to make different"],
      ["try", "TRY", "to make an effort"],
    ]),
    V("food", [
      ["food", "FOOD", "what people and animals eat"],
      ["water", "WAW-ter", "the clear liquid we drink"],
      ["bread", "BRED", "a baked food made from flour"],
      ["rice", "RYS", "small white grains, boiled and eaten"],
      ["meat", "MEET", "the flesh of animals used as food"],
      ["chicken", "CHIK-en", "a common bird, or its meat"],
      ["fish", "FISH", "an animal that lives in water"],
      ["egg", "EG", "an oval food laid by a bird"],
      ["milk", "MILK", "a white drink from cows"],
      ["cheese", "CHEEZ", "a solid food made from milk"],
      ["butter", "BUT-er", "a soft yellow fat spread on bread"],
      ["fruit", "FROOT", "the sweet part of a plant you eat"],
      ["apple", "AP-el", "a round red or green fruit"],
      ["banana", "buh-NAH-nuh", "a long curved yellow fruit"],
      ["orange", "OR-inj", "a round citrus fruit"],
      ["vegetable", "VEJ-tuh-bel", "a plant grown to be eaten"],
      ["potato", "puh-TAY-toh", "a round vegetable grown underground"],
      ["tomato", "tuh-MAH-toh", "a soft red salad fruit"],
      ["onion", "UN-yun", "a strong-tasting round vegetable"],
      ["salt", "SAWLT", "a white seasoning from the sea"],
      ["pepper", "PEP-er", "a hot black seasoning"],
      ["sugar", "SHUUG-er", "a sweet white food"],
      ["oil", "OYL", "a smooth liquid fat used in cooking"],
      ["coffee", "KOF-ee", "a hot dark drink made from beans"],
      ["tea", "TEE", "a hot drink made from leaves"],
      ["juice", "JOOS", "the liquid from a fruit"],
      ["soup", "SOOP", "a hot liquid food"],
      ["salad", "SAL-ad", "a cold dish of raw vegetables"],
      ["dessert", "di-ZURT", "a sweet dish at the end of a meal"],
      ["breakfast", "BREK-fast", "the first meal of the day"],
      ["lunch", "LUNCH", "the midday meal"],
      ["dinner", "DIN-er", "the main evening meal"],
      ["restaurant", "RES-tuh-ront", "a place where meals are served"],
      ["bill", "BIL", "the note showing what you owe"],
      ["taste", "TAYST", "the flavour of a food"],
      ["hungry", "HUNG-gree", "wanting to eat"],
      ["thirsty", "THURS-tee", "wanting to drink"],
      ["delicious", "di-LISH-us", "tasting very good"],
    ]),
    V("body", [
      ["body", "BOD-ee", "the whole physical form of a person"],
      ["head", "HED", "the top part of the body"],
      ["hair", "HAIR", "the fine strands growing on the head"],
      ["face", "FAYS", "the front of the head"],
      ["eye", "EYE", "the organ you see with"],
      ["ear", "EER", "the organ you hear with"],
      ["nose", "NOHZ", "the organ you smell with"],
      ["mouth", "MOWTH", "the opening you eat and speak with"],
      ["tooth", "TOOTH", "one of the hard white parts in the mouth"],
      ["tongue", "TUNG", "the soft part in the mouth used for tasting"],
      ["neck", "NEK", "the part joining the head to the body"],
      ["shoulder", "SHOHL-der", "the joint at the top of the arm"],
      ["arm", "ARM", "the limb from shoulder to hand"],
      ["hand", "HAND", "the part at the end of the arm"],
      ["finger", "FING-ger", "one of the five parts of the hand"],
      ["leg", "LEG", "the limb you stand on"],
      ["foot", "FUUT", "the part at the end of the leg"],
      ["knee", "NEE", "the joint in the middle of the leg"],
      ["back", "BAK", "the rear part of the body"],
      ["chest", "CHEST", "the front of the upper body"],
      ["heart", "HART", "the organ that pumps blood"],
      ["stomach", "STUM-uk", "the organ that digests food"],
      ["blood", "BLUD", "the red liquid in the body"],
      ["bone", "BOHN", "one of the hard parts of the skeleton"],
      ["skin", "SKIN", "the outer covering of the body"],
      ["brain", "BRAYN", "the organ you think with"],
    ]),
    V("health", [
      ["health", "HELTH", "the condition of your body"],
      ["doctor", "DOK-ter", "a person trained to treat illness"],
      ["hospital", "HOS-pi-tal", "a place where sick people are treated"],
      ["pharmacy", "FAR-muh-see", "a shop that sells medicine"],
      ["medicine", "MED-sin", "a substance that treats illness"],
      ["ill", "IL", "not healthy"],
      ["healthy", "HELTH-ee", "in good physical condition"],
      ["pain", "PAYN", "an unpleasant physical feeling"],
      ["fever", "FEE-ver", "a body temperature that is too high"],
      ["cough", "KOF", "to push air from the throat noisily"],
      ["cold", "KOHLD", "a common illness of the nose and throat"],
      ["wound", "WOOND", "an injury that breaks the skin"],
      ["nurse", "NURS", "a person who cares for the sick"],
      ["appointment", "uh-POYNT-ment", "an arranged time to meet"],
      ["hurt", "HURT", "to cause or feel pain"],
      ["ambulance", "AM-byuu-lans", "a vehicle that carries the sick"],
      ["emergency", "i-MUR-jen-see", "a sudden dangerous situation"],
      ["rest", "REST", "to stop working and relax"],
      ["exercise", "EK-ser-syz", "physical activity to stay fit"],
      ["diet", "DY-et", "the food a person usually eats"],
      ["prescription", "pri-SKRIP-shun", "a doctor's written order for medicine"],
      ["recover", "ri-KUV-er", "to become well again"],
      ["treatment", "TREET-ment", "medical care given to a patient"],
    ]),
    V("clothing", [
      ["clothes", "KLOHZ", "the things you wear"],
      ["shirt", "SHURT", "a garment for the upper body with a collar"],
      ["t-shirt", "TEE-shurt", "a simple cotton top with short sleeves"],
      ["trousers", "TROW-zerz", "a garment covering both legs"],
      ["jeans", "JEENZ", "trousers made of strong blue cotton"],
      ["dress", "DRES", "a one-piece garment worn by women"],
      ["skirt", "SKURT", "a garment hanging from the waist"],
      ["coat", "KOHT", "an outer garment for cold weather"],
      ["jacket", "JAK-it", "a short coat"],
      ["sweater", "SWET-er", "a warm knitted top"],
      ["shoes", "SHOOZ", "coverings for the feet"],
      ["boots", "BOOTS", "shoes that cover the ankle"],
      ["socks", "SOKS", "soft coverings worn inside shoes"],
      ["hat", "HAT", "a covering for the head"],
      ["scarf", "SKARF", "a strip of cloth worn round the neck"],
      ["gloves", "GLUVZ", "coverings for the hands"],
      ["belt", "BELT", "a strip worn around the waist"],
      ["glasses", "GLAS-iz", "lenses worn to help you see"],
      ["bag", "BAG", "a container you carry things in"],
      ["suit", "SOOT", "a matching jacket and trousers"],
      ["size", "SYZ", "how big or small something is"],
      ["wear", "WAIR", "to have clothes on your body"],
      ["fit", "FIT", "to be the right size"],
      ["pocket", "POK-it", "a small bag sewn into clothing"],
    ]),
    V("home", [
      ["house", "HOWS", "a building people live in"],
      ["home", "HOHM", "the place where you live"],
      ["flat", "FLAT", "a set of rooms on one floor"],
      ["room", "ROOM", "a divided space inside a building"],
      ["kitchen", "KICH-en", "the room where food is cooked"],
      ["bathroom", "BATH-room", "the room with a bath or shower"],
      ["bedroom", "BED-room", "the room where you sleep"],
      ["living room", "LIV-ing room", "the room where you relax"],
      ["door", "DOR", "the movable barrier you go through"],
      ["window", "WIN-doh", "the glass opening in a wall"],
      ["table", "TAY-bel", "furniture with a flat top and legs"],
      ["chair", "CHAIR", "a seat for one person"],
      ["bed", "BED", "furniture you sleep on"],
      ["sofa", "SOH-fuh", "a long soft seat for several people"],
      ["lamp", "LAMP", "a device that gives light"],
      ["mirror", "MIR-er", "glass that reflects your image"],
      ["key", "KEE", "a small metal object that opens a lock"],
      ["plate", "PLAYT", "a flat dish for food"],
      ["glass", "GLAS", "a container you drink from"],
      ["cup", "KUP", "a small container with a handle"],
      ["knife", "NYF", "a tool with a blade for cutting"],
      ["fork", "FORK", "an eating tool with points"],
      ["spoon", "SPOON", "a rounded eating tool"],
      ["garden", "GAR-den", "the ground around a house for plants"],
      ["stairs", "STAIRZ", "steps going up between floors"],
      ["roof", "ROOF", "the covering on top of a building"],
      ["wall", "WAWL", "an upright side of a room"],
      ["floor", "FLOR", "the surface you walk on indoors"],
      ["furniture", "FUR-ni-cher", "the movable objects in a room"],
    ]),
    V("animals", [
      ["animal", "AN-i-mal", "a living creature that is not a plant"],
      ["dog", "DOG", "a common pet that barks"],
      ["cat", "KAT", "a small pet that purrs"],
      ["horse", "HORS", "a large animal people ride"],
      ["cow", "KOW", "a farm animal kept for milk"],
      ["pig", "PIG", "a fat farm animal with a flat nose"],
      ["sheep", "SHEEP", "a farm animal kept for wool"],
      ["bird", "BURD", "an animal with feathers and wings"],
      ["fish", "FISH", "an animal that breathes underwater"],
      ["mouse", "MOWS", "a very small animal with a long tail"],
      ["rabbit", "RAB-it", "a small animal with long ears"],
      ["lion", "LY-un", "a large wild cat of Africa"],
      ["tiger", "TY-ger", "a large striped wild cat"],
      ["elephant", "EL-i-fant", "the largest land animal"],
      ["monkey", "MUNG-kee", "a climbing animal with a long tail"],
      ["bear", "BAIR", "a large heavy wild animal with thick fur"],
      ["wolf", "WUULF", "a wild animal like a large dog"],
      ["snake", "SNAYK", "a long reptile with no legs"],
      ["spider", "SPY-der", "a small creature with eight legs"],
      ["butterfly", "BUT-er-fly", "an insect with large coloured wings"],
      ["bee", "BEE", "an insect that makes honey"],
      ["ant", "ANT", "a tiny insect that lives in groups"],
      ["fly", "FLY", "a small insect with two wings"],
      ["insect", "IN-sekt", "a small creature with six legs"],
      ["pet", "PET", "an animal kept at home"],
    ]),
    V("nature", [
      ["nature", "NAY-cher", "the physical world, not made by people"],
      ["sun", "SUN", "the star that lights the day"],
      ["moon", "MOON", "the object that shines at night"],
      ["star", "STAR", "a point of light in the night sky"],
      ["sky", "SKY", "the space above the earth"],
      ["cloud", "KLOWD", "a mass of water vapour in the sky"],
      ["rain", "RAYN", "water falling from clouds"],
      ["snow", "SNOH", "soft white ice falling from the sky"],
      ["wind", "WIND", "air moving quickly"],
      ["fire", "FY-er", "the flame and heat of something burning"],
      ["earth", "URTH", "the planet we live on, or soil"],
      ["sea", "SEE", "a large area of salt water"],
      ["river", "RIV-er", "water flowing across land"],
      ["lake", "LAYK", "a large area of water surrounded by land"],
      ["mountain", "MOWN-tin", "a very high area of land"],
      ["forest", "FOR-ist", "a large area covered with trees"],
      ["tree", "TREE", "a tall plant with a wooden trunk"],
      ["flower", "FLOW-er", "the coloured part of a plant"],
      ["leaf", "LEEF", "the flat green part of a plant"],
      ["grass", "GRAS", "the green plant that covers fields"],
      ["beach", "BEECH", "the sandy edge of the sea"],
      ["island", "EYE-land", "land surrounded by water"],
      ["desert", "DEZ-ert", "a dry area with little rain"],
      ["stone", "STOHN", "a small piece of rock"],
      ["weather", "WETH-er", "the state of the air outside"],
      ["storm", "STORM", "violent weather with wind and rain"],
    ]),
    V("places", [
      ["place", "PLAYS", "a particular position or area"],
      ["city", "SIT-ee", "a large town"],
      ["town", "TOWN", "a place with houses and shops"],
      ["village", "VIL-ij", "a small group of houses in the country"],
      ["country", "KUN-tree", "a nation with its own government"],
      ["street", "STREET", "a road with buildings along it"],
      ["square", "SKWAIR", "an open public space in a town"],
      ["market", "MAR-kit", "a place where goods are sold"],
      ["shop", "SHOP", "a place that sells things"],
      ["bank", "BANK", "a place that keeps your money"],
      ["school", "SKOOL", "a place where children learn"],
      ["church", "CHURCH", "a building for Christian worship"],
      ["museum", "myoo-ZEE-um", "a building showing objects of interest"],
      ["park", "PARK", "a public green space in a town"],
      ["hotel", "hoh-TEL", "a building where travellers stay"],
      ["airport", "AIR-port", "a place where aircraft land"],
      ["station", "STAY-shun", "a place where trains stop"],
      ["library", "LY-brer-ee", "a place where books are kept"],
      ["office", "OF-is", "a room or building where people work"],
      ["cinema", "SIN-uh-muh", "a place where films are shown"],
      ["centre", "SEN-ter", "the middle part of a place"],
      ["countryside", "KUN-tree-syd", "land away from towns"],
      ["border", "BOR-der", "the line between two countries"],
      ["bakery", "BAY-ker-ee", "a shop that sells bread"],
    ]),
    V("travel", [
      ["journey", "JUR-nee", "an act of travelling from place to place"],
      ["travel", "TRAV-el", "to go from one place to another"],
      ["car", "KAR", "a road vehicle for a few people"],
      ["bus", "BUS", "a large road vehicle for many people"],
      ["train", "TRAYN", "a line of carriages pulled on rails"],
      ["plane", "PLAYN", "a vehicle that flies"],
      ["bicycle", "BY-si-kel", "a two-wheeled vehicle you pedal"],
      ["boat", "BOHT", "a small vessel that travels on water"],
      ["taxi", "TAK-see", "a car you pay to ride in"],
      ["ticket", "TIK-it", "a paper showing you have paid"],
      ["passport", "PAS-port", "a document allowing foreign travel"],
      ["suitcase", "SOOT-kays", "a case for carrying clothes"],
      ["luggage", "LUG-ij", "the bags a traveller carries"],
      ["map", "MAP", "a drawing showing where places are"],
      ["road", "ROHD", "a hard surface for vehicles"],
      ["way", "WAY", "the route to a place"],
      ["departure", "di-PAR-cher", "the act of leaving"],
      ["arrival", "uh-RY-val", "the act of reaching a place"],
      ["delay", "di-LAY", "a period of waiting past the set time"],
      ["left", "LEFT", "the side opposite the right"],
      ["right", "RYT", "the side opposite the left"],
      ["straight on", "strayt ON", "continuing without turning"],
      ["lost", "LOST", "not knowing where you are"],
      ["customs", "KUS-tumz", "the place where bags are checked at a border"],
      ["holiday", "HOL-i-day", "time away from work for rest"],
    ]),
    V("time", [
      ["time", "TYM", "what is measured in hours and minutes"],
      ["hour", "OWR", "a period of sixty minutes"],
      ["minute", "MIN-it", "a period of sixty seconds"],
      ["second", "SEK-und", "the shortest common unit of time"],
      ["day", "DAY", "a period of twenty-four hours"],
      ["week", "WEEK", "a period of seven days"],
      ["month", "MUNTH", "one of the twelve parts of a year"],
      ["year", "YEER", "a period of twelve months"],
      ["morning", "MOR-ning", "the early part of the day"],
      ["afternoon", "af-ter-NOON", "the time between noon and evening"],
      ["evening", "EEV-ning", "the end of the day before night"],
      ["night", "NYT", "the dark hours"],
      ["Monday", "MUN-day", "the first day of the working week"],
      ["Tuesday", "TYOOZ-day", "the day after Monday"],
      ["Wednesday", "WENZ-day", "the middle day of the working week"],
      ["Thursday", "THURZ-day", "the day before Friday"],
      ["Friday", "FRY-day", "the last day of the working week"],
      ["Saturday", "SAT-er-day", "the first day of the weekend"],
      ["Sunday", "SUN-day", "the day of rest"],
      ["January", "JAN-yoo-er-ee", "the first month"],
      ["February", "FEB-roo-er-ee", "the second month"],
      ["March", "MARCH", "the third month"],
      ["April", "AY-pril", "the fourth month"],
      ["weekend", "WEEK-end", "Saturday and Sunday"],
      ["clock", "KLOK", "a device showing the time"],
      ["summer", "SUM-er", "the warmest season"],
      ["winter", "WIN-ter", "the coldest season"],
      ["future", "FYOO-cher", "the time still to come"],
      ["past", "PAST", "the time that has gone"],
    ]),
    V("work", [
      ["work", "WURK", "activity done to earn a living"],
      ["job", "JOB", "paid regular employment"],
      ["company", "KUM-puh-nee", "a business organisation"],
      ["boss", "BOS", "the person in charge"],
      ["employee", "im-PLOY-ee", "a person who works for a company"],
      ["salary", "SAL-uh-ree", "money paid regularly for work"],
      ["money", "MUN-ee", "coins and notes used to buy things"],
      ["price", "PRYS", "the amount something costs"],
      ["pay", "PAY", "to give money for something"],
      ["meeting", "MEE-ting", "an arranged gathering to discuss things"],
      ["project", "PROJ-ekt", "a planned piece of work"],
      ["client", "KLY-ent", "a person who buys a service"],
      ["invoice", "IN-voys", "a document requesting payment"],
      ["contract", "KON-trakt", "a formal written agreement"],
      ["card", "KARD", "a plastic card used to pay"],
      ["cash", "KASH", "money in the form of notes and coins"],
      ["engineer", "en-ji-NEER", "a person who designs or builds things"],
      ["teacher", "TEE-cher", "a person who teaches"],
      ["lawyer", "LOY-er", "a person trained in the law"],
      ["nurse", "NURS", "a person who cares for patients"],
      ["earn", "URN", "to receive money for work"],
      ["discount", "DIS-kownt", "a reduction in price"],
      ["tax", "TAKS", "money paid to the government"],
      ["career", "kuh-REER", "a person's working life"],
    ]),
    V("school", [
      ["school", "SKOOL", "a place where children are taught"],
      ["university", "yoo-ni-VUR-si-tee", "a place of higher education"],
      ["class", "KLAS", "a group taught together, or a lesson"],
      ["pupil", "PYOO-pil", "a child at school"],
      ["student", "STYOO-dent", "a person who studies"],
      ["teacher", "TEE-cher", "a person who gives lessons"],
      ["book", "BUUK", "printed pages bound together"],
      ["notebook", "NOHT-buuk", "a book of blank pages for writing"],
      ["pencil", "PEN-sil", "a wooden tool for writing"],
      ["pen", "PEN", "an ink tool for writing"],
      ["paper", "PAY-per", "thin material used for writing"],
      ["word", "WURD", "a single unit of language"],
      ["sentence", "SEN-tens", "a group of words expressing a thought"],
      ["lesson", "LES-un", "a period of teaching"],
      ["exam", "ig-ZAM", "a formal test of knowledge"],
      ["homework", "HOHM-wurk", "school work done at home"],
      ["grade", "GRAYD", "a mark showing quality of work"],
      ["learn", "LURN", "to gain knowledge or skill"],
      ["teach", "TEECH", "to help someone learn"],
      ["understand", "un-der-STAND", "to know the meaning of"],
      ["explain", "ik-SPLAYN", "to make something clear"],
      ["language", "LANG-gwij", "the words a people use"],
      ["history", "HIS-tuh-ree", "the study of past events"],
      ["mathematics", "math-uh-MAT-iks", "the study of numbers"],
      ["science", "SY-ens", "the study of the physical world"],
      ["knowledge", "NOL-ij", "what a person knows"],
    ]),
    V("tech", [
      ["computer", "kum-PYOO-ter", "a machine that processes data"],
      ["phone", "FOHN", "a device for speaking to people far away"],
      ["screen", "SKREEN", "the flat surface that shows an image"],
      ["keyboard", "KEE-bord", "the set of keys you type on"],
      ["mouse", "MOWS", "a device you move to point on screen"],
      ["internet", "IN-ter-net", "the global network of computers"],
      ["network", "NET-wurk", "computers connected together"],
      ["email", "EE-mayl", "a message sent electronically"],
      ["password", "PAS-wurd", "a secret word that gives access"],
      ["file", "FYL", "a named collection of data"],
      ["folder", "FOHL-der", "a place that holds files"],
      ["app", "AP", "a program on a phone or computer"],
      ["software", "SOFT-wair", "the programs a computer runs"],
      ["download", "DOWN-lohd", "to copy data to your device"],
      ["upload", "UP-lohd", "to send data from your device"],
      ["save", "SAYV", "to store your work"],
      ["delete", "di-LEET", "to remove permanently"],
      ["search", "SURCH", "to look for information"],
      ["switch on", "swich ON", "to make a device start"],
      ["switch off", "swich OF", "to make a device stop"],
      ["camera", "KAM-ruh", "a device that takes pictures"],
      ["battery", "BAT-uh-ree", "the part that stores power"],
      ["link", "LINK", "a clickable address to another page"],
      ["data", "DAY-tuh", "information stored by a computer"],
      ["update", "UP-dayt", "a newer version of software"],
    ]),
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["Hello, how are you?", "huh-LOH how ar YOO", "A friendly greeting and question",
        [["Hello", "huh-LOH"], ["how", "how"], ["are", "ar"], ["you", "YOO"]]],
      ["I am very well, thank you", "y am ver-ee WEL thank yoo", "A polite positive reply",
        [["I", "y"], ["am", "am"], ["very", "VER-ee"], ["well", "WEL"], ["thank", "thank"], ["you", "yoo"]]],
      ["What is your name?", "wot iz yor NAYM", "Asking someone's name",
        [["What", "wot"], ["is", "iz"], ["your", "yor"], ["name", "NAYM"]]],
      ["My name is Sam", "my naym iz SAM", "Telling someone your name",
        [["My", "my"], ["name", "naym"], ["is", "iz"], ["Sam", "SAM"]]],
      ["I don't understand", "y dohnt un-der-STAND", "Saying the meaning is unclear to you",
        [["I", "y"], ["don't", "dohnt"], ["understand", "un-der-STAND"]]],
      ["Could you repeat that, please?", "kuud yoo ri-PEET that pleez",
        "Politely asking to hear something again",
        [["Could", "kuud"], ["you", "yoo"], ["repeat", "ri-PEET"], ["that", "that"], ["please", "pleez"]]],
      ["Nice to meet you", "nys tuh MEET yoo", "A greeting when meeting for the first time",
        [["Nice", "nys"], ["to", "tuh"], ["meet", "MEET"], ["you", "yoo"]]],
      ["Where are you from?", "wair ar yoo FROM", "Asking about someone's home country",
        [["Where", "wair"], ["are", "ar"], ["you", "yoo"], ["from", "FROM"]]],
    ]),
    S("food", [
      ["I would like a coffee, please", "y wuud lyk uh KOF-ee pleez",
        "A polite way to order a drink",
        [["I", "y"], ["would", "wuud"], ["like", "lyk"], ["a", "uh"], ["coffee", "KOF-ee"], ["please", "pleez"]]],
      ["I am hungry", "y am HUNG-gree", "Saying that you want to eat",
        [["I", "y"], ["am", "am"], ["hungry", "HUNG-gree"]]],
      ["I am thirsty", "y am THURS-tee", "Saying that you want to drink",
        [["I", "y"], ["am", "am"], ["thirsty", "THURS-tee"]]],
      ["The food is delicious", "thuh food iz di-LISH-us", "Praising a meal",
        [["The", "thuh"], ["food", "food"], ["is", "iz"], ["delicious", "di-LISH-us"]]],
      ["Could we have the bill?", "kuud wee hav thuh BIL", "Asking to pay in a restaurant",
        [["Could", "kuud"], ["we", "wee"], ["have", "hav"], ["the", "thuh"], ["bill", "BIL"]]],
      ["I don't eat meat", "y dohnt eet MEET", "Explaining that you are vegetarian",
        [["I", "y"], ["don't", "dohnt"], ["eat", "eet"], ["meat", "MEET"]]],
    ]),
    S("travel", [
      ["Where is the station?", "wair iz thuh STAY-shun", "Asking for directions to the trains",
        [["Where", "wair"], ["is", "iz"], ["the", "thuh"], ["station", "STAY-shun"]]],
      ["I would like a ticket to London", "y wuud lyk uh TIK-it tuh LUN-dun",
        "Buying travel to a city",
        [["I", "y"], ["would", "wuud"], ["like", "lyk"], ["a", "uh"], ["ticket", "TIK-it"], ["to", "tuh"], ["London", "LUN-dun"]]],
      ["The train arrives at eight", "thuh trayn uh-RYVZ at AYT", "Stating an arrival time",
        [["The", "thuh"], ["train", "trayn"], ["arrives", "uh-RYVZ"], ["at", "at"], ["eight", "AYT"]]],
      ["I am lost", "y am LOST", "Saying you don't know where you are",
        [["I", "y"], ["am", "am"], ["lost", "LOST"]]],
      ["Turn right at the corner", "turn RYT at thuh KOR-ner", "Giving a direction",
        [["Turn", "turn"], ["right", "RYT"], ["at", "at"], ["the", "thuh"], ["corner", "KOR-ner"]]],
    ]),
    S("home", [
      ["I live in a small house", "y liv in uh smawl HOWS", "Describing where you live",
        [["I", "y"], ["live", "liv"], ["in", "in"], ["a", "uh"], ["small", "smawl"], ["house", "HOWS"]]],
      ["The door is open", "thuh dor iz OH-pen", "Saying a door is not shut",
        [["The", "thuh"], ["door", "dor"], ["is", "iz"], ["open", "OH-pen"]]],
      ["My family is big", "my FAM-uh-lee iz BIG", "Describing a large family",
        [["My", "my"], ["family", "FAM-uh-lee"], ["is", "iz"], ["big", "BIG"]]],
    ]),
    S("time", [
      ["What time is it?", "wot tym iz IT", "Asking for the time",
        [["What", "wot"], ["time", "tym"], ["is", "iz"], ["it", "IT"]]],
      ["Today is Monday", "tuh-DAY iz MUN-day", "Naming the day of the week",
        [["Today", "tuh-DAY"], ["is", "iz"], ["Monday", "MUN-day"]]],
      ["Tomorrow I go to the market", "tuh-MOR-oh y goh tuh thuh MAR-kit",
        "Describing a plan for the next day",
        [["Tomorrow", "tuh-MOR-oh"], ["I", "y"], ["go", "goh"], ["to", "tuh"], ["the", "thuh"], ["market", "MAR-kit"]]],
      ["I always work in the morning", "y AWL-wayz wurk in thuh MOR-ning",
        "Describing a daily habit",
        [["I", "y"], ["always", "AWL-wayz"], ["work", "wurk"], ["in", "in"], ["the", "thuh"], ["morning", "MOR-ning"]]],
    ]),
    S("school", [
      ["I study English every day", "y STUD-ee ING-glish EV-ree day", "Describing a study habit",
        [["I", "y"], ["study", "STUD-ee"], ["English", "ING-glish"], ["every", "EV-ree"], ["day", "day"]]],
      ["The book is very interesting", "thuh buuk iz ver-ee IN-tres-ting", "Praising a book",
        [["The", "thuh"], ["book", "buuk"], ["is", "iz"], ["very", "ver-ee"], ["interesting", "IN-tres-ting"]]],
      ["Can you help me?", "kan yoo HELP mee", "Asking someone for assistance",
        [["Can", "kan"], ["you", "yoo"], ["help", "HELP"], ["me", "mee"]]],
    ]),
    S("health", [
      ["I have a headache", "y hav uh HED-ayk", "Saying your head hurts",
        [["I", "y"], ["have", "hav"], ["a", "uh"], ["headache", "HED-ayk"]]],
      ["I need a doctor", "y need uh DOK-ter", "Asking for medical help",
        [["I", "y"], ["need", "need"], ["a", "uh"], ["doctor", "DOK-ter"]]],
      ["I don't feel well", "y dohnt feel WEL", "Saying you feel unwell",
        [["I", "y"], ["don't", "dohnt"], ["feel", "feel"], ["well", "WEL"]]],
    ]),
    S("work", [
      ["How much does this cost?", "how much duz this KOST", "Asking a price",
        [["How", "how"], ["much", "much"], ["does", "duz"], ["this", "this"], ["cost", "KOST"]]],
      ["It is too expensive", "it iz too ik-SPEN-siv", "Saying the price is too high",
        [["It", "it"], ["is", "iz"], ["too", "too"], ["expensive", "ik-SPEN-siv"]]],
      ["I work in an office", "y wurk in an OF-is", "Describing where you work",
        [["I", "y"], ["work", "wurk"], ["in", "in"], ["an", "an"], ["office", "OF-is"]]],
    ]),
  );

  /* ----------------------------- Conjugation ------------------------------
   * English verbs change little, so what a learner really needs is the
   * irregular past and the third-person -s. Each table walks one verb through
   * past, present and the "will" future. */
  const CONJUGATION = [
    C("be", "BEE", "be", [
      ["I was", "y WOZ", "I was", "I", "past"],
      ["you were", "yoo WUR", "you were", "you", "past"],
      ["he was", "hee WOZ", "he was", "he", "past"],
      ["she was", "shee WOZ", "she was", "she", "past"],
      ["we were", "wee WUR", "we were", "we", "past"],
      ["they were", "thay WUR", "they were", "they", "past"],
      ["I am", "y AM", "I am", "I", "present"],
      ["you are", "yoo AR", "you are", "you", "present"],
      ["he is", "hee IZ", "he is", "he", "present"],
      ["she is", "shee IZ", "she is", "she", "present"],
      ["we are", "wee AR", "we are", "we", "present"],
      ["they are", "thay AR", "they are", "they", "present"],
      ["I will be", "y wil BEE", "I will be", "I", "future"],
      ["you will be", "yoo wil BEE", "you will be", "you", "future"],
      ["he will be", "hee wil BEE", "he will be", "he", "future"],
      ["we will be", "wee wil BEE", "we will be", "we", "future"],
      ["they will be", "thay wil BEE", "they will be", "they", "future"],
    ]),
    C("have", "HAV", "have", [
      ["I had", "y HAD", "I had", "I", "past"],
      ["you had", "yoo HAD", "you had", "you", "past"],
      ["he had", "hee HAD", "he had", "he", "past"],
      ["we had", "wee HAD", "we had", "we", "past"],
      ["they had", "thay HAD", "they had", "they", "past"],
      ["I have", "y HAV", "I have", "I", "present"],
      ["you have", "yoo HAV", "you have", "you", "present"],
      ["he has", "hee HAZ", "he has", "he", "present"],
      ["we have", "wee HAV", "we have", "we", "present"],
      ["they have", "thay HAV", "they have", "they", "present"],
      ["I will have", "y wil HAV", "I will have", "I", "future"],
      ["you will have", "yoo wil HAV", "you will have", "you", "future"],
      ["he will have", "hee wil HAV", "he will have", "he", "future"],
      ["we will have", "wee wil HAV", "we will have", "we", "future"],
      ["they will have", "thay wil HAV", "they will have", "they", "future"],
    ]),
    C("go", "GOH", "go", [
      ["I went", "y WENT", "I went", "I", "past"],
      ["you went", "yoo WENT", "you went", "you", "past"],
      ["he went", "hee WENT", "he went", "he", "past"],
      ["we went", "wee WENT", "we went", "we", "past"],
      ["they went", "thay WENT", "they went", "they", "past"],
      ["I go", "y GOH", "I go", "I", "present"],
      ["you go", "yoo GOH", "you go", "you", "present"],
      ["he goes", "hee GOHZ", "he goes", "he", "present"],
      ["we go", "wee GOH", "we go", "we", "present"],
      ["they go", "thay GOH", "they go", "they", "present"],
      ["I will go", "y wil GOH", "I will go", "I", "future"],
      ["you will go", "yoo wil GOH", "you will go", "you", "future"],
      ["he will go", "hee wil GOH", "he will go", "he", "future"],
      ["we will go", "wee wil GOH", "we will go", "we", "future"],
      ["they will go", "thay wil GOH", "they will go", "they", "future"],
    ]),
    C("do", "DOO", "do", [
      ["I did", "y DID", "I did", "I", "past"],
      ["you did", "yoo DID", "you did", "you", "past"],
      ["he did", "hee DID", "he did", "he", "past"],
      ["we did", "wee DID", "we did", "we", "past"],
      ["they did", "thay DID", "they did", "they", "past"],
      ["I do", "y DOO", "I do", "I", "present"],
      ["you do", "yoo DOO", "you do", "you", "present"],
      ["he does", "hee DUZ", "he does", "he", "present"],
      ["we do", "wee DOO", "we do", "we", "present"],
      ["they do", "thay DOO", "they do", "they", "present"],
      ["I will do", "y wil DOO", "I will do", "I", "future"],
      ["you will do", "yoo wil DOO", "you will do", "you", "future"],
      ["he will do", "hee wil DOO", "he will do", "he", "future"],
      ["we will do", "wee wil DOO", "we will do", "we", "future"],
      ["they will do", "thay wil DOO", "they will do", "they", "future"],
    ]),
    C("eat", "EET", "eat", [
      ["I ate", "y AYT", "I ate", "I", "past"],
      ["you ate", "yoo AYT", "you ate", "you", "past"],
      ["he ate", "hee AYT", "he ate", "he", "past"],
      ["we ate", "wee AYT", "we ate", "we", "past"],
      ["they ate", "thay AYT", "they ate", "they", "past"],
      ["I eat", "y EET", "I eat", "I", "present"],
      ["you eat", "yoo EET", "you eat", "you", "present"],
      ["he eats", "hee EETS", "he eats", "he", "present"],
      ["we eat", "wee EET", "we eat", "we", "present"],
      ["they eat", "thay EET", "they eat", "they", "present"],
      ["I will eat", "y wil EET", "I will eat", "I", "future"],
      ["you will eat", "yoo wil EET", "you will eat", "you", "future"],
      ["he will eat", "hee wil EET", "he will eat", "he", "future"],
      ["we will eat", "wee wil EET", "we will eat", "we", "future"],
      ["they will eat", "thay wil EET", "they will eat", "they", "future"],
    ]),
    C("speak", "SPEEK", "speak", [
      ["I spoke", "y SPOHK", "I spoke", "I", "past"],
      ["you spoke", "yoo SPOHK", "you spoke", "you", "past"],
      ["he spoke", "hee SPOHK", "he spoke", "he", "past"],
      ["we spoke", "wee SPOHK", "we spoke", "we", "past"],
      ["they spoke", "thay SPOHK", "they spoke", "they", "past"],
      ["I speak", "y SPEEK", "I speak", "I", "present"],
      ["you speak", "yoo SPEEK", "you speak", "you", "present"],
      ["he speaks", "hee SPEEKS", "he speaks", "he", "present"],
      ["we speak", "wee SPEEK", "we speak", "we", "present"],
      ["they speak", "thay SPEEK", "they speak", "they", "present"],
      ["I will speak", "y wil SPEEK", "I will speak", "I", "future"],
      ["you will speak", "yoo wil SPEEK", "you will speak", "you", "future"],
      ["he will speak", "hee wil SPEEK", "he will speak", "he", "future"],
      ["we will speak", "wee wil SPEEK", "we will speak", "we", "future"],
      ["they will speak", "thay wil SPEEK", "they will speak", "they", "future"],
    ]),
    C("see", "SEE", "see", [
      ["I saw", "y SAW", "I saw", "I", "past"],
      ["you saw", "yoo SAW", "you saw", "you", "past"],
      ["he saw", "hee SAW", "he saw", "he", "past"],
      ["we saw", "wee SAW", "we saw", "we", "past"],
      ["they saw", "thay SAW", "they saw", "they", "past"],
      ["I see", "y SEE", "I see", "I", "present"],
      ["you see", "yoo SEE", "you see", "you", "present"],
      ["he sees", "hee SEEZ", "he sees", "he", "present"],
      ["we see", "wee SEE", "we see", "we", "present"],
      ["they see", "thay SEE", "they see", "they", "present"],
      ["I will see", "y wil SEE", "I will see", "I", "future"],
      ["you will see", "yoo wil SEE", "you will see", "you", "future"],
      ["he will see", "hee wil SEE", "he will see", "he", "future"],
      ["we will see", "wee wil SEE", "we will see", "we", "future"],
      ["they will see", "thay wil SEE", "they will see", "they", "future"],
    ]),
    C("take", "TAYK", "take", [
      ["I took", "y TUUK", "I took", "I", "past"],
      ["you took", "yoo TUUK", "you took", "you", "past"],
      ["he took", "hee TUUK", "he took", "he", "past"],
      ["we took", "wee TUUK", "we took", "we", "past"],
      ["they took", "thay TUUK", "they took", "they", "past"],
      ["I take", "y TAYK", "I take", "I", "present"],
      ["you take", "yoo TAYK", "you take", "you", "present"],
      ["he takes", "hee TAYKS", "he takes", "he", "present"],
      ["we take", "wee TAYK", "we take", "we", "present"],
      ["they take", "thay TAYK", "they take", "they", "present"],
      ["I will take", "y wil TAYK", "I will take", "I", "future"],
      ["you will take", "yoo wil TAYK", "you will take", "you", "future"],
      ["he will take", "hee wil TAYK", "he will take", "he", "future"],
      ["we will take", "wee wil TAYK", "we will take", "we", "future"],
      ["they will take", "thay wil TAYK", "they will take", "they", "future"],
    ]),
    C("work", "WURK", "work", [
      ["I worked", "y WURKT", "I worked", "I", "past"],
      ["you worked", "yoo WURKT", "you worked", "you", "past"],
      ["he worked", "hee WURKT", "he worked", "he", "past"],
      ["we worked", "wee WURKT", "we worked", "we", "past"],
      ["they worked", "thay WURKT", "they worked", "they", "past"],
      ["I work", "y WURK", "I work", "I", "present"],
      ["you work", "yoo WURK", "you work", "you", "present"],
      ["he works", "hee WURKS", "he works", "he", "present"],
      ["we work", "wee WURK", "we work", "we", "present"],
      ["they work", "thay WURK", "they work", "they", "present"],
      ["I will work", "y wil WURK", "I will work", "I", "future"],
      ["you will work", "yoo wil WURK", "you will work", "you", "future"],
      ["he will work", "hee wil WURK", "he will work", "he", "future"],
      ["we will work", "wee wil WURK", "we will work", "we", "future"],
      ["they will work", "thay wil WURK", "they will work", "they", "future"],
    ]),
    C("write", "RYT", "write", [
      ["I wrote", "y ROHT", "I wrote", "I", "past"],
      ["you wrote", "yoo ROHT", "you wrote", "you", "past"],
      ["he wrote", "hee ROHT", "he wrote", "he", "past"],
      ["we wrote", "wee ROHT", "we wrote", "we", "past"],
      ["they wrote", "thay ROHT", "they wrote", "they", "past"],
      ["I write", "y RYT", "I write", "I", "present"],
      ["you write", "yoo RYT", "you write", "you", "present"],
      ["he writes", "hee RYTS", "he writes", "he", "present"],
      ["we write", "wee RYT", "we write", "we", "present"],
      ["they write", "thay RYT", "they write", "they", "present"],
      ["I will write", "y wil RYT", "I will write", "I", "future"],
      ["you will write", "yoo wil RYT", "you will write", "you", "future"],
      ["he will write", "hee wil RYT", "he will write", "he", "future"],
      ["we will write", "wee wil RYT", "we will write", "we", "future"],
      ["they will write", "thay wil RYT", "they will write", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Practice",
      l1: "Practice", l2: "makes perfect.",
      tr1: "PRAK-tis", tr2: "mayks PUR-fikt",
      en: "Doing something often is what makes you good at it." },
    { n: 2, chapterEn: "Timing",
      l1: "The early bird", l2: "catches the worm.",
      tr1: "thuh UR-lee BURD", tr2: "KACH-iz thuh WURM",
      en: "Those who act first get the best chances." },
    { n: 3, chapterEn: "Appearances",
      l1: "All that glitters", l2: "is not gold.",
      tr1: "awl that GLIT-erz", tr2: "iz not GOHLD",
      en: "Attractive things are not always valuable." },
    { n: 4, chapterEn: "Prudence",
      l1: "Don't count your chickens", l2: "before they hatch.",
      tr1: "dohnt kownt yor CHIK-enz", tr2: "bi-FOR thay HACH",
      en: "Don't rely on something before it has actually happened." },
    { n: 5, chapterEn: "Effort",
      l1: "Where there's a will,", l2: "there's a way.",
      tr1: "wair thairz uh WIL", tr2: "thairz uh WAY",
      en: "If you truly want something, you will find a means to it." },
    { n: 6, chapterEn: "Company",
      l1: "Birds of a feather", l2: "flock together.",
      tr1: "burdz uv uh FETH-er", tr2: "flok tuh-GETH-er",
      en: "Similar people tend to spend time with each other." },
    { n: 7, chapterEn: "Patience",
      l1: "Rome", l2: "wasn't built in a day.",
      tr1: "ROHM", tr2: "WUZ-ent bilt in uh DAY",
      en: "Important things take a long time to finish." },
    { n: 8, chapterEn: "Prudence",
      l1: "Don't judge a book", l2: "by its cover.",
      tr1: "dohnt juj uh BUUK", tr2: "by its KUV-er",
      en: "Don't decide what something is worth from its appearance." },
    { n: 9, chapterEn: "Hope",
      l1: "Every cloud", l2: "has a silver lining.",
      tr1: "EV-ree KLOWD", tr2: "haz uh SIL-ver LY-ning",
      en: "There is something good in every difficult situation." },
    { n: 10, chapterEn: "Adaptation",
      l1: "When in Rome,", l2: "do as the Romans do.",
      tr1: "wen in ROHM", tr2: "doo az thuh ROH-manz DOO",
      en: "Follow the customs of the place you are in." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("english", {
    icons: {
      alphabet: "Alphabet", greetings: "Greetings", numbers: "Numbers", colors: "Colours",
      family: "Family", people: "People", pronouns: "Pronouns", questions: "Questions",
      grammar: "Linking", adjectives: "Adjectives", adverbs: "Adverbs", verbs: "Verbs",
      food: "Food", body: "Body", health: "Health", clothing: "Clothes", home: "Home",
      animals: "Animals", nature: "Nature", places: "Places", travel: "Travel",
      time: "Time", work: "Work", school: "School", tech: "Tech", sentences: "Sentences",
    },
    ui: { account: "Account", progress: "Progress", search: "Search" },
    alphabet: ALPHABET,
    alphabetTitle: "Alphabet & sounds",
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "Review", vocab: "Words", sentence: "Sentences", conjugation: "Verbs",
      listening: "Listening", mixed: "Mixed", reading: "Sayings",
    },
    reading: {
      id: "sayings", title: "Proverbs", native: "Sayings",
      desc: "Classic English proverbs, line by line",
      blurb: "Proverbs — fixed sayings that carry a whole idea in a handful of words.",
      unit: "sayings", numLabel: "Saying",
      lineQuestion: "Which line completes this saying?",
      items: PROVERBS,
    },
  });
})();
