/* ============================================================================
 * French course — data only.
 *
 * `ta` is the French, `tr` a plain-English respelling (French stresses the
 * last syllable lightly, so the respelling marks vowel quality rather than
 * stress; "ñ" in the respelling means a nasal vowel), `en` the meaning.
 * Nouns carry their article so the gender is learned with the word.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------ Alphabet ------------------------------- */
  const LETTERS = A([
    ["A a", "ah"], ["B b", "bay"], ["C c", "say"], ["D d", "day"], ["E e", "uh"],
    ["F f", "eff"], ["G g", "zhay"], ["H h", "ash"], ["I i", "ee"], ["J j", "zhee"],
    ["K k", "kah"], ["L l", "ell"], ["M m", "emm"], ["N n", "enn"], ["O o", "oh"],
    ["P p", "pay"], ["Q q", "koo"], ["R r", "air"], ["S s", "ess"], ["T t", "tay"],
    ["U u", "oo"], ["V v", "vay"], ["W w", "doo-bluh-vay"], ["X x", "eeks"],
    ["Y y", "ee-grek"], ["Z z", "zed"],
  ]);
  const SOUNDS = A([
    ["é", "ay", "closed e — as in 'café'"], ["è", "eh", "open e — as in 'père'"],
    ["ê", "eh", "open e with circumflex"], ["ç", "suh say-dee-y", "c said as 's'"],
    ["ou", "oo", "as in 'you'"], ["oi", "wah", "as in 'moi'"],
    ["au / eau", "oh", "as in 'eau'"], ["ai", "eh", "as in 'mais'"],
    ["eu", "uh", "as in 'deux'"], ["an / en", "añ", "nasal a"],
    ["on", "oñ", "nasal o"], ["in / ain", "añ (thin)", "nasal i"],
    ["un", "uñ", "nasal u"], ["gn", "ny", "as in 'montagne'"],
    ["ille", "eey", "as in 'famille'"], ["r", "hr", "in the throat"],
    ["h", "(silent)", "never pronounced"],
    ["-ent", "(silent)", "verb ending, not said"],
  ]);
  const ALPHABET = { vowels: LETTERS, consonants: SOUNDS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["bonjour", "boñ-ZHOOR", "hello / good morning"],
      ["salut", "sah-LOO", "hi / bye (informal)"],
      ["bonsoir", "boñ-SWAHR", "good evening"],
      ["bonne nuit", "bun NWEE", "good night"],
      ["au revoir", "oh ruh-VWAHR", "goodbye"],
      ["merci", "mair-SEE", "thank you"],
      ["merci beaucoup", "mair-SEE boh-KOO", "thank you very much"],
      ["de rien", "duh RYAÑ", "you're welcome"],
      ["s'il vous plaît", "seel voo PLEH", "please (formal)"],
      ["s'il te plaît", "seel tuh PLEH", "please (informal)"],
      ["oui", "WEE", "yes"], ["non", "NOÑ", "no"],
      ["pardon", "par-DOÑ", "sorry / excuse me"],
      ["excusez-moi", "eks-koo-zay MWAH", "excuse me"],
      ["je suis désolé", "zhuh swee day-zoh-LAY", "I am sorry"],
      ["comment allez-vous ?", "koh-moñ tah-lay VOO", "how are you? (formal)"],
      ["ça va ?", "sah VAH", "how's it going?"],
      ["ça va bien", "sah vah BYAÑ", "I'm well"],
      ["enchanté", "oñ-shoñ-TAY", "pleased to meet you"],
      ["bienvenue", "byañ-vuh-NOO", "welcome"],
      ["à bientôt", "ah byañ-TOH", "see you soon"],
      ["à demain", "ah duh-MAÑ", "see you tomorrow"],
      ["bon appétit", "boñ nah-pay-TEE", "enjoy your meal"],
      ["santé", "soñ-TAY", "cheers"],
      ["félicitations", "fay-lee-see-tah-SYOÑ", "congratulations"],
      ["bonne chance", "bun SHOÑS", "good luck"],
      ["d'accord", "dah-KOR", "okay / agreed"],
    ]),
    V("numbers", [
      ["zéro", "zay-ROH", "zero"], ["un", "UÑ", "one"], ["deux", "DUH", "two"],
      ["trois", "TRWAH", "three"], ["quatre", "KAT-ruh", "four"],
      ["cinq", "SAÑK", "five"], ["six", "SEES", "six"], ["sept", "SET", "seven"],
      ["huit", "WEET", "eight"], ["neuf", "NUHF", "nine"], ["dix", "DEES", "ten"],
      ["onze", "OÑZ", "eleven"], ["douze", "DOOZ", "twelve"],
      ["treize", "TREZ", "thirteen"], ["quatorze", "kah-TORZ", "fourteen"],
      ["quinze", "KAÑZ", "fifteen"], ["seize", "SEZ", "sixteen"],
      ["dix-sept", "dees-SET", "seventeen"], ["vingt", "VAÑ", "twenty"],
      ["trente", "TROÑT", "thirty"], ["quarante", "kah-ROÑT", "forty"],
      ["cinquante", "sañ-KOÑT", "fifty"], ["soixante", "swah-SOÑT", "sixty"],
      ["cent", "SOÑ", "one hundred"], ["mille", "MEEL", "one thousand"],
      ["premier", "pruh-MYAY", "first"], ["deuxième", "duh-ZYEM", "second"],
      ["dernier", "dair-NYAY", "last"], ["la moitié", "lah mwah-TYAY", "half"],
      ["le nombre", "luh NOÑ-bruh", "number"],
    ]),
    V("colors", [
      ["rouge", "ROOZH", "red"], ["bleu", "BLUH", "blue"], ["vert", "VAIR", "green"],
      ["jaune", "ZHOHN", "yellow"], ["noir", "NWAHR", "black"], ["blanc", "BLOÑ", "white"],
      ["gris", "GREE", "grey"], ["marron", "mah-ROÑ", "brown"],
      ["orange", "oh-ROÑZH", "orange"], ["rose", "ROHZ", "pink"],
      ["violet", "vyoh-LEH", "purple"], ["doré", "doh-RAY", "golden"],
      ["argenté", "ar-zhoñ-TAY", "silver"], ["clair", "KLAIR", "light (colour)"],
      ["foncé", "foñ-SAY", "dark"], ["la couleur", "lah koo-LUHR", "colour"],
      ["coloré", "koh-loh-RAY", "colourful"], ["beige", "BEZH", "beige"],
      ["turquoise", "toor-KWAHZ", "turquoise"], ["brillant", "bree-YOÑ", "bright / shiny"],
      ["pâle", "PAHL", "pale"], ["bleu ciel", "bluh SYEL", "sky blue"],
    ]),
    V("family", [
      ["la famille", "lah fah-MEEY", "family"], ["la mère", "lah MAIR", "mother"],
      ["le père", "luh PAIR", "father"], ["maman", "mah-MOÑ", "mum"],
      ["papa", "pah-PAH", "dad"], ["les parents", "lay pah-ROÑ", "parents"],
      ["le fils", "luh FEES", "son"], ["la fille", "lah FEEY", "daughter / girl"],
      ["le frère", "luh FRAIR", "brother"], ["la sœur", "lah SUHR", "sister"],
      ["le grand-père", "luh groñ-PAIR", "grandfather"],
      ["la grand-mère", "lah groñ-MAIR", "grandmother"],
      ["le petit-fils", "luh puh-tee-FEES", "grandson"],
      ["l'oncle", "LOÑ-kluh", "uncle"], ["la tante", "lah TOÑT", "aunt"],
      ["le cousin", "luh koo-ZAÑ", "cousin (m)"], ["le neveu", "luh nuh-VUH", "nephew"],
      ["la nièce", "lah NYES", "niece"], ["le mari", "luh mah-REE", "husband"],
      ["la femme", "lah FAHM", "wife / woman"], ["le bébé", "luh bay-BAY", "baby"],
      ["l'enfant", "loñ-FOÑ", "child"], ["le parent", "luh pah-ROÑ", "relative"],
      ["le mariage", "luh mah-RYAZH", "wedding"],
      ["le beau-père", "luh boh-PAIR", "father-in-law / stepfather"],
    ]),
    V("people", [
      ["la personne", "lah pair-SUN", "person"], ["les gens", "lay ZHOÑ", "people"],
      ["l'homme", "LUM", "man"], ["la femme", "lah FAHM", "woman"],
      ["le garçon", "luh gar-SOÑ", "boy"], ["la fille", "lah FEEY", "girl"],
      ["l'ami", "lah-MEE", "friend (m)"], ["l'amie", "lah-MEE", "friend (f)"],
      ["le voisin", "luh vwah-ZAÑ", "neighbour"], ["monsieur", "muh-SYUH", "sir / Mr"],
      ["madame", "mah-DAHM", "madam / Mrs"], ["le jeune", "luh ZHUHN", "young person"],
      ["l'adulte", "lah-DOOLT", "adult"], ["le vieillard", "luh vyay-YAHR", "old man"],
      ["l'invité", "lañ-vee-TAY", "guest"], ["l'étranger", "lay-troñ-ZHAY", "foreigner"],
      ["le petit ami", "luh puh-tee tah-MEE", "boyfriend"],
      ["la petite amie", "lah puh-teet ah-MEE", "girlfriend"],
      ["l'équipe", "lay-KEEP", "team"], ["le groupe", "luh GROOP", "group"],
      ["le nom", "luh NOÑ", "name / surname"], ["le prénom", "luh pray-NOÑ", "first name"],
      ["le collègue", "luh koh-LEG", "colleague"],
    ]),
    V("pronouns", [
      ["je", "ZHUH", "I"], ["tu", "TOO", "you (informal)"], ["vous", "VOO", "you (formal / plural)"],
      ["il", "EEL", "he / it"], ["elle", "EL", "she / it"], ["nous", "NOO", "we"],
      ["ils", "EEL", "they (m)"], ["elles", "EL", "they (f)"],
      ["on", "OÑ", "one / we (colloquial)"], ["me", "MUH", "me"], ["te", "TUH", "you (object)"],
      ["le", "LUH", "him / it"], ["la", "LAH", "her / it"], ["lui", "LWEE", "to him / her"],
      ["leur", "LUHR", "to them"], ["mon", "MOÑ", "my (m)"], ["ma", "MAH", "my (f)"],
      ["ton", "TOÑ", "your (m)"], ["son", "SOÑ", "his / her (m)"],
      ["notre", "NOH-truh", "our"], ["votre", "VOH-truh", "your (formal)"],
      ["ce", "SUH", "this / that"], ["cela", "suh-LAH", "that"],
      ["quelqu'un", "kel-KUÑ", "someone"], ["personne", "pair-SUN", "nobody"],
      ["tout le monde", "too luh MOÑD", "everyone"], ["y", "EE", "there (pronoun)"],
    ]),
    V("questions", [
      ["quoi ?", "KWAH", "what?"], ["qu'est-ce que ?", "kess-KUH", "what is it that?"],
      ["qui ?", "KEE", "who?"], ["où ?", "OO", "where?"], ["quand ?", "KOÑ", "when?"],
      ["pourquoi ?", "poor-KWAH", "why?"], ["comment ?", "koh-MOÑ", "how?"],
      ["quel ?", "KEL", "which? (m)"], ["quelle ?", "KEL", "which? (f)"],
      ["combien ?", "koñ-BYAÑ", "how much / how many?"],
      ["d'où ?", "DOO", "where from?"], ["à qui ?", "ah KEE", "to whom / whose?"],
      ["n'est-ce pas ?", "ness-PAH", "isn't it?"],
      ["la question", "lah kess-TYOÑ", "question"],
      ["la réponse", "lah ray-POÑS", "answer"], ["demander", "duh-moñ-DAY", "to ask"],
      ["répondre", "ray-POÑ-druh", "to answer"],
      ["combien ça coûte ?", "koñ-byañ sah KOOT", "how much does it cost?"],
      ["quelle heure est-il ?", "kel UHR ay-TEEL", "what time is it?"],
      ["qu'est-ce qui se passe ?", "kess-kee suh PAHS", "what's happening?"],
    ]),
    V("grammar", [
      ["et", "AY", "and"], ["ou", "OO", "or"], ["mais", "MEH", "but"],
      ["parce que", "pars-KUH", "because"], ["si", "SEE", "if"], ["que", "KUH", "that (conj.)"],
      ["de", "DUH", "of / from"], ["à", "AH", "to / at"], ["dans", "DOÑ", "in"],
      ["sur", "SOOR", "on"], ["sous", "SOO", "under"], ["avec", "ah-VEK", "with"],
      ["sans", "SOÑ", "without"], ["pour", "POOR", "for"], ["par", "PAR", "by"],
      ["chez", "SHAY", "at the home of"], ["entre", "OÑ-truh", "between"],
      ["depuis", "duh-PWEE", "since"], ["jusqu'à", "zhoos-KAH", "until"],
      ["le", "LUH", "the (m)"], ["la", "LAH", "the (f)"], ["les", "LAY", "the (pl)"],
      ["un", "UÑ", "a (m)"], ["une", "OON", "a (f)"], ["du", "DOO", "some (m)"],
      ["aussi", "oh-SEE", "also"], ["donc", "DOÑK", "so / therefore"],
      ["alors", "ah-LOR", "then"], ["ne … pas", "nuh … PAH", "not"],
    ]),
    V("adjectives", [
      ["grand", "GROÑ", "big / tall"], ["petit", "puh-TEE", "small"],
      ["bon", "BOÑ", "good"], ["mauvais", "moh-VEH", "bad"],
      ["nouveau", "noo-VOH", "new"], ["vieux", "VYUH", "old"],
      ["jeune", "ZHUHN", "young"], ["long", "LOÑ", "long"], ["court", "KOOR", "short"],
      ["haut", "OH", "high"], ["bas", "BAH", "low"], ["chaud", "SHOH", "hot"],
      ["froid", "FRWAH", "cold"], ["facile", "fah-SEEL", "easy"],
      ["difficile", "dee-fee-SEEL", "difficult"], ["beau", "BOH", "beautiful"],
      ["joli", "zhoh-LEE", "pretty"], ["laid", "LEH", "ugly"], ["fort", "FOR", "strong"],
      ["faible", "FEH-bluh", "weak"], ["rapide", "rah-PEED", "fast"],
      ["lent", "LOÑ", "slow"], ["riche", "REESH", "rich"], ["pauvre", "POH-vruh", "poor"],
      ["heureux", "uh-RUH", "happy"], ["triste", "TREEST", "sad"],
      ["fatigué", "fah-tee-GAY", "tired"], ["propre", "PROH-pruh", "clean"],
      ["sale", "SAHL", "dirty"], ["plein", "PLAÑ", "full"], ["vide", "VEED", "empty"],
      ["cher", "SHAIR", "expensive / dear"], ["gentil", "zhoñ-TEE", "kind"],
    ]),
    V("adverbs", [
      ["très", "TREH", "very"], ["beaucoup", "boh-KOO", "a lot"], ["peu", "PUH", "little"],
      ["bien", "BYAÑ", "well"], ["mal", "MAHL", "badly"], ["toujours", "too-ZHOOR", "always"],
      ["jamais", "zhah-MEH", "never"], ["parfois", "par-FWAH", "sometimes"],
      ["souvent", "soo-VOÑ", "often"], ["maintenant", "mañt-NOÑ", "now"],
      ["aujourd'hui", "oh-zhoor-DWEE", "today"], ["hier", "YAIR", "yesterday"],
      ["demain", "duh-MAÑ", "tomorrow"], ["tôt", "TOH", "early"], ["tard", "TAR", "late"],
      ["ici", "ee-SEE", "here"], ["là", "LAH", "there"], ["près", "PREH", "near"],
      ["loin", "LWAÑ", "far"], ["ensemble", "oñ-SOÑ-bluh", "together"],
      ["seulement", "suhl-MOÑ", "only"], ["peut-être", "puh-TEH-truh", "maybe"],
      ["déjà", "day-ZHAH", "already"], ["encore", "oñ-KOR", "again / still"],
      ["lentement", "loñt-MOÑ", "slowly"], ["vite", "VEET", "quickly"],
      ["presque", "PRESK", "almost"], ["trop", "TROH", "too much"],
      ["vraiment", "vray-MOÑ", "really"],
    ]),
    V("verbs", [
      ["être", "EH-truh", "to be"], ["avoir", "ah-VWAHR", "to have"],
      ["faire", "FAIR", "to do / make"], ["aller", "ah-LAY", "to go"],
      ["venir", "vuh-NEER", "to come"], ["pouvoir", "poo-VWAHR", "to be able to"],
      ["vouloir", "voo-LWAHR", "to want"], ["devoir", "duh-VWAHR", "to have to"],
      ["savoir", "sah-VWAHR", "to know (facts)"], ["connaître", "koh-NEH-truh", "to know (people)"],
      ["dire", "DEER", "to say"], ["parler", "par-LAY", "to speak"],
      ["manger", "moñ-ZHAY", "to eat"], ["boire", "BWAHR", "to drink"],
      ["vivre", "VEE-vruh", "to live"], ["voir", "VWAHR", "to see"],
      ["regarder", "ruh-gar-DAY", "to watch"], ["écouter", "ay-koo-TAY", "to listen"],
      ["lire", "LEER", "to read"], ["écrire", "ay-KREER", "to write"],
      ["travailler", "trah-vah-YAY", "to work"], ["étudier", "ay-too-DYAY", "to study"],
      ["dormir", "dor-MEER", "to sleep"], ["acheter", "ash-TAY", "to buy"],
      ["vendre", "VOÑ-druh", "to sell"], ["ouvrir", "oo-VREER", "to open"],
      ["fermer", "fair-MAY", "to close"], ["commencer", "koh-moñ-SAY", "to begin"],
      ["finir", "fee-NEER", "to finish"], ["aider", "ay-DAY", "to help"],
      ["penser", "poñ-SAY", "to think"], ["marcher", "mar-SHAY", "to walk"],
      ["courir", "koo-REER", "to run"], ["attendre", "ah-TOÑ-druh", "to wait"],
      ["donner", "doh-NAY", "to give"], ["prendre", "PROÑ-druh", "to take"],
      ["arriver", "ah-ree-VAY", "to arrive"], ["partir", "par-TEER", "to leave"],
      ["aimer", "ay-MAY", "to like / love"],
    ]),
    V("food", [
      ["la nourriture", "lah noo-ree-TOOR", "food"], ["l'eau", "LOH", "water"],
      ["le pain", "luh PAÑ", "bread"], ["le riz", "luh REE", "rice"],
      ["la viande", "lah VYOÑD", "meat"], ["le poulet", "luh poo-LEH", "chicken"],
      ["le poisson", "luh pwah-SOÑ", "fish (food)"], ["l'œuf", "LUHF", "egg"],
      ["le lait", "luh LEH", "milk"], ["le fromage", "luh froh-MAZH", "cheese"],
      ["le beurre", "luh BUHR", "butter"], ["le fruit", "luh FRWEE", "fruit"],
      ["la pomme", "lah PUM", "apple"], ["la banane", "lah bah-NAHN", "banana"],
      ["l'orange", "loh-ROÑZH", "orange (fruit)"], ["le légume", "luh lay-GOOM", "vegetable"],
      ["la pomme de terre", "lah pum duh TAIR", "potato"],
      ["la tomate", "lah toh-MAHT", "tomato"], ["l'oignon", "loh-NYOÑ", "onion"],
      ["l'ail", "LYE", "garlic"], ["le sel", "luh SEL", "salt"],
      ["le poivre", "luh PWAH-vruh", "pepper"], ["le sucre", "luh SOO-kruh", "sugar"],
      ["l'huile", "LWEEL", "oil"], ["le café", "luh kah-FAY", "coffee"],
      ["le thé", "luh TAY", "tea"], ["le vin", "luh VAÑ", "wine"],
      ["la bière", "lah BYAIR", "beer"], ["le jus", "luh ZHOO", "juice"],
      ["la soupe", "lah SOOP", "soup"], ["la salade", "lah sah-LAHD", "salad"],
      ["le gâteau", "luh gah-TOH", "cake"], ["le dessert", "luh day-SAIR", "dessert"],
      ["le petit-déjeuner", "luh puh-tee day-zhuh-NAY", "breakfast"],
      ["le déjeuner", "luh day-zhuh-NAY", "lunch"], ["le dîner", "luh dee-NAY", "dinner"],
      ["le restaurant", "luh res-toh-ROÑ", "restaurant"],
      ["l'addition", "lah-dee-SYOÑ", "the bill"],
    ]),
    V("body", [
      ["le corps", "luh KOR", "body"], ["la tête", "lah TET", "head"],
      ["les cheveux", "lay shuh-VUH", "hair"], ["le visage", "luh vee-ZAZH", "face"],
      ["l'œil", "LUHY", "eye"], ["les yeux", "lay ZYUH", "eyes"],
      ["l'oreille", "loh-RAY", "ear"], ["le nez", "luh NAY", "nose"],
      ["la bouche", "lah BOOSH", "mouth"], ["la dent", "lah DOÑ", "tooth"],
      ["la langue", "lah LOÑG", "tongue / language"], ["le cou", "luh KOO", "neck"],
      ["l'épaule", "lay-POHL", "shoulder"], ["le bras", "luh BRAH", "arm"],
      ["la main", "lah MAÑ", "hand"], ["le doigt", "luh DWAH", "finger"],
      ["la jambe", "lah ZHOÑB", "leg"], ["le pied", "luh PYAY", "foot"],
      ["le genou", "luh zhuh-NOO", "knee"], ["le dos", "luh DOH", "back"],
      ["le cœur", "luh KUHR", "heart"], ["l'estomac", "les-toh-MAH", "stomach"],
      ["le sang", "luh SOÑ", "blood"], ["l'os", "LOSS", "bone"],
      ["la peau", "lah POH", "skin"],
    ]),
    V("health", [
      ["la santé", "lah soñ-TAY", "health"], ["le médecin", "luh mayd-SAÑ", "doctor"],
      ["l'hôpital", "loh-pee-TAHL", "hospital"], ["la pharmacie", "lah far-mah-SEE", "pharmacy"],
      ["le médicament", "luh may-dee-kah-MOÑ", "medicine"],
      ["malade", "mah-LAHD", "ill"], ["en bonne santé", "oñ bun soñ-TAY", "healthy"],
      ["la douleur", "lah doo-LUHR", "pain"], ["la fièvre", "lah FYEH-vruh", "fever"],
      ["la toux", "lah TOO", "cough"], ["le rhume", "luh ROOM", "a cold"],
      ["la blessure", "lah bleh-SOOR", "wound"],
      ["l'infirmière", "lañ-feer-MYAIR", "nurse"],
      ["le rendez-vous", "luh roñ-day-VOO", "appointment"],
      ["j'ai mal", "zhay MAHL", "it hurts / I'm in pain"],
      ["l'ambulance", "loñ-boo-LOÑS", "ambulance"],
      ["l'urgence", "loor-ZHOÑS", "emergency"], ["se reposer", "suh ruh-poh-ZAY", "to rest"],
      ["l'exercice", "leg-zair-SEES", "exercise"], ["le régime", "luh ray-ZHEEM", "diet"],
      ["l'ordonnance", "lor-doh-NOÑS", "prescription"],
      ["guérir", "gay-REER", "to heal / recover"],
    ]),
    V("clothing", [
      ["les vêtements", "lay vet-MOÑ", "clothes"], ["la chemise", "lah shuh-MEEZ", "shirt"],
      ["le t-shirt", "luh tee-SHUHRT", "t-shirt"], ["le pantalon", "luh poñ-tah-LOÑ", "trousers"],
      ["le jean", "luh DZHEEN", "jeans"], ["la robe", "lah ROHB", "dress"],
      ["la jupe", "lah ZHOOP", "skirt"], ["le manteau", "luh moñ-TOH", "coat"],
      ["la veste", "lah VEST", "jacket"], ["le pull", "luh POOL", "sweater"],
      ["les chaussures", "lay shoh-SOOR", "shoes"], ["les bottes", "lay BUT", "boots"],
      ["les chaussettes", "lay shoh-SET", "socks"], ["le chapeau", "luh shah-POH", "hat"],
      ["la casquette", "lah kas-KET", "cap"], ["l'écharpe", "lay-SHARP", "scarf"],
      ["les gants", "lay GOÑ", "gloves"], ["la ceinture", "lah sañ-TOOR", "belt"],
      ["les lunettes", "lay loo-NET", "glasses"], ["le sac", "luh SAK", "bag"],
      ["le costume", "luh kos-TOOM", "suit"], ["la taille", "lah TAHY", "size"],
      ["porter", "por-TAY", "to wear"], ["essayer", "ay-say-YAY", "to try on"],
    ]),
    V("home", [
      ["la maison", "lah may-ZOÑ", "house"], ["le chez-soi", "luh shay-SWAH", "home"],
      ["l'appartement", "lah-par-tuh-MOÑ", "apartment"],
      ["la pièce", "lah PYES", "room"], ["la cuisine", "lah kwee-ZEEN", "kitchen"],
      ["la salle de bains", "lah sahl duh BAÑ", "bathroom"],
      ["la chambre", "lah SHOÑ-bruh", "bedroom"], ["le salon", "luh sah-LOÑ", "living room"],
      ["la porte", "lah PORT", "door"], ["la fenêtre", "lah fuh-NEH-truh", "window"],
      ["la table", "lah TAH-bluh", "table"], ["la chaise", "lah SHEZ", "chair"],
      ["le lit", "luh LEE", "bed"], ["le canapé", "luh kah-nah-PAY", "sofa"],
      ["la lampe", "lah LOÑP", "lamp"], ["le miroir", "luh mee-RWAHR", "mirror"],
      ["la clé", "lah KLAY", "key"], ["l'assiette", "lah-SYET", "plate"],
      ["le verre", "luh VAIR", "glass"], ["la tasse", "lah TAHS", "cup"],
      ["le couteau", "luh koo-TOH", "knife"], ["la fourchette", "lah foor-SHET", "fork"],
      ["la cuillère", "lah kwee-YAIR", "spoon"], ["le jardin", "luh zhar-DAÑ", "garden"],
      ["l'escalier", "les-kah-LYAY", "stairs"], ["le toit", "luh TWAH", "roof"],
      ["le mur", "luh MOOR", "wall"], ["le sol", "luh SOL", "floor"],
    ]),
    V("animals", [
      ["l'animal", "lah-nee-MAHL", "animal"], ["le chien", "luh SHYAÑ", "dog"],
      ["le chat", "luh SHAH", "cat"], ["le cheval", "luh shuh-VAHL", "horse"],
      ["la vache", "lah VAHSH", "cow"], ["le cochon", "luh koh-SHOÑ", "pig"],
      ["le mouton", "luh moo-TOÑ", "sheep"], ["la poule", "lah POOL", "hen"],
      ["l'oiseau", "lwah-ZOH", "bird"], ["le poisson", "luh pwah-SOÑ", "fish"],
      ["la souris", "lah soo-REE", "mouse"], ["le lapin", "luh lah-PAÑ", "rabbit"],
      ["le lion", "luh LYOÑ", "lion"], ["le tigre", "luh TEE-gruh", "tiger"],
      ["l'éléphant", "lay-lay-FOÑ", "elephant"], ["le singe", "luh SAÑZH", "monkey"],
      ["l'ours", "LOORS", "bear"], ["le loup", "luh LOO", "wolf"],
      ["le serpent", "luh sair-POÑ", "snake"], ["l'araignée", "lah-ray-NYAY", "spider"],
      ["le papillon", "luh pah-pee-YOÑ", "butterfly"], ["l'abeille", "lah-BAY", "bee"],
      ["la fourmi", "lah foor-MEE", "ant"], ["la mouche", "lah MOOSH", "fly"],
      ["la tortue", "lah tor-TOO", "tortoise"],
    ]),
    V("nature", [
      ["la nature", "lah nah-TOOR", "nature"], ["le soleil", "luh soh-LAY", "sun"],
      ["la lune", "lah LOON", "moon"], ["l'étoile", "lay-TWAHL", "star"],
      ["le ciel", "luh SYEL", "sky"], ["le nuage", "luh noo-AZH", "cloud"],
      ["la pluie", "lah PLWEE", "rain"], ["la neige", "lah NEZH", "snow"],
      ["le vent", "luh VOÑ", "wind"], ["le feu", "luh FUH", "fire"],
      ["la terre", "lah TAIR", "earth"], ["la mer", "lah MAIR", "sea"],
      ["la rivière", "lah ree-VYAIR", "river"], ["le lac", "luh LAHK", "lake"],
      ["la montagne", "lah moñ-TAH-nyuh", "mountain"], ["la forêt", "lah foh-REH", "forest"],
      ["l'arbre", "LAR-bruh", "tree"], ["la fleur", "lah FLUHR", "flower"],
      ["la feuille", "lah FUHY", "leaf"], ["l'herbe", "LAIRB", "grass"],
      ["la plage", "lah PLAZH", "beach"], ["l'île", "LEEL", "island"],
      ["le désert", "luh day-ZAIR", "desert"], ["la pierre", "lah PYAIR", "stone"],
      ["le temps", "luh TOÑ", "weather / time"], ["l'orage", "loh-RAZH", "storm"],
    ]),
    V("places", [
      ["l'endroit", "loñ-DRWAH", "place"], ["la ville", "lah VEEL", "city / town"],
      ["le village", "luh vee-LAZH", "village"], ["le pays", "luh pay-EE", "country"],
      ["la rue", "lah ROO", "street"], ["la place", "lah PLAHS", "square"],
      ["le marché", "luh mar-SHAY", "market"], ["le magasin", "luh mah-gah-ZAÑ", "shop"],
      ["la banque", "lah BOÑK", "bank"], ["l'école", "lay-KOL", "school"],
      ["l'église", "lay-GLEEZ", "church"], ["le musée", "luh moo-ZAY", "museum"],
      ["le parc", "luh PARK", "park"], ["l'hôtel", "loh-TEL", "hotel"],
      ["l'aéroport", "lah-ay-roh-POR", "airport"], ["la gare", "lah GAR", "train station"],
      ["la bibliothèque", "lah bee-blee-oh-TEK", "library"],
      ["le bureau", "luh boo-ROH", "office / desk"], ["le cinéma", "luh see-nay-MAH", "cinema"],
      ["le quartier", "luh kar-TYAY", "neighbourhood"],
      ["le centre-ville", "luh soñ-truh-VEEL", "town centre"],
      ["la campagne", "lah koñ-PAH-nyuh", "countryside"],
      ["la frontière", "lah froñ-TYAIR", "border"], ["le café", "luh kah-FAY", "café"],
    ]),
    V("travel", [
      ["le voyage", "luh voh-YAZH", "journey"], ["voyager", "voh-yah-ZHAY", "to travel"],
      ["la voiture", "lah vwah-TOOR", "car"], ["le bus", "luh BOOS", "bus"],
      ["le train", "luh TRAÑ", "train"], ["l'avion", "lah-VYOÑ", "aeroplane"],
      ["le vélo", "luh vay-LOH", "bicycle"], ["le bateau", "luh bah-TOH", "boat"],
      ["le taxi", "luh tak-SEE", "taxi"], ["le métro", "luh may-TROH", "underground"],
      ["le billet", "luh bee-YEH", "ticket"], ["le passeport", "luh pas-POR", "passport"],
      ["la valise", "lah vah-LEEZ", "suitcase"], ["les bagages", "lay bah-GAZH", "luggage"],
      ["la carte", "lah KART", "map / card"], ["le chemin", "luh shuh-MAÑ", "way / path"],
      ["la route", "lah ROOT", "road"], ["le départ", "luh day-PAR", "departure"],
      ["l'arrivée", "lah-ree-VAY", "arrival"], ["le retard", "luh ruh-TAR", "delay"],
      ["à gauche", "ah GOHSH", "to the left"], ["à droite", "ah DRWAHT", "to the right"],
      ["tout droit", "too DRWAH", "straight ahead"],
      ["se perdre", "suh PAIR-druh", "to get lost"], ["la douane", "lah DWAHN", "customs"],
    ]),
    V("time", [
      ["le temps", "luh TOÑ", "time"], ["l'heure", "LUHR", "hour / o'clock"],
      ["la minute", "lah mee-NOOT", "minute"], ["la seconde", "lah suh-GOÑD", "second"],
      ["le jour", "luh ZHOOR", "day"], ["la semaine", "lah suh-MEN", "week"],
      ["le mois", "luh MWAH", "month"], ["l'année", "lah-NAY", "year"],
      ["le matin", "luh mah-TAÑ", "morning"], ["l'après-midi", "lah-preh-mee-DEE", "afternoon"],
      ["le soir", "luh SWAHR", "evening"], ["la nuit", "lah NWEE", "night"],
      ["lundi", "luñ-DEE", "Monday"], ["mardi", "mar-DEE", "Tuesday"],
      ["mercredi", "mair-kruh-DEE", "Wednesday"], ["jeudi", "zhuh-DEE", "Thursday"],
      ["vendredi", "voñ-druh-DEE", "Friday"], ["samedi", "sam-DEE", "Saturday"],
      ["dimanche", "dee-MOÑSH", "Sunday"], ["janvier", "zhoñ-VYAY", "January"],
      ["février", "fay-vree-YAY", "February"], ["mars", "MARS", "March"],
      ["avril", "ah-VREEL", "April"], ["mai", "MEH", "May"], ["juin", "ZHWAÑ", "June"],
      ["juillet", "zhwee-YEH", "July"], ["août", "OOT", "August"],
      ["le week-end", "luh week-END", "weekend"], ["la montre", "lah MOÑ-truh", "watch"],
      ["l'été", "lay-TAY", "summer"], ["l'hiver", "lee-VAIR", "winter"],
    ]),
    V("work", [
      ["le travail", "luh trah-VYE", "work"], ["l'emploi", "loñ-PLWAH", "job"],
      ["l'entreprise", "loñ-truh-PREEZ", "company"], ["le patron", "luh pah-TROÑ", "boss"],
      ["l'employé", "loñ-plwah-YAY", "employee"], ["le salaire", "luh sah-LAIR", "salary"],
      ["l'argent", "lar-ZHOÑ", "money"], ["l'euro", "luh-ROH", "euro"],
      ["le prix", "luh PREE", "price"], ["cher", "SHAIR", "expensive"],
      ["bon marché", "boñ mar-SHAY", "cheap"], ["payer", "pay-YAY", "to pay"],
      ["acheter", "ash-TAY", "to buy"], ["vendre", "VOÑ-druh", "to sell"],
      ["la réunion", "lah ray-oo-NYOÑ", "meeting"], ["le projet", "luh proh-ZHEH", "project"],
      ["le client", "luh klee-YOÑ", "client"], ["la facture", "lah fak-TOOR", "invoice"],
      ["le contrat", "luh koñ-TRAH", "contract"], ["la carte bancaire", "lah kart boñ-KAIR", "bank card"],
      ["les espèces", "lay zes-PES", "cash"], ["le métier", "luh may-TYAY", "trade / profession"],
      ["l'ingénieur", "lañ-zhay-NYUHR", "engineer"], ["l'avocat", "lah-voh-KAH", "lawyer"],
      ["gagner", "gah-NYAY", "to earn / win"],
    ]),
    V("school", [
      ["l'école", "lay-KOL", "school"], ["l'université", "loo-nee-vair-see-TAY", "university"],
      ["la classe", "lah KLAHS", "class"], ["l'élève", "lay-LEV", "pupil"],
      ["l'étudiant", "lay-too-DYOÑ", "student"], ["le professeur", "luh proh-feh-SUHR", "teacher"],
      ["le livre", "luh LEE-vruh", "book"], ["le cahier", "luh kah-YAY", "notebook"],
      ["le crayon", "luh kray-YOÑ", "pencil"], ["le stylo", "luh stee-LOH", "pen"],
      ["le papier", "luh pah-PYAY", "paper"], ["le mot", "luh MOH", "word"],
      ["la phrase", "lah FRAHZ", "sentence"], ["la leçon", "lah luh-SOÑ", "lesson"],
      ["l'examen", "leg-zah-MAÑ", "exam"], ["les devoirs", "lay duh-VWAHR", "homework"],
      ["la note", "lah NUT", "grade / note"], ["apprendre", "ah-PROÑ-druh", "to learn"],
      ["enseigner", "oñ-say-NYAY", "to teach"], ["comprendre", "koñ-PROÑ-druh", "to understand"],
      ["expliquer", "eks-plee-KAY", "to explain"], ["la réponse", "lah ray-POÑS", "answer"],
      ["la langue", "lah LOÑG", "language"], ["l'histoire", "lees-TWAHR", "history / story"],
      ["les mathématiques", "lay mah-tay-mah-TEEK", "maths"],
      ["la science", "lah SYOÑS", "science"],
    ]),
    V("tech", [
      ["l'ordinateur", "lor-dee-nah-TUHR", "computer"],
      ["le téléphone", "luh tay-lay-FUN", "telephone"],
      ["le portable", "luh por-TAH-bluh", "mobile / laptop"],
      ["l'écran", "lay-KROÑ", "screen"], ["le clavier", "luh klah-VYAY", "keyboard"],
      ["la souris", "lah soo-REE", "mouse"], ["internet", "añ-tair-NET", "internet"],
      ["le réseau", "luh ray-ZOH", "network"], ["le courriel", "luh koo-RYEL", "email"],
      ["le mot de passe", "luh moh duh PAHS", "password"],
      ["le fichier", "luh fee-SHYAY", "file"], ["le dossier", "luh doh-SYAY", "folder"],
      ["l'application", "lah-plee-kah-SYOÑ", "app"], ["le logiciel", "luh loh-zhee-SYEL", "software"],
      ["télécharger", "tay-lay-shar-ZHAY", "to download"],
      ["enregistrer", "oñ-ruh-zhees-TRAY", "to save"],
      ["supprimer", "soo-pree-MAY", "to delete"], ["chercher", "shair-SHAY", "to search"],
      ["allumer", "ah-loo-MAY", "to switch on"], ["éteindre", "ay-TAÑ-druh", "to switch off"],
      ["l'appareil photo", "lah-pah-ray FOH-toh", "camera"],
      ["la batterie", "lah bah-TREE", "battery"], ["le lien", "luh LYAÑ", "link"],
      ["le mot-clé", "luh moh-KLAY", "keyword"],
    ]),
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["Bonjour, comment allez-vous ?", "boñ-ZHOOR koh-moñ tah-lay VOO",
        "Hello, how are you?",
        [["Bonjour", "boñ-ZHOOR"], ["comment", "koh-MOÑ"], ["allez-vous", "ah-lay-VOO"]]],
      ["Je vais très bien, merci", "zhuh vay treh BYAÑ mair-SEE", "I am very well, thank you",
        [["Je", "zhuh"], ["vais", "vay"], ["très", "treh"], ["bien", "BYAÑ"], ["merci", "mair-SEE"]]],
      ["Comment vous appelez-vous ?", "koh-moñ voo zah-play VOO", "What is your name?",
        [["Comment", "koh-MOÑ"], ["vous", "voo"], ["appelez-vous", "ah-play-VOO"]]],
      ["Je m'appelle Marie", "zhuh mah-PEL mah-REE", "My name is Marie",
        [["Je", "zhuh"], ["m'appelle", "mah-PEL"], ["Marie", "mah-REE"]]],
      ["Je ne comprends pas", "zhuh nuh koñ-PROÑ pah", "I don't understand",
        [["Je", "zhuh"], ["ne", "nuh"], ["comprends", "koñ-PROÑ"], ["pas", "pah"]]],
      ["Pouvez-vous répéter, s'il vous plaît ?", "poo-vay voo ray-pay-TAY seel voo PLEH",
        "Can you repeat, please?",
        [["Pouvez-vous", "poo-vay-VOO"], ["répéter", "ray-pay-TAY"], ["s'il", "seel"], ["vous", "voo"], ["plaît", "PLEH"]]],
      ["Enchanté de vous rencontrer", "oñ-shoñ-TAY duh voo roñ-koñ-TRAY",
        "Pleased to meet you",
        [["Enchanté", "oñ-shoñ-TAY"], ["de", "duh"], ["vous", "voo"], ["rencontrer", "roñ-koñ-TRAY"]]],
      ["Parlez-vous anglais ?", "par-lay voo zoñ-GLEH", "Do you speak English?",
        [["Parlez-vous", "par-lay-VOO"], ["anglais", "oñ-GLEH"]]],
    ]),
    S("food", [
      ["Je voudrais un café, s'il vous plaît", "zhuh voo-DREH uñ kah-FAY seel voo PLEH",
        "I would like a coffee, please",
        [["Je", "zhuh"], ["voudrais", "voo-DREH"], ["un", "uñ"], ["café", "kah-FAY"], ["s'il", "seel"], ["vous", "voo"], ["plaît", "PLEH"]]],
      ["J'ai faim", "zhay FAÑ", "I am hungry", [["J'ai", "zhay"], ["faim", "FAÑ"]]],
      ["J'ai soif", "zhay SWAHF", "I am thirsty", [["J'ai", "zhay"], ["soif", "SWAHF"]]],
      ["Le repas est délicieux", "luh ruh-PAH ay day-lee-SYUH", "The meal is delicious",
        [["Le", "luh"], ["repas", "ruh-PAH"], ["est", "ay"], ["délicieux", "day-lee-SYUH"]]],
      ["L'addition, s'il vous plaît", "lah-dee-SYOÑ seel voo PLEH", "The bill, please",
        [["L'addition", "lah-dee-SYOÑ"], ["s'il", "seel"], ["vous", "voo"], ["plaît", "PLEH"]]],
      ["Je ne mange pas de viande", "zhuh nuh moñzh pah duh VYOÑD", "I don't eat meat",
        [["Je", "zhuh"], ["ne", "nuh"], ["mange", "MOÑZH"], ["pas", "pah"], ["de", "duh"], ["viande", "VYOÑD"]]],
    ]),
    S("travel", [
      ["Où est la gare ?", "oo ay lah GAR", "Where is the train station?",
        [["Où", "oo"], ["est", "ay"], ["la", "lah"], ["gare", "GAR"]]],
      ["Je voudrais un billet pour Paris", "zhuh voo-DREH uñ bee-YEH poor pah-REE",
        "I would like a ticket to Paris",
        [["Je", "zhuh"], ["voudrais", "voo-DREH"], ["un", "uñ"], ["billet", "bee-YEH"], ["pour", "poor"], ["Paris", "pah-REE"]]],
      ["Le train arrive à huit heures", "luh trañ ah-REEV ah wee TUHR",
        "The train arrives at eight",
        [["Le", "luh"], ["train", "TRAÑ"], ["arrive", "ah-REEV"], ["à", "ah"], ["huit", "weet"], ["heures", "UHR"]]],
      ["Je suis perdu", "zhuh swee pair-DOO", "I am lost",
        [["Je", "zhuh"], ["suis", "swee"], ["perdu", "pair-DOO"]]],
      ["Tournez à droite", "toor-NAY ah DRWAHT", "Turn right",
        [["Tournez", "toor-NAY"], ["à", "ah"], ["droite", "DRWAHT"]]],
    ]),
    S("home", [
      ["J'habite dans une petite maison", "zhah-BEET doñ zoon puh-TEET may-ZOÑ",
        "I live in a small house",
        [["J'habite", "zhah-BEET"], ["dans", "doñ"], ["une", "oon"], ["petite", "puh-TEET"], ["maison", "may-ZOÑ"]]],
      ["La porte est ouverte", "lah port ay too-VAIRT", "The door is open",
        [["La", "lah"], ["porte", "PORT"], ["est", "ay"], ["ouverte", "oo-VAIRT"]]],
      ["Ma famille est grande", "mah fah-MEEY ay GROÑD", "My family is big",
        [["Ma", "mah"], ["famille", "fah-MEEY"], ["est", "ay"], ["grande", "GROÑD"]]],
    ]),
    S("time", [
      ["Quelle heure est-il ?", "kel UHR ay-TEEL", "What time is it?",
        [["Quelle", "kel"], ["heure", "UHR"], ["est-il", "ay-TEEL"]]],
      ["Aujourd'hui, c'est lundi", "oh-zhoor-DWEE say luñ-DEE", "Today is Monday",
        [["Aujourd'hui", "oh-zhoor-DWEE"], ["c'est", "say"], ["lundi", "luñ-DEE"]]],
      ["Demain je vais au marché", "duh-MAÑ zhuh vay oh mar-SHAY",
        "Tomorrow I am going to the market",
        [["Demain", "duh-MAÑ"], ["je", "zhuh"], ["vais", "vay"], ["au", "oh"], ["marché", "mar-SHAY"]]],
      ["Je travaille toujours le matin", "zhuh trah-VYE too-ZHOOR luh mah-TAÑ",
        "I always work in the morning",
        [["Je", "zhuh"], ["travaille", "trah-VYE"], ["toujours", "too-ZHOOR"], ["le", "luh"], ["matin", "mah-TAÑ"]]],
    ]),
    S("school", [
      ["J'étudie le français tous les jours", "zhay-too-DEE luh froñ-SEH too lay ZHOOR",
        "I study French every day",
        [["J'étudie", "zhay-too-DEE"], ["le", "luh"], ["français", "froñ-SEH"], ["tous", "too"], ["les", "lay"], ["jours", "ZHOOR"]]],
      ["Le livre est très intéressant", "luh LEE-vruh ay treh zañ-tay-reh-SOÑ",
        "The book is very interesting",
        [["Le", "luh"], ["livre", "LEE-vruh"], ["est", "ay"], ["très", "treh"], ["intéressant", "añ-tay-reh-SOÑ"]]],
      ["Pouvez-vous m'aider ?", "poo-vay voo may-DAY", "Can you help me?",
        [["Pouvez-vous", "poo-vay-VOO"], ["m'aider", "may-DAY"]]],
    ]),
    S("health", [
      ["J'ai mal à la tête", "zhay mahl ah lah TET", "I have a headache",
        [["J'ai", "zhay"], ["mal", "mahl"], ["à", "ah"], ["la", "lah"], ["tête", "TET"]]],
      ["J'ai besoin d'un médecin", "zhay buh-ZWAÑ duñ mayd-SAÑ", "I need a doctor",
        [["J'ai", "zhay"], ["besoin", "buh-ZWAÑ"], ["d'un", "duñ"], ["médecin", "mayd-SAÑ"]]],
      ["Je ne me sens pas bien", "zhuh nuh muh soñ pah BYAÑ", "I don't feel well",
        [["Je", "zhuh"], ["ne", "nuh"], ["me", "muh"], ["sens", "soñ"], ["pas", "pah"], ["bien", "BYAÑ"]]],
    ]),
    S("work", [
      ["Combien ça coûte ?", "koñ-byañ sah KOOT", "How much does it cost?",
        [["Combien", "koñ-BYAÑ"], ["ça", "sah"], ["coûte", "KOOT"]]],
      ["C'est trop cher", "say troh SHAIR", "It is too expensive",
        [["C'est", "say"], ["trop", "troh"], ["cher", "SHAIR"]]],
      ["Je travaille dans un bureau", "zhuh trah-VYE doñ zuñ boo-ROH",
        "I work in an office",
        [["Je", "zhuh"], ["travaille", "trah-VYE"], ["dans", "doñ"], ["un", "uñ"], ["bureau", "boo-ROH"]]],
    ]),
  );

  /* ----------------------------- Conjugation ------------------------------
   * The three everyday tenses: passé composé (past), présent, futur simple. */
  const CONJUGATION = [
    C("être", "EH-truh", "be", [
      ["j'ai été", "zhay ay-TAY", "I was", "I", "past"],
      ["tu as été", "too ah ay-TAY", "you were", "you", "past"],
      ["il a été", "eel ah ay-TAY", "he was", "he", "past"],
      ["elle a été", "el ah ay-TAY", "she was", "she", "past"],
      ["nous avons été", "noo zah-VOÑ ay-TAY", "we were", "we", "past"],
      ["ils ont été", "eel zoñ ay-TAY", "they were", "they", "past"],
      ["je suis", "zhuh SWEE", "I am", "I", "present"],
      ["tu es", "too AY", "you are", "you", "present"],
      ["il est", "eel AY", "he is", "he", "present"],
      ["elle est", "el AY", "she is", "she", "present"],
      ["nous sommes", "noo SUM", "we are", "we", "present"],
      ["ils sont", "eel SOÑ", "they are", "they", "present"],
      ["je serai", "zhuh suh-RAY", "I will be", "I", "future"],
      ["tu seras", "too suh-RAH", "you will be", "you", "future"],
      ["il sera", "eel suh-RAH", "he will be", "he", "future"],
      ["nous serons", "noo suh-ROÑ", "we will be", "we", "future"],
      ["ils seront", "eel suh-ROÑ", "they will be", "they", "future"],
    ]),
    C("avoir", "ah-VWAHR", "have", [
      ["j'ai eu", "zhay OO", "I had", "I", "past"],
      ["tu as eu", "too ah OO", "you had", "you", "past"],
      ["il a eu", "eel ah OO", "he had", "he", "past"],
      ["nous avons eu", "noo zah-VOÑ OO", "we had", "we", "past"],
      ["ils ont eu", "eel zoñ OO", "they had", "they", "past"],
      ["j'ai", "ZHAY", "I have", "I", "present"],
      ["tu as", "too AH", "you have", "you", "present"],
      ["il a", "eel AH", "he has", "he", "present"],
      ["nous avons", "noo zah-VOÑ", "we have", "we", "present"],
      ["ils ont", "eel ZOÑ", "they have", "they", "present"],
      ["j'aurai", "zhoh-RAY", "I will have", "I", "future"],
      ["tu auras", "too oh-RAH", "you will have", "you", "future"],
      ["il aura", "eel oh-RAH", "he will have", "he", "future"],
      ["nous aurons", "noo zoh-ROÑ", "we will have", "we", "future"],
      ["ils auront", "eel zoh-ROÑ", "they will have", "they", "future"],
    ]),
    C("aller", "ah-LAY", "go", [
      ["je suis allé", "zhuh swee zah-LAY", "I went", "I", "past"],
      ["tu es allé", "too ay zah-LAY", "you went", "you", "past"],
      ["il est allé", "eel ay tah-LAY", "he went", "he", "past"],
      ["nous sommes allés", "noo sum zah-LAY", "we went", "we", "past"],
      ["ils sont allés", "eel soñ tah-LAY", "they went", "they", "past"],
      ["je vais", "zhuh VAY", "I go", "I", "present"],
      ["tu vas", "too VAH", "you go", "you", "present"],
      ["il va", "eel VAH", "he goes", "he", "present"],
      ["nous allons", "noo zah-LOÑ", "we go", "we", "present"],
      ["ils vont", "eel VOÑ", "they go", "they", "present"],
      ["j'irai", "zhee-RAY", "I will go", "I", "future"],
      ["tu iras", "too ee-RAH", "you will go", "you", "future"],
      ["il ira", "eel ee-RAH", "he will go", "he", "future"],
      ["nous irons", "noo zee-ROÑ", "we will go", "we", "future"],
      ["ils iront", "eel zee-ROÑ", "they will go", "they", "future"],
    ]),
    C("faire", "FAIR", "do / make", [
      ["j'ai fait", "zhay FEH", "I did", "I", "past"],
      ["tu as fait", "too ah FEH", "you did", "you", "past"],
      ["il a fait", "eel ah FEH", "he did", "he", "past"],
      ["nous avons fait", "noo zah-VOÑ FEH", "we did", "we", "past"],
      ["ils ont fait", "eel zoñ FEH", "they did", "they", "past"],
      ["je fais", "zhuh FEH", "I do", "I", "present"],
      ["tu fais", "too FEH", "you do", "you", "present"],
      ["il fait", "eel FEH", "he does", "he", "present"],
      ["nous faisons", "noo fuh-ZOÑ", "we do", "we", "present"],
      ["ils font", "eel FOÑ", "they do", "they", "present"],
      ["je ferai", "zhuh fuh-RAY", "I will do", "I", "future"],
      ["tu feras", "too fuh-RAH", "you will do", "you", "future"],
      ["il fera", "eel fuh-RAH", "he will do", "he", "future"],
      ["nous ferons", "noo fuh-ROÑ", "we will do", "we", "future"],
      ["ils feront", "eel fuh-ROÑ", "they will do", "they", "future"],
    ]),
    C("parler", "par-LAY", "speak", [
      ["j'ai parlé", "zhay par-LAY", "I spoke", "I", "past"],
      ["tu as parlé", "too ah par-LAY", "you spoke", "you", "past"],
      ["il a parlé", "eel ah par-LAY", "he spoke", "he", "past"],
      ["nous avons parlé", "noo zah-VOÑ par-LAY", "we spoke", "we", "past"],
      ["ils ont parlé", "eel zoñ par-LAY", "they spoke", "they", "past"],
      ["je parle", "zhuh PARL", "I speak", "I", "present"],
      ["tu parles", "too PARL", "you speak", "you", "present"],
      ["il parle", "eel PARL", "he speaks", "he", "present"],
      ["nous parlons", "noo par-LOÑ", "we speak", "we", "present"],
      ["ils parlent", "eel PARL", "they speak", "they", "present"],
      ["je parlerai", "zhuh par-luh-RAY", "I will speak", "I", "future"],
      ["tu parleras", "too par-luh-RAH", "you will speak", "you", "future"],
      ["il parlera", "eel par-luh-RAH", "he will speak", "he", "future"],
      ["nous parlerons", "noo par-luh-ROÑ", "we will speak", "we", "future"],
      ["ils parleront", "eel par-luh-ROÑ", "they will speak", "they", "future"],
    ]),
    C("manger", "moñ-ZHAY", "eat", [
      ["j'ai mangé", "zhay moñ-ZHAY", "I ate", "I", "past"],
      ["tu as mangé", "too ah moñ-ZHAY", "you ate", "you", "past"],
      ["il a mangé", "eel ah moñ-ZHAY", "he ate", "he", "past"],
      ["nous avons mangé", "noo zah-VOÑ moñ-ZHAY", "we ate", "we", "past"],
      ["ils ont mangé", "eel zoñ moñ-ZHAY", "they ate", "they", "past"],
      ["je mange", "zhuh MOÑZH", "I eat", "I", "present"],
      ["tu manges", "too MOÑZH", "you eat", "you", "present"],
      ["il mange", "eel MOÑZH", "he eats", "he", "present"],
      ["nous mangeons", "noo moñ-ZHOÑ", "we eat", "we", "present"],
      ["ils mangent", "eel MOÑZH", "they eat", "they", "present"],
      ["je mangerai", "zhuh moñzh-RAY", "I will eat", "I", "future"],
      ["tu mangeras", "too moñzh-RAH", "you will eat", "you", "future"],
      ["il mangera", "eel moñzh-RAH", "he will eat", "he", "future"],
      ["nous mangerons", "noo moñzh-ROÑ", "we will eat", "we", "future"],
      ["ils mangeront", "eel moñzh-ROÑ", "they will eat", "they", "future"],
    ]),
    C("finir", "fee-NEER", "finish", [
      ["j'ai fini", "zhay fee-NEE", "I finished", "I", "past"],
      ["tu as fini", "too ah fee-NEE", "you finished", "you", "past"],
      ["il a fini", "eel ah fee-NEE", "he finished", "he", "past"],
      ["nous avons fini", "noo zah-VOÑ fee-NEE", "we finished", "we", "past"],
      ["ils ont fini", "eel zoñ fee-NEE", "they finished", "they", "past"],
      ["je finis", "zhuh fee-NEE", "I finish", "I", "present"],
      ["tu finis", "too fee-NEE", "you finish", "you", "present"],
      ["il finit", "eel fee-NEE", "he finishes", "he", "present"],
      ["nous finissons", "noo fee-nee-SOÑ", "we finish", "we", "present"],
      ["ils finissent", "eel fee-NEES", "they finish", "they", "present"],
      ["je finirai", "zhuh fee-nee-RAY", "I will finish", "I", "future"],
      ["tu finiras", "too fee-nee-RAH", "you will finish", "you", "future"],
      ["il finira", "eel fee-nee-RAH", "he will finish", "he", "future"],
      ["nous finirons", "noo fee-nee-ROÑ", "we will finish", "we", "future"],
      ["ils finiront", "eel fee-nee-ROÑ", "they will finish", "they", "future"],
    ]),
    C("pouvoir", "poo-VWAHR", "be able to", [
      ["j'ai pu", "zhay POO", "I could", "I", "past"],
      ["tu as pu", "too ah POO", "you could", "you", "past"],
      ["il a pu", "eel ah POO", "he could", "he", "past"],
      ["nous avons pu", "noo zah-VOÑ POO", "we could", "we", "past"],
      ["ils ont pu", "eel zoñ POO", "they could", "they", "past"],
      ["je peux", "zhuh PUH", "I can", "I", "present"],
      ["tu peux", "too PUH", "you can", "you", "present"],
      ["il peut", "eel PUH", "he can", "he", "present"],
      ["nous pouvons", "noo poo-VOÑ", "we can", "we", "present"],
      ["ils peuvent", "eel PUHV", "they can", "they", "present"],
      ["je pourrai", "zhuh poo-RAY", "I will be able to", "I", "future"],
      ["tu pourras", "too poo-RAH", "you will be able to", "you", "future"],
      ["il pourra", "eel poo-RAH", "he will be able to", "he", "future"],
      ["nous pourrons", "noo poo-ROÑ", "we will be able to", "we", "future"],
      ["ils pourront", "eel poo-ROÑ", "they will be able to", "they", "future"],
    ]),
    C("vouloir", "voo-LWAHR", "want", [
      ["j'ai voulu", "zhay voo-LOO", "I wanted", "I", "past"],
      ["tu as voulu", "too ah voo-LOO", "you wanted", "you", "past"],
      ["il a voulu", "eel ah voo-LOO", "he wanted", "he", "past"],
      ["nous avons voulu", "noo zah-VOÑ voo-LOO", "we wanted", "we", "past"],
      ["ils ont voulu", "eel zoñ voo-LOO", "they wanted", "they", "past"],
      ["je veux", "zhuh VUH", "I want", "I", "present"],
      ["tu veux", "too VUH", "you want", "you", "present"],
      ["il veut", "eel VUH", "he wants", "he", "present"],
      ["nous voulons", "noo voo-LOÑ", "we want", "we", "present"],
      ["ils veulent", "eel VUHL", "they want", "they", "present"],
      ["je voudrai", "zhuh voo-DRAY", "I will want", "I", "future"],
      ["tu voudras", "too voo-DRAH", "you will want", "you", "future"],
      ["il voudra", "eel voo-DRAH", "he will want", "he", "future"],
      ["nous voudrons", "noo voo-DROÑ", "we will want", "we", "future"],
      ["ils voudront", "eel voo-DROÑ", "they will want", "they", "future"],
    ]),
    C("venir", "vuh-NEER", "come", [
      ["je suis venu", "zhuh swee vuh-NOO", "I came", "I", "past"],
      ["tu es venu", "too ay vuh-NOO", "you came", "you", "past"],
      ["il est venu", "eel ay vuh-NOO", "he came", "he", "past"],
      ["nous sommes venus", "noo sum vuh-NOO", "we came", "we", "past"],
      ["ils sont venus", "eel soñ vuh-NOO", "they came", "they", "past"],
      ["je viens", "zhuh VYAÑ", "I come", "I", "present"],
      ["tu viens", "too VYAÑ", "you come", "you", "present"],
      ["il vient", "eel VYAÑ", "he comes", "he", "present"],
      ["nous venons", "noo vuh-NOÑ", "we come", "we", "present"],
      ["ils viennent", "eel VYEN", "they come", "they", "present"],
      ["je viendrai", "zhuh vyañ-DRAY", "I will come", "I", "future"],
      ["tu viendras", "too vyañ-DRAH", "you will come", "you", "future"],
      ["il viendra", "eel vyañ-DRAH", "he will come", "he", "future"],
      ["nous viendrons", "noo vyañ-DROÑ", "we will come", "we", "future"],
      ["ils viendront", "eel vyañ-DROÑ", "they will come", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Patience",
      l1: "Petit à petit,", l2: "l'oiseau fait son nid.",
      tr1: "puh-TEE ah puh-TEE", tr2: "lwah-ZOH feh soñ NEE",
      en: "Little by little, the bird builds its nest." },
    { n: 2, chapterEn: "Effort",
      l1: "Vouloir,", l2: "c'est pouvoir.",
      tr1: "voo-LWAHR", tr2: "say poo-VWAHR",
      en: "To want to is to be able to — where there's a will there's a way." },
    { n: 3, chapterEn: "Appearances",
      l1: "L'habit ne fait pas", l2: "le moine.",
      tr1: "lah-BEE nuh feh PAH", tr2: "luh MWAHN",
      en: "The habit does not make the monk." },
    { n: 4, chapterEn: "Prudence",
      l1: "Il ne faut pas vendre la peau de l'ours", l2: "avant de l'avoir tué.",
      tr1: "eel nuh foh pah VOÑ-druh lah poh duh LOORS", tr2: "ah-VOÑ duh lah-VWAHR too-AY",
      en: "Don't sell the bear's skin before you've killed it." },
    { n: 5, chapterEn: "Time",
      l1: "Rien ne sert de courir,", l2: "il faut partir à point.",
      tr1: "ryañ nuh sair duh koo-REER", tr2: "eel foh par-TEER ah PWAÑ",
      en: "Running is no use; you have to set off on time." },
    { n: 6, chapterEn: "Appetite",
      l1: "L'appétit", l2: "vient en mangeant.",
      tr1: "lah-pay-TEE", tr2: "vyañ toñ moñ-ZHOÑ",
      en: "Appetite comes with eating." },
    { n: 7, chapterEn: "Friendship",
      l1: "Les bons comptes", l2: "font les bons amis.",
      tr1: "lay boñ KOÑT", tr2: "foñ lay boñ zah-MEE",
      en: "Good accounts make good friends." },
    { n: 8, chapterEn: "Caution",
      l1: "Chat échaudé", l2: "craint l'eau froide.",
      tr1: "shah tay-shoh-DAY", tr2: "krañ loh FRWAHD",
      en: "A scalded cat fears cold water." },
    { n: 9, chapterEn: "Company",
      l1: "Qui se ressemble", l2: "s'assemble.",
      tr1: "kee suh ruh-SOÑ-bluh", tr2: "sah-SOÑ-bluh",
      en: "Those who resemble each other gather together." },
    { n: 10, chapterEn: "Hope",
      l1: "Après la pluie,", l2: "le beau temps.",
      tr1: "ah-PREH lah PLWEE", tr2: "luh boh TOÑ",
      en: "After the rain, fine weather." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("french", {
    icons: {
      alphabet: "Alphabet", greetings: "Salutations", numbers: "Nombres", colors: "Couleurs",
      family: "Famille", people: "Gens", pronouns: "Pronoms", questions: "Questions",
      grammar: "Liens", adjectives: "Adjectifs", adverbs: "Adverbes",
      verbs: "Verbes", food: "Nourriture", body: "Corps", health: "Santé",
      clothing: "Vêtements", home: "Maison", animals: "Animaux", nature: "Nature",
      places: "Lieux", travel: "Voyages", time: "Temps", work: "Travail",
      school: "École", tech: "Technologie", sentences: "Phrases",
    },
    ui: { account: "Compte", progress: "Progrès", search: "Recherche" },
    alphabet: ALPHABET,
    alphabetTitle: "Alphabet & sounds",
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "Révision", vocab: "Mots", sentence: "Phrases", conjugation: "Verbes",
      listening: "Écoute", mixed: "Mélange", reading: "Proverbes",
    },
    reading: {
      id: "proverbes", title: "Proverbs", native: "Proverbes",
      desc: "Classic French sayings, line by line",
      blurb: "Proverbes — sayings that turn up in French conversation all the time.",
      unit: "sayings", numLabel: "Proverbe",
      lineQuestion: "Which line completes this proverb?",
      items: PROVERBS,
    },
  });
})();
