/* ============================================================================
 * German course — data only.
 *
 * `ta` is the German, `tr` a plain-English respelling (stressed syllable in
 * CAPS; "kh" is the throaty ch of "Buch", "ü/ö" are written as "ue/oe" hints),
 * `en` the meaning. Nouns carry their article — der/die/das is the one thing
 * you can't guess later, so it is learned with the word from the start.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------ Alphabet ------------------------------- */
  const LETTERS = A([
    ["A a", "ah"], ["B b", "beh"], ["C c", "tseh"], ["D d", "deh"], ["E e", "eh"],
    ["F f", "eff"], ["G g", "geh"], ["H h", "hah"], ["I i", "ee"], ["J j", "yot"],
    ["K k", "kah"], ["L l", "ell"], ["M m", "emm"], ["N n", "enn"], ["O o", "oh"],
    ["P p", "peh"], ["Q q", "koo"], ["R r", "err"], ["S s", "ess"], ["T t", "teh"],
    ["U u", "oo"], ["V v", "fow"], ["W w", "veh"], ["X x", "iks"],
    ["Y y", "IP-si-lon"], ["Z z", "tset"], ["Ä ä", "eh"], ["Ö ö", "oe"],
    ["Ü ü", "ue"], ["ß", "ES-tset"],
  ]);
  const SOUNDS = A([
    ["ei", "eye", "as in 'mein'"], ["ie", "ee", "as in 'sie'"],
    ["eu / äu", "oy", "as in 'neu'"], ["au", "ow", "as in 'Haus'"],
    ["ch (after a/o/u)", "kh", "throaty, as in 'Buch'"],
    ["ch (after i/e)", "hy", "soft, as in 'ich'"],
    ["sch", "sh", "as in 'Schule'"], ["sp- / st-", "shp / sht", "at the start of a word"],
    ["v", "f", "as in 'Vater'"], ["w", "v", "as in 'Wasser'"],
    ["z", "ts", "as in 'Zeit'"], ["j", "y", "as in 'ja'"],
    ["ß", "ss", "sharp s after a long vowel"],
    ["-er (final)", "uh", "as in 'Vater'"],
    ["r (final)", "uh", "barely pronounced"],
  ]);
  const ALPHABET = { vowels: LETTERS, consonants: SOUNDS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["hallo", "HAH-loh", "hello"], ["guten Morgen", "GOO-ten MOR-gen", "good morning"],
      ["guten Tag", "GOO-ten TAHK", "good day / hello"],
      ["guten Abend", "GOO-ten AH-bent", "good evening"],
      ["gute Nacht", "GOO-teh NAKHT", "good night"],
      ["tschüss", "CHUESS", "bye (informal)"],
      ["auf Wiedersehen", "owf VEE-der-zeh-en", "goodbye"],
      ["servus", "ZEHR-voos", "hi / bye (south)"],
      ["danke", "DAHN-keh", "thank you"],
      ["vielen Dank", "FEE-len DAHNK", "many thanks"],
      ["bitte", "BIT-teh", "please / you're welcome"],
      ["ja", "YAH", "yes"], ["nein", "NINE", "no"],
      ["entschuldigung", "ent-SHOOL-di-goong", "excuse me / sorry"],
      ["es tut mir leid", "es toot meer LITE", "I'm sorry"],
      ["wie geht es dir?", "vee GATE es DEER", "how are you?"],
      ["mir geht es gut", "meer gate es GOOT", "I'm well"],
      ["nicht schlecht", "nikht SHLEKHT", "not bad"],
      ["freut mich", "FROYT mikh", "pleased to meet you"],
      ["willkommen", "vil-KOM-men", "welcome"],
      ["bis bald", "bis BAHLT", "see you soon"],
      ["bis morgen", "bis MOR-gen", "see you tomorrow"],
      ["guten Appetit", "GOO-ten ah-peh-TEET", "enjoy your meal"],
      ["prost", "PROHST", "cheers"],
      ["herzlichen Glückwunsch", "HERTS-likh-en GLUEK-voonsh", "congratulations"],
      ["viel Glück", "feel GLUEK", "good luck"],
      ["in Ordnung", "in ORD-noong", "okay / all right"],
    ]),
    V("numbers", [
      ["null", "NOOL", "zero"], ["eins", "INES", "one"], ["zwei", "TSVYE", "two"],
      ["drei", "DRYE", "three"], ["vier", "FEER", "four"], ["fünf", "FUENF", "five"],
      ["sechs", "ZEKS", "six"], ["sieben", "ZEE-ben", "seven"], ["acht", "AKHT", "eight"],
      ["neun", "NOYN", "nine"], ["zehn", "TSANE", "ten"], ["elf", "ELF", "eleven"],
      ["zwölf", "TSVOELF", "twelve"], ["dreizehn", "DRYE-tsane", "thirteen"],
      ["vierzehn", "FEER-tsane", "fourteen"], ["fünfzehn", "FUENF-tsane", "fifteen"],
      ["sechzehn", "ZEKH-tsane", "sixteen"], ["zwanzig", "TSVAHN-tsikh", "twenty"],
      ["dreißig", "DRYE-sikh", "thirty"], ["vierzig", "FEER-tsikh", "forty"],
      ["fünfzig", "FUENF-tsikh", "fifty"], ["hundert", "HOON-dert", "one hundred"],
      ["tausend", "TOW-zent", "one thousand"], ["erste", "EHR-steh", "first"],
      ["zweite", "TSVYE-teh", "second"], ["letzte", "LETS-teh", "last"],
      ["die Hälfte", "dee HELF-teh", "half"], ["die Zahl", "dee TSAHL", "number"],
    ]),
    V("colors", [
      ["rot", "ROHT", "red"], ["blau", "BLOW", "blue"], ["grün", "GRUEN", "green"],
      ["gelb", "GELP", "yellow"], ["schwarz", "SHVARTS", "black"], ["weiß", "VICE", "white"],
      ["grau", "GROW", "grey"], ["braun", "BROWN", "brown"],
      ["orange", "oh-RAHN-zheh", "orange"], ["rosa", "ROH-zah", "pink"],
      ["lila", "LEE-lah", "purple"], ["golden", "GOL-den", "golden"],
      ["silbern", "ZIL-bern", "silver"], ["hell", "HELL", "light / bright"],
      ["dunkel", "DOON-kel", "dark"], ["die Farbe", "dee FAR-beh", "colour"],
      ["bunt", "BOONT", "colourful"], ["beige", "BEHZH", "beige"],
      ["türkis", "tuer-KEES", "turquoise"], ["blass", "BLAHSS", "pale"],
      ["hellblau", "HELL-blow", "light blue"], ["dunkelrot", "DOON-kel-roht", "dark red"],
    ]),
    V("family", [
      ["die Familie", "dee fah-MEE-lyeh", "family"], ["die Mutter", "dee MOO-ter", "mother"],
      ["der Vater", "dehr FAH-ter", "father"], ["die Mama", "dee MAH-mah", "mum"],
      ["der Papa", "dehr PAH-pah", "dad"], ["die Eltern", "dee EL-tern", "parents"],
      ["der Sohn", "dehr ZOHN", "son"], ["die Tochter", "dee TOKH-ter", "daughter"],
      ["der Bruder", "dehr BROO-der", "brother"], ["die Schwester", "dee SHVES-ter", "sister"],
      ["die Geschwister", "dee geh-SHVIS-ter", "siblings"],
      ["der Großvater", "dehr GROHS-fah-ter", "grandfather"],
      ["die Großmutter", "dee GROHS-moo-ter", "grandmother"],
      ["der Enkel", "dehr EN-kel", "grandson"], ["der Onkel", "dehr ON-kel", "uncle"],
      ["die Tante", "dee TAHN-teh", "aunt"], ["der Cousin", "dehr koo-ZEHN", "cousin (m)"],
      ["der Neffe", "dehr NEF-feh", "nephew"], ["der Mann", "dehr MAHN", "man / husband"],
      ["die Frau", "dee FROW", "woman / wife"], ["das Baby", "dahs BAY-bee", "baby"],
      ["das Kind", "dahs KINT", "child"], ["der Verwandte", "dehr fehr-VAHN-teh", "relative"],
      ["die Hochzeit", "dee HOKH-tsite", "wedding"],
      ["der Schwiegervater", "dehr SHVEE-ger-fah-ter", "father-in-law"],
    ]),
    V("people", [
      ["die Person", "dee pehr-ZOHN", "person"], ["die Leute", "dee LOY-teh", "people"],
      ["der Junge", "dehr YOON-geh", "boy"], ["das Mädchen", "dahs MAYT-khen", "girl"],
      ["der Freund", "dehr FROYNT", "friend (m)"], ["die Freundin", "dee FROYN-din", "friend (f)"],
      ["der Nachbar", "dehr NAKH-bar", "neighbour"], ["der Herr", "dehr HEHR", "Mr / gentleman"],
      ["die Dame", "dee DAH-meh", "lady"], ["der Jugendliche", "dehr YOO-gent-likh-eh", "teenager"],
      ["der Erwachsene", "dehr ehr-VAHK-seh-neh", "adult"],
      ["der Rentner", "dehr RENT-ner", "pensioner"], ["der Gast", "dehr GAHST", "guest"],
      ["der Ausländer", "dehr OWS-len-der", "foreigner"],
      ["der Kollege", "dehr ko-LEH-geh", "colleague"],
      ["die Mannschaft", "dee MAHN-shahft", "team"], ["die Gruppe", "dee GROO-peh", "group"],
      ["der Name", "dehr NAH-meh", "name"], ["der Nachname", "dehr NAKH-nah-meh", "surname"],
      ["der Chef", "dehr SHEF", "boss"], ["der Mensch", "dehr MENSH", "human being"],
      ["das Volk", "dahs FOLK", "a people / nation"],
    ]),
    V("pronouns", [
      ["ich", "IKH", "I"], ["du", "DOO", "you (informal)"], ["Sie", "ZEE", "you (formal)"],
      ["er", "EHR", "he"], ["sie", "ZEE", "she / they"], ["es", "ES", "it"],
      ["wir", "VEER", "we"], ["ihr", "EER", "you (plural)"],
      ["mich", "MIKH", "me (accusative)"], ["dich", "DIKH", "you (accusative)"],
      ["mir", "MEER", "to me"], ["dir", "DEER", "to you"], ["ihn", "EEN", "him"],
      ["uns", "OONS", "us"], ["mein", "MINE", "my"], ["dein", "DINE", "your"],
      ["sein", "ZINE", "his / its"], ["ihr (besitzend)", "EER", "her / their"],
      ["unser", "OON-zer", "our"], ["dieser", "DEE-zer", "this"],
      ["jener", "YEH-ner", "that"], ["jemand", "YEH-mahnt", "someone"],
      ["niemand", "NEE-mahnt", "nobody"], ["alle", "AH-leh", "everyone"],
      ["man", "MAHN", "one / people (in general)"], ["sich", "ZIKH", "oneself"],
    ]),
    V("questions", [
      ["was?", "VAHS", "what?"], ["wer?", "VEHR", "who?"], ["wo?", "VOH", "where?"],
      ["wann?", "VAHN", "when?"], ["warum?", "vah-ROOM", "why?"], ["wie?", "VEE", "how?"],
      ["welcher?", "VEL-kher", "which?"], ["wie viel?", "vee FEEL", "how much?"],
      ["wie viele?", "vee FEE-leh", "how many?"], ["woher?", "voh-HEHR", "where from?"],
      ["wohin?", "voh-HIN", "where to?"], ["wessen?", "VES-sen", "whose?"],
      ["nicht wahr?", "nikht VAHR", "isn't it?"], ["die Frage", "dee FRAH-geh", "question"],
      ["die Antwort", "dee AHNT-vort", "answer"], ["fragen", "FRAH-gen", "to ask"],
      ["antworten", "AHNT-vor-ten", "to answer"],
      ["was kostet das?", "vahs KOS-tet dahs", "what does that cost?"],
      ["wie spät ist es?", "vee SHPAYT ist es", "what time is it?"],
      ["was ist los?", "vahs ist LOHS", "what's going on?"],
    ]),
    V("grammar", [
      ["und", "OONT", "and"], ["oder", "OH-der", "or"], ["aber", "AH-ber", "but"],
      ["weil", "VILE", "because"], ["wenn", "VEN", "if / when"], ["dass", "DAHS", "that (conj.)"],
      ["von", "FON", "from / of"], ["zu", "TSOO", "to"], ["in", "IN", "in"],
      ["auf", "OWF", "on"], ["unter", "OON-ter", "under"], ["mit", "MIT", "with"],
      ["ohne", "OH-neh", "without"], ["für", "FUER", "for"], ["bei", "BYE", "at / near"],
      ["nach", "NAHKH", "after / to"], ["vor", "FOR", "before / in front of"],
      ["zwischen", "TSVISH-en", "between"], ["seit", "ZITE", "since"],
      ["bis", "BIS", "until"], ["der", "DEHR", "the (m)"], ["die", "DEE", "the (f/pl)"],
      ["das", "DAHS", "the (n)"], ["ein", "INE", "a (m/n)"], ["eine", "INE-eh", "a (f)"],
      ["auch", "OWKH", "also"], ["nicht", "NIKHT", "not"], ["kein", "KINE", "no / none"],
      ["also", "AHL-zoh", "so / therefore"], ["während", "VEH-rent", "while / during"],
    ]),
    V("adjectives", [
      ["groß", "GROHS", "big / tall"], ["klein", "KLINE", "small"],
      ["gut", "GOOT", "good"], ["schlecht", "SHLEKHT", "bad"], ["neu", "NOY", "new"],
      ["alt", "AHLT", "old"], ["jung", "YOONG", "young"], ["lang", "LAHNG", "long"],
      ["kurz", "KOORTS", "short"], ["hoch", "HOHKH", "high"], ["niedrig", "NEE-drikh", "low"],
      ["heiß", "HICE", "hot"], ["kalt", "KAHLT", "cold"], ["warm", "VARM", "warm"],
      ["einfach", "INE-fahkh", "easy / simple"], ["schwierig", "SHVEE-rikh", "difficult"],
      ["schön", "SHOEN", "beautiful"], ["hässlich", "HESS-likh", "ugly"],
      ["stark", "SHTARK", "strong"], ["schwach", "SHVAHKH", "weak"],
      ["schnell", "SHNELL", "fast"], ["langsam", "LAHNG-zahm", "slow"],
      ["reich", "RIKH", "rich"], ["arm", "ARM", "poor"], ["glücklich", "GLUEK-likh", "happy"],
      ["traurig", "TROW-rikh", "sad"], ["müde", "MUE-deh", "tired"],
      ["sauber", "ZOW-ber", "clean"], ["schmutzig", "SHMOOT-sikh", "dirty"],
      ["voll", "FOL", "full"], ["leer", "LEHR", "empty"], ["teuer", "TOY-er", "expensive"],
      ["billig", "BIL-likh", "cheap"], ["wichtig", "VIKH-tikh", "important"],
    ]),
    V("adverbs", [
      ["sehr", "ZEHR", "very"], ["viel", "FEEL", "a lot"], ["wenig", "VEH-nikh", "little"],
      ["gut", "GOOT", "well"], ["schlecht", "SHLEKHT", "badly"],
      ["immer", "IM-mer", "always"], ["nie", "NEE", "never"],
      ["manchmal", "MAHNKH-mahl", "sometimes"], ["oft", "OFT", "often"],
      ["jetzt", "YETST", "now"], ["heute", "HOY-teh", "today"],
      ["gestern", "GES-tern", "yesterday"], ["morgen", "MOR-gen", "tomorrow"],
      ["früh", "FRUE", "early"], ["spät", "SHPAYT", "late"], ["hier", "HEER", "here"],
      ["dort", "DORT", "there"], ["nah", "NAH", "near"], ["weit", "VITE", "far"],
      ["zusammen", "tsoo-ZAHM-men", "together"], ["nur", "NOOR", "only"],
      ["vielleicht", "fee-LIKHT", "maybe"], ["schon", "SHOHN", "already"],
      ["noch", "NOKH", "still / yet"], ["wieder", "VEE-der", "again"],
      ["fast", "FAHST", "almost"], ["zu viel", "tsoo FEEL", "too much"],
      ["wirklich", "VIRK-likh", "really"], ["gern", "GEHRN", "gladly"],
    ]),
    V("verbs", [
      ["sein", "ZINE", "to be"], ["haben", "HAH-ben", "to have"],
      ["werden", "VEHR-den", "to become"], ["machen", "MAH-khen", "to do / make"],
      ["gehen", "GEH-en", "to go"], ["kommen", "KOM-men", "to come"],
      ["können", "KOEN-nen", "to be able to"], ["wollen", "VOL-len", "to want"],
      ["müssen", "MUES-sen", "to have to"], ["sollen", "ZOL-len", "should"],
      ["dürfen", "DUER-fen", "to be allowed to"], ["wissen", "VIS-sen", "to know (facts)"],
      ["kennen", "KEN-nen", "to know (people)"], ["sagen", "ZAH-gen", "to say"],
      ["sprechen", "SHPREKH-en", "to speak"], ["essen", "ES-sen", "to eat"],
      ["trinken", "TRIN-ken", "to drink"], ["leben", "LEH-ben", "to live"],
      ["wohnen", "VOH-nen", "to live (reside)"], ["sehen", "ZEH-en", "to see"],
      ["schauen", "SHOW-en", "to look"], ["hören", "HOE-ren", "to hear"],
      ["lesen", "LEH-zen", "to read"], ["schreiben", "SHRYE-ben", "to write"],
      ["arbeiten", "AR-bye-ten", "to work"], ["lernen", "LEHR-nen", "to learn"],
      ["schlafen", "SHLAH-fen", "to sleep"], ["kaufen", "KOW-fen", "to buy"],
      ["verkaufen", "fehr-KOW-fen", "to sell"], ["öffnen", "OEF-nen", "to open"],
      ["schließen", "SHLEE-sen", "to close"], ["anfangen", "AHN-fahn-gen", "to begin"],
      ["beenden", "beh-EN-den", "to finish"], ["helfen", "HEL-fen", "to help"],
      ["brauchen", "BROW-khen", "to need"], ["denken", "DEN-ken", "to think"],
      ["laufen", "LOW-fen", "to run / walk"], ["warten", "VAR-ten", "to wait"],
      ["geben", "GEH-ben", "to give"], ["nehmen", "NEH-men", "to take"],
      ["fahren", "FAH-ren", "to drive / travel"],
    ]),
    V("food", [
      ["das Essen", "dahs ES-sen", "food / meal"], ["das Wasser", "dahs VAHS-ser", "water"],
      ["das Brot", "dahs BROHT", "bread"], ["der Reis", "dehr RICE", "rice"],
      ["das Fleisch", "dahs FLYSHE", "meat"], ["das Hähnchen", "dahs HAYN-khen", "chicken"],
      ["der Fisch", "dehr FISH", "fish"], ["das Ei", "dahs EYE", "egg"],
      ["die Milch", "dee MILKH", "milk"], ["der Käse", "dehr KAY-zeh", "cheese"],
      ["die Butter", "dee BOO-ter", "butter"], ["das Obst", "dahs OHPST", "fruit"],
      ["der Apfel", "dehr AHP-fel", "apple"], ["die Banane", "dee bah-NAH-neh", "banana"],
      ["die Orange", "dee oh-RAHN-zheh", "orange"], ["das Gemüse", "dahs geh-MUE-zeh", "vegetables"],
      ["die Kartoffel", "dee kar-TOF-fel", "potato"], ["die Tomate", "dee toh-MAH-teh", "tomato"],
      ["die Zwiebel", "dee TSVEE-bel", "onion"], ["der Knoblauch", "dehr KNOHP-lowkh", "garlic"],
      ["das Salz", "dahs ZAHLTS", "salt"], ["der Pfeffer", "dehr PFEF-fer", "pepper"],
      ["der Zucker", "dehr TSOO-ker", "sugar"], ["das Öl", "dahs OEL", "oil"],
      ["der Kaffee", "dehr KAH-feh", "coffee"], ["der Tee", "dehr TEH", "tea"],
      ["der Wein", "dehr VINE", "wine"], ["das Bier", "dahs BEER", "beer"],
      ["der Saft", "dehr ZAHFT", "juice"], ["die Suppe", "dee ZOO-peh", "soup"],
      ["der Salat", "dehr zah-LAHT", "salad"], ["der Kuchen", "dehr KOO-khen", "cake"],
      ["die Nachspeise", "dee NAHKH-shpye-zeh", "dessert"],
      ["das Frühstück", "dahs FRUE-shtuek", "breakfast"],
      ["das Mittagessen", "dahs MIT-tahk-es-sen", "lunch"],
      ["das Abendessen", "dahs AH-bent-es-sen", "dinner"],
      ["das Restaurant", "dahs res-toh-RAHNG", "restaurant"],
      ["die Rechnung", "dee REKH-noong", "the bill"],
    ]),
    V("body", [
      ["der Körper", "dehr KOER-per", "body"], ["der Kopf", "dehr KOPF", "head"],
      ["das Haar", "dahs HAHR", "hair"], ["das Gesicht", "dahs geh-ZIKHT", "face"],
      ["das Auge", "dahs OW-geh", "eye"], ["das Ohr", "dahs OHR", "ear"],
      ["die Nase", "dee NAH-zeh", "nose"], ["der Mund", "dehr MOONT", "mouth"],
      ["der Zahn", "dehr TSAHN", "tooth"], ["die Zunge", "dee TSOON-geh", "tongue"],
      ["der Hals", "dehr HAHLS", "neck / throat"], ["die Schulter", "dee SHOOL-ter", "shoulder"],
      ["der Arm", "dehr ARM", "arm"], ["die Hand", "dee HAHNT", "hand"],
      ["der Finger", "dehr FIN-ger", "finger"], ["das Bein", "dahs BINE", "leg"],
      ["der Fuß", "dehr FOOS", "foot"], ["das Knie", "dahs KNEE", "knee"],
      ["der Rücken", "dehr RUE-ken", "back"], ["die Brust", "dee BROOST", "chest"],
      ["das Herz", "dahs HEHRTS", "heart"], ["der Magen", "dehr MAH-gen", "stomach"],
      ["das Blut", "dahs BLOOT", "blood"], ["der Knochen", "dehr KNOKH-en", "bone"],
      ["die Haut", "dee HOWT", "skin"],
    ]),
    V("health", [
      ["die Gesundheit", "dee geh-ZOONT-hite", "health"], ["der Arzt", "dehr ARTST", "doctor"],
      ["das Krankenhaus", "dahs KRAHN-ken-hows", "hospital"],
      ["die Apotheke", "dee ah-poh-TEH-keh", "pharmacy"],
      ["die Medizin", "dee meh-dee-TSEEN", "medicine"], ["krank", "KRAHNK", "ill"],
      ["gesund", "geh-ZOONT", "healthy"], ["der Schmerz", "dehr SHMEHRTS", "pain"],
      ["das Fieber", "dahs FEE-ber", "fever"], ["der Husten", "dehr HOOS-ten", "cough"],
      ["die Erkältung", "dee ehr-KEL-toong", "a cold"], ["die Wunde", "dee VOON-deh", "wound"],
      ["die Krankenschwester", "dee KRAHN-ken-shves-ter", "nurse"],
      ["der Termin", "dehr tehr-MEEN", "appointment"],
      ["es tut weh", "es toot VEH", "it hurts"],
      ["der Krankenwagen", "dehr KRAHN-ken-vah-gen", "ambulance"],
      ["der Notfall", "dehr NOHT-fahl", "emergency"],
      ["sich ausruhen", "zikh OWS-roo-en", "to rest"],
      ["die Bewegung", "dee beh-VEH-goong", "exercise / movement"],
      ["die Diät", "dee dee-ATE", "diet"], ["das Rezept", "dahs reh-TSEPT", "prescription"],
      ["gesund werden", "geh-ZOONT VEHR-den", "to get well"],
    ]),
    V("clothing", [
      ["die Kleidung", "dee KLYE-doong", "clothing"], ["das Hemd", "dahs HEMT", "shirt"],
      ["das T-Shirt", "dahs TEE-shirt", "t-shirt"], ["die Hose", "dee HOH-zeh", "trousers"],
      ["die Jeans", "dee JEENS", "jeans"], ["das Kleid", "dahs KLITE", "dress"],
      ["der Rock", "dehr ROK", "skirt"], ["der Mantel", "dehr MAHN-tel", "coat"],
      ["die Jacke", "dee YAH-keh", "jacket"], ["der Pullover", "dehr poo-LOH-ver", "sweater"],
      ["die Schuhe", "dee SHOO-eh", "shoes"], ["die Stiefel", "dee SHTEE-fel", "boots"],
      ["die Socken", "dee ZOK-ken", "socks"], ["der Hut", "dehr HOOT", "hat"],
      ["die Mütze", "dee MUET-seh", "cap"], ["der Schal", "dehr SHAHL", "scarf"],
      ["die Handschuhe", "dee HAHNT-shoo-eh", "gloves"], ["der Gürtel", "dehr GUER-tel", "belt"],
      ["die Brille", "dee BRIL-leh", "glasses"], ["die Tasche", "dee TAH-sheh", "bag"],
      ["der Anzug", "dehr AHN-tsook", "suit"], ["die Größe", "dee GROE-seh", "size"],
      ["tragen", "TRAH-gen", "to wear"], ["anprobieren", "AHN-proh-bee-ren", "to try on"],
    ]),
    V("home", [
      ["das Haus", "dahs HOWS", "house"], ["die Wohnung", "dee VOH-noong", "apartment"],
      ["das Zimmer", "dahs TSIM-mer", "room"], ["die Küche", "dee KUE-kheh", "kitchen"],
      ["das Badezimmer", "dahs BAH-deh-tsim-mer", "bathroom"],
      ["das Schlafzimmer", "dahs SHLAHF-tsim-mer", "bedroom"],
      ["das Wohnzimmer", "dahs VOHN-tsim-mer", "living room"],
      ["die Tür", "dee TUER", "door"], ["das Fenster", "dahs FENS-ter", "window"],
      ["der Tisch", "dehr TISH", "table"], ["der Stuhl", "dehr SHTOOL", "chair"],
      ["das Bett", "dahs BET", "bed"], ["das Sofa", "dahs ZOH-fah", "sofa"],
      ["die Lampe", "dee LAHM-peh", "lamp"], ["der Spiegel", "dehr SHPEE-gel", "mirror"],
      ["der Schlüssel", "dehr SHLUES-sel", "key"], ["der Teller", "dehr TEL-ler", "plate"],
      ["das Glas", "dahs GLAHS", "glass"], ["die Tasse", "dee TAH-seh", "cup"],
      ["das Messer", "dahs MES-ser", "knife"], ["die Gabel", "dee GAH-bel", "fork"],
      ["der Löffel", "dehr LOEF-fel", "spoon"], ["der Garten", "dehr GAR-ten", "garden"],
      ["die Treppe", "dee TREP-peh", "stairs"], ["das Dach", "dahs DAHKH", "roof"],
      ["die Wand", "dee VAHNT", "wall"], ["der Boden", "dehr BOH-den", "floor"],
      ["der Kühlschrank", "dehr KUEL-shrahnk", "fridge"],
    ]),
    V("animals", [
      ["das Tier", "dahs TEER", "animal"], ["der Hund", "dehr HOONT", "dog"],
      ["die Katze", "dee KAHT-seh", "cat"], ["das Pferd", "dahs PFEHRT", "horse"],
      ["die Kuh", "dee KOO", "cow"], ["das Schwein", "dahs SHVINE", "pig"],
      ["das Schaf", "dahs SHAHF", "sheep"], ["das Huhn", "dahs HOON", "chicken (hen)"],
      ["der Vogel", "dehr FOH-gel", "bird"], ["der Fisch", "dehr FISH", "fish"],
      ["die Maus", "dee MOWS", "mouse"], ["das Kaninchen", "dahs kah-NEEN-khen", "rabbit"],
      ["der Löwe", "dehr LOE-veh", "lion"], ["der Tiger", "dehr TEE-ger", "tiger"],
      ["der Elefant", "dehr eh-leh-FAHNT", "elephant"], ["der Affe", "dehr AHF-feh", "monkey"],
      ["der Bär", "dehr BEHR", "bear"], ["der Wolf", "dehr VOLF", "wolf"],
      ["die Schlange", "dee SHLAHN-geh", "snake"], ["die Spinne", "dee SHPIN-neh", "spider"],
      ["der Schmetterling", "dehr SHMET-ter-ling", "butterfly"],
      ["die Biene", "dee BEE-neh", "bee"], ["die Ameise", "dee AH-mye-zeh", "ant"],
      ["die Fliege", "dee FLEE-geh", "fly"], ["die Schildkröte", "dee SHILT-kroe-teh", "tortoise"],
    ]),
    V("nature", [
      ["die Natur", "dee nah-TOOR", "nature"], ["die Sonne", "dee ZON-neh", "sun"],
      ["der Mond", "dehr MOHNT", "moon"], ["der Stern", "dehr SHTEHRN", "star"],
      ["der Himmel", "dehr HIM-mel", "sky"], ["die Wolke", "dee VOL-keh", "cloud"],
      ["der Regen", "dehr REH-gen", "rain"], ["der Schnee", "dehr SHNEH", "snow"],
      ["der Wind", "dehr VINT", "wind"], ["das Feuer", "dahs FOY-er", "fire"],
      ["die Erde", "dee EHR-deh", "earth"], ["das Meer", "dahs MEHR", "sea"],
      ["der Fluss", "dehr FLOOS", "river"], ["der See", "dehr ZEH", "lake"],
      ["der Berg", "dehr BEHRK", "mountain"], ["der Wald", "dehr VAHLT", "forest"],
      ["der Baum", "dehr BOWM", "tree"], ["die Blume", "dee BLOO-meh", "flower"],
      ["das Blatt", "dahs BLAHT", "leaf"], ["das Gras", "dahs GRAHS", "grass"],
      ["der Strand", "dehr SHTRAHNT", "beach"], ["die Insel", "dee IN-zel", "island"],
      ["die Wüste", "dee VUES-teh", "desert"], ["der Stein", "dehr SHTINE", "stone"],
      ["das Wetter", "dahs VET-ter", "weather"], ["das Gewitter", "dahs geh-VIT-ter", "storm"],
    ]),
    V("places", [
      ["der Ort", "dehr ORT", "place"], ["die Stadt", "dee SHTAHT", "city / town"],
      ["das Dorf", "dahs DORF", "village"], ["das Land", "dahs LAHNT", "country"],
      ["die Straße", "dee SHTRAH-seh", "street"], ["der Platz", "dehr PLAHTS", "square"],
      ["der Markt", "dehr MARKT", "market"], ["das Geschäft", "dahs geh-SHEFT", "shop"],
      ["die Bank", "dee BAHNK", "bank"], ["die Schule", "dee SHOO-leh", "school"],
      ["die Kirche", "dee KEER-kheh", "church"], ["das Museum", "dahs moo-ZEH-oom", "museum"],
      ["der Park", "dehr PARK", "park"], ["das Hotel", "dahs hoh-TEL", "hotel"],
      ["der Flughafen", "dehr FLOOK-hah-fen", "airport"],
      ["der Bahnhof", "dehr BAHN-hohf", "train station"],
      ["die Bibliothek", "dee bee-blee-oh-TEHK", "library"],
      ["das Büro", "dahs buer-OH", "office"], ["das Kino", "dahs KEE-noh", "cinema"],
      ["das Viertel", "dahs FEER-tel", "neighbourhood"],
      ["die Innenstadt", "dee IN-nen-shtaht", "town centre"],
      ["das Krankenhaus", "dahs KRAHN-ken-hows", "hospital"],
      ["die Grenze", "dee GREN-tseh", "border"], ["die Bäckerei", "dee bek-ker-EYE", "bakery"],
    ]),
    V("travel", [
      ["die Reise", "dee RYE-zeh", "journey"], ["reisen", "RYE-zen", "to travel"],
      ["das Auto", "dahs OW-toh", "car"], ["der Bus", "dehr BOOS", "bus"],
      ["der Zug", "dehr TSOOK", "train"], ["das Flugzeug", "dahs FLOOK-tsoyk", "aeroplane"],
      ["das Fahrrad", "dahs FAHR-raht", "bicycle"], ["das Schiff", "dahs SHIF", "ship"],
      ["das Taxi", "dahs TAHK-see", "taxi"], ["die U-Bahn", "dee OO-bahn", "underground"],
      ["die Fahrkarte", "dee FAHR-kar-teh", "ticket"],
      ["der Reisepass", "dehr RYE-zeh-pahs", "passport"],
      ["der Koffer", "dehr KOF-fer", "suitcase"], ["das Gepäck", "dahs geh-PEK", "luggage"],
      ["die Karte", "dee KAR-teh", "map / card"], ["der Weg", "dehr VEHK", "way / path"],
      ["die Abfahrt", "dee AHP-fahrt", "departure"], ["die Ankunft", "dee AHN-koonft", "arrival"],
      ["die Verspätung", "dee fehr-SHPAY-toong", "delay"],
      ["links", "LINKS", "left"], ["rechts", "REKHTS", "right"],
      ["geradeaus", "geh-RAH-deh-ows", "straight ahead"],
      ["sich verirren", "zikh fehr-EER-ren", "to get lost"],
      ["der Zoll", "dehr TSOL", "customs"], ["die Haltestelle", "dee HAHL-teh-shtel-leh", "stop"],
    ]),
    V("time", [
      ["die Zeit", "dee TSITE", "time"], ["die Stunde", "dee SHTOON-deh", "hour"],
      ["die Minute", "dee mee-NOO-teh", "minute"], ["die Sekunde", "dee zeh-KOON-deh", "second"],
      ["der Tag", "dehr TAHK", "day"], ["die Woche", "dee VOH-kheh", "week"],
      ["der Monat", "dehr MOH-naht", "month"], ["das Jahr", "dahs YAHR", "year"],
      ["der Morgen", "dehr MOR-gen", "morning"],
      ["der Nachmittag", "dehr NAHKH-mit-tahk", "afternoon"],
      ["der Abend", "dehr AH-bent", "evening"], ["die Nacht", "dee NAHKHT", "night"],
      ["Montag", "MOHN-tahk", "Monday"], ["Dienstag", "DEENS-tahk", "Tuesday"],
      ["Mittwoch", "MIT-vokh", "Wednesday"], ["Donnerstag", "DON-ners-tahk", "Thursday"],
      ["Freitag", "FRYE-tahk", "Friday"], ["Samstag", "ZAHMS-tahk", "Saturday"],
      ["Sonntag", "ZON-tahk", "Sunday"], ["Januar", "YAH-noo-ar", "January"],
      ["Februar", "FEH-broo-ar", "February"], ["März", "MEHRTS", "March"],
      ["April", "ah-PRIL", "April"], ["Mai", "MY", "May"], ["Juni", "YOO-nee", "June"],
      ["Juli", "YOO-lee", "July"], ["das Wochenende", "dahs VOH-khen-en-deh", "weekend"],
      ["die Uhr", "dee OOR", "clock / o'clock"], ["der Sommer", "dehr ZOM-mer", "summer"],
      ["der Winter", "dehr VIN-ter", "winter"],
    ]),
    V("work", [
      ["die Arbeit", "dee AR-bite", "work"], ["der Beruf", "dehr beh-ROOF", "profession"],
      ["die Firma", "dee FEER-mah", "company"], ["der Mitarbeiter", "dehr MIT-ar-bye-ter", "employee"],
      ["das Gehalt", "dahs geh-HAHLT", "salary"], ["das Geld", "dahs GELT", "money"],
      ["der Euro", "dehr OY-roh", "euro"], ["der Preis", "dehr PRICE", "price"],
      ["bezahlen", "beh-TSAH-len", "to pay"], ["die Besprechung", "dee beh-SHPREKH-oong", "meeting"],
      ["das Projekt", "dahs proh-YEKT", "project"], ["der Kunde", "dehr KOON-deh", "customer"],
      ["die Rechnung", "dee REKH-noong", "invoice / bill"],
      ["der Vertrag", "dehr fehr-TRAHK", "contract"], ["die Karte", "dee KAR-teh", "card"],
      ["das Bargeld", "dahs BAR-gelt", "cash"],
      ["der Ingenieur", "dehr in-zheh-NYOER", "engineer"],
      ["der Lehrer", "dehr LEH-rer", "teacher"], ["der Anwalt", "dehr AHN-vahlt", "lawyer"],
      ["der Verkäufer", "dehr fehr-KOY-fer", "salesperson"],
      ["verdienen", "fehr-DEE-nen", "to earn"], ["der Rabatt", "dehr rah-BAHT", "discount"],
      ["die Steuer", "dee SHTOY-er", "tax"],
    ]),
    V("school", [
      ["die Schule", "dee SHOO-leh", "school"],
      ["die Universität", "dee oo-nee-vehr-zee-TATE", "university"],
      ["die Klasse", "dee KLAH-seh", "class"], ["der Schüler", "dehr SHUE-ler", "pupil"],
      ["der Student", "dehr shtoo-DENT", "student"], ["der Lehrer", "dehr LEH-rer", "teacher"],
      ["das Buch", "dahs BOOKH", "book"], ["das Heft", "dahs HEFT", "notebook"],
      ["der Bleistift", "dehr BLYE-shtift", "pencil"], ["der Kugelschreiber", "dehr KOO-gel-shrye-ber", "pen"],
      ["das Papier", "dahs pah-PEER", "paper"], ["das Wort", "dahs VORT", "word"],
      ["der Satz", "dehr ZAHTS", "sentence"], ["die Lektion", "dee lek-TSYOHN", "lesson"],
      ["die Prüfung", "dee PRUE-foong", "exam"], ["die Hausaufgaben", "dee HOWS-owf-gah-ben", "homework"],
      ["die Note", "dee NOH-teh", "grade"], ["lernen", "LEHR-nen", "to learn"],
      ["unterrichten", "OON-ter-rikh-ten", "to teach"], ["verstehen", "fehr-SHTEH-en", "to understand"],
      ["erklären", "ehr-KLEH-ren", "to explain"], ["die Antwort", "dee AHNT-vort", "answer"],
      ["die Sprache", "dee SHPRAH-kheh", "language"], ["die Geschichte", "dee geh-SHIKH-teh", "history / story"],
      ["die Mathematik", "dee mah-teh-mah-TEEK", "maths"],
      ["die Wissenschaft", "dee VIS-sen-shahft", "science"],
    ]),
    V("tech", [
      ["der Computer", "dehr kom-PYOO-ter", "computer"],
      ["das Telefon", "dahs teh-leh-FOHN", "telephone"],
      ["das Handy", "dahs HEN-dee", "mobile phone"],
      ["der Bildschirm", "dehr BILT-shirm", "screen"],
      ["die Tastatur", "dee tahs-tah-TOOR", "keyboard"], ["die Maus", "dee MOWS", "mouse"],
      ["das Internet", "dahs IN-ter-net", "internet"], ["das Netzwerk", "dahs NETS-vehrk", "network"],
      ["die E-Mail", "dee EE-mail", "email"], ["das Passwort", "dahs PAHS-vort", "password"],
      ["die Datei", "dee dah-TYE", "file"], ["der Ordner", "dehr ORD-ner", "folder"],
      ["die App", "dee AHP", "app"], ["das Programm", "dahs proh-GRAHM", "program"],
      ["herunterladen", "heh-ROON-ter-lah-den", "to download"],
      ["hochladen", "HOHKH-lah-den", "to upload"], ["speichern", "SHPYE-khern", "to save"],
      ["löschen", "LOE-shen", "to delete"], ["suchen", "ZOO-khen", "to search"],
      ["einschalten", "INE-shahl-ten", "to switch on"],
      ["ausschalten", "OWS-shahl-ten", "to switch off"],
      ["die Kamera", "dee KAH-meh-rah", "camera"], ["der Akku", "dehr AH-koo", "battery"],
      ["der Link", "dehr LINK", "link"], ["die Daten", "dee DAH-ten", "data"],
    ]),
    /* ---- a second pass over every topic ---- */
    V("greetings", [
      ["grüß dich", "gruess DIKH", "hello (informal, south)"],
      ["moin", "MOYN", "hi (north)"],
      ["bis später", "bis SHPAY-ter", "see you later"],
      ["bis dann", "bis DAHN", "see you then"],
      ["schönen Tag noch", "SHOE-nen tahk NOKH", "have a nice day"],
      ["gute Reise", "GOO-teh RYE-zeh", "have a good trip"],
      ["gute Besserung", "GOO-teh BES-seh-roong", "get well soon"],
      ["gleichfalls", "GLYKH-fahls", "likewise"],
      ["gern geschehen", "gehrn geh-SHAY-en", "you're welcome"],
      ["kein Problem", "kine proh-BLEHM", "no problem"],
      ["Verzeihung", "fehr-TSYE-oong", "pardon me"],
      ["natürlich", "nah-TUER-likh", "of course"],
    ]),
    V("numbers", [
      ["siebzehn", "ZEEP-tsane", "seventeen"], ["achtzehn", "AKHT-tsane", "eighteen"],
      ["neunzehn", "NOYN-tsane", "nineteen"],
      ["einundzwanzig", "INE-oont-tsvahn-tsikh", "twenty-one"],
      ["sechzig", "ZEKH-tsikh", "sixty"], ["siebzig", "ZEEP-tsikh", "seventy"],
      ["achtzig", "AKH-tsikh", "eighty"], ["neunzig", "NOYN-tsikh", "ninety"],
      ["zweihundert", "TSVYE-hoon-dert", "two hundred"],
      ["eine Million", "INE-eh mil-YOHN", "a million"],
      ["dritte", "DRIT-teh", "third"], ["das Dutzend", "dahs DOOT-sent", "dozen"],
      ["das Paar", "dahs PAHR", "pair"], ["beide", "BYE-deh", "both"],
      ["zählen", "TSAY-len", "to count"], ["das Viertel", "dahs FEER-tel", "quarter"],
    ]),
    V("colors", [
      ["dunkelgrün", "DOON-kel-gruen", "dark green"],
      ["weinrot", "VINE-roht", "burgundy"], ["cremefarben", "KREHM-far-ben", "cream-coloured"],
      ["smaragdgrün", "smah-RAHKT-gruen", "emerald green"],
      ["gestreift", "geh-SHTRIFT", "striped"], ["kariert", "kah-REERT", "checked"],
      ["einfarbig", "INE-far-bikh", "plain, one colour"],
      ["färben", "FEHR-ben", "to dye"], ["verblasst", "fehr-BLAHST", "faded"],
      ["der Farbton", "dehr FARB-tohn", "shade"], ["matt", "MAHT", "matt"],
    ]),
    V("family", [
      ["die Schwiegermutter", "dee SHVEE-ger-moo-ter", "mother-in-law"],
      ["der Schwager", "dehr SHVAH-ger", "brother-in-law"],
      ["die Schwägerin", "dee SHVAY-geh-rin", "sister-in-law"],
      ["die Enkelin", "dee EN-keh-lin", "granddaughter"],
      ["die Nichte", "dee NIKH-teh", "niece"],
      ["die Cousine", "dee koo-ZEE-neh", "cousin (f)"],
      ["der Pate", "dehr PAH-teh", "godfather"],
      ["die Patin", "dee PAH-tin", "godmother"],
      ["die Zwillinge", "dee TSVIL-lin-geh", "twins"],
      ["der Vorfahre", "dehr FOR-fah-reh", "ancestor"],
      ["die Stiefmutter", "dee SHTEEF-moo-ter", "stepmother"],
      ["erziehen", "ehr-TSEE-en", "to raise (children)"],
      ["erben", "EHR-ben", "to inherit"],
    ]),
    V("people", [
      ["der Fremde", "dehr FREM-deh", "stranger"],
      ["die Menge", "dee MEN-geh", "crowd"],
      ["der Bürger", "dehr BUER-ger", "citizen"],
      ["der Mitbewohner", "dehr MIT-beh-voh-ner", "flatmate"],
      ["das Paar", "dahs PAHR", "couple"],
      ["der Bekannte", "dehr beh-KAHN-teh", "acquaintance"],
      ["der Zeuge", "dehr TSOY-geh", "witness"],
      ["der Freiwillige", "dehr FRYE-vil-lig-eh", "volunteer"],
      ["die Gesellschaft", "dee geh-ZEL-shahft", "society"],
      ["das Publikum", "dahs POO-blee-koom", "audience"],
      ["der Spitzname", "dehr SHPITS-nah-meh", "nickname"],
      ["die Nachbarin", "dee NAKH-bah-rin", "neighbour (f)"],
    ]),
    V("pronouns", [
      ["euch", "OYKH", "you (plural, object)"],
      ["ihnen", "EE-nen", "to them"],
      ["Ihnen", "EE-nen", "to you (formal)"],
      ["meiner", "MINE-er", "mine"], ["deiner", "DINE-er", "yours"],
      ["jeder", "YAY-der", "each / everyone"],
      ["einige", "INE-ig-eh", "some"], ["mehrere", "MAY-reh-reh", "several"],
      ["irgendwer", "EER-gent-vehr", "anyone"],
      ["etwas", "ET-vahs", "something"], ["nichts", "NIKHTS", "nothing"],
      ["derselbe", "dehr-ZEL-beh", "the same one"],
      ["welcher", "VEL-kher", "which one"],
    ]),
    V("questions", [
      ["für wen?", "fuer VAYN", "for whom?"], ["mit wem?", "mit VAYM", "with whom?"],
      ["seit wann?", "zite VAHN", "since when?"],
      ["bis wann?", "bis VAHN", "until when?"],
      ["wie oft?", "vee OFT", "how often?"],
      ["worüber?", "voh-RUE-ber", "about what?"],
      ["können Sie mir helfen?", "KOEN-nen zee meer HEL-fen", "can you help me?"],
      ["wo ist die Toilette?", "voh ist dee twah-LET-teh", "where is the toilet?"],
      ["wie sagt man…?", "vee zahkt MAHN", "how do you say…?"],
      ["was bedeutet das?", "vahs beh-DOY-tet dahs", "what does that mean?"],
      ["verstehen Sie?", "fehr-SHTAY-en zee", "do you understand?"],
      ["zweifeln", "TSVYE-feln", "to doubt"],
    ]),
    V("grammar", [
      ["weder … noch", "VAY-der … NOKH", "neither … nor"],
      ["sondern", "ZON-dern", "but rather"],
      ["trotzdem", "TROTS-dehm", "nevertheless"],
      ["deshalb", "DES-hahlp", "for that reason"],
      ["trotz", "TROTS", "in spite of"],
      ["über", "UE-ber", "over / about"],
      ["neben", "NAY-ben", "next to"],
      ["gegenüber", "gay-gen-UE-ber", "opposite"],
      ["hinter", "HIN-ter", "behind"],
      ["um … herum", "oom … heh-ROOM", "around"],
      ["gegen", "GAY-gen", "against / towards"],
      ["laut", "LOWT", "according to"],
      ["obwohl", "op-VOHL", "although"],
      ["damit", "dah-MIT", "so that"],
      ["sobald", "zoh-BAHLT", "as soon as"],
      ["entweder … oder", "ENT-vay-der … OH-der", "either … or"],
    ]),
    V("adjectives", [
      ["breit", "BRITE", "wide"], ["schmal", "SHMAHL", "narrow"],
      ["dick", "DIK", "thick / fat"], ["dünn", "DUEN", "thin"],
      ["schwer", "SHVEHR", "heavy / difficult"], ["leicht", "LYKHT", "light / easy"],
      ["hart", "HART", "hard"], ["weich", "VYKH", "soft"],
      ["tief", "TEEF", "deep"], ["trocken", "TROK-ken", "dry"],
      ["nass", "NAHS", "wet"], ["süß", "ZUESS", "sweet"],
      ["salzig", "ZAHL-tsikh", "salty"], ["bitter", "BIT-ter", "bitter"],
      ["scharf", "SHARF", "spicy / sharp"], ["ruhig", "ROO-ikh", "calm"],
      ["laut", "LOWT", "loud"], ["gefährlich", "geh-FEHR-likh", "dangerous"],
      ["sicher", "ZIKH-er", "safe / certain"], ["fertig", "FEHR-tikh", "ready / finished"],
      ["böse", "BOE-zeh", "angry"], ["frei", "FRYE", "free"],
      ["beschäftigt", "beh-SHEF-tikht", "busy"], ["lustig", "LOOS-tikh", "funny"],
    ]),
    V("adverbs", [
      ["kaum", "KOWM", "hardly"], ["ziemlich", "TSEEM-likh", "quite"],
      ["vor allem", "for AH-lem", "above all"],
      ["mindestens", "MIN-des-tens", "at least"],
      ["plötzlich", "PLOETS-likh", "suddenly"],
      ["schließlich", "SHLEES-likh", "finally"],
      ["sofort", "zoh-FORT", "immediately"],
      ["selten", "ZEL-ten", "rarely"], ["oben", "OH-ben", "above / upstairs"],
      ["unten", "OON-ten", "below / downstairs"],
      ["drinnen", "DRIN-nen", "indoors"], ["draußen", "DROW-sen", "outdoors"],
      ["vorwärts", "FOR-vehrts", "forwards"], ["rückwärts", "RUEK-vehrts", "backwards"],
      ["besser", "BES-ser", "better"], ["schlimmer", "SHLIM-mer", "worse"],
      ["sorgfältig", "ZORK-fel-tikh", "carefully"],
      ["zum Glück", "tsoom GLUEK", "luckily"],
    ]),
    V("verbs", [
      ["stellen", "SHTEL-len", "to put (upright)"],
      ["legen", "LAY-gen", "to lay down"],
      ["bringen", "BRIN-gen", "to bring"], ["tragen", "TRAH-gen", "to carry / wear"],
      ["finden", "FIN-den", "to find"], ["verlieren", "fehr-LEE-ren", "to lose"],
      ["gewinnen", "geh-VIN-nen", "to win"], ["spielen", "SHPEE-len", "to play"],
      ["singen", "ZIN-gen", "to sing"], ["tanzen", "TAHN-tsen", "to dance"],
      ["kochen", "KOKH-en", "to cook"], ["putzen", "POOT-sen", "to clean"],
      ["waschen", "VAH-shen", "to wash"], ["zerbrechen", "tsehr-BREKH-en", "to break"],
      ["reparieren", "reh-pah-REE-ren", "to repair"], ["ändern", "EN-dern", "to change"],
      ["sich erinnern", "zikh ehr-IN-nern", "to remember"],
      ["vergessen", "fehr-GES-sen", "to forget"],
      ["versuchen", "fehr-ZOO-khen", "to try"], ["folgen", "FOL-gen", "to follow"],
      ["aufhören", "OWF-hoe-ren", "to stop"], ["lachen", "LAH-khen", "to laugh"],
      ["weinen", "VYE-nen", "to cry"], ["schwimmen", "SHVIM-men", "to swim"],
      ["steigen", "SHTYE-gen", "to climb"], ["aufstehen", "OWF-shtay-en", "to get up"],
      ["sich setzen", "zikh ZET-sen", "to sit down"],
      ["reden", "RAY-den", "to talk"], ["treffen", "TREF-fen", "to meet"],
    ]),
    V("food", [
      ["das Mehl", "dahs MAYL", "flour"], ["die Marmelade", "dee mar-meh-LAH-deh", "jam"],
      ["der Schinken", "dehr SHIN-ken", "ham"], ["die Wurst", "dee VOORST", "sausage"],
      ["das Brötchen", "dahs BROET-khen", "bread roll"],
      ["die Karotte", "dee kah-ROT-teh", "carrot"],
      ["die Paprika", "dee PAH-pree-kah", "pepper (vegetable)"],
      ["die Traube", "dee TROW-beh", "grape"], ["die Erdbeere", "dee EHRT-beh-reh", "strawberry"],
      ["die Zitrone", "dee tsee-TROH-neh", "lemon"],
      ["die Wassermelone", "dee VAH-ser-meh-loh-neh", "watermelon"],
      ["das Eis", "dahs ICE", "ice cream / ice"],
      ["die Serviette", "dee zehr-VYET-teh", "napkin"],
      ["das Trinkgeld", "dahs TRINK-gelt", "tip"],
      ["die Speisekarte", "dee SHPYE-zeh-kar-teh", "menu"],
      ["die Vorspeise", "dee FOR-shpye-zeh", "starter"],
      ["das Hauptgericht", "dahs HOWPT-geh-rikht", "main course"],
      ["probieren", "proh-BEE-ren", "to taste / try"],
      ["Hunger haben", "HOON-ger HAH-ben", "to be hungry"],
      ["Durst haben", "DOORST HAH-ben", "to be thirsty"],
    ]),
    V("body", [
      ["das Handgelenk", "dahs HAHNT-geh-lenk", "wrist"],
      ["der Ellbogen", "dehr EL-boh-gen", "elbow"],
      ["der Knöchel", "dehr KNOE-khel", "ankle"],
      ["die Hüfte", "dee HUEF-teh", "hip"], ["die Taille", "dee TAHL-yeh", "waist"],
      ["der Fingernagel", "dehr FIN-ger-nah-gel", "fingernail"],
      ["der Bart", "dehr BART", "beard"],
      ["die Augenbraue", "dee OW-gen-brow-eh", "eyebrow"],
      ["die Lippe", "dee LIP-peh", "lip"], ["die Kehle", "dee KAY-leh", "throat"],
      ["die Lunge", "dee LOON-geh", "lung"], ["der Muskel", "dehr MOOS-kel", "muscle"],
      ["das Gehirn", "dahs geh-HEERN", "brain"], ["die Stimme", "dee SHTIM-meh", "voice"],
      ["der Atem", "dehr AH-tem", "breath"],
    ]),
    V("health", [
      ["die Grippe", "dee GRIP-peh", "flu"], ["die Allergie", "dee ah-lehr-GEE", "allergy"],
      ["die Impfung", "dee IMP-foong", "vaccination"],
      ["das Pflaster", "dahs PFLAHS-ter", "plaster"],
      ["die Tablette", "dee tah-BLET-teh", "tablet"],
      ["der Zahnarzt", "dehr TSAHN-artst", "dentist"],
      ["die Spritze", "dee SHPRIT-seh", "injection"],
      ["übel", "UE-bel", "nauseous"], ["der Stress", "dehr SHTRESS", "stress"],
      ["husten", "HOOS-ten", "to cough"], ["niesen", "NEE-zen", "to sneeze"],
      ["behandeln", "beh-HAHN-deln", "to treat"],
      ["sich wohl fühlen", "zikh vohl FUE-len", "to feel well"],
      ["das Wartezimmer", "dahs VAR-teh-tsim-mer", "waiting room"],
      ["die Krankenkasse", "dee KRAHN-ken-kah-seh", "health insurance"],
    ]),
    V("clothing", [
      ["die Bluse", "dee BLOO-zeh", "blouse"],
      ["der Schlafanzug", "dehr SHLAHF-ahn-tsook", "pyjamas"],
      ["die Badehose", "dee BAH-deh-hoh-zeh", "swimming trunks"],
      ["die Unterwäsche", "dee OON-ter-veh-sheh", "underwear"],
      ["die Krawatte", "dee krah-VAHT-teh", "tie"],
      ["der Ring", "dehr RING", "ring"], ["die Kette", "dee KET-teh", "necklace"],
      ["die Uhr", "dee OOR", "watch / clock"],
      ["der Regenschirm", "dehr RAY-gen-shirm", "umbrella"],
      ["die Geldbörse", "dee GELT-boer-zeh", "purse"],
      ["die Baumwolle", "dee BOWM-vol-leh", "cotton"],
      ["die Wolle", "dee VOL-leh", "wool"], ["das Leder", "dahs LAY-der", "leather"],
      ["ausziehen", "OWS-tsee-en", "to take off"],
      ["anziehen", "AHN-tsee-en", "to put on"],
    ]),
    V("home", [
      ["die Decke", "dee DEK-keh", "ceiling / blanket"],
      ["der Flur", "dehr FLOOR", "hallway"],
      ["der Balkon", "dehr bahl-KOHN", "balcony"],
      ["der Schrank", "dehr SHRAHNK", "cupboard"],
      ["die Schublade", "dee SHOOP-lah-deh", "drawer"],
      ["das Regal", "dahs reh-GAHL", "shelf"],
      ["der Teppich", "dehr TEP-pikh", "carpet"],
      ["der Vorhang", "dehr FOR-hahng", "curtain"],
      ["das Kissen", "dahs KIS-sen", "pillow"],
      ["das Bettlaken", "dahs BET-lah-ken", "bed sheet"],
      ["der Herd", "dehr HEHRT", "cooker"],
      ["der Backofen", "dehr BAHK-oh-fen", "oven"],
      ["die Dusche", "dee DOO-sheh", "shower"],
      ["der Wasserhahn", "dehr VAH-ser-hahn", "tap"],
      ["der Müll", "dehr MUEL", "rubbish"],
      ["der Besen", "dehr BAY-zen", "broom"],
      ["die Steckdose", "dee SHTEK-doh-zeh", "socket"],
      ["die Waschmaschine", "dee VAHSH-mah-shee-neh", "washing machine"],
    ]),
    V("animals", [
      ["die Ente", "dee EN-teh", "duck"], ["die Gans", "dee GAHNS", "goose"],
      ["die Ziege", "dee TSEE-geh", "goat"], ["der Esel", "dehr AY-zel", "donkey"],
      ["der Fuchs", "dehr FOOKS", "fox"], ["der Hirsch", "dehr HEERSH", "deer"],
      ["das Eichhörnchen", "dahs YKH-hoern-khen", "squirrel"],
      ["die Fledermaus", "dee FLAY-der-mows", "bat"],
      ["der Wal", "dehr VAHL", "whale"], ["der Delfin", "dehr del-FEEN", "dolphin"],
      ["der Hai", "dehr HYE", "shark"], ["die Krabbe", "dee KRAHB-beh", "crab"],
      ["der Frosch", "dehr FROSH", "frog"], ["das Krokodil", "dahs kroh-koh-DEEL", "crocodile"],
      ["der Adler", "dehr AHD-ler", "eagle"], ["die Taube", "dee TOW-beh", "dove / pigeon"],
      ["die Mücke", "dee MUEK-keh", "mosquito"], ["der Schwanz", "dehr SHVAHNTS", "tail"],
      ["der Flügel", "dehr FLUE-gel", "wing"],
    ]),
    V("nature", [
      ["der Nebel", "dehr NAY-bel", "fog"], ["das Eis", "dahs ICE", "ice"],
      ["der Donner", "dehr DON-ner", "thunder"], ["der Blitz", "dehr BLITS", "lightning"],
      ["der Regenbogen", "dehr RAY-gen-boh-gen", "rainbow"],
      ["der Schatten", "dehr SHAHT-ten", "shade / shadow"],
      ["die Welle", "dee VEL-leh", "wave"], ["der Sand", "dehr ZAHNT", "sand"],
      ["der Hügel", "dehr HUE-gel", "hill"], ["das Tal", "dahs TAHL", "valley"],
      ["die Höhle", "dee HOE-leh", "cave"], ["die Wurzel", "dee VOOR-tsel", "root"],
      ["der Ast", "dehr AHST", "branch"], ["der Samen", "dehr ZAH-men", "seed"],
      ["die Umwelt", "dee OOM-velt", "the environment"],
      ["die Verschmutzung", "dee fehr-SHMOOT-soong", "pollution"],
      ["das Klima", "dahs KLEE-mah", "climate"],
    ]),
    V("places", [
      ["die Apotheke", "dee ah-poh-TAY-keh", "pharmacy"],
      ["die Metzgerei", "dee mets-geh-RYE", "butcher's"],
      ["der Supermarkt", "dehr ZOO-per-markt", "supermarket"],
      ["der Friseur", "dehr free-ZOER", "hairdresser"],
      ["die Polizeiwache", "dee poh-lee-TSYE-vah-kheh", "police station"],
      ["das Rathaus", "dahs RAHT-hows", "town hall"],
      ["das Theater", "dahs tay-AH-ter", "theatre"],
      ["das Stadion", "dahs SHTAH-dyon", "stadium"],
      ["der Strand", "dehr SHTRAHNT", "beach"],
      ["die Brücke", "dee BRUEK-keh", "bridge"],
      ["die Ecke", "dee EK-keh", "corner"],
      ["die Altstadt", "dee AHLT-shtaht", "old town"],
      ["der Marktplatz", "dehr MARKT-plahts", "market square"],
      ["das Einkaufszentrum", "dahs INE-kowfs-tsen-troom", "shopping centre"],
    ]),
    V("travel", [
      ["der Flug", "dehr FLOOK", "flight"],
      ["das Gate", "dahs GAYT", "boarding gate"],
      ["das Gleis", "dahs GLICE", "platform / track"],
      ["der Sitzplatz", "dehr ZITS-plahts", "seat"],
      ["der Schalter", "dehr SHAHL-ter", "ticket counter"],
      ["die Buchung", "dee BOO-khoong", "booking"],
      ["die Unterkunft", "dee OON-ter-koonft", "accommodation"],
      ["das Doppelzimmer", "dahs DOP-pel-tsim-mer", "double room"],
      ["der Reiseführer", "dehr RYE-zeh-fue-rer", "guidebook"],
      ["das Andenken", "dahs AHN-den-ken", "souvenir"],
      ["das Handgepäck", "dahs HAHNT-geh-pek", "hand luggage"],
      ["die Reiseversicherung", "dee RYE-zeh-fehr-zikh-eh-roong", "travel insurance"],
      ["die Tankstelle", "dee TAHNK-shtel-leh", "petrol station"],
      ["der Stau", "dehr SHTOW", "traffic jam"],
      ["mieten", "MEE-ten", "to rent"],
    ]),
    V("time", [
      ["August", "ow-GOOST", "August"], ["September", "zep-TEM-ber", "September"],
      ["Oktober", "ok-TOH-ber", "October"], ["November", "noh-VEM-ber", "November"],
      ["Dezember", "day-TSEM-ber", "December"],
      ["der Frühling", "dehr FRUE-ling", "spring"],
      ["der Herbst", "dehr HEHRPST", "autumn"],
      ["das Jahrhundert", "dahs yahr-HOON-dert", "century"],
      ["das Jahrzehnt", "dahs yahr-TSAYNT", "decade"],
      ["die Morgendämmerung", "dee MOR-gen-dem-meh-roong", "dawn"],
      ["die Dämmerung", "dee DEM-meh-roong", "dusk"],
      ["Mitternacht", "MIT-ter-nahkht", "midnight"],
      ["Mittag", "MIT-tahk", "midday"],
      ["vorgestern", "FOR-ges-tern", "the day before yesterday"],
      ["übermorgen", "UE-ber-mor-gen", "the day after tomorrow"],
      ["der Geburtstag", "dehr geh-BOORTS-tahk", "birthday"],
      ["das Datum", "dahs DAH-toom", "date"],
      ["der Fahrplan", "dehr FAHR-plahn", "timetable"],
      ["pünktlich", "PUENKT-likh", "on time"],
    ]),
    V("work", [
      ["das Vorstellungsgespräch", "dahs FOR-shtel-loongs-geh-shprekh", "job interview"],
      ["der Lebenslauf", "dehr LAY-bens-lowf", "CV"],
      ["der Mindestlohn", "dehr MIN-dest-lohn", "minimum wage"],
      ["die Arbeitszeit", "dee AR-bites-tsite", "working hours"],
      ["der Urlaub", "dehr OOR-lowp", "holiday"],
      ["die Rente", "dee REN-teh", "pension"],
      ["die Arbeitslosigkeit", "dee AR-bites-loh-zikh-kite", "unemployment"],
      ["das Budget", "dahs bue-ZHAY", "budget"],
      ["der Gewinn", "dehr geh-VIN", "profit"],
      ["der Verlust", "dehr fehr-LOOST", "loss"],
      ["der Kassenbon", "dehr KAH-sen-bohn", "receipt"],
      ["die Theke", "dehr TAY-keh", "counter"],
      ["die Krankenschwester", "dee KRAHN-ken-shves-ter", "nurse (f)"],
      ["der Koch", "dehr KOKH", "cook"],
      ["der Bauer", "dehr BOW-er", "farmer"],
      ["der Handwerker", "dehr HAHNT-vehr-ker", "tradesman"],
    ]),
    V("school", [
      ["das Klassenzimmer", "dahs KLAH-sen-tsim-mer", "classroom"],
      ["die Tafel", "dee TAH-fel", "blackboard"],
      ["der Radiergummi", "dehr rah-DEER-goo-mee", "rubber"],
      ["das Lineal", "dahs lee-nay-AHL", "ruler"],
      ["der Rucksack", "dehr ROOK-zahk", "backpack"],
      ["das Wörterbuch", "dahs VOER-ter-bookh", "dictionary"],
      ["die Übung", "dee UE-boong", "exercise"],
      ["die Notiz", "dee noh-TEETS", "note"],
      ["die Zusammenfassung", "dee tsoo-ZAH-men-fah-soong", "summary"],
      ["das Stipendium", "dahs shtee-PEN-dyoom", "scholarship"],
      ["der Abschluss", "dehr AHP-shloos", "degree / qualification"],
      ["das Fach", "dahs FAHKH", "school subject"],
      ["die Erdkunde", "dee EHRT-koon-deh", "geography"],
      ["die Kunst", "dee KOONST", "art"], ["die Musik", "dee moo-ZEEK", "music"],
      ["bestehen", "beh-SHTAY-en", "to pass (an exam)"],
      ["durchfallen", "DOORKH-fah-len", "to fail"],
      ["wiederholen", "vee-der-HOH-len", "to revise / repeat"],
    ]),
    V("tech", [
      ["der Laptop", "dehr LEP-top", "laptop"],
      ["das Tablet", "dahs TEB-let", "tablet"],
      ["der Lautsprecher", "dehr LOWT-shprekh-er", "speaker"],
      ["die Kopfhörer", "dee KOPF-hoe-rer", "headphones"],
      ["das Ladegerät", "dahs LAH-deh-geh-rayt", "charger"],
      ["der Drucker", "dehr DROOK-er", "printer"],
      ["der Benutzer", "dehr beh-NOOT-ser", "user"],
      ["das Konto", "dahs KON-toh", "account"],
      ["die Nachricht", "dee NAHKH-rikht", "message"],
      ["der Anruf", "dehr AHN-roof", "phone call"],
      ["der Touchscreen", "dehr TATCH-skreen", "touchscreen"],
      ["aktualisieren", "ahk-too-ah-lee-ZEE-ren", "to update"],
      ["installieren", "in-shtah-LEE-ren", "to install"],
      ["sich anmelden", "zikh AHN-mel-den", "to log in"],
      ["teilen", "TYE-len", "to share"],
      ["das soziale Netzwerk", "dahs zoh-TSYAH-leh NETS-vehrk", "social network"],
    ])
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["Hallo, wie geht es dir?", "HAH-loh vee GATE es DEER", "Hello, how are you?",
        [["Hallo", "HAH-loh"], ["wie", "vee"], ["geht", "GATE"], ["es", "es"], ["dir", "DEER"]]],
      ["Mir geht es sehr gut, danke", "meer gate es zehr GOOT DAHN-keh",
        "I am very well, thank you",
        [["Mir", "meer"], ["geht", "gate"], ["es", "es"], ["sehr", "zehr"], ["gut", "GOOT"], ["danke", "DAHN-keh"]]],
      ["Wie heißt du?", "vee HYSTE doo", "What is your name?",
        [["Wie", "vee"], ["heißt", "HYSTE"], ["du", "doo"]]],
      ["Ich heiße Anna", "ikh HYE-seh AH-nah", "My name is Anna",
        [["Ich", "ikh"], ["heiße", "HYE-seh"], ["Anna", "AH-nah"]]],
      ["Ich verstehe nicht", "ikh fehr-SHTEH-eh nikht", "I don't understand",
        [["Ich", "ikh"], ["verstehe", "fehr-SHTEH-eh"], ["nicht", "nikht"]]],
      ["Können Sie das wiederholen?", "KOEN-nen zee dahs vee-der-HOH-len",
        "Can you repeat that?",
        [["Können", "KOEN-nen"], ["Sie", "zee"], ["das", "dahs"], ["wiederholen", "vee-der-HOH-len"]]],
      ["Freut mich, dich kennenzulernen", "froyt mikh dikh KEN-nen-tsoo-lehr-nen",
        "Pleased to meet you",
        [["Freut", "froyt"], ["mich", "mikh"], ["dich", "dikh"], ["kennenzulernen", "KEN-nen-tsoo-lehr-nen"]]],
      ["Sprechen Sie Englisch?", "SHPREKH-en zee ENG-lish", "Do you speak English?",
        [["Sprechen", "SHPREKH-en"], ["Sie", "zee"], ["Englisch", "ENG-lish"]]],
    ]),
    S("food", [
      ["Ich möchte einen Kaffee, bitte", "ikh MOEKH-teh INE-en KAH-feh BIT-teh",
        "I would like a coffee, please",
        [["Ich", "ikh"], ["möchte", "MOEKH-teh"], ["einen", "INE-en"], ["Kaffee", "KAH-feh"], ["bitte", "BIT-teh"]]],
      ["Ich habe Hunger", "ikh HAH-beh HOON-ger", "I am hungry",
        [["Ich", "ikh"], ["habe", "HAH-beh"], ["Hunger", "HOON-ger"]]],
      ["Ich habe Durst", "ikh HAH-beh DOORST", "I am thirsty",
        [["Ich", "ikh"], ["habe", "HAH-beh"], ["Durst", "DOORST"]]],
      ["Das Essen ist lecker", "dahs ES-sen ist LEK-ker", "The food is delicious",
        [["Das", "dahs"], ["Essen", "ES-sen"], ["ist", "ist"], ["lecker", "LEK-ker"]]],
      ["Die Rechnung, bitte", "dee REKH-noong BIT-teh", "The bill, please",
        [["Die", "dee"], ["Rechnung", "REKH-noong"], ["bitte", "BIT-teh"]]],
      ["Ich esse kein Fleisch", "ikh ES-seh kine FLYSHE", "I don't eat meat",
        [["Ich", "ikh"], ["esse", "ES-seh"], ["kein", "kine"], ["Fleisch", "FLYSHE"]]],
    ]),
    S("travel", [
      ["Wo ist der Bahnhof?", "voh ist dehr BAHN-hohf", "Where is the train station?",
        [["Wo", "voh"], ["ist", "ist"], ["der", "dehr"], ["Bahnhof", "BAHN-hohf"]]],
      ["Ich möchte eine Fahrkarte nach Berlin", "ikh MOEKH-teh INE-eh FAHR-kar-teh nahkh behr-LEEN",
        "I would like a ticket to Berlin",
        [["Ich", "ikh"], ["möchte", "MOEKH-teh"], ["eine", "INE-eh"], ["Fahrkarte", "FAHR-kar-teh"], ["nach", "nahkh"], ["Berlin", "behr-LEEN"]]],
      ["Der Zug kommt um acht Uhr", "dehr tsook komt oom ahkht OOR",
        "The train comes at eight o'clock",
        [["Der", "dehr"], ["Zug", "tsook"], ["kommt", "komt"], ["um", "oom"], ["acht", "ahkht"], ["Uhr", "OOR"]]],
      ["Ich habe mich verirrt", "ikh HAH-beh mikh fehr-EERT", "I am lost",
        [["Ich", "ikh"], ["habe", "HAH-beh"], ["mich", "mikh"], ["verirrt", "fehr-EERT"]]],
      ["Biegen Sie rechts ab", "BEE-gen zee rekhts AHP", "Turn right",
        [["Biegen", "BEE-gen"], ["Sie", "zee"], ["rechts", "rekhts"], ["ab", "AHP"]]],
    ]),
    S("home", [
      ["Ich wohne in einem kleinen Haus", "ikh VOH-neh in INE-em KLINE-en HOWS",
        "I live in a small house",
        [["Ich", "ikh"], ["wohne", "VOH-neh"], ["in", "in"], ["einem", "INE-em"], ["kleinen", "KLINE-en"], ["Haus", "HOWS"]]],
      ["Die Tür ist offen", "dee tuer ist OF-fen", "The door is open",
        [["Die", "dee"], ["Tür", "tuer"], ["ist", "ist"], ["offen", "OF-fen"]]],
      ["Meine Familie ist groß", "MINE-eh fah-MEE-lyeh ist GROHS", "My family is big",
        [["Meine", "MINE-eh"], ["Familie", "fah-MEE-lyeh"], ["ist", "ist"], ["groß", "GROHS"]]],
    ]),
    S("time", [
      ["Wie spät ist es?", "vee SHPAYT ist es", "What time is it?",
        [["Wie", "vee"], ["spät", "SHPAYT"], ["ist", "ist"], ["es", "es"]]],
      ["Heute ist Montag", "HOY-teh ist MOHN-tahk", "Today is Monday",
        [["Heute", "HOY-teh"], ["ist", "ist"], ["Montag", "MOHN-tahk"]]],
      ["Morgen gehe ich zum Markt", "MOR-gen GEH-eh ikh tsoom MARKT",
        "Tomorrow I am going to the market",
        [["Morgen", "MOR-gen"], ["gehe", "GEH-eh"], ["ich", "ikh"], ["zum", "tsoom"], ["Markt", "MARKT"]]],
      ["Ich arbeite immer am Morgen", "ikh AR-bye-teh IM-mer ahm MOR-gen",
        "I always work in the morning",
        [["Ich", "ikh"], ["arbeite", "AR-bye-teh"], ["immer", "IM-mer"], ["am", "ahm"], ["Morgen", "MOR-gen"]]],
    ]),
    S("school", [
      ["Ich lerne jeden Tag Deutsch", "ikh LEHR-neh YEH-den tahk DOYTCH",
        "I learn German every day",
        [["Ich", "ikh"], ["lerne", "LEHR-neh"], ["jeden", "YEH-den"], ["Tag", "tahk"], ["Deutsch", "DOYTCH"]]],
      ["Das Buch ist sehr interessant", "dahs bookh ist zehr in-teh-res-SAHNT",
        "The book is very interesting",
        [["Das", "dahs"], ["Buch", "bookh"], ["ist", "ist"], ["sehr", "zehr"], ["interessant", "in-teh-res-SAHNT"]]],
      ["Kannst du mir helfen?", "kahnst doo meer HEL-fen", "Can you help me?",
        [["Kannst", "kahnst"], ["du", "doo"], ["mir", "meer"], ["helfen", "HEL-fen"]]],
    ]),
    S("health", [
      ["Ich habe Kopfschmerzen", "ikh HAH-beh KOPF-shmehr-tsen", "I have a headache",
        [["Ich", "ikh"], ["habe", "HAH-beh"], ["Kopfschmerzen", "KOPF-shmehr-tsen"]]],
      ["Ich brauche einen Arzt", "ikh BROW-kheh INE-en ARTST", "I need a doctor",
        [["Ich", "ikh"], ["brauche", "BROW-kheh"], ["einen", "INE-en"], ["Arzt", "ARTST"]]],
      ["Mir geht es nicht gut", "meer gate es nikht GOOT", "I don't feel well",
        [["Mir", "meer"], ["geht", "gate"], ["es", "es"], ["nicht", "nikht"], ["gut", "GOOT"]]],
    ]),
    S("work", [
      ["Was kostet das?", "vahs KOS-tet dahs", "What does that cost?",
        [["Was", "vahs"], ["kostet", "KOS-tet"], ["das", "dahs"]]],
      ["Das ist zu teuer", "dahs ist tsoo TOY-er", "That is too expensive",
        [["Das", "dahs"], ["ist", "ist"], ["zu", "tsoo"], ["teuer", "TOY-er"]]],
      ["Ich arbeite in einem Büro", "ikh AR-bye-teh in INE-em buer-OH",
        "I work in an office",
        [["Ich", "ikh"], ["arbeite", "AR-bye-teh"], ["in", "in"], ["einem", "INE-em"], ["Büro", "buer-OH"]]],
    ]),
    S("greetings", [
      ["Woher kommen Sie?", "voh-HEHR KOM-men zee", "Where do you come from?",
        [["Woher", "voh-HEHR"], ["kommen", "KOM-men"], ["Sie", "zee"]]],
      ["Ich komme aus England", "ikh KOM-meh ows ENG-lahnt", "I come from England",
        [["Ich", "ikh"], ["komme", "KOM-meh"], ["aus", "ows"], ["England", "ENG-lahnt"]]],
      ["Ich lerne Deutsch", "ikh LEHR-neh DOYTCH", "I am learning German",
        [["Ich", "ikh"], ["lerne", "LEHR-neh"], ["Deutsch", "DOYTCH"]]],
      ["Ich spreche ein bisschen Deutsch", "ikh SHPREKH-eh ine BIS-khen DOYTCH",
        "I speak a little German",
        [["Ich", "ikh"], ["spreche", "SHPREKH-eh"], ["ein", "ine"], ["bisschen", "BIS-khen"], ["Deutsch", "DOYTCH"]]],
      ["Wie sagt man das auf Deutsch?", "vee zahkt mahn dahs owf DOYTCH",
        "How do you say that in German?",
        [["Wie", "vee"], ["sagt", "zahkt"], ["man", "mahn"], ["das", "dahs"], ["auf", "owf"], ["Deutsch", "DOYTCH"]]],
    ]),
    S("food", [
      ["Was empfehlen Sie?", "vahs emp-FAY-len zee", "What do you recommend?",
        [["Was", "vahs"], ["empfehlen", "emp-FAY-len"], ["Sie", "zee"]]],
      ["Für mich einen Salat", "fuer mikh INE-en zah-LAHT", "A salad for me",
        [["Für", "fuer"], ["mich", "mikh"], ["einen", "INE-en"], ["Salat", "zah-LAHT"]]],
      ["Ich bin allergisch gegen Nüsse", "ikh bin ah-LEHR-gish GAY-gen NUE-seh",
        "I am allergic to nuts",
        [["Ich", "ikh"], ["bin", "bin"], ["allergisch", "ah-LEHR-gish"], ["gegen", "GAY-gen"], ["Nüsse", "NUE-seh"]]],
      ["Zum Wohl!", "tsoom VOHL", "Cheers / to your health",
        [["Zum", "tsoom"], ["Wohl", "VOHL"]]],
    ]),
    S("travel", [
      ["Wann fährt der Zug ab?", "vahn fehrt dehr tsook AHP",
        "When does the train depart?",
        [["Wann", "vahn"], ["fährt", "fehrt"], ["der", "dehr"], ["Zug", "tsook"], ["ab", "AHP"]]],
      ["Ist es weit von hier?", "ist es VITE fon HEER", "Is it far from here?",
        [["Ist", "ist"], ["es", "es"], ["weit", "VITE"], ["von", "fon"], ["hier", "HEER"]]],
      ["Ich möchte ein Zimmer reservieren", "ikh MOEKH-teh ine TSIM-mer reh-zehr-VEE-ren",
        "I would like to book a room",
        [["Ich", "ikh"], ["möchte", "MOEKH-teh"], ["ein", "ine"], ["Zimmer", "TSIM-mer"], ["reservieren", "reh-zehr-VEE-ren"]]],
    ]),
    S("work", [
      ["Kann ich mit Karte zahlen?", "kahn ikh mit KAR-teh TSAH-len",
        "Can I pay by card?",
        [["Kann", "kahn"], ["ich", "ikh"], ["mit", "mit"], ["Karte", "KAR-teh"], ["zahlen", "TSAH-len"]]],
      ["Ich nehme es", "ikh NAY-meh es", "I'll take it",
        [["Ich", "ikh"], ["nehme", "NAY-meh"], ["es", "es"]]],
    ]),
    S("home", [
      ["Ich wohne seit zwei Jahren hier", "ikh VOH-neh zite tsvye YAH-ren HEER",
        "I have lived here for two years",
        [["Ich", "ikh"], ["wohne", "VOH-neh"], ["seit", "zite"], ["zwei", "tsvye"], ["Jahren", "YAH-ren"], ["hier", "HEER"]]],
    ]),
    S("health", [
      ["Ich fühle mich nicht wohl", "ikh FUE-leh mikh nikht VOHL",
        "I don't feel well",
        [["Ich", "ikh"], ["fühle", "FUE-leh"], ["mich", "mikh"], ["nicht", "nikht"], ["wohl", "VOHL"]]],
    ])
  );

  /* ----------------------------- Conjugation ------------------------------
   * Perfekt (the everyday past), Präsens, and Futur I with `werden`. */
  const CONJUGATION = [
    C("sein", "ZINE", "be", [
      ["ich bin gewesen", "ikh bin geh-VEH-zen", "I was", "I", "past"],
      ["du bist gewesen", "doo bist geh-VEH-zen", "you were", "you", "past"],
      ["er ist gewesen", "ehr ist geh-VEH-zen", "he was", "he", "past"],
      ["sie ist gewesen", "zee ist geh-VEH-zen", "she was", "she", "past"],
      ["wir sind gewesen", "veer zint geh-VEH-zen", "we were", "we", "past"],
      ["sie sind gewesen", "zee zint geh-VEH-zen", "they were", "they", "past"],
      ["ich bin", "ikh BIN", "I am", "I", "present"],
      ["du bist", "doo BIST", "you are", "you", "present"],
      ["er ist", "ehr IST", "he is", "he", "present"],
      ["sie ist", "zee IST", "she is", "she", "present"],
      ["wir sind", "veer ZINT", "we are", "we", "present"],
      ["sie sind", "zee ZINT", "they are", "they", "present"],
      ["ich werde sein", "ikh VEHR-deh zine", "I will be", "I", "future"],
      ["du wirst sein", "doo virst zine", "you will be", "you", "future"],
      ["er wird sein", "ehr virt zine", "he will be", "he", "future"],
      ["wir werden sein", "veer VEHR-den zine", "we will be", "we", "future"],
      ["sie werden sein", "zee VEHR-den zine", "they will be", "they", "future"],
    ]),
    C("haben", "HAH-ben", "have", [
      ["ich habe gehabt", "ikh HAH-beh geh-HAHPT", "I had", "I", "past"],
      ["du hast gehabt", "doo hahst geh-HAHPT", "you had", "you", "past"],
      ["er hat gehabt", "ehr haht geh-HAHPT", "he had", "he", "past"],
      ["wir haben gehabt", "veer HAH-ben geh-HAHPT", "we had", "we", "past"],
      ["sie haben gehabt", "zee HAH-ben geh-HAHPT", "they had", "they", "past"],
      ["ich habe", "ikh HAH-beh", "I have", "I", "present"],
      ["du hast", "doo HAHST", "you have", "you", "present"],
      ["er hat", "ehr HAHT", "he has", "he", "present"],
      ["wir haben", "veer HAH-ben", "we have", "we", "present"],
      ["sie haben", "zee HAH-ben", "they have", "they", "present"],
      ["ich werde haben", "ikh VEHR-deh HAH-ben", "I will have", "I", "future"],
      ["du wirst haben", "doo virst HAH-ben", "you will have", "you", "future"],
      ["er wird haben", "ehr virt HAH-ben", "he will have", "he", "future"],
      ["wir werden haben", "veer VEHR-den HAH-ben", "we will have", "we", "future"],
      ["sie werden haben", "zee VEHR-den HAH-ben", "they will have", "they", "future"],
    ]),
    C("gehen", "GEH-en", "go", [
      ["ich bin gegangen", "ikh bin geh-GAHN-gen", "I went", "I", "past"],
      ["du bist gegangen", "doo bist geh-GAHN-gen", "you went", "you", "past"],
      ["er ist gegangen", "ehr ist geh-GAHN-gen", "he went", "he", "past"],
      ["wir sind gegangen", "veer zint geh-GAHN-gen", "we went", "we", "past"],
      ["sie sind gegangen", "zee zint geh-GAHN-gen", "they went", "they", "past"],
      ["ich gehe", "ikh GEH-eh", "I go", "I", "present"],
      ["du gehst", "doo GAYST", "you go", "you", "present"],
      ["er geht", "ehr GATE", "he goes", "he", "present"],
      ["wir gehen", "veer GEH-en", "we go", "we", "present"],
      ["sie gehen", "zee GEH-en", "they go", "they", "present"],
      ["ich werde gehen", "ikh VEHR-deh GEH-en", "I will go", "I", "future"],
      ["du wirst gehen", "doo virst GEH-en", "you will go", "you", "future"],
      ["er wird gehen", "ehr virt GEH-en", "he will go", "he", "future"],
      ["wir werden gehen", "veer VEHR-den GEH-en", "we will go", "we", "future"],
      ["sie werden gehen", "zee VEHR-den GEH-en", "they will go", "they", "future"],
    ]),
    C("machen", "MAH-khen", "do / make", [
      ["ich habe gemacht", "ikh HAH-beh geh-MAHKHT", "I did", "I", "past"],
      ["du hast gemacht", "doo hahst geh-MAHKHT", "you did", "you", "past"],
      ["er hat gemacht", "ehr haht geh-MAHKHT", "he did", "he", "past"],
      ["wir haben gemacht", "veer HAH-ben geh-MAHKHT", "we did", "we", "past"],
      ["sie haben gemacht", "zee HAH-ben geh-MAHKHT", "they did", "they", "past"],
      ["ich mache", "ikh MAH-kheh", "I do", "I", "present"],
      ["du machst", "doo MAHKHST", "you do", "you", "present"],
      ["er macht", "ehr MAHKHT", "he does", "he", "present"],
      ["wir machen", "veer MAH-khen", "we do", "we", "present"],
      ["sie machen", "zee MAH-khen", "they do", "they", "present"],
      ["ich werde machen", "ikh VEHR-deh MAH-khen", "I will do", "I", "future"],
      ["du wirst machen", "doo virst MAH-khen", "you will do", "you", "future"],
      ["er wird machen", "ehr virt MAH-khen", "he will do", "he", "future"],
      ["wir werden machen", "veer VEHR-den MAH-khen", "we will do", "we", "future"],
      ["sie werden machen", "zee VEHR-den MAH-khen", "they will do", "they", "future"],
    ]),
    C("sprechen", "SHPREKH-en", "speak", [
      ["ich habe gesprochen", "ikh HAH-beh geh-SHPROKH-en", "I spoke", "I", "past"],
      ["du hast gesprochen", "doo hahst geh-SHPROKH-en", "you spoke", "you", "past"],
      ["er hat gesprochen", "ehr haht geh-SHPROKH-en", "he spoke", "he", "past"],
      ["wir haben gesprochen", "veer HAH-ben geh-SHPROKH-en", "we spoke", "we", "past"],
      ["sie haben gesprochen", "zee HAH-ben geh-SHPROKH-en", "they spoke", "they", "past"],
      ["ich spreche", "ikh SHPREKH-eh", "I speak", "I", "present"],
      ["du sprichst", "doo SHPRIKHST", "you speak", "you", "present"],
      ["er spricht", "ehr SHPRIKHT", "he speaks", "he", "present"],
      ["wir sprechen", "veer SHPREKH-en", "we speak", "we", "present"],
      ["sie sprechen", "zee SHPREKH-en", "they speak", "they", "present"],
      ["ich werde sprechen", "ikh VEHR-deh SHPREKH-en", "I will speak", "I", "future"],
      ["du wirst sprechen", "doo virst SHPREKH-en", "you will speak", "you", "future"],
      ["er wird sprechen", "ehr virt SHPREKH-en", "he will speak", "he", "future"],
      ["wir werden sprechen", "veer VEHR-den SHPREKH-en", "we will speak", "we", "future"],
      ["sie werden sprechen", "zee VEHR-den SHPREKH-en", "they will speak", "they", "future"],
    ]),
    C("essen", "ES-sen", "eat", [
      ["ich habe gegessen", "ikh HAH-beh geh-GES-sen", "I ate", "I", "past"],
      ["du hast gegessen", "doo hahst geh-GES-sen", "you ate", "you", "past"],
      ["er hat gegessen", "ehr haht geh-GES-sen", "he ate", "he", "past"],
      ["wir haben gegessen", "veer HAH-ben geh-GES-sen", "we ate", "we", "past"],
      ["sie haben gegessen", "zee HAH-ben geh-GES-sen", "they ate", "they", "past"],
      ["ich esse", "ikh ES-seh", "I eat", "I", "present"],
      ["du isst", "doo IST", "you eat", "you", "present"],
      ["er isst", "ehr IST", "he eats", "he", "present"],
      ["wir essen", "veer ES-sen", "we eat", "we", "present"],
      ["sie essen", "zee ES-sen", "they eat", "they", "present"],
      ["ich werde essen", "ikh VEHR-deh ES-sen", "I will eat", "I", "future"],
      ["du wirst essen", "doo virst ES-sen", "you will eat", "you", "future"],
      ["er wird essen", "ehr virt ES-sen", "he will eat", "he", "future"],
      ["wir werden essen", "veer VEHR-den ES-sen", "we will eat", "we", "future"],
      ["sie werden essen", "zee VEHR-den ES-sen", "they will eat", "they", "future"],
    ]),
    C("kommen", "KOM-men", "come", [
      ["ich bin gekommen", "ikh bin geh-KOM-men", "I came", "I", "past"],
      ["du bist gekommen", "doo bist geh-KOM-men", "you came", "you", "past"],
      ["er ist gekommen", "ehr ist geh-KOM-men", "he came", "he", "past"],
      ["wir sind gekommen", "veer zint geh-KOM-men", "we came", "we", "past"],
      ["sie sind gekommen", "zee zint geh-KOM-men", "they came", "they", "past"],
      ["ich komme", "ikh KOM-meh", "I come", "I", "present"],
      ["du kommst", "doo KOMST", "you come", "you", "present"],
      ["er kommt", "ehr KOMT", "he comes", "he", "present"],
      ["wir kommen", "veer KOM-men", "we come", "we", "present"],
      ["sie kommen", "zee KOM-men", "they come", "they", "present"],
      ["ich werde kommen", "ikh VEHR-deh KOM-men", "I will come", "I", "future"],
      ["du wirst kommen", "doo virst KOM-men", "you will come", "you", "future"],
      ["er wird kommen", "ehr virt KOM-men", "he will come", "he", "future"],
      ["wir werden kommen", "veer VEHR-den KOM-men", "we will come", "we", "future"],
      ["sie werden kommen", "zee VEHR-den KOM-men", "they will come", "they", "future"],
    ]),
    C("sehen", "ZEH-en", "see", [
      ["ich habe gesehen", "ikh HAH-beh geh-ZEH-en", "I saw", "I", "past"],
      ["du hast gesehen", "doo hahst geh-ZEH-en", "you saw", "you", "past"],
      ["er hat gesehen", "ehr haht geh-ZEH-en", "he saw", "he", "past"],
      ["wir haben gesehen", "veer HAH-ben geh-ZEH-en", "we saw", "we", "past"],
      ["sie haben gesehen", "zee HAH-ben geh-ZEH-en", "they saw", "they", "past"],
      ["ich sehe", "ikh ZEH-eh", "I see", "I", "present"],
      ["du siehst", "doo ZEEST", "you see", "you", "present"],
      ["er sieht", "ehr ZEET", "he sees", "he", "present"],
      ["wir sehen", "veer ZEH-en", "we see", "we", "present"],
      ["sie sehen", "zee ZEH-en", "they see", "they", "present"],
      ["ich werde sehen", "ikh VEHR-deh ZEH-en", "I will see", "I", "future"],
      ["du wirst sehen", "doo virst ZEH-en", "you will see", "you", "future"],
      ["er wird sehen", "ehr virt ZEH-en", "he will see", "he", "future"],
      ["wir werden sehen", "veer VEHR-den ZEH-en", "we will see", "we", "future"],
      ["sie werden sehen", "zee VEHR-den ZEH-en", "they will see", "they", "future"],
    ]),
    C("können", "KOEN-nen", "be able to", [
      ["ich konnte", "ikh KON-teh", "I could", "I", "past"],
      ["du konntest", "doo KON-test", "you could", "you", "past"],
      ["er konnte", "ehr KON-teh", "he could", "he", "past"],
      ["wir konnten", "veer KON-ten", "we could", "we", "past"],
      ["sie konnten", "zee KON-ten", "they could", "they", "past"],
      ["ich kann", "ikh KAHN", "I can", "I", "present"],
      ["du kannst", "doo KAHNST", "you can", "you", "present"],
      ["er kann", "ehr KAHN", "he can", "he", "present"],
      ["wir können", "veer KOEN-nen", "we can", "we", "present"],
      ["sie können", "zee KOEN-nen", "they can", "they", "present"],
      ["ich werde können", "ikh VEHR-deh KOEN-nen", "I will be able to", "I", "future"],
      ["du wirst können", "doo virst KOEN-nen", "you will be able to", "you", "future"],
      ["er wird können", "ehr virt KOEN-nen", "he will be able to", "he", "future"],
      ["wir werden können", "veer VEHR-den KOEN-nen", "we will be able to", "we", "future"],
      ["sie werden können", "zee VEHR-den KOEN-nen", "they will be able to", "they", "future"],
    ]),
    C("arbeiten", "AR-bye-ten", "work", [
      ["ich habe gearbeitet", "ikh HAH-beh geh-AR-bye-tet", "I worked", "I", "past"],
      ["du hast gearbeitet", "doo hahst geh-AR-bye-tet", "you worked", "you", "past"],
      ["er hat gearbeitet", "ehr haht geh-AR-bye-tet", "he worked", "he", "past"],
      ["wir haben gearbeitet", "veer HAH-ben geh-AR-bye-tet", "we worked", "we", "past"],
      ["sie haben gearbeitet", "zee HAH-ben geh-AR-bye-tet", "they worked", "they", "past"],
      ["ich arbeite", "ikh AR-bye-teh", "I work", "I", "present"],
      ["du arbeitest", "doo AR-bye-test", "you work", "you", "present"],
      ["er arbeitet", "ehr AR-bye-tet", "he works", "he", "present"],
      ["wir arbeiten", "veer AR-bye-ten", "we work", "we", "present"],
      ["sie arbeiten", "zee AR-bye-ten", "they work", "they", "present"],
      ["ich werde arbeiten", "ikh VEHR-deh AR-bye-ten", "I will work", "I", "future"],
      ["du wirst arbeiten", "doo virst AR-bye-ten", "you will work", "you", "future"],
      ["er wird arbeiten", "ehr virt AR-bye-ten", "he will work", "he", "future"],
      ["wir werden arbeiten", "veer VEHR-den AR-bye-ten", "we will work", "we", "future"],
      ["sie werden arbeiten", "zee VEHR-den AR-bye-ten", "they will work", "they", "future"],
    ]),
    C("wissen", "VIS-sen", "know", [
      ["ich wusste", "ikh VOOS-teh", "I knew", "I", "past"],
      ["du wusstest", "doo VOOS-test", "you knew", "you", "past"],
      ["er wusste", "ehr VOOS-teh", "he knew", "he", "past"],
      ["wir wussten", "veer VOOS-ten", "we knew", "we", "past"],
      ["sie wussten", "zee VOOS-ten", "they knew", "they", "past"],
      ["ich weiß", "ikh VICE", "I know", "I", "present"],
      ["du weißt", "doo VICEST", "you know", "you", "present"],
      ["er weiß", "ehr VICE", "he knows", "he", "present"],
      ["wir wissen", "veer VIS-sen", "we know", "we", "present"],
      ["sie wissen", "zee VIS-sen", "they know", "they", "present"],
      ["ich werde wissen", "ikh VEHR-deh VIS-sen", "I will know", "I", "future"],
      ["du wirst wissen", "doo virst VIS-sen", "you will know", "you", "future"],
      ["er wird wissen", "ehr virt VIS-sen", "he will know", "he", "future"],
      ["wir werden wissen", "veer VEHR-den VIS-sen", "we will know", "we", "future"],
      ["sie werden wissen", "zee VEHR-den VIS-sen", "they will know", "they", "future"],
    ]),
    C("geben", "GAY-ben", "give", [
      ["ich habe gegeben", "ikh HAH-beh geh-GAY-ben", "I gave", "I", "past"],
      ["du hast gegeben", "doo hahst geh-GAY-ben", "you gave", "you", "past"],
      ["er hat gegeben", "ehr haht geh-GAY-ben", "he gave", "he", "past"],
      ["wir haben gegeben", "veer HAH-ben geh-GAY-ben", "we gave", "we", "past"],
      ["sie haben gegeben", "zee HAH-ben geh-GAY-ben", "they gave", "they", "past"],
      ["ich gebe", "ikh GAY-beh", "I give", "I", "present"],
      ["du gibst", "doo GEEPST", "you give", "you", "present"],
      ["er gibt", "ehr GEEPT", "he gives", "he", "present"],
      ["wir geben", "veer GAY-ben", "we give", "we", "present"],
      ["sie geben", "zee GAY-ben", "they give", "they", "present"],
      ["ich werde geben", "ikh VEHR-deh GAY-ben", "I will give", "I", "future"],
      ["du wirst geben", "doo virst GAY-ben", "you will give", "you", "future"],
      ["er wird geben", "ehr virt GAY-ben", "he will give", "he", "future"],
      ["wir werden geben", "veer VEHR-den GAY-ben", "we will give", "we", "future"],
      ["sie werden geben", "zee VEHR-den GAY-ben", "they will give", "they", "future"],
    ]),
    C("nehmen", "NAY-men", "take", [
      ["ich habe genommen", "ikh HAH-beh geh-NOM-men", "I took", "I", "past"],
      ["du hast genommen", "doo hahst geh-NOM-men", "you took", "you", "past"],
      ["er hat genommen", "ehr haht geh-NOM-men", "he took", "he", "past"],
      ["wir haben genommen", "veer HAH-ben geh-NOM-men", "we took", "we", "past"],
      ["sie haben genommen", "zee HAH-ben geh-NOM-men", "they took", "they", "past"],
      ["ich nehme", "ikh NAY-meh", "I take", "I", "present"],
      ["du nimmst", "doo NIMST", "you take", "you", "present"],
      ["er nimmt", "ehr NIMT", "he takes", "he", "present"],
      ["wir nehmen", "veer NAY-men", "we take", "we", "present"],
      ["sie nehmen", "zee NAY-men", "they take", "they", "present"],
      ["ich werde nehmen", "ikh VEHR-deh NAY-men", "I will take", "I", "future"],
      ["du wirst nehmen", "doo virst NAY-men", "you will take", "you", "future"],
      ["er wird nehmen", "ehr virt NAY-men", "he will take", "he", "future"],
      ["wir werden nehmen", "veer VEHR-den NAY-men", "we will take", "we", "future"],
      ["sie werden nehmen", "zee VEHR-den NAY-men", "they will take", "they", "future"],
    ]),
    C("finden", "FIN-den", "find", [
      ["ich habe gefunden", "ikh HAH-beh geh-FOON-den", "I found", "I", "past"],
      ["du hast gefunden", "doo hahst geh-FOON-den", "you found", "you", "past"],
      ["er hat gefunden", "ehr haht geh-FOON-den", "he found", "he", "past"],
      ["wir haben gefunden", "veer HAH-ben geh-FOON-den", "we found", "we", "past"],
      ["sie haben gefunden", "zee HAH-ben geh-FOON-den", "they found", "they", "past"],
      ["ich finde", "ikh FIN-deh", "I find", "I", "present"],
      ["du findest", "doo FIN-dest", "you find", "you", "present"],
      ["er findet", "ehr FIN-det", "he finds", "he", "present"],
      ["wir finden", "veer FIN-den", "we find", "we", "present"],
      ["sie finden", "zee FIN-den", "they find", "they", "present"],
      ["ich werde finden", "ikh VEHR-deh FIN-den", "I will find", "I", "future"],
      ["du wirst finden", "doo virst FIN-den", "you will find", "you", "future"],
      ["er wird finden", "ehr virt FIN-den", "he will find", "he", "future"],
      ["wir werden finden", "veer VEHR-den FIN-den", "we will find", "we", "future"],
      ["sie werden finden", "zee VEHR-den FIN-den", "they will find", "they", "future"],
    ]),
    C("fahren", "FAH-ren", "travel / drive", [
      ["ich bin gefahren", "ikh bin geh-FAH-ren", "I travelled", "I", "past"],
      ["du bist gefahren", "doo bist geh-FAH-ren", "you travelled", "you", "past"],
      ["er ist gefahren", "ehr ist geh-FAH-ren", "he travelled", "he", "past"],
      ["wir sind gefahren", "veer zint geh-FAH-ren", "we travelled", "we", "past"],
      ["sie sind gefahren", "zee zint geh-FAH-ren", "they travelled", "they", "past"],
      ["ich fahre", "ikh FAH-reh", "I travel", "I", "present"],
      ["du fährst", "doo FEHRST", "you travel", "you", "present"],
      ["er fährt", "ehr FEHRT", "he travels", "he", "present"],
      ["wir fahren", "veer FAH-ren", "we travel", "we", "present"],
      ["sie fahren", "zee FAH-ren", "they travel", "they", "present"],
      ["ich werde fahren", "ikh VEHR-deh FAH-ren", "I will travel", "I", "future"],
      ["du wirst fahren", "doo virst FAH-ren", "you will travel", "you", "future"],
      ["er wird fahren", "ehr virt FAH-ren", "he will travel", "he", "future"],
      ["wir werden fahren", "veer VEHR-den FAH-ren", "we will travel", "we", "future"],
      ["sie werden fahren", "zee VEHR-den FAH-ren", "they will travel", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Practice",
      l1: "Übung", l2: "macht den Meister.",
      tr1: "UE-boong", tr2: "mahkht den MICE-ter",
      en: "Practice makes the master." },
    { n: 2, chapterEn: "Timing",
      l1: "Morgenstund", l2: "hat Gold im Mund.",
      tr1: "MOR-gen-shtoont", tr2: "haht GOLT im MOONT",
      en: "The morning hour has gold in its mouth." },
    { n: 3, chapterEn: "Prudence",
      l1: "Erst denken,", l2: "dann handeln.",
      tr1: "ehrst DEN-ken", tr2: "dahn HAHN-deln",
      en: "Think first, then act." },
    { n: 4, chapterEn: "Appearances",
      l1: "Es ist nicht alles Gold,", l2: "was glänzt.",
      tr1: "es ist nikht AH-les GOLT", tr2: "vahs GLENTST",
      en: "Not everything that glitters is gold." },
    { n: 5, chapterEn: "Persistence",
      l1: "Steter Tropfen", l2: "höhlt den Stein.",
      tr1: "SHTEH-ter TROP-fen", tr2: "HOELT den SHTINE",
      en: "A steady drip hollows the stone." },
    { n: 6, chapterEn: "Company",
      l1: "Gleich und gleich", l2: "gesellt sich gern.",
      tr1: "glykh oont GLYKH", tr2: "geh-ZELT zikh GEHRN",
      en: "Like gladly keeps company with like." },
    { n: 7, chapterEn: "Prudence",
      l1: "Man soll den Tag nicht vor dem Abend", l2: "loben.",
      tr1: "mahn zol den tahk nikht for dem AH-bent", tr2: "LOH-ben",
      en: "Don't praise the day before the evening." },
    { n: 8, chapterEn: "Effort",
      l1: "Ohne Fleiß", l2: "kein Preis.",
      tr1: "OH-neh FLICE", tr2: "kine PRICE",
      en: "No diligence, no prize." },
    { n: 9, chapterEn: "Beginnings",
      l1: "Aller Anfang", l2: "ist schwer.",
      tr1: "AH-ler AHN-fahng", tr2: "ist SHVEHR",
      en: "Every beginning is hard." },
    { n: 10, chapterEn: "Necessity",
      l1: "In der Not", l2: "frisst der Teufel Fliegen.",
      tr1: "in dehr NOHT", tr2: "frist dehr TOY-fel FLEE-gen",
      en: "In need, even the devil eats flies." },
    { n: 11, chapterEn: "Prudence",
      l1: "Wer den Pfennig nicht ehrt,", l2: "ist des Talers nicht wert.",
      tr1: "vehr den PFEN-nikh nikht EHRT", tr2: "ist des TAH-lers nikht VEHRT",
      en: "Who doesn't honour the penny isn't worth the dollar." },
    { n: 12, chapterEn: "Consequence",
      l1: "Wie man sich bettet,", l2: "so liegt man.",
      tr1: "vee mahn zikh BET-tet", tr2: "zoh LEEKT mahn",
      en: "As you make your bed, so you lie in it." },
    { n: 13, chapterEn: "Company",
      l1: "Sage mir, mit wem du umgehst,", l2: "und ich sage dir, wer du bist.",
      tr1: "ZAH-geh meer mit vaym doo OOM-gayst", tr2: "oont ikh ZAH-geh deer vehr doo BIST",
      en: "Tell me who you spend time with and I'll tell you who you are." },
    { n: 14, chapterEn: "Work",
      l1: "Erst die Arbeit,", l2: "dann das Vergnügen.",
      tr1: "ehrst dee AR-bite", tr2: "dahn dahs fehr-GNUE-gen",
      en: "Work first, then pleasure." },
    { n: 15, chapterEn: "Truth",
      l1: "Lügen", l2: "haben kurze Beine.",
      tr1: "LUE-gen", tr2: "HAH-ben KOOR-tseh BYE-neh",
      en: "Lies have short legs." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("german", {
    icons: {
      alphabet: "Alphabet", greetings: "Grüße", numbers: "Zahlen", colors: "Farben",
      family: "Familie", people: "Leute", pronouns: "Pronomen", questions: "Fragen",
      grammar: "Wörtchen", adjectives: "Adjektive", adverbs: "Adverbien", verbs: "Verben",
      food: "Essen", body: "Körper", health: "Gesundheit", clothing: "Kleidung",
      home: "Zuhause", animals: "Tiere", nature: "Natur", places: "Orte",
      travel: "Reisen", time: "Zeit", work: "Arbeit", school: "Schule",
      tech: "Technik", sentences: "Sätze",
    },
    ui: { account: "Konto", progress: "Fortschritt", search: "Suche" },
    alphabet: ALPHABET,
    alphabetTitle: "Alphabet & sounds",
    alphabetLabels: ["Letters", "Sounds & spelling"],
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "Wiederholung", vocab: "Wörter", sentence: "Sätze", conjugation: "Verben",
      listening: "Hören", mixed: "Gemischt", reading: "Sprichwörter",
    },
    reading: {
      id: "sprichwoerter", title: "Proverbs", native: "Sprichwörter",
      desc: "Classic German sayings, line by line",
      blurb: "Sprichwörter — proverbs that turn up in everyday German.",
      unit: "sayings", numLabel: "Sprichwort",
      lineQuestion: "Which line completes this saying?",
      items: PROVERBS,
    },
  });
})();
