/* ============================================================================
 * Hindi course — data only.
 *
 * `ta` is the Devanagari, `tr` its transliteration (a light scholarly scheme:
 * ā ī ū ṭ ḍ ṇ ś ṣ ṛ …), `en` the English meaning. Nouns are given in their
 * dictionary form; the gender is noted where it isn't predictable.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------ Alphabet -------------------------------
   * The varṇamālā: 13 svar (vowels) with the mātrā each becomes when it
   * follows a consonant, and 33 vyañjan (consonants), each of which carries
   * an inherent "a" until a mātrā or a halant replaces it.
   * -------------------------------------------------------------------- */
  const VOWELS = A([
    ["अ", "a", "a — the inherent vowel, written with no mātrā"],
    ["आ  ा", "ā", "long a — mātrā ा, as in का (kā)"],
    ["इ  ि", "i", "short i — mātrā ि goes before, as in कि (ki)"],
    ["ई  ी", "ī", "long i — mātrā ी, as in की (kī)"],
    ["उ  ु", "u", "short u — mātrā ु below, as in कु (ku)"],
    ["ऊ  ू", "ū", "long u — mātrā ू below, as in कू (kū)"],
    ["ऋ  ृ", "ṛ", "vocalic r — mātrā ृ, as in कृ (kṛ)"],
    ["ए  े", "e", "e — mātrā े above, as in के (ke)"],
    ["ऐ  ै", "ai", "ai — mātrā ै above, as in कै (kai)"],
    ["ओ  ो", "o", "o — mātrā ो, as in को (ko)"],
    ["औ  ौ", "au", "au — mātrā ौ, as in कौ (kau)"],
    ["अं  ं", "aṃ", "anusvāra — nasalises the vowel, as in हिंदी"],
    ["अः  ः", "aḥ", "visarga — a breathed h at the end"],
    ["अँ  ँ", "am̐", "candrabindu — a nasal vowel, as in हँसना"],
    ["्", "halant", "removes the inherent a: क् is k, not ka"],
  ]);
  const CONSONANTS = A([
    ["क", "ka", "guttural — k"], ["ख", "kha", "guttural — k with a puff"],
    ["ग", "ga", "guttural — g"], ["घ", "gha", "guttural — g with a puff"],
    ["ङ", "ṅa", "guttural nasal — ng"],
    ["च", "ca", "palatal — ch"], ["छ", "cha", "palatal — ch with a puff"],
    ["ज", "ja", "palatal — j"], ["झ", "jha", "palatal — j with a puff"],
    ["ञ", "ña", "palatal nasal — ny"],
    ["ट", "ṭa", "retroflex — t, tongue curled back"],
    ["ठ", "ṭha", "retroflex — t with a puff"],
    ["ड", "ḍa", "retroflex — d"], ["ढ", "ḍha", "retroflex — d with a puff"],
    ["ण", "ṇa", "retroflex nasal — n"],
    ["त", "ta", "dental — t, tongue on the teeth"],
    ["थ", "tha", "dental — t with a puff"],
    ["द", "da", "dental — d"], ["ध", "dha", "dental — d with a puff"],
    ["न", "na", "dental nasal — n"],
    ["प", "pa", "labial — p"], ["फ", "pha", "labial — p with a puff"],
    ["ब", "ba", "labial — b"], ["भ", "bha", "labial — b with a puff"],
    ["म", "ma", "labial nasal — m"],
    ["य", "ya", "semivowel — y"], ["र", "ra", "semivowel — r"],
    ["ल", "la", "semivowel — l"], ["व", "va", "semivowel — v / w"],
    ["श", "śa", "sibilant — sh, palatal"], ["ष", "ṣa", "sibilant — sh, retroflex"],
    ["स", "sa", "sibilant — s"], ["ह", "ha", "aspirate — h"],
    ["क्ष", "kṣa", "conjunct — ksh"], ["त्र", "tra", "conjunct — tr"],
    ["ज्ञ", "jña", "conjunct — gy in modern Hindi"],
    ["ड़", "ṛa", "flapped r, a dot below ड"],
    ["ढ़", "ṛha", "flapped r with a puff"],
    ["क़", "qa", "borrowed — a deep k, from Persian"],
    ["ज़", "za", "borrowed — z"], ["फ़", "fa", "borrowed — f"],
  ]);
  const ALPHABET = { vowels: VOWELS, consonants: CONSONANTS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["नमस्ते", "namaste", "hello / goodbye"],
      ["नमस्कार", "namaskār", "greetings (formal)"],
      ["सुप्रभात", "suprabhāt", "good morning"],
      ["शुभ रात्रि", "śubh rātri", "good night"],
      ["धन्यवाद", "dhanyavād", "thank you"],
      ["शुक्रिया", "śukriyā", "thanks"],
      ["कृपया", "kṛpayā", "please"],
      ["हाँ", "hāṁ", "yes"], ["नहीं", "nahīṁ", "no"],
      ["माफ़ कीजिए", "māf kījie", "excuse me / forgive me"],
      ["क्षमा करें", "kṣamā kareṁ", "I'm sorry"],
      ["आप कैसे हैं?", "āp kaise haiṁ", "how are you?"],
      ["मैं ठीक हूँ", "maiṁ ṭhīk hūṁ", "I am fine"],
      ["ठीक है", "ṭhīk hai", "okay / all right"],
      ["स्वागत है", "svāgat hai", "welcome"],
      ["फिर मिलेंगे", "phir mileṁge", "see you again"],
      ["अलविदा", "alvidā", "farewell"],
      ["बधाई हो", "badhāī ho", "congratulations"],
      ["शुभकामनाएँ", "śubhkāmanāeṁ", "best wishes"],
      ["मिलकर खुशी हुई", "milkar khuśī huī", "pleased to meet you"],
      ["आपका नाम क्या है?", "āpkā nām kyā hai", "what is your name?"],
      ["मेरा नाम", "merā nām", "my name"],
      ["जी हाँ", "jī hāṁ", "yes (polite)"],
      ["जी नहीं", "jī nahīṁ", "no (polite)"],
      ["कोई बात नहीं", "koī bāt nahīṁ", "it's no problem"],
      ["आइए", "āie", "please come in"],
    ]),
    V("numbers", [
      ["शून्य", "śūnya", "zero"], ["एक", "ek", "one"], ["दो", "do", "two"],
      ["तीन", "tīn", "three"], ["चार", "cār", "four"], ["पाँच", "pāṁc", "five"],
      ["छह", "chah", "six"], ["सात", "sāt", "seven"], ["आठ", "āṭh", "eight"],
      ["नौ", "nau", "nine"], ["दस", "das", "ten"], ["ग्यारह", "gyārah", "eleven"],
      ["बारह", "bārah", "twelve"], ["तेरह", "terah", "thirteen"],
      ["चौदह", "caudah", "fourteen"], ["पंद्रह", "pandrah", "fifteen"],
      ["सोलह", "solah", "sixteen"], ["बीस", "bīs", "twenty"],
      ["तीस", "tīs", "thirty"], ["चालीस", "cālīs", "forty"],
      ["पचास", "pacās", "fifty"], ["सौ", "sau", "one hundred"],
      ["हज़ार", "hazār", "one thousand"], ["लाख", "lākh", "one hundred thousand"],
      ["पहला", "pahlā", "first"], ["दूसरा", "dūsrā", "second"],
      ["आख़िरी", "ākhirī", "last"], ["आधा", "ādhā", "half"],
      ["संख्या", "saṅkhyā", "number"],
    ]),
    V("colors", [
      ["लाल", "lāl", "red"], ["नीला", "nīlā", "blue"], ["हरा", "harā", "green"],
      ["पीला", "pīlā", "yellow"], ["काला", "kālā", "black"], ["सफ़ेद", "safed", "white"],
      ["भूरा", "bhūrā", "brown"], ["नारंगी", "nāraṅgī", "orange"],
      ["गुलाबी", "gulābī", "pink"], ["बैंगनी", "baiṅganī", "purple"],
      ["सुनहरा", "sunahrā", "golden"], ["चाँदी जैसा", "cāṁdī jaisā", "silver"],
      ["स्लेटी", "sleṭī", "grey"], ["हल्का", "halkā", "light (colour)"],
      ["गहरा", "gaharā", "dark / deep"], ["रंग", "raṅg", "colour"],
      ["रंगीन", "raṅgīn", "colourful"], ["चमकीला", "camkīlā", "bright / shiny"],
      ["फीका", "phīkā", "pale / faded"], ["आसमानी", "āsmānī", "sky blue"],
      ["धानी", "dhānī", "light green"],
    ]),
    V("family", [
      ["परिवार", "parivār", "family"], ["माँ", "māṁ", "mother"],
      ["पिता", "pitā", "father"], ["माता", "mātā", "mother (formal)"],
      ["बेटा", "beṭā", "son"], ["बेटी", "beṭī", "daughter"],
      ["भाई", "bhāī", "brother"], ["बहन", "bahan", "sister"],
      ["दादा", "dādā", "paternal grandfather"], ["दादी", "dādī", "paternal grandmother"],
      ["नाना", "nānā", "maternal grandfather"], ["नानी", "nānī", "maternal grandmother"],
      ["चाचा", "cācā", "paternal uncle"], ["चाची", "cācī", "paternal aunt"],
      ["मामा", "māmā", "maternal uncle"], ["मौसी", "mausī", "maternal aunt"],
      ["पति", "pati", "husband"], ["पत्नी", "patnī", "wife"],
      ["बच्चा", "baccā", "child"], ["बच्ची", "baccī", "girl child"],
      ["रिश्तेदार", "riśtedār", "relative"], ["शादी", "śādī", "wedding / marriage"],
      ["ससुर", "sasur", "father-in-law"], ["पोता", "potā", "grandson"],
      ["भतीजा", "bhatījā", "nephew"],
    ]),
    V("people", [
      ["आदमी", "ādmī", "man"], ["औरत", "aurat", "woman"],
      ["व्यक्ति", "vyakti", "person"], ["लोग", "log", "people"],
      ["लड़का", "laṛkā", "boy"], ["लड़की", "laṛkī", "girl"],
      ["दोस्त", "dost", "friend"], ["मित्र", "mitra", "friend (formal)"],
      ["पड़ोसी", "paṛosī", "neighbour"], ["मेहमान", "mehmān", "guest"],
      ["बूढ़ा", "būṛhā", "old man"], ["जवान", "javān", "young person"],
      ["बच्चे", "bacce", "children"], ["साहब", "sāhab", "sir"],
      ["मैडम", "maiḍam", "madam"], ["विदेशी", "videśī", "foreigner"],
      ["सहकर्मी", "sahkarmī", "colleague"], ["टीम", "ṭīm", "team"],
      ["समूह", "samūh", "group"], ["नाम", "nām", "name"],
      ["भीड़", "bhīṛ", "crowd"], ["इंसान", "insān", "human being"],
      ["नागरिक", "nāgrik", "citizen"],
    ]),
    V("pronouns", [
      ["मैं", "maiṁ", "I"], ["तुम", "tum", "you (familiar)"], ["आप", "āp", "you (polite)"],
      ["तू", "tū", "you (intimate)"], ["वह", "vah", "he / she / that"],
      ["यह", "yah", "this / he / she"], ["हम", "ham", "we"],
      ["वे", "ve", "they"], ["मुझे", "mujhe", "to me"], ["तुम्हें", "tumheṁ", "to you"],
      ["उसे", "use", "to him / her"], ["हमें", "hameṁ", "to us"],
      ["मेरा", "merā", "my"], ["तुम्हारा", "tumhārā", "your"],
      ["आपका", "āpkā", "your (polite)"], ["उसका", "uskā", "his / her"],
      ["हमारा", "hamārā", "our"], ["उनका", "unkā", "their"],
      ["कोई", "koī", "someone / any"], ["कुछ", "kuch", "something / some"],
      ["सब", "sab", "all / everyone"], ["ख़ुद", "khud", "oneself"],
      ["अपना", "apnā", "one's own"], ["इनका", "inkā", "of these"],
    ]),
    V("questions", [
      ["क्या", "kyā", "what"], ["कौन", "kaun", "who"], ["कहाँ", "kahāṁ", "where"],
      ["कब", "kab", "when"], ["क्यों", "kyoṁ", "why"], ["कैसे", "kaise", "how"],
      ["कैसा", "kaisā", "of what kind"], ["कितना", "kitnā", "how much"],
      ["कितने", "kitne", "how many"], ["कौन सा", "kaun sā", "which"],
      ["किसका", "kiskā", "whose"], ["कहाँ से", "kahāṁ se", "from where"],
      ["सवाल", "savāl", "question"], ["जवाब", "javāb", "answer"],
      ["पूछना", "pūchnā", "to ask"], ["बताना", "batānā", "to tell"],
      ["यह कितने का है?", "yah kitne kā hai", "how much is this?"],
      ["क्या समय हुआ है?", "kyā samay huā hai", "what time is it?"],
      ["क्या हुआ?", "kyā huā", "what happened?"],
      ["ना?", "nā", "isn't it? / right?"],
    ]),
    V("grammar", [
      ["और", "aur", "and"], ["या", "yā", "or"], ["लेकिन", "lekin", "but"],
      ["क्योंकि", "kyoṁki", "because"], ["अगर", "agar", "if"], ["तो", "to", "then"],
      ["का", "kā", "of (m)"], ["की", "kī", "of (f)"], ["के", "ke", "of (pl)"],
      ["को", "ko", "to (object marker)"], ["से", "se", "from / with"],
      ["में", "meṁ", "in"], ["पर", "par", "on / but"], ["तक", "tak", "until"],
      ["के लिए", "ke lie", "for"], ["के साथ", "ke sāth", "with"],
      ["के बिना", "ke binā", "without"], ["के बाद", "ke bād", "after"],
      ["के पहले", "ke pahle", "before"], ["के बीच", "ke bīc", "between"],
      ["भी", "bhī", "also"], ["ही", "hī", "only / emphasis"],
      ["नहीं", "nahīṁ", "not"], ["मत", "mat", "don't (command)"],
      ["फिर", "phir", "then / again"], ["इसलिए", "islie", "therefore"],
      ["जब", "jab", "when (relative)"],
    ]),
    V("adjectives", [
      ["बड़ा", "baṛā", "big"], ["छोटा", "choṭā", "small"], ["अच्छा", "acchā", "good"],
      ["बुरा", "burā", "bad"], ["नया", "nayā", "new"], ["पुराना", "purānā", "old (things)"],
      ["जवान", "javān", "young"], ["लंबा", "lambā", "long / tall"],
      ["छोटा-सा", "choṭā-sā", "tiny"], ["ऊँचा", "ūṁcā", "high"],
      ["नीचा", "nīcā", "low"], ["गरम", "garam", "hot"], ["ठंडा", "ṭhaṇḍā", "cold"],
      ["आसान", "āsān", "easy"], ["मुश्किल", "muśkil", "difficult"],
      ["सुंदर", "sundar", "beautiful"], ["बदसूरत", "badsūrat", "ugly"],
      ["मज़बूत", "mazbūt", "strong"], ["कमज़ोर", "kamzor", "weak"],
      ["तेज़", "tez", "fast / sharp"], ["धीमा", "dhīmā", "slow"],
      ["अमीर", "amīr", "rich"], ["ग़रीब", "garīb", "poor"],
      ["ख़ुश", "khuś", "happy"], ["उदास", "udās", "sad"], ["थका", "thakā", "tired"],
      ["साफ़", "sāf", "clean"], ["गंदा", "gandā", "dirty"], ["भरा", "bharā", "full"],
      ["ख़ाली", "khālī", "empty"], ["महँगा", "mahaṁgā", "expensive"],
      ["सस्ता", "sastā", "cheap"], ["ज़रूरी", "zarūrī", "important"],
    ]),
    V("adverbs", [
      ["बहुत", "bahut", "very / much"], ["थोड़ा", "thoṛā", "a little"],
      ["अच्छी तरह", "acchī tarah", "well"], ["हमेशा", "hameśā", "always"],
      ["कभी नहीं", "kabhī nahīṁ", "never"], ["कभी-कभी", "kabhī-kabhī", "sometimes"],
      ["अक्सर", "aksar", "often"], ["अब", "ab", "now"], ["आज", "āj", "today"],
      ["कल", "kal", "yesterday / tomorrow"], ["परसों", "parsoṁ", "day before / after"],
      ["जल्दी", "jaldī", "quickly / early"], ["देर से", "der se", "late"],
      ["यहाँ", "yahāṁ", "here"], ["वहाँ", "vahāṁ", "there"],
      ["पास", "pās", "near"], ["दूर", "dūr", "far"], ["साथ", "sāth", "together"],
      ["सिर्फ़", "sirf", "only"], ["शायद", "śāyad", "maybe"],
      ["पहले से", "pahle se", "already"], ["अभी", "abhī", "right now"],
      ["फिर से", "phir se", "again"], ["धीरे", "dhīre", "slowly"],
      ["लगभग", "lagbhag", "almost"], ["ज़्यादा", "zyādā", "too much / more"],
      ["सच में", "sac meṁ", "really"],
    ]),
    V("verbs", [
      ["होना", "honā", "to be"], ["करना", "karnā", "to do"],
      ["जाना", "jānā", "to go"], ["आना", "ānā", "to come"],
      ["देना", "denā", "to give"], ["लेना", "lenā", "to take"],
      ["खाना", "khānā", "to eat"], ["पीना", "pīnā", "to drink"],
      ["बोलना", "bolnā", "to speak"], ["कहना", "kahnā", "to say"],
      ["सुनना", "sunnā", "to hear"], ["देखना", "dekhnā", "to see"],
      ["पढ़ना", "paṛhnā", "to read / study"], ["लिखना", "likhnā", "to write"],
      ["समझना", "samajhnā", "to understand"], ["सोचना", "socnā", "to think"],
      ["जानना", "jānnā", "to know"], ["सीखना", "sīkhnā", "to learn"],
      ["सिखाना", "sikhānā", "to teach"], ["रहना", "rahnā", "to live / stay"],
      ["सोना", "sonā", "to sleep"], ["उठना", "uṭhnā", "to get up"],
      ["बैठना", "baiṭhnā", "to sit"], ["चलना", "calnā", "to walk / move"],
      ["दौड़ना", "dauṛnā", "to run"], ["ख़रीदना", "kharīdnā", "to buy"],
      ["बेचना", "becnā", "to sell"], ["खोलना", "kholnā", "to open"],
      ["बंद करना", "band karnā", "to close"], ["शुरू करना", "śurū karnā", "to begin"],
      ["ख़त्म करना", "khatm karnā", "to finish"], ["मदद करना", "madad karnā", "to help"],
      ["चाहना", "cāhnā", "to want"], ["मिलना", "milnā", "to meet / receive"],
      ["काम करना", "kām karnā", "to work"], ["इंतज़ार करना", "intazār karnā", "to wait"],
      ["खेलना", "khelnā", "to play"], ["बनाना", "banānā", "to make"],
    ]),
    V("food", [
      ["खाना", "khānā", "food / meal"], ["पानी", "pānī", "water"],
      ["रोटी", "roṭī", "bread / flatbread"], ["चावल", "cāval", "rice"],
      ["दाल", "dāl", "lentils"], ["सब्ज़ी", "sabzī", "vegetable / curry"],
      ["गोश्त", "gośt", "meat"], ["मुर्ग़ा", "murgā", "chicken"],
      ["मछली", "machlī", "fish"], ["अंडा", "aṇḍā", "egg"],
      ["दूध", "dūdh", "milk"], ["दही", "dahī", "yoghurt"],
      ["पनीर", "panīr", "cheese"], ["मक्खन", "makkhan", "butter"],
      ["फल", "phal", "fruit"], ["सेब", "seb", "apple"],
      ["केला", "kelā", "banana"], ["आम", "ām", "mango"],
      ["संतरा", "santrā", "orange"], ["आलू", "ālū", "potato"],
      ["टमाटर", "ṭamāṭar", "tomato"], ["प्याज़", "pyāz", "onion"],
      ["लहसुन", "lahsun", "garlic"], ["नमक", "namak", "salt"],
      ["मिर्च", "mirc", "chilli"], ["चीनी", "cīnī", "sugar"],
      ["तेल", "tel", "oil"], ["मसाला", "masālā", "spice"],
      ["चाय", "cāy", "tea"], ["कॉफ़ी", "kŏfī", "coffee"],
      ["रस", "ras", "juice"], ["मिठाई", "miṭhāī", "sweets"],
      ["नाश्ता", "nāśtā", "breakfast"], ["दोपहर का खाना", "dopahar kā khānā", "lunch"],
      ["रात का खाना", "rāt kā khānā", "dinner"], ["रेस्टोरेंट", "resṭoreṇṭ", "restaurant"],
      ["बिल", "bil", "the bill"], ["भूख", "bhūkh", "hunger"],
    ]),
    V("body", [
      ["शरीर", "śarīr", "body"], ["सिर", "sir", "head"], ["बाल", "bāl", "hair"],
      ["चेहरा", "cehrā", "face"], ["आँख", "āṁkh", "eye"], ["कान", "kān", "ear"],
      ["नाक", "nāk", "nose"], ["मुँह", "muṁh", "mouth"], ["दाँत", "dāṁt", "tooth"],
      ["जीभ", "jībh", "tongue"], ["गला", "galā", "throat / neck"],
      ["कंधा", "kandhā", "shoulder"], ["हाथ", "hāth", "hand / arm"],
      ["उँगली", "uṁglī", "finger"], ["पैर", "pair", "foot / leg"],
      ["घुटना", "ghuṭnā", "knee"], ["पीठ", "pīṭh", "back"],
      ["छाती", "chātī", "chest"], ["दिल", "dil", "heart"],
      ["पेट", "peṭ", "stomach"], ["ख़ून", "khūn", "blood"],
      ["हड्डी", "haḍḍī", "bone"], ["त्वचा", "tvacā", "skin"],
      ["दिमाग़", "dimāg", "brain / mind"],
    ]),
    V("health", [
      ["सेहत", "sehat", "health"], ["डॉक्टर", "ḍŏkṭar", "doctor"],
      ["अस्पताल", "aspatāl", "hospital"], ["दवा", "davā", "medicine"],
      ["दवाख़ाना", "davākhānā", "pharmacy"], ["बीमार", "bīmār", "ill"],
      ["स्वस्थ", "svasth", "healthy"], ["दर्द", "dard", "pain"],
      ["बुख़ार", "bukhār", "fever"], ["खाँसी", "khāṁsī", "cough"],
      ["सर्दी", "sardī", "a cold"], ["चोट", "coṭ", "injury"],
      ["नर्स", "nars", "nurse"], ["इलाज", "ilāj", "treatment"],
      ["आराम", "ārām", "rest"], ["व्यायाम", "vyāyām", "exercise"],
      ["एम्बुलेंस", "embuleṁs", "ambulance"], ["आपातकाल", "āpātkāl", "emergency"],
      ["ठीक होना", "ṭhīk honā", "to get better"],
      ["सिर दर्द", "sir dard", "headache"], ["पेट दर्द", "peṭ dard", "stomach ache"],
      ["टीका", "ṭīkā", "vaccination"],
    ]),
    V("clothing", [
      ["कपड़े", "kapṛe", "clothes"], ["कमीज़", "kamīz", "shirt"],
      ["पैंट", "paiṇṭ", "trousers"], ["साड़ी", "sāṛī", "sari"],
      ["सलवार", "salvār", "salwar (loose trousers)"], ["कुर्ता", "kurtā", "kurta (long tunic)"],
      ["धोती", "dhotī", "dhoti"], ["दुपट्टा", "dupaṭṭā", "scarf / stole"],
      ["कोट", "koṭ", "coat"], ["जैकेट", "jaikeṭ", "jacket"],
      ["स्वेटर", "sveṭar", "sweater"], ["जूता", "jūtā", "shoe"],
      ["चप्पल", "cappal", "sandal"], ["मोज़ा", "mozā", "sock"],
      ["टोपी", "ṭopī", "cap / hat"], ["दस्ताने", "dastāne", "gloves"],
      ["बेल्ट", "belṭ", "belt"], ["चश्मा", "caśmā", "glasses"],
      ["बैग", "baig", "bag"], ["गहना", "gahnā", "jewellery"],
      ["आकार", "ākār", "size"], ["पहनना", "pahannā", "to wear"],
      ["उतारना", "utārnā", "to take off"],
    ]),
    V("home", [
      ["घर", "ghar", "house / home"], ["मकान", "makān", "building / house"],
      ["कमरा", "kamrā", "room"], ["रसोई", "rasoī", "kitchen"],
      ["स्नानघर", "snānghar", "bathroom"], ["बैठक", "baiṭhak", "living room"],
      ["दरवाज़ा", "darvāzā", "door"], ["खिड़की", "khiṛkī", "window"],
      ["मेज़", "mez", "table"], ["कुर्सी", "kursī", "chair"],
      ["बिस्तर", "bistar", "bed"], ["सोफ़ा", "sofā", "sofa"],
      ["दीया", "dīyā", "lamp"], ["शीशा", "śīśā", "mirror / glass"],
      ["चाबी", "cābī", "key"], ["थाली", "thālī", "plate"],
      ["गिलास", "gilās", "glass (tumbler)"], ["कप", "kap", "cup"],
      ["चाकू", "cākū", "knife"], ["चम्मच", "cammac", "spoon"],
      ["बग़ीचा", "bagīcā", "garden"], ["सीढ़ी", "sīṛhī", "stairs / ladder"],
      ["छत", "chat", "roof / ceiling"], ["दीवार", "dīvār", "wall"],
      ["फ़र्श", "farś", "floor"], ["फ़्रिज", "frij", "fridge"],
      ["पंखा", "paṅkhā", "fan"],
    ]),
    V("animals", [
      ["जानवर", "jānvar", "animal"], ["कुत्ता", "kuttā", "dog"],
      ["बिल्ली", "billī", "cat"], ["घोड़ा", "ghoṛā", "horse"],
      ["गाय", "gāy", "cow"], ["बैल", "bail", "ox"], ["सूअर", "sūar", "pig"],
      ["बकरी", "bakrī", "goat"], ["भेड़", "bheṛ", "sheep"],
      ["मुर्ग़ी", "murgī", "hen"], ["पक्षी", "pakṣī", "bird"],
      ["चिड़िया", "ciṛiyā", "small bird"], ["मछली", "machlī", "fish"],
      ["चूहा", "cūhā", "mouse / rat"], ["ख़रगोश", "khargoś", "rabbit"],
      ["शेर", "śer", "lion"], ["बाघ", "bāgh", "tiger"],
      ["हाथी", "hāthī", "elephant"], ["बंदर", "bandar", "monkey"],
      ["भालू", "bhālū", "bear"], ["साँप", "sāṁp", "snake"],
      ["मकड़ी", "makṛī", "spider"], ["तितली", "titlī", "butterfly"],
      ["मधुमक्खी", "madhumakkhī", "bee"], ["चींटी", "cīṁṭī", "ant"],
      ["मक्खी", "makkhī", "fly"],
    ]),
    V("nature", [
      ["प्रकृति", "prakṛti", "nature"], ["सूरज", "sūraj", "sun"],
      ["चाँद", "cāṁd", "moon"], ["तारा", "tārā", "star"],
      ["आसमान", "āsmān", "sky"], ["बादल", "bādal", "cloud"],
      ["बारिश", "bāriś", "rain"], ["बर्फ़", "barf", "snow / ice"],
      ["हवा", "havā", "wind / air"], ["आग", "āg", "fire"],
      ["धरती", "dhartī", "earth"], ["मिट्टी", "miṭṭī", "soil"],
      ["समुद्र", "samudra", "sea"], ["नदी", "nadī", "river"],
      ["झील", "jhīl", "lake"], ["पहाड़", "pahāṛ", "mountain"],
      ["जंगल", "jaṅgal", "forest"], ["पेड़", "peṛ", "tree"],
      ["फूल", "phūl", "flower"], ["पत्ता", "pattā", "leaf"],
      ["घास", "ghās", "grass"], ["समुद्र तट", "samudra taṭ", "beach"],
      ["द्वीप", "dvīp", "island"], ["रेगिस्तान", "registān", "desert"],
      ["पत्थर", "patthar", "stone"], ["मौसम", "mausam", "weather"],
      ["तूफ़ान", "tūfān", "storm"],
    ]),
    V("places", [
      ["जगह", "jagah", "place"], ["शहर", "śahar", "city"],
      ["गाँव", "gāṁv", "village"], ["देश", "deś", "country"],
      ["सड़क", "saṛak", "road / street"], ["बाज़ार", "bāzār", "market"],
      ["दुकान", "dukān", "shop"], ["बैंक", "baiṅk", "bank"],
      ["स्कूल", "skūl", "school"], ["मंदिर", "mandir", "temple"],
      ["मस्जिद", "masjid", "mosque"], ["गिरजाघर", "girjāghar", "church"],
      ["संग्रहालय", "saṅgrahālay", "museum"], ["पार्क", "pārk", "park"],
      ["होटल", "hoṭal", "hotel"], ["हवाई अड्डा", "havāī aḍḍā", "airport"],
      ["स्टेशन", "sṭeśan", "station"], ["पुस्तकालय", "pustakālay", "library"],
      ["दफ़्तर", "daftar", "office"], ["सिनेमा", "sinemā", "cinema"],
      ["मोहल्ला", "mohallā", "neighbourhood"], ["अस्पताल", "aspatāl", "hospital"],
      ["सीमा", "sīmā", "border"], ["रास्ता", "rāstā", "way / path"],
    ]),
    V("travel", [
      ["यात्रा", "yātrā", "journey"], ["सफ़र", "safar", "travel"],
      ["गाड़ी", "gāṛī", "car / vehicle"], ["बस", "bas", "bus"],
      ["रेलगाड़ी", "relgāṛī", "train"], ["हवाई जहाज़", "havāī jahāz", "aeroplane"],
      ["साइकिल", "sāikil", "bicycle"], ["नाव", "nāv", "boat"],
      ["रिक्शा", "rikśā", "rickshaw"], ["टिकट", "ṭikaṭ", "ticket"],
      ["पासपोर्ट", "pāsporṭ", "passport"], ["सूटकेस", "sūṭkes", "suitcase"],
      ["सामान", "sāmān", "luggage / things"], ["नक्शा", "nakśā", "map"],
      ["रास्ता", "rāstā", "route"], ["सीधे", "sīdhe", "straight ahead"],
      ["बाएँ", "bāeṁ", "to the left"], ["दाएँ", "dāeṁ", "to the right"],
      ["आना-जाना", "ānā-jānā", "coming and going"],
      ["देर", "der", "delay"], ["पहुँचना", "pahuṁcnā", "to arrive"],
      ["निकलना", "nikalnā", "to leave / set out"],
      ["खो जाना", "kho jānā", "to get lost"], ["सीमा शुल्क", "sīmā śulk", "customs"],
    ]),
    V("time", [
      ["समय", "samay", "time"], ["घंटा", "ghaṇṭā", "hour"],
      ["मिनट", "minaṭ", "minute"], ["सेकंड", "sekaṇḍ", "second"],
      ["दिन", "din", "day"], ["हफ़्ता", "haftā", "week"],
      ["महीना", "mahīnā", "month"], ["साल", "sāl", "year"],
      ["सुबह", "subah", "morning"], ["दोपहर", "dopahar", "afternoon"],
      ["शाम", "śām", "evening"], ["रात", "rāt", "night"],
      ["सोमवार", "somvār", "Monday"], ["मंगलवार", "maṅgalvār", "Tuesday"],
      ["बुधवार", "budhvār", "Wednesday"], ["गुरुवार", "guruvār", "Thursday"],
      ["शुक्रवार", "śukravār", "Friday"], ["शनिवार", "śanivār", "Saturday"],
      ["रविवार", "ravivār", "Sunday"], ["जनवरी", "janvarī", "January"],
      ["फ़रवरी", "farvarī", "February"], ["मार्च", "mārc", "March"],
      ["अप्रैल", "aprail", "April"], ["गर्मी", "garmī", "summer / heat"],
      ["सर्दी", "sardī", "winter / cold"], ["बरसात", "barsāt", "rainy season"],
      ["घड़ी", "ghaṛī", "clock / watch"], ["तारीख़", "tārīkh", "date"],
    ]),
    V("work", [
      ["काम", "kām", "work"], ["नौकरी", "naukrī", "job"],
      ["कंपनी", "kampanī", "company"], ["मालिक", "mālik", "boss / owner"],
      ["कर्मचारी", "karmcārī", "employee"], ["तनख़्वाह", "tankhvāh", "salary"],
      ["पैसा", "paisā", "money"], ["रुपया", "rupayā", "rupee"],
      ["क़ीमत", "qīmat", "price"], ["महँगा", "mahaṁgā", "expensive"],
      ["सस्ता", "sastā", "cheap"], ["ख़रीदना", "kharīdnā", "to buy"],
      ["बेचना", "becnā", "to sell"], ["बैठक", "baiṭhak", "meeting"],
      ["ग्राहक", "grāhak", "customer"], ["बिल", "bil", "bill"],
      ["समझौता", "samjhautā", "agreement"], ["कार्ड", "kārḍ", "card"],
      ["नक़द", "naqad", "cash"], ["व्यापार", "vyāpār", "business"],
      ["इंजीनियर", "iñjīniyar", "engineer"], ["वकील", "vakīl", "lawyer"],
      ["किसान", "kisān", "farmer"], ["कमाना", "kamānā", "to earn"],
    ]),
    V("school", [
      ["स्कूल", "skūl", "school"], ["विद्यालय", "vidyālay", "school (formal)"],
      ["विश्वविद्यालय", "viśvavidyālay", "university"],
      ["कक्षा", "kakṣā", "class"], ["छात्र", "chātra", "student"],
      ["शिक्षक", "śikṣak", "teacher"], ["गुरु", "guru", "teacher / master"],
      ["किताब", "kitāb", "book"], ["कॉपी", "kŏpī", "notebook"],
      ["पेंसिल", "pensil", "pencil"], ["क़लम", "qalam", "pen"],
      ["काग़ज़", "kāgaz", "paper"], ["शब्द", "śabd", "word"],
      ["वाक्य", "vākya", "sentence"], ["पाठ", "pāṭh", "lesson"],
      ["परीक्षा", "parīkṣā", "exam"], ["गृहकार्य", "gṛhkārya", "homework"],
      ["अंक", "aṅk", "marks / number"], ["सीखना", "sīkhnā", "to learn"],
      ["पढ़ाई", "paṛhāī", "studies"], ["भाषा", "bhāṣā", "language"],
      ["इतिहास", "itihās", "history"], ["गणित", "gaṇit", "maths"],
      ["विज्ञान", "vijñān", "science"], ["ज्ञान", "jñān", "knowledge"],
    ]),
    V("tech", [
      ["कंप्यूटर", "kampyūṭar", "computer"], ["फ़ोन", "fon", "phone"],
      ["मोबाइल", "mobāil", "mobile phone"], ["स्क्रीन", "skrīn", "screen"],
      ["कीबोर्ड", "kīborḍ", "keyboard"], ["माउस", "māus", "mouse"],
      ["इंटरनेट", "iṇṭarneṭ", "internet"], ["नेटवर्क", "neṭvark", "network"],
      ["ईमेल", "īmel", "email"], ["पासवर्ड", "pāsvarḍ", "password"],
      ["फ़ाइल", "fāil", "file"], ["फ़ोल्डर", "folḍar", "folder"],
      ["ऐप", "aip", "app"], ["सॉफ़्टवेयर", "sŏfṭveyar", "software"],
      ["डाउनलोड", "ḍāunloḍ", "download"], ["अपलोड", "aploḍ", "upload"],
      ["सेव करना", "sev karnā", "to save"], ["मिटाना", "miṭānā", "to delete"],
      ["खोजना", "khojnā", "to search"], ["चालू करना", "cālū karnā", "to switch on"],
      ["बंद करना", "band karnā", "to switch off"], ["कैमरा", "kaimrā", "camera"],
      ["बैटरी", "baiṭrī", "battery"], ["लिंक", "liṅk", "link"],
      ["तकनीक", "taknīk", "technology"],
    ]),
    /* ---- a second pass over every topic ---- */
    V("greetings", [
      ["सुप्रभात हो", "suprabhāt ho", "may your morning be good"],
      ["शुभ संध्या", "śubh sandhyā", "good evening"],
      ["आपसे मिलकर अच्छा लगा", "āpse milkar acchā lagā", "it was nice to meet you"],
      ["कैसा चल रहा है?", "kaisā cal rahā hai", "how is it going?"],
      ["सब ठीक है", "sab ṭhīk hai", "everything is fine"],
      ["ध्यान रखना", "dhyān rakhnā", "take care"],
      ["शुभ यात्रा", "śubh yātrā", "have a good journey"],
      ["जल्दी ठीक हो जाओ", "jaldī ṭhīk ho jāo", "get well soon"],
      ["आपका स्वागत है", "āpkā svāgat hai", "you are welcome"],
      ["ज़रूर", "zarūr", "certainly"],
      ["माफ़ करना", "māf karnā", "forgive me (informal)"],
      ["फिर मिलते हैं", "phir milte haiṁ", "we'll meet again"],
    ]),
    V("numbers", [
      ["सत्रह", "satrah", "seventeen"], ["अठारह", "aṭhārah", "eighteen"],
      ["उन्नीस", "unnīs", "nineteen"], ["इक्कीस", "ikkīs", "twenty-one"],
      ["पच्चीस", "paccīs", "twenty-five"], ["साठ", "sāṭh", "sixty"],
      ["सत्तर", "sattar", "seventy"], ["अस्सी", "assī", "eighty"],
      ["नब्बे", "nabbe", "ninety"], ["करोड़", "karoṛ", "ten million"],
      ["तीसरा", "tīsrā", "third"], ["दर्जन", "darjan", "dozen"],
      ["जोड़ा", "joṛā", "pair"], ["दोनों", "donoṁ", "both"],
      ["गिनना", "ginnā", "to count"], ["चौथाई", "cauthāī", "a quarter"],
      ["पौने", "paune", "a quarter to"], ["सवा", "savā", "a quarter past"],
    ]),
    V("colors", [
      ["सुनहला", "sunahlā", "gold-coloured"], ["चाँदी रंग", "cāṁdī raṅg", "silver colour"],
      ["मैरून", "mairūn", "maroon"], ["क्रीम रंग", "krīm raṅg", "cream colour"],
      ["पन्ना हरा", "pannā harā", "emerald green"],
      ["धारीदार", "dhārīdār", "striped"], ["चौकोर डिज़ाइन", "caukor ḍizāin", "checked pattern"],
      ["सादा", "sādā", "plain"], ["रंगना", "raṅgnā", "to dye / to paint"],
      ["फीका पड़ना", "phīkā paṛnā", "to fade"],
      ["चमक", "camak", "shine"], ["गहरा नीला", "gaharā nīlā", "dark blue"],
    ]),
    V("family", [
      ["सास", "sās", "mother-in-law"], ["देवर", "devar", "husband's younger brother"],
      ["ननद", "nanad", "husband's sister"], ["जीजा", "jījā", "sister's husband"],
      ["भाभी", "bhābhī", "brother's wife"], ["बहू", "bahū", "daughter-in-law"],
      ["दामाद", "dāmād", "son-in-law"], ["पोती", "potī", "granddaughter"],
      ["नाती", "nātī", "daughter's son"], ["भतीजी", "bhatījī", "niece"],
      ["जुड़वाँ", "juṛvāṁ", "twins"], ["पूर्वज", "pūrvaj", "ancestor"],
      ["पालना", "pālnā", "to raise / to bring up"],
      ["विरासत", "virāsat", "inheritance"], ["सगाई", "sagāī", "engagement"],
    ]),
    V("people", [
      ["अजनबी", "ajnabī", "stranger"], ["पड़ोसन", "paṛosan", "neighbour (f)"],
      ["सहेली", "sahelī", "friend (f)"], ["मालिक", "mālik", "owner / master"],
      ["नौकर", "naukar", "servant"], ["गवाह", "gavāh", "witness"],
      ["स्वयंसेवक", "svayaṁsevak", "volunteer"], ["समाज", "samāj", "society"],
      ["दर्शक", "darśak", "spectator / audience"],
      ["उपनाम", "upnām", "nickname"], ["जनता", "jantā", "the public"],
      ["नेता", "netā", "leader"], ["साथी", "sāthī", "companion"],
      ["मेज़बान", "mezbān", "host"],
    ]),
    V("pronouns", [
      ["उन्हें", "unheṁ", "to them"], ["इन्हें", "inheṁ", "to these"],
      ["आपको", "āpko", "to you (polite)"], ["हमको", "hamko", "us (object form)"],
      ["मेरे", "mere", "my (plural / oblique)"],
      ["तेरा", "terā", "your (intimate)"],
      ["जो", "jo", "who / which (relative)"],
      ["वो वाला", "vo vālā", "that one"],
      ["इतना", "itnā", "this much"], ["उतना", "utnā", "that much"],
      ["सभी", "sabhī", "all of them"], ["दूसरा", "dūsrā", "the other one"],
      ["एक-दूसरे", "ek-dūsre", "each other"],
    ]),
    V("questions", [
      ["किसके लिए?", "kiske lie", "for whom?"],
      ["किसके साथ?", "kiske sāth", "with whom?"],
      ["कब से?", "kab se", "since when?"],
      ["कब तक?", "kab tak", "until when?"],
      ["कितनी बार?", "kitnī bār", "how many times?"],
      ["किस बारे में?", "kis bāre meṁ", "about what?"],
      ["शौचालय कहाँ है?", "śaucālay kahāṁ hai", "where is the toilet?"],
      ["इसे हिंदी में क्या कहते हैं?", "ise hindī meṁ kyā kahte haiṁ",
        "what is this called in Hindi?"],
      ["इसका मतलब क्या है?", "iskā matlab kyā hai", "what does this mean?"],
      ["आप समझे?", "āp samjhe", "did you understand?"],
      ["शक करना", "śak karnā", "to doubt"],
      ["पूछताछ", "pūchtāch", "enquiry"],
    ]),
    V("grammar", [
      ["न … न", "na … na", "neither … nor"],
      ["या तो … या", "yā to … yā", "either … or"],
      ["चूँकि", "cūṁki", "since / because"],
      ["हालाँकि", "hālāṁki", "although"],
      ["इसके बावजूद", "iske bāvjūd", "in spite of that"],
      ["के ऊपर", "ke ūpar", "above"], ["के नीचे", "ke nīce", "below"],
      ["के सामने", "ke sāmne", "in front of"],
      ["के पीछे", "ke pīche", "behind"],
      ["के पास", "ke pās", "near / with"],
      ["के अनुसार", "ke anusār", "according to"],
      ["की तरफ़", "kī taraf", "towards"],
      ["जैसे ही", "jaise hī", "as soon as"],
      ["ताकि", "tāki", "so that"],
      ["वरना", "varnā", "otherwise"],
    ]),
    V("adjectives", [
      ["चौड़ा", "cauṛā", "wide"], ["सँकरा", "saṁkarā", "narrow"],
      ["मोटा", "moṭā", "thick / fat"], ["पतला", "patlā", "thin"],
      ["भारी", "bhārī", "heavy"], ["हल्का", "halkā", "light (weight)"],
      ["सख़्त", "sakht", "hard / strict"], ["नरम", "naram", "soft"],
      ["गहरा", "gaharā", "deep"], ["सूखा", "sūkhā", "dry"],
      ["गीला", "gīlā", "wet"], ["मीठा", "mīṭhā", "sweet"],
      ["नमकीन", "namkīn", "salty"], ["कड़वा", "kaṛvā", "bitter"],
      ["तीखा", "tīkhā", "spicy"], ["शांत", "śānt", "calm"],
      ["शोरगुल वाला", "śorgul vālā", "noisy"],
      ["ख़तरनाक", "khatarnāk", "dangerous"], ["सुरक्षित", "surakṣit", "safe"],
      ["तैयार", "taiyār", "ready"], ["नाराज़", "nārāz", "angry"],
      ["खाली समय वाला", "khālī samay vālā", "free (having time)"],
      ["व्यस्त", "vyast", "busy"], ["मशहूर", "maśhūr", "famous"],
    ]),
    V("adverbs", [
      ["मुश्किल से", "muśkil se", "hardly"],
      ["काफ़ी", "kāfī", "quite / enough"],
      ["ख़ासकर", "khāskar", "especially"],
      ["कम से कम", "kam se kam", "at least"],
      ["अचानक", "acānak", "suddenly"],
      ["आख़िरकार", "ākhirkār", "finally"],
      ["तुरंत", "turant", "immediately"],
      ["शायद ही", "śāyad hī", "rarely"],
      ["ऊपर", "ūpar", "up / above"], ["नीचे", "nīce", "down / below"],
      ["अंदर", "andar", "inside"], ["बाहर", "bāhar", "outside"],
      ["आगे", "āge", "ahead"], ["पीछे", "pīche", "behind"],
      ["बेहतर", "behtar", "better"], ["बदतर", "badtar", "worse"],
      ["ध्यान से", "dhyān se", "carefully"],
      ["ख़ुशक़िस्मती से", "khuśqismatī se", "luckily"],
    ]),
    V("verbs", [
      ["रखना", "rakhnā", "to put / keep"], ["लाना", "lānā", "to bring"],
      ["ले जाना", "le jānā", "to take away"], ["ढूँढ़ना", "ḍhūṁṛhnā", "to search for"],
      ["खोना", "khonā", "to lose"], ["जीतना", "jītnā", "to win"],
      ["गाना", "gānā", "to sing"], ["नाचना", "nācnā", "to dance"],
      ["पकाना", "pakānā", "to cook"], ["साफ़ करना", "sāf karnā", "to clean"],
      ["धोना", "dhonā", "to wash"], ["तोड़ना", "toṛnā", "to break"],
      ["ठीक करना", "ṭhīk karnā", "to fix"], ["बदलना", "badalnā", "to change"],
      ["याद रखना", "yād rakhnā", "to remember"], ["भूलना", "bhūlnā", "to forget"],
      ["कोशिश करना", "kośiś karnā", "to try"],
      ["रुकना", "ruknā", "to stop / wait"], ["हँसना", "haṁsnā", "to laugh"],
      ["रोना", "ronā", "to cry"], ["तैरना", "tairnā", "to swim"],
      ["चलाना", "calānā", "to drive / operate"],
      ["चढ़ना", "caṛhnā", "to climb"], ["उतरना", "utarnā", "to get down"],
      ["उधार लेना", "udhār lenā", "to borrow"],
      ["भेजना", "bhejnā", "to send"], ["दिखाना", "dikhānā", "to show"],
      ["बुलाना", "bulānā", "to call / invite"],
    ]),
    V("food", [
      ["आटा", "āṭā", "flour"],
      ["सब्ज़ी मंडी", "sabzī maṇḍī", "vegetable market"],
      ["परांठा", "parāṁṭhā", "flatbread fried with ghee"],
      ["समोसा", "samosā", "samosa"], ["पकौड़ा", "pakauṛā", "fritter"],
      ["गाजर", "gājar", "carrot"], ["पालक", "pālak", "spinach"],
      ["भिंडी", "bhiṇḍī", "okra"], ["मटर", "maṭar", "peas"],
      ["अंगूर", "aṅgūr", "grapes"], ["अनार", "anār", "pomegranate"],
      ["नींबू", "nīṁbū", "lemon"], ["तरबूज़", "tarbūz", "watermelon"],
      ["हल्दी", "haldī", "turmeric"], ["जीरा", "jīrā", "cumin"],
      ["धनिया", "dhaniyā", "coriander"], ["अदरक", "adrak", "ginger"],
      ["घी", "ghī", "clarified butter"], ["लस्सी", "lassī", "yoghurt drink"],
      ["अचार", "acār", "pickle"], ["चटनी", "caṭnī", "chutney"],
      ["थाली", "thālī", "a plate meal"], ["स्वादिष्ट", "svādiṣṭ", "delicious"],
      ["चखना", "cakhnā", "to taste"],
    ]),
    V("body", [
      ["कलाई", "kalāī", "wrist"], ["कोहनी", "kohnī", "elbow"],
      ["टख़ना", "ṭakhnā", "ankle"], ["कमर", "kamar", "waist / lower back"],
      ["नाख़ून", "nākhūn", "nail"], ["दाढ़ी", "dāṛhī", "beard"],
      ["मूँछ", "mūṁch", "moustache"], ["भौं", "bhauṁ", "eyebrow"],
      ["होंठ", "hoṁṭh", "lip"], ["फेफड़ा", "phephṛā", "lung"],
      ["मांसपेशी", "māṁspeśī", "muscle"], ["आवाज़", "āvāz", "voice"],
      ["साँस", "sāṁs", "breath"], ["उँगलियाँ", "uṁgliyāṁ", "fingers"],
      ["एड़ी", "eṛī", "heel"],
    ]),
    V("health", [
      ["फ़्लू", "flū", "flu"], ["एलर्जी", "elarjī", "allergy"],
      ["टीकाकरण", "ṭīkākaraṇ", "immunisation programme"], ["पट्टी", "paṭṭī", "bandage"],
      ["गोली", "golī", "tablet"], ["सिरप", "sirap", "syrup"],
      ["दाँतों का डॉक्टर", "dāṁtoṁ kā ḍŏkṭar", "dentist"],
      ["इंजेक्शन", "iñjekśan", "injection"],
      ["चक्कर आना", "cakkar ānā", "to feel dizzy"],
      ["तनाव", "tanāv", "stress"], ["खाँसना", "khāṁsnā", "to cough"],
      ["छींकना", "chīṁknā", "to sneeze"], ["इलाज करना", "ilāj karnā", "to treat"],
      ["स्वस्थ रहना", "svasth rahnā", "to stay healthy"],
      ["मरीज़", "marīz", "patient"], ["लक्षण", "lakṣaṇ", "symptom"],
    ]),
    V("clothing", [
      ["लहँगा", "lahaṁgā", "long skirt worn at weddings"],
      ["शेरवानी", "śervānī", "long formal coat"],
      ["पजामा", "pajāmā", "loose trousers"],
      ["अंडरवियर", "aṇḍarviyar", "underwear"],
      ["स्कार्फ़", "skārf", "scarf"], ["अंगूठी", "aṁgūṭhī", "ring"],
      ["हार", "hār", "necklace"], ["चूड़ी", "cūṛī", "bangle"],
      ["घड़ी", "ghaṛī", "watch"], ["छाता", "chātā", "umbrella"],
      ["बटुआ", "baṭuā", "wallet"], ["सूती", "sūtī", "made of cotton"],
      ["ऊन", "ūn", "wool"], ["चमड़ा", "camṛā", "leather"],
      ["रेशम", "reśam", "silk"], ["बटन", "baṭan", "button"],
    ]),
    V("home", [
      ["गलियारा", "galiyārā", "corridor"], ["बालकनी", "bālkanī", "balcony"],
      ["अलमारी", "almārī", "cupboard / wardrobe"],
      ["दराज़", "darāz", "drawer"], ["शेल्फ़", "śelf", "shelf"],
      ["कालीन", "kālīn", "carpet"], ["पर्दा", "pardā", "curtain"],
      ["तकिया", "takiyā", "pillow"], ["कंबल", "kambal", "blanket"],
      ["चादर", "cādar", "bed sheet"], ["चूल्हा", "cūlhā", "stove"],
      ["ओवन", "ovan", "oven"], ["नल", "nal", "tap"],
      ["कचरा", "kacrā", "rubbish"], ["झाड़ू", "jhāṛū", "broom"],
      ["स्विच", "svic", "switch"], ["बाल्टी", "bālṭī", "bucket"],
      ["आँगन", "āṁgan", "courtyard"],
    ]),
    V("animals", [
      ["बत्तख़", "battakh", "duck"], ["हंस", "haṁs", "swan"],
      ["गधा", "gadhā", "donkey"], ["ऊँट", "ūṁṭ", "camel"],
      ["लोमड़ी", "lomṛī", "fox"], ["हिरण", "hiraṇ", "deer"],
      ["गिलहरी", "gilahrī", "squirrel"], ["चमगादड़", "camgādaṛ", "bat"],
      ["व्हेल", "vhel", "whale"], ["मगरमच्छ", "magarmacch", "crocodile"],
      ["मेंढक", "meṁḍhak", "frog"], ["कछुआ", "kachuā", "tortoise"],
      ["बाज़", "bāz", "hawk"], ["कबूतर", "kabūtar", "pigeon"],
      ["कौआ", "kauā", "crow"], ["मोर", "mor", "peacock"],
      ["तोता", "totā", "parrot"], ["मच्छर", "macchar", "mosquito"],
      ["पूँछ", "pūṁch", "tail"], ["पंख", "paṅkh", "wing / feather"],
    ]),
    V("nature", [
      ["कोहरा", "koharā", "fog"], ["ओस", "os", "dew"],
      ["गरज", "garaj", "thunder"], ["बिजली", "bijlī", "lightning / electricity"],
      ["इंद्रधनुष", "indradhanuṣ", "rainbow"], ["छाया", "chāyā", "shade"],
      ["लहर", "lahar", "wave"], ["रेत", "ret", "sand"],
      ["पहाड़ी", "pahāṛī", "hill"], ["घाटी", "ghāṭī", "valley"],
      ["गुफा", "guphā", "cave"], ["जड़", "jaṛ", "root"],
      ["शाखा", "śākhā", "branch"], ["बीज", "bīj", "seed"],
      ["पर्यावरण", "paryāvaraṇ", "the environment"],
      ["प्रदूषण", "pradūṣaṇ", "pollution"], ["जलवायु", "jalvāyu", "climate"],
      ["मानसून", "mānsūn", "monsoon"],
    ]),
    V("places", [
      ["दवा की दुकान", "davā kī dukān", "chemist's shop"],
      ["नाई की दुकान", "nāī kī dukān", "barber's shop"],
      ["थाना", "thānā", "police station"],
      ["नगर निगम", "nagar nigam", "municipal office"],
      ["रंगमंच", "raṅgmañc", "theatre"],
      ["स्टेडियम", "sṭeḍiyam", "stadium"],
      ["पुल", "pul", "bridge"], ["कोना", "konā", "corner"],
      ["पुराना शहर", "purānā śahar", "old city"],
      ["चौक", "cauk", "town square / crossroads"],
      ["गुरुद्वारा", "gurudvārā", "gurdwara"],
      ["घाट", "ghāṭ", "steps down to a river"],
      ["किला", "kilā", "fort"], ["मॉल", "mŏl", "shopping mall"],
    ]),
    V("travel", [
      ["उड़ान", "uṛān", "flight"], ["प्लेटफ़ॉर्म", "pleṭfŏrm", "platform"],
      ["सीट", "sīṭ", "seat"], ["खिड़की वाली सीट", "khiṛkī vālī sīṭ", "window seat"],
      ["बुकिंग", "bukiṅg", "booking"], ["ठहरने की जगह", "ṭhaharne kī jagah", "accommodation"],
      ["डबल कमरा", "ḍabal kamrā", "double room"],
      ["गाइड", "gāiḍ", "guide"], ["स्मृति चिह्न", "smṛti cihn", "souvenir"],
      ["हाथ का सामान", "hāth kā sāmān", "hand luggage"],
      ["बीमा", "bīmā", "insurance"],
      ["पेट्रोल पंप", "peṭrol paṁp", "petrol station"],
      ["जाम", "jām", "traffic jam"], ["किराया", "kirāyā", "fare / rent"],
      ["वापसी टिकट", "vāpsī ṭikaṭ", "return ticket"],
    ]),
    V("time", [
      ["मई", "maī", "May"], ["जून", "jūn", "June"], ["जुलाई", "julāī", "July"],
      ["अगस्त", "agast", "August"], ["सितंबर", "sitambar", "September"],
      ["अक्टूबर", "akṭūbar", "October"], ["नवंबर", "navambar", "November"],
      ["दिसंबर", "disambar", "December"],
      ["वसंत", "vasant", "spring"], ["शरद", "śarad", "autumn"],
      ["सदी", "sadī", "century"], ["दशक", "daśak", "decade"],
      ["भोर", "bhor", "dawn"], ["शाम ढलना", "śām ḍhalnā", "dusk"],
      ["आधी रात", "ādhī rāt", "midnight"], ["दोपहर बारह बजे", "dopahar bārah baje", "midday"],
      ["जन्मदिन", "janmadin", "birthday"], ["समय सारणी", "samay sāraṇī", "timetable"],
      ["समय पर", "samay par", "on time"], ["त्योहार", "tyohār", "festival"],
    ]),
    V("work", [
      ["इंटरव्यू", "iṇṭarvyū", "interview"], ["बायोडाटा", "bāyoḍāṭā", "CV"],
      ["ओवरटाइम", "ovarṭāim", "overtime"], ["छुट्टी", "chuṭṭī", "holiday / leave"],
      ["सेवानिवृत्ति", "sevānivṛtti", "retirement"],
      ["बेरोज़गारी", "berozgārī", "unemployment"],
      ["बजट", "bajaṭ", "budget"], ["मुनाफ़ा", "munāfā", "profit"],
      ["नुक़सान", "nuqsān", "loss"], ["रसीद", "rasīd", "receipt"],
      ["काउंटर", "kāuṇṭar", "counter"], ["नर्स", "nars", "nurse"],
      ["रसोइया", "rasoiyā", "cook"], ["दुकानदार", "dukāndār", "shopkeeper"],
      ["मज़दूर", "mazdūr", "labourer"], ["वेतन", "vetan", "monthly pay"],
      ["छूट", "chūṭ", "discount"], ["कर", "kar", "tax"],
    ]),
    V("school", [
      ["कक्षा का कमरा", "kakṣā kā kamrā", "classroom"],
      ["ब्लैकबोर्ड", "blaikborḍ", "blackboard"], ["रबर", "rabar", "rubber"],
      ["स्केल", "skel", "ruler"], ["बस्ता", "bastā", "school bag"],
      ["शब्दकोश", "śabdakoś", "dictionary"], ["अभ्यास", "abhyās", "practice"],
      ["नोट्स", "noṭs", "notes"], ["सारांश", "sārāṁś", "summary"],
      ["छात्रवृत्ति", "chātravṛtti", "scholarship"], ["डिग्री", "ḍigrī", "degree"],
      ["विषय", "viṣay", "subject"], ["भूगोल", "bhūgol", "geography"],
      ["कला", "kalā", "art"], ["संगीत", "saṅgīt", "music"],
      ["पास होना", "pās honā", "to pass"], ["फ़ेल होना", "fel honā", "to fail"],
      ["दोहराना", "dohrānā", "to revise / repeat"],
    ]),
    V("tech", [
      ["लैपटॉप", "laipṭŏp", "laptop"], ["टैबलेट", "ṭaibleṭ", "tablet"],
      ["स्पीकर", "spīkar", "speaker"], ["हेडफ़ोन", "heḍfon", "headphones"],
      ["चार्जर", "cārjar", "charger"], ["प्रिंटर", "priṇṭar", "printer"],
      ["उपयोगकर्ता", "upyogkartā", "user"], ["खाता", "khātā", "account"],
      ["संदेश", "sandeś", "message"], ["कॉल", "kŏl", "call"],
      ["टचस्क्रीन", "ṭacskrīn", "touchscreen"],
      ["अपडेट करना", "apḍeṭ karnā", "to update"],
      ["इंस्टॉल करना", "insṭŏl karnā", "to install"],
      ["जुड़ना", "juṛnā", "to connect"], ["साझा करना", "sājhā karnā", "to share"],
      ["सोशल मीडिया", "sośal mīḍiyā", "social media"],
      ["डेटा", "ḍeṭā", "data"], ["ऑनलाइन", "ŏnlāin", "online"],
    ])
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["नमस्ते, आप कैसे हैं?", "namaste, āp kaise haiṁ", "Hello, how are you?",
        [["नमस्ते", "namaste"], ["आप", "āp"], ["कैसे", "kaise"], ["हैं", "haiṁ"]]],
      ["मैं ठीक हूँ, धन्यवाद", "maiṁ ṭhīk hūṁ, dhanyavād", "I am fine, thank you",
        [["मैं", "maiṁ"], ["ठीक", "ṭhīk"], ["हूँ", "hūṁ"], ["धन्यवाद", "dhanyavād"]]],
      ["आपका नाम क्या है?", "āpkā nām kyā hai", "What is your name?",
        [["आपका", "āpkā"], ["नाम", "nām"], ["क्या", "kyā"], ["है", "hai"]]],
      ["मेरा नाम राहुल है", "merā nām rāhul hai", "My name is Rahul",
        [["मेरा", "merā"], ["नाम", "nām"], ["राहुल", "rāhul"], ["है", "hai"]]],
      ["मुझे समझ नहीं आया", "mujhe samajh nahīṁ āyā", "I didn't understand",
        [["मुझे", "mujhe"], ["समझ", "samajh"], ["नहीं", "nahīṁ"], ["आया", "āyā"]]],
      ["कृपया फिर से कहिए", "kṛpayā phir se kahie", "Please say it again",
        [["कृपया", "kṛpayā"], ["फिर", "phir"], ["से", "se"], ["कहिए", "kahie"]]],
      ["क्या आप अंग्रेज़ी बोलते हैं?", "kyā āp aṅgrezī bolte haiṁ", "Do you speak English?",
        [["क्या", "kyā"], ["आप", "āp"], ["अंग्रेज़ी", "aṅgrezī"], ["बोलते", "bolte"], ["हैं", "haiṁ"]]],
      ["आपसे मिलकर खुशी हुई", "āpse milkar khuśī huī", "Pleased to meet you",
        [["आपसे", "āpse"], ["मिलकर", "milkar"], ["खुशी", "khuśī"], ["हुई", "huī"]]],
    ]),
    S("food", [
      ["मुझे पानी चाहिए", "mujhe pānī cāhie", "I want water",
        [["मुझे", "mujhe"], ["पानी", "pānī"], ["चाहिए", "cāhie"]]],
      ["मुझे भूख लगी है", "mujhe bhūkh lagī hai", "I am hungry",
        [["मुझे", "mujhe"], ["भूख", "bhūkh"], ["लगी", "lagī"], ["है", "hai"]]],
      ["एक चाय दीजिए", "ek cāy dījie", "Please give me a tea",
        [["एक", "ek"], ["चाय", "cāy"], ["दीजिए", "dījie"]]],
      ["खाना बहुत स्वादिष्ट है", "khānā bahut svādiṣṭ hai", "The food is very tasty",
        [["खाना", "khānā"], ["बहुत", "bahut"], ["स्वादिष्ट", "svādiṣṭ"], ["है", "hai"]]],
      ["मैं मांस नहीं खाता", "maiṁ māṁs nahīṁ khātā", "I don't eat meat",
        [["मैं", "maiṁ"], ["मांस", "māṁs"], ["नहीं", "nahīṁ"], ["खाता", "khātā"]]],
      ["बिल लाइए", "bil lāie", "Please bring the bill",
        [["बिल", "bil"], ["लाइए", "lāie"]]],
    ]),
    S("travel", [
      ["स्टेशन कहाँ है?", "sṭeśan kahāṁ hai", "Where is the station?",
        [["स्टेशन", "sṭeśan"], ["कहाँ", "kahāṁ"], ["है", "hai"]]],
      ["मुझे दिल्ली का टिकट चाहिए", "mujhe dillī kā ṭikaṭ cāhie",
        "I want a ticket to Delhi",
        [["मुझे", "mujhe"], ["दिल्ली", "dillī"], ["का", "kā"], ["टिकट", "ṭikaṭ"], ["चाहिए", "cāhie"]]],
      ["रेलगाड़ी आठ बजे आती है", "relgāṛī āṭh baje ātī hai", "The train comes at eight",
        [["रेलगाड़ी", "relgāṛī"], ["आठ", "āṭh"], ["बजे", "baje"], ["आती", "ātī"], ["है", "hai"]]],
      ["मैं रास्ता भूल गया", "maiṁ rāstā bhūl gayā", "I have lost my way",
        [["मैं", "maiṁ"], ["रास्ता", "rāstā"], ["भूल", "bhūl"], ["गया", "gayā"]]],
      ["दाएँ मुड़िए", "dāeṁ muṛie", "Turn right",
        [["दाएँ", "dāeṁ"], ["मुड़िए", "muṛie"]]],
    ]),
    S("home", [
      ["मैं एक छोटे घर में रहता हूँ", "maiṁ ek choṭe ghar meṁ rahtā hūṁ",
        "I live in a small house",
        [["मैं", "maiṁ"], ["एक", "ek"], ["छोटे", "choṭe"], ["घर", "ghar"], ["में", "meṁ"], ["रहता", "rahtā"], ["हूँ", "hūṁ"]]],
      ["दरवाज़ा खुला है", "darvāzā khulā hai", "The door is open",
        [["दरवाज़ा", "darvāzā"], ["खुला", "khulā"], ["है", "hai"]]],
      ["मेरा परिवार बड़ा है", "merā parivār baṛā hai", "My family is big",
        [["मेरा", "merā"], ["परिवार", "parivār"], ["बड़ा", "baṛā"], ["है", "hai"]]],
    ]),
    S("time", [
      ["क्या समय हुआ है?", "kyā samay huā hai", "What time is it?",
        [["क्या", "kyā"], ["समय", "samay"], ["हुआ", "huā"], ["है", "hai"]]],
      ["आज सोमवार है", "āj somvār hai", "Today is Monday",
        [["आज", "āj"], ["सोमवार", "somvār"], ["है", "hai"]]],
      ["कल मैं बाज़ार जाऊँगा", "kal maiṁ bāzār jāūṁgā", "Tomorrow I will go to the market",
        [["कल", "kal"], ["मैं", "maiṁ"], ["बाज़ार", "bāzār"], ["जाऊँगा", "jāūṁgā"]]],
      ["मैं हमेशा सुबह काम करता हूँ", "maiṁ hameśā subah kām kartā hūṁ",
        "I always work in the morning",
        [["मैं", "maiṁ"], ["हमेशा", "hameśā"], ["सुबह", "subah"], ["काम", "kām"], ["करता", "kartā"], ["हूँ", "hūṁ"]]],
    ]),
    S("school", [
      ["मैं रोज़ हिंदी पढ़ता हूँ", "maiṁ roz hindī paṛhtā hūṁ", "I study Hindi every day",
        [["मैं", "maiṁ"], ["रोज़", "roz"], ["हिंदी", "hindī"], ["पढ़ता", "paṛhtā"], ["हूँ", "hūṁ"]]],
      ["यह किताब बहुत अच्छी है", "yah kitāb bahut acchī hai", "This book is very good",
        [["यह", "yah"], ["किताब", "kitāb"], ["बहुत", "bahut"], ["अच्छी", "acchī"], ["है", "hai"]]],
      ["क्या आप मेरी मदद कर सकते हैं?", "kyā āp merī madad kar sakte haiṁ",
        "Can you help me?",
        [["क्या", "kyā"], ["आप", "āp"], ["मेरी", "merī"], ["मदद", "madad"], ["कर", "kar"], ["सकते", "sakte"], ["हैं", "haiṁ"]]],
    ]),
    S("health", [
      ["मेरे सिर में दर्द है", "mere sir meṁ dard hai", "I have a headache",
        [["मेरे", "mere"], ["सिर", "sir"], ["में", "meṁ"], ["दर्द", "dard"], ["है", "hai"]]],
      ["मुझे डॉक्टर चाहिए", "mujhe ḍŏkṭar cāhie", "I need a doctor",
        [["मुझे", "mujhe"], ["डॉक्टर", "ḍŏkṭar"], ["चाहिए", "cāhie"]]],
      ["मेरी तबीयत ठीक नहीं है", "merī tabīyat ṭhīk nahīṁ hai", "I don't feel well",
        [["मेरी", "merī"], ["तबीयत", "tabīyat"], ["ठीक", "ṭhīk"], ["नहीं", "nahīṁ"], ["है", "hai"]]],
    ]),
    S("work", [
      ["यह कितने का है?", "yah kitne kā hai", "How much is this?",
        [["यह", "yah"], ["कितने", "kitne"], ["का", "kā"], ["है", "hai"]]],
      ["यह बहुत महँगा है", "yah bahut mahaṁgā hai", "This is very expensive",
        [["यह", "yah"], ["बहुत", "bahut"], ["महँगा", "mahaṁgā"], ["है", "hai"]]],
      ["मैं दफ़्तर में काम करता हूँ", "maiṁ daftar meṁ kām kartā hūṁ",
        "I work in an office",
        [["मैं", "maiṁ"], ["दफ़्तर", "daftar"], ["में", "meṁ"], ["काम", "kām"], ["करता", "kartā"], ["हूँ", "hūṁ"]]],
    ]),
    S("greetings", [
      ["आप कहाँ से हैं?", "āp kahāṁ se haiṁ", "Where are you from?",
        [["आप", "āp"], ["कहाँ", "kahāṁ"], ["से", "se"], ["हैं", "haiṁ"]]],
      ["मैं इंग्लैंड से हूँ", "maiṁ iṅglaiṇḍ se hūṁ", "I am from England",
        [["मैं", "maiṁ"], ["इंग्लैंड", "iṅglaiṇḍ"], ["से", "se"], ["हूँ", "hūṁ"]]],
      ["मैं हिंदी सीख रहा हूँ", "maiṁ hindī sīkh rahā hūṁ", "I am learning Hindi",
        [["मैं", "maiṁ"], ["हिंदी", "hindī"], ["सीख", "sīkh"], ["रहा", "rahā"], ["हूँ", "hūṁ"]]],
      ["मुझे थोड़ी हिंदी आती है", "mujhe thoṛī hindī ātī hai", "I know a little Hindi",
        [["मुझे", "mujhe"], ["थोड़ी", "thoṛī"], ["हिंदी", "hindī"], ["आती", "ātī"], ["है", "hai"]]],
      ["कृपया धीरे बोलिए", "kṛpayā dhīre bolie", "Please speak slowly",
        [["कृपया", "kṛpayā"], ["धीरे", "dhīre"], ["बोलिए", "bolie"]]],
    ]),
    S("food", [
      ["आप क्या सुझाएँगे?", "āp kyā sujhāeṁge", "What would you suggest?",
        [["आप", "āp"], ["क्या", "kyā"], ["सुझाएँगे", "sujhāeṁge"]]],
      ["खाना बहुत तीखा है", "khānā bahut tīkhā hai", "The food is very spicy",
        [["खाना", "khānā"], ["बहुत", "bahut"], ["तीखा", "tīkhā"], ["है", "hai"]]],
      ["मुझे मेवों से एलर्जी है", "mujhe mevoṁ se elarjī hai", "I am allergic to nuts",
        [["मुझे", "mujhe"], ["मेवों", "mevoṁ"], ["से", "se"], ["एलर्जी", "elarjī"], ["है", "hai"]]],
      ["एक प्लेट चावल दीजिए", "ek pleṭ cāval dījie", "Please give me a plate of rice",
        [["एक", "ek"], ["प्लेट", "pleṭ"], ["चावल", "cāval"], ["दीजिए", "dījie"]]],
    ]),
    S("travel", [
      ["ट्रेन कितने बजे जाती है?", "ṭren kitne baje jātī hai",
        "What time does the train go?",
        [["ट्रेन", "ṭren"], ["कितने", "kitne"], ["बजे", "baje"], ["जाती", "jātī"], ["है", "hai"]]],
      ["क्या यह यहाँ से दूर है?", "kyā yah yahāṁ se dūr hai", "Is it far from here?",
        [["क्या", "kyā"], ["यह", "yah"], ["यहाँ", "yahāṁ"], ["से", "se"], ["दूर", "dūr"], ["है", "hai"]]],
      ["मुझे एक कमरा चाहिए", "mujhe ek kamrā cāhie", "I need a room",
        [["मुझे", "mujhe"], ["एक", "ek"], ["कमरा", "kamrā"], ["चाहिए", "cāhie"]]],
    ]),
    S("work", [
      ["क्या मैं कार्ड से दे सकता हूँ?", "kyā maiṁ kārḍ se de saktā hūṁ",
        "Can I pay by card?",
        [["क्या", "kyā"], ["मैं", "maiṁ"], ["कार्ड", "kārḍ"], ["से", "se"], ["दे", "de"], ["सकता", "saktā"], ["हूँ", "hūṁ"]]],
      ["थोड़ा कम कीजिए", "thoṛā kam kījie", "Please make it a bit less",
        [["थोड़ा", "thoṛā"], ["कम", "kam"], ["कीजिए", "kījie"]]],
    ]),
    S("home", [
      ["मैं दो साल से यहाँ रहता हूँ", "maiṁ do sāl se yahāṁ rahtā hūṁ",
        "I have lived here for two years",
        [["मैं", "maiṁ"], ["दो", "do"], ["साल", "sāl"], ["से", "se"], ["यहाँ", "yahāṁ"], ["रहता", "rahtā"], ["हूँ", "hūṁ"]]],
    ]),
    S("health", [
      ["मुझे बुख़ार है", "mujhe bukhār hai", "I have a fever",
        [["मुझे", "mujhe"], ["बुख़ार", "bukhār"], ["है", "hai"]]],
    ])
  );

  /* ----------------------------- Conjugation ------------------------------
   * Masculine forms are used throughout (Hindi verbs also agree with gender);
   * the ending -tā/-tī and -gā/-gī is the piece to notice. */
  const CONJUGATION = [
    C("होना", "honā", "be", [
      ["मैं था", "maiṁ thā", "I was", "I", "past"],
      ["तुम थे", "tum the", "you were", "you", "past"],
      ["वह था", "vah thā", "he was", "he", "past"],
      ["वह थी", "vah thī", "she was", "she", "past"],
      ["हम थे", "ham the", "we were", "we", "past"],
      ["वे थे", "ve the", "they were", "they", "past"],
      ["मैं हूँ", "maiṁ hūṁ", "I am", "I", "present"],
      ["तुम हो", "tum ho", "you are", "you", "present"],
      ["वह है", "vah hai", "he is", "he", "present"],
      ["हम हैं", "ham haiṁ", "we are", "we", "present"],
      ["वे हैं", "ve haiṁ", "they are", "they", "present"],
      ["मैं हूँगा", "maiṁ hūṁgā", "I will be", "I", "future"],
      ["तुम होगे", "tum hoge", "you will be", "you", "future"],
      ["वह होगा", "vah hogā", "he will be", "he", "future"],
      ["हम होंगे", "ham hoṁge", "we will be", "we", "future"],
      ["वे होंगे", "ve hoṁge", "they will be", "they", "future"],
    ]),
    C("करना", "karnā", "do", [
      ["मैंने किया", "maiṁne kiyā", "I did", "I", "past"],
      ["तुमने किया", "tumne kiyā", "you did", "you", "past"],
      ["उसने किया", "usne kiyā", "he did", "he", "past"],
      ["हमने किया", "hamne kiyā", "we did", "we", "past"],
      ["उन्होंने किया", "unhoṁne kiyā", "they did", "they", "past"],
      ["मैं करता हूँ", "maiṁ kartā hūṁ", "I do", "I", "present"],
      ["तुम करते हो", "tum karte ho", "you do", "you", "present"],
      ["वह करता है", "vah kartā hai", "he does", "he", "present"],
      ["हम करते हैं", "ham karte haiṁ", "we do", "we", "present"],
      ["वे करते हैं", "ve karte haiṁ", "they do", "they", "present"],
      ["मैं करूँगा", "maiṁ karūṁgā", "I will do", "I", "future"],
      ["तुम करोगे", "tum karoge", "you will do", "you", "future"],
      ["वह करेगा", "vah karegā", "he will do", "he", "future"],
      ["हम करेंगे", "ham kareṁge", "we will do", "we", "future"],
      ["वे करेंगे", "ve kareṁge", "they will do", "they", "future"],
    ]),
    C("जाना", "jānā", "go", [
      ["मैं गया", "maiṁ gayā", "I went", "I", "past"],
      ["तुम गए", "tum gae", "you went", "you", "past"],
      ["वह गया", "vah gayā", "he went", "he", "past"],
      ["हम गए", "ham gae", "we went", "we", "past"],
      ["वे गए", "ve gae", "they went", "they", "past"],
      ["मैं जाता हूँ", "maiṁ jātā hūṁ", "I go", "I", "present"],
      ["तुम जाते हो", "tum jāte ho", "you go", "you", "present"],
      ["वह जाता है", "vah jātā hai", "he goes", "he", "present"],
      ["हम जाते हैं", "ham jāte haiṁ", "we go", "we", "present"],
      ["वे जाते हैं", "ve jāte haiṁ", "they go", "they", "present"],
      ["मैं जाऊँगा", "maiṁ jāūṁgā", "I will go", "I", "future"],
      ["तुम जाओगे", "tum jāoge", "you will go", "you", "future"],
      ["वह जाएगा", "vah jāegā", "he will go", "he", "future"],
      ["हम जाएँगे", "ham jāeṁge", "we will go", "we", "future"],
      ["वे जाएँगे", "ve jāeṁge", "they will go", "they", "future"],
    ]),
    C("खाना", "khānā", "eat", [
      ["मैंने खाया", "maiṁne khāyā", "I ate", "I", "past"],
      ["तुमने खाया", "tumne khāyā", "you ate", "you", "past"],
      ["उसने खाया", "usne khāyā", "he ate", "he", "past"],
      ["हमने खाया", "hamne khāyā", "we ate", "we", "past"],
      ["उन्होंने खाया", "unhoṁne khāyā", "they ate", "they", "past"],
      ["मैं खाता हूँ", "maiṁ khātā hūṁ", "I eat", "I", "present"],
      ["तुम खाते हो", "tum khāte ho", "you eat", "you", "present"],
      ["वह खाता है", "vah khātā hai", "he eats", "he", "present"],
      ["हम खाते हैं", "ham khāte haiṁ", "we eat", "we", "present"],
      ["वे खाते हैं", "ve khāte haiṁ", "they eat", "they", "present"],
      ["मैं खाऊँगा", "maiṁ khāūṁgā", "I will eat", "I", "future"],
      ["तुम खाओगे", "tum khāoge", "you will eat", "you", "future"],
      ["वह खाएगा", "vah khāegā", "he will eat", "he", "future"],
      ["हम खाएँगे", "ham khāeṁge", "we will eat", "we", "future"],
      ["वे खाएँगे", "ve khāeṁge", "they will eat", "they", "future"],
    ]),
    C("पीना", "pīnā", "drink", [
      ["मैंने पिया", "maiṁne piyā", "I drank", "I", "past"],
      ["तुमने पिया", "tumne piyā", "you drank", "you", "past"],
      ["उसने पिया", "usne piyā", "he drank", "he", "past"],
      ["हमने पिया", "hamne piyā", "we drank", "we", "past"],
      ["उन्होंने पिया", "unhoṁne piyā", "they drank", "they", "past"],
      ["मैं पीता हूँ", "maiṁ pītā hūṁ", "I drink", "I", "present"],
      ["तुम पीते हो", "tum pīte ho", "you drink", "you", "present"],
      ["वह पीता है", "vah pītā hai", "he drinks", "he", "present"],
      ["हम पीते हैं", "ham pīte haiṁ", "we drink", "we", "present"],
      ["वे पीते हैं", "ve pīte haiṁ", "they drink", "they", "present"],
      ["मैं पीऊँगा", "maiṁ pīūṁgā", "I will drink", "I", "future"],
      ["तुम पीओगे", "tum pīoge", "you will drink", "you", "future"],
      ["वह पीएगा", "vah pīegā", "he will drink", "he", "future"],
      ["हम पीएँगे", "ham pīeṁge", "we will drink", "we", "future"],
      ["वे पीएँगे", "ve pīeṁge", "they will drink", "they", "future"],
    ]),
    C("बोलना", "bolnā", "speak", [
      ["मैं बोला", "maiṁ bolā", "I spoke", "I", "past"],
      ["तुम बोले", "tum bole", "you spoke", "you", "past"],
      ["वह बोला", "vah bolā", "he spoke", "he", "past"],
      ["हम बोले", "ham bole", "we spoke", "we", "past"],
      ["वे बोले", "ve bole", "they spoke", "they", "past"],
      ["मैं बोलता हूँ", "maiṁ boltā hūṁ", "I speak", "I", "present"],
      ["तुम बोलते हो", "tum bolte ho", "you speak", "you", "present"],
      ["वह बोलता है", "vah boltā hai", "he speaks", "he", "present"],
      ["हम बोलते हैं", "ham bolte haiṁ", "we speak", "we", "present"],
      ["वे बोलते हैं", "ve bolte haiṁ", "they speak", "they", "present"],
      ["मैं बोलूँगा", "maiṁ bolūṁgā", "I will speak", "I", "future"],
      ["तुम बोलोगे", "tum bologe", "you will speak", "you", "future"],
      ["वह बोलेगा", "vah bolegā", "he will speak", "he", "future"],
      ["हम बोलेंगे", "ham boleṁge", "we will speak", "we", "future"],
      ["वे बोलेंगे", "ve boleṁge", "they will speak", "they", "future"],
    ]),
    C("देखना", "dekhnā", "see", [
      ["मैंने देखा", "maiṁne dekhā", "I saw", "I", "past"],
      ["तुमने देखा", "tumne dekhā", "you saw", "you", "past"],
      ["उसने देखा", "usne dekhā", "he saw", "he", "past"],
      ["हमने देखा", "hamne dekhā", "we saw", "we", "past"],
      ["उन्होंने देखा", "unhoṁne dekhā", "they saw", "they", "past"],
      ["मैं देखता हूँ", "maiṁ dekhtā hūṁ", "I see", "I", "present"],
      ["तुम देखते हो", "tum dekhte ho", "you see", "you", "present"],
      ["वह देखता है", "vah dekhtā hai", "he sees", "he", "present"],
      ["हम देखते हैं", "ham dekhte haiṁ", "we see", "we", "present"],
      ["वे देखते हैं", "ve dekhte haiṁ", "they see", "they", "present"],
      ["मैं देखूँगा", "maiṁ dekhūṁgā", "I will see", "I", "future"],
      ["तुम देखोगे", "tum dekhoge", "you will see", "you", "future"],
      ["वह देखेगा", "vah dekhegā", "he will see", "he", "future"],
      ["हम देखेंगे", "ham dekheṁge", "we will see", "we", "future"],
      ["वे देखेंगे", "ve dekheṁge", "they will see", "they", "future"],
    ]),
    C("आना", "ānā", "come", [
      ["मैं आया", "maiṁ āyā", "I came", "I", "past"],
      ["तुम आए", "tum āe", "you came", "you", "past"],
      ["वह आया", "vah āyā", "he came", "he", "past"],
      ["हम आए", "ham āe", "we came", "we", "past"],
      ["वे आए", "ve āe", "they came", "they", "past"],
      ["मैं आता हूँ", "maiṁ ātā hūṁ", "I come", "I", "present"],
      ["तुम आते हो", "tum āte ho", "you come", "you", "present"],
      ["वह आता है", "vah ātā hai", "he comes", "he", "present"],
      ["हम आते हैं", "ham āte haiṁ", "we come", "we", "present"],
      ["वे आते हैं", "ve āte haiṁ", "they come", "they", "present"],
      ["मैं आऊँगा", "maiṁ āūṁgā", "I will come", "I", "future"],
      ["तुम आओगे", "tum āoge", "you will come", "you", "future"],
      ["वह आएगा", "vah āegā", "he will come", "he", "future"],
      ["हम आएँगे", "ham āeṁge", "we will come", "we", "future"],
      ["वे आएँगे", "ve āeṁge", "they will come", "they", "future"],
    ]),
    C("पढ़ना", "paṛhnā", "read / study", [
      ["मैंने पढ़ा", "maiṁne paṛhā", "I read", "I", "past"],
      ["तुमने पढ़ा", "tumne paṛhā", "you read", "you", "past"],
      ["उसने पढ़ा", "usne paṛhā", "he read", "he", "past"],
      ["हमने पढ़ा", "hamne paṛhā", "we read", "we", "past"],
      ["उन्होंने पढ़ा", "unhoṁne paṛhā", "they read", "they", "past"],
      ["मैं पढ़ता हूँ", "maiṁ paṛhtā hūṁ", "I read", "I", "present"],
      ["तुम पढ़ते हो", "tum paṛhte ho", "you read", "you", "present"],
      ["वह पढ़ता है", "vah paṛhtā hai", "he reads", "he", "present"],
      ["हम पढ़ते हैं", "ham paṛhte haiṁ", "we read", "we", "present"],
      ["वे पढ़ते हैं", "ve paṛhte haiṁ", "they read", "they", "present"],
      ["मैं पढ़ूँगा", "maiṁ paṛhūṁgā", "I will read", "I", "future"],
      ["तुम पढ़ोगे", "tum paṛhoge", "you will read", "you", "future"],
      ["वह पढ़ेगा", "vah paṛhegā", "he will read", "he", "future"],
      ["हम पढ़ेंगे", "ham paṛheṁge", "we will read", "we", "future"],
      ["वे पढ़ेंगे", "ve paṛheṁge", "they will read", "they", "future"],
    ]),
    C("लिखना", "likhnā", "write", [
      ["मैंने लिखा", "maiṁne likhā", "I wrote", "I", "past"],
      ["तुमने लिखा", "tumne likhā", "you wrote", "you", "past"],
      ["उसने लिखा", "usne likhā", "he wrote", "he", "past"],
      ["हमने लिखा", "hamne likhā", "we wrote", "we", "past"],
      ["उन्होंने लिखा", "unhoṁne likhā", "they wrote", "they", "past"],
      ["मैं लिखता हूँ", "maiṁ likhtā hūṁ", "I write", "I", "present"],
      ["तुम लिखते हो", "tum likhte ho", "you write", "you", "present"],
      ["वह लिखता है", "vah likhtā hai", "he writes", "he", "present"],
      ["हम लिखते हैं", "ham likhte haiṁ", "we write", "we", "present"],
      ["वे लिखते हैं", "ve likhte haiṁ", "they write", "they", "present"],
      ["मैं लिखूँगा", "maiṁ likhūṁgā", "I will write", "I", "future"],
      ["तुम लिखोगे", "tum likhoge", "you will write", "you", "future"],
      ["वह लिखेगा", "vah likhegā", "he will write", "he", "future"],
      ["हम लिखेंगे", "ham likheṁge", "we will write", "we", "future"],
      ["वे लिखेंगे", "ve likheṁge", "they will write", "they", "future"],
    ]),
    C("सुनना", "sunnā", "listen", [
      ["मैंने सुना", "maiṁne sunā", "I heard", "I", "past"],
      ["तुमने सुना", "tumne sunā", "you heard", "you", "past"],
      ["उसने सुना", "usne sunā", "he heard", "he", "past"],
      ["हमने सुना", "hamne sunā", "we heard", "we", "past"],
      ["उन्होंने सुना", "unhoṁne sunā", "they heard", "they", "past"],
      ["मैं सुनता हूँ", "maiṁ suntā hūṁ", "I listen", "I", "present"],
      ["तुम सुनते हो", "tum sunte ho", "you listen", "you", "present"],
      ["वह सुनता है", "vah suntā hai", "he listens", "he", "present"],
      ["हम सुनते हैं", "ham sunte haiṁ", "we listen", "we", "present"],
      ["वे सुनते हैं", "ve sunte haiṁ", "they listen", "they", "present"],
      ["मैं सुनूँगा", "maiṁ sunūṁgā", "I will listen", "I", "future"],
      ["तुम सुनोगे", "tum sunoge", "you will listen", "you", "future"],
      ["वह सुनेगा", "vah sunegā", "he will listen", "he", "future"],
      ["हम सुनेंगे", "ham suneṁge", "we will listen", "we", "future"],
      ["वे सुनेंगे", "ve suneṁge", "they will listen", "they", "future"],
    ]),
    C("अभ्यास करना", "abhyās karnā", "practise", [
      ["मैंने अभ्यास किया", "maiṁne abhyās kiyā", "I practised", "I", "past"],
      ["तुमने अभ्यास किया", "tumne abhyās kiyā", "you practised", "you", "past"],
      ["उसने अभ्यास किया", "usne abhyās kiyā", "he practised", "he", "past"],
      ["हमने अभ्यास किया", "hamne abhyās kiyā", "we practised", "we", "past"],
      ["उन्होंने अभ्यास किया", "unhoṁne abhyās kiyā", "they practised", "they", "past"],
      ["मैं अभ्यास करता हूँ", "maiṁ abhyās kartā hūṁ", "I practise", "I", "present"],
      ["तुम अभ्यास करते हो", "tum abhyās karte ho", "you practise", "you", "present"],
      ["वह अभ्यास करता है", "vah abhyās kartā hai", "he practises", "he", "present"],
      ["हम अभ्यास करते हैं", "ham abhyās karte haiṁ", "we practise", "we", "present"],
      ["वे अभ्यास करते हैं", "ve abhyās karte haiṁ", "they practise", "they", "present"],
      ["मैं अभ्यास करूँगा", "maiṁ abhyās karūṁgā", "I will practise", "I", "future"],
      ["तुम अभ्यास करोगे", "tum abhyās karoge", "you will practise", "you", "future"],
      ["वह अभ्यास करेगा", "vah abhyās karegā", "he will practise", "he", "future"],
      ["हम अभ्यास करेंगे", "ham abhyās kareṁge", "we will practise", "we", "future"],
      ["वे अभ्यास करेंगे", "ve abhyās kareṁge", "they will practise", "they", "future"],
    ]),
    C("सोना", "sonā", "sleep", [
      ["मैं सोया", "maiṁ soyā", "I slept", "I", "past"],
      ["तुम सोए", "tum soe", "you slept", "you", "past"],
      ["वह सोया", "vah soyā", "he slept", "he", "past"],
      ["हम सोए", "ham soe", "we slept", "we", "past"],
      ["वे सोए", "ve soe", "they slept", "they", "past"],
      ["मैं सोता हूँ", "maiṁ sotā hūṁ", "I sleep", "I", "present"],
      ["तुम सोते हो", "tum sote ho", "you sleep", "you", "present"],
      ["वह सोता है", "vah sotā hai", "he sleeps", "he", "present"],
      ["हम सोते हैं", "ham sote haiṁ", "we sleep", "we", "present"],
      ["वे सोते हैं", "ve sote haiṁ", "they sleep", "they", "present"],
      ["मैं सोऊँगा", "maiṁ soūṁgā", "I will sleep", "I", "future"],
      ["तुम सोओगे", "tum sooge", "you will sleep", "you", "future"],
      ["वह सोएगा", "vah soegā", "he will sleep", "he", "future"],
      ["हम सोएँगे", "ham soeṁge", "we will sleep", "we", "future"],
      ["वे सोएँगे", "ve soeṁge", "they will sleep", "they", "future"],
    ]),
    C("चलना", "calnā", "walk / move", [
      ["मैं चला", "maiṁ calā", "I walked", "I", "past"],
      ["तुम चले", "tum cale", "you walked", "you", "past"],
      ["वह चला", "vah calā", "he walked", "he", "past"],
      ["हम चले", "ham cale", "we walked", "we", "past"],
      ["वे चले", "ve cale", "they walked", "they", "past"],
      ["मैं चलता हूँ", "maiṁ caltā hūṁ", "I walk", "I", "present"],
      ["तुम चलते हो", "tum calte ho", "you walk", "you", "present"],
      ["वह चलता है", "vah caltā hai", "he walks", "he", "present"],
      ["हम चलते हैं", "ham calte haiṁ", "we walk", "we", "present"],
      ["वे चलते हैं", "ve calte haiṁ", "they walk", "they", "present"],
      ["मैं चलूँगा", "maiṁ calūṁgā", "I will walk", "I", "future"],
      ["तुम चलोगे", "tum caloge", "you will walk", "you", "future"],
      ["वह चलेगा", "vah calegā", "he will walk", "he", "future"],
      ["हम चलेंगे", "ham caleṁge", "we will walk", "we", "future"],
      ["वे चलेंगे", "ve caleṁge", "they will walk", "they", "future"],
    ]),
    C("ख़रीदना", "kharīdnā", "buy", [
      ["मैंने ख़रीदा", "maiṁne kharīdā", "I bought", "I", "past"],
      ["तुमने ख़रीदा", "tumne kharīdā", "you bought", "you", "past"],
      ["उसने ख़रीदा", "usne kharīdā", "he bought", "he", "past"],
      ["हमने ख़रीदा", "hamne kharīdā", "we bought", "we", "past"],
      ["उन्होंने ख़रीदा", "unhoṁne kharīdā", "they bought", "they", "past"],
      ["मैं ख़रीदता हूँ", "maiṁ kharīdtā hūṁ", "I buy", "I", "present"],
      ["तुम ख़रीदते हो", "tum kharīdte ho", "you buy", "you", "present"],
      ["वह ख़रीदता है", "vah kharīdtā hai", "he buys", "he", "present"],
      ["हम ख़रीदते हैं", "ham kharīdte haiṁ", "we buy", "we", "present"],
      ["वे ख़रीदते हैं", "ve kharīdte haiṁ", "they buy", "they", "present"],
      ["मैं ख़रीदूँगा", "maiṁ kharīdūṁgā", "I will buy", "I", "future"],
      ["तुम ख़रीदोगे", "tum kharīdoge", "you will buy", "you", "future"],
      ["वह ख़रीदेगा", "vah kharīdegā", "he will buy", "he", "future"],
      ["हम ख़रीदेंगे", "ham kharīdeṁge", "we will buy", "we", "future"],
      ["वे ख़रीदेंगे", "ve kharīdeṁge", "they will buy", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Effort",
      l1: "जहाँ चाह,", l2: "वहाँ राह।",
      tr1: "jahāṁ cāh", tr2: "vahāṁ rāh",
      en: "Where there is a wish, there is a road." },
    { n: 2, chapterEn: "Patience",
      l1: "धीरे-धीरे रे मना,", l2: "धीरे सब कुछ होय।",
      tr1: "dhīre-dhīre re manā", tr2: "dhīre sab kuch hoy",
      en: "Slowly, O mind — slowly everything comes to be." },
    { n: 3, chapterEn: "Appearances",
      l1: "हाथी के दाँत खाने के और,", l2: "दिखाने के और।",
      tr1: "hāthī ke dāṁt khāne ke aur", tr2: "dikhāne ke aur",
      en: "An elephant has one set of teeth for eating and another for show." },
    { n: 4, chapterEn: "Prudence",
      l1: "अब पछताए होत क्या,", l2: "जब चिड़िया चुग गई खेत।",
      tr1: "ab pachtāe hot kyā", tr2: "jab ciṛiyā cug gaī khet",
      en: "What use is regret now, when the birds have already eaten the field?" },
    { n: 5, chapterEn: "Company",
      l1: "संगत का असर", l2: "पड़ता ही है।",
      tr1: "saṅgat kā asar", tr2: "paṛtā hī hai",
      en: "The company you keep always leaves its mark." },
    { n: 6, chapterEn: "Knowledge",
      l1: "नीम हकीम", l2: "ख़तरा-ए-जान।",
      tr1: "nīm hakīm", tr2: "khatrā-e-jān",
      en: "A half-trained doctor is a danger to life." },
    { n: 7, chapterEn: "Truth",
      l1: "सच को", l2: "आँच नहीं।",
      tr1: "sac ko", tr2: "āṁc nahīṁ",
      en: "Truth cannot be burned." },
    { n: 8, chapterEn: "Unity",
      l1: "एक और एक", l2: "ग्यारह होते हैं।",
      tr1: "ek aur ek", tr2: "gyārah hote haiṁ",
      en: "One and one make eleven — together people are far stronger." },
    { n: 9, chapterEn: "Work",
      l1: "करत करत अभ्यास के", l2: "जड़मति होत सुजान।",
      tr1: "karat karat abhyās ke", tr2: "jaṛmati hot sujān",
      en: "With constant practice even a dull mind becomes wise." },
    { n: 10, chapterEn: "Prudence",
      l1: "दूध का जला", l2: "छाछ भी फूँक-फूँक कर पीता है।",
      tr1: "dūdh kā jalā", tr2: "chāch bhī phūṁk-phūṁk kar pītā hai",
      en: "One burned by milk blows even on buttermilk before drinking." },
    { n: 11, chapterEn: "Unity",
      l1: "एकता में", l2: "बल है।",
      tr1: "ektā meṁ", tr2: "bal hai",
      en: "There is strength in unity." },
    { n: 12, chapterEn: "Appearances",
      l1: "जो दिखता है,", l2: "वो बिकता है।",
      tr1: "jo dikhtā hai", tr2: "vo biktā hai",
      en: "What is seen is what sells." },
    { n: 13, chapterEn: "Effort",
      l1: "मेहनत का फल", l2: "मीठा होता है।",
      tr1: "mehnat kā phal", tr2: "mīṭhā hotā hai",
      en: "The fruit of hard work is sweet." },
    { n: 14, chapterEn: "Speech",
      l1: "बोली से", l2: "आदमी पहचाना जाता है।",
      tr1: "bolī se", tr2: "ādmī pahcānā jātā hai",
      en: "A person is known by the way they speak." },
    { n: 15, chapterEn: "Prudence",
      l1: "जितनी चादर हो,", l2: "उतने ही पैर पसारो।",
      tr1: "jitnī cādar ho", tr2: "utne hī pair pasāro",
      en: "Stretch your legs only as far as your blanket reaches." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("hindi", {
    icons: {
      alphabet: "वर्णमाला", greetings: "नमस्ते", numbers: "संख्या", colors: "रंग",
      family: "परिवार", people: "लोग", pronouns: "सर्वनाम", questions: "प्रश्न",
      grammar: "अव्यय", adjectives: "विशेषण", adverbs: "क्रिया-विशेषण", verbs: "क्रिया",
      food: "खाना", body: "शरीर", health: "सेहत", clothing: "कपड़े", home: "घर",
      animals: "जानवर", nature: "प्रकृति", places: "जगह", travel: "यात्रा",
      time: "समय", work: "काम", school: "स्कूल", tech: "तकनीक", sentences: "वाक्य",
    },
    ui: { account: "खाता", progress: "प्रगति", search: "खोज" },
    alphabet: ALPHABET,
    alphabetTitle: "Devanagari",
    alphabetLabels: ["Svar — vowels & mātrās", "Vyañjan — consonants"],
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "दोहराव", vocab: "शब्द", sentence: "वाक्य", conjugation: "क्रिया",
      listening: "सुनना", mixed: "मिश्रित", reading: "कहावतें",
    },
    reading: {
      id: "kahavat", title: "Proverbs", native: "कहावतें",
      desc: "Classic Hindi sayings, line by line",
      blurb: "कहावतें — proverbs and couplets heard across the Hindi-speaking world.",
      unit: "sayings", numLabel: "कहावत",
      lineQuestion: "Which line completes this saying?",
      items: PROVERBS,
    },
  });
})();
