/* ============================================================================
 * Hindi course — data only.
 *
 * `ta` is the Devanagari, `tr` its transliteration (a light scholarly scheme:
 * ā ī ū ṭ ḍ ṇ ś ṣ ṛ …), `en` the English meaning. Nouns are given in their
 * dictionary form; the gender is noted where it isn't predictable.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------ Alphabet -------------------------------
   * The varṇamālā: 13 svar (vowels) with the mātrā each becomes when it
   * follows a consonant, and 33 vyañjan (consonants), each of which carries
   * an inherent "a" until a mātrā or a halant replaces it.
   * -------------------------------------------------------------------- */
  const VOWELS = A([
    ["अ", "a", "a — the inherent vowel, written with no mātrā"],
    ["आ  ा", "ā", "long a — mātrā ा, as in का (kā)"],
    ["इ  ि", "i", "short i — mātrā ि goes before, as in कि (ki)"],
    ["ई  ी", "ī", "long i — mātrā ी, as in की (kī)"],
    ["उ  ु", "u", "short u — mātrā ु below, as in कु (ku)"],
    ["ऊ  ू", "ū", "long u — mātrā ू below, as in कू (kū)"],
    ["ऋ  ृ", "ṛ", "vocalic r — mātrā ृ, as in कृ (kṛ)"],
    ["ए  े", "e", "e — mātrā े above, as in के (ke)"],
    ["ऐ  ै", "ai", "ai — mātrā ै above, as in कै (kai)"],
    ["ओ  ो", "o", "o — mātrā ो, as in को (ko)"],
    ["औ  ौ", "au", "au — mātrā ौ, as in कौ (kau)"],
    ["अं  ं", "aṃ", "anusvāra — nasalises the vowel, as in हिंदी"],
    ["अः  ः", "aḥ", "visarga — a breathed h at the end"],
    ["अँ  ँ", "am̐", "candrabindu — a nasal vowel, as in हँसना"],
    ["्", "halant", "removes the inherent a: क् is k, not ka"],
  ]);
  const CONSONANTS = A([
    ["क", "ka", "guttural — k"], ["ख", "kha", "guttural — k with a puff"],
    ["ग", "ga", "guttural — g"], ["घ", "gha", "guttural — g with a puff"],
    ["ङ", "ṅa", "guttural nasal — ng"],
    ["च", "ca", "palatal — ch"], ["छ", "cha", "palatal — ch with a puff"],
    ["ज", "ja", "palatal — j"], ["झ", "jha", "palatal — j with a puff"],
    ["ञ", "ña", "palatal nasal — ny"],
    ["ट", "ṭa", "retroflex — t, tongue curled back"],
    ["ठ", "ṭha", "retroflex — t with a puff"],
    ["ड", "ḍa", "retroflex — d"], ["ढ", "ḍha", "retroflex — d with a puff"],
    ["ण", "ṇa", "retroflex nasal — n"],
    ["त", "ta", "dental — t, tongue on the teeth"],
    ["थ", "tha", "dental — t with a puff"],
    ["द", "da", "dental — d"], ["ध", "dha", "dental — d with a puff"],
    ["न", "na", "dental nasal — n"],
    ["प", "pa", "labial — p"], ["फ", "pha", "labial — p with a puff"],
    ["ब", "ba", "labial — b"], ["भ", "bha", "labial — b with a puff"],
    ["म", "ma", "labial nasal — m"],
    ["य", "ya", "semivowel — y"], ["र", "ra", "semivowel — r"],
    ["ल", "la", "semivowel — l"], ["व", "va", "semivowel — v / w"],
    ["श", "śa", "sibilant — sh, palatal"], ["ष", "ṣa", "sibilant — sh, retroflex"],
    ["स", "sa", "sibilant — s"], ["ह", "ha", "aspirate — h"],
    ["क्ष", "kṣa", "conjunct — ksh"], ["त्र", "tra", "conjunct — tr"],
    ["ज्ञ", "jña", "conjunct — gy in modern Hindi"],
    ["ड़", "ṛa", "flapped r, a dot below ड"],
    ["ढ़", "ṛha", "flapped r with a puff"],
    ["क़", "qa", "borrowed — a deep k, from Persian"],
    ["ज़", "za", "borrowed — z"], ["फ़", "fa", "borrowed — f"],
  ]);
  const ALPHABET = { vowels: VOWELS, consonants: CONSONANTS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["नमस्ते", "namaste", "hello / goodbye"],
      ["नमस्कार", "namaskār", "greetings (formal)"],
      ["सुप्रभात", "suprabhāt", "good morning"],
      ["शुभ रात्रि", "śubh rātri", "good night"],
      ["धन्यवाद", "dhanyavād", "thank you"],
      ["शुक्रिया", "śukriyā", "thanks"],
      ["कृपया", "kṛpayā", "please"],
      ["हाँ", "hāṁ", "yes"], ["नहीं", "nahīṁ", "no"],
      ["माफ़ कीजिए", "māf kījie", "excuse me / forgive me"],
      ["क्षमा करें", "kṣamā kareṁ", "I'm sorry"],
      ["आप कैसे हैं?", "āp kaise haiṁ", "how are you?"],
      ["मैं ठीक हूँ", "maiṁ ṭhīk hūṁ", "I am fine"],
      ["ठीक है", "ṭhīk hai", "okay / all right"],
      ["स्वागत है", "svāgat hai", "welcome"],
      ["फिर मिलेंगे", "phir mileṁge", "see you again"],
      ["अलविदा", "alvidā", "farewell"],
      ["बधाई हो", "badhāī ho", "congratulations"],
      ["शुभकामनाएँ", "śubhkāmanāeṁ", "best wishes"],
      ["मिलकर खुशी हुई", "milkar khuśī huī", "pleased to meet you"],
      ["आपका नाम क्या है?", "āpkā nām kyā hai", "what is your name?"],
      ["मेरा नाम", "merā nām", "my name"],
      ["जी हाँ", "jī hāṁ", "yes (polite)"],
      ["जी नहीं", "jī nahīṁ", "no (polite)"],
      ["कोई बात नहीं", "koī bāt nahīṁ", "it's no problem"],
      ["आइए", "āie", "please come in"],
    ]),
    V("numbers", [
      ["शून्य", "śūnya", "zero"], ["एक", "ek", "one"], ["दो", "do", "two"],
      ["तीन", "tīn", "three"], ["चार", "cār", "four"], ["पाँच", "pāṁc", "five"],
      ["छह", "chah", "six"], ["सात", "sāt", "seven"], ["आठ", "āṭh", "eight"],
      ["नौ", "nau", "nine"], ["दस", "das", "ten"], ["ग्यारह", "gyārah", "eleven"],
      ["बारह", "bārah", "twelve"], ["तेरह", "terah", "thirteen"],
      ["चौदह", "caudah", "fourteen"], ["पंद्रह", "pandrah", "fifteen"],
      ["सोलह", "solah", "sixteen"], ["बीस", "bīs", "twenty"],
      ["तीस", "tīs", "thirty"], ["चालीस", "cālīs", "forty"],
      ["पचास", "pacās", "fifty"], ["सौ", "sau", "one hundred"],
      ["हज़ार", "hazār", "one thousand"], ["लाख", "lākh", "one hundred thousand"],
      ["पहला", "pahlā", "first"], ["दूसरा", "dūsrā", "second"],
      ["आख़िरी", "ākhirī", "last"], ["आधा", "ādhā", "half"],
      ["संख्या", "saṅkhyā", "number"],
    ]),
    V("colors", [
      ["लाल", "lāl", "red"], ["नीला", "nīlā", "blue"], ["हरा", "harā", "green"],
      ["पीला", "pīlā", "yellow"], ["काला", "kālā", "black"], ["सफ़ेद", "safed", "white"],
      ["भूरा", "bhūrā", "brown"], ["नारंगी", "nāraṅgī", "orange"],
      ["गुलाबी", "gulābī", "pink"], ["बैंगनी", "baiṅganī", "purple"],
      ["सुनहरा", "sunahrā", "golden"], ["चाँदी जैसा", "cāṁdī jaisā", "silver"],
      ["स्लेटी", "sleṭī", "grey"], ["हल्का", "halkā", "light (colour)"],
      ["गहरा", "gaharā", "dark / deep"], ["रंग", "raṅg", "colour"],
      ["रंगीन", "raṅgīn", "colourful"], ["चमकीला", "camkīlā", "bright / shiny"],
      ["फीका", "phīkā", "pale / faded"], ["आसमानी", "āsmānī", "sky blue"],
      ["धानी", "dhānī", "light green"],
    ]),
    V("family", [
      ["परिवार", "parivār", "family"], ["माँ", "māṁ", "mother"],
      ["पिता", "pitā", "father"], ["माता", "mātā", "mother (formal)"],
      ["बेटा", "beṭā", "son"], ["बेटी", "beṭī", "daughter"],
      ["भाई", "bhāī", "brother"], ["बहन", "bahan", "sister"],
      ["दादा", "dādā", "paternal grandfather"], ["दादी", "dādī", "paternal grandmother"],
      ["नाना", "nānā", "maternal grandfather"], ["नानी", "nānī", "maternal grandmother"],
      ["चाचा", "cācā", "paternal uncle"], ["चाची", "cācī", "paternal aunt"],
      ["मामा", "māmā", "maternal uncle"], ["मौसी", "mausī", "maternal aunt"],
      ["पति", "pati", "husband"], ["पत्नी", "patnī", "wife"],
      ["बच्चा", "baccā", "child"], ["बच्ची", "baccī", "girl child"],
      ["रिश्तेदार", "riśtedār", "relative"], ["शादी", "śādī", "wedding / marriage"],
      ["ससुर", "sasur", "father-in-law"], ["पोता", "potā", "grandson"],
      ["भतीजा", "bhatījā", "nephew"],
    ]),
    V("people", [
      ["आदमी", "ādmī", "man"], ["औरत", "aurat", "woman"],
      ["व्यक्ति", "vyakti", "person"], ["लोग", "log", "people"],
      ["लड़का", "laṛkā", "boy"], ["लड़की", "laṛkī", "girl"],
      ["दोस्त", "dost", "friend"], ["मित्र", "mitra", "friend (formal)"],
      ["पड़ोसी", "paṛosī", "neighbour"], ["मेहमान", "mehmān", "guest"],
      ["बूढ़ा", "būṛhā", "old man"], ["जवान", "javān", "young person"],
      ["बच्चे", "bacce", "children"], ["साहब", "sāhab", "sir"],
      ["मैडम", "maiḍam", "madam"], ["विदेशी", "videśī", "foreigner"],
      ["सहकर्मी", "sahkarmī", "colleague"], ["टीम", "ṭīm", "team"],
      ["समूह", "samūh", "group"], ["नाम", "nām", "name"],
      ["भीड़", "bhīṛ", "crowd"], ["इंसान", "insān", "human being"],
      ["नागरिक", "nāgrik", "citizen"],
    ]),
    V("pronouns", [
      ["मैं", "maiṁ", "I"], ["तुम", "tum", "you (familiar)"], ["आप", "āp", "you (polite)"],
      ["तू", "tū", "you (intimate)"], ["वह", "vah", "he / she / that"],
      ["यह", "yah", "this / he / she"], ["हम", "ham", "we"],
      ["वे", "ve", "they"], ["मुझे", "mujhe", "to me"], ["तुम्हें", "tumheṁ", "to you"],
      ["उसे", "use", "to him / her"], ["हमें", "hameṁ", "to us"],
      ["मेरा", "merā", "my"], ["तुम्हारा", "tumhārā", "your"],
      ["आपका", "āpkā", "your (polite)"], ["उसका", "uskā", "his / her"],
      ["हमारा", "hamārā", "our"], ["उनका", "unkā", "their"],
      ["कोई", "koī", "someone / any"], ["कुछ", "kuch", "something / some"],
      ["सब", "sab", "all / everyone"], ["ख़ुद", "khud", "oneself"],
      ["अपना", "apnā", "one's own"], ["इनका", "inkā", "of these"],
    ]),
    V("questions", [
      ["क्या", "kyā", "what"], ["कौन", "kaun", "who"], ["कहाँ", "kahāṁ", "where"],
      ["कब", "kab", "when"], ["क्यों", "kyoṁ", "why"], ["कैसे", "kaise", "how"],
      ["कैसा", "kaisā", "of what kind"], ["कितना", "kitnā", "how much"],
      ["कितने", "kitne", "how many"], ["कौन सा", "kaun sā", "which"],
      ["किसका", "kiskā", "whose"], ["कहाँ से", "kahāṁ se", "from where"],
      ["सवाल", "savāl", "question"], ["जवाब", "javāb", "answer"],
      ["पूछना", "pūchnā", "to ask"], ["बताना", "batānā", "to tell"],
      ["यह कितने का है?", "yah kitne kā hai", "how much is this?"],
      ["क्या समय हुआ है?", "kyā samay huā hai", "what time is it?"],
      ["क्या हुआ?", "kyā huā", "what happened?"],
      ["ना?", "nā", "isn't it? / right?"],
    ]),
    V("grammar", [
      ["और", "aur", "and"], ["या", "yā", "or"], ["लेकिन", "lekin", "but"],
      ["क्योंकि", "kyoṁki", "because"], ["अगर", "agar", "if"], ["तो", "to", "then"],
      ["का", "kā", "of (m)"], ["की", "kī", "of (f)"], ["के", "ke", "of (pl)"],
      ["को", "ko", "to (object marker)"], ["से", "se", "from / with"],
      ["में", "meṁ", "in"], ["पर", "par", "on / but"], ["तक", "tak", "until"],
      ["के लिए", "ke lie", "for"], ["के साथ", "ke sāth", "with"],
      ["के बिना", "ke binā", "without"], ["के बाद", "ke bād", "after"],
      ["के पहले", "ke pahle", "before"], ["के बीच", "ke bīc", "between"],
      ["भी", "bhī", "also"], ["ही", "hī", "only / emphasis"],
      ["नहीं", "nahīṁ", "not"], ["मत", "mat", "don't (command)"],
      ["फिर", "phir", "then / again"], ["इसलिए", "islie", "therefore"],
      ["जब", "jab", "when (relative)"],
    ]),
    V("adjectives", [
      ["बड़ा", "baṛā", "big"], ["छोटा", "choṭā", "small"], ["अच्छा", "acchā", "good"],
      ["बुरा", "burā", "bad"], ["नया", "nayā", "new"], ["पुराना", "purānā", "old (things)"],
      ["जवान", "javān", "young"], ["लंबा", "lambā", "long / tall"],
      ["छोटा-सा", "choṭā-sā", "tiny"], ["ऊँचा", "ūṁcā", "high"],
      ["नीचा", "nīcā", "low"], ["गरम", "garam", "hot"], ["ठंडा", "ṭhaṇḍā", "cold"],
      ["आसान", "āsān", "easy"], ["मुश्किल", "muśkil", "difficult"],
      ["सुंदर", "sundar", "beautiful"], ["बदसूरत", "badsūrat", "ugly"],
      ["मज़बूत", "mazbūt", "strong"], ["कमज़ोर", "kamzor", "weak"],
      ["तेज़", "tez", "fast / sharp"], ["धीमा", "dhīmā", "slow"],
      ["अमीर", "amīr", "rich"], ["ग़रीब", "garīb", "poor"],
      ["ख़ुश", "khuś", "happy"], ["उदास", "udās", "sad"], ["थका", "thakā", "tired"],
      ["साफ़", "sāf", "clean"], ["गंदा", "gandā", "dirty"], ["भरा", "bharā", "full"],
      ["ख़ाली", "khālī", "empty"], ["महँगा", "mahaṁgā", "expensive"],
      ["सस्ता", "sastā", "cheap"], ["ज़रूरी", "zarūrī", "important"],
    ]),
    V("adverbs", [
      ["बहुत", "bahut", "very / much"], ["थोड़ा", "thoṛā", "a little"],
      ["अच्छी तरह", "acchī tarah", "well"], ["हमेशा", "hameśā", "always"],
      ["कभी नहीं", "kabhī nahīṁ", "never"], ["कभी-कभी", "kabhī-kabhī", "sometimes"],
      ["अक्सर", "aksar", "often"], ["अब", "ab", "now"], ["आज", "āj", "today"],
      ["कल", "kal", "yesterday / tomorrow"], ["परसों", "parsoṁ", "day before / after"],
      ["जल्दी", "jaldī", "quickly / early"], ["देर से", "der se", "late"],
      ["यहाँ", "yahāṁ", "here"], ["वहाँ", "vahāṁ", "there"],
      ["पास", "pās", "near"], ["दूर", "dūr", "far"], ["साथ", "sāth", "together"],
      ["सिर्फ़", "sirf", "only"], ["शायद", "śāyad", "maybe"],
      ["पहले से", "pahle se", "already"], ["अभी", "abhī", "right now"],
      ["फिर से", "phir se", "again"], ["धीरे", "dhīre", "slowly"],
      ["लगभग", "lagbhag", "almost"], ["ज़्यादा", "zyādā", "too much / more"],
      ["सच में", "sac meṁ", "really"],
    ]),
    V("verbs", [
      ["होना", "honā", "to be"], ["करना", "karnā", "to do"],
      ["जाना", "jānā", "to go"], ["आना", "ānā", "to come"],
      ["देना", "denā", "to give"], ["लेना", "lenā", "to take"],
      ["खाना", "khānā", "to eat"], ["पीना", "pīnā", "to drink"],
      ["बोलना", "bolnā", "to speak"], ["कहना", "kahnā", "to say"],
      ["सुनना", "sunnā", "to hear"], ["देखना", "dekhnā", "to see"],
      ["पढ़ना", "paṛhnā", "to read / study"], ["लिखना", "likhnā", "to write"],
      ["समझना", "samajhnā", "to understand"], ["सोचना", "socnā", "to think"],
      ["जानना", "jānnā", "to know"], ["सीखना", "sīkhnā", "to learn"],
      ["सिखाना", "sikhānā", "to teach"], ["रहना", "rahnā", "to live / stay"],
      ["सोना", "sonā", "to sleep"], ["उठना", "uṭhnā", "to get up"],
      ["बैठना", "baiṭhnā", "to sit"], ["चलना", "calnā", "to walk / move"],
      ["दौड़ना", "dauṛnā", "to run"], ["ख़रीदना", "kharīdnā", "to buy"],
      ["बेचना", "becnā", "to sell"], ["खोलना", "kholnā", "to open"],
      ["बंद करना", "band karnā", "to close"], ["शुरू करना", "śurū karnā", "to begin"],
      ["ख़त्म करना", "khatm karnā", "to finish"], ["मदद करना", "madad karnā", "to help"],
      ["चाहना", "cāhnā", "to want"], ["मिलना", "milnā", "to meet / receive"],
      ["काम करना", "kām karnā", "to work"], ["इंतज़ार करना", "intazār karnā", "to wait"],
      ["खेलना", "khelnā", "to play"], ["बनाना", "banānā", "to make"],
    ]),
    V("food", [
      ["खाना", "khānā", "food / meal"], ["पानी", "pānī", "water"],
      ["रोटी", "roṭī", "bread / flatbread"], ["चावल", "cāval", "rice"],
      ["दाल", "dāl", "lentils"], ["सब्ज़ी", "sabzī", "vegetable / curry"],
      ["गोश्त", "gośt", "meat"], ["मुर्ग़ा", "murgā", "chicken"],
      ["मछली", "machlī", "fish"], ["अंडा", "aṇḍā", "egg"],
      ["दूध", "dūdh", "milk"], ["दही", "dahī", "yoghurt"],
      ["पनीर", "panīr", "cheese"], ["मक्खन", "makkhan", "butter"],
      ["फल", "phal", "fruit"], ["सेब", "seb", "apple"],
      ["केला", "kelā", "banana"], ["आम", "ām", "mango"],
      ["संतरा", "santrā", "orange"], ["आलू", "ālū", "potato"],
      ["टमाटर", "ṭamāṭar", "tomato"], ["प्याज़", "pyāz", "onion"],
      ["लहसुन", "lahsun", "garlic"], ["नमक", "namak", "salt"],
      ["मिर्च", "mirc", "chilli"], ["चीनी", "cīnī", "sugar"],
      ["तेल", "tel", "oil"], ["मसाला", "masālā", "spice"],
      ["चाय", "cāy", "tea"], ["कॉफ़ी", "kŏfī", "coffee"],
      ["रस", "ras", "juice"], ["मिठाई", "miṭhāī", "sweets"],
      ["नाश्ता", "nāśtā", "breakfast"], ["दोपहर का खाना", "dopahar kā khānā", "lunch"],
      ["रात का खाना", "rāt kā khānā", "dinner"], ["रेस्टोरेंट", "resṭoreṇṭ", "restaurant"],
      ["बिल", "bil", "the bill"], ["भूख", "bhūkh", "hunger"],
    ]),
    V("body", [
      ["शरीर", "śarīr", "body"], ["सिर", "sir", "head"], ["बाल", "bāl", "hair"],
      ["चेहरा", "cehrā", "face"], ["आँख", "āṁkh", "eye"], ["कान", "kān", "ear"],
      ["नाक", "nāk", "nose"], ["मुँह", "muṁh", "mouth"], ["दाँत", "dāṁt", "tooth"],
      ["जीभ", "jībh", "tongue"], ["गला", "galā", "throat / neck"],
      ["कंधा", "kandhā", "shoulder"], ["हाथ", "hāth", "hand / arm"],
      ["उँगली", "uṁglī", "finger"], ["पैर", "pair", "foot / leg"],
      ["घुटना", "ghuṭnā", "knee"], ["पीठ", "pīṭh", "back"],
      ["छाती", "chātī", "chest"], ["दिल", "dil", "heart"],
      ["पेट", "peṭ", "stomach"], ["ख़ून", "khūn", "blood"],
      ["हड्डी", "haḍḍī", "bone"], ["त्वचा", "tvacā", "skin"],
      ["दिमाग़", "dimāg", "brain / mind"],
    ]),
    V("health", [
      ["सेहत", "sehat", "health"], ["डॉक्टर", "ḍŏkṭar", "doctor"],
      ["अस्पताल", "aspatāl", "hospital"], ["दवा", "davā", "medicine"],
      ["दवाख़ाना", "davākhānā", "pharmacy"], ["बीमार", "bīmār", "ill"],
      ["स्वस्थ", "svasth", "healthy"], ["दर्द", "dard", "pain"],
      ["बुख़ार", "bukhār", "fever"], ["खाँसी", "khāṁsī", "cough"],
      ["सर्दी", "sardī", "a cold"], ["चोट", "coṭ", "injury"],
      ["नर्स", "nars", "nurse"], ["इलाज", "ilāj", "treatment"],
      ["आराम", "ārām", "rest"], ["व्यायाम", "vyāyām", "exercise"],
      ["एम्बुलेंस", "embuleṁs", "ambulance"], ["आपातकाल", "āpātkāl", "emergency"],
      ["ठीक होना", "ṭhīk honā", "to get better"],
      ["सिर दर्द", "sir dard", "headache"], ["पेट दर्द", "peṭ dard", "stomach ache"],
      ["टीका", "ṭīkā", "vaccination"],
    ]),
    V("clothing", [
      ["कपड़े", "kapṛe", "clothes"], ["कमीज़", "kamīz", "shirt"],
      ["पैंट", "paiṇṭ", "trousers"], ["साड़ी", "sāṛī", "sari"],
      ["सलवार", "salvār", "salwar (loose trousers)"], ["कुर्ता", "kurtā", "kurta (long tunic)"],
      ["धोती", "dhotī", "dhoti"], ["दुपट्टा", "dupaṭṭā", "scarf / stole"],
      ["कोट", "koṭ", "coat"], ["जैकेट", "jaikeṭ", "jacket"],
      ["स्वेटर", "sveṭar", "sweater"], ["जूता", "jūtā", "shoe"],
      ["चप्पल", "cappal", "sandal"], ["मोज़ा", "mozā", "sock"],
      ["टोपी", "ṭopī", "cap / hat"], ["दस्ताने", "dastāne", "gloves"],
      ["बेल्ट", "belṭ", "belt"], ["चश्मा", "caśmā", "glasses"],
      ["बैग", "baig", "bag"], ["गहना", "gahnā", "jewellery"],
      ["आकार", "ākār", "size"], ["पहनना", "pahannā", "to wear"],
      ["उतारना", "utārnā", "to take off"],
    ]),
    V("home", [
      ["घर", "ghar", "house / home"], ["मकान", "makān", "building / house"],
      ["कमरा", "kamrā", "room"], ["रसोई", "rasoī", "kitchen"],
      ["स्नानघर", "snānghar", "bathroom"], ["बैठक", "baiṭhak", "living room"],
      ["दरवाज़ा", "darvāzā", "door"], ["खिड़की", "khiṛkī", "window"],
      ["मेज़", "mez", "table"], ["कुर्सी", "kursī", "chair"],
      ["बिस्तर", "bistar", "bed"], ["सोफ़ा", "sofā", "sofa"],
      ["दीया", "dīyā", "lamp"], ["शीशा", "śīśā", "mirror / glass"],
      ["चाबी", "cābī", "key"], ["थाली", "thālī", "plate"],
      ["गिलास", "gilās", "glass (tumbler)"], ["कप", "kap", "cup"],
      ["चाकू", "cākū", "knife"], ["चम्मच", "cammac", "spoon"],
      ["बग़ीचा", "bagīcā", "garden"], ["सीढ़ी", "sīṛhī", "stairs / ladder"],
      ["छत", "chat", "roof / ceiling"], ["दीवार", "dīvār", "wall"],
      ["फ़र्श", "farś", "floor"], ["फ़्रिज", "frij", "fridge"],
      ["पंखा", "paṅkhā", "fan"],
    ]),
    V("animals", [
      ["जानवर", "jānvar", "animal"], ["कुत्ता", "kuttā", "dog"],
      ["बिल्ली", "billī", "cat"], ["घोड़ा", "ghoṛā", "horse"],
      ["गाय", "gāy", "cow"], ["बैल", "bail", "ox"], ["सूअर", "sūar", "pig"],
      ["बकरी", "bakrī", "goat"], ["भेड़", "bheṛ", "sheep"],
      ["मुर्ग़ी", "murgī", "hen"], ["पक्षी", "pakṣī", "bird"],
      ["चिड़िया", "ciṛiyā", "small bird"], ["मछली", "machlī", "fish"],
      ["चूहा", "cūhā", "mouse / rat"], ["ख़रगोश", "khargoś", "rabbit"],
      ["शेर", "śer", "lion"], ["बाघ", "bāgh", "tiger"],
      ["हाथी", "hāthī", "elephant"], ["बंदर", "bandar", "monkey"],
      ["भालू", "bhālū", "bear"], ["साँप", "sāṁp", "snake"],
      ["मकड़ी", "makṛī", "spider"], ["तितली", "titlī", "butterfly"],
      ["मधुमक्खी", "madhumakkhī", "bee"], ["चींटी", "cīṁṭī", "ant"],
      ["मक्खी", "makkhī", "fly"],
    ]),
    V("nature", [
      ["प्रकृति", "prakṛti", "nature"], ["सूरज", "sūraj", "sun"],
      ["चाँद", "cāṁd", "moon"], ["तारा", "tārā", "star"],
      ["आसमान", "āsmān", "sky"], ["बादल", "bādal", "cloud"],
      ["बारिश", "bāriś", "rain"], ["बर्फ़", "barf", "snow / ice"],
      ["हवा", "havā", "wind / air"], ["आग", "āg", "fire"],
      ["धरती", "dhartī", "earth"], ["मिट्टी", "miṭṭī", "soil"],
      ["समुद्र", "samudra", "sea"], ["नदी", "nadī", "river"],
      ["झील", "jhīl", "lake"], ["पहाड़", "pahāṛ", "mountain"],
      ["जंगल", "jaṅgal", "forest"], ["पेड़", "peṛ", "tree"],
      ["फूल", "phūl", "flower"], ["पत्ता", "pattā", "leaf"],
      ["घास", "ghās", "grass"], ["समुद्र तट", "samudra taṭ", "beach"],
      ["द्वीप", "dvīp", "island"], ["रेगिस्तान", "registān", "desert"],
      ["पत्थर", "patthar", "stone"], ["मौसम", "mausam", "weather"],
      ["तूफ़ान", "tūfān", "storm"],
    ]),
    V("places", [
      ["जगह", "jagah", "place"], ["शहर", "śahar", "city"],
      ["गाँव", "gāṁv", "village"], ["देश", "deś", "country"],
      ["सड़क", "saṛak", "road / street"], ["बाज़ार", "bāzār", "market"],
      ["दुकान", "dukān", "shop"], ["बैंक", "baiṅk", "bank"],
      ["स्कूल", "skūl", "school"], ["मंदिर", "mandir", "temple"],
      ["मस्जिद", "masjid", "mosque"], ["गिरजाघर", "girjāghar", "church"],
      ["संग्रहालय", "saṅgrahālay", "museum"], ["पार्क", "pārk", "park"],
      ["होटल", "hoṭal", "hotel"], ["हवाई अड्डा", "havāī aḍḍā", "airport"],
      ["स्टेशन", "sṭeśan", "station"], ["पुस्तकालय", "pustakālay", "library"],
      ["दफ़्तर", "daftar", "office"], ["सिनेमा", "sinemā", "cinema"],
      ["मोहल्ला", "mohallā", "neighbourhood"], ["अस्पताल", "aspatāl", "hospital"],
      ["सीमा", "sīmā", "border"], ["रास्ता", "rāstā", "way / path"],
    ]),
    V("travel", [
      ["यात्रा", "yātrā", "journey"], ["सफ़र", "safar", "travel"],
      ["गाड़ी", "gāṛī", "car / vehicle"], ["बस", "bas", "bus"],
      ["रेलगाड़ी", "relgāṛī", "train"], ["हवाई जहाज़", "havāī jahāz", "aeroplane"],
      ["साइकिल", "sāikil", "bicycle"], ["नाव", "nāv", "boat"],
      ["रिक्शा", "rikśā", "rickshaw"], ["टिकट", "ṭikaṭ", "ticket"],
      ["पासपोर्ट", "pāsporṭ", "passport"], ["सूटकेस", "sūṭkes", "suitcase"],
      ["सामान", "sāmān", "luggage / things"], ["नक्शा", "nakśā", "map"],
      ["रास्ता", "rāstā", "route"], ["सीधे", "sīdhe", "straight ahead"],
      ["बाएँ", "bāeṁ", "to the left"], ["दाएँ", "dāeṁ", "to the right"],
      ["आना-जाना", "ānā-jānā", "coming and going"],
      ["देर", "der", "delay"], ["पहुँचना", "pahuṁcnā", "to arrive"],
      ["निकलना", "nikalnā", "to leave / set out"],
      ["खो जाना", "kho jānā", "to get lost"], ["सीमा शुल्क", "sīmā śulk", "customs"],
    ]),
    V("time", [
      ["समय", "samay", "time"], ["घंटा", "ghaṇṭā", "hour"],
      ["मिनट", "minaṭ", "minute"], ["सेकंड", "sekaṇḍ", "second"],
      ["दिन", "din", "day"], ["हफ़्ता", "haftā", "week"],
      ["महीना", "mahīnā", "month"], ["साल", "sāl", "year"],
      ["सुबह", "subah", "morning"], ["दोपहर", "dopahar", "afternoon"],
      ["शाम", "śām", "evening"], ["रात", "rāt", "night"],
      ["सोमवार", "somvār", "Monday"], ["मंगलवार", "maṅgalvār", "Tuesday"],
      ["बुधवार", "budhvār", "Wednesday"], ["गुरुवार", "guruvār", "Thursday"],
      ["शुक्रवार", "śukravār", "Friday"], ["शनिवार", "śanivār", "Saturday"],
      ["रविवार", "ravivār", "Sunday"], ["जनवरी", "janvarī", "January"],
      ["फ़रवरी", "farvarī", "February"], ["मार्च", "mārc", "March"],
      ["अप्रैल", "aprail", "April"], ["गर्मी", "garmī", "summer / heat"],
      ["सर्दी", "sardī", "winter / cold"], ["बरसात", "barsāt", "rainy season"],
      ["घड़ी", "ghaṛī", "clock / watch"], ["तारीख़", "tārīkh", "date"],
    ]),
    V("work", [
      ["काम", "kām", "work"], ["नौकरी", "naukrī", "job"],
      ["कंपनी", "kampanī", "company"], ["मालिक", "mālik", "boss / owner"],
      ["कर्मचारी", "karmcārī", "employee"], ["तनख़्वाह", "tankhvāh", "salary"],
      ["पैसा", "paisā", "money"], ["रुपया", "rupayā", "rupee"],
      ["क़ीमत", "qīmat", "price"], ["महँगा", "mahaṁgā", "expensive"],
      ["सस्ता", "sastā", "cheap"], ["ख़रीदना", "kharīdnā", "to buy"],
      ["बेचना", "becnā", "to sell"], ["बैठक", "baiṭhak", "meeting"],
      ["ग्राहक", "grāhak", "customer"], ["बिल", "bil", "bill"],
      ["समझौता", "samjhautā", "agreement"], ["कार्ड", "kārḍ", "card"],
      ["नक़द", "naqad", "cash"], ["व्यापार", "vyāpār", "business"],
      ["इंजीनियर", "iñjīniyar", "engineer"], ["वकील", "vakīl", "lawyer"],
      ["किसान", "kisān", "farmer"], ["कमाना", "kamānā", "to earn"],
    ]),
    V("school", [
      ["स्कूल", "skūl", "school"], ["विद्यालय", "vidyālay", "school (formal)"],
      ["विश्वविद्यालय", "viśvavidyālay", "university"],
      ["कक्षा", "kakṣā", "class"], ["छात्र", "chātra", "student"],
      ["शिक्षक", "śikṣak", "teacher"], ["गुरु", "guru", "teacher / master"],
      ["किताब", "kitāb", "book"], ["कॉपी", "kŏpī", "notebook"],
      ["पेंसिल", "pensil", "pencil"], ["क़लम", "qalam", "pen"],
      ["काग़ज़", "kāgaz", "paper"], ["शब्द", "śabd", "word"],
      ["वाक्य", "vākya", "sentence"], ["पाठ", "pāṭh", "lesson"],
      ["परीक्षा", "parīkṣā", "exam"], ["गृहकार्य", "gṛhkārya", "homework"],
      ["अंक", "aṅk", "marks / number"], ["सीखना", "sīkhnā", "to learn"],
      ["पढ़ाई", "paṛhāī", "studies"], ["भाषा", "bhāṣā", "language"],
      ["इतिहास", "itihās", "history"], ["गणित", "gaṇit", "maths"],
      ["विज्ञान", "vijñān", "science"], ["ज्ञान", "jñān", "knowledge"],
    ]),
    V("tech", [
      ["कंप्यूटर", "kampyūṭar", "computer"], ["फ़ोन", "fon", "phone"],
      ["मोबाइल", "mobāil", "mobile phone"], ["स्क्रीन", "skrīn", "screen"],
      ["कीबोर्ड", "kīborḍ", "keyboard"], ["माउस", "māus", "mouse"],
      ["इंटरनेट", "iṇṭarneṭ", "internet"], ["नेटवर्क", "neṭvark", "network"],
      ["ईमेल", "īmel", "email"], ["पासवर्ड", "pāsvarḍ", "password"],
      ["फ़ाइल", "fāil", "file"], ["फ़ोल्डर", "folḍar", "folder"],
      ["ऐप", "aip", "app"], ["सॉफ़्टवेयर", "sŏfṭveyar", "software"],
      ["डाउनलोड", "ḍāunloḍ", "download"], ["अपलोड", "aploḍ", "upload"],
      ["सेव करना", "sev karnā", "to save"], ["मिटाना", "miṭānā", "to delete"],
      ["खोजना", "khojnā", "to search"], ["चालू करना", "cālū karnā", "to switch on"],
      ["बंद करना", "band karnā", "to switch off"], ["कैमरा", "kaimrā", "camera"],
      ["बैटरी", "baiṭrī", "battery"], ["लिंक", "liṅk", "link"],
      ["तकनीक", "taknīk", "technology"],
    ]),
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["नमस्ते, आप कैसे हैं?", "namaste, āp kaise haiṁ", "Hello, how are you?",
        [["नमस्ते", "namaste"], ["आप", "āp"], ["कैसे", "kaise"], ["हैं", "haiṁ"]]],
      ["मैं ठीक हूँ, धन्यवाद", "maiṁ ṭhīk hūṁ, dhanyavād", "I am fine, thank you",
        [["मैं", "maiṁ"], ["ठीक", "ṭhīk"], ["हूँ", "hūṁ"], ["धन्यवाद", "dhanyavād"]]],
      ["आपका नाम क्या है?", "āpkā nām kyā hai", "What is your name?",
        [["आपका", "āpkā"], ["नाम", "nām"], ["क्या", "kyā"], ["है", "hai"]]],
      ["मेरा नाम राहुल है", "merā nām rāhul hai", "My name is Rahul",
        [["मेरा", "merā"], ["नाम", "nām"], ["राहुल", "rāhul"], ["है", "hai"]]],
      ["मुझे समझ नहीं आया", "mujhe samajh nahīṁ āyā", "I didn't understand",
        [["मुझे", "mujhe"], ["समझ", "samajh"], ["नहीं", "nahīṁ"], ["आया", "āyā"]]],
      ["कृपया फिर से कहिए", "kṛpayā phir se kahie", "Please say it again",
        [["कृपया", "kṛpayā"], ["फिर", "phir"], ["से", "se"], ["कहिए", "kahie"]]],
      ["क्या आप अंग्रेज़ी बोलते हैं?", "kyā āp aṅgrezī bolte haiṁ", "Do you speak English?",
        [["क्या", "kyā"], ["आप", "āp"], ["अंग्रेज़ी", "aṅgrezī"], ["बोलते", "bolte"], ["हैं", "haiṁ"]]],
      ["आपसे मिलकर खुशी हुई", "āpse milkar khuśī huī", "Pleased to meet you",
        [["आपसे", "āpse"], ["मिलकर", "milkar"], ["खुशी", "khuśī"], ["हुई", "huī"]]],
    ]),
    S("food", [
      ["मुझे पानी चाहिए", "mujhe pānī cāhie", "I want water",
        [["मुझे", "mujhe"], ["पानी", "pānī"], ["चाहिए", "cāhie"]]],
      ["मुझे भूख लगी है", "mujhe bhūkh lagī hai", "I am hungry",
        [["मुझे", "mujhe"], ["भूख", "bhūkh"], ["लगी", "lagī"], ["है", "hai"]]],
      ["एक चाय दीजिए", "ek cāy dījie", "Please give me a tea",
        [["एक", "ek"], ["चाय", "cāy"], ["दीजिए", "dījie"]]],
      ["खाना बहुत स्वादिष्ट है", "khānā bahut svādiṣṭ hai", "The food is very tasty",
        [["खाना", "khānā"], ["बहुत", "bahut"], ["स्वादिष्ट", "svādiṣṭ"], ["है", "hai"]]],
      ["मैं मांस नहीं खाता", "maiṁ māṁs nahīṁ khātā", "I don't eat meat",
        [["मैं", "maiṁ"], ["मांस", "māṁs"], ["नहीं", "nahīṁ"], ["खाता", "khātā"]]],
      ["बिल लाइए", "bil lāie", "Please bring the bill",
        [["बिल", "bil"], ["लाइए", "lāie"]]],
    ]),
    S("travel", [
      ["स्टेशन कहाँ है?", "sṭeśan kahāṁ hai", "Where is the station?",
        [["स्टेशन", "sṭeśan"], ["कहाँ", "kahāṁ"], ["है", "hai"]]],
      ["मुझे दिल्ली का टिकट चाहिए", "mujhe dillī kā ṭikaṭ cāhie",
        "I want a ticket to Delhi",
        [["मुझे", "mujhe"], ["दिल्ली", "dillī"], ["का", "kā"], ["टिकट", "ṭikaṭ"], ["चाहिए", "cāhie"]]],
      ["रेलगाड़ी आठ बजे आती है", "relgāṛī āṭh baje ātī hai", "The train comes at eight",
        [["रेलगाड़ी", "relgāṛī"], ["आठ", "āṭh"], ["बजे", "baje"], ["आती", "ātī"], ["है", "hai"]]],
      ["मैं रास्ता भूल गया", "maiṁ rāstā bhūl gayā", "I have lost my way",
        [["मैं", "maiṁ"], ["रास्ता", "rāstā"], ["भूल", "bhūl"], ["गया", "gayā"]]],
      ["दाएँ मुड़िए", "dāeṁ muṛie", "Turn right",
        [["दाएँ", "dāeṁ"], ["मुड़िए", "muṛie"]]],
    ]),
    S("home", [
      ["मैं एक छोटे घर में रहता हूँ", "maiṁ ek choṭe ghar meṁ rahtā hūṁ",
        "I live in a small house",
        [["मैं", "maiṁ"], ["एक", "ek"], ["छोटे", "choṭe"], ["घर", "ghar"], ["में", "meṁ"], ["रहता", "rahtā"], ["हूँ", "hūṁ"]]],
      ["दरवाज़ा खुला है", "darvāzā khulā hai", "The door is open",
        [["दरवाज़ा", "darvāzā"], ["खुला", "khulā"], ["है", "hai"]]],
      ["मेरा परिवार बड़ा है", "merā parivār baṛā hai", "My family is big",
        [["मेरा", "merā"], ["परिवार", "parivār"], ["बड़ा", "baṛā"], ["है", "hai"]]],
    ]),
    S("time", [
      ["क्या समय हुआ है?", "kyā samay huā hai", "What time is it?",
        [["क्या", "kyā"], ["समय", "samay"], ["हुआ", "huā"], ["है", "hai"]]],
      ["आज सोमवार है", "āj somvār hai", "Today is Monday",
        [["आज", "āj"], ["सोमवार", "somvār"], ["है", "hai"]]],
      ["कल मैं बाज़ार जाऊँगा", "kal maiṁ bāzār jāūṁgā", "Tomorrow I will go to the market",
        [["कल", "kal"], ["मैं", "maiṁ"], ["बाज़ार", "bāzār"], ["जाऊँगा", "jāūṁgā"]]],
      ["मैं हमेशा सुबह काम करता हूँ", "maiṁ hameśā subah kām kartā hūṁ",
        "I always work in the morning",
        [["मैं", "maiṁ"], ["हमेशा", "hameśā"], ["सुबह", "subah"], ["काम", "kām"], ["करता", "kartā"], ["हूँ", "hūṁ"]]],
    ]),
    S("school", [
      ["मैं रोज़ हिंदी पढ़ता हूँ", "maiṁ roz hindī paṛhtā hūṁ", "I study Hindi every day",
        [["मैं", "maiṁ"], ["रोज़", "roz"], ["हिंदी", "hindī"], ["पढ़ता", "paṛhtā"], ["हूँ", "hūṁ"]]],
      ["यह किताब बहुत अच्छी है", "yah kitāb bahut acchī hai", "This book is very good",
        [["यह", "yah"], ["किताब", "kitāb"], ["बहुत", "bahut"], ["अच्छी", "acchī"], ["है", "hai"]]],
      ["क्या आप मेरी मदद कर सकते हैं?", "kyā āp merī madad kar sakte haiṁ",
        "Can you help me?",
        [["क्या", "kyā"], ["आप", "āp"], ["मेरी", "merī"], ["मदद", "madad"], ["कर", "kar"], ["सकते", "sakte"], ["हैं", "haiṁ"]]],
    ]),
    S("health", [
      ["मेरे सिर में दर्द है", "mere sir meṁ dard hai", "I have a headache",
        [["मेरे", "mere"], ["सिर", "sir"], ["में", "meṁ"], ["दर्द", "dard"], ["है", "hai"]]],
      ["मुझे डॉक्टर चाहिए", "mujhe ḍŏkṭar cāhie", "I need a doctor",
        [["मुझे", "mujhe"], ["डॉक्टर", "ḍŏkṭar"], ["चाहिए", "cāhie"]]],
      ["मेरी तबीयत ठीक नहीं है", "merī tabīyat ṭhīk nahīṁ hai", "I don't feel well",
        [["मेरी", "merī"], ["तबीयत", "tabīyat"], ["ठीक", "ṭhīk"], ["नहीं", "nahīṁ"], ["है", "hai"]]],
    ]),
    S("work", [
      ["यह कितने का है?", "yah kitne kā hai", "How much is this?",
        [["यह", "yah"], ["कितने", "kitne"], ["का", "kā"], ["है", "hai"]]],
      ["यह बहुत महँगा है", "yah bahut mahaṁgā hai", "This is very expensive",
        [["यह", "yah"], ["बहुत", "bahut"], ["महँगा", "mahaṁgā"], ["है", "hai"]]],
      ["मैं दफ़्तर में काम करता हूँ", "maiṁ daftar meṁ kām kartā hūṁ",
        "I work in an office",
        [["मैं", "maiṁ"], ["दफ़्तर", "daftar"], ["में", "meṁ"], ["काम", "kām"], ["करता", "kartā"], ["हूँ", "hūṁ"]]],
    ]),
  );

  /* ----------------------------- Conjugation ------------------------------
   * Masculine forms are used throughout (Hindi verbs also agree with gender);
   * the ending -tā/-tī and -gā/-gī is the piece to notice. */
  const CONJUGATION = [
    C("होना", "honā", "be", [
      ["मैं था", "maiṁ thā", "I was", "I", "past"],
      ["तुम थे", "tum the", "you were", "you", "past"],
      ["वह था", "vah thā", "he was", "he", "past"],
      ["वह थी", "vah thī", "she was", "she", "past"],
      ["हम थे", "ham the", "we were", "we", "past"],
      ["वे थे", "ve the", "they were", "they", "past"],
      ["मैं हूँ", "maiṁ hūṁ", "I am", "I", "present"],
      ["तुम हो", "tum ho", "you are", "you", "present"],
      ["वह है", "vah hai", "he is", "he", "present"],
      ["हम हैं", "ham haiṁ", "we are", "we", "present"],
      ["वे हैं", "ve haiṁ", "they are", "they", "present"],
      ["मैं हूँगा", "maiṁ hūṁgā", "I will be", "I", "future"],
      ["तुम होगे", "tum hoge", "you will be", "you", "future"],
      ["वह होगा", "vah hogā", "he will be", "he", "future"],
      ["हम होंगे", "ham hoṁge", "we will be", "we", "future"],
      ["वे होंगे", "ve hoṁge", "they will be", "they", "future"],
    ]),
    C("करना", "karnā", "do", [
      ["मैंने किया", "maiṁne kiyā", "I did", "I", "past"],
      ["तुमने किया", "tumne kiyā", "you did", "you", "past"],
      ["उसने किया", "usne kiyā", "he did", "he", "past"],
      ["हमने किया", "hamne kiyā", "we did", "we", "past"],
      ["उन्होंने किया", "unhoṁne kiyā", "they did", "they", "past"],
      ["मैं करता हूँ", "maiṁ kartā hūṁ", "I do", "I", "present"],
      ["तुम करते हो", "tum karte ho", "you do", "you", "present"],
      ["वह करता है", "vah kartā hai", "he does", "he", "present"],
      ["हम करते हैं", "ham karte haiṁ", "we do", "we", "present"],
      ["वे करते हैं", "ve karte haiṁ", "they do", "they", "present"],
      ["मैं करूँगा", "maiṁ karūṁgā", "I will do", "I", "future"],
      ["तुम करोगे", "tum karoge", "you will do", "you", "future"],
      ["वह करेगा", "vah karegā", "he will do", "he", "future"],
      ["हम करेंगे", "ham kareṁge", "we will do", "we", "future"],
      ["वे करेंगे", "ve kareṁge", "they will do", "they", "future"],
    ]),
    C("जाना", "jānā", "go", [
      ["मैं गया", "maiṁ gayā", "I went", "I", "past"],
      ["तुम गए", "tum gae", "you went", "you", "past"],
      ["वह गया", "vah gayā", "he went", "he", "past"],
      ["हम गए", "ham gae", "we went", "we", "past"],
      ["वे गए", "ve gae", "they went", "they", "past"],
      ["मैं जाता हूँ", "maiṁ jātā hūṁ", "I go", "I", "present"],
      ["तुम जाते हो", "tum jāte ho", "you go", "you", "present"],
      ["वह जाता है", "vah jātā hai", "he goes", "he", "present"],
      ["हम जाते हैं", "ham jāte haiṁ", "we go", "we", "present"],
      ["वे जाते हैं", "ve jāte haiṁ", "they go", "they", "present"],
      ["मैं जाऊँगा", "maiṁ jāūṁgā", "I will go", "I", "future"],
      ["तुम जाओगे", "tum jāoge", "you will go", "you", "future"],
      ["वह जाएगा", "vah jāegā", "he will go", "he", "future"],
      ["हम जाएँगे", "ham jāeṁge", "we will go", "we", "future"],
      ["वे जाएँगे", "ve jāeṁge", "they will go", "they", "future"],
    ]),
    C("खाना", "khānā", "eat", [
      ["मैंने खाया", "maiṁne khāyā", "I ate", "I", "past"],
      ["तुमने खाया", "tumne khāyā", "you ate", "you", "past"],
      ["उसने खाया", "usne khāyā", "he ate", "he", "past"],
      ["हमने खाया", "hamne khāyā", "we ate", "we", "past"],
      ["उन्होंने खाया", "unhoṁne khāyā", "they ate", "they", "past"],
      ["मैं खाता हूँ", "maiṁ khātā hūṁ", "I eat", "I", "present"],
      ["तुम खाते हो", "tum khāte ho", "you eat", "you", "present"],
      ["वह खाता है", "vah khātā hai", "he eats", "he", "present"],
      ["हम खाते हैं", "ham khāte haiṁ", "we eat", "we", "present"],
      ["वे खाते हैं", "ve khāte haiṁ", "they eat", "they", "present"],
      ["मैं खाऊँगा", "maiṁ khāūṁgā", "I will eat", "I", "future"],
      ["तुम खाओगे", "tum khāoge", "you will eat", "you", "future"],
      ["वह खाएगा", "vah khāegā", "he will eat", "he", "future"],
      ["हम खाएँगे", "ham khāeṁge", "we will eat", "we", "future"],
      ["वे खाएँगे", "ve khāeṁge", "they will eat", "they", "future"],
    ]),
    C("पीना", "pīnā", "drink", [
      ["मैंने पिया", "maiṁne piyā", "I drank", "I", "past"],
      ["तुमने पिया", "tumne piyā", "you drank", "you", "past"],
      ["उसने पिया", "usne piyā", "he drank", "he", "past"],
      ["हमने पिया", "hamne piyā", "we drank", "we", "past"],
      ["उन्होंने पिया", "unhoṁne piyā", "they drank", "they", "past"],
      ["मैं पीता हूँ", "maiṁ pītā hūṁ", "I drink", "I", "present"],
      ["तुम पीते हो", "tum pīte ho", "you drink", "you", "present"],
      ["वह पीता है", "vah pītā hai", "he drinks", "he", "present"],
      ["हम पीते हैं", "ham pīte haiṁ", "we drink", "we", "present"],
      ["वे पीते हैं", "ve pīte haiṁ", "they drink", "they", "present"],
      ["मैं पीऊँगा", "maiṁ pīūṁgā", "I will drink", "I", "future"],
      ["तुम पीओगे", "tum pīoge", "you will drink", "you", "future"],
      ["वह पीएगा", "vah pīegā", "he will drink", "he", "future"],
      ["हम पीएँगे", "ham pīeṁge", "we will drink", "we", "future"],
      ["वे पीएँगे", "ve pīeṁge", "they will drink", "they", "future"],
    ]),
    C("बोलना", "bolnā", "speak", [
      ["मैं बोला", "maiṁ bolā", "I spoke", "I", "past"],
      ["तुम बोले", "tum bole", "you spoke", "you", "past"],
      ["वह बोला", "vah bolā", "he spoke", "he", "past"],
      ["हम बोले", "ham bole", "we spoke", "we", "past"],
      ["वे बोले", "ve bole", "they spoke", "they", "past"],
      ["मैं बोलता हूँ", "maiṁ boltā hūṁ", "I speak", "I", "present"],
      ["तुम बोलते हो", "tum bolte ho", "you speak", "you", "present"],
      ["वह बोलता है", "vah boltā hai", "he speaks", "he", "present"],
      ["हम बोलते हैं", "ham bolte haiṁ", "we speak", "we", "present"],
      ["वे बोलते हैं", "ve bolte haiṁ", "they speak", "they", "present"],
      ["मैं बोलूँगा", "maiṁ bolūṁgā", "I will speak", "I", "future"],
      ["तुम बोलोगे", "tum bologe", "you will speak", "you", "future"],
      ["वह बोलेगा", "vah bolegā", "he will speak", "he", "future"],
      ["हम बोलेंगे", "ham boleṁge", "we will speak", "we", "future"],
      ["वे बोलेंगे", "ve boleṁge", "they will speak", "they", "future"],
    ]),
    C("देखना", "dekhnā", "see", [
      ["मैंने देखा", "maiṁne dekhā", "I saw", "I", "past"],
      ["तुमने देखा", "tumne dekhā", "you saw", "you", "past"],
      ["उसने देखा", "usne dekhā", "he saw", "he", "past"],
      ["हमने देखा", "hamne dekhā", "we saw", "we", "past"],
      ["उन्होंने देखा", "unhoṁne dekhā", "they saw", "they", "past"],
      ["मैं देखता हूँ", "maiṁ dekhtā hūṁ", "I see", "I", "present"],
      ["तुम देखते हो", "tum dekhte ho", "you see", "you", "present"],
      ["वह देखता है", "vah dekhtā hai", "he sees", "he", "present"],
      ["हम देखते हैं", "ham dekhte haiṁ", "we see", "we", "present"],
      ["वे देखते हैं", "ve dekhte haiṁ", "they see", "they", "present"],
      ["मैं देखूँगा", "maiṁ dekhūṁgā", "I will see", "I", "future"],
      ["तुम देखोगे", "tum dekhoge", "you will see", "you", "future"],
      ["वह देखेगा", "vah dekhegā", "he will see", "he", "future"],
      ["हम देखेंगे", "ham dekheṁge", "we will see", "we", "future"],
      ["वे देखेंगे", "ve dekheṁge", "they will see", "they", "future"],
    ]),
    C("आना", "ānā", "come", [
      ["मैं आया", "maiṁ āyā", "I came", "I", "past"],
      ["तुम आए", "tum āe", "you came", "you", "past"],
      ["वह आया", "vah āyā", "he came", "he", "past"],
      ["हम आए", "ham āe", "we came", "we", "past"],
      ["वे आए", "ve āe", "they came", "they", "past"],
      ["मैं आता हूँ", "maiṁ ātā hūṁ", "I come", "I", "present"],
      ["तुम आते हो", "tum āte ho", "you come", "you", "present"],
      ["वह आता है", "vah ātā hai", "he comes", "he", "present"],
      ["हम आते हैं", "ham āte haiṁ", "we come", "we", "present"],
      ["वे आते हैं", "ve āte haiṁ", "they come", "they", "present"],
      ["मैं आऊँगा", "maiṁ āūṁgā", "I will come", "I", "future"],
      ["तुम आओगे", "tum āoge", "you will come", "you", "future"],
      ["वह आएगा", "vah āegā", "he will come", "he", "future"],
      ["हम आएँगे", "ham āeṁge", "we will come", "we", "future"],
      ["वे आएँगे", "ve āeṁge", "they will come", "they", "future"],
    ]),
    C("पढ़ना", "paṛhnā", "read / study", [
      ["मैंने पढ़ा", "maiṁne paṛhā", "I read", "I", "past"],
      ["तुमने पढ़ा", "tumne paṛhā", "you read", "you", "past"],
      ["उसने पढ़ा", "usne paṛhā", "he read", "he", "past"],
      ["हमने पढ़ा", "hamne paṛhā", "we read", "we", "past"],
      ["उन्होंने पढ़ा", "unhoṁne paṛhā", "they read", "they", "past"],
      ["मैं पढ़ता हूँ", "maiṁ paṛhtā hūṁ", "I read", "I", "present"],
      ["तुम पढ़ते हो", "tum paṛhte ho", "you read", "you", "present"],
      ["वह पढ़ता है", "vah paṛhtā hai", "he reads", "he", "present"],
      ["हम पढ़ते हैं", "ham paṛhte haiṁ", "we read", "we", "present"],
      ["वे पढ़ते हैं", "ve paṛhte haiṁ", "they read", "they", "present"],
      ["मैं पढ़ूँगा", "maiṁ paṛhūṁgā", "I will read", "I", "future"],
      ["तुम पढ़ोगे", "tum paṛhoge", "you will read", "you", "future"],
      ["वह पढ़ेगा", "vah paṛhegā", "he will read", "he", "future"],
      ["हम पढ़ेंगे", "ham paṛheṁge", "we will read", "we", "future"],
      ["वे पढ़ेंगे", "ve paṛheṁge", "they will read", "they", "future"],
    ]),
    C("लिखना", "likhnā", "write", [
      ["मैंने लिखा", "maiṁne likhā", "I wrote", "I", "past"],
      ["तुमने लिखा", "tumne likhā", "you wrote", "you", "past"],
      ["उसने लिखा", "usne likhā", "he wrote", "he", "past"],
      ["हमने लिखा", "hamne likhā", "we wrote", "we", "past"],
      ["उन्होंने लिखा", "unhoṁne likhā", "they wrote", "they", "past"],
      ["मैं लिखता हूँ", "maiṁ likhtā hūṁ", "I write", "I", "present"],
      ["तुम लिखते हो", "tum likhte ho", "you write", "you", "present"],
      ["वह लिखता है", "vah likhtā hai", "he writes", "he", "present"],
      ["हम लिखते हैं", "ham likhte haiṁ", "we write", "we", "present"],
      ["वे लिखते हैं", "ve likhte haiṁ", "they write", "they", "present"],
      ["मैं लिखूँगा", "maiṁ likhūṁgā", "I will write", "I", "future"],
      ["तुम लिखोगे", "tum likhoge", "you will write", "you", "future"],
      ["वह लिखेगा", "vah likhegā", "he will write", "he", "future"],
      ["हम लिखेंगे", "ham likheṁge", "we will write", "we", "future"],
      ["वे लिखेंगे", "ve likheṁge", "they will write", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Effort",
      l1: "जहाँ चाह,", l2: "वहाँ राह।",
      tr1: "jahāṁ cāh", tr2: "vahāṁ rāh",
      en: "Where there is a wish, there is a road." },
    { n: 2, chapterEn: "Patience",
      l1: "धीरे-धीरे रे मना,", l2: "धीरे सब कुछ होय।",
      tr1: "dhīre-dhīre re manā", tr2: "dhīre sab kuch hoy",
      en: "Slowly, O mind — slowly everything comes to be." },
    { n: 3, chapterEn: "Appearances",
      l1: "हाथी के दाँत खाने के और,", l2: "दिखाने के और।",
      tr1: "hāthī ke dāṁt khāne ke aur", tr2: "dikhāne ke aur",
      en: "An elephant has one set of teeth for eating and another for show." },
    { n: 4, chapterEn: "Prudence",
      l1: "अब पछताए होत क्या,", l2: "जब चिड़िया चुग गई खेत।",
      tr1: "ab pachtāe hot kyā", tr2: "jab ciṛiyā cug gaī khet",
      en: "What use is regret now, when the birds have already eaten the field?" },
    { n: 5, chapterEn: "Company",
      l1: "संगत का असर", l2: "पड़ता ही है।",
      tr1: "saṅgat kā asar", tr2: "paṛtā hī hai",
      en: "The company you keep always leaves its mark." },
    { n: 6, chapterEn: "Knowledge",
      l1: "नीम हकीम", l2: "ख़तरा-ए-जान।",
      tr1: "nīm hakīm", tr2: "khatrā-e-jān",
      en: "A half-trained doctor is a danger to life." },
    { n: 7, chapterEn: "Truth",
      l1: "सच को", l2: "आँच नहीं।",
      tr1: "sac ko", tr2: "āṁc nahīṁ",
      en: "Truth cannot be burned." },
    { n: 8, chapterEn: "Unity",
      l1: "एक और एक", l2: "ग्यारह होते हैं।",
      tr1: "ek aur ek", tr2: "gyārah hote haiṁ",
      en: "One and one make eleven — together people are far stronger." },
    { n: 9, chapterEn: "Work",
      l1: "करत करत अभ्यास के", l2: "जड़मति होत सुजान।",
      tr1: "karat karat abhyās ke", tr2: "jaṛmati hot sujān",
      en: "With constant practice even a dull mind becomes wise." },
    { n: 10, chapterEn: "Prudence",
      l1: "दूध का जला", l2: "छाछ भी फूँक-फूँक कर पीता है।",
      tr1: "dūdh kā jalā", tr2: "chāch bhī phūṁk-phūṁk kar pītā hai",
      en: "One burned by milk blows even on buttermilk before drinking." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("hindi", {
    icons: {
      alphabet: "वर्णमाला", greetings: "नमस्ते", numbers: "संख्या", colors: "रंग",
      family: "परिवार", people: "लोग", pronouns: "सर्वनाम", questions: "प्रश्न",
      grammar: "अव्यय", adjectives: "विशेषण", adverbs: "क्रिया-विशेषण", verbs: "क्रिया",
      food: "खाना", body: "शरीर", health: "सेहत", clothing: "कपड़े", home: "घर",
      animals: "जानवर", nature: "प्रकृति", places: "जगह", travel: "यात्रा",
      time: "समय", work: "काम", school: "स्कूल", tech: "तकनीक", sentences: "वाक्य",
    },
    ui: { account: "खाता", progress: "प्रगति", search: "खोज" },
    alphabet: ALPHABET,
    alphabetTitle: "Devanagari",
    alphabetLabels: ["Svar — vowels & mātrās", "Vyañjan — consonants"],
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "दोहराव", vocab: "शब्द", sentence: "वाक्य", conjugation: "क्रिया",
      listening: "सुनना", mixed: "मिश्रित", reading: "कहावतें",
    },
    reading: {
      id: "kahavat", title: "Proverbs", native: "कहावतें",
      desc: "Classic Hindi sayings, line by line",
      blurb: "कहावतें — proverbs and couplets heard across the Hindi-speaking world.",
      unit: "sayings", numLabel: "कहावत",
      lineQuestion: "Which line completes this saying?",
      items: PROVERBS,
    },
  });
})();
