/* ============================================================================
 * Italian course — data only.
 *
 * `ta` is the Italian, `tr` a plain-English respelling (stressed syllable in
 * CAPS — Italian spelling doesn't mark stress, so this is the one thing a
 * reader can't guess), `en` the meaning. Nouns carry their article.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------ Alphabet ------------------------------- */
  const LETTERS = A([
    ["A a", "ah"], ["B b", "bee"], ["C c", "chee"], ["D d", "dee"], ["E e", "eh"],
    ["F f", "EF-feh"], ["G g", "jee"], ["H h", "AH-kah"], ["I i", "ee"],
    ["L l", "EL-leh"], ["M m", "EM-meh"], ["N n", "EN-neh"], ["O o", "oh"],
    ["P p", "pee"], ["Q q", "koo"], ["R r", "EHR-reh"], ["S s", "ES-seh"],
    ["T t", "tee"], ["U u", "oo"], ["V v", "voo"], ["Z z", "DZEH-tah"],
    ["J j", "ee LOON-gah"], ["K k", "KAP-pah"], ["W w", "VOO DOP-pyah"],
    ["X x", "EEKS"], ["Y y", "EEP-see-lohn"],
  ]);
  const SOUNDS = A([
    ["ca / co / cu", "kah koh koo", "hard c"], ["ce / ci", "cheh chee", "soft c — 'ch'"],
    ["ga / go / gu", "gah goh goo", "hard g"], ["ge / gi", "jeh jee", "soft g — 'j'"],
    ["ch", "k", "hard c before e/i"], ["gh", "g", "hard g before e/i"],
    ["gli", "lyee", "as in 'famiglia'"], ["gn", "ny", "as in 'gnocchi'"],
    ["sc + e/i", "sh", "as in 'pesce'"], ["z", "ts / dz", "as in 'pizza'"],
    ["h", "(silent)", "never pronounced"],
    ["double consonants", "held longer", "'nonno' ≠ 'nono'"],
  ]);
  const ALPHABET = { vowels: LETTERS, consonants: SOUNDS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["ciao", "CHOW", "hi / bye"],
      ["buongiorno", "bwohn-JOR-noh", "good morning / hello"],
      ["buonasera", "bwoh-nah-SEH-rah", "good evening"],
      ["buonanotte", "bwoh-nah-NOT-teh", "good night"],
      ["arrivederci", "ah-ree-veh-DEHR-chee", "goodbye"],
      ["salve", "SAHL-veh", "hello (neutral)"],
      ["grazie", "GRAHT-tsyeh", "thank you"],
      ["grazie mille", "GRAHT-tsyeh MEEL-leh", "thanks a lot"],
      ["prego", "PREH-goh", "you're welcome / please"],
      ["per favore", "pehr fah-VOH-reh", "please"],
      ["sì", "SEE", "yes"], ["no", "NOH", "no"],
      ["scusi", "SKOO-zee", "excuse me (formal)"],
      ["scusa", "SKOO-zah", "sorry (informal)"],
      ["mi dispiace", "mee dees-PYAH-cheh", "I'm sorry"],
      ["come stai?", "KOH-meh STAI", "how are you?"],
      ["sto bene", "stoh BEH-neh", "I'm well"],
      ["così così", "koh-ZEE koh-ZEE", "so-so"],
      ["piacere", "pyah-CHEH-reh", "pleased to meet you"],
      ["benvenuto", "ben-veh-NOO-toh", "welcome"],
      ["a presto", "ah PREHS-toh", "see you soon"],
      ["a domani", "ah doh-MAH-nee", "see you tomorrow"],
      ["buon appetito", "bwohn ahp-peh-TEE-toh", "enjoy your meal"],
      ["salute", "sah-LOO-teh", "cheers / bless you"],
      ["auguri", "ow-GOO-ree", "best wishes"],
      ["in bocca al lupo", "een BOK-kah ahl LOO-poh", "good luck"],
      ["va bene", "vah BEH-neh", "okay"],
    ]),
    V("numbers", [
      ["zero", "DZEH-roh", "zero"], ["uno", "OO-noh", "one"], ["due", "DOO-eh", "two"],
      ["tre", "TREH", "three"], ["quattro", "KWAT-troh", "four"],
      ["cinque", "CHEEN-kweh", "five"], ["sei", "SEH-ee", "six"],
      ["sette", "SET-teh", "seven"], ["otto", "OT-toh", "eight"],
      ["nove", "NOH-veh", "nine"], ["dieci", "DYEH-chee", "ten"],
      ["undici", "OON-dee-chee", "eleven"], ["dodici", "DOH-dee-chee", "twelve"],
      ["tredici", "TREH-dee-chee", "thirteen"], ["quattordici", "kwat-TOR-dee-chee", "fourteen"],
      ["quindici", "KWEEN-dee-chee", "fifteen"], ["sedici", "SEH-dee-chee", "sixteen"],
      ["venti", "VEN-tee", "twenty"], ["trenta", "TREN-tah", "thirty"],
      ["quaranta", "kwah-RAHN-tah", "forty"], ["cinquanta", "cheen-KWAHN-tah", "fifty"],
      ["cento", "CHEN-toh", "one hundred"], ["mille", "MEEL-leh", "one thousand"],
      ["primo", "PREE-moh", "first"], ["secondo", "seh-KOHN-doh", "second"],
      ["ultimo", "OOL-tee-moh", "last"], ["la metà", "lah meh-TAH", "half"],
      ["il numero", "eel NOO-meh-roh", "number"],
    ]),
    V("colors", [
      ["rosso", "ROS-soh", "red"], ["blu", "BLOO", "blue"], ["azzurro", "ahd-DZOOR-roh", "light blue"],
      ["verde", "VEHR-deh", "green"], ["giallo", "JAHL-loh", "yellow"],
      ["nero", "NEH-roh", "black"], ["bianco", "BYAHN-koh", "white"],
      ["grigio", "GREE-joh", "grey"], ["marrone", "mahr-ROH-neh", "brown"],
      ["arancione", "ah-rahn-CHOH-neh", "orange"], ["rosa", "ROH-zah", "pink"],
      ["viola", "VYOH-lah", "purple"], ["dorato", "doh-RAH-toh", "golden"],
      ["argentato", "ar-jen-TAH-toh", "silver"], ["chiaro", "KYAH-roh", "light (colour)"],
      ["scuro", "SKOO-roh", "dark"], ["il colore", "eel koh-LOH-reh", "colour"],
      ["colorato", "koh-loh-RAH-toh", "colourful"], ["beige", "BEZH", "beige"],
      ["turchese", "toor-KEH-zeh", "turquoise"], ["brillante", "breel-LAHN-teh", "bright"],
      ["pallido", "PAHL-lee-doh", "pale"],
    ]),
    V("family", [
      ["la famiglia", "lah fah-MEE-lyah", "family"], ["la madre", "lah MAH-dreh", "mother"],
      ["il padre", "eel PAH-dreh", "father"], ["la mamma", "lah MAHM-mah", "mum"],
      ["il papà", "eel pah-PAH", "dad"], ["i genitori", "ee jeh-nee-TOH-ree", "parents"],
      ["il figlio", "eel FEE-lyoh", "son"], ["la figlia", "lah FEE-lyah", "daughter"],
      ["il fratello", "eel frah-TEL-loh", "brother"], ["la sorella", "lah soh-REL-lah", "sister"],
      ["il nonno", "eel NON-noh", "grandfather"], ["la nonna", "lah NON-nah", "grandmother"],
      ["il nipote", "eel nee-POH-teh", "grandson / nephew"],
      ["lo zio", "loh DZEE-oh", "uncle"], ["la zia", "lah DZEE-ah", "aunt"],
      ["il cugino", "eel koo-JEE-noh", "cousin (m)"], ["il marito", "eel mah-REE-toh", "husband"],
      ["la moglie", "lah MOH-lyeh", "wife"], ["il bambino", "eel bahm-BEE-noh", "child (boy)"],
      ["la bambina", "lah bahm-BEE-nah", "child (girl)"],
      ["il neonato", "eel neh-oh-NAH-toh", "newborn"],
      ["il parente", "eel pah-REN-teh", "relative"],
      ["il matrimonio", "eel mah-tree-MOH-nyoh", "wedding"],
      ["il suocero", "eel SWOH-cheh-roh", "father-in-law"],
    ]),
    V("people", [
      ["la persona", "lah pehr-SOH-nah", "person"], ["la gente", "lah JEN-teh", "people"],
      ["l'uomo", "LWOH-moh", "man"], ["la donna", "lah DON-nah", "woman"],
      ["il ragazzo", "eel rah-GAHT-tsoh", "boy"], ["la ragazza", "lah rah-GAHT-tsah", "girl"],
      ["l'amico", "lah-MEE-koh", "friend (m)"], ["l'amica", "lah-MEE-kah", "friend (f)"],
      ["il vicino", "eel vee-CHEE-noh", "neighbour"], ["il signore", "eel see-NYOH-reh", "sir / Mr"],
      ["la signora", "lah see-NYOH-rah", "madam / Mrs"],
      ["il giovane", "eel JOH-vah-neh", "young person"],
      ["l'adulto", "lah-DOOL-toh", "adult"], ["l'anziano", "lahn-TSYAH-noh", "elderly person"],
      ["l'ospite", "LOS-pee-teh", "guest"], ["lo straniero", "loh strah-NYEH-roh", "foreigner"],
      ["il fidanzato", "eel fee-dahn-TSAH-toh", "boyfriend / fiancé"],
      ["la squadra", "lah SKWAH-drah", "team"], ["il gruppo", "eel GROOP-poh", "group"],
      ["il nome", "eel NOH-meh", "name"], ["il cognome", "eel koh-NYOH-meh", "surname"],
      ["il collega", "eel kol-LEH-gah", "colleague"],
    ]),
    V("pronouns", [
      ["io", "EE-oh", "I"], ["tu", "TOO", "you (informal)"], ["lei", "LEH-ee", "she / you (formal)"],
      ["lui", "LOO-ee", "he"], ["noi", "NOH-ee", "we"], ["voi", "VOH-ee", "you (plural)"],
      ["loro", "LOH-roh", "they"], ["mi", "MEE", "me"], ["ti", "TEE", "you (object)"],
      ["lo", "LOH", "him / it"], ["la", "LAH", "her / it"], ["ci", "CHEE", "us / there"],
      ["gli", "LYEE", "to him / to them"], ["le", "LEH", "to her"],
      ["mio", "MEE-oh", "my"], ["tuo", "TOO-oh", "your"], ["suo", "SOO-oh", "his / her"],
      ["nostro", "NOS-troh", "our"], ["vostro", "VOS-troh", "your (pl)"],
      ["questo", "KWES-toh", "this"], ["quello", "KWEL-loh", "that"],
      ["qualcuno", "kwahl-KOO-noh", "someone"], ["nessuno", "nes-SOO-noh", "nobody"],
      ["tutti", "TOOT-tee", "everyone"], ["si", "SEE", "oneself"],
      ["ne", "NEH", "of it / of them"],
    ]),
    V("questions", [
      ["che cosa?", "keh KOH-zah", "what?"], ["chi?", "KEE", "who?"],
      ["dove?", "DOH-veh", "where?"], ["quando?", "KWAHN-doh", "when?"],
      ["perché?", "pehr-KEH", "why? / because"], ["come?", "KOH-meh", "how?"],
      ["quale?", "KWAH-leh", "which?"], ["quanto?", "KWAHN-toh", "how much?"],
      ["quanti?", "KWAHN-tee", "how many?"], ["da dove?", "dah DOH-veh", "where from?"],
      ["di chi?", "dee KEE", "whose?"], ["vero?", "VEH-roh", "right? / isn't it?"],
      ["la domanda", "lah doh-MAHN-dah", "question"],
      ["la risposta", "lah rees-POS-tah", "answer"],
      ["chiedere", "KYEH-deh-reh", "to ask"], ["rispondere", "rees-POHN-deh-reh", "to answer"],
      ["quanto costa?", "KWAHN-toh KOS-tah", "how much does it cost?"],
      ["che ore sono?", "keh OH-reh SOH-noh", "what time is it?"],
      ["cosa succede?", "KOH-zah soo-CHEH-deh", "what's happening?"],
      ["dov'è?", "doh-VEH", "where is it?"],
    ]),
    V("grammar", [
      ["e", "EH", "and"], ["o", "OH", "or"], ["ma", "MAH", "but"],
      ["perché", "pehr-KEH", "because"], ["se", "SEH", "if"], ["che", "KEH", "that (conj.)"],
      ["di", "DEE", "of"], ["a", "AH", "to / at"], ["in", "EEN", "in"],
      ["su", "SOO", "on"], ["sotto", "SOT-toh", "under"], ["con", "KOHN", "with"],
      ["senza", "SEN-tsah", "without"], ["per", "PEHR", "for"], ["da", "DAH", "from / by"],
      ["tra", "TRAH", "between"], ["fino a", "FEE-noh ah", "until"],
      ["il", "EEL", "the (m)"], ["la", "LAH", "the (f)"], ["lo", "LOH", "the (m, before s+cons.)"],
      ["un", "OON", "a (m)"], ["una", "OO-nah", "a (f)"],
      ["anche", "AHN-keh", "also"], ["neanche", "neh-AHN-keh", "not even"],
      ["però", "peh-ROH", "however"], ["quindi", "KWEEN-dee", "so / therefore"],
      ["mentre", "MEN-treh", "while"], ["non", "NOHN", "not"],
    ]),
    V("adjectives", [
      ["grande", "GRAHN-deh", "big"], ["piccolo", "PEEK-koh-loh", "small"],
      ["buono", "BWOH-noh", "good"], ["cattivo", "kaht-TEE-voh", "bad"],
      ["nuovo", "NWOH-voh", "new"], ["vecchio", "VEK-kyoh", "old"],
      ["giovane", "JOH-vah-neh", "young"], ["lungo", "LOON-goh", "long"],
      ["corto", "KOR-toh", "short"], ["alto", "AHL-toh", "tall / high"],
      ["basso", "BAHS-soh", "low / short"], ["caldo", "KAHL-doh", "hot"],
      ["freddo", "FRED-doh", "cold"], ["facile", "FAH-chee-leh", "easy"],
      ["difficile", "deef-FEE-chee-leh", "difficult"], ["bello", "BEL-loh", "beautiful"],
      ["brutto", "BROOT-toh", "ugly"], ["forte", "FOR-teh", "strong"],
      ["debole", "DEH-boh-leh", "weak"], ["veloce", "veh-LOH-cheh", "fast"],
      ["lento", "LEN-toh", "slow"], ["ricco", "REEK-koh", "rich"],
      ["povero", "POH-veh-roh", "poor"], ["felice", "feh-LEE-cheh", "happy"],
      ["triste", "TREES-teh", "sad"], ["stanco", "STAHN-koh", "tired"],
      ["pulito", "poo-LEE-toh", "clean"], ["sporco", "SPOR-koh", "dirty"],
      ["pieno", "PYEH-noh", "full"], ["vuoto", "VWOH-toh", "empty"],
      ["caro", "KAH-roh", "expensive / dear"], ["economico", "eh-koh-NOH-mee-koh", "cheap"],
      ["gentile", "jen-TEE-leh", "kind"],
    ]),
    V("adverbs", [
      ["molto", "MOHL-toh", "very / a lot"], ["poco", "POH-koh", "little"],
      ["bene", "BEH-neh", "well"], ["male", "MAH-leh", "badly"],
      ["sempre", "SEM-preh", "always"], ["mai", "MAI", "never"],
      ["a volte", "ah VOL-teh", "sometimes"], ["spesso", "SPES-soh", "often"],
      ["adesso", "ah-DES-soh", "now"], ["oggi", "OD-jee", "today"],
      ["ieri", "YEH-ree", "yesterday"], ["domani", "doh-MAH-nee", "tomorrow"],
      ["presto", "PRES-toh", "early / soon"], ["tardi", "TAR-dee", "late"],
      ["qui", "KWEE", "here"], ["lì", "LEE", "there"], ["vicino", "vee-CHEE-noh", "near"],
      ["lontano", "lohn-TAH-noh", "far"], ["insieme", "een-SYEH-meh", "together"],
      ["solo", "SOH-loh", "only / alone"], ["forse", "FOR-seh", "maybe"],
      ["già", "JAH", "already"], ["ancora", "ahn-KOH-rah", "still / again"],
      ["lentamente", "len-tah-MEN-teh", "slowly"], ["velocemente", "veh-loh-cheh-MEN-teh", "quickly"],
      ["quasi", "KWAH-zee", "almost"], ["troppo", "TROP-poh", "too much"],
      ["davvero", "dahv-VEH-roh", "really"],
    ]),
    V("verbs", [
      ["essere", "ES-seh-reh", "to be"], ["avere", "ah-VEH-reh", "to have"],
      ["fare", "FAH-reh", "to do / make"], ["andare", "ahn-DAH-reh", "to go"],
      ["venire", "veh-NEE-reh", "to come"], ["potere", "poh-TEH-reh", "to be able to"],
      ["volere", "voh-LEH-reh", "to want"], ["dovere", "doh-VEH-reh", "to have to"],
      ["sapere", "sah-PEH-reh", "to know (facts)"], ["conoscere", "koh-NOH-sheh-reh", "to know (people)"],
      ["dire", "DEE-reh", "to say"], ["parlare", "par-LAH-reh", "to speak"],
      ["mangiare", "mahn-JAH-reh", "to eat"], ["bere", "BEH-reh", "to drink"],
      ["vivere", "VEE-veh-reh", "to live"], ["vedere", "veh-DEH-reh", "to see"],
      ["guardare", "gwar-DAH-reh", "to watch"], ["ascoltare", "ahs-kohl-TAH-reh", "to listen"],
      ["leggere", "LED-jeh-reh", "to read"], ["scrivere", "SKREE-veh-reh", "to write"],
      ["lavorare", "lah-voh-RAH-reh", "to work"], ["studiare", "stoo-DYAH-reh", "to study"],
      ["dormire", "dor-MEE-reh", "to sleep"], ["comprare", "kohm-PRAH-reh", "to buy"],
      ["vendere", "VEN-deh-reh", "to sell"], ["aprire", "ah-PREE-reh", "to open"],
      ["chiudere", "KYOO-deh-reh", "to close"], ["cominciare", "koh-meen-CHAH-reh", "to begin"],
      ["finire", "fee-NEE-reh", "to finish"], ["aiutare", "ah-yoo-TAH-reh", "to help"],
      ["pensare", "pen-SAH-reh", "to think"], ["camminare", "kahm-mee-NAH-reh", "to walk"],
      ["correre", "KOR-reh-reh", "to run"], ["aspettare", "ahs-pet-TAH-reh", "to wait"],
      ["dare", "DAH-reh", "to give"], ["prendere", "PREN-deh-reh", "to take"],
      ["arrivare", "ahr-ree-VAH-reh", "to arrive"], ["partire", "par-TEE-reh", "to leave"],
      ["amare", "ah-MAH-reh", "to love"],
    ]),
    V("food", [
      ["il cibo", "eel CHEE-boh", "food"], ["l'acqua", "LAHK-kwah", "water"],
      ["il pane", "eel PAH-neh", "bread"], ["la pasta", "lah PAHS-tah", "pasta"],
      ["il riso", "eel REE-zoh", "rice"], ["la carne", "lah KAR-neh", "meat"],
      ["il pollo", "eel POL-loh", "chicken"], ["il pesce", "eel PEH-sheh", "fish"],
      ["l'uovo", "LWOH-voh", "egg"], ["il latte", "eel LAHT-teh", "milk"],
      ["il formaggio", "eel for-MAHD-joh", "cheese"], ["il burro", "eel BOOR-roh", "butter"],
      ["la frutta", "lah FROOT-tah", "fruit"], ["la mela", "lah MEH-lah", "apple"],
      ["la banana", "lah bah-NAH-nah", "banana"], ["l'arancia", "lah-RAHN-chah", "orange"],
      ["la verdura", "lah vehr-DOO-rah", "vegetables"],
      ["la patata", "lah pah-TAH-tah", "potato"], ["il pomodoro", "eel poh-moh-DOH-roh", "tomato"],
      ["la cipolla", "lah chee-POL-lah", "onion"], ["l'aglio", "LAH-lyoh", "garlic"],
      ["il sale", "eel SAH-leh", "salt"], ["il pepe", "eel PEH-peh", "pepper"],
      ["lo zucchero", "loh TSOOK-keh-roh", "sugar"], ["l'olio", "LOH-lyoh", "oil"],
      ["il caffè", "eel kahf-FEH", "coffee"], ["il tè", "eel TEH", "tea"],
      ["il vino", "eel VEE-noh", "wine"], ["la birra", "lah BEER-rah", "beer"],
      ["il succo", "eel SOOK-koh", "juice"], ["la zuppa", "lah TSOOP-pah", "soup"],
      ["l'insalata", "leen-sah-LAH-tah", "salad"], ["il dolce", "eel DOHL-cheh", "dessert"],
      ["la colazione", "lah koh-lah-TSYOH-neh", "breakfast"],
      ["il pranzo", "eel PRAHN-tsoh", "lunch"], ["la cena", "lah CHEH-nah", "dinner"],
      ["il ristorante", "eel rees-toh-RAHN-teh", "restaurant"],
      ["il conto", "eel KOHN-toh", "the bill"],
    ]),
    V("body", [
      ["il corpo", "eel KOR-poh", "body"], ["la testa", "lah TES-tah", "head"],
      ["i capelli", "ee kah-PEL-lee", "hair"], ["la faccia", "lah FAHT-chah", "face"],
      ["l'occhio", "LOK-kyoh", "eye"], ["l'orecchio", "loh-REK-kyoh", "ear"],
      ["il naso", "eel NAH-zoh", "nose"], ["la bocca", "lah BOK-kah", "mouth"],
      ["il dente", "eel DEN-teh", "tooth"], ["la lingua", "lah LEEN-gwah", "tongue / language"],
      ["il collo", "eel KOL-loh", "neck"], ["la spalla", "lah SPAHL-lah", "shoulder"],
      ["il braccio", "eel BRAHT-choh", "arm"], ["la mano", "lah MAH-noh", "hand"],
      ["il dito", "eel DEE-toh", "finger"], ["la gamba", "lah GAHM-bah", "leg"],
      ["il piede", "eel PYEH-deh", "foot"], ["il ginocchio", "eel jee-NOK-kyoh", "knee"],
      ["la schiena", "lah SKYEH-nah", "back"], ["il petto", "eel PET-toh", "chest"],
      ["il cuore", "eel KWOH-reh", "heart"], ["lo stomaco", "loh STOH-mah-koh", "stomach"],
      ["il sangue", "eel SAHN-gweh", "blood"], ["l'osso", "LOS-soh", "bone"],
      ["la pelle", "lah PEL-leh", "skin"],
    ]),
    V("health", [
      ["la salute", "lah sah-LOO-teh", "health"], ["il medico", "eel MEH-dee-koh", "doctor"],
      ["l'ospedale", "los-peh-DAH-leh", "hospital"], ["la farmacia", "lah far-mah-CHEE-ah", "pharmacy"],
      ["la medicina", "lah meh-dee-CHEE-nah", "medicine"],
      ["malato", "mah-LAH-toh", "ill"], ["sano", "SAH-noh", "healthy"],
      ["il dolore", "eel doh-LOH-reh", "pain"], ["la febbre", "lah FEB-breh", "fever"],
      ["la tosse", "lah TOS-seh", "cough"], ["il raffreddore", "eel rahf-fred-DOH-reh", "a cold"],
      ["la ferita", "lah feh-REE-tah", "wound"], ["l'infermiera", "leen-fer-MYEH-rah", "nurse"],
      ["l'appuntamento", "lahp-poon-tah-MEN-toh", "appointment"],
      ["mi fa male", "mee fah MAH-leh", "it hurts"],
      ["l'ambulanza", "lahm-boo-LAHN-tsah", "ambulance"],
      ["l'emergenza", "leh-mehr-JEN-tsah", "emergency"],
      ["riposare", "ree-poh-ZAH-reh", "to rest"],
      ["l'esercizio", "leh-zehr-CHEE-tsyoh", "exercise"], ["la dieta", "lah DYEH-tah", "diet"],
      ["la ricetta", "lah ree-CHET-tah", "prescription / recipe"],
      ["guarire", "gwah-REE-reh", "to recover"],
    ]),
    V("clothing", [
      ["i vestiti", "ee ves-TEE-tee", "clothes"], ["la camicia", "lah kah-MEE-chah", "shirt"],
      ["la maglietta", "lah mah-LYET-tah", "t-shirt"],
      ["i pantaloni", "ee pahn-tah-LOH-nee", "trousers"], ["i jeans", "ee JEENS", "jeans"],
      ["il vestito", "eel ves-TEE-toh", "dress / suit"], ["la gonna", "lah GON-nah", "skirt"],
      ["il cappotto", "eel kahp-POT-toh", "coat"], ["la giacca", "lah JAHK-kah", "jacket"],
      ["il maglione", "eel mah-LYOH-neh", "sweater"], ["le scarpe", "leh SKAR-peh", "shoes"],
      ["gli stivali", "lyee stee-VAH-lee", "boots"], ["i calzini", "ee kahl-TSEE-nee", "socks"],
      ["il cappello", "eel kahp-PEL-loh", "hat"], ["la sciarpa", "lah SHAR-pah", "scarf"],
      ["i guanti", "ee GWAHN-tee", "gloves"], ["la cintura", "lah cheen-TOO-rah", "belt"],
      ["gli occhiali", "lyee ok-KYAH-lee", "glasses"], ["la borsa", "lah BOR-sah", "bag"],
      ["la taglia", "lah TAH-lyah", "size"], ["indossare", "een-dos-SAH-reh", "to wear"],
      ["provare", "proh-VAH-reh", "to try on"],
    ]),
    V("home", [
      ["la casa", "lah KAH-zah", "house / home"],
      ["l'appartamento", "lahp-par-tah-MEN-toh", "apartment"],
      ["la stanza", "lah STAHN-tsah", "room"], ["la cucina", "lah koo-CHEE-nah", "kitchen"],
      ["il bagno", "eel BAH-nyoh", "bathroom"], ["la camera", "lah KAH-meh-rah", "bedroom"],
      ["il soggiorno", "eel sod-JOR-noh", "living room"], ["la porta", "lah POR-tah", "door"],
      ["la finestra", "lah fee-NES-trah", "window"], ["il tavolo", "eel TAH-voh-loh", "table"],
      ["la sedia", "lah SEH-dyah", "chair"], ["il letto", "eel LET-toh", "bed"],
      ["il divano", "eel dee-VAH-noh", "sofa"], ["la lampada", "lah LAHM-pah-dah", "lamp"],
      ["lo specchio", "loh SPEK-kyoh", "mirror"], ["la chiave", "lah KYAH-veh", "key"],
      ["il piatto", "eel PYAHT-toh", "plate"], ["il bicchiere", "eel beek-KYEH-reh", "glass"],
      ["la tazza", "lah TAHT-tsah", "cup"], ["il coltello", "eel kohl-TEL-loh", "knife"],
      ["la forchetta", "lah for-KET-tah", "fork"], ["il cucchiaio", "eel kook-KYAH-yoh", "spoon"],
      ["il giardino", "eel jar-DEE-noh", "garden"], ["le scale", "leh SKAH-leh", "stairs"],
      ["il tetto", "eel TET-toh", "roof"], ["il muro", "eel MOO-roh", "wall"],
      ["il pavimento", "eel pah-vee-MEN-toh", "floor"],
    ]),
    V("animals", [
      ["l'animale", "lah-nee-MAH-leh", "animal"], ["il cane", "eel KAH-neh", "dog"],
      ["il gatto", "eel GAHT-toh", "cat"], ["il cavallo", "eel kah-VAHL-loh", "horse"],
      ["la mucca", "lah MOOK-kah", "cow"], ["il maiale", "eel mah-YAH-leh", "pig"],
      ["la pecora", "lah PEH-koh-rah", "sheep"], ["la gallina", "lah gahl-LEE-nah", "hen"],
      ["l'uccello", "loot-CHEL-loh", "bird"], ["il pesce", "eel PEH-sheh", "fish"],
      ["il topo", "eel TOH-poh", "mouse"], ["il coniglio", "eel koh-NEE-lyoh", "rabbit"],
      ["il leone", "eel leh-OH-neh", "lion"], ["la tigre", "lah TEE-greh", "tiger"],
      ["l'elefante", "leh-leh-FAHN-teh", "elephant"], ["la scimmia", "lah SHEEM-myah", "monkey"],
      ["l'orso", "LOR-soh", "bear"], ["il lupo", "eel LOO-poh", "wolf"],
      ["il serpente", "eel sehr-PEN-teh", "snake"], ["il ragno", "eel RAH-nyoh", "spider"],
      ["la farfalla", "lah far-FAHL-lah", "butterfly"], ["l'ape", "LAH-peh", "bee"],
      ["la formica", "lah for-MEE-kah", "ant"], ["la mosca", "lah MOS-kah", "fly"],
      ["la tartaruga", "lah tar-tah-ROO-gah", "tortoise"],
    ]),
    V("nature", [
      ["la natura", "lah nah-TOO-rah", "nature"], ["il sole", "eel SOH-leh", "sun"],
      ["la luna", "lah LOO-nah", "moon"], ["la stella", "lah STEL-lah", "star"],
      ["il cielo", "eel CHEH-loh", "sky"], ["la nuvola", "lah NOO-voh-lah", "cloud"],
      ["la pioggia", "lah PYOD-jah", "rain"], ["la neve", "lah NEH-veh", "snow"],
      ["il vento", "eel VEN-toh", "wind"], ["il fuoco", "eel FWOH-koh", "fire"],
      ["la terra", "lah TEHR-rah", "earth"], ["il mare", "eel MAH-reh", "sea"],
      ["il fiume", "eel FYOO-meh", "river"], ["il lago", "eel LAH-goh", "lake"],
      ["la montagna", "lah mohn-TAH-nyah", "mountain"], ["il bosco", "eel BOS-koh", "wood"],
      ["l'albero", "LAHL-beh-roh", "tree"], ["il fiore", "eel FYOH-reh", "flower"],
      ["la foglia", "lah FOH-lyah", "leaf"], ["l'erba", "LEHR-bah", "grass"],
      ["la spiaggia", "lah SPYAHD-jah", "beach"], ["l'isola", "LEE-zoh-lah", "island"],
      ["il deserto", "eel deh-ZEHR-toh", "desert"], ["la pietra", "lah PYEH-trah", "stone"],
      ["il tempo", "eel TEM-poh", "weather / time"],
      ["il temporale", "eel tem-poh-RAH-leh", "storm"],
    ]),
    V("places", [
      ["il posto", "eel POS-toh", "place"], ["la città", "lah cheet-TAH", "city"],
      ["il paese", "eel pah-EH-zeh", "village / country"],
      ["la strada", "lah STRAH-dah", "street / road"], ["la piazza", "lah PYAHT-tsah", "square"],
      ["il mercato", "eel mehr-KAH-toh", "market"], ["il negozio", "eel neh-GOH-tsyoh", "shop"],
      ["la banca", "lah BAHN-kah", "bank"], ["la scuola", "lah SKWOH-lah", "school"],
      ["la chiesa", "lah KYEH-zah", "church"], ["il museo", "eel moo-ZEH-oh", "museum"],
      ["il parco", "eel PAR-koh", "park"], ["l'albergo", "lahl-BEHR-goh", "hotel"],
      ["l'aeroporto", "lah-eh-roh-POR-toh", "airport"],
      ["la stazione", "lah stah-TSYOH-neh", "station"],
      ["la biblioteca", "lah bee-blyoh-TEH-kah", "library"],
      ["l'ufficio", "loof-FEE-choh", "office"], ["il cinema", "eel CHEE-neh-mah", "cinema"],
      ["il quartiere", "eel kwar-TYEH-reh", "neighbourhood"],
      ["il centro", "eel CHEN-troh", "centre"], ["la campagna", "lah kahm-PAH-nyah", "countryside"],
      ["il confine", "eel kohn-FEE-neh", "border"], ["il bar", "eel BAR", "café / bar"],
    ]),
    V("travel", [
      ["il viaggio", "eel VYAHD-joh", "journey"], ["viaggiare", "vyahd-JAH-reh", "to travel"],
      ["la macchina", "lah MAHK-kee-nah", "car"], ["l'autobus", "LOW-toh-boos", "bus"],
      ["il treno", "eel TREH-noh", "train"], ["l'aereo", "lah-EH-reh-oh", "aeroplane"],
      ["la bicicletta", "lah bee-chee-KLET-tah", "bicycle"], ["la barca", "lah BAR-kah", "boat"],
      ["il taxi", "eel TAHK-see", "taxi"], ["la metropolitana", "lah meh-troh-poh-lee-TAH-nah", "underground"],
      ["il biglietto", "eel bee-LYET-toh", "ticket"],
      ["il passaporto", "eel pahs-sah-POR-toh", "passport"],
      ["la valigia", "lah vah-LEE-jah", "suitcase"], ["il bagaglio", "eel bah-GAH-lyoh", "luggage"],
      ["la mappa", "lah MAHP-pah", "map"], ["la via", "lah VEE-ah", "way / street"],
      ["la partenza", "lah par-TEN-tsah", "departure"], ["l'arrivo", "lahr-REE-voh", "arrival"],
      ["il ritardo", "eel ree-TAR-doh", "delay"], ["a sinistra", "ah see-NEES-trah", "to the left"],
      ["a destra", "ah DES-trah", "to the right"], ["dritto", "DREET-toh", "straight ahead"],
      ["perdersi", "PEHR-dehr-see", "to get lost"], ["la dogana", "lah doh-GAH-nah", "customs"],
    ]),
    V("time", [
      ["il tempo", "eel TEM-poh", "time"], ["l'ora", "LOH-rah", "hour"],
      ["il minuto", "eel mee-NOO-toh", "minute"], ["il secondo", "eel seh-KOHN-doh", "second"],
      ["il giorno", "eel JOR-noh", "day"], ["la settimana", "lah set-tee-MAH-nah", "week"],
      ["il mese", "eel MEH-zeh", "month"], ["l'anno", "LAHN-noh", "year"],
      ["la mattina", "lah maht-TEE-nah", "morning"],
      ["il pomeriggio", "eel poh-meh-REED-joh", "afternoon"],
      ["la sera", "lah SEH-rah", "evening"], ["la notte", "lah NOT-teh", "night"],
      ["lunedì", "loo-neh-DEE", "Monday"], ["martedì", "mar-teh-DEE", "Tuesday"],
      ["mercoledì", "mehr-koh-leh-DEE", "Wednesday"], ["giovedì", "joh-veh-DEE", "Thursday"],
      ["venerdì", "veh-nehr-DEE", "Friday"], ["sabato", "SAH-bah-toh", "Saturday"],
      ["domenica", "doh-MEH-nee-kah", "Sunday"], ["gennaio", "jen-NAH-yoh", "January"],
      ["febbraio", "feb-BRAH-yoh", "February"], ["marzo", "MAR-tsoh", "March"],
      ["aprile", "ah-PREE-leh", "April"], ["maggio", "MAHD-joh", "May"],
      ["giugno", "JOO-nyoh", "June"], ["luglio", "LOO-lyoh", "July"],
      ["il fine settimana", "eel FEE-neh set-tee-MAH-nah", "weekend"],
      ["l'orologio", "loh-roh-LOH-joh", "clock / watch"],
      ["l'estate", "les-TAH-teh", "summer"], ["l'inverno", "leen-VEHR-noh", "winter"],
    ]),
    V("work", [
      ["il lavoro", "eel lah-VOH-roh", "work / job"],
      ["l'azienda", "lah-TSYEN-dah", "company"], ["il capo", "eel KAH-poh", "boss"],
      ["il dipendente", "eel dee-pen-DEN-teh", "employee"],
      ["lo stipendio", "loh stee-PEN-dyoh", "salary"], ["i soldi", "ee SOL-dee", "money"],
      ["l'euro", "LEH-oo-roh", "euro"], ["il prezzo", "eel PRET-tsoh", "price"],
      ["pagare", "pah-GAH-reh", "to pay"], ["la riunione", "lah ryoo-NYOH-neh", "meeting"],
      ["il progetto", "eel proh-JET-toh", "project"], ["il cliente", "eel klee-EN-teh", "client"],
      ["la fattura", "lah faht-TOO-rah", "invoice"], ["il contratto", "eel kohn-TRAHT-toh", "contract"],
      ["la carta", "lah KAR-tah", "card"], ["i contanti", "ee kohn-TAHN-tee", "cash"],
      ["la professione", "lah proh-fes-SYOH-neh", "profession"],
      ["l'ingegnere", "leen-jeh-NYEH-reh", "engineer"],
      ["l'avvocato", "lahv-voh-KAH-toh", "lawyer"],
      ["l'insegnante", "leen-seh-NYAHN-teh", "teacher"],
      ["il mercato", "eel mehr-KAH-toh", "market"],
      ["guadagnare", "gwah-dah-NYAH-reh", "to earn"],
      ["lo sconto", "loh SKOHN-toh", "discount"],
    ]),
    V("school", [
      ["la scuola", "lah SKWOH-lah", "school"],
      ["l'università", "loo-nee-vehr-see-TAH", "university"],
      ["la classe", "lah KLAHS-seh", "class"], ["l'alunno", "lah-LOON-noh", "pupil"],
      ["lo studente", "loh stoo-DEN-teh", "student"],
      ["il professore", "eel proh-fes-SOH-reh", "teacher"], ["il libro", "eel LEE-broh", "book"],
      ["il quaderno", "eel kwah-DEHR-noh", "notebook"], ["la matita", "lah mah-TEE-tah", "pencil"],
      ["la penna", "lah PEN-nah", "pen"], ["la carta", "lah KAR-tah", "paper"],
      ["la parola", "lah pah-ROH-lah", "word"], ["la frase", "lah FRAH-zeh", "sentence"],
      ["la lezione", "lah leh-TSYOH-neh", "lesson"], ["l'esame", "leh-ZAH-meh", "exam"],
      ["i compiti", "ee KOHM-pee-tee", "homework"], ["il voto", "eel VOH-toh", "grade"],
      ["imparare", "eem-pah-RAH-reh", "to learn"], ["insegnare", "een-seh-NYAH-reh", "to teach"],
      ["capire", "kah-PEE-reh", "to understand"], ["spiegare", "spyeh-GAH-reh", "to explain"],
      ["la risposta", "lah rees-POS-tah", "answer"], ["la lingua", "lah LEEN-gwah", "language"],
      ["la storia", "lah STOH-ryah", "history / story"],
      ["la matematica", "lah mah-teh-MAH-tee-kah", "maths"],
      ["la scienza", "lah SHEN-tsah", "science"],
    ]),
    V("tech", [
      ["il computer", "eel kohm-PYOO-tehr", "computer"],
      ["il telefono", "eel teh-LEH-foh-noh", "telephone"],
      ["il cellulare", "eel chel-loo-LAH-reh", "mobile phone"],
      ["lo schermo", "loh SKEHR-moh", "screen"], ["la tastiera", "lah tahs-TYEH-rah", "keyboard"],
      ["il mouse", "eel MOWS", "mouse"], ["internet", "een-tehr-NET", "internet"],
      ["la rete", "lah REH-teh", "network"], ["la posta elettronica", "lah POS-tah eh-let-TROH-nee-kah", "email"],
      ["la password", "lah PAHS-word", "password"], ["il file", "eel FAH-eel", "file"],
      ["la cartella", "lah kar-TEL-lah", "folder"],
      ["l'applicazione", "lahp-plee-kah-TSYOH-neh", "app"],
      ["il programma", "eel proh-GRAHM-mah", "program"],
      ["scaricare", "skah-ree-KAH-reh", "to download"],
      ["caricare", "kah-ree-KAH-reh", "to upload"], ["salvare", "sahl-VAH-reh", "to save"],
      ["cancellare", "kahn-chel-LAH-reh", "to delete"], ["cercare", "chehr-KAH-reh", "to search"],
      ["accendere", "aht-CHEN-deh-reh", "to switch on"],
      ["spegnere", "SPEH-nyeh-reh", "to switch off"],
      ["la fotocamera", "lah foh-toh-KAH-meh-rah", "camera"],
      ["la batteria", "lah baht-teh-REE-ah", "battery"],
      ["il collegamento", "eel kol-leh-gah-MEN-toh", "link"],
    ]),
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["Ciao, come stai?", "chow KOH-meh STAI", "Hi, how are you?",
        [["Ciao", "chow"], ["come", "KOH-meh"], ["stai", "STAI"]]],
      ["Sto molto bene, grazie", "stoh MOHL-toh BEH-neh GRAHT-tsyeh", "I am very well, thank you",
        [["Sto", "stoh"], ["molto", "MOHL-toh"], ["bene", "BEH-neh"], ["grazie", "GRAHT-tsyeh"]]],
      ["Come ti chiami?", "KOH-meh tee KYAH-mee", "What is your name?",
        [["Come", "KOH-meh"], ["ti", "tee"], ["chiami", "KYAH-mee"]]],
      ["Mi chiamo Luca", "mee KYAH-moh LOO-kah", "My name is Luca",
        [["Mi", "mee"], ["chiamo", "KYAH-moh"], ["Luca", "LOO-kah"]]],
      ["Non capisco", "nohn kah-PEES-koh", "I don't understand",
        [["Non", "nohn"], ["capisco", "kah-PEES-koh"]]],
      ["Puoi ripetere, per favore?", "PWOH-ee ree-PEH-teh-reh pehr fah-VOH-reh",
        "Can you repeat, please?",
        [["Puoi", "PWOH-ee"], ["ripetere", "ree-PEH-teh-reh"], ["per", "pehr"], ["favore", "fah-VOH-reh"]]],
      ["Piacere di conoscerti", "pyah-CHEH-reh dee koh-NOH-shehr-tee", "Nice to meet you",
        [["Piacere", "pyah-CHEH-reh"], ["di", "dee"], ["conoscerti", "koh-NOH-shehr-tee"]]],
      ["Parli inglese?", "PAR-lee een-GLEH-zeh", "Do you speak English?",
        [["Parli", "PAR-lee"], ["inglese", "een-GLEH-zeh"]]],
    ]),
    S("food", [
      ["Vorrei un caffè, per favore", "vor-REH-ee oon kahf-FEH pehr fah-VOH-reh",
        "I would like a coffee, please",
        [["Vorrei", "vor-REH-ee"], ["un", "oon"], ["caffè", "kahf-FEH"], ["per", "pehr"], ["favore", "fah-VOH-reh"]]],
      ["Ho fame", "oh FAH-meh", "I am hungry", [["Ho", "oh"], ["fame", "FAH-meh"]]],
      ["Ho sete", "oh SEH-teh", "I am thirsty", [["Ho", "oh"], ["sete", "SEH-teh"]]],
      ["Il cibo è delizioso", "eel CHEE-boh eh deh-lee-TSYOH-zoh", "The food is delicious",
        [["Il", "eel"], ["cibo", "CHEE-boh"], ["è", "eh"], ["delizioso", "deh-lee-TSYOH-zoh"]]],
      ["Il conto, per favore", "eel KOHN-toh pehr fah-VOH-reh", "The bill, please",
        [["Il", "eel"], ["conto", "KOHN-toh"], ["per", "pehr"], ["favore", "fah-VOH-reh"]]],
      ["Non mangio carne", "nohn MAHN-joh KAR-neh", "I don't eat meat",
        [["Non", "nohn"], ["mangio", "MAHN-joh"], ["carne", "KAR-neh"]]],
    ]),
    S("travel", [
      ["Dov'è la stazione?", "doh-VEH lah stah-TSYOH-neh", "Where is the station?",
        [["Dov'è", "doh-VEH"], ["la", "lah"], ["stazione", "stah-TSYOH-neh"]]],
      ["Vorrei un biglietto per Roma", "vor-REH-ee oon bee-LYET-toh pehr ROH-mah",
        "I would like a ticket to Rome",
        [["Vorrei", "vor-REH-ee"], ["un", "oon"], ["biglietto", "bee-LYET-toh"], ["per", "pehr"], ["Roma", "ROH-mah"]]],
      ["Il treno arriva alle otto", "eel TREH-noh ahr-REE-vah AHL-leh OT-toh",
        "The train arrives at eight",
        [["Il", "eel"], ["treno", "TREH-noh"], ["arriva", "ahr-REE-vah"], ["alle", "AHL-leh"], ["otto", "OT-toh"]]],
      ["Mi sono perso", "mee SOH-noh PEHR-soh", "I am lost",
        [["Mi", "mee"], ["sono", "SOH-noh"], ["perso", "PEHR-soh"]]],
      ["Giri a destra", "JEE-ree ah DES-trah", "Turn right",
        [["Giri", "JEE-ree"], ["a", "ah"], ["destra", "DES-trah"]]],
    ]),
    S("home", [
      ["Vivo in una casa piccola", "VEE-voh een OO-nah KAH-zah PEEK-koh-lah",
        "I live in a small house",
        [["Vivo", "VEE-voh"], ["in", "een"], ["una", "OO-nah"], ["casa", "KAH-zah"], ["piccola", "PEEK-koh-lah"]]],
      ["La porta è aperta", "lah POR-tah eh ah-PEHR-tah", "The door is open",
        [["La", "lah"], ["porta", "POR-tah"], ["è", "eh"], ["aperta", "ah-PEHR-tah"]]],
      ["La mia famiglia è grande", "lah MEE-ah fah-MEE-lyah eh GRAHN-deh", "My family is big",
        [["La", "lah"], ["mia", "MEE-ah"], ["famiglia", "fah-MEE-lyah"], ["è", "eh"], ["grande", "GRAHN-deh"]]],
    ]),
    S("time", [
      ["Che ore sono?", "keh OH-reh SOH-noh", "What time is it?",
        [["Che", "keh"], ["ore", "OH-reh"], ["sono", "SOH-noh"]]],
      ["Oggi è lunedì", "OD-jee eh loo-neh-DEE", "Today is Monday",
        [["Oggi", "OD-jee"], ["è", "eh"], ["lunedì", "loo-neh-DEE"]]],
      ["Domani vado al mercato", "doh-MAH-nee VAH-doh ahl mehr-KAH-toh",
        "Tomorrow I go to the market",
        [["Domani", "doh-MAH-nee"], ["vado", "VAH-doh"], ["al", "ahl"], ["mercato", "mehr-KAH-toh"]]],
      ["Lavoro sempre la mattina", "lah-VOH-roh SEM-preh lah maht-TEE-nah",
        "I always work in the morning",
        [["Lavoro", "lah-VOH-roh"], ["sempre", "SEM-preh"], ["la", "lah"], ["mattina", "maht-TEE-nah"]]],
    ]),
    S("school", [
      ["Studio italiano ogni giorno", "STOO-dyoh ee-tah-LYAH-noh OH-nyee JOR-noh",
        "I study Italian every day",
        [["Studio", "STOO-dyoh"], ["italiano", "ee-tah-LYAH-noh"], ["ogni", "OH-nyee"], ["giorno", "JOR-noh"]]],
      ["Il libro è molto interessante", "eel LEE-broh eh MOHL-toh een-teh-res-SAHN-teh",
        "The book is very interesting",
        [["Il", "eel"], ["libro", "LEE-broh"], ["è", "eh"], ["molto", "MOHL-toh"], ["interessante", "een-teh-res-SAHN-teh"]]],
      ["Puoi aiutarmi?", "PWOH-ee ah-yoo-TAR-mee", "Can you help me?",
        [["Puoi", "PWOH-ee"], ["aiutarmi", "ah-yoo-TAR-mee"]]],
    ]),
    S("health", [
      ["Mi fa male la testa", "mee fah MAH-leh lah TES-tah", "My head hurts",
        [["Mi", "mee"], ["fa", "fah"], ["male", "MAH-leh"], ["la", "lah"], ["testa", "TES-tah"]]],
      ["Ho bisogno di un medico", "oh bee-ZOH-nyoh dee oon MEH-dee-koh", "I need a doctor",
        [["Ho", "oh"], ["bisogno", "bee-ZOH-nyoh"], ["di", "dee"], ["un", "oon"], ["medico", "MEH-dee-koh"]]],
      ["Non mi sento bene", "nohn mee SEN-toh BEH-neh", "I don't feel well",
        [["Non", "nohn"], ["mi", "mee"], ["sento", "SEN-toh"], ["bene", "BEH-neh"]]],
    ]),
    S("work", [
      ["Quanto costa questo?", "KWAHN-toh KOS-tah KWES-toh", "How much does this cost?",
        [["Quanto", "KWAHN-toh"], ["costa", "KOS-tah"], ["questo", "KWES-toh"]]],
      ["È troppo caro", "eh TROP-poh KAH-roh", "It is too expensive",
        [["È", "eh"], ["troppo", "TROP-poh"], ["caro", "KAH-roh"]]],
      ["Lavoro in un ufficio", "lah-VOH-roh een oon oof-FEE-choh", "I work in an office",
        [["Lavoro", "lah-VOH-roh"], ["in", "een"], ["un", "oon"], ["ufficio", "oof-FEE-choh"]]],
    ]),
  );

  /* ----------------------------- Conjugation ------------------------------
   * Passato prossimo (past), presente, futuro semplice. */
  const CONJUGATION = [
    C("essere", "ES-seh-reh", "be", [
      ["io sono stato", "EE-oh SOH-noh STAH-toh", "I was", "I", "past"],
      ["tu sei stato", "too SEH-ee STAH-toh", "you were", "you", "past"],
      ["lui è stato", "LOO-ee eh STAH-toh", "he was", "he", "past"],
      ["lei è stata", "LEH-ee eh STAH-tah", "she was", "she", "past"],
      ["noi siamo stati", "NOH-ee SYAH-moh STAH-tee", "we were", "we", "past"],
      ["loro sono stati", "LOH-roh SOH-noh STAH-tee", "they were", "they", "past"],
      ["io sono", "EE-oh SOH-noh", "I am", "I", "present"],
      ["tu sei", "too SEH-ee", "you are", "you", "present"],
      ["lui è", "LOO-ee EH", "he is", "he", "present"],
      ["lei è", "LEH-ee EH", "she is", "she", "present"],
      ["noi siamo", "NOH-ee SYAH-moh", "we are", "we", "present"],
      ["loro sono", "LOH-roh SOH-noh", "they are", "they", "present"],
      ["io sarò", "EE-oh sah-ROH", "I will be", "I", "future"],
      ["tu sarai", "too sah-RAI", "you will be", "you", "future"],
      ["lui sarà", "LOO-ee sah-RAH", "he will be", "he", "future"],
      ["noi saremo", "NOH-ee sah-REH-moh", "we will be", "we", "future"],
      ["loro saranno", "LOH-roh sah-RAHN-noh", "they will be", "they", "future"],
    ]),
    C("avere", "ah-VEH-reh", "have", [
      ["io ho avuto", "EE-oh oh ah-VOO-toh", "I had", "I", "past"],
      ["tu hai avuto", "too eye ah-VOO-toh", "you had", "you", "past"],
      ["lui ha avuto", "LOO-ee ah ah-VOO-toh", "he had", "he", "past"],
      ["noi abbiamo avuto", "NOH-ee ahb-BYAH-moh ah-VOO-toh", "we had", "we", "past"],
      ["loro hanno avuto", "LOH-roh AHN-noh ah-VOO-toh", "they had", "they", "past"],
      ["io ho", "EE-oh OH", "I have", "I", "present"],
      ["tu hai", "too EYE", "you have", "you", "present"],
      ["lui ha", "LOO-ee AH", "he has", "he", "present"],
      ["noi abbiamo", "NOH-ee ahb-BYAH-moh", "we have", "we", "present"],
      ["loro hanno", "LOH-roh AHN-noh", "they have", "they", "present"],
      ["io avrò", "EE-oh ah-VROH", "I will have", "I", "future"],
      ["tu avrai", "too ah-VRAI", "you will have", "you", "future"],
      ["lui avrà", "LOO-ee ah-VRAH", "he will have", "he", "future"],
      ["noi avremo", "NOH-ee ah-VREH-moh", "we will have", "we", "future"],
      ["loro avranno", "LOH-roh ah-VRAHN-noh", "they will have", "they", "future"],
    ]),
    C("andare", "ahn-DAH-reh", "go", [
      ["io sono andato", "EE-oh SOH-noh ahn-DAH-toh", "I went", "I", "past"],
      ["tu sei andato", "too SEH-ee ahn-DAH-toh", "you went", "you", "past"],
      ["lui è andato", "LOO-ee eh ahn-DAH-toh", "he went", "he", "past"],
      ["noi siamo andati", "NOH-ee SYAH-moh ahn-DAH-tee", "we went", "we", "past"],
      ["loro sono andati", "LOH-roh SOH-noh ahn-DAH-tee", "they went", "they", "past"],
      ["io vado", "EE-oh VAH-doh", "I go", "I", "present"],
      ["tu vai", "too VAI", "you go", "you", "present"],
      ["lui va", "LOO-ee VAH", "he goes", "he", "present"],
      ["noi andiamo", "NOH-ee ahn-DYAH-moh", "we go", "we", "present"],
      ["loro vanno", "LOH-roh VAHN-noh", "they go", "they", "present"],
      ["io andrò", "EE-oh ahn-DROH", "I will go", "I", "future"],
      ["tu andrai", "too ahn-DRAI", "you will go", "you", "future"],
      ["lui andrà", "LOO-ee ahn-DRAH", "he will go", "he", "future"],
      ["noi andremo", "NOH-ee ahn-DREH-moh", "we will go", "we", "future"],
      ["loro andranno", "LOH-roh ahn-DRAHN-noh", "they will go", "they", "future"],
    ]),
    C("fare", "FAH-reh", "do / make", [
      ["io ho fatto", "EE-oh oh FAHT-toh", "I did", "I", "past"],
      ["tu hai fatto", "too eye FAHT-toh", "you did", "you", "past"],
      ["lui ha fatto", "LOO-ee ah FAHT-toh", "he did", "he", "past"],
      ["noi abbiamo fatto", "NOH-ee ahb-BYAH-moh FAHT-toh", "we did", "we", "past"],
      ["loro hanno fatto", "LOH-roh AHN-noh FAHT-toh", "they did", "they", "past"],
      ["io faccio", "EE-oh FAHT-choh", "I do", "I", "present"],
      ["tu fai", "too FAI", "you do", "you", "present"],
      ["lui fa", "LOO-ee FAH", "he does", "he", "present"],
      ["noi facciamo", "NOH-ee faht-CHAH-moh", "we do", "we", "present"],
      ["loro fanno", "LOH-roh FAHN-noh", "they do", "they", "present"],
      ["io farò", "EE-oh fah-ROH", "I will do", "I", "future"],
      ["tu farai", "too fah-RAI", "you will do", "you", "future"],
      ["lui farà", "LOO-ee fah-RAH", "he will do", "he", "future"],
      ["noi faremo", "NOH-ee fah-REH-moh", "we will do", "we", "future"],
      ["loro faranno", "LOH-roh fah-RAHN-noh", "they will do", "they", "future"],
    ]),
    C("parlare", "par-LAH-reh", "speak", [
      ["io ho parlato", "EE-oh oh par-LAH-toh", "I spoke", "I", "past"],
      ["tu hai parlato", "too eye par-LAH-toh", "you spoke", "you", "past"],
      ["lui ha parlato", "LOO-ee ah par-LAH-toh", "he spoke", "he", "past"],
      ["noi abbiamo parlato", "NOH-ee ahb-BYAH-moh par-LAH-toh", "we spoke", "we", "past"],
      ["loro hanno parlato", "LOH-roh AHN-noh par-LAH-toh", "they spoke", "they", "past"],
      ["io parlo", "EE-oh PAR-loh", "I speak", "I", "present"],
      ["tu parli", "too PAR-lee", "you speak", "you", "present"],
      ["lui parla", "LOO-ee PAR-lah", "he speaks", "he", "present"],
      ["noi parliamo", "NOH-ee par-LYAH-moh", "we speak", "we", "present"],
      ["loro parlano", "LOH-roh PAR-lah-noh", "they speak", "they", "present"],
      ["io parlerò", "EE-oh par-leh-ROH", "I will speak", "I", "future"],
      ["tu parlerai", "too par-leh-RAI", "you will speak", "you", "future"],
      ["lui parlerà", "LOO-ee par-leh-RAH", "he will speak", "he", "future"],
      ["noi parleremo", "NOH-ee par-leh-REH-moh", "we will speak", "we", "future"],
      ["loro parleranno", "LOH-roh par-leh-RAHN-noh", "they will speak", "they", "future"],
    ]),
    C("mangiare", "mahn-JAH-reh", "eat", [
      ["io ho mangiato", "EE-oh oh mahn-JAH-toh", "I ate", "I", "past"],
      ["tu hai mangiato", "too eye mahn-JAH-toh", "you ate", "you", "past"],
      ["lui ha mangiato", "LOO-ee ah mahn-JAH-toh", "he ate", "he", "past"],
      ["noi abbiamo mangiato", "NOH-ee ahb-BYAH-moh mahn-JAH-toh", "we ate", "we", "past"],
      ["loro hanno mangiato", "LOH-roh AHN-noh mahn-JAH-toh", "they ate", "they", "past"],
      ["io mangio", "EE-oh MAHN-joh", "I eat", "I", "present"],
      ["tu mangi", "too MAHN-jee", "you eat", "you", "present"],
      ["lui mangia", "LOO-ee MAHN-jah", "he eats", "he", "present"],
      ["noi mangiamo", "NOH-ee mahn-JAH-moh", "we eat", "we", "present"],
      ["loro mangiano", "LOH-roh MAHN-jah-noh", "they eat", "they", "present"],
      ["io mangerò", "EE-oh mahn-jeh-ROH", "I will eat", "I", "future"],
      ["tu mangerai", "too mahn-jeh-RAI", "you will eat", "you", "future"],
      ["lui mangerà", "LOO-ee mahn-jeh-RAH", "he will eat", "he", "future"],
      ["noi mangeremo", "NOH-ee mahn-jeh-REH-moh", "we will eat", "we", "future"],
      ["loro mangeranno", "LOH-roh mahn-jeh-RAHN-noh", "they will eat", "they", "future"],
    ]),
    C("vedere", "veh-DEH-reh", "see", [
      ["io ho visto", "EE-oh oh VEES-toh", "I saw", "I", "past"],
      ["tu hai visto", "too eye VEES-toh", "you saw", "you", "past"],
      ["lui ha visto", "LOO-ee ah VEES-toh", "he saw", "he", "past"],
      ["noi abbiamo visto", "NOH-ee ahb-BYAH-moh VEES-toh", "we saw", "we", "past"],
      ["loro hanno visto", "LOH-roh AHN-noh VEES-toh", "they saw", "they", "past"],
      ["io vedo", "EE-oh VEH-doh", "I see", "I", "present"],
      ["tu vedi", "too VEH-dee", "you see", "you", "present"],
      ["lui vede", "LOO-ee VEH-deh", "he sees", "he", "present"],
      ["noi vediamo", "NOH-ee veh-DYAH-moh", "we see", "we", "present"],
      ["loro vedono", "LOH-roh VEH-doh-noh", "they see", "they", "present"],
      ["io vedrò", "EE-oh veh-DROH", "I will see", "I", "future"],
      ["tu vedrai", "too veh-DRAI", "you will see", "you", "future"],
      ["lui vedrà", "LOO-ee veh-DRAH", "he will see", "he", "future"],
      ["noi vedremo", "NOH-ee veh-DREH-moh", "we will see", "we", "future"],
      ["loro vedranno", "LOH-roh veh-DRAHN-noh", "they will see", "they", "future"],
    ]),
    C("potere", "poh-TEH-reh", "be able to", [
      ["io ho potuto", "EE-oh oh poh-TOO-toh", "I could", "I", "past"],
      ["tu hai potuto", "too eye poh-TOO-toh", "you could", "you", "past"],
      ["lui ha potuto", "LOO-ee ah poh-TOO-toh", "he could", "he", "past"],
      ["noi abbiamo potuto", "NOH-ee ahb-BYAH-moh poh-TOO-toh", "we could", "we", "past"],
      ["loro hanno potuto", "LOH-roh AHN-noh poh-TOO-toh", "they could", "they", "past"],
      ["io posso", "EE-oh POS-soh", "I can", "I", "present"],
      ["tu puoi", "too PWOH-ee", "you can", "you", "present"],
      ["lui può", "LOO-ee PWOH", "he can", "he", "present"],
      ["noi possiamo", "NOH-ee pos-SYAH-moh", "we can", "we", "present"],
      ["loro possono", "LOH-roh POS-soh-noh", "they can", "they", "present"],
      ["io potrò", "EE-oh poh-TROH", "I will be able to", "I", "future"],
      ["tu potrai", "too poh-TRAI", "you will be able to", "you", "future"],
      ["lui potrà", "LOO-ee poh-TRAH", "he will be able to", "he", "future"],
      ["noi potremo", "NOH-ee poh-TREH-moh", "we will be able to", "we", "future"],
      ["loro potranno", "LOH-roh poh-TRAHN-noh", "they will be able to", "they", "future"],
    ]),
    C("volere", "voh-LEH-reh", "want", [
      ["io ho voluto", "EE-oh oh voh-LOO-toh", "I wanted", "I", "past"],
      ["tu hai voluto", "too eye voh-LOO-toh", "you wanted", "you", "past"],
      ["lui ha voluto", "LOO-ee ah voh-LOO-toh", "he wanted", "he", "past"],
      ["noi abbiamo voluto", "NOH-ee ahb-BYAH-moh voh-LOO-toh", "we wanted", "we", "past"],
      ["loro hanno voluto", "LOH-roh AHN-noh voh-LOO-toh", "they wanted", "they", "past"],
      ["io voglio", "EE-oh VOH-lyoh", "I want", "I", "present"],
      ["tu vuoi", "too VWOH-ee", "you want", "you", "present"],
      ["lui vuole", "LOO-ee VWOH-leh", "he wants", "he", "present"],
      ["noi vogliamo", "NOH-ee voh-LYAH-moh", "we want", "we", "present"],
      ["loro vogliono", "LOH-roh VOH-lyoh-noh", "they want", "they", "present"],
      ["io vorrò", "EE-oh vor-ROH", "I will want", "I", "future"],
      ["tu vorrai", "too vor-RAI", "you will want", "you", "future"],
      ["lui vorrà", "LOO-ee vor-RAH", "he will want", "he", "future"],
      ["noi vorremo", "NOH-ee vor-REH-moh", "we will want", "we", "future"],
      ["loro vorranno", "LOH-roh vor-RAHN-noh", "they will want", "they", "future"],
    ]),
    C("venire", "veh-NEE-reh", "come", [
      ["io sono venuto", "EE-oh SOH-noh veh-NOO-toh", "I came", "I", "past"],
      ["tu sei venuto", "too SEH-ee veh-NOO-toh", "you came", "you", "past"],
      ["lui è venuto", "LOO-ee eh veh-NOO-toh", "he came", "he", "past"],
      ["noi siamo venuti", "NOH-ee SYAH-moh veh-NOO-tee", "we came", "we", "past"],
      ["loro sono venuti", "LOH-roh SOH-noh veh-NOO-tee", "they came", "they", "past"],
      ["io vengo", "EE-oh VEN-goh", "I come", "I", "present"],
      ["tu vieni", "too VYEH-nee", "you come", "you", "present"],
      ["lui viene", "LOO-ee VYEH-neh", "he comes", "he", "present"],
      ["noi veniamo", "NOH-ee veh-NYAH-moh", "we come", "we", "present"],
      ["loro vengono", "LOH-roh VEN-goh-noh", "they come", "they", "present"],
      ["io verrò", "EE-oh ver-ROH", "I will come", "I", "future"],
      ["tu verrai", "too ver-RAI", "you will come", "you", "future"],
      ["lui verrà", "LOO-ee ver-RAH", "he will come", "he", "future"],
      ["noi verremo", "NOH-ee ver-REH-moh", "we will come", "we", "future"],
      ["loro verranno", "LOH-roh ver-RAHN-noh", "they will come", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Persistence",
      l1: "Chi va piano,", l2: "va sano e va lontano.",
      tr1: "kee vah PYAH-noh", tr2: "vah SAH-noh eh vah lohn-TAH-noh",
      en: "Who goes slowly goes safely and goes far." },
    { n: 2, chapterEn: "Opportunity",
      l1: "Chi dorme", l2: "non piglia pesci.",
      tr1: "kee DOR-meh", tr2: "nohn PEE-lyah PEH-shee",
      en: "One who sleeps catches no fish." },
    { n: 3, chapterEn: "Truth",
      l1: "Le bugie", l2: "hanno le gambe corte.",
      tr1: "leh boo-JEE-eh", tr2: "AHN-noh leh GAHM-beh KOR-teh",
      en: "Lies have short legs." },
    { n: 4, chapterEn: "Friendship",
      l1: "Chi trova un amico", l2: "trova un tesoro.",
      tr1: "kee TROH-vah oon ah-MEE-koh", tr2: "TROH-vah oon teh-ZOH-roh",
      en: "Whoever finds a friend finds a treasure." },
    { n: 5, chapterEn: "Home",
      l1: "Casa mia,", l2: "casa mia, per piccina che tu sia.",
      tr1: "KAH-zah MEE-ah", tr2: "KAH-zah MEE-ah pehr peet-CHEE-nah keh too SEE-ah",
      en: "Home is home, however small you may be." },
    { n: 6, chapterEn: "Prudence",
      l1: "Non tutte le ciambelle", l2: "riescono col buco.",
      tr1: "nohn TOOT-teh leh chahm-BEL-leh", tr2: "RYEH-skoh-noh kohl BOO-koh",
      en: "Not all doughnuts come out with a hole — not everything goes to plan." },
    { n: 7, chapterEn: "Appearances",
      l1: "L'abito", l2: "non fa il monaco.",
      tr1: "LAH-bee-toh", tr2: "nohn fah eel MOH-nah-koh",
      en: "The habit does not make the monk." },
    { n: 8, chapterEn: "Timing",
      l1: "Il mattino", l2: "ha l'oro in bocca.",
      tr1: "eel maht-TEE-noh", tr2: "ah LOH-roh een BOK-kah",
      en: "The morning has gold in its mouth." },
    { n: 9, chapterEn: "Adaptation",
      l1: "Paese che vai,", l2: "usanza che trovi.",
      tr1: "pah-EH-zeh keh VAI", tr2: "oo-ZAHN-tsah keh TROH-vee",
      en: "Whatever country you go to, you'll find its own customs." },
    { n: 10, chapterEn: "Necessity",
      l1: "A caval donato", l2: "non si guarda in bocca.",
      tr1: "ah kah-VAHL doh-NAH-toh", tr2: "nohn see GWAR-dah een BOK-kah",
      en: "Don't look a gift horse in the mouth." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("italian", {
    icons: {
      alphabet: "Alfabeto", greetings: "Saluti", numbers: "Numeri", colors: "Colori",
      family: "Famiglia", people: "Gente", pronouns: "Pronomi", questions: "Domande",
      grammar: "Legami", adjectives: "Aggettivi", adverbs: "Avverbi", verbs: "Verbi",
      food: "Cibo", body: "Corpo", health: "Salute", clothing: "Vestiti", home: "Casa",
      animals: "Animali", nature: "Natura", places: "Luoghi", travel: "Viaggi",
      time: "Tempo", work: "Lavoro", school: "Scuola", tech: "Tecnologia",
      sentences: "Frasi",
    },
    ui: { account: "Account", progress: "Progressi", search: "Cerca" },
    alphabet: ALPHABET,
    alphabetTitle: "Alphabet & sounds",
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "Ripasso", vocab: "Parole", sentence: "Frasi", conjugation: "Verbi",
      listening: "Ascolto", mixed: "Misto", reading: "Proverbi",
    },
    reading: {
      id: "proverbi", title: "Proverbs", native: "Proverbi",
      desc: "Classic Italian sayings, line by line",
      blurb: "Proverbi — the sayings Italians reach for in everyday conversation.",
      unit: "sayings", numLabel: "Proverbio",
      lineQuestion: "Which line completes this proverb?",
      items: PROVERBS,
    },
  });
})();
