/* ============================================================================
 * Japanese course — data only.
 *
 * `ta` is the Japanese (kanji with kana as it is normally written), `tr` the
 * rōmaji (Hepburn, with ō ū for long vowels), `en` the meaning. Verbs are
 * given in the polite -masu form where that is what a learner will actually
 * say, and in the dictionary form where the list is about the word itself.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* -------------------------------- Kana ---------------------------------- */
  const HIRAGANA = A([
    ["あ", "a"], ["い", "i"], ["う", "u"], ["え", "e"], ["お", "o"],
    ["か", "ka"], ["き", "ki"], ["く", "ku"], ["け", "ke"], ["こ", "ko"],
    ["さ", "sa"], ["し", "shi"], ["す", "su"], ["せ", "se"], ["そ", "so"],
    ["た", "ta"], ["ち", "chi"], ["つ", "tsu"], ["て", "te"], ["と", "to"],
    ["な", "na"], ["に", "ni"], ["ぬ", "nu"], ["ね", "ne"], ["の", "no"],
    ["は", "ha"], ["ひ", "hi"], ["ふ", "fu"], ["へ", "he"], ["ほ", "ho"],
    ["ま", "ma"], ["み", "mi"], ["む", "mu"], ["め", "me"], ["も", "mo"],
    ["や", "ya"], ["ゆ", "yu"], ["よ", "yo"],
    ["ら", "ra"], ["り", "ri"], ["る", "ru"], ["れ", "re"], ["ろ", "ro"],
    ["わ", "wa"], ["を", "wo"], ["ん", "n"],
  ]);
  const KATAKANA = A([
    ["ア", "a"], ["イ", "i"], ["ウ", "u"], ["エ", "e"], ["オ", "o"],
    ["カ", "ka"], ["キ", "ki"], ["ク", "ku"], ["ケ", "ke"], ["コ", "ko"],
    ["サ", "sa"], ["シ", "shi"], ["ス", "su"], ["セ", "se"], ["ソ", "so"],
    ["タ", "ta"], ["チ", "chi"], ["ツ", "tsu"], ["テ", "te"], ["ト", "to"],
    ["ナ", "na"], ["ニ", "ni"], ["ヌ", "nu"], ["ネ", "ne"], ["ノ", "no"],
    ["ハ", "ha"], ["ヒ", "hi"], ["フ", "fu"], ["ヘ", "he"], ["ホ", "ho"],
    ["マ", "ma"], ["ミ", "mi"], ["ム", "mu"], ["メ", "me"], ["モ", "mo"],
    ["ヤ", "ya"], ["ユ", "yu"], ["ヨ", "yo"],
    ["ラ", "ra"], ["リ", "ri"], ["ル", "ru"], ["レ", "re"], ["ロ", "ro"],
    ["ワ", "wa"], ["ヲ", "wo"], ["ン", "n"],
  ]);
  const ALPHABET = { vowels: HIRAGANA, consonants: KATAKANA };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["こんにちは", "konnichiwa", "hello / good afternoon"],
      ["おはようございます", "ohayō gozaimasu", "good morning"],
      ["こんばんは", "konbanwa", "good evening"],
      ["おやすみなさい", "oyasuminasai", "good night"],
      ["さようなら", "sayōnara", "goodbye"],
      ["じゃあね", "jā ne", "see you (casual)"],
      ["また明日", "mata ashita", "see you tomorrow"],
      ["ありがとう", "arigatō", "thank you"],
      ["ありがとうございます", "arigatō gozaimasu", "thank you (polite)"],
      ["どういたしまして", "dō itashimashite", "you're welcome"],
      ["お願いします", "onegai shimasu", "please"],
      ["はい", "hai", "yes"], ["いいえ", "iie", "no"],
      ["すみません", "sumimasen", "excuse me / sorry"],
      ["ごめんなさい", "gomen nasai", "I'm sorry"],
      ["お元気ですか", "o-genki desu ka", "how are you?"],
      ["元気です", "genki desu", "I'm well"],
      ["はじめまして", "hajimemashite", "how do you do (first meeting)"],
      ["よろしくお願いします", "yoroshiku onegai shimasu", "pleased to meet you"],
      ["いらっしゃいませ", "irasshaimase", "welcome (to a shop)"],
      ["おめでとう", "omedetō", "congratulations"],
      ["頑張って", "ganbatte", "good luck / do your best"],
      ["乾杯", "kanpai", "cheers"],
      ["いただきます", "itadakimasu", "said before eating"],
      ["ごちそうさま", "gochisōsama", "said after eating"],
      ["大丈夫", "daijōbu", "it's fine / all right"],
      ["お名前は？", "o-namae wa", "what is your name?"],
    ]),
    V("numbers", [
      ["ゼロ", "zero", "zero"], ["一", "ichi", "one"], ["二", "ni", "two"],
      ["三", "san", "three"], ["四", "yon", "four"], ["五", "go", "five"],
      ["六", "roku", "six"], ["七", "nana", "seven"], ["八", "hachi", "eight"],
      ["九", "kyū", "nine"], ["十", "jū", "ten"], ["十一", "jūichi", "eleven"],
      ["十二", "jūni", "twelve"], ["二十", "nijū", "twenty"],
      ["三十", "sanjū", "thirty"], ["五十", "gojū", "fifty"],
      ["百", "hyaku", "one hundred"], ["千", "sen", "one thousand"],
      ["一万", "ichiman", "ten thousand"], ["一番", "ichiban", "number one / most"],
      ["最初", "saisho", "the first"], ["最後", "saigo", "the last"],
      ["半分", "hanbun", "half"], ["いくつ", "ikutsu", "how many"],
      ["一つ", "hitotsu", "one thing"], ["二つ", "futatsu", "two things"],
      ["三つ", "mittsu", "three things"], ["番号", "bangō", "number"],
    ]),
    V("colors", [
      ["赤", "aka", "red"], ["青", "ao", "blue"], ["緑", "midori", "green"],
      ["黄色", "kiiro", "yellow"], ["黒", "kuro", "black"], ["白", "shiro", "white"],
      ["灰色", "haiiro", "grey"], ["茶色", "chairo", "brown"],
      ["オレンジ", "orenji", "orange"], ["ピンク", "pinku", "pink"],
      ["紫", "murasaki", "purple"], ["金色", "kin'iro", "gold"],
      ["銀色", "gin'iro", "silver"], ["色", "iro", "colour"],
      ["明るい", "akarui", "bright"], ["暗い", "kurai", "dark"],
      ["薄い", "usui", "pale / thin"], ["濃い", "koi", "deep / dark (colour)"],
      ["水色", "mizuiro", "light blue"], ["カラフル", "karafuru", "colourful"],
      ["透明", "tōmei", "transparent"],
    ]),
    V("family", [
      ["家族", "kazoku", "family"], ["お母さん", "okāsan", "mother (someone else's)"],
      ["母", "haha", "my mother"], ["お父さん", "otōsan", "father (someone else's)"],
      ["父", "chichi", "my father"], ["両親", "ryōshin", "parents"],
      ["息子", "musuko", "son"], ["娘", "musume", "daughter"],
      ["お兄さん", "onīsan", "older brother"], ["兄", "ani", "my older brother"],
      ["弟", "otōto", "younger brother"], ["お姉さん", "onēsan", "older sister"],
      ["姉", "ane", "my older sister"], ["妹", "imōto", "younger sister"],
      ["おじいさん", "ojīsan", "grandfather"], ["おばあさん", "obāsan", "grandmother"],
      ["孫", "mago", "grandchild"], ["おじさん", "ojisan", "uncle"],
      ["おばさん", "obasan", "aunt"], ["いとこ", "itoko", "cousin"],
      ["夫", "otto", "husband"], ["妻", "tsuma", "wife"],
      ["赤ちゃん", "akachan", "baby"], ["子供", "kodomo", "child"],
      ["親戚", "shinseki", "relative"], ["結婚式", "kekkonshiki", "wedding"],
    ]),
    V("people", [
      ["人", "hito", "person"], ["人々", "hitobito", "people"],
      ["男の人", "otoko no hito", "man"], ["女の人", "onna no hito", "woman"],
      ["男の子", "otoko no ko", "boy"], ["女の子", "onna no ko", "girl"],
      ["友達", "tomodachi", "friend"], ["隣の人", "tonari no hito", "neighbour"],
      ["お客さん", "okyakusan", "guest / customer"],
      ["若者", "wakamono", "young person"], ["大人", "otona", "adult"],
      ["お年寄り", "otoshiyori", "elderly person"],
      ["外国人", "gaikokujin", "foreigner"], ["同僚", "dōryō", "colleague"],
      ["チーム", "chīmu", "team"], ["グループ", "gurūpu", "group"],
      ["名前", "namae", "name"], ["苗字", "myōji", "surname"],
      ["みんな", "minna", "everyone"], ["自分", "jibun", "oneself"],
      ["恋人", "koibito", "boyfriend / girlfriend"],
      ["先輩", "senpai", "senior colleague"], ["後輩", "kōhai", "junior colleague"],
    ]),
    V("pronouns", [
      ["私", "watashi", "I / me"], ["僕", "boku", "I (casual, male)"],
      ["あなた", "anata", "you"], ["彼", "kare", "he / boyfriend"],
      ["彼女", "kanojo", "she / girlfriend"], ["私たち", "watashitachi", "we"],
      ["彼ら", "karera", "they"], ["これ", "kore", "this (thing)"],
      ["それ", "sore", "that (near you)"], ["あれ", "are", "that (over there)"],
      ["この", "kono", "this (before a noun)"], ["その", "sono", "that (before a noun)"],
      ["ここ", "koko", "here"], ["そこ", "soko", "there"],
      ["あそこ", "asoko", "over there"], ["私の", "watashi no", "my"],
      ["あなたの", "anata no", "your"], ["彼の", "kare no", "his"],
      ["誰か", "dareka", "someone"], ["誰も", "daremo", "nobody (with a negative)"],
      ["何か", "nanika", "something"], ["みんなの", "minna no", "everyone's"],
      ["全部", "zenbu", "all of it"],
    ]),
    V("questions", [
      ["何", "nani", "what"], ["誰", "dare", "who"], ["どこ", "doko", "where"],
      ["いつ", "itsu", "when"], ["なぜ", "naze", "why"], ["どうして", "dōshite", "why (softer)"],
      ["どう", "dō", "how"], ["どうやって", "dō yatte", "how (by what means)"],
      ["どれ", "dore", "which one"], ["どの", "dono", "which (before a noun)"],
      ["いくら", "ikura", "how much (money)"], ["いくつ", "ikutsu", "how many"],
      ["どのくらい", "dono kurai", "how long / how much"],
      ["誰の", "dare no", "whose"], ["か", "ka", "makes a sentence a question"],
      ["ね", "ne", "isn't it? (seeking agreement)"],
      ["質問", "shitsumon", "question"], ["答え", "kotae", "answer"],
      ["聞く", "kiku", "to ask / to listen"], ["答える", "kotaeru", "to answer"],
      ["何時ですか", "nanji desu ka", "what time is it?"],
    ]),
    V("grammar", [
      ["は", "wa", "topic marker"], ["が", "ga", "subject marker"],
      ["を", "o", "object marker"], ["に", "ni", "to / at / in"],
      ["で", "de", "at / by means of"], ["の", "no", "possessive 'of'"],
      ["と", "to", "and / with"], ["も", "mo", "also"],
      ["から", "kara", "from / because"], ["まで", "made", "until"],
      ["や", "ya", "and (a partial list)"], ["でも", "demo", "but"],
      ["しかし", "shikashi", "however"], ["だから", "dakara", "so / therefore"],
      ["けど", "kedo", "though"], ["ために", "tame ni", "in order to"],
      ["上", "ue", "above / on"], ["下", "shita", "below / under"],
      ["中", "naka", "inside"], ["外", "soto", "outside"],
      ["前", "mae", "before / in front"], ["後", "ato", "after"],
      ["間", "aida", "between"], ["です", "desu", "polite 'is'"],
      ["ます", "masu", "polite verb ending"], ["ない", "nai", "not"],
      ["ください", "kudasai", "please (do)"],
    ]),
    V("adjectives", [
      ["大きい", "ōkii", "big"], ["小さい", "chiisai", "small"],
      ["いい", "ii", "good"], ["悪い", "warui", "bad"],
      ["新しい", "atarashii", "new"], ["古い", "furui", "old (things)"],
      ["若い", "wakai", "young"], ["長い", "nagai", "long"],
      ["短い", "mijikai", "short"], ["高い", "takai", "tall / expensive"],
      ["低い", "hikui", "low"], ["安い", "yasui", "cheap"],
      ["暑い", "atsui", "hot (weather)"], ["熱い", "atsui", "hot (to touch)"],
      ["寒い", "samui", "cold (weather)"], ["冷たい", "tsumetai", "cold (to touch)"],
      ["簡単", "kantan", "easy / simple"], ["難しい", "muzukashii", "difficult"],
      ["きれい", "kirei", "pretty / clean"], ["汚い", "kitanai", "dirty"],
      ["強い", "tsuyoi", "strong"], ["弱い", "yowai", "weak"],
      ["速い", "hayai", "fast"], ["遅い", "osoi", "slow / late"],
      ["楽しい", "tanoshii", "fun / enjoyable"], ["嬉しい", "ureshii", "happy"],
      ["悲しい", "kanashii", "sad"], ["疲れた", "tsukareta", "tired"],
      ["面白い", "omoshiroi", "interesting / funny"],
      ["美味しい", "oishii", "delicious"], ["静か", "shizuka", "quiet"],
      ["大切", "taisetsu", "important / precious"],
    ]),
    V("adverbs", [
      ["とても", "totemo", "very"], ["少し", "sukoshi", "a little"],
      ["たくさん", "takusan", "a lot"], ["よく", "yoku", "well / often"],
      ["いつも", "itsumo", "always"], ["決して", "kesshite", "never (with a negative)"],
      ["時々", "tokidoki", "sometimes"], ["今", "ima", "now"],
      ["今日", "kyō", "today"], ["昨日", "kinō", "yesterday"],
      ["明日", "ashita", "tomorrow"], ["早く", "hayaku", "early / quickly"],
      ["遅く", "osoku", "late"], ["ここに", "koko ni", "here"],
      ["近く", "chikaku", "nearby"], ["遠く", "tōku", "far away"],
      ["一緒に", "issho ni", "together"], ["だけ", "dake", "only"],
      ["たぶん", "tabun", "probably"], ["もう", "mō", "already"],
      ["まだ", "mada", "still / not yet"], ["また", "mata", "again"],
      ["ゆっくり", "yukkuri", "slowly"], ["すぐに", "sugu ni", "immediately"],
      ["ほとんど", "hotondo", "almost / mostly"], ["本当に", "hontō ni", "really"],
      ["ちょっと", "chotto", "a bit"],
    ]),
    V("verbs", [
      ["する", "suru", "to do"], ["ある", "aru", "to exist (things)"],
      ["いる", "iru", "to exist (people, animals)"], ["行く", "iku", "to go"],
      ["来る", "kuru", "to come"], ["帰る", "kaeru", "to return home"],
      ["できる", "dekiru", "to be able to"], ["ほしい", "hoshii", "to want (a thing)"],
      ["知る", "shiru", "to know"], ["分かる", "wakaru", "to understand"],
      ["言う", "iu", "to say"], ["話す", "hanasu", "to speak"],
      ["食べる", "taberu", "to eat"], ["飲む", "nomu", "to drink"],
      ["住む", "sumu", "to live (reside)"], ["見る", "miru", "to see / watch"],
      ["聞く", "kiku", "to listen / ask"], ["読む", "yomu", "to read"],
      ["書く", "kaku", "to write"], ["働く", "hataraku", "to work"],
      ["勉強する", "benkyō suru", "to study"], ["寝る", "neru", "to sleep"],
      ["起きる", "okiru", "to get up"], ["買う", "kau", "to buy"],
      ["売る", "uru", "to sell"], ["開ける", "akeru", "to open"],
      ["閉める", "shimeru", "to close"], ["始める", "hajimeru", "to begin"],
      ["終わる", "owaru", "to end"], ["手伝う", "tetsudau", "to help"],
      ["思う", "omou", "to think"], ["歩く", "aruku", "to walk"],
      ["走る", "hashiru", "to run"], ["待つ", "matsu", "to wait"],
      ["あげる", "ageru", "to give"], ["もらう", "morau", "to receive"],
      ["取る", "toru", "to take"], ["会う", "au", "to meet"],
      ["作る", "tsukuru", "to make"], ["使う", "tsukau", "to use"],
    ]),
    V("food", [
      ["食べ物", "tabemono", "food"], ["水", "mizu", "water"],
      ["ご飯", "gohan", "rice / a meal"], ["パン", "pan", "bread"],
      ["麺", "men", "noodles"], ["ラーメン", "rāmen", "ramen"],
      ["寿司", "sushi", "sushi"], ["肉", "niku", "meat"],
      ["鶏肉", "toriniku", "chicken"], ["牛肉", "gyūniku", "beef"],
      ["魚", "sakana", "fish"], ["卵", "tamago", "egg"],
      ["牛乳", "gyūnyū", "milk"], ["チーズ", "chīzu", "cheese"],
      ["果物", "kudamono", "fruit"], ["りんご", "ringo", "apple"],
      ["バナナ", "banana", "banana"], ["みかん", "mikan", "mandarin orange"],
      ["野菜", "yasai", "vegetables"], ["じゃがいも", "jagaimo", "potato"],
      ["トマト", "tomato", "tomato"], ["玉ねぎ", "tamanegi", "onion"],
      ["塩", "shio", "salt"], ["砂糖", "satō", "sugar"],
      ["醤油", "shōyu", "soy sauce"], ["油", "abura", "oil"],
      ["お茶", "ocha", "tea"], ["コーヒー", "kōhī", "coffee"],
      ["ジュース", "jūsu", "juice"], ["ビール", "bīru", "beer"],
      ["味噌汁", "misoshiru", "miso soup"], ["サラダ", "sarada", "salad"],
      ["朝ご飯", "asagohan", "breakfast"], ["昼ご飯", "hirugohan", "lunch"],
      ["晩ご飯", "bangohan", "dinner"], ["レストラン", "resutoran", "restaurant"],
      ["お会計", "okaikei", "the bill"], ["お腹がすいた", "onaka ga suita", "I'm hungry"],
    ]),
    V("body", [
      ["体", "karada", "body"], ["頭", "atama", "head"], ["髪", "kami", "hair"],
      ["顔", "kao", "face"], ["目", "me", "eye"], ["耳", "mimi", "ear"],
      ["鼻", "hana", "nose"], ["口", "kuchi", "mouth"], ["歯", "ha", "tooth"],
      ["舌", "shita", "tongue"], ["首", "kubi", "neck"], ["肩", "kata", "shoulder"],
      ["腕", "ude", "arm"], ["手", "te", "hand"], ["指", "yubi", "finger"],
      ["足", "ashi", "leg / foot"], ["膝", "hiza", "knee"],
      ["背中", "senaka", "back"], ["胸", "mune", "chest"],
      ["心臓", "shinzō", "heart (organ)"], ["お腹", "onaka", "stomach / belly"],
      ["血", "chi", "blood"], ["骨", "hone", "bone"], ["皮膚", "hifu", "skin"],
      ["脳", "nō", "brain"],
    ]),
    V("health", [
      ["健康", "kenkō", "health"], ["医者", "isha", "doctor"],
      ["病院", "byōin", "hospital"], ["薬局", "yakkyoku", "pharmacy"],
      ["薬", "kusuri", "medicine"], ["病気", "byōki", "illness"],
      ["痛い", "itai", "painful / it hurts"], ["熱", "netsu", "fever"],
      ["咳", "seki", "cough"], ["風邪", "kaze", "a cold"],
      ["怪我", "kega", "injury"], ["看護師", "kangoshi", "nurse"],
      ["予約", "yoyaku", "appointment / reservation"],
      ["救急車", "kyūkyūsha", "ambulance"], ["緊急", "kinkyū", "emergency"],
      ["休む", "yasumu", "to rest / take time off"],
      ["運動", "undō", "exercise"], ["検査", "kensa", "examination / test"],
      ["治る", "naoru", "to get better"], ["頭痛", "zutsū", "headache"],
      ["腹痛", "fukutsū", "stomach ache"], ["元気", "genki", "well / energetic"],
    ]),
    V("clothing", [
      ["服", "fuku", "clothes"], ["シャツ", "shatsu", "shirt"],
      ["Tシャツ", "tīshatsu", "t-shirt"], ["ズボン", "zubon", "trousers"],
      ["ジーンズ", "jīnzu", "jeans"], ["スカート", "sukāto", "skirt"],
      ["ワンピース", "wanpīsu", "dress"], ["コート", "kōto", "coat"],
      ["ジャケット", "jaketto", "jacket"], ["セーター", "sētā", "sweater"],
      ["靴", "kutsu", "shoes"], ["ブーツ", "būtsu", "boots"],
      ["靴下", "kutsushita", "socks"], ["帽子", "bōshi", "hat / cap"],
      ["マフラー", "mafurā", "scarf"], ["手袋", "tebukuro", "gloves"],
      ["ベルト", "beruto", "belt"], ["眼鏡", "megane", "glasses"],
      ["鞄", "kaban", "bag"], ["着物", "kimono", "kimono"],
      ["サイズ", "saizu", "size"], ["着る", "kiru", "to wear (upper body)"],
      ["履く", "haku", "to wear (shoes, trousers)"],
    ]),
    V("home", [
      ["家", "ie", "house / home"], ["アパート", "apāto", "apartment"],
      ["部屋", "heya", "room"], ["台所", "daidokoro", "kitchen"],
      ["風呂", "furo", "bath"], ["トイレ", "toire", "toilet"],
      ["寝室", "shinshitsu", "bedroom"], ["居間", "ima", "living room"],
      ["ドア", "doa", "door"], ["窓", "mado", "window"],
      ["机", "tsukue", "desk"], ["テーブル", "tēburu", "table"],
      ["椅子", "isu", "chair"], ["ベッド", "beddo", "bed"],
      ["布団", "futon", "futon"], ["ソファ", "sofa", "sofa"],
      ["電気", "denki", "light / electricity"], ["鏡", "kagami", "mirror"],
      ["鍵", "kagi", "key"], ["皿", "sara", "plate"],
      ["コップ", "koppu", "cup / glass"], ["箸", "hashi", "chopsticks"],
      ["スプーン", "supūn", "spoon"], ["庭", "niwa", "garden"],
      ["階段", "kaidan", "stairs"], ["屋根", "yane", "roof"],
      ["壁", "kabe", "wall"], ["床", "yuka", "floor"],
      ["冷蔵庫", "reizōko", "fridge"],
    ]),
    V("animals", [
      ["動物", "dōbutsu", "animal"], ["犬", "inu", "dog"], ["猫", "neko", "cat"],
      ["馬", "uma", "horse"], ["牛", "ushi", "cow"], ["豚", "buta", "pig"],
      ["羊", "hitsuji", "sheep"], ["鶏", "niwatori", "chicken"],
      ["鳥", "tori", "bird"], ["魚", "sakana", "fish"],
      ["ねずみ", "nezumi", "mouse"], ["うさぎ", "usagi", "rabbit"],
      ["ライオン", "raion", "lion"], ["虎", "tora", "tiger"],
      ["象", "zō", "elephant"], ["猿", "saru", "monkey"],
      ["熊", "kuma", "bear"], ["狼", "ōkami", "wolf"],
      ["蛇", "hebi", "snake"], ["蜘蛛", "kumo", "spider"],
      ["蝶", "chō", "butterfly"], ["蜂", "hachi", "bee"],
      ["蟻", "ari", "ant"], ["虫", "mushi", "insect"], ["亀", "kame", "turtle"],
    ]),
    V("nature", [
      ["自然", "shizen", "nature"], ["太陽", "taiyō", "sun"],
      ["月", "tsuki", "moon"], ["星", "hoshi", "star"],
      ["空", "sora", "sky"], ["雲", "kumo", "cloud"], ["雨", "ame", "rain"],
      ["雪", "yuki", "snow"], ["風", "kaze", "wind"], ["火", "hi", "fire"],
      ["土", "tsuchi", "soil"], ["地球", "chikyū", "the Earth"],
      ["海", "umi", "sea"], ["川", "kawa", "river"], ["湖", "mizuumi", "lake"],
      ["山", "yama", "mountain"], ["森", "mori", "forest"],
      ["木", "ki", "tree / wood"], ["花", "hana", "flower"],
      ["葉", "ha", "leaf"], ["草", "kusa", "grass"],
      ["浜辺", "hamabe", "beach"], ["島", "shima", "island"],
      ["砂漠", "sabaku", "desert"], ["石", "ishi", "stone"],
      ["天気", "tenki", "weather"], ["嵐", "arashi", "storm"],
      ["地震", "jishin", "earthquake"],
    ]),
    V("places", [
      ["場所", "basho", "place"], ["町", "machi", "town"],
      ["都市", "toshi", "city"], ["村", "mura", "village"],
      ["国", "kuni", "country"], ["道", "michi", "road / way"],
      ["市場", "ichiba", "market"], ["店", "mise", "shop"],
      ["銀行", "ginkō", "bank"], ["学校", "gakkō", "school"],
      ["神社", "jinja", "shrine"], ["お寺", "otera", "temple"],
      ["博物館", "hakubutsukan", "museum"], ["公園", "kōen", "park"],
      ["ホテル", "hoteru", "hotel"], ["空港", "kūkō", "airport"],
      ["駅", "eki", "station"], ["図書館", "toshokan", "library"],
      ["事務所", "jimusho", "office"], ["映画館", "eigakan", "cinema"],
      ["病院", "byōin", "hospital"], ["近所", "kinjo", "neighbourhood"],
      ["中心", "chūshin", "centre"], ["田舎", "inaka", "countryside"],
      ["コンビニ", "konbini", "convenience store"],
    ]),
    V("travel", [
      ["旅行", "ryokō", "travel / trip"], ["車", "kuruma", "car"],
      ["バス", "basu", "bus"], ["電車", "densha", "train"],
      ["新幹線", "shinkansen", "bullet train"], ["飛行機", "hikōki", "aeroplane"],
      ["自転車", "jitensha", "bicycle"], ["船", "fune", "boat / ship"],
      ["タクシー", "takushī", "taxi"], ["地下鉄", "chikatetsu", "underground"],
      ["切符", "kippu", "ticket"], ["パスポート", "pasupōto", "passport"],
      ["荷物", "nimotsu", "luggage"], ["スーツケース", "sūtsukēsu", "suitcase"],
      ["地図", "chizu", "map"], ["出発", "shuppatsu", "departure"],
      ["到着", "tōchaku", "arrival"], ["遅れ", "okure", "delay"],
      ["左", "hidari", "left"], ["右", "migi", "right"],
      ["まっすぐ", "massugu", "straight ahead"],
      ["道に迷う", "michi ni mayou", "to get lost"],
      ["税関", "zeikan", "customs"], ["観光", "kankō", "sightseeing"],
      ["お土産", "omiyage", "souvenir"],
    ]),
    V("time", [
      ["時間", "jikan", "time"], ["時", "ji", "o'clock"],
      ["分", "fun", "minute"], ["秒", "byō", "second"],
      ["日", "hi", "day"], ["週", "shū", "week"], ["月", "tsuki", "month"],
      ["年", "toshi", "year"], ["朝", "asa", "morning"],
      ["昼", "hiru", "noon / daytime"], ["夕方", "yūgata", "early evening"],
      ["夜", "yoru", "night"], ["月曜日", "getsuyōbi", "Monday"],
      ["火曜日", "kayōbi", "Tuesday"], ["水曜日", "suiyōbi", "Wednesday"],
      ["木曜日", "mokuyōbi", "Thursday"], ["金曜日", "kin'yōbi", "Friday"],
      ["土曜日", "doyōbi", "Saturday"], ["日曜日", "nichiyōbi", "Sunday"],
      ["一月", "ichigatsu", "January"], ["二月", "nigatsu", "February"],
      ["三月", "sangatsu", "March"], ["週末", "shūmatsu", "weekend"],
      ["時計", "tokei", "clock / watch"], ["春", "haru", "spring"],
      ["夏", "natsu", "summer"], ["秋", "aki", "autumn"], ["冬", "fuyu", "winter"],
    ]),
    V("work", [
      ["仕事", "shigoto", "work / job"], ["会社", "kaisha", "company"],
      ["社長", "shachō", "company president"], ["部長", "buchō", "department head"],
      ["社員", "shain", "employee"], ["給料", "kyūryō", "salary"],
      ["お金", "okane", "money"], ["円", "en", "yen"],
      ["値段", "nedan", "price"], ["払う", "harau", "to pay"],
      ["会議", "kaigi", "meeting"], ["企画", "kikaku", "project / plan"],
      ["お客様", "okyakusama", "customer (polite)"],
      ["請求書", "seikyūsho", "invoice"], ["契約", "keiyaku", "contract"],
      ["カード", "kādo", "card"], ["現金", "genkin", "cash"],
      ["職業", "shokugyō", "profession"], ["技師", "gishi", "engineer"],
      ["先生", "sensei", "teacher / doctor"], ["弁護士", "bengoshi", "lawyer"],
      ["稼ぐ", "kasegu", "to earn"], ["割引", "waribiki", "discount"],
      ["税金", "zeikin", "tax"], ["残業", "zangyō", "overtime"],
    ]),
    V("school", [
      ["学校", "gakkō", "school"], ["大学", "daigaku", "university"],
      ["教室", "kyōshitsu", "classroom"], ["授業", "jugyō", "lesson / class"],
      ["学生", "gakusei", "student"], ["生徒", "seito", "pupil"],
      ["先生", "sensei", "teacher"], ["本", "hon", "book"],
      ["ノート", "nōto", "notebook"], ["鉛筆", "enpitsu", "pencil"],
      ["ペン", "pen", "pen"], ["紙", "kami", "paper"],
      ["言葉", "kotoba", "word / language"], ["文", "bun", "sentence"],
      ["漢字", "kanji", "kanji characters"], ["試験", "shiken", "exam"],
      ["宿題", "shukudai", "homework"], ["成績", "seiseki", "grade / results"],
      ["習う", "narau", "to learn (from a teacher)"],
      ["教える", "oshieru", "to teach"], ["説明する", "setsumei suru", "to explain"],
      ["答え", "kotae", "answer"], ["日本語", "nihongo", "Japanese language"],
      ["歴史", "rekishi", "history"], ["数学", "sūgaku", "mathematics"],
      ["科学", "kagaku", "science"],
    ]),
    V("tech", [
      ["コンピューター", "konpyūtā", "computer"], ["パソコン", "pasokon", "personal computer"],
      ["電話", "denwa", "telephone"], ["携帯", "keitai", "mobile phone"],
      ["画面", "gamen", "screen"], ["キーボード", "kībōdo", "keyboard"],
      ["マウス", "mausu", "mouse"], ["インターネット", "intānetto", "internet"],
      ["ネット", "netto", "the net"], ["メール", "mēru", "email"],
      ["パスワード", "pasuwādo", "password"], ["ファイル", "fairu", "file"],
      ["フォルダ", "foruda", "folder"], ["アプリ", "apuri", "app"],
      ["ソフト", "sofuto", "software"], ["ダウンロード", "daunrōdo", "download"],
      ["アップロード", "appurōdo", "upload"], ["保存する", "hozon suru", "to save"],
      ["削除する", "sakujo suru", "to delete"], ["検索する", "kensaku suru", "to search"],
      ["つける", "tsukeru", "to switch on"], ["消す", "kesu", "to switch off / erase"],
      ["カメラ", "kamera", "camera"], ["電池", "denchi", "battery"],
      ["リンク", "rinku", "link"], ["データ", "dēta", "data"],
    ]),
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["こんにちは、お元気ですか。", "konnichiwa, o-genki desu ka", "Hello, how are you?",
        [["こんにちは", "konnichiwa"], ["お元気", "o-genki"], ["ですか", "desu ka"]]],
      ["はい、元気です。", "hai, genki desu", "Yes, I'm well",
        [["はい", "hai"], ["元気", "genki"], ["です", "desu"]]],
      ["お名前は何ですか。", "o-namae wa nan desu ka", "What is your name?",
        [["お名前", "o-namae"], ["は", "wa"], ["何", "nan"], ["ですか", "desu ka"]]],
      ["私は田中です。", "watashi wa Tanaka desu", "I am Tanaka",
        [["私", "watashi"], ["は", "wa"], ["田中", "Tanaka"], ["です", "desu"]]],
      ["分かりません。", "wakarimasen", "I don't understand",
        [["分かりません", "wakarimasen"]]],
      ["もう一度お願いします。", "mō ichido onegai shimasu", "Once more, please",
        [["もう一度", "mō ichido"], ["お願いします", "onegai shimasu"]]],
      ["はじめまして、よろしくお願いします。", "hajimemashite, yoroshiku onegai shimasu",
        "How do you do — pleased to meet you",
        [["はじめまして", "hajimemashite"], ["よろしく", "yoroshiku"], ["お願いします", "onegai shimasu"]]],
      ["英語を話せますか。", "eigo o hanasemasu ka", "Can you speak English?",
        [["英語", "eigo"], ["を", "o"], ["話せますか", "hanasemasu ka"]]],
    ]),
    S("food", [
      ["コーヒーをください。", "kōhī o kudasai", "Coffee, please",
        [["コーヒー", "kōhī"], ["を", "o"], ["ください", "kudasai"]]],
      ["お腹がすきました。", "onaka ga sukimashita", "I am hungry",
        [["お腹", "onaka"], ["が", "ga"], ["すきました", "sukimashita"]]],
      ["喉が渇きました。", "nodo ga kawakimashita", "I am thirsty",
        [["喉", "nodo"], ["が", "ga"], ["渇きました", "kawakimashita"]]],
      ["この料理は美味しいです。", "kono ryōri wa oishii desu", "This dish is delicious",
        [["この", "kono"], ["料理", "ryōri"], ["は", "wa"], ["美味しい", "oishii"], ["です", "desu"]]],
      ["お会計をお願いします。", "okaikei o onegai shimasu", "The bill, please",
        [["お会計", "okaikei"], ["を", "o"], ["お願いします", "onegai shimasu"]]],
      ["肉を食べません。", "niku o tabemasen", "I don't eat meat",
        [["肉", "niku"], ["を", "o"], ["食べません", "tabemasen"]]],
    ]),
    S("travel", [
      ["駅はどこですか。", "eki wa doko desu ka", "Where is the station?",
        [["駅", "eki"], ["は", "wa"], ["どこ", "doko"], ["ですか", "desu ka"]]],
      ["東京までの切符をください。", "Tōkyō made no kippu o kudasai",
        "A ticket to Tokyo, please",
        [["東京", "Tōkyō"], ["までの", "made no"], ["切符", "kippu"], ["を", "o"], ["ください", "kudasai"]]],
      ["電車は八時に来ます。", "densha wa hachiji ni kimasu", "The train comes at eight",
        [["電車", "densha"], ["は", "wa"], ["八時", "hachiji"], ["に", "ni"], ["来ます", "kimasu"]]],
      ["道に迷いました。", "michi ni mayoimashita", "I have lost my way",
        [["道", "michi"], ["に", "ni"], ["迷いました", "mayoimashita"]]],
      ["右に曲がってください。", "migi ni magatte kudasai", "Please turn right",
        [["右", "migi"], ["に", "ni"], ["曲がって", "magatte"], ["ください", "kudasai"]]],
    ]),
    S("home", [
      ["小さい家に住んでいます。", "chiisai ie ni sunde imasu", "I live in a small house",
        [["小さい", "chiisai"], ["家", "ie"], ["に", "ni"], ["住んでいます", "sunde imasu"]]],
      ["ドアが開いています。", "doa ga aite imasu", "The door is open",
        [["ドア", "doa"], ["が", "ga"], ["開いています", "aite imasu"]]],
      ["家族は大きいです。", "kazoku wa ōkii desu", "My family is big",
        [["家族", "kazoku"], ["は", "wa"], ["大きい", "ōkii"], ["です", "desu"]]],
    ]),
    S("time", [
      ["今何時ですか。", "ima nanji desu ka", "What time is it now?",
        [["今", "ima"], ["何時", "nanji"], ["ですか", "desu ka"]]],
      ["今日は月曜日です。", "kyō wa getsuyōbi desu", "Today is Monday",
        [["今日", "kyō"], ["は", "wa"], ["月曜日", "getsuyōbi"], ["です", "desu"]]],
      ["明日市場に行きます。", "ashita ichiba ni ikimasu", "Tomorrow I go to the market",
        [["明日", "ashita"], ["市場", "ichiba"], ["に", "ni"], ["行きます", "ikimasu"]]],
      ["いつも朝働きます。", "itsumo asa hatarakimasu", "I always work in the morning",
        [["いつも", "itsumo"], ["朝", "asa"], ["働きます", "hatarakimasu"]]],
    ]),
    S("school", [
      ["毎日日本語を勉強します。", "mainichi nihongo o benkyō shimasu",
        "I study Japanese every day",
        [["毎日", "mainichi"], ["日本語", "nihongo"], ["を", "o"], ["勉強します", "benkyō shimasu"]]],
      ["この本は面白いです。", "kono hon wa omoshiroi desu", "This book is interesting",
        [["この", "kono"], ["本", "hon"], ["は", "wa"], ["面白い", "omoshiroi"], ["です", "desu"]]],
      ["手伝ってくれますか。", "tetsudatte kuremasu ka", "Could you help me?",
        [["手伝って", "tetsudatte"], ["くれますか", "kuremasu ka"]]],
    ]),
    S("health", [
      ["頭が痛いです。", "atama ga itai desu", "My head hurts",
        [["頭", "atama"], ["が", "ga"], ["痛い", "itai"], ["です", "desu"]]],
      ["医者が必要です。", "isha ga hitsuyō desu", "I need a doctor",
        [["医者", "isha"], ["が", "ga"], ["必要", "hitsuyō"], ["です", "desu"]]],
      ["気分が悪いです。", "kibun ga warui desu", "I don't feel well",
        [["気分", "kibun"], ["が", "ga"], ["悪い", "warui"], ["です", "desu"]]],
    ]),
    S("work", [
      ["これはいくらですか。", "kore wa ikura desu ka", "How much is this?",
        [["これ", "kore"], ["は", "wa"], ["いくら", "ikura"], ["ですか", "desu ka"]]],
      ["高すぎます。", "takasugimasu", "It is too expensive",
        [["高すぎます", "takasugimasu"]]],
      ["事務所で働いています。", "jimusho de hataraite imasu", "I work in an office",
        [["事務所", "jimusho"], ["で", "de"], ["働いています", "hataraite imasu"]]],
    ]),
  );

  /* ----------------------------- Conjugation ------------------------------
   * Japanese verbs don't change with the person — they change with tense and
   * politeness. These tables use the polite -masu forms and vary the subject,
   * so the pattern (-mashita / -masu) is what you're really drilling. */
  const CONJUGATION = [
    C("食べる", "taberu", "eat", [
      ["私は食べました", "watashi wa tabemashita", "I ate", "I", "past"],
      ["あなたは食べました", "anata wa tabemashita", "you ate", "you", "past"],
      ["彼は食べました", "kare wa tabemashita", "he ate", "he", "past"],
      ["彼女は食べました", "kanojo wa tabemashita", "she ate", "she", "past"],
      ["私たちは食べました", "watashitachi wa tabemashita", "we ate", "we", "past"],
      ["彼らは食べました", "karera wa tabemashita", "they ate", "they", "past"],
      ["私は食べます", "watashi wa tabemasu", "I eat", "I", "present"],
      ["あなたは食べます", "anata wa tabemasu", "you eat", "you", "present"],
      ["彼は食べます", "kare wa tabemasu", "he eats", "he", "present"],
      ["私たちは食べます", "watashitachi wa tabemasu", "we eat", "we", "present"],
      ["彼らは食べます", "karera wa tabemasu", "they eat", "they", "present"],
      ["私は食べるつもりです", "watashi wa taberu tsumori desu", "I will eat", "I", "future"],
      ["あなたは食べるでしょう", "anata wa taberu deshō", "you will eat", "you", "future"],
      ["彼は食べるでしょう", "kare wa taberu deshō", "he will eat", "he", "future"],
      ["私たちは食べるでしょう", "watashitachi wa taberu deshō", "we will eat", "we", "future"],
      ["彼らは食べるでしょう", "karera wa taberu deshō", "they will eat", "they", "future"],
    ]),
    C("飲む", "nomu", "drink", [
      ["私は飲みました", "watashi wa nomimashita", "I drank", "I", "past"],
      ["あなたは飲みました", "anata wa nomimashita", "you drank", "you", "past"],
      ["彼は飲みました", "kare wa nomimashita", "he drank", "he", "past"],
      ["私たちは飲みました", "watashitachi wa nomimashita", "we drank", "we", "past"],
      ["彼らは飲みました", "karera wa nomimashita", "they drank", "they", "past"],
      ["私は飲みます", "watashi wa nomimasu", "I drink", "I", "present"],
      ["あなたは飲みます", "anata wa nomimasu", "you drink", "you", "present"],
      ["彼は飲みます", "kare wa nomimasu", "he drinks", "he", "present"],
      ["私たちは飲みます", "watashitachi wa nomimasu", "we drink", "we", "present"],
      ["彼らは飲みます", "karera wa nomimasu", "they drink", "they", "present"],
      ["私は飲むつもりです", "watashi wa nomu tsumori desu", "I will drink", "I", "future"],
      ["あなたは飲むでしょう", "anata wa nomu deshō", "you will drink", "you", "future"],
      ["彼は飲むでしょう", "kare wa nomu deshō", "he will drink", "he", "future"],
      ["私たちは飲むでしょう", "watashitachi wa nomu deshō", "we will drink", "we", "future"],
      ["彼らは飲むでしょう", "karera wa nomu deshō", "they will drink", "they", "future"],
    ]),
    C("行く", "iku", "go", [
      ["私は行きました", "watashi wa ikimashita", "I went", "I", "past"],
      ["あなたは行きました", "anata wa ikimashita", "you went", "you", "past"],
      ["彼は行きました", "kare wa ikimashita", "he went", "he", "past"],
      ["私たちは行きました", "watashitachi wa ikimashita", "we went", "we", "past"],
      ["彼らは行きました", "karera wa ikimashita", "they went", "they", "past"],
      ["私は行きます", "watashi wa ikimasu", "I go", "I", "present"],
      ["あなたは行きます", "anata wa ikimasu", "you go", "you", "present"],
      ["彼は行きます", "kare wa ikimasu", "he goes", "he", "present"],
      ["私たちは行きます", "watashitachi wa ikimasu", "we go", "we", "present"],
      ["彼らは行きます", "karera wa ikimasu", "they go", "they", "present"],
      ["私は行くつもりです", "watashi wa iku tsumori desu", "I will go", "I", "future"],
      ["あなたは行くでしょう", "anata wa iku deshō", "you will go", "you", "future"],
      ["彼は行くでしょう", "kare wa iku deshō", "he will go", "he", "future"],
      ["私たちは行くでしょう", "watashitachi wa iku deshō", "we will go", "we", "future"],
      ["彼らは行くでしょう", "karera wa iku deshō", "they will go", "they", "future"],
    ]),
    C("話す", "hanasu", "speak", [
      ["私は話しました", "watashi wa hanashimashita", "I spoke", "I", "past"],
      ["あなたは話しました", "anata wa hanashimashita", "you spoke", "you", "past"],
      ["彼は話しました", "kare wa hanashimashita", "he spoke", "he", "past"],
      ["私たちは話しました", "watashitachi wa hanashimashita", "we spoke", "we", "past"],
      ["彼らは話しました", "karera wa hanashimashita", "they spoke", "they", "past"],
      ["私は話します", "watashi wa hanashimasu", "I speak", "I", "present"],
      ["あなたは話します", "anata wa hanashimasu", "you speak", "you", "present"],
      ["彼は話します", "kare wa hanashimasu", "he speaks", "he", "present"],
      ["私たちは話します", "watashitachi wa hanashimasu", "we speak", "we", "present"],
      ["彼らは話します", "karera wa hanashimasu", "they speak", "they", "present"],
      ["私は話すつもりです", "watashi wa hanasu tsumori desu", "I will speak", "I", "future"],
      ["あなたは話すでしょう", "anata wa hanasu deshō", "you will speak", "you", "future"],
      ["彼は話すでしょう", "kare wa hanasu deshō", "he will speak", "he", "future"],
      ["私たちは話すでしょう", "watashitachi wa hanasu deshō", "we will speak", "we", "future"],
      ["彼らは話すでしょう", "karera wa hanasu deshō", "they will speak", "they", "future"],
    ]),
    C("見る", "miru", "see", [
      ["私は見ました", "watashi wa mimashita", "I saw", "I", "past"],
      ["あなたは見ました", "anata wa mimashita", "you saw", "you", "past"],
      ["彼は見ました", "kare wa mimashita", "he saw", "he", "past"],
      ["私たちは見ました", "watashitachi wa mimashita", "we saw", "we", "past"],
      ["彼らは見ました", "karera wa mimashita", "they saw", "they", "past"],
      ["私は見ます", "watashi wa mimasu", "I see", "I", "present"],
      ["あなたは見ます", "anata wa mimasu", "you see", "you", "present"],
      ["彼は見ます", "kare wa mimasu", "he sees", "he", "present"],
      ["私たちは見ます", "watashitachi wa mimasu", "we see", "we", "present"],
      ["彼らは見ます", "karera wa mimasu", "they see", "they", "present"],
      ["私は見るつもりです", "watashi wa miru tsumori desu", "I will see", "I", "future"],
      ["あなたは見るでしょう", "anata wa miru deshō", "you will see", "you", "future"],
      ["彼は見るでしょう", "kare wa miru deshō", "he will see", "he", "future"],
      ["私たちは見るでしょう", "watashitachi wa miru deshō", "we will see", "we", "future"],
      ["彼らは見るでしょう", "karera wa miru deshō", "they will see", "they", "future"],
    ]),
    C("読む", "yomu", "read", [
      ["私は読みました", "watashi wa yomimashita", "I read", "I", "past"],
      ["あなたは読みました", "anata wa yomimashita", "you read", "you", "past"],
      ["彼は読みました", "kare wa yomimashita", "he read", "he", "past"],
      ["私たちは読みました", "watashitachi wa yomimashita", "we read", "we", "past"],
      ["彼らは読みました", "karera wa yomimashita", "they read", "they", "past"],
      ["私は読みます", "watashi wa yomimasu", "I read", "I", "present"],
      ["あなたは読みます", "anata wa yomimasu", "you read", "you", "present"],
      ["彼は読みます", "kare wa yomimasu", "he reads", "he", "present"],
      ["私たちは読みます", "watashitachi wa yomimasu", "we read", "we", "present"],
      ["彼らは読みます", "karera wa yomimasu", "they read", "they", "present"],
      ["私は読むつもりです", "watashi wa yomu tsumori desu", "I will read", "I", "future"],
      ["あなたは読むでしょう", "anata wa yomu deshō", "you will read", "you", "future"],
      ["彼は読むでしょう", "kare wa yomu deshō", "he will read", "he", "future"],
      ["私たちは読むでしょう", "watashitachi wa yomu deshō", "we will read", "we", "future"],
      ["彼らは読むでしょう", "karera wa yomu deshō", "they will read", "they", "future"],
    ]),
    C("書く", "kaku", "write", [
      ["私は書きました", "watashi wa kakimashita", "I wrote", "I", "past"],
      ["あなたは書きました", "anata wa kakimashita", "you wrote", "you", "past"],
      ["彼は書きました", "kare wa kakimashita", "he wrote", "he", "past"],
      ["私たちは書きました", "watashitachi wa kakimashita", "we wrote", "we", "past"],
      ["彼らは書きました", "karera wa kakimashita", "they wrote", "they", "past"],
      ["私は書きます", "watashi wa kakimasu", "I write", "I", "present"],
      ["あなたは書きます", "anata wa kakimasu", "you write", "you", "present"],
      ["彼は書きます", "kare wa kakimasu", "he writes", "he", "present"],
      ["私たちは書きます", "watashitachi wa kakimasu", "we write", "we", "present"],
      ["彼らは書きます", "karera wa kakimasu", "they write", "they", "present"],
      ["私は書くつもりです", "watashi wa kaku tsumori desu", "I will write", "I", "future"],
      ["あなたは書くでしょう", "anata wa kaku deshō", "you will write", "you", "future"],
      ["彼は書くでしょう", "kare wa kaku deshō", "he will write", "he", "future"],
      ["私たちは書くでしょう", "watashitachi wa kaku deshō", "we will write", "we", "future"],
      ["彼らは書くでしょう", "karera wa kaku deshō", "they will write", "they", "future"],
    ]),
    C("買う", "kau", "buy", [
      ["私は買いました", "watashi wa kaimashita", "I bought", "I", "past"],
      ["あなたは買いました", "anata wa kaimashita", "you bought", "you", "past"],
      ["彼は買いました", "kare wa kaimashita", "he bought", "he", "past"],
      ["私たちは買いました", "watashitachi wa kaimashita", "we bought", "we", "past"],
      ["彼らは買いました", "karera wa kaimashita", "they bought", "they", "past"],
      ["私は買います", "watashi wa kaimasu", "I buy", "I", "present"],
      ["あなたは買います", "anata wa kaimasu", "you buy", "you", "present"],
      ["彼は買います", "kare wa kaimasu", "he buys", "he", "present"],
      ["私たちは買います", "watashitachi wa kaimasu", "we buy", "we", "present"],
      ["彼らは買います", "karera wa kaimasu", "they buy", "they", "present"],
      ["私は買うつもりです", "watashi wa kau tsumori desu", "I will buy", "I", "future"],
      ["あなたは買うでしょう", "anata wa kau deshō", "you will buy", "you", "future"],
      ["彼は買うでしょう", "kare wa kau deshō", "he will buy", "he", "future"],
      ["私たちは買うでしょう", "watashitachi wa kau deshō", "we will buy", "we", "future"],
      ["彼らは買うでしょう", "karera wa kau deshō", "they will buy", "they", "future"],
    ]),
    C("する", "suru", "do", [
      ["私はしました", "watashi wa shimashita", "I did", "I", "past"],
      ["あなたはしました", "anata wa shimashita", "you did", "you", "past"],
      ["彼はしました", "kare wa shimashita", "he did", "he", "past"],
      ["私たちはしました", "watashitachi wa shimashita", "we did", "we", "past"],
      ["彼らはしました", "karera wa shimashita", "they did", "they", "past"],
      ["私はします", "watashi wa shimasu", "I do", "I", "present"],
      ["あなたはします", "anata wa shimasu", "you do", "you", "present"],
      ["彼はします", "kare wa shimasu", "he does", "he", "present"],
      ["私たちはします", "watashitachi wa shimasu", "we do", "we", "present"],
      ["彼らはします", "karera wa shimasu", "they do", "they", "present"],
      ["私はするつもりです", "watashi wa suru tsumori desu", "I will do", "I", "future"],
      ["あなたはするでしょう", "anata wa suru deshō", "you will do", "you", "future"],
      ["彼はするでしょう", "kare wa suru deshō", "he will do", "he", "future"],
      ["私たちはするでしょう", "watashitachi wa suru deshō", "we will do", "we", "future"],
      ["彼らはするでしょう", "karera wa suru deshō", "they will do", "they", "future"],
    ]),
    C("来る", "kuru", "come", [
      ["私は来ました", "watashi wa kimashita", "I came", "I", "past"],
      ["あなたは来ました", "anata wa kimashita", "you came", "you", "past"],
      ["彼は来ました", "kare wa kimashita", "he came", "he", "past"],
      ["私たちは来ました", "watashitachi wa kimashita", "we came", "we", "past"],
      ["彼らは来ました", "karera wa kimashita", "they came", "they", "past"],
      ["私は来ます", "watashi wa kimasu", "I come", "I", "present"],
      ["あなたは来ます", "anata wa kimasu", "you come", "you", "present"],
      ["彼は来ます", "kare wa kimasu", "he comes", "he", "present"],
      ["私たちは来ます", "watashitachi wa kimasu", "we come", "we", "present"],
      ["彼らは来ます", "karera wa kimasu", "they come", "they", "present"],
      ["私は来るつもりです", "watashi wa kuru tsumori desu", "I will come", "I", "future"],
      ["あなたは来るでしょう", "anata wa kuru deshō", "you will come", "you", "future"],
      ["彼は来るでしょう", "kare wa kuru deshō", "he will come", "he", "future"],
      ["私たちは来るでしょう", "watashitachi wa kuru deshō", "we will come", "we", "future"],
      ["彼らは来るでしょう", "karera wa kuru deshō", "they will come", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs -------------------------------
   * ことわざ (kotowaza) — the short sayings that turn up in everyday speech. */
  const PROVERBS = [
    { n: 1, chapterEn: "Persistence",
      l1: "七転び", l2: "八起き。",
      tr1: "nana korobi", tr2: "ya oki",
      en: "Fall down seven times, get up eight." },
    { n: 2, chapterEn: "Patience",
      l1: "石の上にも", l2: "三年。",
      tr1: "ishi no ue ni mo", tr2: "sannen",
      en: "Three years sitting on a stone — persistence warms even rock." },
    { n: 3, chapterEn: "Society",
      l1: "出る杭は", l2: "打たれる。",
      tr1: "deru kui wa", tr2: "utareru",
      en: "The stake that sticks out gets hammered down." },
    { n: 4, chapterEn: "Beginnings",
      l1: "千里の道も", l2: "一歩から。",
      tr1: "senri no michi mo", tr2: "ippo kara",
      en: "Even a thousand-mile road begins with one step." },
    { n: 5, chapterEn: "Prudence",
      l1: "覆水", l2: "盆に返らず。",
      tr1: "fukusui", tr2: "bon ni kaerazu",
      en: "Spilled water does not return to the tray." },
    { n: 6, chapterEn: "Learning",
      l1: "聞くは一時の恥、", l2: "聞かぬは一生の恥。",
      tr1: "kiku wa ittoki no haji", tr2: "kikanu wa isshō no haji",
      en: "Asking is a moment's shame; not asking is a lifetime's shame." },
    { n: 7, chapterEn: "Company",
      l1: "類は", l2: "友を呼ぶ。",
      tr1: "rui wa", tr2: "tomo o yobu",
      en: "Like calls to like." },
    { n: 8, chapterEn: "Effort",
      l1: "案ずるより", l2: "産むが易し。",
      tr1: "anzuru yori", tr2: "umu ga yasushi",
      en: "Doing it is easier than worrying about it." },
    { n: 9, chapterEn: "Modesty",
      l1: "実るほど", l2: "頭を垂れる稲穂かな。",
      tr1: "minoru hodo", tr2: "kōbe o tareru inaho kana",
      en: "The riper the rice, the lower it bows its head." },
    { n: 10, chapterEn: "Time",
      l1: "光陰", l2: "矢の如し。",
      tr1: "kōin", tr2: "ya no gotoshi",
      en: "Time flies like an arrow." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("japanese", {
    icons: {
      alphabet: "かな", greetings: "あいさつ", numbers: "数字", colors: "色",
      family: "家族", people: "人々", pronouns: "代名詞", questions: "疑問",
      grammar: "助詞", adjectives: "形容詞", adverbs: "副詞", verbs: "動詞",
      food: "食べ物", body: "体", health: "健康", clothing: "服", home: "家",
      animals: "動物", nature: "自然", places: "場所", travel: "旅行",
      time: "時間", work: "仕事", school: "学校", tech: "技術", sentences: "文",
    },
    ui: { account: "アカウント", progress: "進捗", search: "検索" },
    alphabet: ALPHABET,
    alphabetTitle: "Hiragana & katakana",
    alphabetLabels: ["Hiragana", "Katakana"],
    alphabetUnit: "kana",
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "復習", vocab: "単語", sentence: "文", conjugation: "動詞",
      listening: "聴解", mixed: "総合", reading: "ことわざ",
    },
    reading: {
      id: "kotowaza", title: "Proverbs", native: "ことわざ",
      desc: "Classic Japanese sayings, line by line",
      blurb: "ことわざ — proverbs that still turn up in everyday Japanese.",
      unit: "sayings", numLabel: "第",
      lineQuestion: "Which line completes this proverb?",
      items: PROVERBS,
    },
  });
})();
