/* ============================================================================
 * Portuguese course (Brazilian) — data only.
 *
 * `ta` is the Portuguese, `tr` a plain-English respelling (stressed syllable
 * in CAPS; "ñ" marks a nasal vowel, as in "não" → "NOWÑ"), `en` the meaning.
 * Nouns carry their article so the gender is learned with the word.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------ Alphabet ------------------------------- */
  const LETTERS = A([
    ["A a", "ah"], ["B b", "beh"], ["C c", "seh"], ["D d", "deh"], ["E e", "eh"],
    ["F f", "EH-fee"], ["G g", "zheh"], ["H h", "ah-GAH"], ["I i", "ee"],
    ["J j", "ZHOH-tah"], ["K k", "kah"], ["L l", "EH-lee"], ["M m", "EH-mee"],
    ["N n", "EH-nee"], ["O o", "oh"], ["P p", "peh"], ["Q q", "keh"],
    ["R r", "EH-hee"], ["S s", "EH-see"], ["T t", "teh"], ["U u", "oo"],
    ["V v", "veh"], ["W w", "DAH-blyoo"], ["X x", "SHEES"], ["Y y", "EEP-see-lohn"],
    ["Z z", "zeh"],
  ]);
  const SOUNDS = A([
    ["ã / â", "añ", "nasal a"], ["õ", "oñ", "nasal o"], ["ão", "owñ", "as in 'não'"],
    ["ç", "s", "c with a cedilla"], ["ch", "sh", "as in 'chá'"],
    ["lh", "ly", "as in 'filho'"], ["nh", "ny", "as in 'sonho'"],
    ["rr / initial r", "h", "a breathy h in Brazil"],
    ["di / de", "jee", "as in 'dia'"], ["ti / te", "chee", "as in 'noite'"],
    ["s between vowels", "z", "as in 'casa'"], ["x", "sh / ks", "varies by word"],
    ["e (unstressed final)", "ee", "as in 'noite'"],
    ["o (unstressed final)", "oo", "as in 'gato'"],
  ]);
  const ALPHABET = { vowels: LETTERS, consonants: SOUNDS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["oi", "OY", "hi"], ["olá", "oh-LAH", "hello"],
      ["bom dia", "bohñ JEE-ah", "good morning"],
      ["boa tarde", "BOH-ah TAR-jee", "good afternoon"],
      ["boa noite", "BOH-ah NOY-chee", "good evening / good night"],
      ["tchau", "CHOW", "bye"], ["até logo", "ah-TEH LOH-goo", "see you later"],
      ["adeus", "ah-DEH-oos", "goodbye"],
      ["obrigado", "oh-bree-GAH-doo", "thank you (said by a man)"],
      ["obrigada", "oh-bree-GAH-dah", "thank you (said by a woman)"],
      ["de nada", "jee NAH-dah", "you're welcome"],
      ["por favor", "por fah-VOR", "please"],
      ["sim", "SEEÑ", "yes"], ["não", "NOWÑ", "no"],
      ["desculpe", "des-KOOL-pee", "sorry / excuse me"],
      ["com licença", "kohñ lee-SEN-sah", "excuse me (passing)"],
      ["tudo bem?", "TOO-doo BEÑ", "how are you? / all good?"],
      ["tudo bem", "TOO-doo BEÑ", "I'm fine"],
      ["como vai?", "KOH-moo VYE", "how are you?"],
      ["muito prazer", "MOOY-toh prah-ZEHR", "pleased to meet you"],
      ["bem-vindo", "beñ-VEEN-doo", "welcome"],
      ["até amanhã", "ah-TEH ah-mah-NYAÑ", "see you tomorrow"],
      ["bom apetite", "bohñ ah-peh-CHEE-chee", "enjoy your meal"],
      ["saúde", "sah-OO-jee", "cheers / bless you"],
      ["parabéns", "pah-rah-BEÑS", "congratulations"],
      ["boa sorte", "BOH-ah SOR-chee", "good luck"],
      ["tá bom", "tah BOHÑ", "okay"],
    ]),
    V("numbers", [
      ["zero", "ZEH-roo", "zero"], ["um", "OOÑ", "one"], ["dois", "DOYS", "two"],
      ["três", "TREHS", "three"], ["quatro", "KWAH-troo", "four"],
      ["cinco", "SEEN-koo", "five"], ["seis", "SAYS", "six"],
      ["sete", "SEH-chee", "seven"], ["oito", "OY-too", "eight"],
      ["nove", "NOH-vee", "nine"], ["dez", "DEHS", "ten"],
      ["onze", "OHN-zee", "eleven"], ["doze", "DOH-zee", "twelve"],
      ["treze", "TREH-zee", "thirteen"], ["quatorze", "kah-TOR-zee", "fourteen"],
      ["quinze", "KEEN-zee", "fifteen"], ["dezesseis", "deh-zeh-SAYS", "sixteen"],
      ["vinte", "VEEN-chee", "twenty"], ["trinta", "TREEN-tah", "thirty"],
      ["quarenta", "kwah-REN-tah", "forty"], ["cinquenta", "seen-KWEN-tah", "fifty"],
      ["cem", "SEÑ", "one hundred"], ["mil", "MEEW", "one thousand"],
      ["primeiro", "pree-MAY-roo", "first"], ["segundo", "seh-GOON-doo", "second"],
      ["último", "OOL-chee-moo", "last"], ["a metade", "ah meh-TAH-jee", "half"],
      ["o número", "oo NOO-meh-roo", "number"],
    ]),
    V("colors", [
      ["vermelho", "ver-MEH-lyoo", "red"], ["azul", "ah-ZOOW", "blue"],
      ["verde", "VER-jee", "green"], ["amarelo", "ah-mah-REH-loo", "yellow"],
      ["preto", "PREH-too", "black"], ["branco", "BRAHN-koo", "white"],
      ["cinza", "SEEN-zah", "grey"], ["marrom", "mah-HOHÑ", "brown"],
      ["laranja", "lah-RAHN-zhah", "orange"], ["rosa", "HOH-zah", "pink"],
      ["roxo", "HOH-shoo", "purple"], ["dourado", "doh-RAH-doo", "golden"],
      ["prateado", "prah-cheh-AH-doo", "silver"], ["claro", "KLAH-roo", "light (colour)"],
      ["escuro", "es-KOO-roo", "dark"], ["a cor", "ah KOR", "colour"],
      ["colorido", "koh-loh-REE-doo", "colourful"], ["bege", "BEH-zhee", "beige"],
      ["turquesa", "toor-KEH-zah", "turquoise"], ["brilhante", "bree-LYAHN-chee", "bright"],
      ["pálido", "PAH-lee-doo", "pale"], ["azul-claro", "ah-zoow-KLAH-roo", "light blue"],
    ]),
    V("family", [
      ["a família", "ah fah-MEE-lyah", "family"], ["a mãe", "ah MAIÑ", "mother"],
      ["o pai", "oo PYE", "father"], ["a mamãe", "ah mah-MAIÑ", "mum"],
      ["o papai", "oo pah-PYE", "dad"], ["os pais", "oos PYES", "parents"],
      ["o filho", "oo FEE-lyoo", "son"], ["a filha", "ah FEE-lyah", "daughter"],
      ["o irmão", "oo eer-MOWÑ", "brother"], ["a irmã", "ah eer-MAÑ", "sister"],
      ["o avô", "oo ah-VOH", "grandfather"], ["a avó", "ah ah-VAW", "grandmother"],
      ["o neto", "oo NEH-too", "grandson"], ["o tio", "oo CHEE-oo", "uncle"],
      ["a tia", "ah CHEE-ah", "aunt"], ["o primo", "oo PREE-moo", "cousin (m)"],
      ["o sobrinho", "oo soh-BREE-nyoo", "nephew"], ["o marido", "oo mah-REE-doo", "husband"],
      ["a esposa", "ah es-POH-zah", "wife"], ["o bebê", "oo beh-BEH", "baby"],
      ["a criança", "ah kree-AHN-sah", "child"], ["o menino", "oo meh-NEE-noo", "boy"],
      ["a menina", "ah meh-NEE-nah", "girl"], ["o parente", "oo pah-REN-chee", "relative"],
      ["o casamento", "oo kah-zah-MEN-too", "wedding"],
      ["o sogro", "oo SOH-groo", "father-in-law"],
    ]),
    V("people", [
      ["a pessoa", "ah peh-SOH-ah", "person"], ["a gente", "ah ZHEN-chee", "people / we"],
      ["o homem", "oo OH-meñ", "man"], ["a mulher", "ah moo-LYEHR", "woman"],
      ["o rapaz", "oo hah-PAHS", "young man"], ["a moça", "ah MOH-sah", "young woman"],
      ["o amigo", "oo ah-MEE-goo", "friend (m)"], ["a amiga", "ah ah-MEE-gah", "friend (f)"],
      ["o vizinho", "oo vee-ZEE-nyoo", "neighbour"], ["o senhor", "oo seh-NYOR", "sir"],
      ["a senhora", "ah seh-NYOH-rah", "madam"], ["o jovem", "oo ZHOH-veñ", "young person"],
      ["o adulto", "oo ah-DOOL-too", "adult"], ["o idoso", "oo ee-DOH-zoo", "elderly person"],
      ["o convidado", "oo kohn-vee-DAH-doo", "guest"],
      ["o estrangeiro", "oo es-trahn-ZHAY-roo", "foreigner"],
      ["o namorado", "oo nah-moh-RAH-doo", "boyfriend"],
      ["a namorada", "ah nah-moh-RAH-dah", "girlfriend"],
      ["a equipe", "ah eh-KEE-pee", "team"], ["o grupo", "oo GROO-poo", "group"],
      ["o nome", "oo NOH-mee", "name"], ["o sobrenome", "oo soh-breh-NOH-mee", "surname"],
      ["o colega", "oo koh-LEH-gah", "colleague"],
    ]),
    V("pronouns", [
      ["eu", "EH-oo", "I"], ["você", "voh-SEH", "you"], ["ele", "EH-lee", "he"],
      ["ela", "EH-lah", "she"], ["nós", "NOHS", "we"], ["vocês", "voh-SEHS", "you all"],
      ["eles", "EH-lees", "they (m)"], ["elas", "EH-lahs", "they (f)"],
      ["me", "MEE", "me"], ["te", "CHEE", "you (object)"], ["o", "OO", "him / it"],
      ["a", "AH", "her / it"], ["nos", "NOOS", "us"], ["meu", "MEH-oo", "my (m)"],
      ["minha", "MEE-nyah", "my (f)"], ["seu", "SEH-oo", "your / his"],
      ["sua", "SOO-ah", "your / her"], ["nosso", "NOH-soo", "our"],
      ["este", "ES-chee", "this"], ["esse", "EH-see", "that"],
      ["aquele", "ah-KEH-lee", "that (over there)"],
      ["alguém", "ahw-GEÑ", "someone"], ["ninguém", "neen-GEÑ", "nobody"],
      ["todos", "TOH-doos", "everyone"], ["se", "SEE", "oneself"],
    ]),
    V("questions", [
      ["o que?", "oo KEH", "what?"], ["quem?", "KEÑ", "who?"],
      ["onde?", "OHN-jee", "where?"], ["quando?", "KWAHN-doo", "when?"],
      ["por quê?", "por KEH", "why?"], ["como?", "KOH-moo", "how?"],
      ["qual?", "KWAHW", "which?"], ["quanto?", "KWAHN-too", "how much?"],
      ["quantos?", "KWAHN-toos", "how many?"], ["de onde?", "jee OHN-jee", "where from?"],
      ["para onde?", "PAH-rah OHN-jee", "where to?"], ["de quem?", "jee KEÑ", "whose?"],
      ["né?", "NEH", "right?"], ["a pergunta", "ah per-GOON-tah", "question"],
      ["a resposta", "ah hes-POS-tah", "answer"], ["perguntar", "per-goon-TAR", "to ask"],
      ["responder", "hes-pohn-DEHR", "to answer"],
      ["quanto custa?", "KWAHN-too KOOS-tah", "how much does it cost?"],
      ["que horas são?", "kee OH-rahs SOWÑ", "what time is it?"],
      ["o que aconteceu?", "oo kee ah-kohn-teh-SEH-oo", "what happened?"],
    ]),
    V("grammar", [
      ["e", "EE", "and"], ["ou", "OH", "or"], ["mas", "MAHS", "but"],
      ["porque", "por-KEE", "because"], ["se", "SEE", "if"], ["que", "KEE", "that (conj.)"],
      ["de", "JEE", "of / from"], ["a", "AH", "to"], ["em", "EÑ", "in / on"],
      ["com", "KOHÑ", "with"], ["sem", "SEÑ", "without"], ["para", "PAH-rah", "for / to"],
      ["por", "POR", "by / through"], ["sobre", "SOH-bree", "about / on"],
      ["entre", "EN-tree", "between"], ["desde", "DEZ-jee", "since"],
      ["até", "ah-TEH", "until"], ["o", "OO", "the (m)"], ["a", "AH", "the (f)"],
      ["um", "OOÑ", "a (m)"], ["uma", "OO-mah", "a (f)"],
      ["também", "tahñ-BEÑ", "also"], ["nem", "NEÑ", "nor"],
      ["embora", "eñ-BOH-rah", "although"], ["então", "en-TOWÑ", "then / so"],
      ["enquanto", "en-KWAHN-too", "while"], ["não", "NOWÑ", "not"],
    ]),
    V("adjectives", [
      ["grande", "GRAHN-jee", "big"], ["pequeno", "peh-KEH-noo", "small"],
      ["bom", "BOHÑ", "good"], ["ruim", "hoo-EEÑ", "bad"], ["novo", "NOH-voo", "new"],
      ["velho", "VEH-lyoo", "old"], ["jovem", "ZHOH-veñ", "young"],
      ["longo", "LOHN-goo", "long"], ["curto", "KOOR-too", "short"],
      ["alto", "AHW-too", "tall / high"], ["baixo", "BYE-shoo", "short / low"],
      ["quente", "KEN-chee", "hot"], ["frio", "FREE-oo", "cold"],
      ["fácil", "FAH-seew", "easy"], ["difícil", "jee-FEE-seew", "difficult"],
      ["bonito", "boh-NEE-too", "pretty"], ["feio", "FAY-oo", "ugly"],
      ["forte", "FOR-chee", "strong"], ["fraco", "FRAH-koo", "weak"],
      ["rápido", "HAH-pee-doo", "fast"], ["devagar", "deh-vah-GAR", "slow"],
      ["rico", "HEE-koo", "rich"], ["pobre", "POH-bree", "poor"],
      ["feliz", "feh-LEES", "happy"], ["triste", "TREES-chee", "sad"],
      ["cansado", "kahn-SAH-doo", "tired"], ["limpo", "LEEÑ-poo", "clean"],
      ["sujo", "SOO-zhoo", "dirty"], ["cheio", "SHAY-oo", "full"],
      ["vazio", "vah-ZEE-oo", "empty"], ["caro", "KAH-roo", "expensive"],
      ["barato", "bah-RAH-too", "cheap"], ["legal", "leh-GAHW", "cool / nice"],
    ]),
    V("adverbs", [
      ["muito", "MOOY-too", "very / a lot"], ["pouco", "POH-koo", "little"],
      ["bem", "BEÑ", "well"], ["mal", "MAHW", "badly"], ["sempre", "SEÑ-pree", "always"],
      ["nunca", "NOON-kah", "never"], ["às vezes", "ahs VEH-zees", "sometimes"],
      ["agora", "ah-GOH-rah", "now"], ["hoje", "OH-zhee", "today"],
      ["ontem", "OHN-teñ", "yesterday"], ["amanhã", "ah-mah-NYAÑ", "tomorrow"],
      ["cedo", "SEH-doo", "early"], ["tarde", "TAR-jee", "late"],
      ["aqui", "ah-KEE", "here"], ["ali", "ah-LEE", "there"],
      ["perto", "PER-too", "near"], ["longe", "LOHN-zhee", "far"],
      ["juntos", "ZHOON-toos", "together"], ["só", "SAW", "only"],
      ["talvez", "tahw-VEHS", "maybe"], ["já", "ZHAH", "already"],
      ["ainda", "ah-EEN-dah", "still / yet"], ["de novo", "jee NOH-voo", "again"],
      ["devagar", "deh-vah-GAR", "slowly"], ["depressa", "deh-PREH-sah", "quickly"],
      ["quase", "KWAH-zee", "almost"], ["demais", "deh-MYES", "too much"],
      ["realmente", "heh-ahw-MEN-chee", "really"],
    ]),
    V("verbs", [
      ["ser", "SEHR", "to be (permanent)"], ["estar", "es-TAR", "to be (state)"],
      ["ter", "TEHR", "to have"], ["fazer", "fah-ZEHR", "to do / make"],
      ["ir", "EER", "to go"], ["vir", "VEER", "to come"],
      ["poder", "poh-DEHR", "to be able to"], ["querer", "keh-REHR", "to want"],
      ["saber", "sah-BEHR", "to know (facts)"], ["conhecer", "koh-nyeh-SEHR", "to know (people)"],
      ["dizer", "jee-ZEHR", "to say"], ["falar", "fah-LAR", "to speak"],
      ["comer", "koh-MEHR", "to eat"], ["beber", "beh-BEHR", "to drink"],
      ["morar", "moh-RAR", "to live (reside)"], ["ver", "VEHR", "to see"],
      ["assistir", "ah-sees-CHEER", "to watch"], ["ouvir", "oh-VEER", "to hear"],
      ["ler", "LEHR", "to read"], ["escrever", "es-kreh-VEHR", "to write"],
      ["trabalhar", "trah-bah-LYAR", "to work"], ["estudar", "es-too-DAR", "to study"],
      ["dormir", "dor-MEER", "to sleep"], ["comprar", "kohñ-PRAR", "to buy"],
      ["vender", "ven-DEHR", "to sell"], ["abrir", "ah-BREER", "to open"],
      ["fechar", "feh-SHAR", "to close"], ["começar", "koh-meh-SAR", "to begin"],
      ["terminar", "ter-mee-NAR", "to finish"], ["ajudar", "ah-zhoo-DAR", "to help"],
      ["precisar", "preh-see-ZAR", "to need"], ["pensar", "pen-SAR", "to think"],
      ["andar", "ahn-DAR", "to walk"], ["correr", "koh-HEHR", "to run"],
      ["esperar", "es-peh-RAR", "to wait / hope"], ["dar", "DAR", "to give"],
      ["chegar", "sheh-GAR", "to arrive"], ["sair", "sah-EER", "to leave / go out"],
      ["gostar", "gos-TAR", "to like"],
    ]),
    V("food", [
      ["a comida", "ah koh-MEE-dah", "food"], ["a água", "ah AH-gwah", "water"],
      ["o pão", "oo POWÑ", "bread"], ["o arroz", "oo ah-HOHS", "rice"],
      ["o feijão", "oo fay-ZHOWÑ", "beans"], ["a carne", "ah KAR-nee", "meat"],
      ["o frango", "oo FRAHN-goo", "chicken"], ["o peixe", "oo PAY-shee", "fish"],
      ["o ovo", "oo OH-voo", "egg"], ["o leite", "oo LAY-chee", "milk"],
      ["o queijo", "oo KAY-zhoo", "cheese"], ["a manteiga", "ah mahn-TAY-gah", "butter"],
      ["a fruta", "ah FROO-tah", "fruit"], ["a maçã", "ah mah-SAÑ", "apple"],
      ["a banana", "ah bah-NAH-nah", "banana"], ["a laranja", "ah lah-RAHN-zhah", "orange"],
      ["o legume", "oo leh-GOO-mee", "vegetable"], ["a batata", "ah bah-TAH-tah", "potato"],
      ["o tomate", "oo toh-MAH-chee", "tomato"], ["a cebola", "ah seh-BOH-lah", "onion"],
      ["o alho", "oo AH-lyoo", "garlic"], ["o sal", "oo SAHW", "salt"],
      ["a pimenta", "ah pee-MEN-tah", "pepper"], ["o açúcar", "oo ah-SOO-kar", "sugar"],
      ["o óleo", "oo OH-lyoo", "oil"], ["o café", "oo kah-FEH", "coffee"],
      ["o chá", "oo SHAH", "tea"], ["o vinho", "oo VEE-nyoo", "wine"],
      ["a cerveja", "ah ser-VEH-zhah", "beer"], ["o suco", "oo SOO-koo", "juice"],
      ["a sopa", "ah SOH-pah", "soup"], ["a salada", "ah sah-LAH-dah", "salad"],
      ["a sobremesa", "ah soh-breh-MEH-zah", "dessert"],
      ["o café da manhã", "oo kah-FEH dah mah-NYAÑ", "breakfast"],
      ["o almoço", "oo ahw-MOH-soo", "lunch"], ["o jantar", "oo zhahn-TAR", "dinner"],
      ["o restaurante", "oo hes-tow-RAHN-chee", "restaurant"],
      ["a conta", "ah KOHN-tah", "the bill"],
    ]),
    V("body", [
      ["o corpo", "oo KOR-poo", "body"], ["a cabeça", "ah kah-BEH-sah", "head"],
      ["o cabelo", "oo kah-BEH-loo", "hair"], ["o rosto", "oo HOS-too", "face"],
      ["o olho", "oo OH-lyoo", "eye"], ["a orelha", "ah oh-REH-lyah", "ear"],
      ["o nariz", "oo nah-REES", "nose"], ["a boca", "ah BOH-kah", "mouth"],
      ["o dente", "oo DEN-chee", "tooth"], ["a língua", "ah LEEN-gwah", "tongue / language"],
      ["o pescoço", "oo pes-KOH-soo", "neck"], ["o ombro", "oo OHÑ-broo", "shoulder"],
      ["o braço", "oo BRAH-soo", "arm"], ["a mão", "ah MOWÑ", "hand"],
      ["o dedo", "oo DEH-doo", "finger"], ["a perna", "ah PER-nah", "leg"],
      ["o pé", "oo PEH", "foot"], ["o joelho", "oo zhoh-EH-lyoo", "knee"],
      ["as costas", "ahs KOS-tahs", "back"], ["o peito", "oo PAY-too", "chest"],
      ["o coração", "oo koh-rah-SOWÑ", "heart"], ["o estômago", "oo es-TOH-mah-goo", "stomach"],
      ["o sangue", "oo SAHN-gee", "blood"], ["o osso", "oo OH-soo", "bone"],
      ["a pele", "ah PEH-lee", "skin"],
    ]),
    V("health", [
      ["a saúde", "ah sah-OO-jee", "health"], ["o médico", "oo MEH-jee-koo", "doctor"],
      ["o hospital", "oo os-pee-TAHW", "hospital"], ["a farmácia", "ah far-MAH-syah", "pharmacy"],
      ["o remédio", "oo heh-MEH-jyoo", "medicine"], ["doente", "doh-EN-chee", "ill"],
      ["saudável", "sow-DAH-vew", "healthy"], ["a dor", "ah DOR", "pain"],
      ["a febre", "ah FEH-bree", "fever"], ["a tosse", "ah TOH-see", "cough"],
      ["o resfriado", "oo hes-free-AH-doo", "a cold"], ["a ferida", "ah feh-REE-dah", "wound"],
      ["a enfermeira", "ah en-fer-MAY-rah", "nurse"],
      ["a consulta", "ah kohn-SOOW-tah", "appointment"],
      ["está doendo", "es-TAH doh-EN-doo", "it hurts"],
      ["a ambulância", "ah ahñ-boo-LAHN-syah", "ambulance"],
      ["a emergência", "ah eh-mer-ZHEN-syah", "emergency"],
      ["descansar", "des-kahn-SAR", "to rest"],
      ["o exercício", "oo eh-zer-SEE-syoo", "exercise"], ["a dieta", "ah jee-EH-tah", "diet"],
      ["a receita", "ah heh-SAY-tah", "prescription / recipe"],
      ["melhorar", "meh-lyoh-RAR", "to get better"],
    ]),
    V("clothing", [
      ["a roupa", "ah HOH-pah", "clothes"], ["a camisa", "ah kah-MEE-zah", "shirt"],
      ["a camiseta", "ah kah-mee-ZEH-tah", "t-shirt"], ["a calça", "ah KAHW-sah", "trousers"],
      ["o jeans", "oo ZHEENS", "jeans"], ["o vestido", "oo ves-CHEE-doo", "dress"],
      ["a saia", "ah SYE-ah", "skirt"], ["o casaco", "oo kah-ZAH-koo", "coat"],
      ["a jaqueta", "ah zhah-KEH-tah", "jacket"], ["o suéter", "oo SWEH-ter", "sweater"],
      ["os sapatos", "oos sah-PAH-toos", "shoes"], ["as botas", "ahs BOH-tahs", "boots"],
      ["as meias", "ahs MAY-ahs", "socks"], ["o chapéu", "oo shah-PEH-oo", "hat"],
      ["o boné", "oo boh-NEH", "cap"], ["o cachecol", "oo kah-sheh-KOHW", "scarf"],
      ["as luvas", "ahs LOO-vahs", "gloves"], ["o cinto", "oo SEEN-too", "belt"],
      ["os óculos", "oos OH-koo-loos", "glasses"], ["a bolsa", "ah BOHW-sah", "handbag"],
      ["o terno", "oo TER-noo", "suit"], ["o tamanho", "oo tah-MAH-nyoo", "size"],
      ["vestir", "ves-CHEER", "to wear / put on"],
      ["experimentar", "es-peh-ree-men-TAR", "to try on"],
    ]),
    V("home", [
      ["a casa", "ah KAH-zah", "house / home"],
      ["o apartamento", "oo ah-par-tah-MEN-too", "apartment"],
      ["o quarto", "oo KWAR-too", "room / bedroom"], ["a cozinha", "ah koh-ZEE-nyah", "kitchen"],
      ["o banheiro", "oo bah-NYAY-roo", "bathroom"], ["a sala", "ah SAH-lah", "living room"],
      ["a porta", "ah POR-tah", "door"], ["a janela", "ah zhah-NEH-lah", "window"],
      ["a mesa", "ah MEH-zah", "table"], ["a cadeira", "ah kah-DAY-rah", "chair"],
      ["a cama", "ah KAH-mah", "bed"], ["o sofá", "oo soh-FAH", "sofa"],
      ["a lâmpada", "ah LAHÑ-pah-dah", "lamp"], ["o espelho", "oo es-PEH-lyoo", "mirror"],
      ["a chave", "ah SHAH-vee", "key"], ["o prato", "oo PRAH-too", "plate"],
      ["o copo", "oo KOH-poo", "glass"], ["a xícara", "ah SHEE-kah-rah", "cup"],
      ["a faca", "ah FAH-kah", "knife"], ["o garfo", "oo GAR-foo", "fork"],
      ["a colher", "ah koh-LYEHR", "spoon"], ["o jardim", "oo zhar-JEEÑ", "garden"],
      ["a escada", "ah es-KAH-dah", "stairs"], ["o telhado", "oo teh-LYAH-doo", "roof"],
      ["a parede", "ah pah-REH-jee", "wall"], ["o chão", "oo SHOWÑ", "floor"],
      ["a geladeira", "ah zheh-lah-DAY-rah", "fridge"],
    ]),
    V("animals", [
      ["o animal", "oo ah-nee-MAHW", "animal"], ["o cachorro", "oo kah-SHOH-hoo", "dog"],
      ["o gato", "oo GAH-too", "cat"], ["o cavalo", "oo kah-VAH-loo", "horse"],
      ["a vaca", "ah VAH-kah", "cow"], ["o porco", "oo POR-koo", "pig"],
      ["a ovelha", "ah oh-VEH-lyah", "sheep"], ["a galinha", "ah gah-LEE-nyah", "hen"],
      ["o pássaro", "oo PAH-sah-roo", "bird"], ["o peixe", "oo PAY-shee", "fish"],
      ["o rato", "oo HAH-too", "mouse / rat"], ["o coelho", "oo koh-EH-lyoo", "rabbit"],
      ["o leão", "oo leh-OWÑ", "lion"], ["o tigre", "oo CHEE-gree", "tiger"],
      ["o elefante", "oo eh-leh-FAHN-chee", "elephant"], ["o macaco", "oo mah-KAH-koo", "monkey"],
      ["o urso", "oo OOR-soo", "bear"], ["o lobo", "oo LOH-boo", "wolf"],
      ["a cobra", "ah KOH-brah", "snake"], ["a aranha", "ah ah-RAH-nyah", "spider"],
      ["a borboleta", "ah bor-boh-LEH-tah", "butterfly"], ["a abelha", "ah ah-BEH-lyah", "bee"],
      ["a formiga", "ah for-MEE-gah", "ant"], ["a mosca", "ah MOS-kah", "fly"],
      ["a tartaruga", "ah tar-tah-ROO-gah", "turtle"],
    ]),
    V("nature", [
      ["a natureza", "ah nah-too-REH-zah", "nature"], ["o sol", "oo SOHW", "sun"],
      ["a lua", "ah LOO-ah", "moon"], ["a estrela", "ah es-TREH-lah", "star"],
      ["o céu", "oo SEH-oo", "sky"], ["a nuvem", "ah NOO-veñ", "cloud"],
      ["a chuva", "ah SHOO-vah", "rain"], ["a neve", "ah NEH-vee", "snow"],
      ["o vento", "oo VEN-too", "wind"], ["o fogo", "oo FOH-goo", "fire"],
      ["a terra", "ah TEH-hah", "earth"], ["o mar", "oo MAR", "sea"],
      ["o rio", "oo HEE-oo", "river"], ["o lago", "oo LAH-goo", "lake"],
      ["a montanha", "ah mohn-TAH-nyah", "mountain"], ["a floresta", "ah floh-RES-tah", "forest"],
      ["a árvore", "ah AR-voh-ree", "tree"], ["a flor", "ah FLOR", "flower"],
      ["a folha", "ah FOH-lyah", "leaf"], ["a grama", "ah GRAH-mah", "grass"],
      ["a praia", "ah PRYE-ah", "beach"], ["a ilha", "ah EE-lyah", "island"],
      ["o deserto", "oo deh-ZER-too", "desert"], ["a pedra", "ah PEH-drah", "stone"],
      ["o tempo", "oo TEÑ-poo", "weather / time"],
      ["a tempestade", "ah teñ-pes-TAH-jee", "storm"],
    ]),
    V("places", [
      ["o lugar", "oo loo-GAR", "place"], ["a cidade", "ah see-DAH-jee", "city"],
      ["a vila", "ah VEE-lah", "village"], ["o país", "oo pah-EES", "country"],
      ["a rua", "ah HOO-ah", "street"], ["a praça", "ah PRAH-sah", "square"],
      ["o mercado", "oo mer-KAH-doo", "market"], ["a loja", "ah LOH-zhah", "shop"],
      ["o banco", "oo BAHN-koo", "bank"], ["a escola", "ah es-KOH-lah", "school"],
      ["a igreja", "ah ee-GREH-zhah", "church"], ["o museu", "oo moo-ZEH-oo", "museum"],
      ["o parque", "oo PAR-kee", "park"], ["o hotel", "oo oh-TEW", "hotel"],
      ["o aeroporto", "oo ah-eh-roh-POR-too", "airport"],
      ["a estação", "ah es-tah-SOWÑ", "station"],
      ["a biblioteca", "ah bee-blyoh-TEH-kah", "library"],
      ["o escritório", "oo es-kree-TOH-ryoo", "office"], ["o cinema", "oo see-NEH-mah", "cinema"],
      ["o bairro", "oo BYE-hoo", "neighbourhood"], ["o centro", "oo SEN-troo", "downtown"],
      ["o campo", "oo KAHÑ-poo", "countryside"], ["a fronteira", "ah frohn-TAY-rah", "border"],
      ["a padaria", "ah pah-dah-REE-ah", "bakery"],
    ]),
    V("travel", [
      ["a viagem", "ah vee-AH-zheñ", "journey"], ["viajar", "vee-ah-ZHAR", "to travel"],
      ["o carro", "oo KAH-hoo", "car"], ["o ônibus", "oo OH-nee-boos", "bus"],
      ["o trem", "oo TREÑ", "train"], ["o avião", "oo ah-vee-OWÑ", "aeroplane"],
      ["a bicicleta", "ah bee-see-KLEH-tah", "bicycle"], ["o barco", "oo BAR-koo", "boat"],
      ["o táxi", "oo TAHK-see", "taxi"], ["o metrô", "oo meh-TROH", "underground"],
      ["a passagem", "ah pah-SAH-zheñ", "ticket"],
      ["o passaporte", "oo pah-sah-POR-chee", "passport"],
      ["a mala", "ah MAH-lah", "suitcase"], ["a bagagem", "ah bah-GAH-zheñ", "luggage"],
      ["o mapa", "oo MAH-pah", "map"], ["o caminho", "oo kah-MEE-nyoo", "way / path"],
      ["a estrada", "ah es-TRAH-dah", "road"], ["a saída", "ah sah-EE-dah", "exit"],
      ["a chegada", "ah sheh-GAH-dah", "arrival"], ["o atraso", "oo ah-TRAH-zoo", "delay"],
      ["à esquerda", "ah es-KEHR-dah", "to the left"],
      ["à direita", "ah jee-RAY-tah", "to the right"],
      ["em frente", "eñ FREN-chee", "straight ahead"],
      ["se perder", "see per-DEHR", "to get lost"], ["a alfândega", "ah ahw-FAHN-deh-gah", "customs"],
    ]),
    V("time", [
      ["o tempo", "oo TEÑ-poo", "time"], ["a hora", "ah OH-rah", "hour"],
      ["o minuto", "oo mee-NOO-too", "minute"], ["o segundo", "oo seh-GOON-doo", "second"],
      ["o dia", "oo JEE-ah", "day"], ["a semana", "ah seh-MAH-nah", "week"],
      ["o mês", "oo MEHS", "month"], ["o ano", "oo AH-noo", "year"],
      ["a manhã", "ah mah-NYAÑ", "morning"], ["a tarde", "ah TAR-jee", "afternoon"],
      ["a noite", "ah NOY-chee", "night"], ["segunda-feira", "seh-GOON-dah FAY-rah", "Monday"],
      ["terça-feira", "TER-sah FAY-rah", "Tuesday"],
      ["quarta-feira", "KWAR-tah FAY-rah", "Wednesday"],
      ["quinta-feira", "KEEN-tah FAY-rah", "Thursday"],
      ["sexta-feira", "SES-tah FAY-rah", "Friday"], ["sábado", "SAH-bah-doo", "Saturday"],
      ["domingo", "doh-MEEN-goo", "Sunday"], ["janeiro", "zhah-NAY-roo", "January"],
      ["fevereiro", "feh-veh-RAY-roo", "February"], ["março", "MAR-soo", "March"],
      ["abril", "ah-BREEW", "April"], ["maio", "MYE-oo", "May"],
      ["junho", "ZHOO-nyoo", "June"], ["julho", "ZHOO-lyoo", "July"],
      ["o fim de semana", "oo feeñ jee seh-MAH-nah", "weekend"],
      ["o relógio", "oo heh-LOH-zhyoo", "clock / watch"],
      ["o verão", "oo veh-ROWÑ", "summer"], ["o inverno", "oo een-VER-noo", "winter"],
    ]),
    V("work", [
      ["o trabalho", "oo trah-BAH-lyoo", "work"], ["o emprego", "oo eñ-PREH-goo", "job"],
      ["a empresa", "ah eñ-PREH-zah", "company"], ["o chefe", "oo SHEH-fee", "boss"],
      ["o funcionário", "oo foon-syoh-NAH-ryoo", "employee"],
      ["o salário", "oo sah-LAH-ryoo", "salary"], ["o dinheiro", "oo jee-NYAY-roo", "money"],
      ["o real", "oo heh-AHW", "real (currency)"], ["o preço", "oo PREH-soo", "price"],
      ["pagar", "pah-GAR", "to pay"], ["a reunião", "ah heh-oo-nee-OWÑ", "meeting"],
      ["o projeto", "oo proh-ZHEH-too", "project"], ["o cliente", "oo klee-EN-chee", "client"],
      ["a nota fiscal", "ah NOH-tah fees-KAHW", "invoice / receipt"],
      ["o contrato", "oo kohn-TRAH-too", "contract"], ["o cartão", "oo kar-TOWÑ", "card"],
      ["o dinheiro vivo", "oo jee-NYAY-roo VEE-voo", "cash"],
      ["a profissão", "ah proh-fee-SOWÑ", "profession"],
      ["o engenheiro", "oo en-zheh-NYAY-roo", "engineer"],
      ["o advogado", "oo ahd-voh-GAH-doo", "lawyer"],
      ["o professor", "oo proh-feh-SOR", "teacher"],
      ["ganhar", "gah-NYAR", "to earn / win"], ["o desconto", "oo des-KOHN-too", "discount"],
    ]),
    V("school", [
      ["a escola", "ah es-KOH-lah", "school"],
      ["a universidade", "ah oo-nee-ver-see-DAH-jee", "university"],
      ["a aula", "ah OW-lah", "class / lesson"], ["o aluno", "oo ah-LOO-noo", "pupil"],
      ["o estudante", "oo es-too-DAHN-chee", "student"],
      ["o professor", "oo proh-feh-SOR", "teacher"], ["o livro", "oo LEE-vroo", "book"],
      ["o caderno", "oo kah-DER-noo", "notebook"], ["o lápis", "oo LAH-pees", "pencil"],
      ["a caneta", "ah kah-NEH-tah", "pen"], ["o papel", "oo pah-PEW", "paper"],
      ["a palavra", "ah pah-LAH-vrah", "word"], ["a frase", "ah FRAH-zee", "sentence"],
      ["a lição", "ah lee-SOWÑ", "lesson"], ["a prova", "ah PROH-vah", "exam"],
      ["a lição de casa", "ah lee-SOWÑ jee KAH-zah", "homework"],
      ["a nota", "ah NOH-tah", "grade"], ["aprender", "ah-pren-DEHR", "to learn"],
      ["ensinar", "en-see-NAR", "to teach"], ["entender", "en-ten-DEHR", "to understand"],
      ["explicar", "es-plee-KAR", "to explain"], ["a resposta", "ah hes-POS-tah", "answer"],
      ["o idioma", "oo ee-jee-OH-mah", "language"], ["a história", "ah ees-TOH-ryah", "history"],
      ["a matemática", "ah mah-teh-MAH-chee-kah", "maths"],
      ["a ciência", "ah see-EN-syah", "science"],
    ]),
    V("tech", [
      ["o computador", "oo kohñ-poo-tah-DOR", "computer"],
      ["o telefone", "oo teh-leh-FOH-nee", "telephone"],
      ["o celular", "oo seh-loo-LAR", "mobile phone"], ["a tela", "ah TEH-lah", "screen"],
      ["o teclado", "oo teh-KLAH-doo", "keyboard"], ["o mouse", "oo MOW-see", "mouse"],
      ["a internet", "ah een-ter-NEH-chee", "internet"], ["a rede", "ah HEH-jee", "network"],
      ["o e-mail", "oo ee-MAY-oo", "email"], ["a senha", "ah SEH-nyah", "password"],
      ["o arquivo", "oo ar-KEE-voo", "file"], ["a pasta", "ah PAHS-tah", "folder"],
      ["o aplicativo", "oo ah-plee-kah-CHEE-voo", "app"],
      ["o programa", "oo proh-GRAH-mah", "program"],
      ["baixar", "bye-SHAR", "to download"], ["enviar", "en-vee-AR", "to send"],
      ["salvar", "sahw-VAR", "to save"], ["apagar", "ah-pah-GAR", "to delete"],
      ["procurar", "proh-koo-RAR", "to search"], ["ligar", "lee-GAR", "to switch on / call"],
      ["desligar", "des-lee-GAR", "to switch off"],
      ["a câmera", "ah KAH-meh-rah", "camera"], ["a bateria", "ah bah-teh-REE-ah", "battery"],
      ["o link", "oo LEEN-kee", "link"],
    ]),
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["Oi, tudo bem?", "oy TOO-doo BEÑ", "Hi, how are you?",
        [["Oi", "oy"], ["tudo", "TOO-doo"], ["bem", "BEÑ"]]],
      ["Estou muito bem, obrigado", "es-TOH MOOY-too BEÑ oh-bree-GAH-doo",
        "I am very well, thank you",
        [["Estou", "es-TOH"], ["muito", "MOOY-too"], ["bem", "BEÑ"], ["obrigado", "oh-bree-GAH-doo"]]],
      ["Como você se chama?", "KOH-moo voh-SEH see SHAH-mah", "What is your name?",
        [["Como", "KOH-moo"], ["você", "voh-SEH"], ["se", "see"], ["chama", "SHAH-mah"]]],
      ["Meu nome é João", "MEH-oo NOH-mee eh zhoo-OWÑ", "My name is João",
        [["Meu", "MEH-oo"], ["nome", "NOH-mee"], ["é", "eh"], ["João", "zhoo-OWÑ"]]],
      ["Não entendo", "nowñ en-TEN-doo", "I don't understand",
        [["Não", "nowñ"], ["entendo", "en-TEN-doo"]]],
      ["Pode repetir, por favor?", "POH-jee heh-peh-CHEER por fah-VOR",
        "Can you repeat, please?",
        [["Pode", "POH-jee"], ["repetir", "heh-peh-CHEER"], ["por", "por"], ["favor", "fah-VOR"]]],
      ["Muito prazer em conhecer você", "MOOY-too prah-ZEHR eñ koh-nyeh-SEHR voh-SEH",
        "Nice to meet you",
        [["Muito", "MOOY-too"], ["prazer", "prah-ZEHR"], ["em", "eñ"], ["conhecer", "koh-nyeh-SEHR"], ["você", "voh-SEH"]]],
      ["Você fala inglês?", "voh-SEH FAH-lah een-GLEHS", "Do you speak English?",
        [["Você", "voh-SEH"], ["fala", "FAH-lah"], ["inglês", "een-GLEHS"]]],
    ]),
    S("food", [
      ["Eu quero um café, por favor", "EH-oo KEH-roo ooñ kah-FEH por fah-VOR",
        "I want a coffee, please",
        [["Eu", "EH-oo"], ["quero", "KEH-roo"], ["um", "ooñ"], ["café", "kah-FEH"], ["por", "por"], ["favor", "fah-VOR"]]],
      ["Estou com fome", "es-TOH kohñ FOH-mee", "I am hungry",
        [["Estou", "es-TOH"], ["com", "kohñ"], ["fome", "FOH-mee"]]],
      ["Estou com sede", "es-TOH kohñ SEH-jee", "I am thirsty",
        [["Estou", "es-TOH"], ["com", "kohñ"], ["sede", "SEH-jee"]]],
      ["A comida está deliciosa", "ah koh-MEE-dah es-TAH deh-lee-see-OH-zah",
        "The food is delicious",
        [["A", "ah"], ["comida", "koh-MEE-dah"], ["está", "es-TAH"], ["deliciosa", "deh-lee-see-OH-zah"]]],
      ["A conta, por favor", "ah KOHN-tah por fah-VOR", "The bill, please",
        [["A", "ah"], ["conta", "KOHN-tah"], ["por", "por"], ["favor", "fah-VOR"]]],
      ["Eu não como carne", "EH-oo nowñ KOH-moo KAR-nee", "I don't eat meat",
        [["Eu", "EH-oo"], ["não", "nowñ"], ["como", "KOH-moo"], ["carne", "KAR-nee"]]],
    ]),
    S("travel", [
      ["Onde fica a estação?", "OHN-jee FEE-kah ah es-tah-SOWÑ", "Where is the station?",
        [["Onde", "OHN-jee"], ["fica", "FEE-kah"], ["a", "ah"], ["estação", "es-tah-SOWÑ"]]],
      ["Quero uma passagem para São Paulo", "KEH-roo OO-mah pah-SAH-zheñ PAH-rah sowñ POW-loo",
        "I want a ticket to São Paulo",
        [["Quero", "KEH-roo"], ["uma", "OO-mah"], ["passagem", "pah-SAH-zheñ"], ["para", "PAH-rah"], ["São Paulo", "sowñ POW-loo"]]],
      ["O trem chega às oito", "oo treñ SHEH-gah ahs OY-too", "The train arrives at eight",
        [["O", "oo"], ["trem", "treñ"], ["chega", "SHEH-gah"], ["às", "ahs"], ["oito", "OY-too"]]],
      ["Estou perdido", "es-TOH per-JEE-doo", "I am lost",
        [["Estou", "es-TOH"], ["perdido", "per-JEE-doo"]]],
      ["Vire à direita", "VEE-ree ah jee-RAY-tah", "Turn right",
        [["Vire", "VEE-ree"], ["à", "ah"], ["direita", "jee-RAY-tah"]]],
    ]),
    S("home", [
      ["Eu moro numa casa pequena", "EH-oo MOH-roo NOO-mah KAH-zah peh-KEH-nah",
        "I live in a small house",
        [["Eu", "EH-oo"], ["moro", "MOH-roo"], ["numa", "NOO-mah"], ["casa", "KAH-zah"], ["pequena", "peh-KEH-nah"]]],
      ["A porta está aberta", "ah POR-tah es-TAH ah-BER-tah", "The door is open",
        [["A", "ah"], ["porta", "POR-tah"], ["está", "es-TAH"], ["aberta", "ah-BER-tah"]]],
      ["Minha família é grande", "MEE-nyah fah-MEE-lyah eh GRAHN-jee", "My family is big",
        [["Minha", "MEE-nyah"], ["família", "fah-MEE-lyah"], ["é", "eh"], ["grande", "GRAHN-jee"]]],
    ]),
    S("time", [
      ["Que horas são?", "kee OH-rahs SOWÑ", "What time is it?",
        [["Que", "kee"], ["horas", "OH-rahs"], ["são", "SOWÑ"]]],
      ["Hoje é segunda-feira", "OH-zhee eh seh-GOON-dah FAY-rah", "Today is Monday",
        [["Hoje", "OH-zhee"], ["é", "eh"], ["segunda-feira", "seh-GOON-dah FAY-rah"]]],
      ["Amanhã vou ao mercado", "ah-mah-NYAÑ voh ow mer-KAH-doo",
        "Tomorrow I go to the market",
        [["Amanhã", "ah-mah-NYAÑ"], ["vou", "voh"], ["ao", "ow"], ["mercado", "mer-KAH-doo"]]],
      ["Eu sempre trabalho de manhã", "EH-oo SEÑ-pree trah-BAH-lyoo jee mah-NYAÑ",
        "I always work in the morning",
        [["Eu", "EH-oo"], ["sempre", "SEÑ-pree"], ["trabalho", "trah-BAH-lyoo"], ["de", "jee"], ["manhã", "mah-NYAÑ"]]],
    ]),
    S("school", [
      ["Eu estudo português todo dia", "EH-oo es-TOO-doo por-too-GEHS TOH-doo JEE-ah",
        "I study Portuguese every day",
        [["Eu", "EH-oo"], ["estudo", "es-TOO-doo"], ["português", "por-too-GEHS"], ["todo", "TOH-doo"], ["dia", "JEE-ah"]]],
      ["O livro é muito interessante", "oo LEE-vroo eh MOOY-too een-teh-reh-SAHN-chee",
        "The book is very interesting",
        [["O", "oo"], ["livro", "LEE-vroo"], ["é", "eh"], ["muito", "MOOY-too"], ["interessante", "een-teh-reh-SAHN-chee"]]],
      ["Você pode me ajudar?", "voh-SEH POH-jee mee ah-zhoo-DAR", "Can you help me?",
        [["Você", "voh-SEH"], ["pode", "POH-jee"], ["me", "mee"], ["ajudar", "ah-zhoo-DAR"]]],
    ]),
    S("health", [
      ["Minha cabeça está doendo", "MEE-nyah kah-BEH-sah es-TAH doh-EN-doo",
        "My head hurts",
        [["Minha", "MEE-nyah"], ["cabeça", "kah-BEH-sah"], ["está", "es-TAH"], ["doendo", "doh-EN-doo"]]],
      ["Preciso de um médico", "preh-SEE-zoo jee ooñ MEH-jee-koo", "I need a doctor",
        [["Preciso", "preh-SEE-zoo"], ["de", "jee"], ["um", "ooñ"], ["médico", "MEH-jee-koo"]]],
      ["Não estou me sentindo bem", "nowñ es-TOH mee sen-CHEEN-doo BEÑ",
        "I don't feel well",
        [["Não", "nowñ"], ["estou", "es-TOH"], ["me", "mee"], ["sentindo", "sen-CHEEN-doo"], ["bem", "BEÑ"]]],
    ]),
    S("work", [
      ["Quanto custa isso?", "KWAHN-too KOOS-tah EE-soo", "How much does this cost?",
        [["Quanto", "KWAHN-too"], ["custa", "KOOS-tah"], ["isso", "EE-soo"]]],
      ["É caro demais", "eh KAH-roo deh-MYES", "It is too expensive",
        [["É", "eh"], ["caro", "KAH-roo"], ["demais", "deh-MYES"]]],
      ["Eu trabalho num escritório", "EH-oo trah-BAH-lyoo nooñ es-kree-TOH-ryoo",
        "I work in an office",
        [["Eu", "EH-oo"], ["trabalho", "trah-BAH-lyoo"], ["num", "nooñ"], ["escritório", "es-kree-TOH-ryoo"]]],
    ]),
  );

  /* ----------------------------- Conjugation ------------------------------
   * Pretérito perfeito (past), presente, futuro. `você` is used for "you",
   * as it is in everyday Brazilian speech. */
  const CONJUGATION = [
    C("ser", "SEHR", "be", [
      ["eu fui", "EH-oo FOOY", "I was", "I", "past"],
      ["você foi", "voh-SEH FOY", "you were", "you", "past"],
      ["ele foi", "EH-lee FOY", "he was", "he", "past"],
      ["ela foi", "EH-lah FOY", "she was", "she", "past"],
      ["nós fomos", "nohs FOH-moos", "we were", "we", "past"],
      ["eles foram", "EH-lees FOH-rowñ", "they were", "they", "past"],
      ["eu sou", "EH-oo SOH", "I am", "I", "present"],
      ["você é", "voh-SEH EH", "you are", "you", "present"],
      ["ele é", "EH-lee EH", "he is", "he", "present"],
      ["ela é", "EH-lah EH", "she is", "she", "present"],
      ["nós somos", "nohs SOH-moos", "we are", "we", "present"],
      ["eles são", "EH-lees SOWÑ", "they are", "they", "present"],
      ["eu serei", "EH-oo seh-RAY", "I will be", "I", "future"],
      ["você será", "voh-SEH seh-RAH", "you will be", "you", "future"],
      ["ele será", "EH-lee seh-RAH", "he will be", "he", "future"],
      ["nós seremos", "nohs seh-REH-moos", "we will be", "we", "future"],
      ["eles serão", "EH-lees seh-ROWÑ", "they will be", "they", "future"],
    ]),
    C("estar", "es-TAR", "be (state)", [
      ["eu estive", "EH-oo es-CHEE-vee", "I was", "I", "past"],
      ["você esteve", "voh-SEH es-TEH-vee", "you were", "you", "past"],
      ["ele esteve", "EH-lee es-TEH-vee", "he was", "he", "past"],
      ["nós estivemos", "nohs es-chee-VEH-moos", "we were", "we", "past"],
      ["eles estiveram", "EH-lees es-chee-VEH-rowñ", "they were", "they", "past"],
      ["eu estou", "EH-oo es-TOH", "I am", "I", "present"],
      ["você está", "voh-SEH es-TAH", "you are", "you", "present"],
      ["ele está", "EH-lee es-TAH", "he is", "he", "present"],
      ["nós estamos", "nohs es-TAH-moos", "we are", "we", "present"],
      ["eles estão", "EH-lees es-TOWÑ", "they are", "they", "present"],
      ["eu estarei", "EH-oo es-tah-RAY", "I will be", "I", "future"],
      ["você estará", "voh-SEH es-tah-RAH", "you will be", "you", "future"],
      ["ele estará", "EH-lee es-tah-RAH", "he will be", "he", "future"],
      ["nós estaremos", "nohs es-tah-REH-moos", "we will be", "we", "future"],
      ["eles estarão", "EH-lees es-tah-ROWÑ", "they will be", "they", "future"],
    ]),
    C("ter", "TEHR", "have", [
      ["eu tive", "EH-oo CHEE-vee", "I had", "I", "past"],
      ["você teve", "voh-SEH TEH-vee", "you had", "you", "past"],
      ["ele teve", "EH-lee TEH-vee", "he had", "he", "past"],
      ["nós tivemos", "nohs chee-VEH-moos", "we had", "we", "past"],
      ["eles tiveram", "EH-lees chee-VEH-rowñ", "they had", "they", "past"],
      ["eu tenho", "EH-oo TEH-nyoo", "I have", "I", "present"],
      ["você tem", "voh-SEH TEÑ", "you have", "you", "present"],
      ["ele tem", "EH-lee TEÑ", "he has", "he", "present"],
      ["nós temos", "nohs TEH-moos", "we have", "we", "present"],
      ["eles têm", "EH-lees TEÑ-eñ", "they have", "they", "present"],
      ["eu terei", "EH-oo teh-RAY", "I will have", "I", "future"],
      ["você terá", "voh-SEH teh-RAH", "you will have", "you", "future"],
      ["ele terá", "EH-lee teh-RAH", "he will have", "he", "future"],
      ["nós teremos", "nohs teh-REH-moos", "we will have", "we", "future"],
      ["eles terão", "EH-lees teh-ROWÑ", "they will have", "they", "future"],
    ]),
    C("falar", "fah-LAR", "speak", [
      ["eu falei", "EH-oo fah-LAY", "I spoke", "I", "past"],
      ["você falou", "voh-SEH fah-LOH", "you spoke", "you", "past"],
      ["ele falou", "EH-lee fah-LOH", "he spoke", "he", "past"],
      ["nós falamos", "nohs fah-LAH-moos", "we spoke", "we", "past"],
      ["eles falaram", "EH-lees fah-LAH-rowñ", "they spoke", "they", "past"],
      ["eu falo", "EH-oo FAH-loo", "I speak", "I", "present"],
      ["você fala", "voh-SEH FAH-lah", "you speak", "you", "present"],
      ["ele fala", "EH-lee FAH-lah", "he speaks", "he", "present"],
      ["nós falamos", "nohs fah-LAH-moos", "we speak", "we", "present"],
      ["eles falam", "EH-lees FAH-lowñ", "they speak", "they", "present"],
      ["eu falarei", "EH-oo fah-lah-RAY", "I will speak", "I", "future"],
      ["você falará", "voh-SEH fah-lah-RAH", "you will speak", "you", "future"],
      ["ele falará", "EH-lee fah-lah-RAH", "he will speak", "he", "future"],
      ["nós falaremos", "nohs fah-lah-REH-moos", "we will speak", "we", "future"],
      ["eles falarão", "EH-lees fah-lah-ROWÑ", "they will speak", "they", "future"],
    ]),
    C("comer", "koh-MEHR", "eat", [
      ["eu comi", "EH-oo koh-MEE", "I ate", "I", "past"],
      ["você comeu", "voh-SEH koh-MEH-oo", "you ate", "you", "past"],
      ["ele comeu", "EH-lee koh-MEH-oo", "he ate", "he", "past"],
      ["nós comemos", "nohs koh-MEH-moos", "we ate", "we", "past"],
      ["eles comeram", "EH-lees koh-MEH-rowñ", "they ate", "they", "past"],
      ["eu como", "EH-oo KOH-moo", "I eat", "I", "present"],
      ["você come", "voh-SEH KOH-mee", "you eat", "you", "present"],
      ["ele come", "EH-lee KOH-mee", "he eats", "he", "present"],
      ["nós comemos", "nohs koh-MEH-moos", "we eat", "we", "present"],
      ["eles comem", "EH-lees KOH-meñ", "they eat", "they", "present"],
      ["eu comerei", "EH-oo koh-meh-RAY", "I will eat", "I", "future"],
      ["você comerá", "voh-SEH koh-meh-RAH", "you will eat", "you", "future"],
      ["ele comerá", "EH-lee koh-meh-RAH", "he will eat", "he", "future"],
      ["nós comeremos", "nohs koh-meh-REH-moos", "we will eat", "we", "future"],
      ["eles comerão", "EH-lees koh-meh-ROWÑ", "they will eat", "they", "future"],
    ]),
    C("ir", "EER", "go", [
      ["eu fui", "EH-oo FOOY", "I went", "I", "past"],
      ["você foi", "voh-SEH FOY", "you went", "you", "past"],
      ["ele foi", "EH-lee FOY", "he went", "he", "past"],
      ["nós fomos", "nohs FOH-moos", "we went", "we", "past"],
      ["eles foram", "EH-lees FOH-rowñ", "they went", "they", "past"],
      ["eu vou", "EH-oo VOH", "I go", "I", "present"],
      ["você vai", "voh-SEH VYE", "you go", "you", "present"],
      ["ele vai", "EH-lee VYE", "he goes", "he", "present"],
      ["nós vamos", "nohs VAH-moos", "we go", "we", "present"],
      ["eles vão", "EH-lees VOWÑ", "they go", "they", "present"],
      ["eu irei", "EH-oo ee-RAY", "I will go", "I", "future"],
      ["você irá", "voh-SEH ee-RAH", "you will go", "you", "future"],
      ["ele irá", "EH-lee ee-RAH", "he will go", "he", "future"],
      ["nós iremos", "nohs ee-REH-moos", "we will go", "we", "future"],
      ["eles irão", "EH-lees ee-ROWÑ", "they will go", "they", "future"],
    ]),
    C("fazer", "fah-ZEHR", "do / make", [
      ["eu fiz", "EH-oo FEES", "I did", "I", "past"],
      ["você fez", "voh-SEH FEHS", "you did", "you", "past"],
      ["ele fez", "EH-lee FEHS", "he did", "he", "past"],
      ["nós fizemos", "nohs fee-ZEH-moos", "we did", "we", "past"],
      ["eles fizeram", "EH-lees fee-ZEH-rowñ", "they did", "they", "past"],
      ["eu faço", "EH-oo FAH-soo", "I do", "I", "present"],
      ["você faz", "voh-SEH FAHS", "you do", "you", "present"],
      ["ele faz", "EH-lee FAHS", "he does", "he", "present"],
      ["nós fazemos", "nohs fah-ZEH-moos", "we do", "we", "present"],
      ["eles fazem", "EH-lees FAH-zeñ", "they do", "they", "present"],
      ["eu farei", "EH-oo fah-RAY", "I will do", "I", "future"],
      ["você fará", "voh-SEH fah-RAH", "you will do", "you", "future"],
      ["ele fará", "EH-lee fah-RAH", "he will do", "he", "future"],
      ["nós faremos", "nohs fah-REH-moos", "we will do", "we", "future"],
      ["eles farão", "EH-lees fah-ROWÑ", "they will do", "they", "future"],
    ]),
    C("querer", "keh-REHR", "want", [
      ["eu quis", "EH-oo KEES", "I wanted", "I", "past"],
      ["você quis", "voh-SEH KEES", "you wanted", "you", "past"],
      ["ele quis", "EH-lee KEES", "he wanted", "he", "past"],
      ["nós quisemos", "nohs kee-ZEH-moos", "we wanted", "we", "past"],
      ["eles quiseram", "EH-lees kee-ZEH-rowñ", "they wanted", "they", "past"],
      ["eu quero", "EH-oo KEH-roo", "I want", "I", "present"],
      ["você quer", "voh-SEH KEHR", "you want", "you", "present"],
      ["ele quer", "EH-lee KEHR", "he wants", "he", "present"],
      ["nós queremos", "nohs keh-REH-moos", "we want", "we", "present"],
      ["eles querem", "EH-lees KEH-reñ", "they want", "they", "present"],
      ["eu quererei", "EH-oo keh-reh-RAY", "I will want", "I", "future"],
      ["você quererá", "voh-SEH keh-reh-RAH", "you will want", "you", "future"],
      ["ele quererá", "EH-lee keh-reh-RAH", "he will want", "he", "future"],
      ["nós quereremos", "nohs keh-reh-REH-moos", "we will want", "we", "future"],
      ["eles quererão", "EH-lees keh-reh-ROWÑ", "they will want", "they", "future"],
    ]),
    C("poder", "poh-DEHR", "be able to", [
      ["eu pude", "EH-oo POO-jee", "I could", "I", "past"],
      ["você pôde", "voh-SEH POH-jee", "you could", "you", "past"],
      ["ele pôde", "EH-lee POH-jee", "he could", "he", "past"],
      ["nós pudemos", "nohs poo-DEH-moos", "we could", "we", "past"],
      ["eles puderam", "EH-lees poo-DEH-rowñ", "they could", "they", "past"],
      ["eu posso", "EH-oo POH-soo", "I can", "I", "present"],
      ["você pode", "voh-SEH POH-jee", "you can", "you", "present"],
      ["ele pode", "EH-lee POH-jee", "he can", "he", "present"],
      ["nós podemos", "nohs poh-DEH-moos", "we can", "we", "present"],
      ["eles podem", "EH-lees POH-deñ", "they can", "they", "present"],
      ["eu poderei", "EH-oo poh-deh-RAY", "I will be able to", "I", "future"],
      ["você poderá", "voh-SEH poh-deh-RAH", "you will be able to", "you", "future"],
      ["ele poderá", "EH-lee poh-deh-RAH", "he will be able to", "he", "future"],
      ["nós poderemos", "nohs poh-deh-REH-moos", "we will be able to", "we", "future"],
      ["eles poderão", "EH-lees poh-deh-ROWÑ", "they will be able to", "they", "future"],
    ]),
    C("morar", "moh-RAR", "live", [
      ["eu morei", "EH-oo moh-RAY", "I lived", "I", "past"],
      ["você morou", "voh-SEH moh-ROH", "you lived", "you", "past"],
      ["ele morou", "EH-lee moh-ROH", "he lived", "he", "past"],
      ["nós moramos", "nohs moh-RAH-moos", "we lived", "we", "past"],
      ["eles moraram", "EH-lees moh-RAH-rowñ", "they lived", "they", "past"],
      ["eu moro", "EH-oo MOH-roo", "I live", "I", "present"],
      ["você mora", "voh-SEH MOH-rah", "you live", "you", "present"],
      ["ele mora", "EH-lee MOH-rah", "he lives", "he", "present"],
      ["nós moramos", "nohs moh-RAH-moos", "we live", "we", "present"],
      ["eles moram", "EH-lees MOH-rowñ", "they live", "they", "present"],
      ["eu morarei", "EH-oo moh-rah-RAY", "I will live", "I", "future"],
      ["você morará", "voh-SEH moh-rah-RAH", "you will live", "you", "future"],
      ["ele morará", "EH-lee moh-rah-RAH", "he will live", "he", "future"],
      ["nós moraremos", "nohs moh-rah-REH-moos", "we will live", "we", "future"],
      ["eles morarão", "EH-lees moh-rah-ROWÑ", "they will live", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Prudence",
      l1: "Mais vale um pássaro na mão", l2: "do que dois voando.",
      tr1: "myes VAH-lee ooñ PAH-sah-roo nah MOWÑ", tr2: "doo kee doys voh-AHN-doo",
      en: "A bird in the hand is worth two in flight." },
    { n: 2, chapterEn: "Patience",
      l1: "Devagar", l2: "se vai ao longe.",
      tr1: "deh-vah-GAR", tr2: "see vye ow LOHN-zhee",
      en: "Slowly one goes far." },
    { n: 3, chapterEn: "Company",
      l1: "Diga-me com quem andas", l2: "e eu te direi quem és.",
      tr1: "JEE-gah-mee kohñ keñ AHN-dahs", tr2: "ee EH-oo chee jee-RAY keñ EHS",
      en: "Tell me who you walk with and I'll tell you who you are." },
    { n: 4, chapterEn: "Effort",
      l1: "Água mole em pedra dura", l2: "tanto bate até que fura.",
      tr1: "AH-gwah MOH-lee eñ PEH-drah DOO-rah", tr2: "TAHN-too BAH-chee ah-TEH kee FOO-rah",
      en: "Soft water on hard stone strikes until it bores through." },
    { n: 5, chapterEn: "Timing",
      l1: "Deus ajuda", l2: "quem cedo madruga.",
      tr1: "DEH-oos ah-ZHOO-dah", tr2: "keñ SEH-doo mah-DROO-gah",
      en: "God helps those who rise early." },
    { n: 6, chapterEn: "Appearances",
      l1: "Nem tudo que reluz", l2: "é ouro.",
      tr1: "neñ TOO-doo kee heh-LOOS", tr2: "eh OH-roo",
      en: "Not all that glitters is gold." },
    { n: 7, chapterEn: "Caution",
      l1: "Gato escaldado", l2: "tem medo de água fria.",
      tr1: "GAH-too es-kahw-DAH-doo", tr2: "teñ MEH-doo jee AH-gwah FREE-ah",
      en: "A scalded cat is afraid of cold water." },
    { n: 8, chapterEn: "Adaptation",
      l1: "Em Roma,", l2: "faça como os romanos.",
      tr1: "eñ HOH-mah", tr2: "FAH-sah KOH-moo oos hoh-MAH-noos",
      en: "In Rome, do as the Romans do." },
    { n: 9, chapterEn: "Hope",
      l1: "Depois da tempestade,", l2: "vem a bonança.",
      tr1: "deh-POYS dah teñ-pes-TAH-jee", tr2: "veñ ah boh-NAHN-sah",
      en: "After the storm comes the calm." },
    { n: 10, chapterEn: "Practice",
      l1: "A prática", l2: "leva à perfeição.",
      tr1: "ah PRAH-chee-kah", tr2: "LEH-vah ah per-fay-SOWÑ",
      en: "Practice leads to perfection." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("portuguese", {
    icons: {
      alphabet: "Alfabeto", greetings: "Saudações", numbers: "Números", colors: "Cores",
      family: "Família", people: "Pessoas", pronouns: "Pronomes", questions: "Perguntas",
      grammar: "Ligações", adjectives: "Adjetivos", adverbs: "Advérbios", verbs: "Verbos",
      food: "Comida", body: "Corpo", health: "Saúde", clothing: "Roupa", home: "Casa",
      animals: "Animais", nature: "Natureza", places: "Lugares", travel: "Viagens",
      time: "Tempo", work: "Trabalho", school: "Escola", tech: "Tecnologia",
      sentences: "Frases",
    },
    ui: { account: "Conta", progress: "Progresso", search: "Buscar" },
    alphabet: ALPHABET,
    alphabetTitle: "Alphabet & sounds",
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "Revisão", vocab: "Palavras", sentence: "Frases", conjugation: "Verbos",
      listening: "Escuta", mixed: "Mistura", reading: "Provérbios",
    },
    reading: {
      id: "proverbios", title: "Proverbs", native: "Provérbios",
      desc: "Classic Brazilian sayings, line by line",
      blurb: "Provérbios — sayings heard across Brazil and Portugal alike.",
      unit: "sayings", numLabel: "Provérbio",
      lineQuestion: "Which line completes this proverb?",
      items: PROVERBS,
    },
  });
})();
