/* ============================================================================
 * Spanish course — data only.
 *
 * `ta` is the Spanish, `tr` a plain-English respelling (stressed syllable in
 * CAPS), `en` the meaning. Nouns carry their article so the gender is learned
 * with the word. Latin-American and Peninsular usage are both common; where
 * they differ the widely-understood form is given.
 * ==========================================================================*/
(function () {
  "use strict";
  const { V, S, C, A } = window.KILI;

  /* ------------------------------ Alphabet ------------------------------- */
  const LETTERS = A([
    ["A a", "ah"], ["B b", "BEH"], ["C c", "SEH"], ["D d", "DEH"], ["E e", "EH"],
    ["F f", "EH-feh"], ["G g", "HEH"], ["H h", "AH-cheh"], ["I i", "EE"],
    ["J j", "HOH-tah"], ["K k", "kah"], ["L l", "EH-leh"], ["M m", "EH-meh"],
    ["N n", "EH-neh"], ["Ñ ñ", "EH-nyeh"], ["O o", "OH"], ["P p", "PEH"],
    ["Q q", "KOO"], ["R r", "EH-rreh"], ["S s", "EH-seh"], ["T t", "TEH"],
    ["U u", "OO"], ["V v", "OO-beh"], ["W w", "OO-beh DOH-bleh"],
    ["X x", "EH-kees"], ["Y y", "YEH"], ["Z z", "SEH-tah"],
  ]);
  const SOUNDS = A([
    ["ch", "cheh", "as in 'church'"], ["ll", "EH-yeh", "like English 'y'"],
    ["rr", "EH-rreh", "a rolled r"], ["qu", "koo", "always 'k' before e/i"],
    ["gu", "goo", "hard g before e/i"], ["ce/ci", "seh/see", "soft c — 's'"],
    ["ge/gi", "heh/hee", "g sounds like 'h'"], ["h", "AH-cheh", "always silent"],
    ["ñ", "EH-nyeh", "'ny' as in canyon"], ["j", "HOH-tah", "a throaty 'h'"],
  ]);
  const ALPHABET = { vowels: LETTERS, consonants: SOUNDS };

  /* ------------------------------ Vocabulary ----------------------------- */
  const VOCAB = [].concat(
    V("greetings", [
      ["hola", "OH-la", "hello"],
      ["adiós", "ah-DYOHS", "goodbye"],
      ["buenos días", "BWEH-nohs DEE-ahs", "good morning"],
      ["buenas tardes", "BWEH-nahs TAR-dehs", "good afternoon"],
      ["buenas noches", "BWEH-nahs NOH-chehs", "good evening / good night"],
      ["gracias", "GRAH-syahs", "thank you"],
      ["muchas gracias", "MOO-chahs GRAH-syahs", "thank you very much"],
      ["de nada", "deh NAH-dah", "you're welcome"],
      ["por favor", "por fah-VOR", "please"],
      ["sí", "SEE", "yes"],
      ["no", "NOH", "no"],
      ["perdón", "per-DOHN", "sorry / excuse me"],
      ["lo siento", "loh SYEN-toh", "I'm sorry"],
      ["con permiso", "kohn per-MEE-soh", "excuse me (passing)"],
      ["¿cómo estás?", "KOH-moh ehs-TAHS", "how are you?"],
      ["muy bien", "mwee BYEN", "very well"],
      ["más o menos", "mahs oh MEH-nohs", "so-so"],
      ["mucho gusto", "MOO-choh GOOS-toh", "pleased to meet you"],
      ["bienvenido", "byen-veh-NEE-doh", "welcome"],
      ["hasta luego", "AHS-tah LWEH-goh", "see you later"],
      ["hasta mañana", "AHS-tah mah-NYAH-nah", "see you tomorrow"],
      ["buen provecho", "bwen proh-VEH-choh", "enjoy your meal"],
      ["salud", "sah-LOOD", "cheers / bless you"],
      ["felicidades", "feh-lee-see-DAH-dehs", "congratulations"],
      ["¿qué tal?", "keh TAHL", "how's it going?"],
      ["claro", "KLAH-roh", "of course"],
      ["vale", "BAH-leh", "okay (Spain)"],
    ]),
    V("numbers", [
      ["cero", "SEH-roh", "zero"], ["uno", "OO-noh", "one"], ["dos", "DOHS", "two"],
      ["tres", "TREHS", "three"], ["cuatro", "KWAH-troh", "four"],
      ["cinco", "SEEN-koh", "five"], ["seis", "SAYS", "six"],
      ["siete", "SYEH-teh", "seven"], ["ocho", "OH-choh", "eight"],
      ["nueve", "NWEH-veh", "nine"], ["diez", "DYEHS", "ten"],
      ["once", "OHN-seh", "eleven"], ["doce", "DOH-seh", "twelve"],
      ["trece", "TREH-seh", "thirteen"], ["catorce", "kah-TOR-seh", "fourteen"],
      ["quince", "KEEN-seh", "fifteen"], ["dieciséis", "dyeh-see-SAYS", "sixteen"],
      ["veinte", "BAYN-teh", "twenty"], ["treinta", "TRAYN-tah", "thirty"],
      ["cuarenta", "kwah-REN-tah", "forty"], ["cincuenta", "seen-KWEN-tah", "fifty"],
      ["cien", "SYEN", "one hundred"], ["mil", "MEEL", "one thousand"],
      ["primero", "pree-MEH-roh", "first"], ["segundo", "seh-GOON-doh", "second"],
      ["último", "OOL-tee-moh", "last"], ["la mitad", "lah mee-TAHD", "half"],
      ["el número", "el NOO-meh-roh", "number"],
    ]),
    V("colors", [
      ["rojo", "ROH-hoh", "red"], ["azul", "ah-SOOL", "blue"],
      ["verde", "BER-deh", "green"], ["amarillo", "ah-mah-REE-yoh", "yellow"],
      ["negro", "NEH-groh", "black"], ["blanco", "BLAHN-koh", "white"],
      ["gris", "GREES", "grey"], ["marrón", "mah-RROHN", "brown"],
      ["naranja", "nah-RAHN-hah", "orange"], ["rosa", "ROH-sah", "pink"],
      ["morado", "moh-RAH-doh", "purple"], ["dorado", "doh-RAH-doh", "golden"],
      ["plateado", "plah-teh-AH-doh", "silver"], ["claro", "KLAH-roh", "light (colour)"],
      ["oscuro", "ohs-KOO-roh", "dark"], ["el color", "el koh-LOR", "colour"],
      ["colorido", "koh-loh-REE-doh", "colourful"], ["celeste", "seh-LEHS-teh", "sky blue"],
      ["beige", "BEH-ees", "beige"], ["turquesa", "toor-KEH-sah", "turquoise"],
      ["brillante", "bree-YAHN-teh", "bright / shiny"],
      ["pálido", "PAH-lee-doh", "pale"],
    ]),
    V("family", [
      ["la familia", "lah fah-MEE-lyah", "family"],
      ["la madre", "lah MAH-dreh", "mother"], ["el padre", "el PAH-dreh", "father"],
      ["mamá", "mah-MAH", "mum"], ["papá", "pah-PAH", "dad"],
      ["los padres", "lohs PAH-drehs", "parents"],
      ["el hijo", "el EE-hoh", "son"], ["la hija", "lah EE-hah", "daughter"],
      ["el hermano", "el er-MAH-noh", "brother"], ["la hermana", "lah er-MAH-nah", "sister"],
      ["el abuelo", "el ah-BWEH-loh", "grandfather"],
      ["la abuela", "lah ah-BWEH-lah", "grandmother"],
      ["el nieto", "el NYEH-toh", "grandson"], ["el tío", "el TEE-oh", "uncle"],
      ["la tía", "lah TEE-ah", "aunt"], ["el primo", "el PREE-moh", "cousin (m)"],
      ["el sobrino", "el soh-BREE-noh", "nephew"],
      ["el esposo", "el ehs-POH-soh", "husband"], ["la esposa", "lah ehs-POH-sah", "wife"],
      ["el marido", "el mah-REE-doh", "husband"],
      ["el bebé", "el beh-BEH", "baby"], ["el niño", "el NEE-nyoh", "child (boy)"],
      ["la niña", "lah NEE-nyah", "child (girl)"],
      ["el pariente", "el pah-RYEN-teh", "relative"],
      ["la boda", "lah BOH-dah", "wedding"],
      ["el suegro", "el SWEH-groh", "father-in-law"],
    ]),
    V("people", [
      ["la persona", "lah per-SOH-nah", "person"], ["la gente", "lah HEN-teh", "people"],
      ["el hombre", "el OHM-breh", "man"], ["la mujer", "lah moo-HER", "woman"],
      ["el chico", "el CHEE-koh", "boy"], ["la chica", "lah CHEE-kah", "girl"],
      ["el amigo", "el ah-MEE-goh", "friend (m)"], ["la amiga", "lah ah-MEE-gah", "friend (f)"],
      ["el vecino", "el beh-SEE-noh", "neighbour"],
      ["el señor", "el seh-NYOR", "sir / Mr"], ["la señora", "lah seh-NYOH-rah", "madam / Mrs"],
      ["el joven", "el HOH-ben", "young person"], ["el adulto", "el ah-DOOL-toh", "adult"],
      ["el anciano", "el ahn-SYAH-noh", "elderly person"],
      ["el invitado", "el een-bee-TAH-doh", "guest"],
      ["el extranjero", "el ehks-trahn-HEH-roh", "foreigner"],
      ["el novio", "el NOH-byoh", "boyfriend"], ["la novia", "lah NOH-byah", "girlfriend"],
      ["el equipo", "el eh-KEE-poh", "team"],
      ["el grupo", "el GROO-poh", "group"],
      ["el nombre", "el NOHM-breh", "name"],
      ["el apellido", "el ah-peh-YEE-doh", "surname"],
      ["el compañero", "el kohm-pah-NYEH-roh", "companion / classmate"],
    ]),
    V("pronouns", [
      ["yo", "YOH", "I"], ["tú", "TOO", "you (informal)"], ["usted", "oos-TED", "you (formal)"],
      ["él", "EL", "he"], ["ella", "EH-yah", "she"], ["nosotros", "noh-SOH-trohs", "we"],
      ["vosotros", "boh-SOH-trohs", "you all (Spain)"], ["ustedes", "oos-TEH-dehs", "you all"],
      ["ellos", "EH-yohs", "they (m)"], ["ellas", "EH-yahs", "they (f)"],
      ["me", "MEH", "me / myself"], ["te", "TEH", "you (object)"],
      ["lo", "LOH", "him / it"], ["la", "LAH", "her / it"], ["nos", "NOHS", "us"],
      ["mi", "MEE", "my"], ["tu", "TOO", "your"], ["su", "SOO", "his / her / their"],
      ["nuestro", "NWEHS-troh", "our"], ["mío", "MEE-oh", "mine"],
      ["este", "EHS-teh", "this"], ["ese", "EH-seh", "that"],
      ["aquel", "ah-KEL", "that (over there)"],
      ["alguien", "AHL-gyen", "someone"], ["nadie", "NAH-dyeh", "nobody"],
      ["todos", "TOH-dohs", "everyone"], ["se", "SEH", "oneself"],
    ]),
    V("questions", [
      ["¿qué?", "KEH", "what?"], ["¿quién?", "KYEN", "who?"], ["¿dónde?", "DOHN-deh", "where?"],
      ["¿cuándo?", "KWAHN-doh", "when?"], ["¿por qué?", "por KEH", "why?"],
      ["¿cómo?", "KOH-moh", "how?"], ["¿cuál?", "KWAHL", "which?"],
      ["¿cuánto?", "KWAHN-toh", "how much?"], ["¿cuántos?", "KWAHN-tohs", "how many?"],
      ["¿a dónde?", "ah DOHN-deh", "where to?"], ["¿de dónde?", "deh DOHN-deh", "where from?"],
      ["¿para qué?", "pah-rah KEH", "what for?"],
      ["¿verdad?", "ber-DAHD", "right? / isn't it?"],
      ["¿de quién?", "deh KYEN", "whose?"],
      ["la pregunta", "lah preh-GOON-tah", "question"],
      ["la respuesta", "lah rehs-PWEHS-tah", "answer"],
      ["preguntar", "preh-goon-TAR", "to ask"],
      ["responder", "rehs-pohn-DER", "to answer"],
      ["¿cuánto cuesta?", "KWAHN-toh KWEHS-tah", "how much does it cost?"],
      ["¿qué hora es?", "keh OH-rah ehs", "what time is it?"],
      ["¿qué pasa?", "keh PAH-sah", "what's happening?"],
    ]),
    V("grammar", [
      ["y", "EE", "and"], ["o", "OH", "or"], ["pero", "PEH-roh", "but"],
      ["porque", "por-KEH", "because"], ["si", "SEE", "if"], ["que", "KEH", "that (conj.)"],
      ["de", "DEH", "of / from"], ["a", "AH", "to"], ["en", "EN", "in / on"],
      ["con", "KOHN", "with"], ["sin", "SEEN", "without"], ["para", "PAH-rah", "for"],
      ["por", "POR", "by / through"], ["sobre", "SOH-breh", "on / about"],
      ["entre", "EN-treh", "between"], ["desde", "DEHS-deh", "since / from"],
      ["hasta", "AHS-tah", "until"], ["el", "EL", "the (m)"], ["la", "LAH", "the (f)"],
      ["un", "OON", "a (m)"], ["una", "OO-nah", "a (f)"],
      ["también", "tahm-BYEN", "also"], ["tampoco", "tahm-POH-koh", "neither"],
      ["aunque", "OWN-keh", "although"], ["entonces", "en-TOHN-sehs", "then / so"],
      ["además", "ah-deh-MAHS", "besides"], ["mientras", "MYEN-trahs", "while"],
    ]),
    V("adjectives", [
      ["grande", "GRAHN-deh", "big"], ["pequeño", "peh-KEH-nyoh", "small"],
      ["bueno", "BWEH-noh", "good"], ["malo", "MAH-loh", "bad"],
      ["nuevo", "NWEH-boh", "new"], ["viejo", "BYEH-hoh", "old"],
      ["joven", "HOH-ben", "young"], ["largo", "LAR-goh", "long"],
      ["corto", "KOR-toh", "short"], ["alto", "AHL-toh", "tall / high"],
      ["bajo", "BAH-hoh", "short / low"], ["caliente", "kah-LYEN-teh", "hot"],
      ["frío", "FREE-oh", "cold"], ["fácil", "FAH-seel", "easy"],
      ["difícil", "dee-FEE-seel", "difficult"], ["bonito", "boh-NEE-toh", "pretty"],
      ["feo", "FEH-oh", "ugly"], ["fuerte", "FWER-teh", "strong"],
      ["débil", "DEH-beel", "weak"], ["rápido", "RAH-pee-doh", "fast"],
      ["lento", "LEN-toh", "slow"], ["rico", "RREE-koh", "rich / tasty"],
      ["pobre", "POH-breh", "poor"], ["feliz", "feh-LEES", "happy"],
      ["triste", "TREES-teh", "sad"], ["cansado", "kahn-SAH-doh", "tired"],
      ["limpio", "LEEM-pyoh", "clean"], ["sucio", "SOO-syoh", "dirty"],
      ["lleno", "YEH-noh", "full"], ["vacío", "bah-SEE-oh", "empty"],
      ["caro", "KAH-roh", "expensive"], ["barato", "bah-RAH-toh", "cheap"],
    ]),
    V("adverbs", [
      ["muy", "MWEE", "very"], ["mucho", "MOO-choh", "a lot"], ["poco", "POH-koh", "a little"],
      ["bien", "BYEN", "well"], ["mal", "MAHL", "badly"], ["siempre", "SYEM-preh", "always"],
      ["nunca", "NOON-kah", "never"], ["a veces", "ah BEH-sehs", "sometimes"],
      ["ahora", "ah-OH-rah", "now"], ["hoy", "OY", "today"], ["ayer", "ah-YER", "yesterday"],
      ["mañana", "mah-NYAH-nah", "tomorrow"], ["temprano", "tem-PRAH-noh", "early"],
      ["tarde", "TAR-deh", "late"], ["aquí", "ah-KEE", "here"], ["allí", "ah-YEE", "there"],
      ["cerca", "SER-kah", "nearby"], ["lejos", "LEH-hohs", "far"],
      ["juntos", "HOON-tohs", "together"], ["solo", "SOH-loh", "only / alone"],
      ["quizás", "kee-SAHS", "maybe"], ["ya", "YAH", "already"],
      ["todavía", "toh-dah-BEE-ah", "still / yet"], ["otra vez", "OH-trah BEHS", "again"],
      ["despacio", "dehs-PAH-syoh", "slowly"], ["deprisa", "deh-PREE-sah", "quickly"],
      ["casi", "KAH-see", "almost"], ["demasiado", "deh-mah-SYAH-doh", "too much"],
    ]),
    V("verbs", [
      ["ser", "SER", "to be (permanent)"], ["estar", "ehs-TAR", "to be (state)"],
      ["tener", "teh-NER", "to have"], ["hacer", "ah-SER", "to do / make"],
      ["ir", "EER", "to go"], ["venir", "beh-NEER", "to come"],
      ["poder", "poh-DER", "to be able to"], ["querer", "keh-RER", "to want / love"],
      ["saber", "sah-BER", "to know (facts)"], ["conocer", "koh-noh-SER", "to know (people)"],
      ["decir", "deh-SEER", "to say"], ["hablar", "ah-BLAR", "to speak"],
      ["comer", "koh-MER", "to eat"], ["beber", "beh-BER", "to drink"],
      ["vivir", "bee-BEER", "to live"], ["ver", "BER", "to see"],
      ["mirar", "mee-RAR", "to watch"], ["escuchar", "ehs-koo-CHAR", "to listen"],
      ["leer", "leh-ER", "to read"], ["escribir", "ehs-kree-BEER", "to write"],
      ["trabajar", "trah-bah-HAR", "to work"], ["estudiar", "ehs-too-DYAR", "to study"],
      ["dormir", "dor-MEER", "to sleep"], ["comprar", "kohm-PRAR", "to buy"],
      ["vender", "ben-DER", "to sell"], ["abrir", "ah-BREER", "to open"],
      ["cerrar", "seh-RRAR", "to close"], ["empezar", "em-peh-SAR", "to begin"],
      ["terminar", "ter-mee-NAR", "to finish"], ["ayudar", "ah-yoo-DAR", "to help"],
      ["necesitar", "neh-seh-see-TAR", "to need"], ["pensar", "pen-SAR", "to think"],
      ["caminar", "kah-mee-NAR", "to walk"], ["correr", "koh-RRER", "to run"],
      ["esperar", "ehs-peh-RAR", "to wait / hope"], ["dar", "DAR", "to give"],
      ["llegar", "yeh-GAR", "to arrive"], ["salir", "sah-LEER", "to leave / go out"],
    ]),
    V("food", [
      ["la comida", "lah koh-MEE-dah", "food / meal"],
      ["el agua", "el AH-gwah", "water"], ["el pan", "el PAHN", "bread"],
      ["el arroz", "el ah-RROHS", "rice"], ["la carne", "lah KAR-neh", "meat"],
      ["el pollo", "el POH-yoh", "chicken"], ["el pescado", "el pehs-KAH-doh", "fish (food)"],
      ["el huevo", "el WEH-boh", "egg"], ["la leche", "lah LEH-cheh", "milk"],
      ["el queso", "el KEH-soh", "cheese"], ["la fruta", "lah FROO-tah", "fruit"],
      ["la manzana", "lah mahn-SAH-nah", "apple"], ["el plátano", "el PLAH-tah-noh", "banana"],
      ["la naranja", "lah nah-RAHN-hah", "orange (fruit)"],
      ["la verdura", "lah ber-DOO-rah", "vegetable"],
      ["la papa", "lah PAH-pah", "potato"], ["el tomate", "el toh-MAH-teh", "tomato"],
      ["la cebolla", "lah seh-BOH-yah", "onion"], ["el ajo", "el AH-hoh", "garlic"],
      ["la sal", "lah SAHL", "salt"], ["el azúcar", "el ah-SOO-kar", "sugar"],
      ["el aceite", "el ah-SAY-teh", "oil"], ["el café", "el kah-FEH", "coffee"],
      ["el té", "el TEH", "tea"], ["el vino", "el BEE-noh", "wine"],
      ["la cerveza", "lah ser-BEH-sah", "beer"], ["el jugo", "el HOO-goh", "juice"],
      ["la sopa", "lah SOH-pah", "soup"], ["la ensalada", "lah en-sah-LAH-dah", "salad"],
      ["el postre", "el POHS-treh", "dessert"], ["el desayuno", "el deh-sah-YOO-noh", "breakfast"],
      ["el almuerzo", "el ahl-MWER-soh", "lunch"], ["la cena", "lah SEH-nah", "dinner"],
      ["el restaurante", "el rehs-tow-RAHN-teh", "restaurant"],
      ["la cuenta", "lah KWEN-tah", "the bill"],
    ]),
    V("body", [
      ["el cuerpo", "el KWER-poh", "body"], ["la cabeza", "lah kah-BEH-sah", "head"],
      ["el pelo", "el PEH-loh", "hair"], ["la cara", "lah KAH-rah", "face"],
      ["el ojo", "el OH-hoh", "eye"], ["la oreja", "lah oh-REH-hah", "ear"],
      ["la nariz", "lah nah-REES", "nose"], ["la boca", "lah BOH-kah", "mouth"],
      ["el diente", "el DYEN-teh", "tooth"], ["la lengua", "lah LEN-gwah", "tongue"],
      ["el cuello", "el KWEH-yoh", "neck"], ["el hombro", "el OHM-broh", "shoulder"],
      ["el brazo", "el BRAH-soh", "arm"], ["la mano", "lah MAH-noh", "hand"],
      ["el dedo", "el DEH-doh", "finger"], ["la pierna", "lah PYER-nah", "leg"],
      ["el pie", "el PYEH", "foot"], ["la rodilla", "lah rroh-DEE-yah", "knee"],
      ["la espalda", "lah ehs-PAHL-dah", "back"], ["el pecho", "el PEH-choh", "chest"],
      ["el corazón", "el koh-rah-SOHN", "heart"], ["el estómago", "el ehs-TOH-mah-goh", "stomach"],
      ["la sangre", "lah SAHN-greh", "blood"], ["el hueso", "el WEH-soh", "bone"],
      ["la piel", "lah PYEL", "skin"],
    ]),
    V("health", [
      ["la salud", "lah sah-LOOD", "health"], ["el médico", "el MEH-dee-koh", "doctor"],
      ["el hospital", "el ohs-pee-TAHL", "hospital"], ["la farmacia", "lah far-MAH-syah", "pharmacy"],
      ["la medicina", "lah meh-dee-SEE-nah", "medicine"],
      ["enfermo", "en-FER-moh", "ill"], ["sano", "SAH-noh", "healthy"],
      ["el dolor", "el doh-LOR", "pain"], ["la fiebre", "lah FYEH-breh", "fever"],
      ["la tos", "lah TOHS", "cough"], ["el resfriado", "el rehs-FRYAH-doh", "a cold"],
      ["la herida", "lah eh-REE-dah", "wound"], ["la enfermera", "lah en-fer-MEH-rah", "nurse"],
      ["la cita", "lah SEE-tah", "appointment"],
      ["me duele", "meh DWEH-leh", "it hurts me"],
      ["la ambulancia", "lah ahm-boo-LAHN-syah", "ambulance"],
      ["la emergencia", "lah eh-mer-HEN-syah", "emergency"],
      ["descansar", "dehs-kahn-SAR", "to rest"],
      ["el ejercicio", "el eh-her-SEE-syoh", "exercise"],
      ["la dieta", "lah DYEH-tah", "diet"],
      ["la receta", "lah rreh-SEH-tah", "prescription"],
      ["cuidarse", "kwee-DAR-seh", "to take care of oneself"],
    ]),
    V("clothing", [
      ["la ropa", "lah RROH-pah", "clothes"], ["la camisa", "lah kah-MEE-sah", "shirt"],
      ["la camiseta", "lah kah-mee-SEH-tah", "t-shirt"],
      ["el pantalón", "el pahn-tah-LOHN", "trousers"],
      ["los vaqueros", "lohs bah-KEH-rohs", "jeans"],
      ["el vestido", "el behs-TEE-doh", "dress"], ["la falda", "lah FAHL-dah", "skirt"],
      ["el abrigo", "el ah-BREE-goh", "coat"], ["la chaqueta", "lah chah-KEH-tah", "jacket"],
      ["el suéter", "el SWEH-ter", "sweater"], ["los zapatos", "lohs sah-PAH-tohs", "shoes"],
      ["las botas", "lahs BOH-tahs", "boots"], ["los calcetines", "lohs kahl-seh-TEE-nehs", "socks"],
      ["el sombrero", "el sohm-BREH-roh", "hat"], ["la gorra", "lah GOH-rrah", "cap"],
      ["la bufanda", "lah boo-FAHN-dah", "scarf"], ["los guantes", "lohs GWAHN-tehs", "gloves"],
      ["el cinturón", "el seen-too-ROHN", "belt"], ["las gafas", "lahs GAH-fahs", "glasses"],
      ["el bolso", "el BOHL-soh", "handbag"], ["el traje", "el TRAH-heh", "suit"],
      ["la talla", "lah TAH-yah", "size"], ["llevar", "yeh-BAR", "to wear"],
      ["probarse", "proh-BAR-seh", "to try on"],
    ]),
    V("home", [
      ["la casa", "lah KAH-sah", "house"], ["el hogar", "el oh-GAR", "home"],
      ["el apartamento", "el ah-par-tah-MEN-toh", "apartment"],
      ["la habitación", "lah ah-bee-tah-SYOHN", "room"],
      ["la cocina", "lah koh-SEE-nah", "kitchen"], ["el baño", "el BAH-nyoh", "bathroom"],
      ["el dormitorio", "el dor-mee-TOH-ryoh", "bedroom"],
      ["la sala", "lah SAH-lah", "living room"], ["la puerta", "lah PWER-tah", "door"],
      ["la ventana", "lah ben-TAH-nah", "window"], ["la mesa", "lah MEH-sah", "table"],
      ["la silla", "lah SEE-yah", "chair"], ["la cama", "lah KAH-mah", "bed"],
      ["el sofá", "el soh-FAH", "sofa"], ["la lámpara", "lah LAHM-pah-rah", "lamp"],
      ["el espejo", "el ehs-PEH-hoh", "mirror"], ["la llave", "lah YAH-beh", "key"],
      ["el plato", "el PLAH-toh", "plate"], ["el vaso", "el BAH-soh", "glass (cup)"],
      ["la taza", "lah TAH-sah", "cup"], ["el cuchillo", "el koo-CHEE-yoh", "knife"],
      ["el tenedor", "el teh-neh-DOR", "fork"], ["la cuchara", "lah koo-CHAH-rah", "spoon"],
      ["el jardín", "el har-DEEN", "garden"], ["la escalera", "lah ehs-kah-LEH-rah", "stairs"],
      ["el techo", "el TEH-choh", "roof / ceiling"], ["la pared", "lah pah-RED", "wall"],
      ["el suelo", "el SWEH-loh", "floor"],
    ]),
    V("animals", [
      ["el animal", "el ah-nee-MAHL", "animal"], ["el perro", "el PEH-rroh", "dog"],
      ["el gato", "el GAH-toh", "cat"], ["el caballo", "el kah-BAH-yoh", "horse"],
      ["la vaca", "lah BAH-kah", "cow"], ["el cerdo", "el SER-doh", "pig"],
      ["la oveja", "lah oh-BEH-hah", "sheep"], ["la gallina", "lah gah-YEE-nah", "hen"],
      ["el pájaro", "el PAH-hah-roh", "bird"], ["el pez", "el PEHS", "fish (live)"],
      ["el ratón", "el rrah-TOHN", "mouse"], ["el conejo", "el koh-NEH-hoh", "rabbit"],
      ["el león", "el leh-OHN", "lion"], ["el tigre", "el TEE-greh", "tiger"],
      ["el elefante", "el eh-leh-FAHN-teh", "elephant"], ["el mono", "el MOH-noh", "monkey"],
      ["el oso", "el OH-soh", "bear"], ["el lobo", "el LOH-boh", "wolf"],
      ["la serpiente", "lah ser-PYEN-teh", "snake"], ["la araña", "lah ah-RAH-nyah", "spider"],
      ["la mariposa", "lah mah-ree-POH-sah", "butterfly"], ["la abeja", "lah ah-BEH-hah", "bee"],
      ["la hormiga", "lah or-MEE-gah", "ant"], ["la mosca", "lah MOHS-kah", "fly"],
      ["la tortuga", "lah tor-TOO-gah", "turtle"],
    ]),
    V("nature", [
      ["la naturaleza", "lah nah-too-rah-LEH-sah", "nature"],
      ["el sol", "el SOHL", "sun"], ["la luna", "lah LOO-nah", "moon"],
      ["la estrella", "lah ehs-TREH-yah", "star"], ["el cielo", "el SYEH-loh", "sky"],
      ["la nube", "lah NOO-beh", "cloud"], ["la lluvia", "lah YOO-byah", "rain"],
      ["la nieve", "lah NYEH-beh", "snow"], ["el viento", "el BYEN-toh", "wind"],
      ["el fuego", "el FWEH-goh", "fire"], ["la tierra", "lah TYEH-rrah", "earth / soil"],
      ["el mar", "el MAR", "sea"], ["el río", "el RREE-oh", "river"],
      ["el lago", "el LAH-goh", "lake"], ["la montaña", "lah mohn-TAH-nyah", "mountain"],
      ["el bosque", "el BOHS-keh", "forest"], ["el árbol", "el AR-bohl", "tree"],
      ["la flor", "lah FLOR", "flower"], ["la hoja", "lah OH-hah", "leaf"],
      ["la hierba", "lah YER-bah", "grass"], ["la playa", "lah PLAH-yah", "beach"],
      ["la isla", "lah EES-lah", "island"], ["el desierto", "el deh-SYER-toh", "desert"],
      ["la piedra", "lah PYEH-drah", "stone"], ["el tiempo", "el TYEM-poh", "weather"],
      ["la tormenta", "lah tor-MEN-tah", "storm"],
    ]),
    V("places", [
      ["el lugar", "el loo-GAR", "place"], ["la ciudad", "lah syoo-DAHD", "city"],
      ["el pueblo", "el PWEH-bloh", "town / village"], ["el país", "el pah-EES", "country"],
      ["la calle", "lah KAH-yeh", "street"], ["la plaza", "lah PLAH-sah", "square"],
      ["el mercado", "el mer-KAH-doh", "market"], ["la tienda", "lah TYEN-dah", "shop"],
      ["el banco", "el BAHN-koh", "bank"], ["la escuela", "lah ehs-KWEH-lah", "school"],
      ["la iglesia", "lah ee-GLEH-syah", "church"], ["el museo", "el moo-SEH-oh", "museum"],
      ["el parque", "el PAR-keh", "park"], ["el hotel", "el oh-TEL", "hotel"],
      ["el aeropuerto", "el ah-eh-roh-PWER-toh", "airport"],
      ["la estación", "lah ehs-tah-SYOHN", "station"],
      ["la biblioteca", "lah bee-blyoh-TEH-kah", "library"],
      ["la oficina", "lah oh-fee-SEE-nah", "office"], ["el cine", "el SEE-neh", "cinema"],
      ["el hospital", "el ohs-pee-TAHL", "hospital"], ["el barrio", "el BAH-rryoh", "neighbourhood"],
      ["el centro", "el SEN-troh", "centre / downtown"],
      ["el campo", "el KAHM-poh", "countryside"], ["la frontera", "lah frohn-TEH-rah", "border"],
    ]),
    V("travel", [
      ["el viaje", "el BYAH-heh", "journey"], ["viajar", "byah-HAR", "to travel"],
      ["el coche", "el KOH-cheh", "car"], ["el autobús", "el ow-toh-BOOS", "bus"],
      ["el tren", "el TREN", "train"], ["el avión", "el ah-BYOHN", "aeroplane"],
      ["la bicicleta", "lah bee-see-KLEH-tah", "bicycle"], ["el barco", "el BAR-koh", "boat"],
      ["el taxi", "el TAHK-see", "taxi"], ["el billete", "el bee-YEH-teh", "ticket"],
      ["el pasaporte", "el pah-sah-POR-teh", "passport"],
      ["la maleta", "lah mah-LEH-tah", "suitcase"], ["el equipaje", "el eh-kee-PAH-heh", "luggage"],
      ["el mapa", "el MAH-pah", "map"], ["el camino", "el kah-MEE-noh", "road / way"],
      ["la carretera", "lah kah-rreh-TEH-rah", "highway"],
      ["la salida", "lah sah-LEE-dah", "exit / departure"],
      ["la llegada", "lah yeh-GAH-dah", "arrival"],
      ["el retraso", "el rreh-TRAH-soh", "delay"],
      ["a la izquierda", "ah lah ees-KYER-dah", "to the left"],
      ["a la derecha", "ah lah deh-REH-chah", "to the right"],
      ["todo recto", "TOH-doh RREK-toh", "straight ahead"],
      ["cerca de", "SER-kah deh", "near to"], ["perderse", "per-DER-seh", "to get lost"],
      ["la aduana", "lah ah-DWAH-nah", "customs"],
    ]),
    V("time", [
      ["el tiempo", "el TYEM-poh", "time"], ["la hora", "lah OH-rah", "hour"],
      ["el minuto", "el mee-NOO-toh", "minute"], ["el segundo", "el seh-GOON-doh", "second"],
      ["el día", "el DEE-ah", "day"], ["la semana", "lah seh-MAH-nah", "week"],
      ["el mes", "el MEHS", "month"], ["el año", "el AH-nyoh", "year"],
      ["la mañana", "lah mah-NYAH-nah", "morning"], ["la tarde", "lah TAR-deh", "afternoon"],
      ["la noche", "lah NOH-cheh", "night"], ["el lunes", "el LOO-nehs", "Monday"],
      ["el martes", "el MAR-tehs", "Tuesday"], ["el miércoles", "el MYER-koh-lehs", "Wednesday"],
      ["el jueves", "el HWEH-behs", "Thursday"], ["el viernes", "el BYER-nehs", "Friday"],
      ["el sábado", "el SAH-bah-doh", "Saturday"], ["el domingo", "el doh-MEEN-goh", "Sunday"],
      ["enero", "eh-NEH-roh", "January"], ["febrero", "feh-BREH-roh", "February"],
      ["marzo", "MAR-soh", "March"], ["abril", "ah-BREEL", "April"],
      ["mayo", "MAH-yoh", "May"], ["junio", "HOO-nyoh", "June"],
      ["julio", "HOO-lyoh", "July"], ["agosto", "ah-GOHS-toh", "August"],
      ["el fin de semana", "el feen deh seh-MAH-nah", "weekend"],
      ["el reloj", "el rreh-LOH", "clock / watch"],
      ["el verano", "el beh-RAH-noh", "summer"], ["el invierno", "el een-BYER-noh", "winter"],
    ]),
    V("work", [
      ["el trabajo", "el trah-BAH-hoh", "work / job"],
      ["la empresa", "lah em-PREH-sah", "company"], ["el jefe", "el HEH-feh", "boss"],
      ["el empleado", "el em-pleh-AH-doh", "employee"],
      ["el sueldo", "el SWEL-doh", "salary"], ["el dinero", "el dee-NEH-roh", "money"],
      ["el euro", "el EH-oo-roh", "euro"], ["el precio", "el PREH-syoh", "price"],
      ["barato", "bah-RAH-toh", "cheap"], ["caro", "KAH-roh", "expensive"],
      ["pagar", "pah-GAR", "to pay"], ["comprar", "kohm-PRAR", "to buy"],
      ["vender", "ben-DER", "to sell"], ["la reunión", "lah rreh-oo-NYOHN", "meeting"],
      ["el proyecto", "el proh-YEK-toh", "project"], ["el cliente", "el KLYEN-teh", "client"],
      ["la factura", "lah fahk-TOO-rah", "invoice"], ["el contrato", "el kohn-TRAH-toh", "contract"],
      ["la tarjeta", "lah tar-HEH-tah", "card"], ["el efectivo", "el eh-fek-TEE-boh", "cash"],
      ["la profesión", "lah proh-feh-SYOHN", "profession"],
      ["el ingeniero", "el een-heh-NYEH-roh", "engineer"],
      ["el maestro", "el mah-EHS-troh", "teacher"],
      ["el abogado", "el ah-boh-GAH-doh", "lawyer"],
      ["la tienda", "lah TYEN-dah", "shop"], ["ganar", "gah-NAR", "to earn / win"],
    ]),
    V("school", [
      ["la escuela", "lah ehs-KWEH-lah", "school"],
      ["la universidad", "lah oo-nee-ber-see-DAHD", "university"],
      ["la clase", "lah KLAH-seh", "class"], ["el alumno", "el ah-LOOM-noh", "pupil"],
      ["el estudiante", "el ehs-too-DYAHN-teh", "student"],
      ["el profesor", "el proh-feh-SOR", "teacher"], ["el libro", "el LEE-broh", "book"],
      ["el cuaderno", "el kwah-DER-noh", "notebook"], ["el lápiz", "el LAH-pees", "pencil"],
      ["el bolígrafo", "el boh-LEE-grah-foh", "pen"], ["el papel", "el pah-PEL", "paper"],
      ["la palabra", "lah pah-LAH-brah", "word"], ["la frase", "lah FRAH-seh", "sentence"],
      ["la lección", "lah lek-SYOHN", "lesson"], ["el examen", "el ehk-SAH-men", "exam"],
      ["la tarea", "lah tah-REH-ah", "homework"], ["la nota", "lah NOH-tah", "grade / note"],
      ["aprender", "ah-pren-DER", "to learn"], ["enseñar", "en-seh-NYAR", "to teach"],
      ["entender", "en-ten-DER", "to understand"], ["explicar", "ehks-plee-KAR", "to explain"],
      ["la respuesta", "lah rrehs-PWEHS-tah", "answer"],
      ["el idioma", "el ee-DYOH-mah", "language"],
      ["la historia", "lah ees-TOH-ryah", "history / story"],
      ["las matemáticas", "lahs mah-teh-MAH-tee-kahs", "maths"],
      ["la ciencia", "lah SYEN-syah", "science"],
    ]),
    V("tech", [
      ["el ordenador", "el or-deh-nah-DOR", "computer (Spain)"],
      ["la computadora", "lah kohm-poo-tah-DOH-rah", "computer (LatAm)"],
      ["el teléfono", "el teh-LEH-foh-noh", "telephone"],
      ["el móvil", "el MOH-beel", "mobile phone"],
      ["la pantalla", "lah pahn-TAH-yah", "screen"],
      ["el teclado", "el teh-KLAH-doh", "keyboard"], ["el ratón", "el rrah-TOHN", "mouse"],
      ["internet", "een-ter-NET", "internet"], ["la red", "lah RRED", "network"],
      ["el correo", "el koh-RREH-oh", "email / post"],
      ["la contraseña", "lah kohn-trah-SEH-nyah", "password"],
      ["el archivo", "el ar-CHEE-boh", "file"], ["la carpeta", "lah kar-PEH-tah", "folder"],
      ["la aplicación", "lah ah-plee-kah-SYOHN", "app"],
      ["el programa", "el proh-GRAH-mah", "program"],
      ["descargar", "dehs-kar-GAR", "to download"], ["subir", "soo-BEER", "to upload"],
      ["guardar", "gwar-DAR", "to save"], ["borrar", "boh-RRAR", "to delete"],
      ["buscar", "boos-KAR", "to search"], ["encender", "en-sen-DER", "to switch on"],
      ["apagar", "ah-pah-GAR", "to switch off"], ["la cámara", "lah KAH-mah-rah", "camera"],
      ["la batería", "lah bah-teh-REE-ah", "battery"],
      ["el enlace", "el en-LAH-seh", "link"],
    ]),
    /* ---- a second pass over every topic: the words you reach for once the
       first few hundred are comfortable ---- */
    V("greetings", [
      ["encantado", "en-kahn-TAH-doh", "delighted (to meet you)"],
      ["igualmente", "ee-gwahl-MEN-teh", "likewise"],
      ["¿qué hay?", "keh EYE", "what's up?"],
      ["hasta pronto", "AHS-tah PROHN-toh", "see you soon"],
      ["nos vemos", "nohs BEH-mohs", "see you around"],
      ["cuídate", "KWEE-dah-teh", "take care"],
      ["buen viaje", "bwen BYAH-heh", "have a good trip"],
      ["que te mejores", "keh teh meh-HOH-rehs", "get well soon"],
      ["lo mismo digo", "loh MEES-moh DEE-goh", "same to you"],
      ["disculpe", "dees-KOOL-peh", "excuse me (formal)"],
      ["no importa", "noh eem-POR-tah", "it doesn't matter"],
      ["por supuesto", "por soo-PWEHS-toh", "of course"],
    ]),
    V("numbers", [
      ["diecisiete", "dyeh-see-SYEH-teh", "seventeen"],
      ["dieciocho", "dyeh-SYOH-choh", "eighteen"],
      ["diecinueve", "dyeh-see-NWEH-beh", "nineteen"],
      ["veintiuno", "bayn-tee-OO-noh", "twenty-one"],
      ["sesenta", "seh-SEN-tah", "sixty"], ["setenta", "seh-TEN-tah", "seventy"],
      ["ochenta", "oh-CHEN-tah", "eighty"], ["noventa", "noh-BEN-tah", "ninety"],
      ["doscientos", "dohs-SYEN-tohs", "two hundred"],
      ["un millón", "oon mee-YOHN", "a million"],
      ["tercero", "ter-SEH-roh", "third"], ["docena", "doh-SEH-nah", "dozen"],
      ["par", "PAR", "pair"], ["ambos", "AHM-bohs", "both"],
      ["contar", "kohn-TAR", "to count"],
    ]),
    V("colors", [
      ["violeta", "byoh-LEH-tah", "violet"], ["lila", "LEE-lah", "lilac"],
      ["crema", "KREH-mah", "cream"], ["ocre", "OH-kreh", "ochre"],
      ["esmeralda", "ehs-meh-RAHL-dah", "emerald green"],
      ["carmesí", "kar-meh-SEE", "crimson"],
      ["a rayas", "ah RAH-yahs", "striped"],
      ["a cuadros", "ah KWAH-drohs", "checked"],
      ["liso", "LEE-soh", "plain / smooth"],
      ["teñir", "teh-NYEER", "to dye"],
      ["desteñido", "dehs-teh-NYEE-doh", "faded"],
      ["el tono", "el TOH-noh", "shade / tone"],
    ]),
    V("family", [
      ["la suegra", "lah SWEH-grah", "mother-in-law"],
      ["el cuñado", "el koo-NYAH-doh", "brother-in-law"],
      ["el yerno", "el YER-noh", "son-in-law"],
      ["la nuera", "lah NWEH-rah", "daughter-in-law"],
      ["la nieta", "lah NYEH-tah", "granddaughter"],
      ["la sobrina", "lah soh-BREE-nah", "niece"],
      ["la prima", "lah PREE-mah", "cousin (f)"],
      ["el padrino", "el pah-DREE-noh", "godfather"],
      ["la madrina", "lah mah-DREE-nah", "godmother"],
      ["los gemelos", "lohs heh-MEH-lohs", "twins"],
      ["el antepasado", "el ahn-teh-pah-SAH-doh", "ancestor"],
      ["criar", "kree-AR", "to raise (children)"],
      ["heredar", "eh-reh-DAR", "to inherit"],
    ]),
    V("people", [
      ["el desconocido", "el dehs-koh-noh-SEE-doh", "stranger"],
      ["la multitud", "lah mool-tee-TOOD", "crowd"],
      ["el ciudadano", "el syoo-dah-DAH-noh", "citizen"],
      ["el líder", "el LEE-der", "leader"],
      ["el compañero de piso", "el kohm-pah-NYEH-roh deh PEE-soh", "flatmate"],
      ["la pareja", "lah pah-REH-hah", "couple / partner"],
      ["el conocido", "el koh-noh-SEE-doh", "acquaintance"],
      ["el testigo", "el tehs-TEE-goh", "witness"],
      ["el voluntario", "el boh-loon-TAH-ryoh", "volunteer"],
      ["la sociedad", "lah soh-syeh-DAHD", "society"],
      ["el público", "el POO-blee-koh", "audience / public"],
      ["el apodo", "el ah-POH-doh", "nickname"],
    ]),
    V("pronouns", [
      ["le", "LEH", "to him / to her"], ["les", "LEHS", "to them"],
      ["os", "OHS", "you all (object, Spain)"],
      ["conmigo", "kohn-MEE-goh", "with me"],
      ["contigo", "kohn-TEE-goh", "with you"],
      ["consigo", "kohn-SEE-goh", "with oneself"],
      ["tuyo", "TOO-yoh", "yours"], ["suyo", "SOO-yoh", "his / hers / theirs"],
      ["esto", "EHS-toh", "this thing"], ["eso", "EH-soh", "that thing"],
      ["aquello", "ah-KEH-yoh", "that thing over there"],
      ["cualquiera", "kwahl-KYEH-rah", "anyone / any"],
      ["cada uno", "KAH-dah OO-noh", "each one"],
      ["ninguno", "neen-GOO-noh", "none / neither"],
    ]),
    V("questions", [
      ["¿para quién?", "pah-rah KYEN", "for whom?"],
      ["¿con quién?", "kohn KYEN", "with whom?"],
      ["¿desde cuándo?", "DEHS-deh KWAHN-doh", "since when?"],
      ["¿hasta cuándo?", "AHS-tah KWAHN-doh", "until when?"],
      ["¿cuántas veces?", "KWAHN-tahs BEH-sehs", "how many times?"],
      ["¿de qué?", "deh KEH", "about what?"],
      ["¿puedes ayudarme?", "PWEH-dehs ah-yoo-DAR-meh", "can you help me?"],
      ["¿dónde está el baño?", "DOHN-deh ehs-TAH el BAH-nyoh", "where is the toilet?"],
      ["¿cómo se dice…?", "KOH-moh seh DEE-seh", "how do you say…?"],
      ["¿qué significa?", "keh seeg-nee-FEE-kah", "what does it mean?"],
      ["¿me entiendes?", "meh en-TYEN-dehs", "do you understand me?"],
      ["dudar", "doo-DAR", "to doubt"],
    ]),
    V("grammar", [
      ["ni", "NEE", "nor"], ["sino", "SEE-noh", "but rather"],
      ["mientras tanto", "MYEN-trahs TAHN-toh", "meanwhile"],
      ["sin embargo", "seen em-BAR-goh", "however"],
      ["por lo tanto", "por loh TAHN-toh", "therefore"],
      ["a pesar de", "ah peh-SAR deh", "in spite of"],
      ["en cuanto a", "en KWAHN-toh ah", "as for"],
      ["debajo de", "deh-BAH-hoh deh", "underneath"],
      ["encima de", "en-SEE-mah deh", "on top of"],
      ["delante de", "deh-LAHN-teh deh", "in front of"],
      ["detrás de", "deh-TRAHS deh", "behind"],
      ["alrededor de", "ahl-reh-deh-DOR deh", "around"],
      ["hacia", "AH-syah", "towards"], ["según", "seh-GOON", "according to"],
      ["unos", "OO-nohs", "some / a few"],
    ]),
    V("adjectives", [
      ["ancho", "AHN-choh", "wide"], ["estrecho", "ehs-TREH-choh", "narrow"],
      ["grueso", "GRWEH-soh", "thick"], ["delgado", "del-GAH-doh", "thin / slim"],
      ["pesado", "peh-SAH-doh", "heavy"], ["ligero", "lee-HEH-roh", "light (weight)"],
      ["duro", "DOO-roh", "hard"], ["blando", "BLAHN-doh", "soft"],
      ["profundo", "proh-FOON-doh", "deep"], ["seco", "SEH-koh", "dry"],
      ["mojado", "moh-HAH-doh", "wet"], ["dulce", "DOOL-seh", "sweet"],
      ["salado", "sah-LAH-doh", "salty"], ["amargo", "ah-MAR-goh", "bitter"],
      ["picante", "pee-KAHN-teh", "spicy"], ["tranquilo", "trahn-KEE-loh", "calm"],
      ["ruidoso", "rrwee-DOH-soh", "noisy"], ["peligroso", "peh-lee-GROH-soh", "dangerous"],
      ["seguro", "seh-GOO-roh", "safe / sure"], ["listo", "LEES-toh", "clever / ready"],
      ["amable", "ah-MAH-bleh", "kind"], ["enfadado", "en-fah-DAH-doh", "angry"],
    ]),
    V("adverbs", [
      ["apenas", "ah-PEH-nahs", "hardly"], ["bastante", "bahs-TAHN-teh", "quite / enough"],
      ["sobre todo", "SOH-breh TOH-doh", "above all"],
      ["al menos", "ahl MEH-nohs", "at least"],
      ["de repente", "deh rreh-PEN-teh", "suddenly"],
      ["por fin", "por FEEN", "finally"], ["en seguida", "en seh-GEE-dah", "right away"],
      ["a menudo", "ah meh-NOO-doh", "often"], ["rara vez", "RAH-rah BEHS", "rarely"],
      ["arriba", "ah-RREE-bah", "up / above"], ["abajo", "ah-BAH-hoh", "down / below"],
      ["adentro", "ah-DEN-troh", "inside"], ["afuera", "ah-FWEH-rah", "outside"],
      ["adelante", "ah-deh-LAHN-teh", "forward"], ["atrás", "ah-TRAHS", "backwards"],
      ["mejor", "meh-HOR", "better"], ["peor", "peh-OR", "worse"],
      ["cuidadosamente", "kwee-dah-doh-sah-MEN-teh", "carefully"],
    ]),
    V("verbs", [
      ["poner", "poh-NER", "to put"], ["sacar", "sah-KAR", "to take out"],
      ["traer", "trah-ER", "to bring"], ["llevar", "yeh-BAR", "to carry / wear"],
      ["encontrar", "en-kohn-TRAR", "to find"], ["perder", "per-DER", "to lose"],
      ["ganar", "gah-NAR", "to win / earn"], ["jugar", "hoo-GAR", "to play"],
      ["cantar", "kahn-TAR", "to sing"], ["bailar", "bye-LAR", "to dance"],
      ["cocinar", "koh-see-NAR", "to cook"], ["limpiar", "leem-PYAR", "to clean"],
      ["lavar", "lah-BAR", "to wash"], ["romper", "rrohm-PER", "to break"],
      ["arreglar", "ah-rreh-GLAR", "to fix"], ["cambiar", "kahm-BYAR", "to change"],
      ["recordar", "rreh-kor-DAR", "to remember"], ["olvidar", "ohl-bee-DAR", "to forget"],
      ["entender", "en-ten-DER", "to understand"], ["intentar", "een-ten-TAR", "to try"],
      ["seguir", "seh-GEER", "to follow / continue"], ["parar", "pah-RAR", "to stop"],
      ["descansar", "dehs-kahn-SAR", "to rest"],
      ["reír", "rreh-EER", "to laugh"], ["llorar", "yoh-RAR", "to cry"],
      ["nadar", "nah-DAR", "to swim"], ["conducir", "kohn-doo-SEER", "to drive"],
      ["subir", "soo-BEER", "to go up"], ["bajar", "bah-HAR", "to go down"],
    ]),
    V("food", [
      ["el desayunar", "el deh-sah-yoo-NAR", "to have breakfast"],
      ["la harina", "lah ah-REE-nah", "flour"], ["el huevo frito", "el WEH-boh FREE-toh", "fried egg"],
      ["la mantequilla", "lah mahn-teh-KEE-yah", "butter"],
      ["la mermelada", "lah mer-meh-LAH-dah", "jam"],
      ["el jamón", "el hah-MOHN", "ham"], ["la tortilla", "lah tor-TEE-yah", "omelette / tortilla"],
      ["el bocadillo", "el boh-kah-DEE-yoh", "sandwich"],
      ["la zanahoria", "lah sah-nah-OH-ryah", "carrot"],
      ["la lechuga", "lah leh-CHOO-gah", "lettuce"],
      ["el pimiento", "el pee-MYEN-toh", "pepper (vegetable)"],
      ["la uva", "lah OO-bah", "grape"], ["la fresa", "lah FREH-sah", "strawberry"],
      ["el limón", "el lee-MOHN", "lemon"], ["la sandía", "lah sahn-DEE-ah", "watermelon"],
      ["el helado", "el eh-LAH-doh", "ice cream"], ["el pastel", "el pahs-TEL", "cake"],
      ["la cuchara", "lah koo-CHAH-rah", "spoon"], ["la servilleta", "lah ser-bee-YEH-tah", "napkin"],
      ["la propina", "lah proh-PEE-nah", "tip"], ["el menú", "el meh-NOO", "menu"],
      ["la ración", "lah rrah-SYOHN", "portion"], ["probar", "proh-BAR", "to taste / try"],
    ]),
    V("body", [
      ["la muñeca", "lah moo-NYEH-kah", "wrist"], ["el codo", "el KOH-doh", "elbow"],
      ["el tobillo", "el toh-BEE-yoh", "ankle"], ["la cadera", "lah kah-DEH-rah", "hip"],
      ["la cintura", "lah seen-TOO-rah", "waist"], ["la uña", "lah OO-nyah", "nail"],
      ["la barba", "lah BAR-bah", "beard"], ["el bigote", "el bee-GOH-teh", "moustache"],
      ["la ceja", "lah SEH-hah", "eyebrow"], ["el labio", "el LAH-byoh", "lip"],
      ["la garganta", "lah gar-GAHN-tah", "throat"], ["el pulmón", "el pool-MOHN", "lung"],
      ["el músculo", "el MOOS-koo-loh", "muscle"], ["el cerebro", "el seh-REH-broh", "brain"],
      ["la voz", "lah BOHS", "voice"], ["la respiración", "lah rrehs-pee-rah-SYOHN", "breathing"],
    ]),
    V("health", [
      ["la gripe", "lah GREE-peh", "flu"], ["la alergia", "lah ah-LER-hyah", "allergy"],
      ["la vacuna", "lah bah-KOO-nah", "vaccine"],
      ["la venda", "lah BEN-dah", "bandage"], ["la pastilla", "lah pahs-TEE-yah", "pill"],
      ["el jarabe", "el hah-RAH-beh", "syrup"], ["el dentista", "el den-TEES-tah", "dentist"],
      ["la sangre", "lah SAHN-greh", "blood"], ["mareado", "mah-reh-AH-doh", "dizzy"],
      ["el estrés", "el ehs-TREHS", "stress"], ["dormir bien", "dor-MEER BYEN", "to sleep well"],
      ["toser", "toh-SER", "to cough"], ["estornudar", "ehs-tor-noo-DAR", "to sneeze"],
      ["curar", "koo-RAR", "to cure"], ["doler", "doh-LER", "to hurt"],
    ]),
    V("clothing", [
      ["la blusa", "lah BLOO-sah", "blouse"], ["el chaleco", "el chah-LEH-koh", "waistcoat"],
      ["el pijama", "el pee-HAH-mah", "pyjamas"], ["el bañador", "el bah-nyah-DOR", "swimsuit"],
      ["la ropa interior", "lah RROH-pah een-teh-RYOR", "underwear"],
      ["la corbata", "lah kor-BAH-tah", "tie"], ["el anillo", "el ah-NEE-yoh", "ring"],
      ["el collar", "el koh-YAR", "necklace"], ["el reloj", "el rreh-LOH", "watch"],
      ["el paraguas", "el pah-RAH-gwahs", "umbrella"],
      ["la cartera", "lah kar-TEH-rah", "wallet"], ["el algodón", "el ahl-goh-DOHN", "cotton"],
      ["la lana", "lah LAH-nah", "wool"], ["el cuero", "el KWEH-roh", "leather"],
      ["quitarse", "kee-TAR-seh", "to take off"], ["vestirse", "behs-TEER-seh", "to get dressed"],
    ]),
    V("home", [
      ["el pasillo", "el pah-SEE-yoh", "corridor"],
      ["el balcón", "el bahl-KOHN", "balcony"], ["el armario", "el ar-MAH-ryoh", "wardrobe"],
      ["el cajón", "el kah-HOHN", "drawer"], ["la estantería", "lah ehs-tahn-teh-REE-ah", "bookshelf"],
      ["la alfombra", "lah ahl-FOHM-brah", "rug"], ["la cortina", "lah kor-TEE-nah", "curtain"],
      ["la almohada", "lah ahl-moh-AH-dah", "pillow"], ["la manta", "lah MAHN-tah", "blanket"],
      ["la sábana", "lah SAH-bah-nah", "sheet"], ["la nevera", "lah neh-BEH-rah", "fridge"],
      ["el horno", "el OR-noh", "oven"], ["la ducha", "lah DOO-chah", "shower"],
      ["el grifo", "el GREE-foh", "tap"], ["la basura", "lah bah-SOO-rah", "rubbish"],
      ["la escoba", "lah ehs-KOH-bah", "broom"], ["el enchufe", "el en-CHOO-feh", "plug / socket"],
    ]),
    V("animals", [
      ["el pato", "el PAH-toh", "duck"], ["el ganso", "el GAHN-soh", "goose"],
      ["la cabra", "lah KAH-brah", "goat"], ["el burro", "el BOO-rroh", "donkey"],
      ["el zorro", "el SOH-rroh", "fox"], ["el ciervo", "el SYER-boh", "deer"],
      ["la ardilla", "lah ar-DEE-yah", "squirrel"], ["el murciélago", "el moor-SYEH-lah-goh", "bat"],
      ["la ballena", "lah bah-YEH-nah", "whale"], ["el delfín", "el del-FEEN", "dolphin"],
      ["el tiburón", "el tee-boo-ROHN", "shark"], ["el cangrejo", "el kahn-GREH-hoh", "crab"],
      ["la rana", "lah RRAH-nah", "frog"], ["el cocodrilo", "el koh-koh-DREE-loh", "crocodile"],
      ["el águila", "el AH-gee-lah", "eagle"], ["la paloma", "lah pah-LOH-mah", "dove / pigeon"],
      ["el mosquito", "el mohs-KEE-toh", "mosquito"], ["la cola", "lah KOH-lah", "tail"],
      ["el ala", "el AH-lah", "wing"],
    ]),
    V("nature", [
      ["la niebla", "lah NYEH-blah", "fog"], ["el hielo", "el YEH-loh", "ice"],
      ["el trueno", "el TRWEH-noh", "thunder"], ["el relámpago", "el rreh-LAHM-pah-goh", "lightning"],
      ["el arcoíris", "el ar-koh-EE-rees", "rainbow"], ["la sombra", "lah SOHM-brah", "shade / shadow"],
      ["la ola", "lah OH-lah", "wave"], ["la arena", "lah ah-REH-nah", "sand"],
      ["la colina", "lah koh-LEE-nah", "hill"], ["el valle", "el BAH-yeh", "valley"],
      ["la cueva", "lah KWEH-bah", "cave"], ["la raíz", "lah rrah-EES", "root"],
      ["la rama", "lah RRAH-mah", "branch"], ["la semilla", "lah seh-MEE-yah", "seed"],
      ["el bosque tropical", "el BOHS-keh troh-pee-KAHL", "rainforest"],
      ["el medio ambiente", "el MEH-dyoh ahm-BYEN-teh", "the environment"],
      ["la contaminación", "lah kohn-tah-mee-nah-SYOHN", "pollution"],
    ]),
    V("places", [
      ["la farmacia", "lah far-MAH-syah", "pharmacy"],
      ["la panadería", "lah pah-nah-deh-REE-ah", "bakery"],
      ["la carnicería", "lah kar-nee-seh-REE-ah", "butcher's"],
      ["el supermercado", "el soo-per-mer-KAH-doh", "supermarket"],
      ["la peluquería", "lah peh-loo-keh-REE-ah", "hairdresser's"],
      ["la comisaría", "lah koh-mee-sah-REE-ah", "police station"],
      ["el ayuntamiento", "el ah-yoon-tah-MYEN-toh", "town hall"],
      ["el teatro", "el teh-AH-troh", "theatre"],
      ["el estadio", "el ehs-TAH-dyoh", "stadium"],
      ["la playa", "lah PLAH-yah", "beach"],
      ["el puente", "el PWEN-teh", "bridge"],
      ["la esquina", "lah ehs-KEE-nah", "corner"],
      ["el barrio antiguo", "el BAH-rryoh ahn-TEE-gwoh", "old town"],
      ["la plaza mayor", "lah PLAH-sah mah-YOR", "main square"],
      ["el pueblo natal", "el PWEH-bloh nah-TAHL", "home town"],
    ]),
    V("travel", [
      ["el vuelo", "el BWEH-loh", "flight"], ["la puerta de embarque", "lah PWER-tah deh em-BAR-keh", "boarding gate"],
      ["el andén", "el ahn-DEN", "platform"], ["el asiento", "el ah-SYEN-toh", "seat"],
      ["la ventanilla", "lah ben-tah-NEE-yah", "window seat / ticket window"],
      ["la reserva", "lah rreh-SER-bah", "booking"],
      ["el alojamiento", "el ah-loh-hah-MYEN-toh", "accommodation"],
      ["la habitación doble", "lah ah-bee-tah-SYOHN DOH-bleh", "double room"],
      ["la llave de la habitación", "lah YAH-beh deh lah ah-bee-tah-SYOHN", "room key"],
      ["el guía", "el GEE-ah", "guide"], ["el recuerdo", "el rreh-KWER-doh", "souvenir"],
      ["la maleta de mano", "lah mah-LEH-tah deh MAH-noh", "hand luggage"],
      ["el seguro de viaje", "el seh-GOO-roh deh BYAH-heh", "travel insurance"],
      ["la gasolinera", "lah gah-soh-lee-NEH-rah", "petrol station"],
      ["el atasco", "el ah-TAHS-koh", "traffic jam"],
      ["alquilar", "ahl-kee-LAR", "to rent / hire"],
    ]),
    V("time", [
      ["septiembre", "sep-TYEM-breh", "September"], ["octubre", "ohk-TOO-breh", "October"],
      ["noviembre", "noh-BYEM-breh", "November"], ["diciembre", "dee-SYEM-breh", "December"],
      ["la primavera", "lah pree-mah-BEH-rah", "spring"], ["el otoño", "el oh-TOH-nyoh", "autumn"],
      ["el siglo", "el SEE-gloh", "century"], ["la década", "lah DEH-kah-dah", "decade"],
      ["el amanecer", "el ah-mah-neh-SER", "dawn"], ["el atardecer", "el ah-tar-deh-SER", "dusk"],
      ["la medianoche", "lah meh-dyah-NOH-cheh", "midnight"],
      ["el mediodía", "el meh-dyoh-DEE-ah", "midday"],
      ["anteayer", "ahn-teh-ah-YER", "the day before yesterday"],
      ["pasado mañana", "pah-SAH-doh mah-NYAH-nah", "the day after tomorrow"],
      ["el cumpleaños", "el koom-pleh-AH-nyohs", "birthday"],
      ["la fecha", "lah FEH-chah", "date"], ["el horario", "el oh-RAH-ryoh", "timetable"],
      ["a tiempo", "ah TYEM-poh", "on time"],
    ]),
    V("work", [
      ["la entrevista", "lah en-treh-BEES-tah", "interview"],
      ["el currículum", "el koo-RREE-koo-loom", "CV"],
      ["el sueldo mínimo", "el SWEL-doh MEE-nee-moh", "minimum wage"],
      ["el horario laboral", "el oh-RAH-ryoh lah-boh-RAHL", "working hours"],
      ["las vacaciones", "lahs bah-kah-SYOH-nehs", "holidays"],
      ["la jubilación", "lah hoo-bee-lah-SYOHN", "retirement"],
      ["el desempleo", "el deh-sem-PLEH-oh", "unemployment"],
      ["el impuesto", "el eem-PWEHS-toh", "tax"],
      ["el presupuesto", "el preh-soo-PWEHS-toh", "budget"],
      ["la ganancia", "lah gah-NAHN-syah", "profit"],
      ["la pérdida", "lah PER-dee-dah", "loss"],
      ["el descuento", "el dehs-KWEN-toh", "discount"],
      ["el recibo", "el rreh-SEE-boh", "receipt"],
      ["el mostrador", "el mohs-trah-DOR", "counter"],
      ["el enfermero", "el en-fer-MEH-roh", "nurse"],
      ["el cocinero", "el koh-see-NEH-roh", "cook"],
      ["el agricultor", "el ah-gree-kool-TOR", "farmer"],
    ]),
    V("school", [
      ["el aula", "el OW-lah", "classroom"], ["el pupitre", "el poo-PEE-treh", "desk"],
      ["la pizarra", "lah pee-SAH-rrah", "blackboard"], ["la goma", "lah GOH-mah", "rubber"],
      ["la regla", "lah RREH-glah", "ruler"], ["la mochila", "lah moh-CHEE-lah", "backpack"],
      ["el diccionario", "el deek-syoh-NAH-ryoh", "dictionary"],
      ["el ejercicio", "el eh-her-SEE-syoh", "exercise"],
      ["el apunte", "el ah-POON-teh", "note"], ["el resumen", "el rreh-SOO-men", "summary"],
      ["la beca", "lah BEH-kah", "scholarship"], ["la carrera", "lah kah-RREH-rah", "degree course"],
      ["la asignatura", "lah ah-seeg-nah-TOO-rah", "subject"],
      ["la geografía", "lah heh-oh-grah-FEE-ah", "geography"],
      ["el arte", "el AR-teh", "art"], ["la música", "lah MOO-see-kah", "music"],
      ["aprobar", "ah-proh-BAR", "to pass (an exam)"],
      ["suspender", "soos-pen-DER", "to fail"],
      ["repasar", "rreh-pah-SAR", "to revise"],
    ]),
    V("tech", [
      ["el portátil", "el por-TAH-teel", "laptop"],
      ["la tableta", "lah tah-BLEH-tah", "tablet"],
      ["el altavoz", "el ahl-tah-BOHS", "speaker"],
      ["los auriculares", "lohs ow-ree-koo-LAH-rehs", "headphones"],
      ["el cargador", "el kar-gah-DOR", "charger"],
      ["la impresora", "lah eem-preh-SOH-rah", "printer"],
      ["el usuario", "el oo-SWAH-ryoh", "user"],
      ["la cuenta", "lah KWEN-tah", "account"],
      ["el mensaje", "el men-SAH-heh", "message"],
      ["la llamada", "lah yah-MAH-dah", "call"],
      ["la pantalla táctil", "lah pahn-TAH-yah TAHK-teel", "touchscreen"],
      ["la contraseña segura", "lah kohn-trah-SEH-nyah seh-GOO-rah", "strong password"],
      ["actualizar", "ahk-twah-lee-SAR", "to update"],
      ["instalar", "een-stah-LAR", "to install"],
      ["conectar", "koh-nek-TAR", "to connect"],
      ["compartir", "kohm-par-TEER", "to share"],
      ["la red social", "lah rred soh-SYAHL", "social network"],
    ])
  );

  /* ------------------------------ Sentences ------------------------------ */
  const SENTENCES = [].concat(
    S("greetings", [
      ["Hola, ¿cómo estás?", "OH-la KOH-moh ehs-TAHS", "Hello, how are you?",
        [["Hola", "OH-la"], ["cómo", "KOH-moh"], ["estás", "ehs-TAHS"]]],
      ["Estoy muy bien, gracias", "ehs-TOY mwee BYEN GRAH-syahs", "I am very well, thank you",
        [["Estoy", "ehs-TOY"], ["muy", "mwee"], ["bien", "BYEN"], ["gracias", "GRAH-syahs"]]],
      ["¿Cómo te llamas?", "KOH-moh teh YAH-mahs", "What is your name?",
        [["Cómo", "KOH-moh"], ["te", "teh"], ["llamas", "YAH-mahs"]]],
      ["Me llamo Ana", "meh YAH-moh AH-nah", "My name is Ana",
        [["Me", "meh"], ["llamo", "YAH-moh"], ["Ana", "AH-nah"]]],
      ["No entiendo", "noh en-TYEN-doh", "I don't understand",
        [["No", "noh"], ["entiendo", "en-TYEN-doh"]]],
      ["¿Puedes repetirlo, por favor?", "PWEH-dehs rreh-peh-TEER-loh por fah-VOR",
        "Can you repeat that, please?",
        [["Puedes", "PWEH-dehs"], ["repetirlo", "rreh-peh-TEER-loh"], ["por", "por"], ["favor", "fah-VOR"]]],
      ["Mucho gusto en conocerte", "MOO-choh GOOS-toh en koh-noh-SER-teh",
        "Nice to meet you",
        [["Mucho", "MOO-choh"], ["gusto", "GOOS-toh"], ["en", "en"], ["conocerte", "koh-noh-SER-teh"]]],
      ["¿Hablas inglés?", "AH-blahs een-GLEHS", "Do you speak English?",
        [["Hablas", "AH-blahs"], ["inglés", "een-GLEHS"]]],
    ]),
    S("food", [
      ["Quiero un café, por favor", "KYEH-roh oon kah-FEH por fah-VOR",
        "I want a coffee, please",
        [["Quiero", "KYEH-roh"], ["un", "oon"], ["café", "kah-FEH"], ["por", "por"], ["favor", "fah-VOR"]]],
      ["Tengo hambre", "TEN-goh AHM-breh", "I am hungry",
        [["Tengo", "TEN-goh"], ["hambre", "AHM-breh"]]],
      ["Tengo sed", "TEN-goh SED", "I am thirsty",
        [["Tengo", "TEN-goh"], ["sed", "SED"]]],
      ["La comida está deliciosa", "lah koh-MEE-dah ehs-TAH deh-lee-SYOH-sah",
        "The food is delicious",
        [["La", "lah"], ["comida", "koh-MEE-dah"], ["está", "ehs-TAH"], ["deliciosa", "deh-lee-SYOH-sah"]]],
      ["La cuenta, por favor", "lah KWEN-tah por fah-VOR", "The bill, please",
        [["La", "lah"], ["cuenta", "KWEN-tah"], ["por", "por"], ["favor", "fah-VOR"]]],
      ["No como carne", "noh KOH-moh KAR-neh", "I don't eat meat",
        [["No", "noh"], ["como", "KOH-moh"], ["carne", "KAR-neh"]]],
    ]),
    S("travel", [
      ["¿Dónde está la estación?", "DOHN-deh ehs-TAH lah ehs-tah-SYOHN",
        "Where is the station?",
        [["Dónde", "DOHN-deh"], ["está", "ehs-TAH"], ["la", "lah"], ["estación", "ehs-tah-SYOHN"]]],
      ["Quiero un billete a Madrid", "KYEH-roh oon bee-YEH-teh ah mah-DREED",
        "I want a ticket to Madrid",
        [["Quiero", "KYEH-roh"], ["un", "oon"], ["billete", "bee-YEH-teh"], ["a", "ah"], ["Madrid", "mah-DREED"]]],
      ["El tren llega a las ocho", "el TREN YEH-gah ah lahs OH-choh",
        "The train arrives at eight",
        [["El", "el"], ["tren", "TREN"], ["llega", "YEH-gah"], ["a", "ah"], ["las", "lahs"], ["ocho", "OH-choh"]]],
      ["Estoy perdido", "ehs-TOY per-DEE-doh", "I am lost",
        [["Estoy", "ehs-TOY"], ["perdido", "per-DEE-doh"]]],
      ["Gire a la derecha", "HEE-reh ah lah deh-REH-chah", "Turn right",
        [["Gire", "HEE-reh"], ["a", "ah"], ["la", "lah"], ["derecha", "deh-REH-chah"]]],
    ]),
    S("home", [
      ["Vivo en una casa pequeña", "BEE-boh en OO-nah KAH-sah peh-KEH-nyah",
        "I live in a small house",
        [["Vivo", "BEE-boh"], ["en", "en"], ["una", "OO-nah"], ["casa", "KAH-sah"], ["pequeña", "peh-KEH-nyah"]]],
      ["La puerta está abierta", "lah PWER-tah ehs-TAH ah-BYER-tah", "The door is open",
        [["La", "lah"], ["puerta", "PWER-tah"], ["está", "ehs-TAH"], ["abierta", "ah-BYER-tah"]]],
      ["Mi familia es grande", "mee fah-MEE-lyah ehs GRAHN-deh", "My family is big",
        [["Mi", "mee"], ["familia", "fah-MEE-lyah"], ["es", "ehs"], ["grande", "GRAHN-deh"]]],
    ]),
    S("time", [
      ["¿Qué hora es?", "keh OH-rah ehs", "What time is it?",
        [["Qué", "keh"], ["hora", "OH-rah"], ["es", "ehs"]]],
      ["Hoy es lunes", "OY ehs LOO-nehs", "Today is Monday",
        [["Hoy", "OY"], ["es", "ehs"], ["lunes", "LOO-nehs"]]],
      ["Mañana voy al mercado", "mah-NYAH-nah boy ahl mer-KAH-doh",
        "Tomorrow I go to the market",
        [["Mañana", "mah-NYAH-nah"], ["voy", "boy"], ["al", "ahl"], ["mercado", "mer-KAH-doh"]]],
      ["Siempre trabajo por la mañana", "SYEM-preh trah-BAH-hoh por lah mah-NYAH-nah",
        "I always work in the morning",
        [["Siempre", "SYEM-preh"], ["trabajo", "trah-BAH-hoh"], ["por", "por"], ["la", "lah"], ["mañana", "mah-NYAH-nah"]]],
    ]),
    S("school", [
      ["Estudio español todos los días", "ehs-TOO-dyoh ehs-pah-NYOL TOH-dohs lohs DEE-ahs",
        "I study Spanish every day",
        [["Estudio", "ehs-TOO-dyoh"], ["español", "ehs-pah-NYOL"], ["todos", "TOH-dohs"], ["los", "lohs"], ["días", "DEE-ahs"]]],
      ["El libro es muy interesante", "el LEE-broh ehs mwee een-teh-reh-SAHN-teh",
        "The book is very interesting",
        [["El", "el"], ["libro", "LEE-broh"], ["es", "ehs"], ["muy", "mwee"], ["interesante", "een-teh-reh-SAHN-teh"]]],
      ["¿Puedes ayudarme?", "PWEH-dehs ah-yoo-DAR-meh", "Can you help me?",
        [["Puedes", "PWEH-dehs"], ["ayudarme", "ah-yoo-DAR-meh"]]],
    ]),
    S("health", [
      ["Me duele la cabeza", "meh DWEH-leh lah kah-BEH-sah", "My head hurts",
        [["Me", "meh"], ["duele", "DWEH-leh"], ["la", "lah"], ["cabeza", "kah-BEH-sah"]]],
      ["Necesito un médico", "neh-seh-SEE-toh oon MEH-dee-koh", "I need a doctor",
        [["Necesito", "neh-seh-SEE-toh"], ["un", "oon"], ["médico", "MEH-dee-koh"]]],
      ["No me siento bien", "noh meh SYEN-toh BYEN", "I don't feel well",
        [["No", "noh"], ["me", "meh"], ["siento", "SYEN-toh"], ["bien", "BYEN"]]],
    ]),
    S("work", [
      ["¿Cuánto cuesta esto?", "KWAHN-toh KWEHS-tah EHS-toh", "How much does this cost?",
        [["Cuánto", "KWAHN-toh"], ["cuesta", "KWEHS-tah"], ["esto", "EHS-toh"]]],
      ["Es demasiado caro", "ehs deh-mah-SYAH-doh KAH-roh", "It is too expensive",
        [["Es", "ehs"], ["demasiado", "deh-mah-SYAH-doh"], ["caro", "KAH-roh"]]],
      ["Trabajo en una oficina", "trah-BAH-hoh en OO-nah oh-fee-SEE-nah",
        "I work in an office",
        [["Trabajo", "trah-BAH-hoh"], ["en", "en"], ["una", "OO-nah"], ["oficina", "oh-fee-SEE-nah"]]],
    ]),
    S("greetings", [
      ["¿De dónde eres?", "deh DOHN-deh EH-rehs", "Where are you from?",
        [["De", "deh"], ["dónde", "DOHN-deh"], ["eres", "EH-rehs"]]],
      ["Soy de Inglaterra", "soy deh een-glah-TEH-rrah", "I am from England",
        [["Soy", "soy"], ["de", "deh"], ["Inglaterra", "een-glah-TEH-rrah"]]],
      ["Estoy aprendiendo español", "ehs-TOY ah-pren-DYEN-doh ehs-pah-NYOL",
        "I am learning Spanish",
        [["Estoy", "ehs-TOY"], ["aprendiendo", "ah-pren-DYEN-doh"], ["español", "ehs-pah-NYOL"]]],
      ["Hablo un poco de español", "AH-bloh oon POH-koh deh ehs-pah-NYOL",
        "I speak a little Spanish",
        [["Hablo", "AH-bloh"], ["un", "oon"], ["poco", "POH-koh"], ["de", "deh"], ["español", "ehs-pah-NYOL"]]],
      ["¿Cómo se dice esto en español?", "KOH-moh seh DEE-seh EHS-toh en ehs-pah-NYOL",
        "How do you say this in Spanish?",
        [["Cómo", "KOH-moh"], ["se", "seh"], ["dice", "DEE-seh"], ["esto", "EHS-toh"], ["en", "en"], ["español", "ehs-pah-NYOL"]]],
    ]),
    S("food", [
      ["¿Qué me recomienda?", "keh meh rreh-koh-MYEN-dah", "What do you recommend?",
        [["Qué", "keh"], ["me", "meh"], ["recomienda", "rreh-koh-MYEN-dah"]]],
      ["Para mí, una ensalada", "PAH-rah MEE OO-nah en-sah-LAH-dah",
        "For me, a salad",
        [["Para", "PAH-rah"], ["mí", "MEE"], ["una", "OO-nah"], ["ensalada", "en-sah-LAH-dah"]]],
      ["Soy alérgico a los frutos secos", "soy ah-LER-hee-koh ah lohs FROO-tohs SEH-kohs",
        "I am allergic to nuts",
        [["Soy", "soy"], ["alérgico", "ah-LER-hee-koh"], ["a", "ah"], ["los", "lohs"], ["frutos", "FROO-tohs"], ["secos", "SEH-kohs"]]],
      ["Está muy rico", "ehs-TAH mwee RREE-koh", "It's very tasty",
        [["Está", "ehs-TAH"], ["muy", "mwee"], ["rico", "RREE-koh"]]],
    ]),
    S("travel", [
      ["¿A qué hora sale el tren?", "ah keh OH-rah SAH-leh el TREN",
        "What time does the train leave?",
        [["A", "ah"], ["qué", "keh"], ["hora", "OH-rah"], ["sale", "SAH-leh"], ["el", "el"], ["tren", "TREN"]]],
      ["¿Está lejos de aquí?", "ehs-TAH LEH-hohs deh ah-KEE", "Is it far from here?",
        [["Está", "ehs-TAH"], ["lejos", "LEH-hohs"], ["de", "deh"], ["aquí", "ah-KEE"]]],
      ["Quiero reservar una habitación", "KYEH-roh rreh-ser-BAR OO-nah ah-bee-tah-SYOHN",
        "I want to book a room",
        [["Quiero", "KYEH-roh"], ["reservar", "rreh-ser-BAR"], ["una", "OO-nah"], ["habitación", "ah-bee-tah-SYOHN"]]],
    ]),
    S("work", [
      ["¿Puedo pagar con tarjeta?", "PWEH-doh pah-GAR kohn tar-HEH-tah",
        "Can I pay by card?",
        [["Puedo", "PWEH-doh"], ["pagar", "pah-GAR"], ["con", "kohn"], ["tarjeta", "tar-HEH-tah"]]],
      ["Me lo llevo", "meh loh YEH-boh", "I'll take it",
        [["Me", "meh"], ["lo", "loh"], ["llevo", "YEH-boh"]]],
    ]),
    S("home", [
      ["Vivo aquí desde hace dos años", "BEE-boh ah-KEE DEHS-deh AH-seh dohs AH-nyohs",
        "I have lived here for two years",
        [["Vivo", "BEE-boh"], ["aquí", "ah-KEE"], ["desde", "DEHS-deh"], ["hace", "AH-seh"], ["dos", "dohs"], ["años", "AH-nyohs"]]],
    ]),
    S("health", [
      ["Me encuentro mal", "meh en-KWEN-troh MAHL", "I feel ill",
        [["Me", "meh"], ["encuentro", "en-KWEN-troh"], ["mal", "MAHL"]]],
    ])
  );

  /* ----------------------------- Conjugation ------------------------------
   * Six persons across three simple tenses. Pronouns are usually dropped in
   * Spanish, but they're kept here so each form is unambiguous when practising. */
  const CONJUGATION = [
    C("ser", "SER", "be", [
      ["yo fui", "yoh FWEE", "I was", "I", "past"],
      ["tú fuiste", "too FWEES-teh", "you were", "you", "past"],
      ["él fue", "el FWEH", "he was", "he", "past"],
      ["ella fue", "EH-yah FWEH", "she was", "she", "past"],
      ["nosotros fuimos", "noh-SOH-trohs FWEE-mohs", "we were", "we", "past"],
      ["ellos fueron", "EH-yohs FWEH-rohn", "they were", "they", "past"],
      ["yo soy", "yoh SOY", "I am", "I", "present"],
      ["tú eres", "too EH-rehs", "you are", "you", "present"],
      ["él es", "el EHS", "he is", "he", "present"],
      ["ella es", "EH-yah EHS", "she is", "she", "present"],
      ["nosotros somos", "noh-SOH-trohs SOH-mohs", "we are", "we", "present"],
      ["ellos son", "EH-yohs SOHN", "they are", "they", "present"],
      ["yo seré", "yoh seh-REH", "I will be", "I", "future"],
      ["tú serás", "too seh-RAHS", "you will be", "you", "future"],
      ["él será", "el seh-RAH", "he will be", "he", "future"],
      ["ella será", "EH-yah seh-RAH", "she will be", "she", "future"],
      ["nosotros seremos", "noh-SOH-trohs seh-REH-mohs", "we will be", "we", "future"],
      ["ellos serán", "EH-yohs seh-RAHN", "they will be", "they", "future"],
    ]),
    C("estar", "ehs-TAR", "be (state)", [
      ["yo estuve", "yoh ehs-TOO-beh", "I was", "I", "past"],
      ["tú estuviste", "too ehs-too-BEES-teh", "you were", "you", "past"],
      ["él estuvo", "el ehs-TOO-boh", "he was", "he", "past"],
      ["nosotros estuvimos", "noh-SOH-trohs ehs-too-BEE-mohs", "we were", "we", "past"],
      ["ellos estuvieron", "EH-yohs ehs-too-BYEH-rohn", "they were", "they", "past"],
      ["yo estoy", "yoh ehs-TOY", "I am", "I", "present"],
      ["tú estás", "too ehs-TAHS", "you are", "you", "present"],
      ["él está", "el ehs-TAH", "he is", "he", "present"],
      ["nosotros estamos", "noh-SOH-trohs ehs-TAH-mohs", "we are", "we", "present"],
      ["ellos están", "EH-yohs ehs-TAHN", "they are", "they", "present"],
      ["yo estaré", "yoh ehs-tah-REH", "I will be", "I", "future"],
      ["tú estarás", "too ehs-tah-RAHS", "you will be", "you", "future"],
      ["él estará", "el ehs-tah-RAH", "he will be", "he", "future"],
      ["nosotros estaremos", "noh-SOH-trohs ehs-tah-REH-mohs", "we will be", "we", "future"],
      ["ellos estarán", "EH-yohs ehs-tah-RAHN", "they will be", "they", "future"],
    ]),
    C("tener", "teh-NER", "have", [
      ["yo tuve", "yoh TOO-beh", "I had", "I", "past"],
      ["tú tuviste", "too too-BEES-teh", "you had", "you", "past"],
      ["él tuvo", "el TOO-boh", "he had", "he", "past"],
      ["nosotros tuvimos", "noh-SOH-trohs too-BEE-mohs", "we had", "we", "past"],
      ["ellos tuvieron", "EH-yohs too-BYEH-rohn", "they had", "they", "past"],
      ["yo tengo", "yoh TEN-goh", "I have", "I", "present"],
      ["tú tienes", "too TYEH-nehs", "you have", "you", "present"],
      ["él tiene", "el TYEH-neh", "he has", "he", "present"],
      ["nosotros tenemos", "noh-SOH-trohs teh-NEH-mohs", "we have", "we", "present"],
      ["ellos tienen", "EH-yohs TYEH-nen", "they have", "they", "present"],
      ["yo tendré", "yoh ten-DREH", "I will have", "I", "future"],
      ["tú tendrás", "too ten-DRAHS", "you will have", "you", "future"],
      ["él tendrá", "el ten-DRAH", "he will have", "he", "future"],
      ["nosotros tendremos", "noh-SOH-trohs ten-DREH-mohs", "we will have", "we", "future"],
      ["ellos tendrán", "EH-yohs ten-DRAHN", "they will have", "they", "future"],
    ]),
    C("hablar", "ah-BLAR", "speak", [
      ["yo hablé", "yoh ah-BLEH", "I spoke", "I", "past"],
      ["tú hablaste", "too ah-BLAHS-teh", "you spoke", "you", "past"],
      ["él habló", "el ah-BLOH", "he spoke", "he", "past"],
      ["nosotros hablamos", "noh-SOH-trohs ah-BLAH-mohs", "we spoke", "we", "past"],
      ["ellos hablaron", "EH-yohs ah-BLAH-rohn", "they spoke", "they", "past"],
      ["yo hablo", "yoh AH-bloh", "I speak", "I", "present"],
      ["tú hablas", "too AH-blahs", "you speak", "you", "present"],
      ["él habla", "el AH-blah", "he speaks", "he", "present"],
      ["nosotros hablamos", "noh-SOH-trohs ah-BLAH-mohs", "we speak", "we", "present"],
      ["ellos hablan", "EH-yohs AH-blahn", "they speak", "they", "present"],
      ["yo hablaré", "yoh ah-blah-REH", "I will speak", "I", "future"],
      ["tú hablarás", "too ah-blah-RAHS", "you will speak", "you", "future"],
      ["él hablará", "el ah-blah-RAH", "he will speak", "he", "future"],
      ["nosotros hablaremos", "noh-SOH-trohs ah-blah-REH-mohs", "we will speak", "we", "future"],
      ["ellos hablarán", "EH-yohs ah-blah-RAHN", "they will speak", "they", "future"],
    ]),
    C("comer", "koh-MER", "eat", [
      ["yo comí", "yoh koh-MEE", "I ate", "I", "past"],
      ["tú comiste", "too koh-MEES-teh", "you ate", "you", "past"],
      ["él comió", "el koh-MYOH", "he ate", "he", "past"],
      ["nosotros comimos", "noh-SOH-trohs koh-MEE-mohs", "we ate", "we", "past"],
      ["ellos comieron", "EH-yohs koh-MYEH-rohn", "they ate", "they", "past"],
      ["yo como", "yoh KOH-moh", "I eat", "I", "present"],
      ["tú comes", "too KOH-mehs", "you eat", "you", "present"],
      ["él come", "el KOH-meh", "he eats", "he", "present"],
      ["nosotros comemos", "noh-SOH-trohs koh-MEH-mohs", "we eat", "we", "present"],
      ["ellos comen", "EH-yohs KOH-men", "they eat", "they", "present"],
      ["yo comeré", "yoh koh-meh-REH", "I will eat", "I", "future"],
      ["tú comerás", "too koh-meh-RAHS", "you will eat", "you", "future"],
      ["él comerá", "el koh-meh-RAH", "he will eat", "he", "future"],
      ["nosotros comeremos", "noh-SOH-trohs koh-meh-REH-mohs", "we will eat", "we", "future"],
      ["ellos comerán", "EH-yohs koh-meh-RAHN", "they will eat", "they", "future"],
    ]),
    C("vivir", "bee-BEER", "live", [
      ["yo viví", "yoh bee-BEE", "I lived", "I", "past"],
      ["tú viviste", "too bee-BEES-teh", "you lived", "you", "past"],
      ["él vivió", "el bee-BYOH", "he lived", "he", "past"],
      ["nosotros vivimos", "noh-SOH-trohs bee-BEE-mohs", "we lived", "we", "past"],
      ["ellos vivieron", "EH-yohs bee-BYEH-rohn", "they lived", "they", "past"],
      ["yo vivo", "yoh BEE-boh", "I live", "I", "present"],
      ["tú vives", "too BEE-behs", "you live", "you", "present"],
      ["él vive", "el BEE-beh", "he lives", "he", "present"],
      ["nosotros vivimos", "noh-SOH-trohs bee-BEE-mohs", "we live", "we", "present"],
      ["ellos viven", "EH-yohs BEE-ben", "they live", "they", "present"],
      ["yo viviré", "yoh bee-bee-REH", "I will live", "I", "future"],
      ["tú vivirás", "too bee-bee-RAHS", "you will live", "you", "future"],
      ["él vivirá", "el bee-bee-RAH", "he will live", "he", "future"],
      ["nosotros viviremos", "noh-SOH-trohs bee-bee-REH-mohs", "we will live", "we", "future"],
      ["ellos vivirán", "EH-yohs bee-bee-RAHN", "they will live", "they", "future"],
    ]),
    C("ir", "EER", "go", [
      ["yo fui", "yoh FWEE", "I went", "I", "past"],
      ["tú fuiste", "too FWEES-teh", "you went", "you", "past"],
      ["él fue", "el FWEH", "he went", "he", "past"],
      ["nosotros fuimos", "noh-SOH-trohs FWEE-mohs", "we went", "we", "past"],
      ["ellos fueron", "EH-yohs FWEH-rohn", "they went", "they", "past"],
      ["yo voy", "yoh BOY", "I go", "I", "present"],
      ["tú vas", "too BAHS", "you go", "you", "present"],
      ["él va", "el BAH", "he goes", "he", "present"],
      ["nosotros vamos", "noh-SOH-trohs BAH-mohs", "we go", "we", "present"],
      ["ellos van", "EH-yohs BAHN", "they go", "they", "present"],
      ["yo iré", "yoh ee-REH", "I will go", "I", "future"],
      ["tú irás", "too ee-RAHS", "you will go", "you", "future"],
      ["él irá", "el ee-RAH", "he will go", "he", "future"],
      ["nosotros iremos", "noh-SOH-trohs ee-REH-mohs", "we will go", "we", "future"],
      ["ellos irán", "EH-yohs ee-RAHN", "they will go", "they", "future"],
    ]),
    C("hacer", "ah-SER", "do / make", [
      ["yo hice", "yoh EE-seh", "I did", "I", "past"],
      ["tú hiciste", "too ee-SEES-teh", "you did", "you", "past"],
      ["él hizo", "el EE-soh", "he did", "he", "past"],
      ["nosotros hicimos", "noh-SOH-trohs ee-SEE-mohs", "we did", "we", "past"],
      ["ellos hicieron", "EH-yohs ee-SYEH-rohn", "they did", "they", "past"],
      ["yo hago", "yoh AH-goh", "I do", "I", "present"],
      ["tú haces", "too AH-sehs", "you do", "you", "present"],
      ["él hace", "el AH-seh", "he does", "he", "present"],
      ["nosotros hacemos", "noh-SOH-trohs ah-SEH-mohs", "we do", "we", "present"],
      ["ellos hacen", "EH-yohs AH-sen", "they do", "they", "present"],
      ["yo haré", "yoh ah-REH", "I will do", "I", "future"],
      ["tú harás", "too ah-RAHS", "you will do", "you", "future"],
      ["él hará", "el ah-RAH", "he will do", "he", "future"],
      ["nosotros haremos", "noh-SOH-trohs ah-REH-mohs", "we will do", "we", "future"],
      ["ellos harán", "EH-yohs ah-RAHN", "they will do", "they", "future"],
    ]),
    C("querer", "keh-RER", "want", [
      ["yo quise", "yoh KEE-seh", "I wanted", "I", "past"],
      ["tú quisiste", "too kee-SEES-teh", "you wanted", "you", "past"],
      ["él quiso", "el KEE-soh", "he wanted", "he", "past"],
      ["nosotros quisimos", "noh-SOH-trohs kee-SEE-mohs", "we wanted", "we", "past"],
      ["ellos quisieron", "EH-yohs kee-SYEH-rohn", "they wanted", "they", "past"],
      ["yo quiero", "yoh KYEH-roh", "I want", "I", "present"],
      ["tú quieres", "too KYEH-rehs", "you want", "you", "present"],
      ["él quiere", "el KYEH-reh", "he wants", "he", "present"],
      ["nosotros queremos", "noh-SOH-trohs keh-REH-mohs", "we want", "we", "present"],
      ["ellos quieren", "EH-yohs KYEH-ren", "they want", "they", "present"],
      ["yo querré", "yoh keh-RREH", "I will want", "I", "future"],
      ["tú querrás", "too keh-RRAHS", "you will want", "you", "future"],
      ["él querrá", "el keh-RRAH", "he will want", "he", "future"],
      ["nosotros querremos", "noh-SOH-trohs keh-RREH-mohs", "we will want", "we", "future"],
      ["ellos querrán", "EH-yohs keh-RRAHN", "they will want", "they", "future"],
    ]),
    C("poder", "poh-DER", "be able to", [
      ["yo pude", "yoh POO-deh", "I could", "I", "past"],
      ["tú pudiste", "too poo-DEES-teh", "you could", "you", "past"],
      ["él pudo", "el POO-doh", "he could", "he", "past"],
      ["nosotros pudimos", "noh-SOH-trohs poo-DEE-mohs", "we could", "we", "past"],
      ["ellos pudieron", "EH-yohs poo-DYEH-rohn", "they could", "they", "past"],
      ["yo puedo", "yoh PWEH-doh", "I can", "I", "present"],
      ["tú puedes", "too PWEH-dehs", "you can", "you", "present"],
      ["él puede", "el PWEH-deh", "he can", "he", "present"],
      ["nosotros podemos", "noh-SOH-trohs poh-DEH-mohs", "we can", "we", "present"],
      ["ellos pueden", "EH-yohs PWEH-den", "they can", "they", "present"],
      ["yo podré", "yoh poh-DREH", "I will be able to", "I", "future"],
      ["tú podrás", "too poh-DRAHS", "you will be able to", "you", "future"],
      ["él podrá", "el poh-DRAH", "he will be able to", "he", "future"],
      ["nosotros podremos", "noh-SOH-trohs poh-DREH-mohs", "we will be able to", "we", "future"],
      ["ellos podrán", "EH-yohs poh-DRAHN", "they will be able to", "they", "future"],
    ]),
    C("decir", "deh-SEER", "say", [
      ["yo dije", "yoh DEE-heh", "I said", "I", "past"],
      ["tú dijiste", "too dee-HEES-teh", "you said", "you", "past"],
      ["él dijo", "el DEE-hoh", "he said", "he", "past"],
      ["nosotros dijimos", "noh-SOH-trohs dee-HEE-mohs", "we said", "we", "past"],
      ["ellos dijeron", "EH-yohs dee-HEH-rohn", "they said", "they", "past"],
      ["yo digo", "yoh DEE-goh", "I say", "I", "present"],
      ["tú dices", "too DEE-sehs", "you say", "you", "present"],
      ["él dice", "el DEE-seh", "he says", "he", "present"],
      ["nosotros decimos", "noh-SOH-trohs deh-SEE-mohs", "we say", "we", "present"],
      ["ellos dicen", "EH-yohs DEE-sen", "they say", "they", "present"],
      ["yo diré", "yoh dee-REH", "I will say", "I", "future"],
      ["tú dirás", "too dee-RAHS", "you will say", "you", "future"],
      ["él dirá", "el dee-RAH", "he will say", "he", "future"],
      ["nosotros diremos", "noh-SOH-trohs dee-REH-mohs", "we will say", "we", "future"],
      ["ellos dirán", "EH-yohs dee-RAHN", "they will say", "they", "future"],
    ]),
    C("saber", "sah-BER", "know", [
      ["yo supe", "yoh SOO-peh", "I knew / found out", "I", "past"],
      ["tú supiste", "too soo-PEES-teh", "you knew", "you", "past"],
      ["él supo", "el SOO-poh", "he knew", "he", "past"],
      ["nosotros supimos", "noh-SOH-trohs soo-PEE-mohs", "we knew", "we", "past"],
      ["ellos supieron", "EH-yohs soo-PYEH-rohn", "they knew", "they", "past"],
      ["yo sé", "yoh SEH", "I know", "I", "present"],
      ["tú sabes", "too SAH-behs", "you know", "you", "present"],
      ["él sabe", "el SAH-beh", "he knows", "he", "present"],
      ["nosotros sabemos", "noh-SOH-trohs sah-BEH-mohs", "we know", "we", "present"],
      ["ellos saben", "EH-yohs SAH-ben", "they know", "they", "present"],
      ["yo sabré", "yoh sah-BREH", "I will know", "I", "future"],
      ["tú sabrás", "too sah-BRAHS", "you will know", "you", "future"],
      ["él sabrá", "el sah-BRAH", "he will know", "he", "future"],
      ["nosotros sabremos", "noh-SOH-trohs sah-BREH-mohs", "we will know", "we", "future"],
      ["ellos sabrán", "EH-yohs sah-BRAHN", "they will know", "they", "future"],
    ]),
    C("dar", "DAR", "give", [
      ["yo di", "yoh DEE", "I gave", "I", "past"],
      ["tú diste", "too DEES-teh", "you gave", "you", "past"],
      ["él dio", "el DYOH", "he gave", "he", "past"],
      ["nosotros dimos", "noh-SOH-trohs DEE-mohs", "we gave", "we", "past"],
      ["ellos dieron", "EH-yohs DYEH-rohn", "they gave", "they", "past"],
      ["yo doy", "yoh DOY", "I give", "I", "present"],
      ["tú das", "too DAHS", "you give", "you", "present"],
      ["él da", "el DAH", "he gives", "he", "present"],
      ["nosotros damos", "noh-SOH-trohs DAH-mohs", "we give", "we", "present"],
      ["ellos dan", "EH-yohs DAHN", "they give", "they", "present"],
      ["yo daré", "yoh dah-REH", "I will give", "I", "future"],
      ["tú darás", "too dah-RAHS", "you will give", "you", "future"],
      ["él dará", "el dah-RAH", "he will give", "he", "future"],
      ["nosotros daremos", "noh-SOH-trohs dah-REH-mohs", "we will give", "we", "future"],
      ["ellos darán", "EH-yohs dah-RAHN", "they will give", "they", "future"],
    ]),
    C("ver", "BER", "see", [
      ["yo vi", "yoh BEE", "I saw", "I", "past"],
      ["tú viste", "too BEES-teh", "you saw", "you", "past"],
      ["él vio", "el BYOH", "he saw", "he", "past"],
      ["nosotros vimos", "noh-SOH-trohs BEE-mohs", "we saw", "we", "past"],
      ["ellos vieron", "EH-yohs BYEH-rohn", "they saw", "they", "past"],
      ["yo veo", "yoh BEH-oh", "I see", "I", "present"],
      ["tú ves", "too BEHS", "you see", "you", "present"],
      ["él ve", "el BEH", "he sees", "he", "present"],
      ["nosotros vemos", "noh-SOH-trohs BEH-mohs", "we see", "we", "present"],
      ["ellos ven", "EH-yohs BEN", "they see", "they", "present"],
      ["yo veré", "yoh beh-REH", "I will see", "I", "future"],
      ["tú verás", "too beh-RAHS", "you will see", "you", "future"],
      ["él verá", "el beh-RAH", "he will see", "he", "future"],
      ["nosotros veremos", "noh-SOH-trohs beh-REH-mohs", "we will see", "we", "future"],
      ["ellos verán", "EH-yohs beh-RAHN", "they will see", "they", "future"],
    ]),
    C("trabajar", "trah-bah-HAR", "work", [
      ["yo trabajé", "yoh trah-bah-HEH", "I worked", "I", "past"],
      ["tú trabajaste", "too trah-bah-HAHS-teh", "you worked", "you", "past"],
      ["él trabajó", "el trah-bah-HOH", "he worked", "he", "past"],
      ["nosotros trabajamos", "noh-SOH-trohs trah-bah-HAH-mohs", "we worked", "we", "past"],
      ["ellos trabajaron", "EH-yohs trah-bah-HAH-rohn", "they worked", "they", "past"],
      ["yo trabajo", "yoh trah-BAH-hoh", "I work", "I", "present"],
      ["tú trabajas", "too trah-BAH-hahs", "you work", "you", "present"],
      ["él trabaja", "el trah-BAH-hah", "he works", "he", "present"],
      ["nosotros trabajamos", "noh-SOH-trohs trah-bah-HAH-mohs", "we work", "we", "present"],
      ["ellos trabajan", "EH-yohs trah-BAH-hahn", "they work", "they", "present"],
      ["yo trabajaré", "yoh trah-bah-hah-REH", "I will work", "I", "future"],
      ["tú trabajarás", "too trah-bah-hah-RAHS", "you will work", "you", "future"],
      ["él trabajará", "el trah-bah-hah-RAH", "he will work", "he", "future"],
      ["nosotros trabajaremos", "noh-SOH-trohs trah-bah-hah-REH-mohs", "we will work", "we", "future"],
      ["ellos trabajarán", "EH-yohs trah-bah-hah-RAHN", "they will work", "they", "future"],
    ]),
  ];

  /* ------------------------------- Proverbs ------------------------------- */
  const PROVERBS = [
    { n: 1, chapterEn: "Patience",
      l1: "No por mucho madrugar,", l2: "amanece más temprano.",
      tr1: "noh por MOO-choh mah-droo-GAR", tr2: "ah-mah-NEH-seh mahs tem-PRAH-noh",
      en: "Rising earlier doesn't make the sun come up sooner." },
    { n: 2, chapterEn: "Action",
      l1: "A quien madruga,", l2: "Dios le ayuda.",
      tr1: "ah KYEN mah-DROO-gah", tr2: "DYOHS leh ah-YOO-dah",
      en: "God helps the one who rises early." },
    { n: 3, chapterEn: "Company",
      l1: "Dime con quién andas,", l2: "y te diré quién eres.",
      tr1: "DEE-meh kohn KYEN AHN-dahs", tr2: "ee teh dee-REH KYEN EH-rehs",
      en: "Tell me who you walk with and I'll tell you who you are." },
    { n: 4, chapterEn: "Prudence",
      l1: "Más vale pájaro en mano", l2: "que cien volando.",
      tr1: "mahs BAH-leh PAH-hah-roh en MAH-noh", tr2: "keh SYEN boh-LAHN-doh",
      en: "A bird in the hand is worth a hundred in flight." },
    { n: 5, chapterEn: "Effort",
      l1: "No hay mal", l2: "que por bien no venga.",
      tr1: "noh eye MAHL", tr2: "keh por BYEN noh BEN-gah",
      en: "There's no bad thing that doesn't come for some good." },
    { n: 6, chapterEn: "Practice",
      l1: "La práctica", l2: "hace al maestro.",
      tr1: "lah PRAHK-tee-kah", tr2: "AH-seh ahl mah-EHS-troh",
      en: "Practice makes the master." },
    { n: 7, chapterEn: "Caution",
      l1: "Ojos que no ven,", l2: "corazón que no siente.",
      tr1: "OH-hohs keh noh BEN", tr2: "koh-rah-SOHN keh noh SYEN-teh",
      en: "Eyes that don't see, a heart that doesn't feel." },
    { n: 8, chapterEn: "Appearances",
      l1: "No es oro", l2: "todo lo que reluce.",
      tr1: "noh ehs OH-roh", tr2: "TOH-doh loh keh rreh-LOO-seh",
      en: "Not all that glitters is gold." },
    { n: 9, chapterEn: "Adaptation",
      l1: "Donde fueres,", l2: "haz lo que vieres.",
      tr1: "DOHN-deh FWEH-rehs", tr2: "ahs loh keh BYEH-rehs",
      en: "Wherever you go, do as you see done." },
    { n: 10, chapterEn: "Persistence",
      l1: "Agua que no has de beber,", l2: "déjala correr.",
      tr1: "AH-gwah keh noh ahs deh beh-BER", tr2: "DEH-hah-lah koh-RRER",
      en: "Water you won't drink — let it run." },
    { n: 11, chapterEn: "Wisdom",
      l1: "Más sabe el diablo por viejo", l2: "que por diablo.",
      tr1: "mahs SAH-beh el DYAH-bloh por BYEH-hoh", tr2: "keh por DYAH-bloh",
      en: "The devil knows more from being old than from being the devil." },
    { n: 12, chapterEn: "Moderation",
      l1: "En boca cerrada", l2: "no entran moscas.",
      tr1: "en BOH-kah ser-RAH-dah", tr2: "noh EN-trahn MOHS-kahs",
      en: "Flies don't get into a closed mouth." },
    { n: 13, chapterEn: "Work",
      l1: "El que algo quiere,", l2: "algo le cuesta.",
      tr1: "el keh AHL-goh KYEH-reh", tr2: "AHL-goh leh KWEHS-tah",
      en: "Whoever wants something has to pay for it." },
    { n: 14, chapterEn: "Family",
      l1: "De tal palo,", l2: "tal astilla.",
      tr1: "deh tahl PAH-loh", tr2: "tahl ahs-TEE-yah",
      en: "From such a stick, such a splinter — like father, like son." },
    { n: 15, chapterEn: "Patience",
      l1: "Roma", l2: "no se construyó en un día.",
      tr1: "RROH-mah", tr2: "noh seh kohns-troo-YOH en oon DEE-ah",
      en: "Rome wasn't built in a day." },
  ].map(p => Object.assign({}, p, { ta: p.l1 + " " + p.l2, tr: p.tr1 + " " + p.tr2 }));

  /* ------------------------------- Register ------------------------------ */
  window.KILI.register("spanish", {
    icons: {
      alphabet: "Alfabeto", greetings: "Saludos", numbers: "Números", colors: "Colores",
      family: "Familia", people: "Gente", pronouns: "Pronombres", questions: "Preguntas",
      grammar: "Enlaces", adjectives: "Adjetivos", adverbs: "Adverbios", verbs: "Verbos",
      food: "Comida", body: "Cuerpo", health: "Salud", clothing: "Ropa", home: "Casa",
      animals: "Animales", nature: "Naturaleza", places: "Lugares", travel: "Viajes",
      time: "Tiempo", work: "Trabajo", school: "Escuela", tech: "Tecnología",
      sentences: "Frases",
    },
    ui: { account: "Cuenta", progress: "Progreso", search: "Buscar" },
    alphabet: ALPHABET,
    alphabetTitle: "Alphabet & sounds",
    alphabetLabels: ["Letters", "Sounds & spelling"],
    vocab: VOCAB,
    sentences: SENTENCES,
    conjugation: CONJUGATION,
    practiceIcons: {
      review: "Repaso", vocab: "Palabras", sentence: "Frases", conjugation: "Verbos",
      listening: "Escuchar", mixed: "Mezcla", reading: "Refranes",
    },
    reading: {
      id: "refranes", title: "Proverbs", native: "Refranes",
      desc: "Classic Spanish sayings, line by line",
      blurb: "Refranes — the proverbs every Spanish speaker grows up hearing.",
      unit: "sayings", numLabel: "Refrán",
      lineQuestion: "Which line completes this saying?",
      items: PROVERBS,
    },
  });
})();
